### ISSUE TITLE
[BUG] whileHover does not register for Wacom tablet

### ISSUE THREAD

**Issue by stahlmanDesign** [framer/motion#1001]
This is sort of an edge case but would be nice to add support if it's just an oversight or not difficult.

**2. Describe the bug**
`whileHover` does not register for the Wacom tablet. It works fine with the trackpad or mouse.

See video

https://user-images.githubusercontent.com/972804/108752876-06ddea80-7512-11eb-8dd5-23acb53c8aaa.mp4

**Comment by mattgperry** [comment]
That’s odd! You’d expect it to fire pointer events given it’s just a mouse. Does it normally fire hover events like CSS selectors? I doubt we’ll be able to do this as we don’t have a Wacom, but would take a PR if it’s a simple fix.

**Comment by stahlmanDesign** [comment]
Yes, it _does_ fire for css hover.

Wacom requires a driver, so I think they probably emulate mouse events, and there's something not quite seamless in the way they do it. Will have to investigate

**Comment by mattgperry** [comment]
That's weird, it must have some odd pointer emulation. Maybe it emulates mouse events but not pointer events? 

I'm going to close this as a `wontfix` for now but if there's a sane and simple fix out there, like I say I would totally accept a PR for this.
