### ISSUE TITLE
[FEATURE] useVelocityTransform 

### ISSUE THREAD

**Issue by djfarly** [framer/motion#1003]
**Is your feature request related to a problem? Please describe.**
I would like to create a new MotionValue based on another MotionValues velocity.
Concrete use case: Apply a skew transform to images on scroll that is stronger the faster the user scrolls. (See condesandbox below)
This seems to doable in user space by targeting `getVelocity()` on the parent MotionValue. The problem is, that there never is a zero velocity call to the useTransform-transformer since the value itself is not changing anymore. Thus in my example if you scroll fast and stop abruptly - the images get stuck in a skewed position.

**Describe the solution you'd like**
An API like this would be great:
```ts
  const { scrollY } = useViewportScroll();
  const skewY = useVelocityTransform(scrollY, (scrollYVelocity) => {
    return scrollYVelocity * 0.00015;
  });
```

As an alternative MotionValues could expose their velocity as a MotionValue directly:
```ts
  const { scrollY } = useViewportScroll();
  const scrollYVelocity = scrollY.velocityMotionValueOrSomething; // 🤨
  const skewY = useTransform(scrollYVelocity, (scrollYVelocity) => {
    return scrollYVelocity * 0.00015;
  });
```

I tried to implement the first API in user space by replicating [the "next-next-frame velocity check" from the MotionValue internals](https://github.com/framer/motion/blob/main/src/value/index.ts#L302-L325). This works, but when setting the velocity to zero, it is quite jumpy. My guess is, that happens because it gains new velocity from being set to zero, thus retriggering the check.

```ts
function useVelocityTransform(
  val: MotionValue<number>,
  transformer: (velocity: number) => number,
) {
  const transformed = useTransform(val, () => transformer(val.getVelocity()));

  const handlePostRender = React.useCallback(() => {
    sync.postRender(handleClearFrame);
  }, []);

  const handleClearFrame = React.useCallback(
    ({ timestamp, delta }) => {
	  // if there has been no update since the last frame, assume velocity 0
      if ((transformed as any).lastUpdated - timestamp + delta !== 0) {
        transformed.set(0);
      }
    },
    [transformed],
  );

  React.useEffect(() =>
    val.onChange(() => {
      sync.postRender(handlePostRender);
    }),
  );

  return transformed;
}
```

Idk if this is very correct. It definitely feels quite hacky. ;)
One way to get rid of the jumpyness – and the way I am using this solution atm is to `useSpring` the resulting transformed value to basically smooth it out.

```ts
  const { scrollY } = useViewportScroll();

  const skewY = useVelocityTransform(scrollY, (scrollYVelocity) => {
    return scrollYVelocity * 0.00015;
  });

  const skewYSpring = useSpring(skewY, { stiffness: 400, damping: 40 });
```

**All in all it would be nice to have a built in way to to something like this.**

**Describe alternatives you've considered**
The user-land solution above seems possible, but quite complicated and brittle.

**Additional context**
See this example on Codesandbox:

https://codesandbox.io/s/flamboyant-framework-qmrey?file=/src/App.tsx

You can play around with these lines to try out the normal vs. the springified value.
```ts
// skewY: skewY // quite jumpy
 skewY: skewYSpring // a bit less jumpy
```

Comment out this line to see the stuck effect:
```ts
sync.postRender(handlePostRender);
```

If I can be of any help, let me know. Tyvm! <3

**Comment by mattgperry** [comment]
I think this is a great idea!
