### ISSUE TITLE
[FEATURE] Fallback to "enter" state when JavaScript is disabled

### ISSUE THREAD

**Issue by samuelgoddard** [framer/motion#1004]
I absolutely love Framer Motion and use it for pretty much all of my animations in either Next or Gatsby for page transitions. One thing i've always thought is dumb is by default, if Javascript is disabled, the "initial" state of the animation is applied to the element and not the "enter" state - in pretty much all of my use cases the "initial" state is generally the element being hidden so when JS is disabled my site is pretty much entirely hidden.

For example, the following code animation:

```
export const fade = {
  initial: { opacity: 0 },
  enter: { 
    opacity: 1,
    transition: { duration: 1, ease: [0.83, 0, 0.17, 1] }
  },
  exit: {
    opacity: 0,
      transition: { duration: 0.75, ease: [0.83, 0, 0.17, 1] }
    }
}
```

in this basic fade example, with javascript disabled any element with this animation applied will render with the following:

```
<div style="opacity:0;"></div>
```

I feel like if JS is disabled Framer either shouldn't touch the DOM or it should be applying the "enter" state as the default to the DOM. Interested to hear other peoples thoughts. Cheers!

**Comment by mattgperry** [comment]
I think this is a great idea but I'm not sure how feasible it'd be to implement. If Motion applied the enter state as default you'd see a very noticeable moment where all the content was visible, before its hidden and animated back in.

The best was IMO would be to have `AnimatePresence initial={false}` so the first page is rendered as normal and only subsequent pages animate in.

**Comment by samuelgoddard** [comment]
Thanks for the reply @mattgperry - That's understandable, I guess for sites that really need a nojs fallback for whatever reason the `initial={false}` method is actually a pretty nice middle ground solution, lose first load animations but gain nojs layouts. I wasn't actually aware of that solution and think it'll work as a nice solution for a project i'm working on so thanks for that!! :)
