### ISSUE TITLE
[QUESTION] How to make to motion component bounce off the wall?

### ISSUE THREAD

**Issue by maurodesouza** [framer/motion#1012]
Hi!

I trying to make a bounce animation but the motion component stay stuck on the constraint limits

```js
const Bounce = () => {
  const containerRef = useRef(null)

  return (
    <Container ref={containerRef}>

      <motion.div
        drag
        dragConstraints={containerRef}
      />
    </Container>
  )
}
```

Result -

![framer-motion](https://user-images.githubusercontent.com/54520907/109703374-27422080-7b74-11eb-8e61-c18e77a2e4a1.gif)

I would like to get this effect, something like a pong game - https://www.ponggame.org

![image](https://user-images.githubusercontent.com/54520907/109703647-77b97e00-7b74-11eb-942f-e2218c9c3bdd.png)

How can i do this?

**Comment by mattgperry** [comment]
Hey there

So ideally you'd be using some kind of physics animation which doesn't exist in Popmotion anymore so you'd either have to roll your own or find one. But the basic approach would be to make `x` and `y` motion values and disable Motion's `dragTransition`:

```jsx
const x = useMotionValue(0)
const y = useMotionValue(0)

return <motion.div drag dragTransition={false} style={{ x, y }} />
```

Then you would want to add an `onDragEnd` listener that triggers a physics animation on the motion values:

```
onDragEnd={() => {
  // psuedo-code
  physics({
    from: x.get(),
    velocity: x.getVelocity(),
    onUpdate: (latest) => {
      if (latest >= 0) {
        x.set(latest)
      } else {
        // start a new physics animation that flips the current velocity,
        // sending the box in the opposite direction
      }
    }
  })
}}
```
