### ISSUE TITLE
[BUG] onTap not firing when using Talkback on Android

### ISSUE THREAD

**Issue by alxsavard** [framer/motion#1019]
## What's going on
Hi!

We've been using framer-motion for a while in our application and we really like it. We recently added VoiceOver and TalkBack support and we noticed something for talkback.

Talkback is the Android screen reader option and usually you select/focus an item (with a single tap), once it's selected you can click it by double-tapping anywhere on the screen (to emit a "click" on the item). All of that works pretty well except in one case. 

We were using the `onTap` event on our button because the `onClick` event did not always work when the button was placed inside of a draggable. This is a trick we pulled a long time ago from this old issue: https://github.com/framer/motion/issues/252

We just not realize that the `onTap` doesn't fire when you do a 'double click' on the Android device that has Talkback enabled. You can double-click and hold to have the event fire, but that is actually a 'right click' in talkback so users would most likely be confused. 

## Expected behaviour
`onTap` should fire when we select the button, then double-click the screen

## Actual behaviour 
`onTap` only fires if you select the button and then double-click and hold

## Steps to reproduce
1. Enable talkback on you Android device
2. Open this sandbox: https://codesandbox.io/s/framer-motion-simple-animation-forked-jpcg1
3. Select the box by tapping it once. It should be outlined 
4. Double-tap anywhere on the screen

No console log is emited. Do the same without talkback and everything works as expected.

I can get a video if you need it, but I'm having some trouble with my screen recorder at the moment.

## Environment
This seems to be specific to Android, the event fire correctly on iOS

**Comment by mattgperry** [comment]
Apologises but this has been the only report on this after a few years so it's unlikely to be fixed.
