### ISSUE TITLE
[FEATURE] Allow disabling inertia animation for `dragTransition` (e.g. `dragTransition={false}`)

### ISSUE THREAD

**Issue by tnunes** [framer/motion#1020]
**Is your feature request related to a problem? Please describe.**
When using drag gestures without elasticity and momentum (`dragElastic={false} dragMomentum={false}`), after releasing the dragged component, it jumps or bounces back before it finally stops.

Depending on the velocity of the drag, it may end up stopping away from the point it was released on.

An example use case that requires this feature is a video progress scrubber, where after dragging the scrubber handle, we want it to stay exactly where it was dropped, without any additional spring movement.

**Describe the solution you'd like**
An option like `dragTransition={false}` that would completely disable the final spring inertia animation after the drag movement ends.

**Describe alternatives you've considered**
Played around with `dragTransition` settings and tried to use a very stiff and damp spring, but couldn't get the final inertia animation that causes the bounce or jump to not happen.

```
dragTransition={{
  bounceStiffness: 1000000,
  bounceDamping: 10000000,
  timeConstant: 0,
  power: 0,
}}
```

**Comment by mattgperry** [comment]
I believe `dragTransition={{ type: false }}` should accomplish this. If you're having troubles please make a new ticket with a CodeSandbox.

**Comment by yanickrochon** [comment]
> I believe `dragTransition={{ type: false }}` should accomplish this. If you're having troubles please make a new ticket with a CodeSandbox.

This is not valid with TypeScript.

**Comment by yanickrochon** [comment]
The solution for this [is](https://www.framer.com/motion/gestures/) :

```jsx
<motion.div
  drag
  dragConstraints={{ left: 0, right: 300 }}
  dragMomentum={false}
/>
```
