### ISSUE TITLE
[FEATURE] layout="size"

### ISSUE THREAD

**Issue by bhollis** [framer/motion#1032]
**Is your feature request related to a problem? Please describe.**
I'm loving the `layout` prop, and I see that it has an option for only animating position, not size. I'd actually like the opposite sometimes, where size animates but position doesn't - sometimes my items lay out in a different place and I'd like them to smoothly animate to their new size (often to reveal or hide some secondary information) but to snap to their new position in the layout instantly. 

**Describe the solution you'd like**
I'd like to be able to specify `layout="size"` and have only the size of my object be animated, rather than size and position. I see that this was brought up in https://github.com/framer/motion/issues/205 before.

**Describe alternatives you've considered**
I don't have another idea for how I could achieve this effect beyond not using layout animation.

**Comment by bulby97** [comment]
Any hacks or any info about this issue ?
I have a tooltip I'd like to resize without having it to move between positions.

**Comment by bhollis** [comment]
I started hacking on it and it seems pretty straightforward, but I haven't tested it out yet.

**Comment by bulby97** [comment]
Nice! Would you be able to show the piece of code please?

**Comment by bhollis** [comment]
Submitted a PR, hope I did it right 🤞
