### ISSUE TITLE
[BUG] Package exports field doesn't provide CJS fallback (can't use in Next.js project)

### ISSUE THREAD

**Issue by vasiliicuhar** [framer/motion#1035]
Looks like recent change to package.json in v3.10.4 breaks Next.js build.
https://github.com/framer/motion/blob/7e22ad1e85c2dd3bd4d760ff814f328bedfe41a4/package.json#L7

It's missing CJS fallback per Node.js documentation
https://nodejs.org/api/packages.html#packages_conditional_exports

I believe correct definition would be following:

```js
{
  "exports": {
     "require": "dist/framer-motion.cjs.js",
     "default": "./dist/es/index.js"
  }
}
```

If you try to upgrade to 3.10.4 on a existing Next.js project, you'd see following build error:
```
SyntaxError: Unexpected token 'export'
```

## Environment details
next@10.0.8
framer-motion@3.10.4

## Workaround

Temporarily downgrade to 3.10.3

**Comment by nghiepit** [comment]
Same issue in my project

>node_modules/framer-motion/dist/es/index.js:1
>export { MotionConfig, MotionConfigContext } from './context/MotionConfigContext.js';
^^^^^^
> SyntaxError: Unexpected token 'export'

But, For now I can't make a reproduction on codesanbox.

**Comment by nathansearles** [comment]
Same issue. After upgrading a Next.js project to v3.10.4 I'm seeing following build error:

`SyntaxError: Unexpected token 'export'`

## Environment details

next@10.0.8
framer-motion@3.10.4

## Workaround

Temporarily downgrade to 3.10.3

**Comment by vasiliicuhar** [comment]
@nathansearles because it happens only during pre-rendering. 

I could create minimal reproducible example Tomorrow, if needed. But the issue is in the exports field

**Comment by nathansearles** [comment]
> @nathansearles because it happens only during pre-rendering.
> 
> I could create minimal reproducible example Tomorrow, if needed. But the issue is in the exports field

All good. Thanks for the detailed report! Good to know the issue is within the Framer Motion exports and not a project level issue.

**Comment by mattgperry** [comment]
@vasiliicuhar Thanks for the suggestion on how to fix this! Can someone encountering this try `3.10.5-rc.0`

**Comment by KyleBurger** [comment]
Verified this is working for me w/ `3.10.5-rc.0` 👍

**Comment by nathansearles** [comment]
Confirming `3.10.5-rc.0` fixes this issue. Thanks @mattgperry!
