### ISSUE TITLE
framer-motion  3.10.2  →  3.10.4 NextJS[BUG]

### ISSUE THREAD

**Issue by neosa** [framer/motion#1036]
SyntaxError: Unexpected token 'export'
external%20%22framer-motion%22 (1:0) @ eval

module.exports = require("framer-motion");

**Comment by prathameshkoshti** [comment]
I'm also facing same issue. Initially thought it's something related to next.js because next package also received an update today. But then I changed the version of framer-motion in package.json to earlier version:
```
"dependencies": {
  ...
  "framer-motion": "3.10.3",
  ...
}

So if you are facing this issue, for time being you can update the version.

**Comment by Mzaien** [comment]
I got a smilier issue related to one export 
```
framer-motion/dist/es/index.js:1
export { MotionConfig, MotionConfigContext } from './context/MotionConfigContext.js';
SyntaxError: Unexpected token 'export'
```

**Comment by johnfrades** [comment]
> 3.10.3

Thanks, i'm also experiencing this problem. Downgrading to 3.10.3 solves it
