### ISSUE TITLE
[BUG] Carrousel Animation broken from 2.5  

### ISSUE THREAD

**Issue by alex83130** [framer/motion#1038]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

On a few of my websites I use a good-looking Carousel Component founded on Codesandox  (Wasn't created by myself) and which is based on Framer Motion.
As you can see on the codesandox everything work well until the version 2.4 included, but from 2.5 the carousel is broken. 
Do you have a clue about any Framer Motion's breaking changes which could cause the issue on the Component ?

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/motion-page-ts-brz9n

**4. Steps to reproduce**

1. Change the Framer Motion version at 2.4
2.  Play with the Carousel (Everything should work well)

3. Change the Framer Motion version at 2.5
4.  Play with the Carousel (The carousel doesn't work as expected)

**5. Expected behavior**

I would like the carousel working with the higher possible version of Framer Motion

**Comment by rafaelderolez** [comment]
@alex83130 It works if you comment out `transition={transition}` in `src/components/Page.tsx` line 381. I think the transition api changed over time it doesn't play nice with the old config.
