### ISSUE TITLE
[BUG] Stagger animations do not call onAnimationStart on children

### ISSUE THREAD

**Issue by BrunoQuaresma** [framer/motion#1042]
Hi folks, I noticed the children elements of stagger animations are not calling `onAnimationStart`. 

Here is the link to the sandbox: https://codesandbox.io/s/framer-motion-side-menu-forked-prlys?file=/src/MenuItem.tsx

Is there another way to know when a child element started the animation?

Thanks.

**Comment by iibarbari** [comment]
i am also facing this issue :(

**Comment by controversial** [comment]
Looks to me like onUpdate still fires - you could judge when the animation has started based on when onUpdate is first called

**Comment by adamatronix** [comment]
I'm still facing this issue. Anyone else?
