### ISSUE TITLE
[FEATURE] Use framer-motion in a non-HTML context

### ISSUE THREAD

**Issue by ThomasRutzer** [framer/motion#1044]
Hi, 

maybe I've overlooked something. But in general, is it possible to use framer-motion in another context than HTML, e.g. Canvas/WebGL? 

As far as I understand, you need to have `motion` components to make it work, which are only available for HTML elements. But I am building a React App which includes 2D HTML together with [react-three-fiber](https://github.com/pmndrs/react-three-fiber) and would like to have one animation library for both contexts. [React-spring](https://github.com/pmndrs/react-spring) offers that, but I don't need spring-based animations. 

Maybe this can be achieved with a combination of `useMotionValue` + `useTransform` and I just don't get it yet?

Thanks a lot for your help!

**Comment by mattgperry** [comment]
I'm not sure if `MotionValue` is compatible with `react-three-fiber` - if it were then `useMotionValue` could be used with `animate`. 

We have done some work on a version that is explicitly compatible with `react-three-fiber` but it's more of a hackathon project at the moment, hopefully we'll find more time to work on it soon.

**Comment by ThomasRutzer** [comment]
Hi @mattgperry thanks for your quick answer! I think I'll wait then for an officially compatible version - hope you and your team can find time to work on that, could be worth it for a lot of people using React for hybrid-apps of HTML + WebGL.

Since this is more of a general question, I'll close the issue now.

**Comment by n1xx1** [comment]
I love using AnimateLayout and AnimateSharedLayout, and having them in react-three-fiber would be a godsent. Hopefully you will have time to work on that on the near feature, after using framer-motion, react-spring feels a bit cumbersome.
