### ISSUE TITLE
[BUG] Custom motion component doesn't animate with merged ref

### ISSUE THREAD

**Issue by stvnwn** [framer/motion#1046]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

I have a function component that uses state and a local ref. I want to convert the component into a `motion` component. In preparation, I pass the component into `React.forwardRef()` and use [`react-merge-refs`](https://github.com/gregberge/react-merge-refs) to merge the local ref and the ref originating from `React.forwardRef()`. Then I convert the component with motion(_component_).

For some reason, modifications to the `motion` component's state will prevent it from animating (at least on mount).

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[https://codesandbox.io/s/magical-cartwright-heqbx](https://codesandbox.io/s/magical-cartwright-heqbx)

**4. Steps to reproduce**

1. Load the CodeSandbox

**5. Expected behavior**

On mount, the Square component's opacity should animate from 0 to 0.5. Note that the Square component will behave as intended if one prevents it from modifying its state.

**Comment by adibfirman** [comment]
Hi @stvnwn 
I just curious, why you use 2 refs instead of one? don't you should with one ref? like check with ternary like this
`ref ? ref : localRef`

**Comment by mattgperry** [comment]
I'd more likely expect this to work with 

```javascript
const mergedRefs = useMemo(() => mergeRefs([localRef, ref]))
```

But even so, it doesn't.

**Comment by mattgperry** [comment]
Fixed in the meantime

**Comment by jdnichollsc** [comment]
@mattgperry I tried using the below props but it's not working:
```
layout="position"
layoutId="avatar"
```

do you know why? <3

Thanks for your help!
