### ISSUE TITLE
[BUG] Next.js: framerMotion.motion.custom is not a function

### ISSUE THREAD

**Issue by kaizendevar** [framer/motion#1047]
New version Bug. When run the project I got a 500 error due to the new version. While the previous version was working: 3.10.5

**Comment by mattgperry** [comment]
Ah yeah this was deprecated in 3, now you can use `motion()` instead. If you relied on the old default behaviour of forwarding Motion's props to children you can do `motion(Component, { forwardMotionProps: true })`
