### ISSUE TITLE
[BUG] useViewportScroll initially not updating

### ISSUE THREAD

**Issue by MatixYo** [framer/motion#1049]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

Give a clear and concise description of what the bug is.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

**4. Steps to reproduce**

1. Go to https://codesandbox.io/s/misty-dew-g6019?file=/src/App.js
3. Copy the code and run it in local react App because on CodeSandbox on every refresh scroll position is reset
2. Run app and scroll 200 px down then refresh.
3. See error: after refresh window is scrolled down 200 px but opacity is at 0 as if it was not scrolled.

**5. Expected behavior**

After refresh it should update opacity value with current scroll position (200 px => 1 in that case).

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

**7. Environment details**

If applicable, let us know which OS, browser, browser version etc you're using.

Chrome 89

**Comment by Setuini** [comment]
I currently have the same issue as described.
Seems to be a problem with useTransfrom.
My scrollY value is the correct scroll position (before and after the refresh), but my useTransfrom value is 0 after the refresh.

```
const { scrollY } = useViewportScroll();
const scrollY2 = useTransform(scrollY, value => value * 2);
```

**Comment by mattgperry** [comment]
This doesn't seem to be broken in the latest versions of Motion.
