### ISSUE TITLE
[BUG] 4.0.0 onLayoutAnimationComplete works strangely on mobile.

### ISSUE THREAD

**Issue by ivanburlakov** [framer/motion#1051]
I am experiencing a very strange bug in my project. After updating to `4.0.0` my `onLayoutAnimationComplete` is firing both on start of animation and on complete. But only on mobile device (Android Chrome, Firefox).

I was trying to replicate with simplified setup in sandbox and there it fires once, but, even a stranger thing is happening, the circle is not animating at all on mobile, while on PC it works just fine: https://codesandbox.io/s/framer-motion-2-animatesharedlayout-animate-between-different-components-forked-72dd2.

You can see the full code of my component here: https://gist.github.com/ivanburlakov/fa1697a971b301f6642f97851cd62eb0 . Also, for some reason it fires 2 times after the animation, even though I use `onLayoutAnimationComplete` just once in my code, but that was happening even before `4.0.0`.

**Comment by lukasz-fiuk** [comment]
I have the same issue on chrome, macos

**Comment by mattgperry** [comment]
No longer seems to be an issue.
