### ISSUE TITLE
[BUG] LazyMotion features with dynamic import cause shared layout animations to fire once.

### ISSUE THREAD

**Issue by haydencleary** [framer/motion#1056]
**1. Read the FAQs**
👍

**2. Describe the bug**

With the LazyMotion component in 4.0.0 the dynamic import of Framer features causes shared layout animations to only fire once.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[https://codesandbox.io/s/framer-motion-dynamic-issue-5qrbz](https://codesandbox.io/s/framer-motion-dynamic-issue-5qrbz)

**4. Steps to reproduce**

Change pages between home and about to see the red bar animate.
- If the features are imported dynamically the red bar will transition on the first page change, and the other times it will just appear in its final location.
- If the features are imported statically the red bar will transition on each page change as expected.

**5. Expected behavior**

Shared layout animations should have consistant behaviour if the features are imported statically or dynamically using the LazyMotion component.

---

Thanks for your work on this library and banging out the latest releases so fast, it's awesome! 🤘

**Comment by mattgperry** [comment]
Fixed in 5
