### ISSUE TITLE
[QUESTION] Trigger scroll when visible in viewport

### ISSUE THREAD

**Issue by thierryteyssier** [framer/motion#1072]
I do not find a solution to start a "scroll" once the element is visible in the viewport like it is done on https://www.framer.com/motion/ in the "scroll" card.

I use react-intersection-observer but I do not know how I can "link" it with useViewportScroll.

Thanks!

**Comment by bernardojb** [comment]
Heyy, have you managed to solve the problem using react-intersection-observer?
