### ISSUE TITLE
[BUG] Funky stuff with relative layout projection in 4.1.x

### ISSUE THREAD

**Issue by rijk** [framer/motion#1083]
No Sandbox yet, but am seeing some very weird behaviour in my app after updating to 4.1.2.

<details>
<summary>Origin for modal open transition incorrect after open/closing sidebar:</summary>

https://user-images.githubusercontent.com/159500/113304094-fb949080-9301-11eb-830c-ac082849a2ed.mov
</details>

---

In the video above, you can also see the items seem to have shifted too far to the left. 

<details>
<summary>This also happens in my in-modal sidebar:</summary>

![image](https://user-images.githubusercontent.com/159500/113304426-50380b80-9302-11eb-9bb0-b35614094c72.png)

The highlighted element should be in the sidebar on the right. When I collapse the sidebar you see the content jump back to its right position for one frame:

https://user-images.githubusercontent.com/159500/113304783-a60cb380-9302-11eb-8ab1-265f6cb36cc6.mov
</details>

---

<details>
<summary>Thumbnails don't animate back to their position:</summary>

https://user-images.githubusercontent.com/159500/113305287-27fcdc80-9303-11eb-9998-19e1fa6f3ddf.mov

They always go to the top left corner..
</details>

**Comment by mattgperry** [comment]
Are you also seeing this in `4.1.1`/`4.1.0` ?

**Comment by rijk** [comment]
Hm, `4.1.0` seems to be an even bigger mess :)

https://user-images.githubusercontent.com/159500/113306304-3d263b00-9304-11eb-8bde-656d043b9e00.mov

There's probably an issue in my code. I'll do some more digging and update you.

**Comment by rijk** [comment]
Nope, it doesn't seem to be the code; it started in `4.1.0`. With no other changes, here's the same interactions on `4.0.3` (all working as intended):


https://user-images.githubusercontent.com/159500/113307739-c1c58900-9305-11eb-84ec-963afae0d16a.mov

**Comment by rijk** [comment]
I have a feeling performance is worse as well, I'm seeing more dropped frames compared to 4.0.3.

**Comment by mattgperry** [comment]
That should be unlikely as fewer animations should run in general as many were wasted before. But worth looking into

**Comment by rijk** [comment]
Here's a reproduction Sandbox: https://v2gnm.csb.app

1. Open/close a modal, note correct layout animation
2. Open Menu
3. Open/close modal, layout animation from incorrect starting point
4. Close Menu
5. Open/close modal, layout animation from incorrect starting point

https://user-images.githubusercontent.com/159500/113402944-29cbac00-93a6-11eb-99e1-5f7116548e30.mov

Interesting to note is that when uncommenting the `useEffect` in `Modal.tsx` (that triggers a state update every second), the layout animation seems to be stuck in a loop:


https://user-images.githubusercontent.com/159500/113403101-6ac3c080-93a6-11eb-96b1-f773f12ab3c9.mov

**Comment by rijk** [comment]
This seems to be fixed with #1096.
