### ISSUE TITLE
Use element dimension in AnimatePresence

### ISSUE THREAD

**Issue by marcselman** [framer/motion#1086]
Hi,
I have made a sort of dropdown component. I'm using `AnimatePresence` to animate the dropdown when the header is clicked.
The dropdown has `position: absolute` and because the header has `position: relative` this works very well. The dropdown appears nicely below the header but the left sides are aligned. I want the dropdown to be centered below the header element.
If the dropdown width was fixed to, for example, 400px I would do something like `margin-left: -200px`.
But in this case the element does not have a fixed width.
I know that Framer Motion handles `auto` values so I assume it stores the calculated dimensions somewhere.
Can I use the calculated dimensions somehow in the css styles of the `motion.div`?

**Comment by rijk** [comment]
Without a Sandbox it's unlikely people will be able to help you here. Maybe you can try something like this;

```css
  .dropdown {
    position: absolute;
    left: 50%;
    transform: translateX( -50% );
  }
```

This is a common technique for centering absolutely positioned elements of which you don't know the size.

**Comment by mattgperry** [comment]
There is a prop called `onLayoutMeasure` which gets called with the measured box but it only fires when a component is doing layout animations. But otherwise this sounds a bit like https://github.com/framer/motion/issues/296
