### ISSUE TITLE
[BUG] visibility hidden does not animate

### ISSUE THREAD

**Issue by danielo515** [framer/motion#1091]
**2. Describe the bug**

If I add visibility hidden to one of the variants, that variant does not animate

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

I am using this codesandbox for another report, but this problem is appearing there

https://codesandbox.io/s/framer-controls-promises-not-fulfilling-luqyq?file=/src/Example.jsx

**4. Steps to reproduce**

1. Go to the sandbox
2. Use the ESC key to toggle the content
3. Check that it animates in but not out
4. You can remove the visibility hidden and it will animate

**5. Expected behavior**

I expect the visibility hidden to be added at the end, when animation finishes

**6. Video or screenshots**

Nope

**7. Environment details**

```
  System:
    OS: macOS 11.1
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
  npmPackages:
    react: ^16.14.4
    react-dom: ^16.14.4
    framer-motion: 4.1.3
```

**Comment by rijk** [comment]
Are you sure you need `visiblity: hidden`? It will have the same effect as turning the opacity to 0. If I remove this rule it does animate: https://codesandbox.io/s/framer-controls-promises-not-fulfilling-forked-2xmpl

Alternatively, maybe the [`transitionEnd`](https://www.framer.com/api/motion/types/#targetandtransition) property could be useful to you. I've used this for things like setting `overflow: 'visible'` to enable scrolling inside the element once the animation is finished.

**Comment by danielo515** [comment]
Hello @rijk , thanks for your answer.

> Are you sure you need visiblity: hidden?

Yes, I need it for several use-cases. For example when I want to remove the node from the page flow and remove all it's event handlers (clicks, over, etc)
`transtitionEnd` looks like a legit way of doing it, because visibility is not anything you animate, but something you want to target.
Thanks
