### ISSUE TITLE
[BUG] backgroundPosition is not animated when transformed value changes

### ISSUE THREAD

**Issue by JohannesKlauss** [framer/motion#1092]
**2. Describe the bug**

The properties `backgroundPositionX` and `backgroundPositionY` aren't animated when using useTransform. The initial value is set, but the prop never gets updated when the motion value or transform result changes.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/morning-glade-d87z4?file=/src/App.js

**4. Steps to reproduce**

1. Open the sandbox
2. Drag the div with the background image on its x axis.
3. Background image position doesn't change.

**5. Expected behavior**

The CSS properties should be updated accordingly.

In case of the sandbox the background image should stay put to create the illusion that the div would act as a window that is draggable over the positional static background image.

**Comment by mattgperry** [comment]
```
  const negativeX = useTransform(x, (x) => -x + "px");
```

Nice effect btw
