### ISSUE TITLE
[FEATURE] motionValues maintain last value after animate stop

### ISSUE THREAD

**Issue by jedierikb** [framer/motion#1093]
https://codesandbox.io/s/animate-resets-motionvalue-nnk34?file=/src/App.tsx

In a ```useEffect```, we use [animate](https://www.framer.com/api/motion/utilities/#animate) utility to tween a ```motionValue```.

When this ```useEffect``` is called multiple times, the motionValue is reverted each time to its original constructor value before beginning its animation to its new target.  I would have expected the ```motionValue``` to maintain its last value.

Is it possible to add a feature for a ```motionValue``` to maintain its last animated-to value for subsequent calls to re-start ```animate```?

**Comment by jedierikb** [comment]
Here is my solution to recall the last set motionValue between calls to restart animate in useEffect:
https://codesandbox.io/s/animate-resets-motionvalue-forked-um7ec?file=/src/App.tsx

**Comment by mattgperry** [comment]
It should be useMotionValue not new MotionValue. This is making a new
motion value every render hence why the animation starts from the initial
value each time

Op za 10 apr. 2021 om 16:29 schreef Erik Blankinship <
***@***.***>

**Comment by jedierikb** [comment]
:-P
