### ISSUE TITLE
[BUG] motionValue sometimes set to NaN via animate utility

### ISSUE THREAD

**Issue by jedierikb** [framer/motion#1094]
Sometimes when resetting an animate on a motionValue, the motionValue becomes NaN.

In this codepen, click to reset the target of the animation a few times and the motion value becomes set to NaN.
https://codesandbox.io/s/animate-results-in-nan-um7ec?file=/src/App.tsx

The motion value should never be set to NaN.

**Comment by jedierikb** [comment]
Here is a video
https://photos.app.goo.gl/NYTusgmh347JnXik8

**Comment by jedierikb** [comment]
NaN happens when the animate object has the `duration` parameter and does not seem to happen when `duration` is omitted.

https://codesandbox.io/s/animate-results-in-nan-forked-0xlq6?file=/src/App.tsx:405-426

**Comment by jedierikb** [comment]
Poking about in framer-motion source, I see my calls go to popmotion via
https://github.com/framer/motion/blob/e8e7906d82de61233b870ac3db51cbaaaa0a9efb/src/animation/utils/transitions.ts#L198

but grabbing some parameters which cause the bug and feeding them into popmotion directly does not cause onUpdate to go NaN:
https://codesandbox.io/s/animate-results-in-nan-forked-nopfx?file=/src/App.tsx

Not sure off the top of my head the next best path to debug this...

**Comment by jedierikb** [comment]
Dug into popmotion a bit to trace this.  

It seems that sometimes when a derived Velocity is added to a settings object, tween updates return NaN.

Here is a contrived example with a known errant velocity and duration:
https://codesandbox.io/s/animate-results-in-nan-um7ec?file=/src/App.tsx

Here are my rough notes from tracing in popMotion:
```
in createSpring, if damping == 0 and stiffness == 0, then
dampingRatio is NaN
and then dampedAngularFreq_1 is NaN
and then ResolveSpring returns NaN
```

Let me know if I should open a ticket in popmotion.  Thank you for help in debuggng this.

**Comment by mattgperry** [comment]
Thanks for the popmotion ticket! I'll close this one so it's just tracked in one place.
