### ISSUE TITLE
[BUG] MotionValue velocity reports extra 0 values for viewport scroll

### ISSUE THREAD

**Issue by djfarly** [framer/motion#1097]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

MotionValue Velocity updates seem to fire twice per frame, when using scrolling as input. One time with a value of `0`, one time with the correct velocity.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-310-usevelocity-forked-05q9q?fontsize=14&hidenavigation=1&theme=dark

*Note*: The code in the hook is super messy. I stumbled upon this when trying to utilize `onChange` on the velocity motion value itself. (I was trying to figure out when scrolling stopped -> velocity = 0 - the bug makes that impossible).
The framesync stuff was added just to see why the zero values weren't "commited". (Probably because another correct value comes in during the same frame).

My best guess is that there is a double `notify()` call within motion value [here](https://github.com/framer/motion/blob/main/src/value/index.ts#L271) and [here](https://github.com/framer/motion/blob/main/src/value/index.ts#L339). But I might be totally wrong here. :D

**4. Steps to reproduce**

1. go to sandbox above
2. scroll the viewport and check the console output
4. See multiple logged values (`0` and the actual value) per frame.

**5. Expected behavior**

It should report velocity without changing to 0 within the same frame.

**6. Video or screenshots**

see code sandbox

**7. Environment details**

should not matter

tyvm for looking into this <3

**Comment by perrysmotors** [comment]
@mattgperry I'm seeing the same issue.

**Comment by mattgperry** [comment]
```
export function useScrollVelocity() {
  const { scrollY } = useViewportScroll();

  useVelocity(scrollY).on("change", console.log)
}

```

This seems to work as expected

**Comment by perrysmotors** [comment]
Just checked, and is working fine for me now. Thanks :)
