### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by javusScriptus** [framer/motion#1098]
I'm wondering if there is and option to pass values like the length of the container into `const input` array, so that the animation could be more flexible : 
```
const x = useMotionValue(0)
const input = [-200, 0, 200]
const output = [0, 1, 0]
const opacity = useTransform(x, input, output)
```

so I want to be able to do something like this: ```const input = [-wrapperWidth.current, 0, wrapperWidth.current]```

**Comment by souldreamer** [comment]
One solution is to normalize the initial motion value by dividing it by your reference value:

```typescript
const x = useMotionValue(0);
const normalized = useTransform(x, x => wrapperWidth.current ? x / wrapperWidth.current : 0);
const input = [-1, 0, 1];
const output = [0, 1, 0];
const opacity = useTransform(x, input, output);
```

**Comment by javusScriptus** [comment]
Thank you!
