### ISSUE TITLE
[BUG] 'Complex values too different to mix' but the values are identical

### ISSUE THREAD

**Issue by rokobekavac0** [framer/motion#1099]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

This is my animate object 
```jsx
animate={{
          WebkitMask: show
            ? "linear-gradient(0deg, #000000ff, #00000000, #00000000, #0000009e, #000000ff, #000000ff, #000000ff, #00000033)"
            : "linear-gradient(0deg, #00000000, #000000ff, #000000ff, #000000ff, #000000ff, #000000ff, #000000ff, #00000000)"
}}
```
I expect it to animate between those 2 gradients but I'm getting the following error: 
```
Complex values 'linear-gradient(0deg, rgba(0, 0, 0, 1)0, rgba(0, 0, 0, 1)ff, rgba(0, 0, 0, 1)ff, rgba(0, 0, 0, 1)ff, rgba(0, 0, 0, 1)ff, rgba(0, 0, 0, 1)ff, rgba(0, 0, 0, 1)ff, rgba(0, 0, 0, 1)0)' and 'linear-gradient(0deg, #000000ff, #00000000, #00000000, #0000009e, #000000ff, #000000ff, #000000ff, #00000033)' too different to mix. Ensure all colors are of the same type.
```
Looks like framer-motion converted initial values to `rgba`.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-bug-cnrhc

**4. Steps to reproduce**

Just click on a div.

**5. Expected behavior**
Animation between 2 masks.

### `AnimatePresence` isn't working

Have all of its immediate children got a unique `key` prop that **remains the same for that component every render**?

```jsx
// Bad: The index could be given to a different component if the order of items changes
<AnimatePresence>
  {items.map((item, index) => <Component key={index} />)}
</AnimatePresence>
```

```jsx 
// Good: The item ID is unique to each component
<AnimatePresence>
  {items.map((item, index) => <Component key={item.id} />)}
</AnimatePresence>
```

Is the `AnimatePresence` correctly outside of the controlling conditional? `AnimatePresence` must be rendered whenever you expect an `exit` animation to run - it can't do so if it's unmounted!

```jsx
// Bad: AnimatePresence is unmounted - exit animations won't run
{isVisible && (
  <AnimatePresence>
    <Component />
  </AnimatePresence>
)}
```

```jsx
// Good: Only the children are unmounted - exit animations will run
<AnimatePresence>
  {isVisible && <Component />}
</AnimatePresence>
```

**Comment by rokobekavac0** [comment]
UPDATE:
It appears that hex values with opacity (#000000ff) are causing this problem. [Demo](https://codesandbox.io/s/framer-motion-bug-forked-dzk0k?file=/src/App.js) works when I replace hex with rgba values.

**Comment by mattgperry** [comment]
Closing as this was fixed in the meantime - but yeah looks like this was before we supported Hex & opacity
