### ISSUE TITLE
[BUG] staggerChildren doesn't work with display: contents

### ISSUE THREAD

**Issue by markspolakovs** [framer/motion#1102]
**Describe the bug**

When using `staggerChildren` and variants with a child that has a `display: contents` style, staggering doesn't happen.

**Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/fm-display-contents-repro-fgj12

**Steps to reproduce**

1. Click "Show" and watch the three list items animate in staggered.
2. In the drop-down, change display from "block" to "contents"
3. Click "show" again, and watch them animate in simultaneously

**Expected behavior**

`staggerChildren` to properly stagger children that have `display: contents`. Alternatively, the fact that it cannot should be documented somewhere.

**Video or screenshots**

https://user-images.githubusercontent.com/2904440/115231188-2dcd2d00-a10d-11eb-957a-0abde1daf8af.mp4

(the screen flickering is not part of the issue)

**Environment details**

Arch Linux 5.11.11-arch1-1, Chrome 89.0.4389.114 (Official Build) (64-bit)

**Comment by KirdesMF** [comment]
I'm not that its really related to framer-motion but more of a CSS "issue".

**Comment by mattgperry** [comment]
You can't style `display: contents` elements. It's not that `staggerChildren` is incompatible with it, it's more that the container is fading in and out giving the illusion that the fade also happening on the children is still happening, but it isn't.
