### ISSUE TITLE
[BUG] Variants with transition duration 0 break in macOS Safari

### ISSUE THREAD

**Issue by Regaddi** [framer/motion#1104]
**2. Describe the bug**

When switching between variants, where all variants have `transition.duration: 0` set (essentially disabling animation), the UI will get stuck in one of the states.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/cool-sky-d9lhy?file=/src/App.js

**4. Steps to reproduce**

1. Go to https://codesandbox.io/s/cool-sky-d9lhy?file=/src/App.js
2. Click on `toggle`
3. Click on `toggle` again

**5. Expected behavior**

The drawn line re-appears.

**6. Video or screenshots**

![CleanShot 2021-04-19 at 16 34 15](https://user-images.githubusercontent.com/1336590/115254005-3c2b4100-a12d-11eb-95ae-57feeaaa4661.gif)

**7. Environment details**

OS: macOS Big Sur 11.2.3 (20D91)
Browser: Safari 14.0.3 (16610.4.3.1.7)

**Comment by mattgperry** [comment]
Seems to be fixed in Safari 15
