### ISSUE TITLE
[FEATURE] Is it possible to animate properties with CSS transitions instead of JavaScript?

### ISSUE THREAD

**Issue by anatolzak** [framer/motion#1105]
**Is your feature request related to a problem? Please describe.**
I have noticed that when using motion and animating properties, it slows down slower devices and sometimes animations run slower than they should be. My guess is that it is because framer motion updates the css property value constantly till it reaches the desired value.

For example with opacity, animating from 0 to 1 will look like this: 
```css
opacity: 0;
opacity: 0.001;
opacity: 0.004;
opacity: 0.008;
.....
opacity: 1;
```

And when animating multiple elements at the same time, the device slows down even more sometimes.

**Describe the solution you'd like**
Instead, what would be great is if we could animate CSS properties by using CSS transitions like this:

```css
opacity: 0;
```
```css
opacity: 1;
transition: opacity .3s;
```

**Describe alternatives you've considered**
I love framer motion and everything it enables you to do without writing much code. Unfortunately, I have had to not to use framer motion since it wasn't performant and instead had to implement animations with React Transition Group. But there were animations that I haven't been able to re-implement on my own.

I would love to be able to use framer motion and have it be performing super fast the way CSS transitions do.

I really appreciate all your work so much and would love to hear your feedback!

**Comment by rijk** [comment]
https://css-tricks.com/myth-busting-css-animations-vs-javascript/
