### ISSUE TITLE
[FEATURE] Allow single axis layout animations

### ISSUE THREAD

**Issue by bvangraafeiland** [framer/motion#1112]
**Is your feature request related to a problem? Please describe.**
When using the `layout` prop, layout changes will cause the element to be animated to its new position like intended. However, when there is a content shift, parents of the animated elements will not be animated, causing a lagging effect as the child "catches up". See [this CodeSandbox](https://codesandbox.io/s/framer-motion-2-layout-animations-forked-h147x?file=/src/App.js) for a demonstration.

**Describe the solution you'd like**
This could be solved by allowing to select a single axis to animate, like we can do with the `drag` prop. In the case of this CodeSandbox for example, the `y` value of the translate would be disabled. Then when the content shifts, only the `x` coordinate will animate, causing the dot to stay within the button.

**Describe alternatives you've considered**
A possible alternative in this case would be to first animate the dot when clicking, and passing `toggleSwitch` to `onLayoutAnimationComplete`. However, if the content shift is caused by something outside of this component (like having multiple toggles below each other), this won't work.

**Comment by rijk** [comment]
I've [run into this issue as well](https://github.com/framer/motion/issues/1027#issuecomment-801426832) and came up with an alternative possible solution: #1027 .

**Comment by bvangraafeiland** [comment]
Ah yes, that makes sense. I saw your proposal before but didn't realize it included the same issue. Such a boundary sounds more complicated to implement though...

**Comment by irg1008** [comment]
Any solution in this??, I am facing the same issue. I have a fixed navbar with a toggle inside that shifts on route change.

**Comment by mattgperry** [comment]
Sorry this isn't the nicest API right now but I made it mostly for internal Framer use.

If you make the switch container a `motion.div` and add `layout layoutRoot` props it will work as you're expecting: https://codesandbox.io/s/framer-motion-2-layout-animations-forked-gc4ckn?file=/src/App.js
