### ISSUE TITLE
[FEATURE] add gsap ScrollTrigger like functionality

### ISSUE THREAD

**Issue by violabg** [framer/motion#1121]
I love this library but it would be great if it could have some additional features in order to help with triggering animations on scroll. Something similar to gsap ScrollTrigger plugin.
https://greensock.com/docs/v3/Plugins/ScrollTrigger

**Comment by mattgperry** [comment]
I agree! I don't know when it'll be but there's more we can do in this area for sure.

**Comment by mattgperry** [comment]
`whileInView` should provide the scroll triggering stuff here

**Comment by jdnichollsc** [comment]
@mattgperry can we change the duration of the transition while the component is not in view? I don't see any example in the website so I'm not sure if that's possible. 
I added transition config to the initial state but it's not working.

Thanks for your help!
