### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by UtshoBarua** [framer/motion#1122]
i don't know why i am having this issue in react if i am using as it says in the documentation like this
<motion.h1 animate={{fontSize:80, x:100px,y:500px}} >this is header</motion.h1>
these are not working but if i am using it like this in react 
<motion.h1 animate={{fontSize:'80px', x:'100px',y:'500px'}} >this is header</motion.h1> 
then its working fine but there also delay not working

**Comment by mattgperry** [comment]
Feel free to reopen with a sandbox
