### ISSUE TITLE
[BUG] framer-motion breaks in tslib version 2.2.0

### ISSUE THREAD

**Issue by omofolarin** [framer/motion#1123]
export '__spreadArray' was not found in 'tslib'  

On tslib version 2.2.0

node_modules/framer-motion/dist/es/components/AnimatePresence/index.js 123:27-40

**Comment by mattgperry** [comment]
This should be fixed in 5

**Comment by chimson** [comment]
I know this is closed and should be fixed in 5, but I'm using ```^5.2.0``` and the issue persists in tests, might be an issue with ```jest```

**Comment by mattgperry** [comment]
There's an issue about this in tslib https://github.com/microsoft/tslib/issues/149 so I'm going to reclose this. I've attempted to update tslib but have run into other issues 🙄 but I'll keep an eye on that issue. Pinning seems to be the only way from now.
