### ISSUE TITLE
[FEATURE] Request animation frame

### ISSUE THREAD

**Issue by javusScriptus** [framer/motion#1126]
Is there an option to somehow connect framer motion with the `request animation frame` loop? I need to update some elements in THREE.js with the MotionValues from framer motion and want to use the same render loop for both of them.

**Comment by mattgperry** [comment]
Is it possible to use your own render loop for Three.js? If so it would be possible to create this with [Framesync](https://github.com/Popmotion/popmotion/tree/master/packages/framesync), which is what Framer Motion uses.

```
sync.update(() => {
  updateThree()
}, true)
```

**Comment by javusScriptus** [comment]
@mattgperry I tried putting all my THREE.js update functions in multiple `sync.update(()=>{ ... },true)`, but It does not work. Should I also change something in framer-motion layer of the app? The way It works now is that I pass MotionValues named `offsetY`, which is a spring value, and then use it as `offsetY.get()` in THREE to update the three elements.

**Comment by mattgperry** [comment]
Ah ok. It should probably be `sync.render` then. Whereever you have this (from the Three docs):

```javascript
function animate() {
	requestAnimationFrame( animate );
	renderer.render( scene, camera );
}
animate();
```

You should have:

```javascript
sync.render(() => {
  renderer.render( scene, camera );
}, true);
```

**Comment by javusScriptus** [comment]
Still the same. Maybe the problem is that I read `offsetY` value with `.get()`, while the motion elements receive it instantly?

**Comment by mattgperry** [comment]
When you say it's not working, what exactly do you mean? That there's a frame lag or things just don't move? Have you logged out what offsetY.get() returns?

**Comment by javusScriptus** [comment]
I mean that there is a lag between the images and page offset, while they both use `offsetY`, but THREE.js uses `offsetY.get()`.
`offsetY.get()` returns proper values while I console.log them in sync.render loop

**Comment by javusScriptus** [comment]
In this case I had to eventually not use framer motion, and move all the DOM elements manipulations in to THREE.js request animation function. Thanks @mattgperry for the idea anyways, It was on point, however there were some issues with syncing the animations.
