### ISSUE TITLE
[BUG] useTransform introduces jank to a spring motionvalue

### ISSUE THREAD

**Issue by tarngerine** [framer/motion#1129]
**2. Describe the bug**
When a spring motion value is transformed by a useTransform, it introduces a little jank/jump at the very end of the animation curve.

To be clear, the issue isn't that these animation curves aren't 100% in sync, it's that when the useTransform animation is used by itself, the animation does not look smooth. 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/funny-rubin-ic1j9?file=/src/App.js
See the top red box compared to the bottom red box, at the very end of the animation, the top red box will skip ahead by 1 pixel or so, which makes the animation not look smooth 

**4. Steps to reproduce**

1. Go to code sandbox
2. Toggle [animate] button
3. Observe the top and bottom red box

**5. Expected behavior**
the useTransform curve should follow the smooth conclusion of the spring motionvalue

**6. Video or screenshots**

https://user-images.githubusercontent.com/1629901/117210277-148ad880-adbd-11eb-90de-ca1d9610710d.mov

<img width="189" alt="image" src="https://user-images.githubusercontent.com/1629901/117210368-31271080-adbd-11eb-8790-f10a023ab08f.png">
See the offset of the top and bottom

**7. Environment details**

Can see this on Safari 14.1, Chrome, on Catalina

**Comment by souldreamer** [comment]
I think it's probably something other than the transform at fault. Making progress go from 0 to 100 too, but adding two dummy transforms after, the value is identical to the untransformed spring. It might be an issue with floating point precision, but not sure.

```typescript
  const _xt = useTransform(progress, v => v - 100);
  const xTransform = useTransform(_xt, v => 100+v);
```

**Comment by mattgperry** [comment]
It's because the progress spring is animating to `1` and the spring spring is animating to `100`. Springs need to choose an arbitrary point to cut off. By animating a tiny amount like `0` -> `1` you probably want to provide something like `restDelta: 0.0001`
