### ISSUE TITLE
[BUG] Syntax error when using react-hot-loader

### ISSUE THREAD

**Issue by askAguilr** [framer/motion#1132]
**2. Describe the bug**

Starting from 3.7.0 up to current versions, using framer-motion and react-hot-loader causes a crash on start, making it imposible to use the develop builds. The production builds runs fine.

A syntax error is shown 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Couldn't setup react-hot-loader in codesandbox.

**4. Steps to reproduce**

1. Setup a project with the latest version of react-hot-loader
2. import {motion} from "framer-motion" and use it anywhere
3. stop the react app, start again.

**5. Expected behavior**

The project should launch as usual

**6. Video or screenshots**

![image](https://user-images.githubusercontent.com/2243726/117405702-a4ba4200-aed1-11eb-95f7-c64917f0dc44.png)

**Comment by mattgperry** [comment]
Without a reproduction it's unlikely I'm going to find the time to look into this.
