### ISSUE TITLE
[BUG] TypeError: v.match is not a function

### ISSUE THREAD

**Issue by vuhi** [framer/motion#1136]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
Chaining `useSpring()` and `userTransform()` with **output value[]** as **percentage string** throws error: 
### TypeError: v.match is not a function
```
const [top, topSetter] = useState(0);
const [clientHeight, clientHeightSetter] = useState(0);
useEffect(() => {
  if (!ref|| !ref.current) return;

  const setValues = () => {
    topSetter(internalRef!.current!.offsetTop);
    clientHeightSetter(window.innerHeight);
  };
  setValues();
}, [ref]);
const { scrollY } = useViewportScroll();
const y = useSpring(useTransform(
  scrollY, 
  [top - clientHeight + 70, top], 
  ['20%', '-100%'], 
  { clamp: false })
);
```

- **CodeSandBox** does not throw any error, but local development throw error

**6. screenshots**

<img width="617" alt="Capture" src="https://user-images.githubusercontent.com/35607328/117528510-adc61480-afa0-11eb-834c-411aef8403c2.PNG">

Stack traces:

<img width="762" alt="Capture" src="https://user-images.githubusercontent.com/35607328/117528596-fd0c4500-afa0-11eb-997e-c78ca1911f3c.PNG">

<img width="761" alt="Capture" src="https://user-images.githubusercontent.com/35607328/117528660-4361a400-afa1-11eb-9339-9c1afa0af654.PNG">

<img width="765" alt="Capture" src="https://user-images.githubusercontent.com/35607328/117528686-6c823480-afa1-11eb-89f5-d6248251181d.PNG">

**7. Environment details**
- package.json: `"framer-motion": "^4.1.9", "react": "^17.0.2", "react-dom": "^17.0.2"`
- Window
- Chrome

**Comment by Ragnar-Loth-brok** [comment]
use string value  in here with 'px' added.-> [top - clientHeight + 70, top]
like -> 
         [`${top - clientHeight}px` + 70, `${top}px`]

**Comment by dlmanning** [comment]
I believe what's happening here will be an issue anytime one animates between a number and a string value, or vice versa. Within popmotion, [interpolate](https://github.com/Popmotion/popmotion/blob/master/packages/popmotion/src/utils/interpolate.ts#L24) will select a mixerFactory based on the type of the parameter it begins animating from.

Popmotion's type definitions expect animate to be called with matching types for `from` and `to` [here](https://github.com/framer/motion/blob/main/src/animation/utils/transitions.ts#L198). However, [`from` is an `any` type](https://github.com/framer/motion/blob/main/src/animation/utils/transitions.ts#L159), so you aren't getting a type error.

**Comment by dh00mk3tu** [comment]
> I got this error with:
> 
> ```ts
> const x = useMotionValue("0px")
> const s = useSpring(x)
> ```
> 

Try putting x under double quotes. 

const s = useSpring(x)

**Comment by mattgperry** [comment]
`useSpring` only accepts numerical MotionValues as input. You can convert to % with a `useTransform` off the spring, not before
