### ISSUE TITLE
motion link does not animate when it's child of nextJs Link component

### ISSUE THREAD

**Issue by SamyZog** [framer/motion#1144]
when creating a motion styled link `styled(motion.a)``;`, I cannot trigger an animation on it if it is the child of a nextjs `Link` component.

nextjs `Link` docs: 

`If the child of Link is a function component, in addition to using passHref, you must wrap the component in React.forwardRef`

https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-function-component

the sandbox represents 3 cases, only one triggers an animation, the one where I do not pass the ref attribute to the styled motion link component

https://codesandbox.io/s/motion-link-does-not-animate-if-child-of-nextjs-link-component-q0by8?file=/pages/index.js

Is this the expected behavior, if so please could you explain why this is happening?

**Comment by mattgperry** [comment]
It's not expected, it's definitely weird, though I'm also finding it really hard to replicate. I'm not sure how truthful CodeSandbox is being to me when I change versions, I'm getting stuck animations now.

It does seem to work if you pass `ref` directly to a `motion.a`. But this doesn't work:

```javascript
const StyledLink = motion(styled.a``);
```

I see the `ref` provided by `next/link` is a function. We did change something in regards to our handling of these in `4.1.13`. Does it work for you with `4.1.11`? Alternatively does downgrading Styled Component change anything?

**Comment by jgoux** [comment]
Hello all, `4.1.13` indeed broke something for us as well.

We use framer-motion to animate elements in our design system built with stitches and radix from modulz. Our Drawer is no longer animated : https://gist.github.com/jgoux/4e1ed75db7a62974e8faf8fa85c68c64

**Comment by rbourdon** [comment]
I'm experiencing this in my Next.js project as well when using `next/link`, starting with framer-motion `4.1.13`

**Comment by SamyZog** [comment]
> It's not expected, it's definitely weird, though I'm also finding it really hard to replicate. I'm not sure how truthful CodeSandbox is being to me when I change versions, I'm getting stuck animations now.
> 
> It does seem to work if you pass `ref` directly to a `motion.a`. But this doesn't work:
> 
> ```js
> const StyledLink = motion(styled.a``);
> ```
> 
> I see the `ref` provided by `next/link` is a function. We did change something in regards to our handling of these in `4.1.13`. Does it work for you with `4.1.11`? Alternatively does downgrading Styled Component change anything?

you were right about sandbox, I tried to recreate the issue locally with vscode, and the results are not the same, on the sandbox at least one of the animations get triggered. Locally nothing worked, I tried to reproduce the issue by trying other different combinations for the last couple of hours, alas nothing. 

My guess is for the time being the best solution is wrapping the link with a motion wrapper to get the expected behavior...

**Comment by mattgperry** [comment]
Can you try 4.1.16 and let me know if this fixes it?

**Comment by rbourdon** [comment]
> 
> 
> Can you try 4.1.16 and let me know if this fixes it?

4.1.16 fixed the issue for me, thanks!

**Comment by jgoux** [comment]
@mattgperry it's fixed for us as well! Many thanks Matt!

**Comment by SamyZog** [comment]
@mattgperry yup, all fixed. Thank you!
