### ISSUE TITLE
ScaleX parent without scaling children

### ISSUE THREAD

**Issue by chapster11** [framer/motion#1145]
I'm seeing that useInvertedScale() is depreciated and It says to use the layout prop instead but it doesn't seem to achieve the same effect. I'm trying to scaleX a parent div whiteout affecting the scale of the children. 

https://codesandbox.io/s/gracious-gates-luum0?file=/src/App.js

1. refresh page scaleX happens on parent
2. Text inside parent should stay the same and not scale or distort
Example using useInvertedScale
https://codesandbox.io/s/framer-motion-useinvertedscale-49wlv?fontsize=14&module=/src/Example.tsx&file=/src/Example.tsx

**Comment by mattgperry** [comment]
@chapster11 Where did you see the reference to `useInvertedScale()`? I'm not seeing anything in the docs.

**Comment by mattgperry** [comment]
Ah I see yeah there’s a frame where you can perceive the text to change wrapping. I’m surprised this is visible to be honest but you might get away with it with overflow hidden. 

It might be the text needs an explicit layout to keep it full width?

**Comment by chapster11** [comment]
Ah yea setting an explicit width will prevent that text from wrapping causing it to look weird. 
So does width map to scaleX under the hood or do you have to add layout prop to the element. 

Also I noticed in your example compared to mine or the docs you were using a state to trigger the width this is really nice, never thought of it this way. Can you explain what layout prop is doing here that is different to my first example using the docs approach of a variant.

**Comment by mattgperry** [comment]
Sure, layout basically says “animate any static layout changes, triggered by a react render, using transforms”. 

layout=position should animate only the changes position, switching the size instantly, otherwise text can appear distorted

**Comment by joshuawootonn** [comment]
Hello! I have been trying to answer [this SO](https://stackoverflow.com/q/67477219/8239711) question for a couple of hours now. Seems really closely related to what you guys are doing. @mattgperry can you explain why your sandbox doesn't animate the div to 0 when I reverse it? 

You can reverse it easily here: https://codesandbox.io/s/nifty-fire-6feqx?file=/src/App.js

**Comment by rbourdon** [comment]
> 
> 
> Hello! I seem to have a problem really closely related to what you guys are talking about. @mattgperry can you explain why your sandbox doesn't animate the div to 0 when I reverse it?
> 
> You can reverse it easily here: https://codesandbox.io/s/nifty-fire-6feqx?file=/src/App.js
> 
> Related [SO question](https://stackoverflow.com/q/67477219/8239711) I am trying to answer

I opened an issue for this: #1149

It's related to the fact that animating width/height via layout (any change to the style prop or css properties) uses scale() behind the scenes for smooth animation.
