### ISSUE TITLE
[BUG] SVG Attributes 

### ISSUE THREAD

**Issue by KirdesMF** [framer/motion#1152]
This issue is related to #1150

First, I don't know if it's really needed to fill a bug report. Let me know if there is something wrong.
I should have checked when I made the PR #1151

there is others svg attributes that should be in the camelCase array

I realised that after trying to animate a svg pattern https://codesandbox.io/s/magical-williams-i8vv2?file=/src/styles.css

![image](https://user-images.githubusercontent.com/54989552/118400936-001fc900-b664-11eb-85d8-32068fae93dd.png)

Here is the list of camelCase svg attribute

- allowReorder
- attributeName
- attributeType
- autoReverse
- baseFrequency
- baseProfile
- calcMode
- clipPathUnits
- contentScriptType
- contentStyleType
- diffuseConstant
- edgeMode
- externalResourcesRequired
- filterRes
- filterUnits
- glyphRef
- gradientTransform
- gradientUnits
- kernelMatrix
- kernelUnitLength
- keyPoints
- keySplines
- keyTimes
- lengthAdjust
- limitingConeAngle
- markerHeight
- markerUnits
- markerWidth
- maskContentUnits
- maskUnits
- patternContentUnits
- patternTransform
- patternUnits
- pointsAtX
- pointsAtY
- pointsAtZ
- preserveAlpha
- preserveAspectRatio
- primitiveUnits
- repeatCount
- repeatDur
- requiredExtensions
- requiredFeatures
- specularConstant
- specularExponent
- spreadMethod
- startOffset
- stdDeviation
- stitchTiles
- surfaceScale
- systemLanguage
- tableValues
- textLength
- viewBox
- viewTarget
- xChannelSelector
- yChannelSelector

**Comment by rijk** [comment]
I ran into this issue while trying to animate `startOffset`, it is still present in `framer-motion@6.3.3`.

**Comment by willhindson** [comment]
Also a problem for me — it's animating the non-property "start-offset" instead of startOffset

**Comment by PCPbiscuit** [comment]
I've created a PR which adds missing most used animated camel case svg attributes

**Comment by rijk** [comment]
That will not get merged, [other people have done that already](https://github.com/framer/motion/pull/1153) and it was rejected due to bundle size.

If we were to solve this, it would have to be with a [solution like this](https://github.com/framer/motion/pull/1153#issuecomment-1135736249) that doesn't require a hardcoded list of attributes.
