### ISSUE TITLE
[BUG] 4.1.6 broke layout animation

### ISSUE THREAD

**Issue by rijk** [framer/motion#1155]
Still working on reproduction, but the recording shows what's happening:

**framer-motion@4.1.5** (works as intended):

https://user-images.githubusercontent.com/159500/118468270-e2ef0700-b704-11eb-9823-a168646d19e6.mov

**framer-motion@4.1.6** (note the flash in the open animation):

https://user-images.githubusercontent.com/159500/118468319-ee423280-b704-11eb-9ba4-42681174eeab.mov

**Comment by rijk** [comment]
This issue seems to be gone now in 4.1.18.

**Comment by rijk** [comment]
Scratch that, issue still there. Working on a reproduction.

**Comment by rijk** [comment]
Ok this was super weird, but after a LOT of debugging I discovered the issue was with my particular install of `framer-motion`. When I run `npm uninstall framer-motion` followed by `npm i framer-motion@4.1.18-rc.26` the flickering is gone. 

After reinstalling nothing changed in `package.json`, but there are changes in `package-lock.json`, here is the diff: https://gist.github.com/rijk/ea987e188b14253c8f5fc956d97dcb81 . 

But it seems none of the dependency versions have even changed. So I don't understand why `package-lock.json` changes after reinstalling, or why this solves the flickering issue. Any idea @mattgperry ?

**Comment by rijk** [comment]
Oh my god sorry I feel so bad, reason turned out to be I had `@popmotion/popcorn@0.4.2` installed directly. Sorry for the spam!

**Comment by berkaycirak** [comment]
I think the issue can be solved by removing transition from your element whether there is transition styling in the css of related element. Since transition property of motion.[element] can be conflicting with transition property of related custom CSS. For example, in that paragraph element, I have added a transition prop which comes from motion and if I add a transition styling to my className then that P will flash and be flicking. 
```
<motion.p
							initial={{ opacity: 0 }}
							animate={{ opacity: 1 }}
							transition={{ duration: 1, delay: index }}
							key={index}
							ref={(el) => (optionRef.current[index] = el)}
							className={`bg-gradient-to-tr from-[#7e9497] to-[#83f3e1] w-[80%] whitespace-nowrap mb-4 rounded-full p-2 px-4  cursor-pointer mx-auto relative after:w-[20px] after:h-[20px] after:rounded-full after:border after:absolute after:right-[5%] after:border-[#1c262e] active:from-[#b0b973] active:to-[#b0b973]  `}
							onClick={(e) => {
								handleClick(e, option);
								handleSelect(e);
							}}
							dangerouslySetInnerHTML={{ __html: option }}
						/>
```

**Comment by istvantothdesign** [comment]
> I think the issue can be solved by removing transition from your element whether there is transition styling in the css of the related element. Since transition property of motion.[element] can be conflicting with transition property of related custom CSS. For example, in that paragraph element, I have added a transition prop which comes from motion and if I add a transition styling to my className then that P will flash and be flicking.
> 
> ```
> <motion.p
> 							initial={{ opacity: 0 }}
> 							animate={{ opacity: 1 }}
> 							transition={{ duration: 1, delay: index }}
> 							key={index}
> 							ref={(el) => (optionRef.current[index] = el)}
> 							className={some tailwind styling without transition}
> 							onClick={(e) => {
> 								handleClick(e, option);
> 								handleSelect(e);
> 							}}
> 							dangerouslySetInnerHTML={{ __html: option }}
> 						/>
> ```

Thank you. This solved the issue for me.
