### ISSUE TITLE
[BUG] While dragging, the children does not follow the parent. Override in Framer App.

### ISSUE THREAD

**Issue by blankov** [framer/motion#1156]
**2. Describe the bug**

When dragging a frame with override the children does not follow the parent.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://framer.com/projects/BUG-When-dragging-a-frame-with-override-the-children-does-not-follow-the-parent--w9WeAtiOoDYCy3PiuFnn

**4. Steps to reproduce**

1. Add 'drag' as Override
2. See error

**6. Video or screenshots**

I added a black background to the parent to show the offset.
![2021-05-17 12 20 36](https://user-images.githubusercontent.com/47553128/118473932-2f414380-b713-11eb-8b9b-0a79a26a83b2.gif)

**7. Environment details**

macOS 10.15.4 (19E287)
Framer App

**Comment by mattgperry** [comment]
The best place for Framer product issues is https://www.framer.com/support/
