### ISSUE TITLE
[BUG] 4.1.16 Layout projection while drag moving elements to wrong place

### ISSUE THREAD

**Issue by rijk** [framer/motion#1158]
**Describe the bug**

See the following video:

https://user-images.githubusercontent.com/159500/118494286-49365280-b722-11eb-9ddf-43d55f890c0a.mov

**Expected behavior**

Colored squares should not move outside their white parent box.

Also note that the first box (with "v2") moves down by itself after refreshing, for no apparent reason.

**CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-2-drag-to-reorder-forked-ldpzw — Without `React.memo()`; subtle issues
https://codesandbox.io/s/framer-motion-drag-shift-issue-reactmemo-170jl?file=/src/App.js — With `React.memo()`; issues as presented in first video

**Issue 1:** When starting drag (or changing position), there is an unexpected scale animation on the grey square

https://user-images.githubusercontent.com/159500/118473584-6e1ecb80-b70a-11eb-8a4f-0ee0f7a82250.mov

**Issue 2:** The projection of the gray square is not always correct

https://user-images.githubusercontent.com/159500/118473716-94446b80-b70a-11eb-868f-930e37fdd287.mov

**Comment by rijk** [comment]
Also interesting to note that the "v2" square moves back when opening the modal for a different step:


https://user-images.githubusercontent.com/159500/118495892-ec3b9c00-b723-11eb-886e-bdbde655bd03.mov

**Comment by rijk** [comment]
In the Sandbox, I've even seen it move diagonally, which is super weird as the drag is only Y axis:


https://user-images.githubusercontent.com/159500/118497592-7f290600-b725-11eb-8b4a-506bfcd783a8.mov

**Comment by rijk** [comment]
The initial shifting issue recorded here is fixed in f308a2e365724c951c9a1178722c5dab97139f62 (part of 4.1.18-rc.2). 👌

> Also interesting to note that the "v2" square moves back when opening the modal for a different step:
> 
>  Screen.Recording.2021-05-17.at.15.22.34.mov

**Comment by rijk** [comment]
The original issue (boxes shifting outside of parent on drag) is still present in latest (4.1.18-rc.15/85459c703aa5ae7cbd8984c30827793e3d276461). Let me know if you need a repro Sandbox.

**Comment by rijk** [comment]
On 4.1.18-rc.17, it is a little better, but still some issues for the first item: https://codesandbox.io/s/framer-motion-2-drag-to-reorder-forked-ldpzw


https://user-images.githubusercontent.com/159500/120994328-ac952c80-c784-11eb-82c3-494c2478f5fc.mov

**Comment by rijk** [comment]
Here's a Sandbox that shows the issue in the initial video: https://codesandbox.io/s/framer-motion-drag-shift-issue-reactmemo-170jl?file=/src/App.js — it happens when introducing `React.memo()`.

**Comment by mattgperry** [comment]
Closing this for now as the drag/drop use-case has been superseded by Reorder. If it's still a problem please open a new ticket (or reopen this one if possible)
