### ISSUE TITLE
[FEATURE] Adjust drag delta?

### ISSUE THREAD

**Issue by zschiller** [framer/motion#1161]
I'm trying to use Framer Motion to implement a re-orderable list using `drag` and `layout` properties. The one issue I am running into is one of the parent nodes may have a `transform: scale` applied to it (to support zoom) and so the drag gestures aren't tracking the mouse properly.

Is there some way to interrupt the drag event and adjust the measured delta to compensate for the zoom level? Or is there another way to implement this that I should look into?

Thanks!

**Comment by sarendsen** [comment]
@zschiller did you found a solution for this?

**Comment by zschiller** [comment]
@sarendsen I ended up reimplementing the transform/translation/DOM measurement myself on top of the `onPan` gestures from Framer motion.

**Comment by sguergachi** [comment]
Hitting this issue, would be nice to have a built in way to handle this.
