### ISSUE TITLE
[FEATURE] Add disable feature for AnimatePresence

### ISSUE THREAD

**Issue by MoMoWongHK** [framer/motion#1163]
**Is your feature request related to a problem? Please describe.**
I am using motion for PWA development, I found that some page transitions should disable while this is desktop size.

**Describe the solution you'd like**
Just add one props in `<AnimatePresence>`
  <AnimatePresence enable={true} >

**Describe alternatives you've considered**
I tried to change variants in the `<motion.div>` but not effective

**Comment by mattgperry** [comment]
Feel free to reopen with sandbox showing the undesired behaviour.
