### ISSUE TITLE
[FEATURE] allow multi-touch drag

### ISSUE THREAD

**Issue by augustblack** [framer/motion#1164]
Thanks for this awesome library.

I think it would be a great feature to allow multi-touch drag.

Here is an example  and potential use case where multi-touch drag would be helpful:

https://muxc4.csb.app/

Trying to move both faders at once results in funky behavior on a phone/mobile

**Comment by mattgperry** [comment]
Closing as `wontfix` to set expectations.

It's still possible this could be implemented, but it's unlikely to happen unless we need the functionality inside Framer.
