### ISSUE TITLE
Option to use transform instead of transform3d to get around Chrome rendering bugs

### ISSUE THREAD

**Issue by lmartins** [framer/motion#1165]
**Is your feature request related to a problem? Please describe.**
Chrome currently displays, and for several years now, some rendering issues when you apply a `clip-path` to a SVG group which itself contains a `image` element with `transform3d` applied to it.

I'm currently running into this problem, in a situation where I have an svg image which can be dragged using Motion's drag features. Those will apply the transforms using `transform3d` triggering the problem in Chrome. All other browsers I have access to render properly.

**Describe the solution you'd like**
Having the option to use `transform` instead of `transform3d` would for the most part retain the same functionality, while avoiding Chrome issues.

**Comment by mattgperry** [comment]
Is it possible to use `transformTemplate` https://www.framer.com/docs/component/###transformtemplate?

**Comment by mattgperry** [comment]
Feel free to reopen if the above doesn't solve the issue!
