### ISSUE TITLE
[BUG] AnimateSharedLayout offsets on first render

### ISSUE THREAD

**Issue by ghost** [framer/motion#1167]
Give a clear and concise description of what the bug is.

translate3D offsets way too much when using "margin: 0 auto" with a centered container.
This is caused in the AnimateSharedLayout using Next.JS.
This happens only on the first click, the second render it works as expected

**6. Video or screenshots**

https://user-images.githubusercontent.com/44460622/119705145-b3ed3980-be58-11eb-9b0f-58dbec6bcd85.mov

**7. Environment details**

using Chrome in MacOS

**Comment by mattgperry** [comment]
Can you try again with Motion 5 and reopen with a codesandbox if it still isn't working?
