### ISSUE TITLE
[BUG]Unable to pass ref when using useElementScroll

### ISSUE THREAD

**Issue by lodisy** [framer/motion#1168]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

Unable to pass ref when using useElementScroll

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/serverless-fast-l6w90

**4. Steps to reproduce**

1. Named a ref variable 
2. Get the scrollY using useElementScroll(ref)
3. Pass the ref to the scrollable div, here Sheet.Content(forwardRef) or the div inside it.
4. Ref is always undefined 
5. Remove the useElementScroll sentence 
6. Ref works

**5. Expected behavior**

No errors

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

**7. Environment details**

If applicable, let us know which OS, browser, browser version etc you're using.

### `AnimatePresence` isn't working

Have all of its immediate children got a unique `key` prop that **remains the same for that component every render**?

```jsx
// Bad: The index could be given to a different component if the order of items changes
<AnimatePresence>
  {items.map((item, index) => <Component key={index} />)}
</AnimatePresence>
```

```jsx 
// Good: The item ID is unique to each component
<AnimatePresence>
  {items.map((item, index) => <Component key={item.id} />)}
</AnimatePresence>
```

Is the `AnimatePresence` correctly outside of the controlling conditional? `AnimatePresence` must be rendered whenever you expect an `exit` animation to run - it can't do so if it's unmounted!

```jsx
// Bad: AnimatePresence is unmounted - exit animations won't run
{isVisible && (
  <AnimatePresence>
    <Component />
  </AnimatePresence>
)}
```

```jsx
// Good: Only the children are unmounted - exit animations will run
<AnimatePresence>
  {isVisible && <Component />}
</AnimatePresence>
```

**Comment by pinktonio** [comment]
@lodisy How did you solve it? I'm getting the same error as in your demo.
