### ISSUE TITLE
[BUG] Glitchy behaviour when adding an animation to a draggable element

### ISSUE THREAD

**Issue by buesing** [framer/motion#1170]
**2. Describe the bug**

Using a variant based animation on a `<motion.div>` that is also draggable results in buggy behvariour. **This used to work in v1, but doesn't anymore since v2**. See the codesandbox below.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Here is the example of a bottom sheet that works in version 1:
https://codesandbox.io/s/framer-motion-bottom-sheet-fixed-m2vls?file=/src/index.js

And this is the example in v4 which displays the buggy behaviour:
https://codesandbox.io/s/framer-motion-bottom-sheet-problem-forked-2hzu7

**4. Steps to reproduce**

1. Go to the [codesandbox link](https://codesandbox.io/s/framer-motion-bottom-sheet-problem-forked-2hzu7)
2. Click on "Toggle"
3. Notice the sheet doesn't animate to the top
4. Try dragging the sheet around
4. Notice the sheet can't be dragged smoothly.

**5. Expected behavior**

The div should be smoothly draggable and animate to the top and bottom positions as in the example in v1: https://codesandbox.io/s/framer-motion-bottom-sheet-fixed-m2vls?file=/src/index.js

**Comment by mattgperry** [comment]
This seems to be fixed in 5

**Comment by amannn** [comment]
> This seems to be fixed in 5

Can confirm, thanks a lot!
