### ISSUE TITLE
[BUG] AnimatePresence does not unmount when AnimateSharedLayout is below it

### ISSUE THREAD

**Issue by marceloadsj** [framer/motion#1172]
First of all, thanks a lot for that amazing lib. 😄

**1. Read the [FAQs](#faqs) 👇** ✔

**2. Describe the bug** Give a clear and concise description of what the bug is.

When AnimateSharedLayout is under a AnimatePresence, if the same action (for ex, onClick) trigger both animations, the AnimatePresence will not unmount.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug** A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

https://codesandbox.io/s/framer-motion-2-animatesharedlayout-animate-between-different-components-forked-311pv?file=/src/Circles.js

**4. Steps to reproduce**

1. Go to the sandbox provided
2. Click on "Open" so a Dialog will open (AnimatePresence)
3. Click on any colored circle, both animations will trigger (AnimateSharedLayout moving colored circle  & AnimatePresence closing off)
4. Check the devtools and see that the DOM elements are still there

**5. Expected behavior** A clear and concise description of what you expected to happen.

The AnimatePresence should unmount its children correctly, removing the elements from the DOM.

**6. Video or screenshots** If applicable, add a video or screenshots to help explain the bug.

Follow the steps on item number 4.

**7. Environment details** If applicable, let us know which OS, browser, browser version etc you're using.
Tested on Chrome: Version 90.0.4430.212 (Official Build) (64-bit)

___

A use case example:
- A Drawer (AnimatePresence) with Nav inside.
- The Nav links has a "border" that slides to the selected link when it was clicked (AnimateSharedLayout).
- Clicking on a Nav link changes the page, thus, closing the Drawer.

Nav example:
![image](https://user-images.githubusercontent.com/4874089/119981311-c765e500-bfbd-11eb-8ae9-91567184ad0d.png)

___

PS: Let me know if I have to implement any specific control with, for example, usePresence hook, to put this scenario to work.

**Comment by paales** [comment]
Your demo seems to be out-of-date, but checked it with the latest version and still seems to be the issue: https://codesandbox.io/s/framer-motion-2-animatesharedlayout-animate-between-different-components-forked-311pv?file=/src/Circles.js

**Comment by marceloadsj** [comment]
Thanks @paales , I've updated the link on my message with yours. I might have installed the wrong version, but locally I use the latest one and yes, the issue is still there. Thanks for noticing the version mistake!

**Comment by lukasz-fiuk** [comment]
I'm experiencing the same issue.  Have you found any solution/workaround  for this bug?

**Comment by marceloadsj** [comment]
Giving that for my use case, the animated element is just decorative, I simply hide it when the drawer is closing.
![image](https://user-images.githubusercontent.com/4874089/127891264-66b02bb5-1099-4ac8-88f3-ac4c73cb4a23.png)

But I don't know if there is some workaround for more complex use cases, sorry.

**Comment by mattgperry** [comment]
Fixed in 5
