### ISSUE TITLE
[BUG] animation that should be applied to the newly created component is applied repeatedly only to the first component created.

### ISSUE THREAD

**Issue by bmaner** [framer/motion#1174]
**2. Describe the bug**

When creating the todolist app, animation that should be applied to 

the newly created component is applied repeatedly only to the first component created.

I think watching videos will be more helpful for understanding.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[https://10rfm.csb.app/](url)
[https://codesandbox.io/s/10rfm?file=/src/App.js](url)
**4. Steps to reproduce**

1. Please type any letters in the input tag. If you create about three lists, you will find that only the first list is animated.
2. Press the opensandbox button on the bottom right and enter the components directory.
3. When you open the Todo.js file, you can see my code that allows the animation to take effect whenever a new list is created.

```jsx
  return todos.map((todo, index) => (
    <motion.div
      className={todo.isComplete ? "todo-row complete" : "todo-row"}
      key={index}
      initial={{ x: -100, opacity: 0 }}
      animate={{ x: 0, opacity: 1 }}
      transition={{ duration: 1, type: "spring" }}
    >
      <div
        className="todo-content"
        key={todo.id}
        onClick={() => completeTodo(todo.id)}
      >
        {todo.text}
      </div>
      <div className="icons">
        <RiCloseCircleLine
          onClick={() => removeTodo(todo.id)}
          className="icon"
        />
        <TiEdit
          onClick={() => setEdit({ id: todo.id, value: todo.text })}
          className="icon"
        />
      </div>
    </motion.div>
  ));
```

**5. Expected behavior**

I hope that the same animation will be applied every time a new list is created, rather than just the components that were created for the first time.

**6. Video or screenshots**

![ezgif com-gif-maker](https://user-images.githubusercontent.com/78008369/120216998-b2fe4280-c272-11eb-8b22-2059e8e1f91e.gif)

I'm a beginner studying development. I'm not sure wether it's bug or my mistake that the animation doesn't work. Please check it out. Thank you.

**Comment by mattgperry** [comment]
Your key is `index`. The key needs to be consistent for each component throughout the duration of its lifespan.

In the video for instance, the first added item gets `0`. Then when a second item is added, the first item now has an index of `1`, so React sees this as a new item and animates it. The second item has a key of `0`, which React sees as the old component, so doesn't animate it.

The key should be `todo.id`
