### ISSUE TITLE
[BUG] Drag event on smart component with nested children & variants not working properly

### ISSUE THREAD

**Issue by alex-lechner** [framer/motion#1175]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

Dragging of a "complex" smart component with nested children and different variants does not work. The x-coordinate always resets to 0 after drag end and the nested children do not get dragged along. Reference #663 and #636 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Can't be reproduced in CodeSandbox because you have to use the framer app to create smart components.

**4. Steps to reproduce**

1. Create a Frame with multiple texts (or other layers) inside
2. Turn the Frame into a smart component
3. Create variants of that Frame (which change from Variant 1 to Variant 2 with onTap for example)
4. Create a code file and add:
```jsx
import {
    Override,
    motionValue,
} from "framer"
const xPos = motionValue(0)

export function Drag(): Override {
    return {
        drag: "x",
        x: xPos,
        dragMomentum: false,
        dragElastic: 0.1,
    }
}
```
5. Save and name it `test.tsx"
6. On the Canvas: choose the smart component
7. On the right panel, click on `Overrides` > `File` choose `test.tsx` and on `Override`choose `Drag`

**5. Expected behavior**

The smart component and all its nested children are all in the same position.

**6. Video or screenshots**

![smart-component-issue](https://user-images.githubusercontent.com/26361781/120334450-ec759300-c2f0-11eb-998a-bbdaca9e2211.gif)

**7. Environment details**

Framer Desktop app on MacOS v11.4

**Comment by mattgperry** [comment]
Framer support can be found on our Discord! https://www.framer.com/community/
