### ISSUE TITLE
[BUG] img dimensions snap / distort when using AnimateSharedLayout

### ISSUE THREAD

**Issue by YajJackson** [framer/motion#1176]
## Description
`<motion.img layout layoutId />` dimensions "snap" / distort when transitioning from modal state back to initial state while using `<AnimateSharedLayout>`.

## Sandbox
https://codesandbox.io/s/bold-wildflower-msd2y?file=/src/App.js

## Steps to reproduce the behavior
1. Open sandbox
2. Tap any of the images to open modal view
3. Tap anywhere on the modal to close the modal
4. Observe the `<motion.img />` snap 

## What should happen
The image element should smoothly transition back to initial state since `layout` & `layoutId` have been set.

## Video
https://user-images.githubusercontent.com/19982913/120349667-4adc4a80-c2cc-11eb-9bce-65ab6362fcb9.mov

## Environment
OS: macOs Big Sur Version 11.1
Browser: Chrome Version 90.0.4430.212 (Official Build) (x86_64)

## Other notes
I am not exactly an expert framer-motion user, so it's very possible user-error is at play here.

**Comment by YajJackson** [comment]
Sandbox code in case it's more convenient to read it here:
```tsx
export default function App() {
  const [selected, setSelected] = useState(null);

  return (
    <div className="App">
      <AnimateSharedLayout>
        <motion.div
          style={{
            display: "flex",
            gap: 10,
            width: 500
          }}
        >
          {images.map((src) => (
            <motion.div
              layout
              layoutId={"container" + src}
              key={src}
              style={{ height: 300, width: 200, background: "red" }}
            >
              <motion.img
                layout
                layoutId={src}
                src={src}
                style={{
                  objectFit: "contain",
                  flex: 1,
                  width: "100%",
                  height: "100%",
                  cursor: "pointer"
                }}
                onClick={() => setSelected(src)}
              />
            </motion.div>
          ))}
        </motion.div>
        <AnimatePresence>
          {selected && (
            <motion.div
              layout
              layoutId={"container" + selected}
              style={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                position: "absolute",
                top: 0,
                left: 0,
                width: "100vw",
                height: "100vh",
                background: "blue",
                cursor: "pointer"
              }}
              onClick={() => setSelected()}
            >
              <motion.img
                layout
                layoutId={selected}
                src={selected}
                style={{ objectFit: "contain", height: 300, width: 200 }}
              />
            </motion.div>
          )}
        </AnimatePresence>
      </AnimateSharedLayout>
    </div>
  );
}
```

**Comment by sidonaldson** [comment]
I found this issue too. If you add transition={{duration:20}} it's easier to spot what is going on.

The animation is applying a transform like so `translate3d(-55.5698px, -76.7639px, 0px) scale(**0.896614, 1**)`

It seems the scale is the wrong ratio. If you take object-fit out the equation it works fine.

https://codesandbox.io/s/red-blue-zoomie-36r1w?file=/src/App.js

I was trying to create a zoom out effect where the initial image is cropped but not resized using `object-fit:none` - which makes the issue even more obvious.

https://codesandbox.io/s/condescending-hellman-wlwz8?file=/src/App.js

**Comment by mattgperry** [comment]
You would need to ensure the image itself is the same aspect ratio in both states, perhaps by using an extra parent element to handle the containment.
