### ISSUE TITLE
[BUG] Proxy is not defined in older browsers

### ISSUE THREAD

**Issue by alirezavlz** [framer/motion#1178]
Hey, I'm using the framer-motion in my project, I'm using browserstack to test the application, it seems the framer-motion is using `Proxy` which is not polyfillable. Is there any other way to use framer motion that supports older browsers?

I saw the issue on Chrome v38

![image](https://user-images.githubusercontent.com/53314423/120521049-cb866e00-c3d4-11eb-9264-cde186b6551c.png)

**Comment by mattgperry** [comment]
From `5.3.3` later today you'll be able to define components like this:

```javascript
const MotionDiv = motion("div")
```

If you need backwards compatibility with old browsers.
