### ISSUE TITLE
[BUG] Having issues in "whileHover" 

### ISSUE THREAD

**Issue by mhkasif** [framer/motion#1179]
**Description**
I'm having an issue with the latest version of framer-motion while hovering.

I've migrated from **2.9.4** to **4.1.17** and found that many things have changed.

I'm first mentioning the bug that's happening now but not on the older version.
when I hover over the element it starts its animation but if I remove the mouse in the middle, it gives some odd result.

**CodesandboxLink**
[bug link](https://codesandbox.io/s/gifted-mccarthy-xb5pp?file=/src/App.js)
https://codesandbox.io/s/gifted-mccarthy-xb5pp?file=/src/App.js

above is the link which is causing issue

**Steps to reproduce Bug**

1. Go to [https://codesandbox.io/s/gifted-mccarthy-xb5pp?file=/src/App.js](https://codesandbox.io/s/gifted-mccarthy-xb5pp?file=/src/BackButton.scss)
2. Hover on "Slide back" and leaves the mouse in the middle of the animation
3. See an error

I can't explain without showing the visuals so I'm posting a video that shows the bug.
** Video Of Bug**

https://user-images.githubusercontent.com/30750191/120905088-2fc16000-c669-11eb-9364-1c5a34926bca.mov

** Expected Result **

https://user-images.githubusercontent.com/30750191/120905273-7fecf200-c66a-11eb-8dbe-0020516c616b.mov

** Environment details**

OS: macOs Catalina Version 10.15.7.
Google chome Version 91.0.4472.77 

If applicable, let us know which OS, browser, browser version etc you're using.

**Comment by mhkasif** [comment]
anyone?

**Comment by SPodjasek** [comment]
@mhkasif  I'm also facing issues with `whileHover` but in my case it stopped working at all - in Chrome, they work in FIrefox. Can you validate your problem also exists on Firefox?

**Comment by mhkasif** [comment]
@SPodjasek having same problem both on firefox too

**Comment by SPodjasek** [comment]
I've made some extensive testing of my problem and it seems to occur only on my dev machine chrome & chromium - testing on any other OS/machine it works as expected.

**Comment by dn9z** [comment]
I experience the same.  `whileHover` not working at all in Chrome.

**Comment by dn9z** [comment]
I experience the same. whileHover not working at all in chrome and buggy in firefox

**Comment by dn9z** [comment]
I experience the same. `whileHover` not working at all in chrome and buggy in firefox

**Comment by GMaiolo** [comment]
Note: This is still happening with version `6.3.10`

**Comment by mattgperry** [comment]
It's picking up the delay/stagger stuff from the initial render. Currently I think the only way to fix this is to change the `transition` after initial render.

As a feature this is being tracked: https://github.com/framer/motion/issues/1725
