### ISSUE TITLE
[BUG] App Drawer doc example is using V2

### ISSUE THREAD

**Issue by glekner** [framer/motion#1186]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
While reading https://www.framer.com/api/motion/examples/
I noticed The App Drawer example is using V2
Is the team going to update those docs?

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/app-store-ui-using-react-and-framer-motion-jnqfv

**4. Steps to reproduce**
https://www.framer.com/api/motion/animate-shared-layout/#crossfade

**5. Expected behavior**
The example should use V4
The example is using `useInvertedScale` which is removed in V4, can you please provide an updated sandbox?

**Comment by mattgperry** [comment]
Example has been removed from the docs, might not have time to recreate for 5

**Comment by cristianrincon-ui** [comment]
Is this example never coming back? Such a great implementation but can't run now.
