### ISSUE TITLE
Is it possible to enable GitHub Discussions?

### ISSUE THREAD

**Issue by Restuta** [framer/motion#1191]
Re: https://docs.github.com/en/discussions

I think it could redirect community from using Issues for Discussions and provide better experience for those on both ends.

**Comment by Ploppy3** [comment]
@mattgperry

**Comment by miguderp** [comment]
Asking also about this, discussions are a great place to share around ideas, examples & showcases without them being specifically linked to an issue; would love to have that enabled!

**Comment by mattgperry** [comment]
Consider it done 😃 let’s give it a go!
