### ISSUE TITLE
[FEATURE] Imitate CSS step() animation timing function

### ISSUE THREAD

**Issue by ThomasRutzer** [framer/motion#1195]
Is it possible to create a keyframe based animation like when you use [CSS timing function step()](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function)? The gist is, that there is no tween between values of each frame...

**Comment by mattgperry** [comment]
You can pass functions to `ease` so you could import `steps` from `popmotion`: https://popmotion.io/#quick-start-easing-factories-steps

**Comment by ThomasRutzer** [comment]
Ok. Do you think this would be increase the bundlesize remarkebly?

**Comment by mattgperry** [comment]
Bits of popmotion are already included, steps isn't, but its a very small function so thanks to tree-shaking you'll only be importing that

**Comment by ThomasRutzer** [comment]
Thanks for your quick replies. I'll give it a try
