### ISSUE TITLE
[BUG] Drag breaks when parent uses css scale and flexbox align-items = stretch

### ISSUE THREAD

**Issue by jamwise** [framer/motion#1198]
**1. Read the [FAQs](#faqs) 👇**
✅ 

**2. Describe the bug**

Given a list of stretched items in a flexbox container with the `drag` prop, and when the parent has been scaled, the position and size of the items becomes erratic. They seem to be holding on to the old size values when changing the parent's scale.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/objective-murdock-lolv5?file=/src/App.js

**4. Steps to reproduce**

1. Go to https://codesandbox.io/s/objective-murdock-lolv5?file=/src/App.js
2. Drag any of the items
3. Click the button "scale"
4. Try to drag items again
5. See items lose their position and size

**5. Expected behavior**

The items scale with their parent, but remain scaled and their position is predictable and not erratic.

**6. Video or screenshots**

https://user-images.githubusercontent.com/6416083/123549827-a87f7d80-d738-11eb-885c-c5aabefe8ea7.mov

**7. Environment details**

Any greenfield browser

### `AnimatePresence` isn't working

Have all of its immediate children got a unique `key` prop that **remains the same for that component every render**?

```jsx
// Bad: The index could be given to a different component if the order of items changes
<AnimatePresence>
  {items.map((item, index) => <Component key={index} />)}
</AnimatePresence>
```

```jsx 
// Good: The item ID is unique to each component
<AnimatePresence>
  {items.map((item, index) => <Component key={item.id} />)}
</AnimatePresence>
```

Is the `AnimatePresence` correctly outside of the controlling conditional? `AnimatePresence` must be rendered whenever you expect an `exit` animation to run - it can't do so if it's unmounted!

```jsx
// Bad: AnimatePresence is unmounted - exit animations won't run
{isVisible && (
  <AnimatePresence>
    <Component />
  </AnimatePresence>
)}
```

```jsx
// Good: Only the children are unmounted - exit animations will run
<AnimatePresence>
  {isVisible && <Component />}
</AnimatePresence>
```

**Comment by mattgperry** [comment]
Fixed in 5
