### ISSUE TITLE
[FEATURE] Update Appstore example to modern apis

### ISSUE THREAD

**Issue by liorpr** [framer/motion#1199]
Hi, thanks for building this awesome library.

I was looking at this example: [https://codesandbox.io/s/app-store-ui-using-react-and-framer-motion-ecgc2](url)
and noticed it's using an old version of framer motion, where some apis are deprecated, would be really nice to have this example update its dependency to the latest framer motion version.

**Comment by tommyboylab** [comment]
I'm currently looking into the same thing a few years later.. I like the example but would like to know the proper way to implement this with later versions of Framer.

I've gotten it running with later versions, but it seems migrating it from Framer 1  to 2 it breaks the drag functionality (unable to trigger the exit) then bumping to version 5 onwards drag works again, but now causes the elements to re-position themselves to the center of the viewport after drag.

Only thing I really did was upgrade deps, migrate router and framer to use layout

This is my first real look at framer motion so I'm not knowledgeable enough to understand what is happening, but if anyone has some experience with it it would be awesome to update this example.


Here's a gif up to/after v5 with same element triggers:
![drag](https://user-images.githubusercontent.com/44362297/225967555-d347f8e8-712f-40e1-85db-f6c394d16050.gif)

**Comment by mattgperry** [comment]
Apologises but I'm probably not going to find the time to port this example. It's not necessarily even possible to mix the drag gesture in a good way currently.

**Comment by BjoernRave** [comment]
@tommyboylab did you make any progress in making the example work with the latest framer motion? Would be interested if you figured something out :)

**Comment by mattgperry** [comment]
Found the time: https://codesandbox.io/p/sandbox/framer-motion-app-store-demo-su6mx?file=%2Fsrc%2FItem.js

**Comment by chasemccoy** [comment]
This is awesome @mattgperry, thanks! Heads up you might wanna update the link to the old example on this page: https://www.framer.com/motion/examples/#%23ui-patterns
