### ISSUE TITLE
[BUG] Children of layout animated parents do not (or only partly) use same custom duration as parent

### ISSUE THREAD

**Issue by WDeenik** [framer/motion#1203]
**1. Read the [FAQs](#faqs) 👇 ✅ **

**2. Describe the bug**

When you have a layout animated parent with children that also need a `layout` to prevent distortion, those children do not (or only partly?) use the same custom animation duration as their parent.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/fervent-sun-ypprj

**4. Steps to reproduce**

1. Go to the above mentioned sandbox
2. Click on the left 'expand' button. The parent expands to a fixed postion, and the expand button compensates for distortion like it should.
3. Click on the right 'expand' button. This parent expands with a custom delay. Now the expand button seems to use the default duration for its Y movement, while its X movement seems to use the parent's custom duration.

**5. Expected behavior**

I would have expected them to fully use the custom duration of their parent by default, so only setting `layout` on them would 100% prevent distortion. Now it results in quite weird behaviour until you explicitly set the same custom duration on the children as on their parent.

**6. Video or screenshots**

https://user-images.githubusercontent.com/22861287/124254760-ad25a680-db29-11eb-9988-b3a9b58914e7.mov

**7. Environment details**

MacOS, Chrome 91.0.4472.114

**Comment by mattgperry** [comment]
`transition` is not inherited. You can set a default `transition` for a tree using `MotionConfig`

```jsx
<MotionConfig transition={{ duration }}>
  {children}
</MotionConfig>
```
