### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jzequn** [framer/motion#1215]
**1. please fix this bug** 
So that I can generate random length of array for x,y,z properties of animate.

**2. Describe the bug**
I got this error on CodeSandbox
```shell
/node_modules/popmotion/dist/es/utils/
interpolate.js
mixers[mixerIndex] is not a function
browser
```

or this one on chrome
```shell
interpolate.js:72 Uncaught TypeError: mixers[mixerIndex] is not a function
    at interpolate.js:72
    at interpolate.js:91
    at Object.next (keyframes.js:31)
    at update (index.js:60)
    at passTimestamp (index.js:10)
    at Object.process (create-render-step.js:37)
    at processStep (index.js:44)
    at Array.forEach (<anonymous>)
    at processFrame (index.js:51)
```

So basically, this bug happen when I try to assign an array with only one single value to x or y or z property of animate. 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
[CodeSandbox](https://codesandbox.io/s/small-tdd-7d51o?file=/src/App.js)

**4. Steps to reproduce**

1. Go to [CodeSandbox](https://codesandbox.io/s/small-tdd-7d51o?file=/src/App.js)
2. See a problem on problem tab next to console tab.

**5. Expected behavior**

'hi there' text should move to the right for about 10px. 
It never happen because of this bug when [10] is assigned to x.

**Comment by mattgperry** [comment]
Arrays accept 2 or more values - you can put in `x: [null, 10]` or `x: [0, 10]`

**Comment by jzequn** [comment]
Okey, thanks for the solution. However, I still think it would be a good idea to accept single value for array. I will close this issue anyway.
