### ISSUE TITLE
[BUG] SnapToCursor not working in version 4.1.12 and upwards.

### ISSUE THREAD

**Issue by Glazzy** [framer/motion#1216]
**Describe the bug**

Using the dragControls and passing { snapToCursor: true } does not work as intended. The snapping to the cursor does not occour when clicking, but only when i click and start dragging. This worked as intended in version **4.1.11**

**CodeSandbox reproduction of the bug**
https://codesandbox.io/s/framer-motion-usedragcontrols-forked-8t0qn?file=/src/App.js:385-451

**Steps to reproduce**
1. Click anywhere on the rail ( notice how the knob does not snap to the cursor )
2. Click anwhere on the rail and hold down the mouse and start dragging ( notice how it now works )
3. Try and switch to version 4.1.11 and do the first step again ( notice how everything works as intended now the knob correctly snaps to the cursor )

**Expected behavior**
Expected Knob to snap to cursor upon clicking on the rail

**Comment by mattgperry** [comment]
Fixed in 5
