### ISSUE TITLE
[BUG] Dragged elements keep a transform property at rest, breaking position: sticky

### ISSUE THREAD

**Issue by andrewmarg** [framer/motion#1217]
**Describe the bug**

Dragged elements have  ```transform: translate3d(0px, 0px, 0px) scale(1, 1)``` after drag ends. The transform property creates a new stacking context, which breaks sticky-positioned elements.

https://codesandbox.io/s/competent-sunset-g72kj?file=/src/App.js

**Steps to reproduce**

1. Drag a <motion.div>
2. It will now pass over rather than under a sticky element when the page is scrolled.

**Expected behavior**

When a dragged element at rest has no transformation, it shouldn't have a transform property.

**Comment by mattgperry** [comment]
Fixed in 5
