### ISSUE TITLE
Set Transform to none on transition end

### ISSUE THREAD

**Issue by DanielLuu** [framer/motion#1218]
**Is your feature request related to a problem? Please describe.**
I'm having an issue where I have a modal that is position: fixed inside of an element that has a transform animation

**Describe the solution you'd like**
Being able to set the transform to none after the animation ends

**Describe alternatives you've considered**
I've considered using JS to pin my modal to the top of the scroll window but it's jerky at best

**Comment by dnlmzw** [comment]
+1

Tried the following, but it seems to be reset every time the component rerenders:

```
onAnimationComplete={() => {
  setTimeout(() => {
    document.querySelector('.element').style.transform =
      'none'
  }, 1)
}}
```

**Comment by mattgperry** [comment]
Are you animating independent transforms? If so, you can set these to default via `transitionEnd` ala

```
animate={{
  x: 100,
  transitionEnd: { x: 0 }
}}
```
