### ISSUE TITLE
[FEATURE] Allow 'custom' dependent variant to be returned in useAnimation controls

### ISSUE THREAD

**Issue by mrbjjackson** [framer/motion#1219]
Hi,

I'm trying to orchestrate some animations using `controls.start()`.

I want these animations to be dependent on a `custom` prop.

But instead of changing an _animation object_ passed to `controls.start` I would like to use logic to return a variant dependent on the `custom` prop passed to the component.

For example:

**Variants:**
```
variants: {
   hidden: {
      opacity: 0
   },
   visible: {
      opacity: 1
   }
}
```

Components: 
```
<motion.section animate={controls} custom={'section1'} variants={variants} initial='hidden'>Section 1</motion.section>

<motion.section animate={controls} custom={'section2'} variants={variants} initial='hidden'>Section 2</motion.section>
```

Animation controls:
```
await controls.start( section => {
   if(section === sectionWeWantToShow) {
      return ('visible')
   } else {
      return ('hidden')
   }
}
)
```

In this example I want to make Section 1 or Section 2 visible based on what the value of `sectionWeWantToShow` is set to.

I can get a dynamic `controls.start` to work if I return an animation object ([as described in the docs](https://www.framer.com/docs/animation/##dynamic-start)) and I can pass a static variant value to `controls.start()` e.g. `controls.start('visible')` but if I try to dynamically generate the variant to pass to `controls.start`, I get an error: 

_"Failed to set an indexed property on 'CSSStyleDeclaration': Indexed property setter is not supported."_

It's possible this functionality does exist, I'm just doing something wrong, but if not, it seems like a good feature to suggest.

Many thanks,
Ben

**Comment by mattgperry** [comment]
`useAnimationControls` is deprecated and there's currently no functionality to trigger variants from `animate()` so it's unlikely this will be implemented.
