### ISSUE TITLE
[BUG] StaggeredChildren does not loop infinitely

### ISSUE THREAD

**Issue by ilknureren** [framer/motion#1220]
**1. Describe the bug**
**StaggeredChildren does not loop infinitely.**
I want to have a component where staggeredChildren display divs on screen one by one then loops back to the beginning again after all of the divs are displayed. 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/tender-feather-6lmtb?file=/src/App.js

**4. Steps to reproduce**
1. Go to https://codesandbox.io/s/tender-feather-6lmtb?file=/src/App.js
2. On top of the page, I have a staggeredChildren component where repeat infinite. does not work.
3. Second example of where repeat infinite does work, but we don't define staggeredChildren.

**5. Expected behavior**
The first example should 
1. Display, one, two, three like the way it does now.
2. After 3, one, two, three should go back to hidden with opacity:0
3. After it is hidden, it should start in the beginning again, displaying, one, two,  three
4. Repeat infinitely.

**Comment by mattgperry** [comment]
What's happening here is it looks like the example without `staggeredChildren` is working as expecting but really it's just that the container opacity animation is repeating infinity. 

Having `repeat: Infinity` work in a nested way would be a big change and probably isn't something that will be looked at soon, but it is something you can accomplish with the current API.

Personally I would use the animation controls for this:

```
  const controls = useAnimation();

  useEffect(() => {
    async function animate() {
      while (true) {
        await controls.start("show");
        controls.set("hidden");
      }
    }
    animate();
  });
```

https://codesandbox.io/s/priceless-hill-kcn4n?file=/src/App.js:350-562
