### ISSUE TITLE
[BUG]: `whileTap` should have priority over `whileFocus`

### ISSUE THREAD

**Issue by smeijer** [framer/motion#1221]
**Describe the bug**

I believe that `whileTap` should have priority over `whileFocus`

**IMPORTANT: Provide a CodeSandbox reproduction of the bug**

A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

https://codesandbox.io/s/framer-motion-focus-zz81e?file=/src/App.js

**Steps to reproduce**

1. Open the sandbox
2. Click on a few times on both buttons
3. The one that uses `whileFocus`, never shows the `>` on the `whileTap` position

**Expected behavior**
As I need to focus an element, before I'm able to "tap" it, I believe that Tap transforms should take priority over focus transforms.

**Video or screenshots**

https://user-images.githubusercontent.com/1196524/125958540-4876764d-bb8d-4ba6-a102-014a67d958b4.mp4

**Environment details**

```
browser:   Chrome 91.0.4472.77
os:        Linux, Ubuntu 20.04
```

**Comment by gilsonnunesfilho** [comment]
Any updates on this? Seems that whileFocus still blocks whileTap on my projects.
