### ISSUE TITLE
[FEATURE] Variants don't take MotionValues

### ISSUE THREAD

**Issue by controversial** [framer/motion#1222]
**Describe the bug**
Variants don't take MotionValues. If a variant is defined with one of its values as a MotionValue, that value won't be animated to.

**Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-variant-motion-values-khcxz?file=/src/App.js

The first div has its variants defined using Numbers in their values. The second div has its variants defined using MotionValues. Clicking the button changes the variant on both, but only the first animates.

**Steps to reproduce**

1. Define a component with variants
2. Set the values in the variants to use motionvalues
3. Try switching the variant

**Expected behavior**

I expect that when variants are defined using motion values, everything “just works.” In my case, the value that I need to use in the variant rapidly changes with cursor position. By setting the variant’s value to use a MotionValue, I had hoped to have the following:
1. When animating to that variant, the animation targets the value of the MotionValue
2. Once that variant is selected as the current variant, the component‘s style will follow the current value of the MotionValue exactly.
3. Once that variant is no longer the selected variant, the component animates from the latest value of the MotionValue

I tried replacing the motionvalue with `mv.get()`, but this obviously prevents the component from following the motionvalue when that variant is selected, unless the component re-renders.

**Comment by apfelbox** [comment]
This one would be **_really_** helpful.

Especially if you are animation multiple values, as `useTransform` can't produce a map of motion values (as that would be `MotionValue<{...}>` instead of the required `{MotionValue<>, ..}` inside `style`).
So right now you need to do separate `useTransform` calls (one per property) instead of just a single one where you conveniently set the variant.

**Comment by mattgperry** [comment]
I appreciate the idea but realistically it's unlikely to happen unless we come to want that functionaity in Framer so to set expectations I'm closing as a `wontfix`.
