### ISSUE TITLE
[BUG] Animation lagging with simple translation / opacity

### ISSUE THREAD

**Issue by Aarbel** [framer/motion#1229]
Hi, i have a performance issue with `AnimatePresence` (see code / video bellow). The animation lags to open a simple Drawer on the side.

Do you know how i can solve this problem ? Can it be a javascript animation problem ? Do you really use pure CSS GPU accelerated animations ?

![image](https://user-images.githubusercontent.com/25119847/127371954-2e1b1514-eeb7-4551-9e1a-8b2b90eb681e.png)

https://user-images.githubusercontent.com/25119847/127371918-836a9569-69ff-49cc-8f05-487b075e122c.mp4

**Comment by mattgperry** [comment]
Have you tried setting `will-change: opacity` to the element animating opacity?

**Comment by Aarbel** [comment]
@mattgperry i will check. This is not automatically added by framer-motion ?

**Comment by mattgperry** [comment]
We add `translateZ(0)` to transforms but other styles have to be handled by
users currently. `will-change` isn't side-effect free, maybe this is
changing with better browser support but there are trade-offs involved that
I'd have to look into before making it automatic.

**Comment by Aarbel** [comment]
@mattgperry thanks a lot !

Did you putted the info in the framer animation doc ? I think it could be a good point in https://www.framer.com/docs/introduction/

**Comment by Aarbel** [comment]
@mattgperry fixed ?
