### ISSUE TITLE
parent div display flex row makes children motion laggy at the beginning. 

### ISSUE THREAD

**Issue by nnguyen52** [framer/motion#1230]
**2. 
Parent div display as flex row makes motion child lag when rendering at the beginning. But not displaying at flexbox , it animates snoothly. 

**3. CodeSandbox reproduction of the bug
https://codesandbox.io/s/exciting-clarke-f7fky?file=/src/App.js

**4. Steps to reproduce**

if you remove line 36 (display : flex) it anitmates smoothly, but having this make it laggy at very beginning.

**5. Expected behavior:
i expected to see it animate as smooth as without displaying flex.

**Comment by singlexyz** [comment]
I think the problem is animate the img before it loaded.

**Comment by nnguyen52** [comment]
how cani fix this issue ? :<

**Comment by rbourdon** [comment]
> 
> 
> how cani fix this issue ? :<

You need to use smaller images. Those images are enormous (largest is 5760x3840) and you are only displaying them at 100x100. I think the difference with flex is only because it makes them overlap as they animate.

**Comment by nnguyen52** [comment]
thank you @rbourdon!  i will try, honestly i pull some random image online, i didnt considered scaling it down. :3
