### ISSUE TITLE
[FEATURE] No link to code example

### ISSUE THREAD

**Issue by ovidubya** [framer/motion#1232]
**Describe the solution you'd like**
Would it be possible to include a link to a code sandbox or codepen to the following example shown in https://framer.com/motion 

## Example 
<img width="1454" alt="Screen Shot 2021-08-03 at 12 45 57 PM" src="https://user-images.githubusercontent.com/22357156/128061898-ce3d4afc-1c2a-48d5-b7ca-385bfdd4fd92.png">

**Comment by o-alexandrov** [comment]
duplicate of https://github.com/framer/motion/issues/905

**Comment by mattgperry** [comment]
Closing as a `wontfix` as I'm unlikely to find the time for this one.
