### ISSUE TITLE
Support Legacy React 15?

### ISSUE THREAD

**Issue by MovingGifts** [framer/motion#1235]
Hello,

Our app is stuck on an older version of React, 15.6.2 to be exact. At this point we can't upgrade the React version since a lot of things will break that were built on the older version and the respective dependency packages.

Any idea if there is way to use the motion framework with that react version?

Note: We tried to downgrade one of the motion codepen's react/react dom dependecy version to 15.6.2 and we got the following error:
![image](https://user-images.githubusercontent.com/1202909/128657521-fcb753cc-af24-4d9c-84f2-afd1b5aee85e.png)

**Comment by mattgperry** [comment]
Hi there, I'm afraid not. Motion makes extensive use of hooks which were introduced in `16.8` - probably some other APIs too.
