### ISSUE TITLE
AnimationProvider for improved orchestration

### ISSUE THREAD

**Issue by malerba118** [framer/motion#1236]
**Is your feature request related to a problem? Please describe.**
I've dabbled with framer-motion in the past but for the first time i'm starting to use it in a more serious project and i'm finding myself wishing for better tooling around orchestration. `'beforeChildren'` and `'afterChildren'` are limited to parent-child relationships and feel limited in their capabilities. `useAnimation` is a nice way to get more granular control over animation sequences but it's still difficult to pass controls around the app to where you need them. 

**Describe the solution you'd like**
I'm dabbling with an API right now that augments `useAnimation` and allows sharing of `AnimationControls` across the app via react context. The idea is give each `AnimationControls` an id and then maintain them in a global store that can be accessed through context. Here's a userland example of the api i'm imagining ([codesandbox](https://codesandbox.io/s/animationprovider-fli1h?file=/src/App.js)):

```jsx
// index.jsx
import React from "react";
import ReactDOM from "react-dom";
import App from "./App";
import { AnimationProvider } from "./AnimationProvider";

const rootElement = document.getElementById("root");
ReactDOM.render(
  <React.StrictMode>
    <AnimationProvider>
      <App />
    </AnimationProvider>
  </React.StrictMode>,
  rootElement
);
```

 ```jsx
// App.jsx
import React from "react";
import { motion } from "framer-motion";
import Image from "./Image";
import { useAnimation } from "./AnimationProvider";
import "./styles.css";

const variants = {
  content: {
    visible: {
      opacity: 1
    },
    hidden: {
      opacity: 0
    }
  }
};

export default function App() {
  const controls = useAnimation();
  // Listen to image animation and do something when it's done
  useAnimation({
    id: "image-status",
    onChange: async ({ animation, variant }) => {
      if (variant === "loaded") {
        await animation;
        controls.start("visible");
      }
    }
  });

  return (
    <div>
      <Image src="http://placekitten.com/300/300" />
      <motion.p initial="hidden" variants={variants.content} animate={controls}>
        hello
      </motion.p>
    </div>
  );
}
```

```jsx
// Image.jsx
import React, { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { useAnimation } from "./AnimationProvider";

const variants = {
  image: {
    loading: {
      opacity: 0
    },
    loaded: {
      opacity: 1,
      transition: {
        duration: 1
      }
    }
  }
};

const Image = ({ src, ...otherProps }) => {
  const [status, setStatus] = useState("loading");
  const controls = useAnimation({ id: "image-status" });

  useEffect(() => {
    controls.start(status);
  }, [status]);

  return (
    <motion.img
      initial="loading"
      animate={controls}
      variants={variants.image}
      src={src}
      onLoad={() => setStatus("loaded")}
      onError={() => setStatus("errored")}
    />
  );
};

export default Image;
```

My overarching goal in my project right now is to create standalone reusable components like `Image` that manage their own controls internally, but still allow observability into their animations for the app that's consuming them. There's certainly some finer details that would need to be addressed with an api like this such as mounting and lifecycle. Though one nice thing is i think this could be done in a backward compatible manner so that `useAnimation` invoked with no arguments would still work as before and would not need to be wrapped in a provider because in absence of a provider it could still just create the animation controls locally.

**Comment by malerba118** [comment]
Here's a slightly different flavor i'm considering which allows before/after hooks, also made `id` a positional param here. I think more correctly `variant` should be called definition and could just be an inline animation object as well, but omitting that for now just to try to convey my primary use-case with clarity.

```tsx
type useAnimation = (
  id?: string,
  options?: {
    before?: ({ variant: string }) => Promise<void>; // do something before animation starts
    after?: ({ variant: string }) => void; // do something after animation completes
  }
) => AnimationControls;
```

**Comment by mattgperry** [comment]
Closing this out as `animate()` with timeline sequencing is the orchestration solution
