### ISSUE TITLE
[BUG] clipPath doesn't animate between components when using AnimateSharedLayout and React key is different

### ISSUE THREAD

**Issue by kkirby** [framer/motion#1237]
I'm not entirely sure this is a bug because it's technically not a layout property; though neither is `background-color` or `border-color`, and those animate when using `AnimateSharedLayout`. Anyways, the issue is that `clipPath` isn't animating between two elements when using `AnimateSharedLayout` with a `layoutId`. It appears to work if the React `key` remains the same, however, if the `key` mutates, it does not work. Although background-color still animates when the `key` is different. There is also some weird layout animation oddities when using a key vs not using a key.

## CodeSandbox

https://codesandbox.io/s/boring-leftpad-xxzh0?file=/src/App.tsx

## Steps to reproduce

Click on the circle to animate the position and clip path

## Expected behavior

I would expect the clipPath to animate with the backgroundColor

## Video or screenshots

https://user-images.githubusercontent.com/34333/129035761-24c95bc7-ea6e-4f64-b512-57f8a217b1d4.mp4

## Environment details

MacOS 11.4, Chrome Version 92.0.4515.131 (Official Build) (x86_64)

**Comment by mattgperry** [comment]
I think this continuation of values isn't supported any more (prefering opacity to blend between the two) so closing as a `wontfix`.
