### ISSUE TITLE
[BUG] ScaleX works with percentages on chrome, but only with floating points between 0 and 1 on Safari

### ISSUE THREAD

**Issue by wahidshafique** [framer/motion#1238]
While trying to scale a progress bar, I noticed an issue where it was not working on Safari. After some testing, I realized that on Chrome and Firefox, percent values are valid for something like scaleX.

```
const value = 50
// somewhere below
animate={{
          originX: 0,
          scaleX: `${value}%`,
        }}
```

However, the same values do NOT work in Safari. What does work, is any normalized value from 0-1 (not a percent).

```
const value = 0.5
// somewhere below
animate={{
          originX: 0,
          scaleX: `${value}`,
        }}
```

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-scalex-different-in-safari-vs-chrome-h10hd?file=/src/App.tsx

**4. Steps to reproduce**

1. Try to play with the slider on Chrome, it should work
2. Now try the same thing in Safari

**5. Expected behavior**
It should work the same, animating to the intended percentage value, on both browsers

**Comment by mattgperry** [comment]
Scale is defined as a number where `1` = actual size. Percentages are not defined in the spec and any browser support is against spec. Safari will probably never support this and Chrome/Firefox could end support at any time.

**Comment by wahidshafique** [comment]
> Scale is defined as a number where `1` = actual size. Percentages are not defined in the spec and any browser support is against spec. Safari will probably never support this and Chrome/Firefox could end support at any time.

To followup, when I _do_ use numbers, it does not animate anymore, `50%` animates fine, whereas `0.5` does not.
