### ISSUE TITLE
[BUG] MotionValue is not changing on elements with layoutId

### ISSUE THREAD

**Issue by vavra7** [framer/motion#1242]
**Describe the bug**

MotionValue doesn't work on elements with layoutId.

**Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-layoutid-motion-value-bug-4wtjl

**Expected behavior**

I expect that dragging of element will propagate its position into respective MotionValue. Then it can be possible to use the value the same way as you use it in function "checkSwipeToDismiss" in following [example](https://codesandbox.io/s/app-store-ui-using-react-and-framer-motion-ecgc2?file=/src/Card/index.tsx:1433-1452).

**Comment by mattgperry** [comment]
Fixed in 5
