### ISSUE TITLE
[BUG] Layout animation: Border radius not animating correctly when using rem

### ISSUE THREAD

**Issue by Julian-Sz** [framer/motion#1243]
## I am animating expanding cards with AnimateSharedLayout.

 - When the `border-radius` unit is `px` (or `%`), it animates correctly, as seen here:
https://codesandbox.io/s/animate-projects-with-animatesharedlayout-borderradius-in-px-bpjgk

 - However, if I set the `border-radius` in `rem`, it jumps around:
https://codesandbox.io/s/animate-projects-with-animatesharedlayout-borderradius-in-rem-76qsh?file=/src/App.js

 - This bug also appears when I use `vw` or `vh` (but nobody ever does that)
 https://codesandbox.io/s/animate-projects-with-animatesharedlayout-borderradius-in-vw-cs1e8
 
### I've created a minimal, reproducible example here:

-  https://codesandbox.io/s/animate-card-minimal-ty19u
(It also works when I change `rem` to `px`)

### The bug only occurs when the layout gets animated, a normal animation works fine with `rem`:
https://codesandbox.io/s/animate-borderradius-with-rem-x176g
 
 #### Tested on:
 Chrome version 92.0.4515.159 (Windows 10)
 Framer Motion version 4.1.17

**Comment by mattgperry** [comment]
This is because Framer Motion doesn't support scale correction for rem border-radius and it probably won't. I'll update the docs to make a note of this.

**Comment by 66990208** [comment]
> This is because Framer Motion doesn't support scale correction for rem border-radius and it probably won't. I'll update the docs to make a note of this.

Will vw and vh be supported in the future?
