### ISSUE TITLE
[BUG] dragging after showing a motion component via <select> doesn't work

### ISSUE THREAD

**Issue by ianstormtaylor** [framer/motion#1244]
**2. Describe the bug**

If you render a draggable motion component as the result of a `<select>` change event, for some reason the `onDrag` handler is not bound correctly and fails the first time you try to drag it—it just stays in place. However, trying to drag it a second time makes it work... very strange.

This only happens in Safari on macOS. (Or at least it doesn't happen in Edge/Chrome.)

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-drag-with-constraints-forked-2tc47?file=/src/index.tsx

**4. Steps to reproduce**

1. Go to the sandbox (copied from draggable example)
2. Use the `<select>` in the top left and "show" the example
3. Try to drag the box
4. Nothing will happen
5. Try to drag the box again
6. It will drag properly

**5. Expected behavior**

It should work the first time.

**6. Video or screenshots**

![](http://g.recordit.co/aGzVH5vElQ.gif)

**7. Environment details**

macOS 10.15
Safari 14.0

**Comment by mattgperry** [comment]
This one was confusing! But then I found this ticket: https://bugs.webkit.org/show_bug.cgi?id=232123

It's appears to be not so much that the element is being newly rendered but that the previous click was on a context menu.
