### ISSUE TITLE
[BUG] Offset between the cursor and the dragged element when the page is scrolled down

### ISSUE THREAD

**Issue by sinnerJoe** [framer/motion#1245]
**1. Describe the bug**

When dragging an element with ```drag={true}``` prop set,  and the page scrolled down at the same time, the dragged element will be rendered lower than the cursor by the amount of scroll down.

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/drag-layout-flicker-forked-sf8jz

**3. Steps to reproduce**
1. Go to the code sandbox link above.
2. Scroll to the bottom of the page
3. Drag any of the rectangles up.
4. Observe the offset between the cursor and the dragged rectangle in the process of dragging.

**5. Expected behavior**

I expect the rectangle to be positioned under the cursor in the same way it was when I started dragging itl

**6. Environment details**

Artix Linux, Firefox 89 (64 bit)

**Comment by WNemencha** [comment]
On my side fixed this by using `framer-motion@4.1.1` (not `^4.1.1`) which seems to not have the bug/regression inside ;)

**Comment by mattgperry** [comment]
Fixed in https://codesandbox.io/s/drag-layout-flicker-forked-evrzk?file=/src/App.tsx
