### ISSUE TITLE
[BUG] Use null value in keyframe

### ISSUE THREAD

**Issue by WesselKoorn** [framer/motion#1252]
Hi!

I'm trying to do something pretty straightforward, yet I can't figure out how to do it. I want to create a sequence where the z-index is first set to 1, and the width is set to 100% after. And a reversed one where the width is set to 50% first and z-index to 0 after.

The following variants works, but when it's mid-animation and it should revert it first jumps to 100% before going to 50%:

```
const variants = {
    open: {
      width: ["50%", "100%"],
      "z-index": [1, 1]
    },
    closed: {
      width: ["100%", "50%"],
      "z-index": [1, 0]
    }
  };
```

I read in [the docs](https://www.framer.com/docs/animation/##keyframes) that you can specify `null` as initial value so it animates from whatever the current value is:

```
const variants = {
    open: {
      width: [null, "100%"],
      "z-index": [1, 1]
    },
    closed: {
      width: [null, "50%"],
      "z-index": [1, 0]
    }
  };
```

But it throws the following error:

```
Keyframes must be of the same dimension as the current value
```

Here's a reproduction in Sandbox: https://codesandbox.io/s/pedantic-roman-o7odb?file=/src/App.tsx

Thanks!

**Comment by mattgperry** [comment]
Fixed in `5.x`
