### ISSUE TITLE
onPan not called after rerenders (v4.0.0+)

### ISSUE THREAD

**Issue by rijk** [framer/motion#1257]
**Describe the bug**

Somehow when `onTapStart` performs multiple state updates, `onPan` is no longer called while dragging. This used to work in v3 but has broken since v4.

**CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-pan-tap-9fo29?file=/src/App.js

**Steps to reproduce**

1. Click and drag in the white square
2. Observe: "panning" logged to console
3. Activate a second state update in `onTapStart`
4. Observe: nothing logged to console when dragging

**Expected behavior**

I don't know why it is no longer working, but it would be difficult to work around this.

**Comment by rijk** [comment]
It probably has to do with this: https://github.com/framer/motion/blob/f8d08b271ae9b021521d0b80cdf1b3f787ccde13/src/gestures/use-pan-gesture.ts#L14-L16

**Comment by mattgperry** [comment]
Can't reproduce in `latest`
