### ISSUE TITLE
[FEATURE] Better documentation

### ISSUE THREAD

**Issue by j2is** [framer/motion#1258]
Wish the documentation was better, it's missing how to include and use things.

For example I'm looking for how to use `controls`. I go to https://www.framer.com/docs/utilities.

The first example is:
```
// With properties
controls.set({ opacity: 0 })

// With variants
controls.set("hidden")
```

It's missing that there's an useAnimation hook. It would be nice to include the following before the shorthand:
```
import { motion, useAnimation} from 'framer-motion';

export default function(){
    const controls = useAnimation();
   return(<motion.div animate={controls} >);
}
```

**Comment by mattgperry** [comment]
Added this snippet!
