### ISSUE TITLE
[BUG] Exit animation not working next js

### ISSUE THREAD

**Issue by adamjw3** [framer/motion#1259]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

Exit animations not working

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://next-js-boilerplate-roan.vercel.app/

**4. Steps to reproduce**

i have the following transition to fade in and out a page

```
export const fade = {
    initial: { opacity: 0 },
    enter: {
        opacity: 1,
        transition: { duration: 0.4, ease: [0.83, 0, 0.17, 1] },
    },
    exit: {
        opacity: 0,
        transition: { delay: 10, duration: 9000, ease: [0.83, 0, 0.17, 1] },
    },
};
```

Adding this as a variant

`<motion.div initial="initial" animate="enter" exit="exit" className={styles.maincontent}>
                <motion.div variants={fade}>
                    <h1 className="heading">Contact</h1>
                    <br />
                    <p className="para">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin fermentum lectus eu faucibus accumsan. Nulla erat metus, sagittis et dolor id, ultrices venenatis metus. Vivamus
                        ultrices massa ut lectus cursus sollicitudin. Suspendisse at purus vulputate, venenatis magna a, gravida quam. Vivamus non congue nibh, nec dignissim lectus. Morbi id odio
                        auctor tellus blandit dignissim. Sed non convallis orci. Nulla facilisis tellus at tellus vehicula gravida. Nam ex diam, eleifend sit amet consectetur non, finibus posuere
                        velit. Nunc ut augue varius, dapibus risus at, malesuada ligula.
                    </p>
                    <br />
                    <p className="para">
                        Aliquam condimentum quam quam, ac finibus sem consectetur vitae. Etiam vel placerat mauris, a feugiat ligula. Integer efficitur massa facilisis, ornare ex eget, commodo elit.
                        Nam id nulla dapibus, fermentum tortor ac, viverra est. Pellentesque sodales tristique condimentum. Praesent porttitor laoreet aliquet. Maecenas in ornare ipsum. Vestibulum
                        dictum egestas scelerisque. Donec arcu lacus, laoreet vitae tellus a, ullamcorper scelerisque nulla. Nullam at luctus leo. Integer pharetra consectetur erat, ut vehicula lectus
                        rhoncus sed. In at bibendum neque. Nullam ut nunc fringilla, congue eros vitae, ultricies sapien. Proin tempus risus sit amet mi vestibulum euismod. Sed posuere lacinia enim,
                        sed ornare ex congue ac.
                    </p>
                    <br />
                    <FancyLink destination="/about" a11yText="link to main page" label="Home" />
                </motion.div>
            </motion.div>`

i added a duration of 10 secs to the exit animation as i thought it wasn't getting fired and its not.

i'm using next js and in my _app.js i have the following as recommended. notice the exitbeforeeneter.

` <AnimateSharedLayout>
            <AnimatePresence exitBeforeEnter>
                <Component {...pageProps} />
            </AnimatePresence>
        </AnimateSharedLayout>`

**5. Expected behavior**

The exit to take 10 secs and then go to the clicked page.

This might be a newbie question but its my first week with framer motion

**Comment by MatteoGauthier** [comment]
don't work for me to
