### ISSUE TITLE
[FEATURE] AnimateSharedLayout exit transitions that don't keep the original elements in-layout

### ISSUE THREAD

**Issue by zxti** [framer/motion#1267]
Shorter version: How can we enable layout transitions where the exiting elements (cross-)fade out (like Framer's Magic Motion transitions), without needing users manually set absolute positions and sizes on their exiting DOM tree just for the transition?

Longer version:

Currently, when using AnimateSharedLayout to transition between two different DOM trees, you can't have exit transitions without AnimatePresence.

Unfortunately, the way `AnimatePresence` works is it keeps the exiting tree in-layout. This is almost never what you want for these transitions.

I believe it might be possible in userland to accomplish this using `usePresence`—as soon as we are no longer present, measure the DOM node's dimensions and set that explicit with position:absolute.

This is something I miss from the great [react-flip-toolkit](https://github.com/aholachek/react-flip-toolkit). Exiting elements are kept in-tree but taken out of layout, which enables the exit fade transitions you see when filtering the list: https://react-flip-toolkit.surge.sh/

Out of curiosity, how is this handled with Framer's Magic Motion transitions? I'm assuming it's because Framer gets to fully control its layout system and can thus make the whole exiting and entering screen absolutely positioned.

**Comment by zxti** [comment]
Another interesting somewhat-related bit from react-flip-toolkit is it doesn't need AnimatePresence—it uses portals to keep around the exiting elements.

**Comment by mattgperry** [comment]
To set expectations if this isn't covered by `AnimatePresence` and its `mode="popLayout"` then it's unlikely to be implemented.
