### ISSUE TITLE
[BUG] Using a cloneElement that is in sync with layout changes breaks AnimateSharedLayout+AnimatePresence

### ISSUE THREAD

**Issue by zxti** [framer/motion#1269]
https://codesandbox.io/s/relaxed-curie-3qo4p?file=/src/App.tsx

Both left and right sides show an AnimateSharedLayout crossfade transition. The left one works as expected; the right one doesn't crossfade / doesn't keep around the exiting element in the AnimatePresence.

The only difference between them is that the right one is wrapped in a component that does a `cloneElement` at intervals that match the shared layout transition changes.

Expected behavior is that both sides are the same.

I believe any of the following will result in the crossfade working again:

- Remove the interval on the CycleTimer, and just issue a cloneElement once
- Changing CycleTimer's interval to be very different from the interval on the Example2 component
- Remove the cloneElement and just render children

**Comment by mattgperry** [comment]
Fixed in latest: https://codesandbox.io/s/brave-lovelace-1cn8s?file=/src/App.tsx
