### ISSUE TITLE
[BUG] Presence of an additional AnimatePresence breaks crossfading AnimateSharedLayout

### ISSUE THREAD

**Issue by zxti** [framer/motion#1270]
https://codesandbox.io/s/eager-glitter-z5e69?file=/src/App.tsx

Simply adding another AnimatePresence (at the bottom) causes the entire AnimateSharedLayout crossfade not work.

Expected behavior: Try replacing "broken" with "", and you'll see the working transition.

**Comment by mattgperry** [comment]
If you try out the latest version you can see this is fixed: https://codesandbox.io/s/cool-kate-0qyg1?file=/src/App.tsx
