### ISSUE TITLE
[FEATURE] Provide "full view"s examples, maybe help Framer community to share examples in a public playground

### ISSUE THREAD

**Issue by Aarbel** [framer/motion#1278]
Hi Framer team,

**Framer documentation provides a lot of animations / examples for "atomic" animations (cf https://www.framer.com/docs/examples/), but that would be wonderful to have simple "full view"s examples to just start to animate an existing app (with lists, dashboards, cards).**

Maybe also having a playground to quickly see / copy the possibilities that Framer community offers would be a great thing, https://threejs.org/ and webgl ecosystem does it well !

# Examples

https://user-images.githubusercontent.com/25119847/134807663-334ffe89-7da1-457a-ae3d-b8858b1f4197.mp4

https://user-images.githubusercontent.com/25119847/134807699-d152105d-dbdb-43bc-828a-d0744212cdb3.mp4

# More examples links

https://dribbble.com/shots/14108605-Star-Game-Dashboard
https://dribbble.com/shots/15911425-Payroll-Hr-Management-Platform
https://dribbble.com/shots/16475541-Financial-dashboard-animation
https://dribbble.com/shots/15595097-Finezjo-Dashboard-interactions
https://dribbble.com/shots/16147301-Pryon-analytics-UI
https://dribbble.com/shots/15502621-Deadly-Virus-Information-Dashboard-Concept
https://dribbble.com/shots/16040796-AI-Web-Dashboard-Concured
https://dribbble.com/shots/14699615-Time-Logging-Interaction-Project-Management-App
https://dribbble.com/shots/16160951-Real-Estate-Platform
https://dribbble.com/shots/14688430-Basis-dashboard-UI-interaction-design

**Comment by mattgperry** [comment]
These look really nice but I think it's unlikely this will be made as we concentrate on showcasing Framer sites.

**Comment by Aarbel** [comment]
@mattgperry 😭🥹😿
