### ISSUE TITLE
[BUG] Transform does not transition properly when component mounts

### ISSUE THREAD

**Issue by rbhalla** [framer/motion#1284]
**Describe the bug**

When using `AnimatePresence`, the `transform` property only correctly transitions when the component unmounts.

**CodeSandbox reproduction of the bug**

https://codepen.io/rb03/pen/WNOBOab

**Steps to reproduce**

Use transform in `initial`, `animate` and `exit`.

**Expected behavior**

I would expect `transform` to transition its values in the same way it does when it exits.

**Video or screenshots**

N/A codesandbox shows it.

**Environment details**

macOS 10.15.5, Chrome 94.0.4606.61

**Misc**

Apologies if this is already covered in documentation / existing issues. I did take a look and couldn't find anything.

**Comment by mattgperry** [comment]
transform(0%, 0) will fix this. It uses the target value as the template
for the animation and this one doesn’t have a unit type which is why it
does work on the way out

**Comment by rbhalla** [comment]
Ahh, that makes a lot of sense, and thank you for such a quick response!

I imagine this is technically not a bug then and possibly something I just missed in the documentation. Will close now but feel free to reopen if it's something worth keeping around.
