### ISSUE TITLE
[BUG] useMotionTemplate doesn't work with !important

### ISSUE THREAD

**Issue by filipjakov** [framer/motion#1285]
Hi folks,

I need to communicate to some children components a current animation value. The only feasible thing atm is to communicate it via css properties. Since the css property is already declared, i must use `!important` to override the value (since the descendants override the set values from the parent)

I tried the following:

```jsx
const x = useMotionValue(0);
const backgroundColor = useTransform(x, [-100, 0, 100], ['#CBC9CF', '#E03C3C', "black"]);
const color = useMotionTemplate`${backgroundColor} !important`;

return <m.section  style={{ backgroundColor, ['--color' as string]: color }} />
```

But it seems that the css prop (`--color`) doesn't get inserted in `style`  if `!important` is present in the `useMotionTemplate`. 

When i remove `!important`:
```
const color = useMotionTemplate`${backgroundColor}`;
```

everything works as expected (wrt to framer motion).

Is this a bug or is this expected behaviour? Any alternatives I could pick in the meantime?

Thank in advance :)

**Comment by mattgperry** [comment]
Perhaps as an aside Motion doesn't support named color values so black should be `"#000"`.

Apparently you can't set `!important` the way Motion sets style (`element.style[key] = "0px !important"`)

This probably isn't something we're going to change in the medium term so all I can suggest is something like 

```jsx
const ref = useRef(null)
// Insert your motion value logic here

useEffect(() => color.onChange((latest) => ref.current.style.setProperty('--color', latest, 'important')), [color])

return <m.section ref={ref} style={{ backgroundColor }} />
```
