### ISSUE TITLE
Nested motion components - child motion component does not changes its position when the parent does.

### ISSUE THREAD

**Issue by nileshmurf** [framer/motion#1286]
**2. Describe the bug**
I have timeline component (like video editor timeline) which has resizable blocks. These blocks have resize handles at their right end which can be dragged to resize the block. I then added a drag to reorder functionality in the same so that the blocks can be reordered by dragging. Everything works fine in this example just that the resize handle (which is also a motion component) does not change its position with its parent when I try to reorder. It remains in its original position as if it has fixed position and then snaps back to its parent after the dragging ends. Also, this does not happen with the block which is currently getting dragged, this happens with other blocks which change their positions according to the block which is being dragged.

Is this because I have nested two motion components ? How can I fix this ? 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
Here is the link for codesandbox:
[https://codesandbox.io/s/framer-nested-motion-0p25g?file=/src/components/DynamicSizeList/index.js](https://codesandbox.io/s/framer-nested-motion-0p25g?file=/src/components/DynamicSizeList/index.js)

**4. Steps to reproduce**
1. Drag any block to reorder it.
2. You'll that resize handle of other blocks are not getting ordered with their parents

**5. Expected behavior**
When a block moves, its children should move with it but since resize handle is a motion component it does not move and sticks to its original position as if it has position fixed. If I add a normal DOM element it behaves in a normal way.

**6. Video or screenshots**
https://user-images.githubusercontent.com/88651023/136016494-515799ad-683b-4327-acac-ade02e28cae7.mov

**7. Environment details**
I am on a mac m1 Big Sur
Chrome - 94.0.46
framer-motion: 4.1.17

**Comment by mattgperry** [comment]
Please reopen if this still happens with the `Reorder` components.
