### ISSUE TITLE
[DOC/FWIW] performance hit with '%' units

### ISSUE THREAD

**Issue by lkj4** [framer/motion#1291]
Not a bug but noteworthy and something which could get into the docs (if not there yet), I just changed few animations from a `%` unit to `rem` (`width` and `left` props on various `m.div`s) and the performance re fps is night and day to before. Happy that I found this 😛

**Comment by mattgperry** [comment]
That's interesting but probably more of a general performance tip rather than specifically Motion-related. I wonder if the browser is remeasuring the element every frame or something?
