### ISSUE TITLE
[FEATURE] `whileActive` gesture

### ISSUE THREAD

**Issue by joshuawootonn** [framer/motion#1300]
**Is your feature request related to a problem? Please describe.**
I want to be able to animate my components with whileActive for keyboard-driven animation in the same way that whileTap takes care of mouse-driven animation

**Describe the solution you'd like**
This is probably self-evident give ^

**Describe alternatives you've considered**
I am running all css animation for my UI kit ATM. I have tried using a combination of gestures and css animations, but since the gestures override css they don't play well together.

**Additional context**
Here is a sandbox of the other gestures working on my button. You can try hitting space on focus (It doesn't work :))
https://codesandbox.io/s/framer-motion-gesture-demo-for-ui-element-4lswx

**Comment by dahannes** [comment]
I would love to see foremost `whileDisabled` and `whileFocusVisible`as well.
I think all of these should be covered:

`whileActive`
`whileFocus` Implemented #836
`whileFocusWithin` Requested #1465
`whileFocusVisible` 👈 
`whileDisabled`

**Comment by mattgperry** [comment]
Closing as a `wontfix` as unlikely to be added unless we find a need for it in Framer.
