### ISSUE TITLE
Layout animation not working for childs in portal (5.0.0-rc.1)

### ISSUE THREAD

**Issue by rijk** [framer/motion#1302]
https://codesandbox.io/s/framer-motion-v5-0-0-portal-issue-m4v4z?file=/src/App.tsx

I managed to work around the state update funkiness by moving the state to a child component (and have a parent with only `<motion.div>`s). Now the only issue remaining is with portals.

**Steps to reproduce**

1. Click on the blue square
2. Observe correct layout animation on modal open and close
3. Change `portal={true}` in App.tsx:45
4. Observe no layout animation on open, still correct on close

**Expected behavior**

Portals should have no effect on layout animations (like in previous `framer-motion` versions).

**Comment by Zombobot1** [comment]
I have a similar problem. When I placed the [switch button](https://codesandbox.io/s/framer-motion-2-layout-animations-kij8p?from-embed) from official examples in a dropdown menu its handle starts animation with weird offset about 500px. Menu is rendered with a portal. Without portal animation works as expected.

**Comment by thatsjonsense** [comment]
I've found that conditionally rendering a portal causes problems, but animating inside a portal that's always there works ok.

Bad:
```
{isZoomed &&  <Portal>
    <Box layoutId="abc" />
 </Portal>}
```

Good:
```
<Portal>
   {isZoomed && <Box layoutId="abc" />}
</Portal>
```

**Comment by Danziger** [comment]
Any progress on this?

**Comment by Miguel-A-Jara** [comment]
Any updates on this issue?

**Comment by Feridinha** [comment]
dead issue xd

**Comment by mattgperry** [comment]
Closing this as `wontfix` to set expectations - this is unlikely to be looked at unless we find a need within Framer for adding support for Portals
