### ISSUE TITLE
[BUG] 5.0 Failed to compile with create-react-app

### ISSUE THREAD

**Issue by semihraifgurel** [framer/motion#1307]
```
Failed to compile.

./node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available)
```

**Comment by dcakmak** [comment]
my setup as asked, was just a fresh project setup:
        "@testing-library/jest-dom": "^5.14.1",
        "@testing-library/react": "^11.2.7",
        "@testing-library/user-event": "^12.8.3",
        "framer-motion": "^5.0.0"
        "node-sass": "^6.0.1",
        "react": "^17.0.2",
        "react-dom": "^17.0.2",
        "react-scripts": "4.0.3",
        "styled-components": "^5.3.3",
        "web-vitals": "^1.1.2"

**Comment by jafin** [comment]
@justrealmilk  I added the following to `craco.config.js` and it appears to work.

```js
module.exports = {
  webpack: {
        configure: {
            module: {
                rules: [
                    {
                        type: 'javascript/auto',
                        test: /\.mjs$/,
                        include: /node_modules/,
                    },
                ],
            },
        },
    },
}
```

**Comment by frabcus** [comment]
I get the same error using this via Next.js

**Comment by kpjob555** [comment]
I also have this same issue

**Comment by yadprab** [comment]
me too facing the same

**Comment by titan3755** [comment]
same problem. Is there no way to fix it without downgrading framer-motion?

**Comment by justrealmilk** [comment]
> @justrealmilk  I added the following to `craco.config.js` and it appears to work.
> 
> 
> 
> ```js
> 
> module.exports = {
> 
>   webpack: {
> 
>         configure: {
> 
>             module: {
> 
>                 rules: [
> 
>                     {
> 
>                         type: 'javascript/auto',
> 
>                         test: /\.mjs$/,
> 
>                         include: /node_modules/,
> 
>                     },
> 
>                 ],
> 
>             },
> 
>         },
> 
>     },
> 
> }
> 
> ```

Weirdly didn't work for me

**Comment by Solo-Digital** [comment]
> > @justrealmilk  I added the following to `craco.config.js` and it appears to work.
> > ```js
> > module.exports = {
> > 
> >   webpack: {
> > 
> >         configure: {
> > 
> >             module: {
> > 
> >                 rules: [
> > 
> >                     {
> > 
> >                         type: 'javascript/auto',
> > 
> >                         test: /\.mjs$/,
> > 
> >                         include: /node_modules/,
> > 
> >                     },
> > 
> >                 ],
> > 
> >             },
> > 
> >         },
> > 
> >     },
> > 
> > }
> > ```
> 
> Weirdly didn't work for me

It worked for me

**Comment by daxaxelrod** [comment]
@Solo-Digital Did you already have [craco](https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#installation) installed?

**Comment by Solo-Digital** [comment]
> @Solo-Digital Did you already have [craco](https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#installation) installed?

Yes - Craco version 6.3.0 and Framer Motion 5.2.0

**Comment by ManuelNelson7** [comment]
Hi, I'm having the same issue, i'm doing the build of my final project, but it didn't let me. I ran "npm run dev" and the message says `Can't import the named export 'Children' from non EcmaScript module (only default export is available)`

**Comment by wahidshafique** [comment]
I am getting this error when trying to run storybook `6.3.12` and framer `5.2.1`

**Comment by j-borg** [comment]
> I am getting this error when trying to run storybook `6.3.12` and framer `5.2.1`

Same here. @jafin 's solution worked for us though. Added the `mjs` rule to the `webpackFinal` config in Storybook https://storybook.js.org/docs/react/configure/webpack#extending-storybooks-webpack-config

**Comment by granolocks** [comment]
👍  same issue on a rails app using the `react-rails` gem + webpacker

**Comment by github-user001** [comment]
I'm using NextJS fwiw and fixed the error by following @j-borg's link and just wanted to make what the solution was explicit because webpack gives me nightmares and I feel like any time I'm fortunate enough to happen across a tip that works, I am eternally grateful. 

In my project, I've got a `.storybook` directory at the root.

Within that directory, I have a file at `.storybook/main.js`. I just added the entry for the `webpackFinal` property of that file, so now it looks like so (the other stuff was already there)

```js
module.exports = {
  stories: [
    "../stories/**/*.stories.mdx",
    "../stories/**/*.stories.@(js|jsx|ts|tsx)",
  ],
  addons: ["@storybook/addon-links", "@storybook/addon-essentials"],

  /// BELOW THIS WAS ADDED

  webpackFinal: async (config, { configType }) => {
    // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
    // You can change the configuration based on that.
    // 'PRODUCTION' is used when building the static version of storybook.

    // Make whatever fine-grained changes you need
    config.module.rules.push({
      type: "javascript/auto",
      test: /\.mjs$/,
      include: /node_modules/,
    });

    // Return the altered config
    return config;
  },
};
  /// ABOVE THIS WAS ADDED
```

**Comment by dcsan** [comment]
I don't even want to use framer but chakra-ui seems to depend on it, so CRA broke chakra-ui it seems. and that bug is from 2019. https://github.com/formatjs/formatjs/issues/1395#issuecomment-518823361

do we really need to battle with craco to get any progress?

**Comment by TK-Frontend** [comment]
> ```js
>  webpack: {
>         configure: {
>             module: {
>                 rules: [
>                     {
>                         type: 'javascript/auto',
>                         test: /\.mjs$/,
>                         include: /node_modules/,
>                     },
>                 ],
>             },
>         },
>     },
> ```

This solved my problem in half. In addition I had to change eslint.json file to 
`{
  "env": {
    "browser": true,
    "es2021": true
  }}` 
Now eslint doesn't work, but I can use framer-motion. So I think the problem can be in eslint configuration.

**Comment by rami4625** [comment]
I got the same problem after upgrading from version 4.1.17 to version 5.3.0

**Comment by DaliborD45** [comment]
> @justrealmilk I added the following to `craco.config.js` and it appears to work.
> 
> ```js
> module.exports = {
>   webpack: {
>         configure: {
>             module: {
>                 rules: [
>                     {
>                         type: 'javascript/auto',
>                         test: /\.mjs$/,
>                         include: /node_modules/,
>                     },
>                 ],
>             },
>         },
>     },
> }
> ```

this works for me as well

**Comment by justrealmilk** [comment]
I have a more complex CRACO config. For anyone using a configure function, this is it

```js
module.exports = {
  webpack: {
    configure: function (webpackConfig) {
      const locales = {
        type: 'javascript/auto',
        test: /\.json/,
        include: /src(\/|\\)locales/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: whenProd(() => '[name].[contenthash:8].[ext]', '[name].[ext]'),
              outputPath: (url, resourcePath, context) => {
                const lng = resourcePath.replace(/\\/g, '/').match(/locales\/(.+)\/translation.json/)[1];

                return `static/locales/${lng}/${url}`;
              },
            },
          },
        ],
      };

      addBeforeLoader(webpackConfig, loaderByName('file-loader'), locales);

      // *********************
      webpackConfig.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto',
      });
      // *********************

      return webpackConfig;
    },
  }
}
```

**Comment by vmutlu** [comment]
Having same issue

**Comment by axelmarciano** [comment]
If you are using react-app-rewired, you can just add at the end of the override function in config-overrides.js : 

```
config.module.rules = [
    ...config.module.rules,
    {
      type: 'javascript/auto',
      test: /\.mjs$/,
      include: /node_modules/,
    },
  ]
```

Kind regards

**Comment by vmutlu** [comment]
no man this code is not working on blog unfortunately. I stopped using motion

**Comment by Wxld** [comment]
Can't solve the issue, tried everything that is told to do in comments.. help.. any alternative of framer?

**Comment by hamatoyogi** [comment]
> I'm using NextJS fwiw and fixed the error by following @j-borg's link and just wanted to make what the solution was explicit because webpack gives me nightmares and I feel like any time I'm fortunate enough to happen across a tip that works, I am eternally grateful.
> 
> In my project, I've got a `.storybook` directory at the root.
> 
> Within that directory, I have a file at `.storybook/main.js`. I just added the entry for the `webpackFinal` property of that file, so now it looks like so (the other stuff was already there)
> 
> ```js
> module.exports = {
>   stories: [
>     "../stories/**/*.stories.mdx",
>     "../stories/**/*.stories.@(js|jsx|ts|tsx)",
>   ],
>   addons: ["@storybook/addon-links", "@storybook/addon-essentials"],
> 
>   /// BELOW THIS WAS ADDED
> 
>   webpackFinal: async (config, { configType }) => {
>     // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
>     // You can change the configuration based on that.
>     // 'PRODUCTION' is used when building the static version of storybook.
> 
>     // Make whatever fine-grained changes you need
>     config.module.rules.push({
>       type: "javascript/auto",
>       test: /\.mjs$/,
>       include: /node_modules/,
>     });
> 
>     // Return the altered config
>     return config;
>   },
> };
> 
>   /// ABOVE THIS WAS ADDED
> ```

This worked for me. Also on a NextJS app. Thanks @github-user001  🙏🏾

**Comment by Wxld** [comment]
> > @justrealmilk  I added the following to `craco.config.js` and it appears to work.
> > ```js
> > module.exports = {
> > 
> >   webpack: {
> > 
> >         configure: {
> > 
> >             module: {
> > 
> >                 rules: [
> > 
> >                     {
> > 
> >                         type: 'javascript/auto',
> > 
> >                         test: /\.mjs$/,
> > 
> >                         include: /node_modules/,
> > 
> >                     },
> > 
> >                 ],
> > 
> >             },
> > 
> >         },
> > 
> >     },
> > 
> > }
> > ```
> 
> Weirdly didn't work for me

This worked for me, but now the tailwind is not working. All the styling has gone.

**Comment by aviiwithu** [comment]
> ```
> Failed to compile.
> 
> ./node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs
> Can't import the named export 'Children' from non EcmaScript module (only default export is available)
> ```

Getting the same issue when installed with framer-motion@5.3.3.

To solve this issue and work without error, it is recommended to install framer-motion@4.1.17.

Check this link:
https://www.framer.com/docs/guide-upgrade/##esm-and-create-react-app

**Comment by qhdgkdbs** [comment]
i have same issue with my CRA and i got solution from 
[link](https://github.com/reactioncommerce/reaction-component-library/issues/399#issuecomment-467860022)

**Comment by mattgperry** [comment]
I believe this will fix CRA https://github.com/facebook/create-react-app/releases/tag/v5.0.0

**Comment by semihraifgurel** [comment]
Working with CRA 5

**Comment by bkiac** [comment]
I still have this issue with `@chakra-ui/react@1.7.3`, `framer-motion@5.6.0`, `storybook-react@6.4.14` and `@chakra-ui/storybook-addon@1.0.1`

**Comment by sgarcia-dev** [comment]
Having this issue on a Webpack v4.43.x (no CRA) install, none of the fixes appear to work besides downgrading to v4.1.x . Perhaps we shouldn't close this issue until a new version of framer-motion arrives which solves this issue without requiring patches/updates to other tooling?

**Comment by bluekingnfx** [comment]
Update your react scripts, `npm install react-scripts@latest`

**Comment by sgarcia-dev** [comment]
We aren't using `react-scripts` @bluekingnfx

**Comment by isc30** [comment]
this fixes it:
```
    config.module.rules.push({
      test: /\.mjs$/,
      include: /node_modules/,
      type: 'javascript/auto',
    })
    config.resolve.extensions.push('.mjs')
```

**Comment by channyeintun** [comment]
> this fixes it:
> 
> ```
>     webpackConfig.module.rules.push({
>       test: /\.mjs$/,
>       include: /node_modules/,
>       type: 'javascript/auto',
>     })
>     webpackConfig.resolve.extensions.push('.mjs')
> ```

Thanks. This solves my problem in nextjs project.

**Comment by thesmashten** [comment]
Lol I broke my entire project trying to add framer-motion. My advice: don't bother. Get good at CSS animations, the clowns at framer motion have no clue what they're doing and their stuff only works in their perfect little sandbox display online.

**Comment by isc30** [comment]
@thesmashten framer-motion is an awesome project and follows the latest standards in ESM. If you can't get it to run, look at yourself
