### ISSUE TITLE
Reorder items

### ISSUE THREAD

**Issue by mirik999** [framer/motion#1311]
Hi there, just updated framer-motion package to v.5.0.0 and wanted to implement reorder feature in my project but for some reason it didnt work smoothly and correctly, i created sandbox with the exactly the same code as i have. 

[Codesandbox example](https://codesandbox.io/s/cranky-dijkstra-i69oq?file=/pages/index.js)

**Comment by mattgperry** [comment]
Which browser are you using? Looks good to me
