### ISSUE TITLE
Clear initial class styles copied into inline styles after gesture

### ISSUE THREAD

**Issue by tinleym** [framer/motion#1317]
**Is your feature request related to a problem? Please describe.**
Once a hover gesture is finished, initial class styles are copied into inline styles. These override subsequent style sheet changes.

For example, let's say I have a gray icon in a toggle button. I'd like it to turn white when it's hovered, and when it's pressed and toggled on, I'd like to attached a ".pressed" class to the icon, which would turn it pink. Instead, the ".pressed" color value is overridden by the initial state copied into inline styles, and the icon is gray.

Persisting initial class styles in inline styles also causes issues with hot reloading... page reload is required to see style sheet edits take effect on elements that have undergone an animation.

**Describe the solution you'd like**
It would be nice if inline styles copied from the style sheet were cleared once their animation ends, so the element can go back to its true initial state.

**Describe alternatives you've considered**
_To apply the intended styles..._
1) Keeping state-coupled styles out of the style sheet altogether by explicitly defining initial styles that might change out of CSS, using CSS Custom Properties where needed (if, for example, you keep your design system in CSS or a preprocessor like SASS). 

2) !important (which, um, yeah...)

_To keep styles in sync on hot reloading..._
I don't think this is possible at the moment

**Comment by mattgperry** [comment]
This adds prohibitive complexity so it's unlikely to be built in the future.
