### ISSUE TITLE
[BUG] `Reorder.Item` not in correct position if reordered in a scrollable container

### ISSUE THREAD

**Issue by setowilliam** [framer/motion#1319]
**2. Describe the bug**

Using `Reorder` in a scrollable container seems to cause the position of other `Reorder.Item` to be incorrect after scrolling sometimes.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[CodeSandbox example](https://codesandbox.io/s/framer-motion-5-drag-to-reorder-lists-forked-mp8oq?file=/src/App.tsx)

**4. Steps to reproduce**

1. Swap the first and second items.
2. Scroll to the bottom of the container.
3. Swap the last two items.

**5. Expected behavior**

Position of the items should be in their correct position after scrolling and reordering.

**6. Video or screenshots**

https://user-images.githubusercontent.com/28901927/139621967-bc4c8467-962a-4836-a9e6-d945f819b81b.mov

**7. Environment details**

MacOS Monterey, Chrome Version 95.0.4638.54 (Official Build) (arm64)

**Comment by mattgperry** [comment]
You want to add `layoutScroll` to the scrollable parent: https://codesandbox.io/s/framer-motion-5-drag-to-reorder-lists-forked-n27v5

I'll add a section to the docs to clarify!

**Comment by farshidinanloo** [comment]
@setowilliam 
Did you manage to fix it? 
I still have the problem

**Comment by qpre** [comment]
Hey, having a similar issue (same symptoms). I see @mattgperry solution works when the scrollable container is also the scrollable container, but what if I have:

"pseudo template"
```
<body class="flex flex-col w-screen h-screen">
   <header class="flex-none">...</header>
   <!-- scrollable main -->
   <main class="flex-1 overflow-y-scroll">
      <fattitle>Hello</fattitle>
      <Reorder.Group>
         {items.map(() => (<Reorder.Item />)}
      </Reorder.Group>
   </main>
```

In this case, `main` is the scrollable container; there are no issues as long as `main` is not scrolled, once it is scrolled it fails 100% of the time.
adding `layoutScroll` on `<Reorder.Group>` does not help here.

Is there a way to tell `<Reorder.Group>` to take `main`'s scroll offset as an input to its computations ?

**Comment by qpre** [comment]
nevermind,
Even though I was certain I tried this before, turning `main` into a `motion.div` with `layoutScroll` fixed the issue.
Sorry for disturbing !!!
