### ISSUE TITLE
[Question] How to "read" div's position, in a "framer" way?

### ISSUE THREAD

**Issue by voland62** [framer/motion#1320]
Hi.
We usually animate like this:
`    <motion.div animate={{ x: newVal }} />`
, but what if **newVal** depends on current **x** of the div? How we can "read" it?
Thanks.

**Comment by mattgperry** [comment]
Hi there

The recommended way is to create a `MotionValue`. Internally, Framer Motion uses `MotionValue`s to track the state of all animating values. But you can create them yourself in order to inspect/manipulate them.

```jsx
const x = useMotionValue(0)

// This would double x every render
return <motion.div animate={{ x: x.get() * 2 }} style={{ x }} />
```
