### ISSUE TITLE
[BUG] HSLA colors sometimes transition incorrectly

### ISSUE THREAD

**Issue by rbourdon** [framer/motion#1324]
**1. Description of the bug**

Animating between some HSLA colors produces strange results.

**2. CodeSandbox reproduction of the bug**
[https://codesandbox.io/s/framer-motion-gesture-animations-forked-2ipb3?file=/src/index.js](https://codesandbox.io/s/framer-motion-gesture-animations-forked-2ipb3?file=/src/index.js)

**4. Steps to reproduce**
1. Go to the sandbox
2. Hover over the box or button
3. Observe incorrect color transition
4. Click button to switch to RGBA colors
5. Observe correct color transition

**5. Expected behavior**
Expect HSLA color transitions to behave the same as RGBA.

**Comment by mattgperry** [comment]
Yeah I think this is because we do a very literal mix between hsla values. So mixing two different hues will animate the hue value like it was spinning a wheel. I'll take a look at the web spec and see how they do it.
