### ISSUE TITLE
[BUG] AnimatePresence Array Modifications Re-animates multiple array items

### ISSUE THREAD

**Issue by BryanAM** [framer/motion#1329]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

When animating an array with different array operations, e.g. slice, splice, concat, filter, pop, framer-motion animates all array items when using <AnimatePresence>. Without <AnimatePresence> the animation is closer but the segmented part of the array, e.g. array.splice(index, 1) to the end of the list are animated.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
SandBox
https://codesandbox.io/s/crazy-austin-x1q8y?file=/src/App.js

**4. Steps to reproduce**

1. Add one or multiple toasts
2. Remove toasts by either close X button or button at top
All toasts are re-rendered and thus re-animated.

**5. Expected behavior**

Only modified Toasts should animated (added or removed or popped).
Delete should only delete a single toast, not the "remaining"

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

**7. Environment details**

MacOS, Safari, Chrome Latest

### `AnimatePresence` isn't working

Have all of its immediate children got a unique `key` prop that **remains the same for that component every render**?

```jsx
// Bad: The index could be given to a different component if the order of items changes
<AnimatePresence>
  {items.map((item, index) => <Component key={index} />)}
</AnimatePresence>
```

```jsx 
// Good: The item ID is unique to each component
<AnimatePresence>
  {items.map((item, index) => <Component key={item.id} />)}
</AnimatePresence>
```

Is the `AnimatePresence` correctly outside of the controlling conditional? `AnimatePresence` must be rendered whenever you expect an `exit` animation to run - it can't do so if it's unmounted!

```jsx
// Bad: AnimatePresence is unmounted - exit animations won't run
{isVisible && (
  <AnimatePresence>
    <Component />
  </AnimatePresence>
)}
```

```jsx
// Good: Only the children are unmounted - exit animations will run
<AnimatePresence>
  {isVisible && <Component />}
</AnimatePresence>
```

**Comment by mattgperry** [comment]
`uuid()` is generating a new key every render. React can only keep track of components between renders if keys are stable. 

```
key={toast.uuid}
```
