### ISSUE TITLE
[BUG] Using CSS variables doesn't trigger animation (version 5.0.2 and above)

### ISSUE THREAD

**Issue by xeho91** [framer/motion#1336]
I am using CSS variables to get the position `x` value **based on the element's width**.
In the version `5.0.1`, this was working fine, without any issues.

However, after I **upgraded `framer-motion`** to version `5.0.2` and eventually to `5.2.0`, I have noticed that the animations suddenly stopped working _(they're not triggered at all)_.

## Minimal reproduction Sandbox
https://codesandbox.io/s/brave-rhodes-ld5bs?file=/src/App.js

You can see that this pattern works fine in version `5.0.1`, however in more recent versions, it doesn't work.
Is it expected behaviour, or was there any breaking change that I missed?

**Comment by mattgperry** [comment]
There's nothing jumping out at me in the changelogs, I'll take a look
