### ISSUE TITLE
[BUG] Perspective / z settings...

### ISSUE THREAD

**Issue by voland62** [framer/motion#1338]
Hi
I'm trying to reproduce [this](https://codesandbox.io/s/perspective-forked-j13yl?file=/src/styles.css) behavior on framer.com
It seems like it works with CodeComponent implementation, but override-based impl. [works strange](https://framer.com/share/Perspective--2GOxHM3zqmc6HMT2trKR/WuS3R3PmK)...

[This is the project](https://framer.com/projects/Perspective--49fHV0FnWOZddoqcjIAx-hvUAd).
Not sure is it a bug, or my fault somewhere...

P.S. I don't use `transformPerspective` b.t.w, because I don't understand how to use it... Any suggestions?...

**Comment by mattgperry** [comment]
Hey there, you can get support for Framer on the Discord! https://www.framer.com/community/
