### ISSUE TITLE
[BUG] Can't import the named export 'Children' from non EcmaScript module

### ISSUE THREAD

**Issue by JohnCook36** [framer/motion#1340]
Hello. 
Faced the problem shown in the screenshot. Found a solution in your issues, but it didn't help. What could be the problem?

Thanks in advance
![image](https://user-images.githubusercontent.com/50880354/140668922-d9700a4c-d1a0-43fe-8ef7-1f8678fa1f69.png)

**Comment by mryechkin** [comment]
Running into this issue as well (using standard `create-react-app` template with Webpack 4). No changes other than upgrading from `4.1.17` to `5.2.1`, and now seeing the same error.

**Comment by mryechkin** [comment]
This is probably the same root cause as #1307

**Comment by mattgperry** [comment]
Dupe https://github.com/framer/motion/issues/1307
