### ISSUE TITLE
[BUG] Framer motion error after install the package and import

### ISSUE THREAD

**Issue by Bonnary** [framer/motion#1349]
I get this error after installing and importing framer-motion in the middle of my project
``` 
Can't import the named export 'Children' from non EcmaScript module (only default export is available) 
```
[CodeSandbox](https://codesandbox.io/s/rough-morning-hcdrh?file=/src/App.js)

I have tried to install after npx create-react-app and it works fine. This only happened if I install the package in the middle, and in CodeSandbox also work fine don't know why it's only happened in my local machine

**Comment by mattgperry** [comment]
Dupe https://github.com/framer/motion/issues/1307
