### ISSUE TITLE
[BUG] MotionValue set method does not update component

### ISSUE THREAD

**Issue by gornyyvladimir** [framer/motion#1353]
**1. Describe the bug**

When I use set method on MotionValue it does not update (re-render) component

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-range-slider-0rr44?file=/src/RangeSlider/index.tsx

**3. Steps to reproduce**

1. Drag the knob

**4. Expected behavior**

I want to update x position on drag end.
On drag end the knob should be in the center, because we set a center position of the trackpad

**5. Real behavior**

On drag end we set a new position to x, but nothing happend

**6. Environment details**

On version 3.0.0 All works as expected, but on 4 and upper versions position does not update

If I use the useMotionValue incorrectly, can you show me an example of how to do it correctly?

**Comment by mattgperry** [comment]
If you pass `dragTransition={{type:false}}` you can see it works as expected, what seems to be happening is an animation is playing on drag end, even for a frame, which is overriding your `.set`. I'll take a look.

**Comment by gornyyvladimir** [comment]
> If you pass `dragTransition={{type:false}}` you can see it works as expected, what seems to be happening is an animation is playing on drag end, even for a frame, which is overriding your `.set`. I'll take a look.

Do I use MotionValue correctly in this example? I need do some calculations after dragging and update knob position. Maybe better update react state and re-render component? Or use set is the rigth way?
P.s Sorry for my stupid questions, but documentation does not describe this situations

**Comment by mattgperry** [comment]
I've been thinking about it and I think this is a `wontfix`. Reason being, in this example you have `dragConstraints` applied. So, if you call `.set` during an `onDragEnd` that fires when the knob is outside its constraints, it's going to be overwritten by this animation anyway. I'd rather keep the behaviour consistent - either it's overwritten by an animation or it isn't.

What I would do here is call `.stop()` on the motion value before `.set()`. This will ensure any animations are stopped and you can set your value as expected.

`outputX` is always derived from `x` so setting this directly will probably be ignored, or at least overwritten by future updates to `x`.

You are using `MotionValue` correctly. When a `MotionValue` changes, any styles it's bound to will update on the next animation frame. It is entirely apart from React renders though for performance reasons. `.stop()` will be enough to move the knob. If for some other reason you want to trigger a React render you'll need to use `useState`, but I don't think you need to from what I've seen of this example.

**Comment by gornyyvladimir** [comment]
I will attach here my finished example of range slider based on framer motion for the history
https://codesandbox.io/s/framer-motion-range-slider-onhgx
