### ISSUE TITLE
[BUG] Layout transition variants not working

### ISSUE THREAD

**Issue by theelk801** [framer/motion#1357]
When I try to use variants to control a layout animation in a motion component it doesn't pass the transition information through, but when I add the transition arg directly to the component it does. I've created a Sandbox replicating the problem [here](https://codesandbox.io/s/silly-cloud-pdrf8)

**Comment by mattgperry** [comment]
This isn't something that is supported, `transition` doesn't accept variant labels and we're not switching *to* a variant of any kind when we perform a layout animation. The second example is correct.
