### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by codeBoCode** [framer/motion#1359]
I am trying to make images sliding in and out for my login page.

I am using React & framer-motion

I use from framer-motion and I believe I set up everything correctly.

The initial prop for the motion.img is y: -1000 The animate prop is y: 0 the exit prop is y: 1000

For some reason, when the images switch, I only get the exit animation. Below is codesandbox link.

How can I make it so when the image switches, the next image pushes down the previous one?

https://codesandbox.io/s/priceless-paper-vquog?file=/src/App.js

**Comment by rbourdon** [comment]
What's happening is the exiting element is still in the DOM, taking up space, forcing the entering image below it until it's removed at which point the new image moves back up. If you look at the official example for this, you'll notice the images are absolutely positioned to avoid this. I modified your sandbox: https://codesandbox.io/s/eager-mestorf-sfwhn?file=/src/App.js

**Comment by mattgperry** [comment]
This is correct - there’s a feature ticket somewhere to add a prop that could pop exiting elements from the document flow but we haven’t had a chance to implement this yet

**Comment by codeBoCode** [comment]
@rbourdon thank you very much, kind sir! I was able to implement this into my app.
