### ISSUE TITLE
[BUG] Offset between pointer and `Reorder.Item` in iOS Safari

### ISSUE THREAD

**Issue by esdete2** [framer/motion#1360]
**1. Read the [FAQs](#faqs) 👇**
 ✅
 
**2. Describe the bug**

Hey there,
I just came across a strange behaviour. Sometimes there is an offset between the pointer and the `Reorder.Item` when you move the item quickly in Safari on iOS (as you can see in the video below). Probably caused by Safari's address bar moving in and out or the window height that changes as a result.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-5-drag-to-reorder-lists-uonye

**4. Steps to reproduce**

1. Go to the CodeSandbox on an iPhone Device/Simulator with iOS/Safari 15.
2. Drag one item and move it up and down.
3. Sometimes when the address bar moves in or out, the item is shifted.

**5. Expected behavior**

The item should always remain in the position of the pointer.

**6. Video or screenshots**

https://user-images.githubusercontent.com/34043608/142779838-56623185-1966-4688-8244-34bcc04210f8.mov

**7. Environment details**

iOS/Safari 15.0 on iPhone 12 & 13

**Comment by mattgperry** [comment]
Marking as wontfix and opening Webkit bug report. The address bar should not respond to touch gesture when `touch-action: pan-x`

iOS bug report: https://bugs.webkit.org/show_bug.cgi?id=233417

**Comment by esdete2** [comment]
Only `auto` and `manipulate` seems to be supported by Safari:

https://caniuse.com/css-touch-action

**Comment by mattgperry** [comment]
That footnote is attached to iOS versions 9-12.5

**Comment by esdete2** [comment]
Oh, you're right! Sorry about that
