### ISSUE TITLE
[FEATURE] Provide hook for Reorder.Item logic and don't render anything in Reorder.Group

### ISSUE THREAD

**Issue by fnberta** [framer/motion#1362]
This is not really a feature request but rather a question/suggestion around the new Reorder API. I was curious about the thinking behind it:

1. For `Group`, you provide a component that takes an `as` prop. When I look at the code, I don't really see why this is needed. What's the reason for not just letting the consumer render whatever they want and simply export the `.Provider` from `Group`? The current solution makes `Group` more complex as you need to deal with the `as` thing and pass through props and ref.
2. For `Item`, you also provide a component but it doesn't really have any rendering logic. It just renders whatever is input via `as` and passes some props. It would be nice to have this props preparing logic as a hook so that consumers can build their own `Item` components rendering whatever they want and pass whatever props they want on top of what is prepared by framer-motion. I can see how this would be a bit more work for the consumer but it would give the most flexibility.

In any case, the current API works flawlessly, I was curious just about the thinking behind it. To me personally, the `as` prop always feels a bit like changing implementation details from the outside. Shouldn't a component have an intrinsic element to render? And if not, maybe it shouldn't be component but a hook (or multiple components composing common functionality).

Love this library, immensely helpful, thanks for all the hard work!

**Comment by mattgperry** [comment]
1 is future-proofing the component, it will be necessary to render an element for the group if we want to do stuff like drag-to-remove or moving between lists.

For 2 we are rendering a `motion.` element and configuring it in a certain way. We could alternatively do this as a hook but there's far more ways for someone to fuck this up in implementation. Framer Motion is about `capability x simplicity` and for me a hook that returns props that *have* to be provided to a `motion` component in a specific way isn't an API I personally want to provide. I can see how that would provide more flexibility but it just isn't in accordance with the library's ethos.

I'm not a fan of the `as` prop either btw but I do prefer it to the alternatives.

Glad you're enjoying the library tho!
