### ISSUE TITLE
Framer Motion 5 and Preact

### ISSUE THREAD

**Issue by eduardfossas** [framer/motion#1369]
Hello! I am using Framer Motion 4 with Preact and works great! The problem is when I try to update it to Framer Motion 5, it logs an error in a bunch of files of node modules the following:
Module not found: Error: Can't resolve 'react' in './node_modules/framer-motion/

Did someone face the same issue?
Thank you very much!

**Comment by mattgperry** [comment]
Sorry Preact isn’t supported! Any time it’s worked has been accidental.

**Comment by peter-wd-1** [comment]
dose current motion/react has compatibility issue with Preact build as well?
