### ISSUE TITLE
[BUG] Property 'type' does not exist on AnimateSharedLayout's component props.

### ISSUE THREAD

**Issue by bstro** [framer/motion#1370]
**Describe the bug**
The [documentation](https://www.framer.com/docs/animate-shared-layout/##crossfade) for `<AnimateSharedLayout>` describes a `type` prop that takes the strings `crossfade` and `switch` as values. This prop does not appear to exist in the actual type, and so I get a typescript error: `Property 'type' does not exist on type 'IntrinsicAttributes & { children?: ReactNode; }'`

**CodeSandbox**
https://codesandbox.io/s/crazy-sinoussi-ejv4t?file=/src/App.tsx

**Steps to reproduce**
1. Go to the [CodeSandbox](https://codesandbox.io/s/crazy-sinoussi-ejv4t?file=/src/App.tsx) and wait for the type error to show.

**Expected behavior**
Would expect that the types match the docs (I hope that doesn't carry a snarky tone, none is intended).

**Screenshot**

![image](https://user-images.githubusercontent.com/627290/143173496-700cce60-d495-4454-af08-b06f630a5e1d.png)

**Comment by mattgperry** [comment]
It’s been removed in 5, i delisted the page but will add a notice

**Comment by Luvjeet** [comment]
I am still getting this error? why is it so?
![image](https://user-images.githubusercontent.com/65855002/156959988-5b6fbefb-3ea4-41f1-8058-b80d57b738dd.png)

**Comment by mattgperry** [comment]
You can remove the component outright

**Comment by mattgperry** [comment]
It happens automatically between two elements with the same layoutid. You
can turn it off by unmountibg the exiting element

Op ma 7 mrt. 2022 om 23:02 schreef Karl Kihlström ***@***.***>
