### ISSUE TITLE
[BUG] Shared elements don't animate styles

### ISSUE THREAD

**Issue by artpumpkin** [framer/motion#1371]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
Colors and other properties doesn't morph in the new version 5.3.3

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
framer-motion 2.0.0
https://codesandbox.io/s/framer-motion-2-animatesharedlayout-animate-between-different-components-forked-qgf9b

framer-motion 5.3.3
https://codesandbox.io/s/framer-motion-2-animatesharedlayout-animate-between-different-components-forked-lsvi3

**4. Steps to reproduce**
**5. Expected behavior**
Morph colors when using layoutId and AnimateSharedLayout.

**6. Video or screenshots**
framer-motion 2.0.0
![fm2](https://user-images.githubusercontent.com/46715750/143736104-1d9b2597-2a6a-4be6-a94a-782fe1c24f69.gif)

framer-motion 5.3.3
![fm5](https://user-images.githubusercontent.com/46715750/143736112-537514a9-8363-40d3-820f-7273a2498fb3.gif)

**7. Environment details**

**Comment by mattgperry** [comment]
To set expectations although I appreciate the issue I think it's not likely that this will be reimplemented unless we find need for it within Framer.
