### ISSUE TITLE
[BUG] LazyMotion/m behaves differently

### ISSUE THREAD

**Issue by ambar** [framer/motion#1376]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

1. The `m` component is mounted twice
2. The initial animation is not started, or the initial style is not set

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

1. https://codesandbox.io/s/framer-lazy-motion-re-mount-iobxi
2. https://codesandbox.io/s/framer-motion-lazymotion-initial-false-46ws3

**4. Steps to reproduce**

1. logs: ref/div, ref/null, ref/div
2. sandbox
    - Before mount: Box B's position is not expected A/C/D, this is crucial for SSR (or slow network)
    - After resolve: Box A is not moving, whether or not the x changed

**5. Expected behavior**

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

**7. Environment details**

If applicable, let us know which OS, browser, browser version etc you're using.

**Comment by mattgperry** [comment]
Closing as, at least with the latest version, the initial value is as expected (0 when no initial is set).

https://codesandbox.io/p/sandbox/framer-motion-lazymotion-initial-false-forked-zqzmfg
