### ISSUE TITLE
[BUG] Height animation with AnimatePresence with 'exitBeforeEnter' not working as expected

### ISSUE THREAD

**Issue by miguel-arrf** [framer/motion#1379]
**2. Describe the bug**
When using AnimatePresence with 'exitBeforeEnter', the parent container height is not animated.

**3.  CodeSandbox reproduction of the bug**
[https://codesandbox.io/s/laughing-thunder-lu8ol?file=/src/App.js](https://codesandbox.io/s/laughing-thunder-lu8ol?file=/src/App.js)

**4. Steps to reproduce**
Steps to reproduce the behaviour:
1. Go to [https://codesandbox.io/s/laughing-thunder-lu8ol?file=/src/App.js](https://codesandbox.io/s/laughing-thunder-lu8ol?file=/src/App.js)
2. Click on the 'Information Processing' button and then on the 'Natural Language Processing' button.
4. The height of the parent container isn't animated.

**5. Expected behaviour**
When changing between the selected section (on the left), the right section height (and the parent section height) should be animated.

If the AnimatePresence with 'exitBeforeEnter' is removed then the height animation occurs but it is janky... and I also lose the exit animation that I want.

**6. Video or screenshots**

![Screen Recording 2021-12-02 at 20 54 27](https://user-images.githubusercontent.com/11770916/144501818-406e565d-ff05-4bdb-bd4d-3c2cd1a8136b.gif)

**7. Environment details**
macOS Monterey;
Chrome 96
Framer motion 5.3.3

**Comment by georgekrax** [comment]
Yoy should use `layout` animations. You can wrap the components with `<LayoutGroup />`. `<AnimatePresence />` is essentially used for enter and exit animations.

**Comment by mattgperry** [comment]
I'm not seeing where `height` should be animated in the code. You would be better using measuring `height` and setting it via `animate` or using layout animations.
