### ISSUE TITLE
[FEATURE] Make unit configurable

### ISSUE THREAD

**Issue by ThomasRutzer** [framer/motion#1380]
Currently,  **seconds** as unit  is used for all timings. Would be nice if this could be configured in [MotionConfig](https://www.framer.com/docs/motion-config/), e.g.:

```js
import { motion, MotionConfig } from "framer-motion"

export const MyComponent = ({ isVisible }) => (
  <MotionConfig transition={{ duration: 1000 }} unit="miliseconds">
    <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
      />
  </MotionConfig>
)

``` 

We often have to format between miliseconds and seconds in our projects.

**Comment by singlexyz** [comment]
I think this simple unit conversion does not need to add another props.
If you had to use milliseconds, it's better to wrap a layer of components. 
```jsx
function MyMotionConfig({ transition = {}, children }) {
  return (
    <MotionConfig transition={{ ...transition, duration: transition.duration / 1000 }}>
      {children}
    </MotionConfig>
  )
}

```

**Comment by mattgperry** [comment]
Doing this globally would break composability. It’ll probably have to remain a until function.
