### ISSUE TITLE
[BUG] useDomEvent export is missing in use-dom-event.mjs on es build

### ISSUE THREAD

**Issue by bastienrobert** [framer/motion#1382]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

I've just update `framer-motion` to the version **5.4.0** and I'm getting this error message: `SyntaxError: The requested module '../events/use-dom-event.mjs' does not provide an export named 'useDomEvent'`. After a short investigation, I can't see any export of `useDomEvent` in **dist/es/events/use-dom-event.mjs**.
This error came up on my NextJS app.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Not applicable: can't repro on codesandbox.

**4. Steps to reproduce**

1. Import `framer-motion`
2. See error

**5. Expected behavior**

`useAnimationFrame` should be exported.

**6. Video or screenshots**

Not applicable.

**7. Environment details**

During bundling phase on NextJS.

**Comment by bastienrobert** [comment]
See https://unpkg.com/framer-motion@5.4.0/dist/es/events/use-dom-event.mjs & https://unpkg.com/framer-motion@5.4.0/dist/es/gestures/use-focus-gesture.mjs

**Comment by mattgperry** [comment]
Thanks for the report, this is now fixed in 5.4.1
