### ISSUE TITLE
Broken exports/imports in version 5.4.0 

### ISSUE THREAD

**Issue by DanTsk** [framer/motion#1383]
`useDomEvent` function (which is used in `gestures`, i.e: [focus-gesture](https://unpkg.com/browse/framer-motion@5.4.0/dist/es/gestures/use-focus-gesture.mjs)) does not exists inside [events/use-dom-event.mjs](https://unpkg.com/browse/framer-motion@5.4.0/dist/es/events/use-dom-event.mjs)

**Comment by mattgperry** [comment]
Dupe https://github.com/framer/motion/issues/1382
