### ISSUE TITLE
[BUG] Unexpected Layout Behavior with AnimatePresence present

### ISSUE THREAD

**Issue by weissleon** [framer/motion#1386]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

According to the documentation on [LayoutGroup](https://www.framer.com/docs/layout-group/), the **LayoutGroup** can be used to trigger layout transition between elements **from different trees**.
If I understand it correctly, **as long as the elements are of the same tree**, simply setting `layout` and `layoutId` property is enough to trigger layout transition starting from Version 5.
However, I discovered that the layout transition works only half when a parent element contains a child element with `AnimatePresence`.
The layout transition works just fine when the element is entering. It breaks when the element exits.

I solved it by wrapping the entire element tree with yet another LayoutGroup.
Is this an expected behavior? If so, can we update the documentation regarding this?

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
LINK: https://codesandbox.io/s/layoutgroup-animatepresence-8c58k?file=/src/App.js

**4. Steps to reproduce**
Toggle the `Show Content` button on the page.

**5. Expected behavior**
The container should shrink with animation when the content element is removed from the tree.

**6. Video or screenshots**

**7. Environment details**

OS: Windows 10
Browser: Chrome (96.0.4664.45 64bit)

**Comment by EliavYair1** [comment]
hi,
I have solved your issue by adding this to your code:

`<motion.h1 transition={{ duration: 0.01 }} layout>
          Title
        </motion.h1>`

please let me know if its works for you.
thanks.

**Comment by samselikoff** [comment]
@weissleon ever figure this guy out? I'm running into something similar. I basically want to invert the `initial -> animate` animation as in your example, but because AnimatePresence "holds space" for the existing element, the layout animation doesn't run until it's fully exited.

**Comment by mattgperry** [comment]
Here's an approach using `usePresence`

```
const Text = ({ children }) => {
  const [isPresent] = usePresence();
  return (
    <motion.p
      layout
      initial="hidden"
      animate="visible"
      exit="hidden"
      variants={variant}
      style={{
        position: isPresent ? "static" : "absolute",
        whiteSpace: "nowrap",
      }}
    >
      {children}
    </motion.p>
  );
};
```

**Comment by samselikoff** [comment]
Awesome, thanks Matt!
