### ISSUE TITLE
[FEATURE] onViewportBoxUpdate or equivalent method

### ISSUE THREAD

**Issue by HenryDavies** [framer/motion#1388]
**Is your feature request related to a problem? Please describe.**
I was using `onViewportBoxUpdate` to allow a `layout=true` card to animate its height without distortion in its border:
- Layout scale animations on elements with borders cause distortion in the border ([codesandbox example](https://codesandbox.io/s/border-distortion-mums1?file=/src/index.js))
- I therefore put the border on a separate empty (and `layout=false`) div aligned with the card
- I used `onViewportBoxUpdate` to set the height of this empty div on each tick of the card's layout animation, so it appeared that the border was around the card, animating without any distortion

I would like to upgrade to v5 but this is stopping me.

**Describe the solution you'd like**
My end-goal is to have a `layout=true` card animate its height without any distortion in the border. I think this involves somehow hooking into the height of the card as it animates, whether this be via an `onViewportBoxUpdate` method or equivalent.

It's also very possible I'm missing a simpler solution for doing this, in which case I'd love to know how.
 
Thanks in advance for any help, and thanks for providing such a great library

**Comment by kschmott** [comment]
Did you figure this out?

**Comment by mattgperry** [comment]
I think it's unlikely we will reimplement this in the near future so to set expecations I'm closing as `wontfix`
