### ISSUE TITLE
[BUG] MotionConfig does not propagate changes to transition

### ISSUE THREAD

**Issue by wurstbonbon** [framer/motion#1398]
**1. Describe the bug**

`MotionConfig` uses `toString` to memoize the transition that is passed down via context.  
`toString` returns `[object Object]` for regular objects, thus the context isn't updated when the transition is changed.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/framer-motion-motion-config-memo-rohc3

**4. Steps to reproduce**

1. Click "Disabled Animation"
2. Click the button below.
-> Bug: The animation is still happing with a non-zero duration.

**5. Expected behavior**

Changes to the transition should be propagated. 

**6. Environment details**

Should be broken in all browser.

**Comment by power-f-GOD** [comment]
https://github.com/framer/motion/pull/1399#issuecomment-1005276236
