### ISSUE TITLE
[BUG] Transitioning height between "auto" and 0 causes body to scroll abruptly

### ISSUE THREAD

**Issue by mattjis** [framer/motion#1402]
When collapsing (`height` auto -> 0) an accordion, Framer Motion will abruptly scroll up to where the new bottom of page position will be — before the transition has even started.

This issue mostly affects Safari (Mac & iOS), but happens in Chrome too with certain "accordion content".

This is what Framer Motion is doing:

https://user-images.githubusercontent.com/21289982/147768989-f7923959-0578-4bc8-beaf-86a420fd7cbb.mp4

This is what Framer Motion should be doing (custom solution without Framer Motion):

https://user-images.githubusercontent.com/21289982/147769081-c455703f-257c-4fa1-af2f-e2c1829fcbde.mp4

And here's the code snippet used for this accordion:
```javascript
<motion.div
	initial={false}
	className="relative overflow-hidden"
	animate={{
		height: active ? "auto" : "0px",
		opacity: active ? 1 : 0
	}}
	transition={{ duration: 0.5, ease: [0.7, 0, 0.3, 1] }}
>
	...
</motion.div>
```

Example repository: https://github.com/mattjis/framer-motion-bug 
Example live demo: https://framer-motion-bug.vercel.app

**Comment by mattjis** [comment]
I've also noticed it happens sometimes in Chrome, but every-time in Safari.

**Comment by EliavYair1** [comment]
can you send a link or reference of the project you working on so i could run tests?

**Comment by mattjis** [comment]
@EliavYair1 I created an example repository here: https://github.com/mattjis/framer-motion-bug and a live demo here: https://framer-motion-bug.vercel.app

**Comment by mattjis** [comment]
@mattgperry any ideas what's causing this behaviour?

**Comment by mattjis** [comment]
@mattgperry just noticed your own accordion example https://codesandbox.io/s/framer-motion-accordion-qx958 has the same issue.

**Comment by fchubu** [comment]
This bug is driving me crazy, does anybody know how to solve it?

**Comment by mattjis** [comment]
This has finally been solved!

**Comment by umar-brackets** [comment]
> This has finally been solved!

can you please tell me where to find the solution of this scroll issue? btw I am new to github

**Comment by mattjis** [comment]
@umar-brackets I updated my `framer-motion` via `npm` and it's now working as expected — so I marked as resolved.
