### ISSUE TITLE
[BUG] Clicking interrupts <Reorder> component

### ISSUE THREAD

**Issue by joshwcomeau** [framer/motion#1404]
When clicking a <Reorder.Item>, it will freeze in-place rather than finishing its inertia transition:

![framer-motion-reorder](https://user-images.githubusercontent.com/6692932/147960182-16df288d-2476-4914-9bfd-7faaa444f3b6.gif)

I assume that this isn't intentional, especially since it happens even when the list element doesn't contain interactive elements (eg. links, buttons).

CodeSandbox: https://codesandbox.io/s/framer-motion-5-drag-to-reorder-lists-uonye?from-embed

It's reproducible for me on MacOS Monterey, Chrome 96, using Framer Motion 5.0.0-rc4 (the CodeSandbox) as well as 5.5.5 (my local codebase).

Framer Motion is an *incredible* library, and I'm so thankful for the work y'all do :) thanks!

**Comment by klaasman** [comment]
I'm unable to reproduce this issue in the codesandbox. How do you perform the additional click while dragging?

**Comment by mattgperry** [comment]
It makes sense - we stop an element instantly when a user grabs it so you can catch it. So here it’s let go, caught and stopped. We need to resume the reorder animation when the item is let go again

**Comment by Julian-Sz** [comment]
> I'm unable to reproduce this issue in the codesandbox. How do you perform the additional click while dragging?
You have to let it go and then you can stop it with a click while it animates back.

**Comment by hexwit** [comment]
so is there any way to disable/ignore this functionality when it is possible to stop animation by click?

**Comment by yardenxr** [comment]
any update on this?

**Comment by tom-laventure** [comment]
Hi all, big fan of this library and would love to contribute, happy to take a look at this bug in my free time if no one else has started work on it?

**Comment by mattgperry** [comment]
Fix going out in `10.17.1`

**Comment by sushanyadav** [comment]
I am still getting this bug. using : "framer-motion": "^11.0.8"
