### ISSUE TITLE
Error installing framer motion

### ISSUE THREAD

**Issue by justbenuk** [framer/motion#1405]
`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: justben@undefined
npm ERR! Found: three@0.136.0
npm ERR! node_modules/three
npm ERR!   peer three@">=0.126" from @react-three/fiber@7.0.24
npm ERR!   node_modules/@react-three/fiber
npm ERR!     peerOptional @react-three/fiber@"*" from framer-motion@5.5.5
npm ERR!     node_modules/framer-motion
npm ERR!       framer-motion@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional three@"^0.135.0" from framer-motion@5.5.5
npm ERR! node_modules/framer-motion
npm ERR!   framer-motion@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/ben/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ben/.npm/_logs/2022-01-03T23_13_00_237Z-debug.log
`
I keep getting this error when installing framer motion on a fresh nextjs build.. any ideas. I have updated npm and all packages

**Comment by paales** [comment]
"tree" should be "three"?

**Comment by mattgperry** [comment]
@justbenuk Do you get the same error with `5.5.6-beta.0` ?

**Comment by justbenuk** [comment]
Please ignore me. the error was because I have just moved from windows to ubuntu full time. I had used apt to install nodejs and I didn't realise how old the version of node was from the ubuntu repository. I have since updated node to the latest version and worked straight away.

**Comment by aklevecz** [comment]
> `5.5.6-beta.0`

This worked for me

**Comment by DhiaMbarki** [comment]
f*ck where is the answer

**Comment by psantosh16** [comment]
What is update for this question ? I am also stuck here.

**Comment by DevInfinix** [comment]
agree
