### ISSUE TITLE
[BUG] When switching from absolute to fixed and changing scroll position layout animations trigger

### ISSUE THREAD

**Issue by paales** [framer/motion#1407]
I'm trying to build proper page transitions with framer motion on nextjs. Available here: https://www.npmjs.com/package/@graphcommerce/framer-next-pages

We've got scroll position support when pages transition to allow stable overlays and allow for layout transitions. However it seems that layout projections have an issue when the page repositions.

**1. Read the [FAQs](#faqs) 👇**
✅ 

**2. Describe the bug**

This was working in Framer Motion 4 but v5 seems to be handling things differently.

The layout _from-animation_ is somehow not taking in account the current scroll position of page but the _to-animation_ is taking it in account causing the animation to be fired.

1. If a new page is loaded we record the scroll position of the old page. (e.g. 186px scrollTop)
2. We set the window.scrollTop to 0
3. We set the old page to `style="position: fixed; top: -186px;"`
4. We set the new page to `position: absolute; z-index: 1;`

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/wizardly-pike-4cd98?file=/pages/index.tsx

**4. Steps to reproduce**

1. Go to sandbox
2. Scroll down a bit so that you see about half of the red area.
3. Open the overlay

**5. Expected behavior**

I would expect the red area to remain stable and make sure the scroll position is taken into account to transition the layout.

**6. Video or screenshots**

In our app we can see the issue occur:

You can see it in the video where the gallery is shifted down first and then it is animated back up:

https://user-images.githubusercontent.com/1244416/148037440-19e12609-4bff-4205-90a4-5f4feba0cf34.mp4

In this video you can see the gallery flash by but the rest of the page remains stable:

https://user-images.githubusercontent.com/1244416/148039381-a378403d-eb5b-4532-adac-042aedd85bcc.mp4

**Comment by mattgperry** [comment]
Closing in favour of the new parent ticket
