### ISSUE TITLE
[BUG] dragConstraints does not work as it used to in a scrollable container

### ISSUE THREAD

**Issue by hoangbn** [framer/motion#1412]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

When the scrollable container is used as dragConstraints for a draggable item, the constraints are not calculated correctly.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-5-drag-to-reorder-lists-forked-iw8o9?file=/src/App.tsx

**4. Steps to reproduce**

1. Go to code sabdbox
2. Scroll down a little bit, so Letuce is still in view, but not at the bottom.
3. Try to drag Letuce down

**5. Expected behavior**

Lettuce should be able to be dragged until it touches the bottom of container, and it should stop when it touches the top of the container (outside the overflow).

For reference, here is how it used to work in framer 4 (as expected)

![dragConstraint expected](https://user-images.githubusercontent.com/38968280/148596929-f03a06ce-e3e3-43f4-943c-63ca9ec414d5.gif)

**6. Video or screenshots**

![dragConstraint issue](https://user-images.githubusercontent.com/38968280/148596665-f9eabb65-026a-4e43-9ca1-74ecf12ac5e1.gif)

**Comment by likewerealive** [comment]
@hoangbn Did you find any work around for this? I'm hitting the same issue!

**Comment by hoangbn** [comment]
No, I did not

**Comment by mattgperry** [comment]
Closing for https://github.com/framer/motion/issues/1339

**Comment by francescosac95** [comment]
@mattgperry  I would expect there's a solution if the issues have been closed. Can you please direct me to it?
