### ISSUE TITLE
must borderRadius be unitless for crossfade effect ?

### ISSUE THREAD

**Issue by ArianHamdi** [framer/motion#1413]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

when I want to change `borderRadius` during the crossfade effect if I add a unit e.g. `borderRadius : "20px"` or `borderRadius : "20%"` , it doesn't work properly as I expected. Thus I was forced to omit the unit e.g. `borderRadius : 20`.

Is it a bug or it's normal for you?

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/objective-fermat-t4hq0?file=/src/App.js

**4. Steps to reproduce**

1. Open codesandbox link.
2. Click on an element to see the crossfade effect and smooth changes in borderRadius.
3. Add unit to borderRadius e.g. "20px".
4. Now click on an element and see borderRadius changes. you can see that the changes are not smooth.

**Comment by ShahriarKh** [comment]
🤔 Seems to be a bug with pixel units.
I checked the browser console. Unitless `border-radius` is converted to percentages.
![image](https://user-images.githubusercontent.com/31452340/148684198-11b58571-9181-49fe-a591-7e07ddfefc00.png)

**Comment by mattgperry** [comment]
Yeah I think if it’s a string it’s handled as a percentage, number for pixels. We should probably check for the px

**Comment by mattgperry** [comment]
My mistake its that strings aren't supported at all for crossfading
