### ISSUE TITLE
[BUG] transitions defined inside variants are not used in Framer Motion 3D

### ISSUE THREAD

**Issue by itssharlee** [framer/motion#1418]
**Describe the bug**

Framer Motion 3D uses the default `transition` instead of the one provided in each variant on version `5.5.0` and later.

**IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[https://codesandbox.io/s/framer-motion-transitions-demo-l24qt?file=/src/App.js](https://codesandbox.io/s/framer-motion-transitions-demo-l24qt?file=/src/App.js)

**Steps to reproduce**

1. Click on the button 'To the left'
2. Click on the button 'To the right'
-> The transitions are the same, even if different transitions are set in the variants

**Expected behavior**

Transitions used must be the ones defined in each variant instead of using the default transitions.

**Environment details**

Should not work in all browsers (Tested in Chrome and Firefox)

**Comment by itssharlee** [comment]
I found the fix, we now need to wrap our scene in a `MotionCanvas` instead of a simple `Canvas` component.

**Comment by cdebotton** [comment]
I'm encountering this bug using `framer-motion-3d@6.2.8` with `@react-three/fiber@7.0.26`. The `transition` property is always ignored.

**Comment by roelkok** [comment]
Can this issue be re-opened? I also have the issue with `framer-motion-3d@6.3.3`
