### ISSUE TITLE
[FEATURE] Access animation events for layout animations

### ISSUE THREAD

**Issue by el-dav** [framer/motion#1419]
**Is your feature request related to a problem? Please describe.**

I would like to have access to animation events e.g. `onUpdate` `onAnimationStart` and `onAnimationEnd` for layout animations. However these don't seem to trigger for layout animations, only regular animations. For layout animations the API only includes `onLayoutAnimationComplete`.

This seems like an interesting omission and i was wondering if it was intentional?

I'm trying to sync the position of an external component with a motion component (which has layout animations enabled), and I can't see a way to achieve this without these events.

**Describe the solution you'd like**
Ideally I would like the equivalent of `onUpdate` and `onAnimationStart` but for layout animations. Or alternatively have `onUpdate` `onAnimationStart` and `onAnimationEnd` also trigger for layout animations.

Many thanks!

**Comment by mattgperry** [comment]
`onLayoutAnimationStart` has since been added but to set expectations it is unlikely I'll add a per-frame callback.
