### ISSUE TITLE
[BUG] React 18 issues

### ISSUE THREAD

**Issue by marcospassos** [framer/motion#1421]
Using React 18 a component inside `<AnimatePresence/>` does not unmount from the DOM after the exit animation finishes. There are also other issues involving `layoutId`, but the one that seems really broken is the `<AnimatePresence/>`.

It seems that most issues are related to the strict mode. Disabling it fix the issue.

Framer version: 5.5.5
React version:  18.0.0-rc0

**Comment by mattgperry** [comment]
Thanks for the report! With layoutId, are the other issues specifically in relation to AnimatePresence?

**Comment by marcospassos** [comment]
All issues I've noticed are related to `<AnimatedPresence/>`. Even disabling the strict mode, animations that are not directly child of the `<AnimatedPresence/>` don't work.

**Comment by mattgperry** [comment]
Ah yeah that makes sense it still isn't concurrent safe, we'll have to take a look at this soon.

**Comment by vpontis** [comment]
> Ah yeah that makes sense it still isn't concurrent safe, we'll have to take a look at this soon.

That would be awesome, thanks @mattgperry. This is blocking our upgrade to React 18 and we love Framer Motion :)

**Comment by JarolinVargas** [comment]
Any updates on this? I'm also dealing with this issue

**Comment by madebyfabian** [comment]
Also facing this issue when upgrading to react 18. Since this is Open for such a long time, what can we do to get more focus on fixing things for react 18? I can provide a reproduction codesandbox if that helps. But it's also stopping me from upgrading to react 18, therefore it would be great to see at least a workaround for this.

**Comment by mattgperry** [comment]
We've been on 18 for a while so please reopen with Sandbox examples of any issues you run into.
