### ISSUE TITLE
[BUG] Animate Presence exit animation in HoC not working

### ISSUE THREAD

**Issue by agcty** [framer/motion#1424]
**1. Read the [FAQs](#faqs) 👇**

I read the FAQs

**2. Describe the bug**

I'm building a convenience HoC for showing/hiding components and trying to give them exit animations.

The HoC is intended to be used like this in its simplest form:

```jsx
const ToggledThing = useToggle(Thing, isOpen);
```

```jsx
import { AnimatePresence } from "framer-motion";

export default function useToggle(ToggledComponent, isOpen) {
  return function WithToggle(props) {
    return (
      <>
        <AnimatePresence>
          {isOpen && <ToggledComponent {...props} />}
        </AnimatePresence>
      </>
    );
  };
}
```

The isOpen state is passed correctly and the component mounts and unmounts accordingly but for some reason the exit animation doesn't get triggered.

**Possible related issue with zustand**

Really not sure if this is related to the issue above but one really weird issue I found out while playing around with zustand and framer-motion is that exit animations work as long as the piece of state that is used in the HoC is not accessed somewhere else:

```jsx
// this code works
export function useToggleString(ToggledComponent) {
  return function WithToggle(props) {
    const isOpenString = useStore((state) => state.isOpenString);

    const isOpen = isOpenString === "true";

    return (
      <>
        <AnimatePresence>
          {isOpen && <ToggledComponent {...props} />}
        </AnimatePresence>
      </>
    );
  };
}
```

```jsx
// UNTIL isOpenString is being accessed somewhere else in the codebase like this:
const isOpenTest = useStore((state) => state.isOpenString);
```

then it won't show the exit animation. Again, this is a really really weird issue and I'm not even sure where to raise it but hoping that explaining it here is valuable in any way. Also tagging @dai-shi.

**3. CodeSandbox reproduction of the bug**

https://codesandbox.io/s/gifted-bush-9p1ib?file=/src/App.js

**4. Steps to reproduce**

1. Click "Toggle", now the entry animation shows
2. Click "Toggle" again, exit animation doesn't show

**5. Expected behavior**

The exit animation shows when the component gets unmounted

**6. Video or screenshots**

https://www.loom.com/share/b26bf08b61c9440cba16b92f2f1b511a

**7. Environment details**

react 17.0.2
framer-motion 5.6.0 (also happens with v6 beta)

**Comment by agcty** [comment]
Might be related to this: https://github.com/framer/motion/issues/1085

**Comment by mattgperry** [comment]
You're making a brand new component every render. This could have other unexpected consequences, for instance `initial` => `animate` animations running every render instead of what you would expect to be the initial render.
