### ISSUE TITLE
[HELP/FEATURE] Crossfading between components

### ISSUE THREAD

**Issue by mattjis** [framer/motion#1428]
I wish there was a way to transition from one component to another as if they were `position: absolute` on top of each other inside a `relative` container, crossfading their `opacity` in and out while the `relative` container's `height`/`width` adjusted smoothly to match that of the new component.

I don't think `exitBeforeEnter` looks nice, and it takes twice as long to finish. It also doesn't solve the smooth `height`/`width` transition between the components.

---

Is this currently possible with Framer Motion?

**Comment by mikirejf** [comment]
@mattjis 

For the crossfading part, if it helps: https://codesandbox.io/s/framer-motion-crossfading-8mq6oe
