### ISSUE TITLE
[BUG] LayoutId is animating non-affected elements in nested scrollviews

### ISSUE THREAD

**Issue by v-morlock** [framer/motion#1430]
**2. Describe the bug**

Given an absolute-positioned scrollview from which an also absolute-positioned modal is opened and animated using a layoutId, other items are also animated when scrolling around before triggering the animation. 

https://codesandbox.io/s/frosty-cherry-5limg

**4. Steps to reproduce**

- open a modal, close by clicking the modal
- scroll a bit
- open a second modal
- watch other items animating (seemingly) random

**5. Expected behavior**

Only the affected item should animate

**6. Video or screenshots**

[If applicable, add a video or screenshots to help explain the bug.
](https://user-images.githubusercontent.com/18666999/151141687-1e905ffc-a6df-46f5-9053-3acadcddb91b.mov)

**7. Environment details**

Seems to be browser-independent, occured in

- Electron / Macos
- Safari / Macos
- Electron / Linux

**Comment by v-morlock** [comment]
Update: this seems to affect all cases where the scrollview is not the parent element but some other element with overflow: scroll

**Comment by v-morlock** [comment]
Update2: found out that i need to set layoutScroll to the ancestor. However, now the closing-animation is looking wrong.

https://user-images.githubusercontent.com/18666999/151197690-64142f0d-abff-40bc-a75f-51dedc45309c.mov

```tsx
    <Fragment>
      {selectedWord && (
        <motion.div
          layoutId={selectedWord.id}
          style={{
            position: "fixed",
            top: "10vw",
            left: "25vw",
            width: "50vw",
            height: "50vw",
            backgroundColor: selectedWord.color,
            zIndex: 2
          }}
          onClick={() => setSelectedWord(undefined)}
        ></motion.div>
      )}

      <motion.div
        layoutScroll
        style={{
          overflow: "scroll",
          position: "absolute",
          left: 0,
          top: 0,
          right: 0,
          bottom: 0,
          display: "grid",
          gridTemplateColumns: "repeat(3, 1fr)"
        }}
      >
        {words.map(({ word, color, id }) =>
          selectedWord?.id === id ? (
            <div key={id} style={{ height: 100, margin: 20, padding: 20 }} />
          ) : (
            <motion.div
              key={id}
              layoutId={id}
              style={{
                margin: 20,
                padding: 20,
                backgroundColor: color,
                height: 100
              }}
              onClick={() => setSelectedWord(id)}
            >
              {word}
            </motion.div>
          )
        )}
      </motion.div>
    </Fragment>

```

**Comment by EliavYair1** [comment]
ive forked your codesandbox project.

https://codesandbox.io/s/objective-minsky-dqd57

check out if this solution is good for you.

**Comment by ivanburlakov** [comment]
Have you found the solution?

**Comment by mattgperry** [comment]
Closing in favour of https://github.com/framer/motion/issues/2465 as a parent ticket
