### ISSUE TITLE
[BUG]: Chrome 'requestAnimationFrame' violation errors

### ISSUE THREAD

**Issue by xplato** [framer/motion#1431]
**Description**

Using a contained drag area (with a `ref`) and transforming the motion value to a usable `x` and `y` (relative to the container) causes a very laggy experience.

Basically, I want to be able to drag a small box within another box **and** be able to easily use the current values. Therefore, I created a [`useDragBox`](https://codesandbox.io/s/framer-motion-lag-sandbox-c00fm?file=/src/useDragBox.js:419-433) hook which handles this for me. I am then able to compare the current values with human-readable and usable values like `x > 150` (relative to the width of the parent).

All the same, it works, but it is more often than not very very laggy. There has been a few times where it was extremely smooth, but frankly not any more. I'm really not quite sure what's happening here.

I've received all of the following warnings from within the sandbox link below:

```console
[Violation] 'requestAnimationFrame' handler took 250ms
[Violation] 'requestAnimationFrame' handler took <N>ms
[Violation] Forced reflow while executing JavaScript took 250ms
```

Is my `useDragBox` hook causing a reflow with how the x and y values are applied?

**Sandbox**

View the live sandbox here to see the warnings from within the console: [c00fm.csb.app](https://c00fm.csb.app/)

The code to the sandbox is available here [codesandbox.io](https://codesandbox.io/s/framer-motion-lag-sandbox-c00fm)

**Steps to reproduce**

1. Use your mouse to click and drag the smaller, lighter blue box within the dark container.
2. As you move it, there should be a noticeable lag and the console should warn you.

**Expected behavior**

A smooth, kinetic animation without dropped frames _and_ usable MotionValues.

**Screenshots**

Here's a performance report taken in Brave on the link above:

![framer-issue](https://user-images.githubusercontent.com/87919558/151417311-65ea5d99-0201-43d0-b3b1-ca43e55c6888.png)

**Environment details**

- Framer: I've tried **4.1.17,** **6.2.1,** and **6.2.3**
- React: **17.0.2**
- OS: MacOS 12.1
- Browser: Brave 1.34.81 (Chromium: 97.0.4692.99)

**Comment by xplato** [comment]
Any word on this? It has been half a year lol

**Comment by mattgperry** [comment]
No longer broken in React 18 thanks to async state updates.
