### ISSUE TITLE
[BUG] AnimatePresence doesn't work when input autoFocus inside

### ISSUE THREAD

**Issue by lcswillems** [framer/motion#1432]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

When AnimatePresence contains an input with autoFocus property, it doesn't work correctly.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

```tsx
import * as React from "react";
import { useState } from "react";
import { render } from "react-dom";
import { motion, AnimatePresence } from "framer-motion";

const App = () => {
  const [page, setPage] = useState(0);

  return (
    <>
      <AnimatePresence initial={false}>
        <motion.div
          key={page}
          initial={{ x: 1000 }}
          animate={{ x: 0 }}
          exit={{ x: -1000 }}
          transition={{ duration: 10 }}
        >
          <input autoFocus value={page} />
        </motion.div>
      </AnimatePresence>
      <button onClick={() => setPage(page + 1)}>Next</button>
    </>
  );
};

render(<App />, document.getElementById("root"));
```

The CodeSandBox with the bug: https://codesandbox.io/s/framer-motion-image-gallery-forked-4r5ez?file=/src/index.tsx

The same CodeSandBox without the autoFocus property: https://codesandbox.io/s/framer-motion-image-gallery-forked-3pe47?file=/src/index.tsx

**4. Steps to reproduce**

1. Go to the CodeSandBox with the bug.
2. Click on the "Next" button.
3. See the animation being weird.

You can check the codesandbox without the autoFocus to observe how the animation should behave.

**Comment by Cilia94** [comment]
I'm having the same issue, is there a workaround/solution?

**Comment by heerzhang** [comment]
I use <motion.div  drag ，And animate（），find the same issue,

**Comment by mattgperry** [comment]
Watch the horizontal scrollbar. When the new element is added, the browser sets focus on it. This scrolls the element into view and is expected behaviour, unrelated to Motion. Your best bet is to somehow prevent horizontal scrolling.
