### ISSUE TITLE
[HELP / BUG] Sketchy layout animation with exit in AnimatePresence

### ISSUE THREAD

**Issue by georgekrax** [framer/motion#1434]
**2. Describe the bug**

Why `layout` animation under <LayoutGroup />, is having a gray flash while changing size?
I want some children elements to have `display: none`, but when I set that CSS property, there is a flash.
If I comment this out then the animation behaves well.

**OR**

If I uncomment the `exit` animation prop in `components/Select/ModalOption.tsx` (line 37) then the animation works good, with border and layout animation.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

A [CodeSandbox ](https://codesandbox.io/s/compassionate-hellman-4zif0?file=/src/components/Select/Item.tsx) minimal reproduction to quickly follow the reproduction steps. 
https://codesandbox.io/s/compassionate-hellman-4zif0?file=/src/components/Select/Item.tsx

**4. Steps to reproduce**

1. Go to `components/Select/Item.tsx`
2. Click the Button element and you will open the modal
3. Click the "Go to second" options panel
4. See the error (**gay flash**)
5. Click the "Go to first" to return to the first options panel
6. Try to comment and uncomment the `227 - 228 lines` at the `components/Select/Item.tsx` file
7. Repeat the steps, by changing the `display: none` and `hidden` attributes
8. See how the error replicates, with `display: none` and without

**OR**
1. Click the Button element and you will open the modal
2. Click the "Go to second" options panel
3. See the error (**gay flash**)
4. Click the "Go to first" to return to the first options panel
5. See the error again
6. Go to `components/Select/ModalOption.tsx`
7. Comment the `exit` prop animation (line 37)
8. Repeat the steps, and you will see that there are no sketchy transitions

**5. Expected behavior**

I do not want to have a gray flash when changing between option panels. If you remove the `display: none` style and `hidden` HTML attribute, the animation will run smoothly.

**OR**

I want to have exit animation with layout animations combined.

**6. Video or screenshots**

https://user-images.githubusercontent.com/62029562/151679483-6880f5c4-8d57-49d3-828d-4fbb874e1e77.mp4

**7. Environment details**

**System:**
    OS: Windows 10 10.0.22000
    CPU: (8) x64 AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx  
    Memory: 911.25 MB / 5.94 GB

**Binaries:**
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\node_modules\.bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD

**Browsers:**
    Edge: Spartan (44.22000.120.0), Chromium (97.0.1072.76)
    Internet Explorer: 11.0.22000.120

**Comment by mattgperry** [comment]
I haven't been able to reproduce but even so we don't really support layout animations with display: none - these changes will always happen instantly and report layouts of 0x0
