### ISSUE TITLE
[FEATURE] Reorder with multiple lists

### ISSUE THREAD

**Issue by ericfennis** [framer/motion#1435]
**Is your feature request related to a problem? Please describe.**
I would like to reorder multiple lists with the Reorder component. It would be nice if you can drag one item to a second list and reorder it.
With the current implementation you can only reorder one list. But you can't move items from listA to a listB.

**Describe the solution you'd like**
1. Support for multiple arrays or nested arrays or 
2. Additional callback function in the Reorder.Item that can help implementing a custom order function.

**Describe alternatives you've considered**
Switching to an other library that can make this possible like: 
https://lytc.github.io/react-sortly/#/examples/multiple-tree
https://github.com/frontend-collective/react-sortable-tree

**Additional context**
See this [demo](https://codesandbox.io/s/multilist-reorder-54ui0?file=/src/App.tsx) what I want to accomplish
or see this video. 

https://user-images.githubusercontent.com/11825403/151839227-fc12caa4-d79a-4c55-97fc-36d598135bcb.mov

**Comment by AcePetrucci** [comment]
+1 on that, this feature would be incredible as I'm stuck trying to come up with something to achieve this

**Comment by seleckis** [comment]
Nobody can do this? Really needed.

**Comment by mattgperry** [comment]
To set expectations I'm closing as a `wontfix`, it is unlikely to happen until we find a need for it within Framer.
