### ISSUE TITLE
Documentation issues /docs/examples

### ISSUE THREAD

**Issue by michael-harvey** [framer/motion#1437]
https://www.framer.com/docs/examples/#line-drawing

- The iframe has `title` and `src` switched, so the codesandbox embed isn't rendering. 
- The description for this section seems to be using back ticks for keywords `pathLength` and `pathSpacing` instead of `<code>` tags.

Apologies if this should be on the api-docs repo, but felt it was more appropriate here since the docs are now closed source.

Cheers for the great animation lib!

**Comment by mattgperry** [comment]
Thanks for this report! Fixed
