### ISSUE TITLE
[BUG] `AnimatePresence` not keeping up

### ISSUE THREAD

**Issue by Ploppy3** [framer/motion#1439]
**Describe the bug**

If the state changes fast enough, the final state can be broken.

https://codesandbox.io/s/serene-poincare-q45cs?file=/src/Loader.js

**Steps to reproduce**

Click quickly on the toggle button, you should end up with no grey square, which shouldn't be possible.

**Expected behavior**

The transition should be complete.

**Environment details**

Tested on Firefox and Chrome.

**Comment by mattgperry** [comment]
Dupe https://github.com/framer/motion/issues/907
