### ISSUE TITLE
[BUG] Animation Repeating

### ISSUE THREAD

**Issue by AaronBentley** [framer/motion#1441]
**Describe the bug**

I've made a small component (using create-react-app) to show how many trees have been planted  from an [Ecologi](https://ecologi.com/) campaign.

I animate the tree saplings, then I want to fade in an alert with data on the total amount of CO2e offset (note I'm using [Chakra UI](https://chakra-ui.com/) for the UI) once the tree saplings animation has completed.

This is working, however he tree saplings animation is repeated after implementing the `onAnimationComplete` prop on line 129.

I'm not sure what's causing the animation to repeat when the alert fades in after the saplings animation has completed? 🤔

**CodeSandbox reproduction of the bug**

https://codesandbox.io/s/nosy-trees-fos3b?file=/src/app.js

**Steps to reproduce**

Visit the CodeSandbox.

**Expected behavior**

I'd expect the `onAnimationComplete` to not initiate a repeated animation.

Have I missed something trivial here?

Thanks for taking the time to look at my issue ♥️

**Comment by mattgperry** [comment]
You're creating these components anew every single render:

```
    const MotionSimpleGrid = motion(SimpleGrid)
    const MotionFlex = motion(Flex)
 ```

These new components get mounted every single render, which means you animate `initial` -> `animate` every render too.

Moving these two lines to outside the component will fix the bug.

**Comment by AaronBentley** [comment]
Thank you @mattgperry 🙌 

Appreciated and confirmed is now working as intended - I had that sinking feeling I was doing something silly.

Thanks again.

**Comment by mattgperry** [comment]
No worries! Glad to hear this fixed it!

**Comment by emotionl** [comment]
> You're creating these components anew every single render:
> 
> ```
>     const MotionSimpleGrid = motion(SimpleGrid)
>     const MotionFlex = motion(Flex)
> ```
> 
> These new components get mounted every single render, which means you animate `initial` -> `animate` every render too.
> 
> Moving these two lines to outside the component will fix the bug.

Works for me ~
