### ISSUE TITLE
[QUESTION] How to handle layoutId and enter animations overlap

### ISSUE THREAD

**Issue by bootstrap-minui** [framer/motion#1442]
**Question**
When using both `layoutId` and `enter` (or `exit`) animations, animations will overlap.

Is it possible to avoid this behaviour? What would be the right approach to handle this?

**Demo**
https://codesandbox.io/s/framer-motion-animatesharedlayout-app-store-demo-forked-s6dpt?file=/src/List.js

**Steps to reproduce**
1. Click on a card. `layoutId` animation is triggered.
2. Click on overlay to go back to the list. `layoutId` and `enter` animations are triggered (overlap).

**Why I need both animations**
- I want to keep `enter` animation when there is no `layoutId` animations (If the list is the first page where I arrive or if I arrive on the list from a page that doesn't have a matching layoutId).
- I want to remove `enter` animation when there is a `layoutId` animation (If I arrive on the list from a page that has a matching layoutId).

**Comment by nilayfispan** [comment]
I was also wondering if this was possible! Is there a way to do this via existing components, or is this unsupported?

Thank you!

**Comment by mattgperry** [comment]
Aside from delay I don't think there's an easy solution to this, apologises.
