### ISSUE TITLE
[BUG] Sticky position on animated object's parent results in unnatural layout animation during scrolling

### ISSUE THREAD

**Issue by IgnusG** [framer/motion#1445]
**1. Describe the bug**

Using layout animations on a sticky element during scrolling causes the animated object to calculate the origin transform once and animate from it but the original would-be position of the object would have already changed with the scroll which results in unnatural animations. I'm unsure of if and where adding a `layoutScroll` could fix this.

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/framer-motion-sticky-layout-zikox?file=/src/App.tsx

**3. Steps to reproduce**

1. Scroll the codesandbox page and see how the animated red box stick to its position despite its original container leaving behind due to scroll

**4. Expected behavior**
The object should preferably keep the scroll in mind during animating so it adjusts its transform in line with the scrolled content. 

**5. Video or screenshots**

<img height="400px" src="https://user-images.githubusercontent.com/6438760/152687917-17feba54-9021-4b94-a215-d71f3a9e75ee.gif" />

**Comment by mattgperry** [comment]
This is unlikely to be fixed. The problem with `position: sticky` is it can be positioned in one of two coordinate spaces (page and viewport) but there's no good way of deciding when it's switched between the two.
