### ISSUE TITLE
[BUG] : SlideShow stuck when drag and doubleclick it

### ISSUE THREAD

**Issue by riky177** [framer/motion#1446]
I found that in framer motion docs they have an example slide show like this https://codesandbox.io/s/framer-motion-image-gallery-pqvx3?from-embed=&file=/src/Example.tsx, but I found a bug when we drag and double click it, it will be stuck like this picture

![image](https://user-images.githubusercontent.com/45587890/153114349-2b035489-d607-4189-abad-516f818ed4a8.png)

**Comment by ValentinH** [comment]
This can also be reproduced on a simpler example like this one: https://codesandbox.io/s/framer-motion-drag-with-constraints-pjn6t?from-embed=&file=/src/Example.tsx
<img width="383" alt="image" src="https://user-images.githubusercontent.com/2678610/170720642-89cdf505-2fea-4f4c-a71c-18b54cbcaa8f.png">

Drag the target outside of the box and double-click it before it returns to the constrained position.

**Comment by mattgperry** [comment]
Dupe https://github.com/framer/motion/issues/1404
