### ISSUE TITLE
[BUG] changing `animate` states in a parent can fail to show in children.

### ISSUE THREAD

**Issue by onnlucky** [framer/motion#1455]
A minimal testcase, a first click should turn the square orange, but won't:
```html
<script src="../../dev/webpack/react.development.js"></script>
<script src="../../dev/webpack/react-dom.development.js"></script>
<script src="dist/framer-motion.dev.js"></script>
<main id="main">ERROR</main>
<script>
    const _jsx = React.createElement
    const motion = Motion.motion

    const Component = function () {
        const [variant, setVariant] = React.useState("variant1")
        console.log("render:", variant)

        return _jsx(motion.div,
            {
                id: "OUTER",
                animate: variant,
                onTap: () => { console.log("OUTER onTap") },
            }
            , _jsx(motion.div,
                {
                    id: "INNER",
                    onTap: () => { console.log("INNER onTap"); setVariant("clicked") },
                    style: {
                        width: 300,
                        height: 300,
                    },
                    variants: {
                        "variant1": { "backgroundColor": "blue" },
                        "clicked": { "backgroundColor": "orange" },
                    },
                }
            )
        )
    }

    ReactDOM.render(_jsx(Component), document.getElementById("main"))
</script>
```

According to our analysis, the problem is this sequence:
1. The inner will fire `onPointerUp`, which will do `setActive`, which will `animateChanges` but with the soon-to-be-outdated animate context, this will setup `protectedKeys : { backgroundColor: true}` and no `needsAnimating`.
2. Then the inner `onTap` will fire, changing the `animate` state.
3. Then the outer will fire `onPointerUp`, doing `setActive`, doing `animateChanges`, doing `animateTarget` on the inner element, but it will block its animation.
4. Then the outer `onTap` will fire. Use effect will `animateChanges` again but no property changed, nothing happens.

One potential fix we tried is to only start animations from `useEffect`s, not from event handlers. But doing that as simply as possible breaks `whileHover` and other such features. See this PR: https://github.com/framer/motion/pull/1451

cc @shuangq

**Comment by onnlucky** [comment]
Perhaps it is helpful to add, this is a very boiled down version of code that Framer generates for its variant components if they include hovers states but no pressed states.

**Comment by shuangq** [comment]
The same example in the description in codesandbox: https://codesandbox.io/s/inspiring-sutherland-4ryin?file=/src/App.js
