### ISSUE TITLE
[BUG] AnimatePresence — element not unmounted onExitComplete

### ISSUE THREAD

**Issue by adrienpicard** [framer/motion#1457]
**1. Read the [FAQs](#faqs)
✅

**2. Describe the bug**
Using AnimatePresence I notice that the element is not fully un-mounted when `onExitComplete` or `onAnimationComplete` callbacks are called. I'm trying to trigger a resize when a component unmounts and I can't get the timings right because of this. How would one do this using Motion?

**3. Provide a CodeSandbox reproduction of the bug**
https://stackblitz.com/edit/framer-motion-animate-presence-q?file=index.tsx

It seems to work as expected on `enter`, but on `exit` the element is mounted still.

**5. Expected behavior**
On `exit`, when `onExitComplete` or `onAnimationComplete` are call, the component has unmounted.

**Comment by mattgperry** [comment]
This should have been fixed since, please reopen if not.

**Comment by glukki** [comment]
Still valid :(
I'm expecting the `onExitComplete` callback to get fired after the child's `useEffect` cleanup callback.
A bit extended original demo: https://stackblitz.com/edit/framer-motion-animate-presence-q-ufdg7s?file=index.tsx
