### ISSUE TITLE
[BUG] AnimatePresense runs previous animation when changing animation settings on motion.div

### ISSUE THREAD

**Issue by dmitry-vychikov** [framer/motion#1459]
**1. Read the [FAQs](#faqs) 👇** - read

**2. Describe the bug**
When I change animation settings (`initial`, `animate`, `exit` values) on `motion.div`, it will fire the OLDer animation that was set up previously, not the new one I'm changing to. This issue creates a "collision" of animations.

**My use case:**
I'm trying to achieve simple `SlideX` and `SlideY` animations in my app. The correct animation depends on the route transition.

I have 3 components: `MainView`, `ListView`, `DetailedListItemView`. I want to achieve the following animated transitions:
- `MainView` -> `ListView`:
    - `MainView` remains in place
    - `ListView` is animating in from the bottom of the screen above the `MainView`
- `ListView` -> `MainView`:
    - `ListView` is animating out down the screen and is showing the `MainView` that's hidden behind
- `ListView` -> `DetailedListItemView`:
    - `ListView` is animating out to the left and stays below
    - `DetailedListItemView` is animating in from the right and stays above

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**: https://codesandbox.io/s/framer-motion-animation-bug-8fp55r

**4. Steps to reproduce**

1. Open the sandbox
2. Click on `Go to List`: List will animate from bottom to top – its ok.
3. Click on any item in the list:
    - List will animate to the **bottom-left** - NOT ok
    - Detailed list view will animate from the right side - OK
4. Click on `Back to List`
    - Don't mind this animation, it does not look nice because proper "back" navigation implementation is missing here
 5. Click on`Go to main`
    - List will animate to the **bottom-right** - NOT ok
 

**5. Expected behavior**
1. n/a
2. OK
3. List should animate to the **left**, not _bottom-left_
4. n/a
5. List should animate to the **bottom**, not _bottom-right_
 
**6. Video or screenshots**

1)
https://user-images.githubusercontent.com/31896999/154547192-77b67146-a451-4410-a831-ccf8ea326731.mov

2)
And here's a longer version of the video with my comments. I had to upload it to Google Drive because it exceeds github's 10MB limit.
https://drive.google.com/file/d/1PDwV_1SzgGumGjgDiyAAZ1M9EJbxy-x8/view?usp=sharing

**7. Environment details**
Latest version of Chrome/Firefox/Safari on both Desktop and Android/iOS. The issue is identical in all the browsers

**8. Additional info**

My solution is based on `react-router` library where each view - is a separate route. For that reason, the CodeSandbox is quite large. I'll try to provide some docs here.

The solution consists of three parts:

1) Detecting the transition direction. Basically, I need to know which route I'm leaving and which route I will enter. As a result, I expose:
    - `useRouteTransition` hook that gives `from` and `to` values of the next transition
    - `useCustomNavigate`  hook which is a wrapper over react-router's `useNavigate`. It is required to correctly manage transitions and update `useRouteTransition`.

2) A small framework for defining transition routes and their animation settings.

Transitions are defined as following:

```js
export const animationsConfig = [
  ...makeSlideYTransition("/", "/list"),
  ...makeSlideXTransition("/list", "list/*")
];
```

`makeSlideYTransition` and `makeSlideXTransition` are helpers methods which construct `MotionProps` objects with appropriate `initial`, `animate` and `exit` props.

3) AnimatePresense wrapping my routes and a `motion.div` that uses the framework from 2) to get animation settings for the current transition
```js
<AnimatePresence initial={false}>
      <Routes location={location} key={location.pathname}>
        ...
     </Routes>
</AnimatePresence>
```

```js
export default function AnimationContainer({ children }) {
  const animation = useCurrentLocationTransitionAnimation();
  return (
    <motion.div className="container-absolute" {...animation}>
      {children}
    </motion.div>
  );
}
```

4) There are a couple of log messages in the sandbox that should help understand what values are actually being applied to the `motion.div`. The animation settings in the console seem correct, but the animation that's being applied **does not always match** the configuration passed to `motion.div` (in those cases I outlined in steps to reproduce section).

Please see my second video record (the one uploaded to google drive).

**Comment by mattgperry** [comment]
Looks like this has since been fixed.
