### ISSUE TITLE
[BUG] AnimatePresense throws "useLayoutEffect does nothing on the server" warning in Next Js

### ISSUE THREAD

**Issue by jnddao** [framer/motion#1460]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
AnimatePresense throws "useLayoutEffect does nothing on the server" warning in Next@12.1 + framer-motion@6.2.6

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-6-2-6-next-12-1-uselayouteffect-bug-u1vvp2?file=/pages/index.js
**Refresh the compiled page in CodeSandbox if error does not appear in console**

**4. Steps to reproduce**

Simply import AnimatePresense and use it and a warning will be thrown in Next after compilation.

**5. Expected behavior**

No warning is shown

**6. Video or screenshots**

![image](https://user-images.githubusercontent.com/51881944/154626558-1fae58ba-9794-4372-b496-9c12528f2207.png)

**7. Environment details**

Next@12.1
framer-motion@6.2.6

**Comment by feross** [comment]
Fixed in https://github.com/framer/motion/pull/1452

**Comment by dvlden** [comment]
@feross Did it make it in latest release? `6.2.7`
Because I don't see it mentioned in the changelog.

**Comment by StLyn4** [comment]
> @feross Did it make it in latest release? `6.2.7`
> 
> Because I don't see it mentioned in the changelog.

Personally, I don't see any more warnings after the update

**Comment by mattgperry** [comment]
Yeah it’s in 6.2.7 I just forgot to add it to the changelog!
