### ISSUE TITLE
[FEATURE] CountUP when in Viewport

### ISSUE THREAD

**Issue by aress31** [framer/motion#1461]
Is there any way to animate pure data, in this case numbers to create a count up that would leverage the `whileInView` prop?

This is a very common use case for adding animation to a website, if there is no trivial way to perform this using `framer-motion` maybe this could be added to the backlog?

**Comment by mattgperry** [comment]
It depends what you're trying to achieve. The `useInView` hook can be used to re-render when an element enters/leaves the viewport. The low-level `animate` function can be used to animate raw values.
