### ISSUE TITLE
[FEATURE] whileFocusWithin prop

### ISSUE THREAD

**Issue by tpict** [framer/motion#1465]
**Is your feature request related to a problem? Please describe.**
Orchestrating a chain of animations in a branch of the VDOM is really easy by applying `whileHover` to the root node. However, if you want to trigger the same animations when the user navigates inside of that branch using the keyboard, there's no `whileFocusWithin` prop that can handle that for you.

**Describe the solution you'd like**
A `whileFocusWithin` prop that behaves like `whileFocus`, but is triggered by any child element receiving focus.

**Describe alternatives you've considered**
Could pass animation controls to every child and trigger on focus events, or set up a listener/ref and check if `document.activeElement` is inside the root animation node.

**Additional context**
It just feels like a little hole in the API to me. It's _crazy_ how easy it is to declaratively write beautiful animations with the `whileHover` + `staggerChildren` approach. Would be nice to have the same with focus events

**Comment by mattgperry** [comment]
Closing as `wontfix` to set expectations. It might still get made but probably only if we find a use within Framer.
