### ISSUE TITLE
How can I do this??

### ISSUE THREAD

**Issue by pipi6782** [framer/motion#1467]
I'm sorry about asking here.
I wanna change rotation and size "only parent".
How can i do this?
it doesn't have to be parent-child.
It doesn't matter which way, if possible.
Sorry for my bad english :(
![image](https://user-images.githubusercontent.com/69996679/155488502-dbe4e5aa-2799-4ee5-a9d7-7054d668edaa.png)

**Comment by pipi6782** [comment]
`<Box
                component={motion.div}
                animate={{rotate: [0, 0, 270, 270, 0], scale:[0.7,1,1,0.7,0.7], borderRadius: ["20%", "20%", "50%", "50%", "20%"] }}
                transition={{duration: 2, repeat: Infinity, repeatDelay: 1}}
                className='child'>
                    <motion.img
                        src={puppy}
                        layoutId = "Image"
                        animate={{rotate:[0,0,-270,-270,0]}}
                        transition={{ duration: 2,repeat: Infinity,repeatDelay:1 }}
                        className="image"/>
            </Box>`

this is my code (i used it with mui)

**Comment by mattgperry** [comment]
You might have more luck in our Discord https://discord.com/invite/framer

This is indeed quite tricky. You can do something like this

```jsx
function Component() {
  const scale = useMotionValue(1)
  const rotate = useMotionValue(0)
  
  const childScale = useTransform(scale, latest => latest > 1 / latest)
  const childRotate = useTransform(rotate, latest => -latest)
  
  return (
    <motion.div animate={yourAnimation} transition={yourTransition} style={{ scale, rotate }}>
      <motion.div style={{ scale: childScale, rotate: childRotate }} />
    </motion.div>
  )
}
```

This will get you most of the way, it might also be that you need to do some work ensuring the child stays in the center of the parent but this is the princple.
