### ISSUE TITLE
How to hide scrollbar during transition?

### ISSUE THREAD

**Issue by ShahriarKh** [framer/motion#1468]
In many cases, the element I want to animate has `overflow: auto` and fixed height (or width). The problem with this is, when mixed with `motion`, the scrollbar appears even though it's not required (visually) or it keeps flashing until the transition is finished.  
Is it possible to give the element `overflow: hidden` **only during the transition**?

**Comment by helloromero** [comment]
@ShahriarKh is there a fix for this?

**Comment by ShahriarKh** [comment]
> @ShahriarKh is there a fix for this?

I'm looking for a solution just like you!

**Comment by HardCodeProgrammer** [comment]
I need a solution too... 😭

**Comment by a-churchill** [comment]
Try something like this:

```tsx
  const [isOpen, setIsOpen] = useState(initialIsOpen);
  const [isAnimating, setIsAnimating] = useState(false);

  return (
    <>
      {trigger}
      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.section
            initial="collapsed"
            animate="open"
            exit="collapsed"
            onAnimationStart={() => setIsAnimating(true)}
            onAnimationComplete={() => setIsAnimating(false)}
            style={{ overflow: isAnimating ? "hidden" : "auto" }}
            variants={{
              open: { opacity: 1, height: "auto" },
              collapsed: { opacity: 0, height: 0, overflow: "hidden" },
            }}
          >
            {children}
          </motion.section>
        )}
      </AnimatePresence>
```

The key is using the `isAnimating` state to switch the overflow behavior, and setting that state `onAnimationStart` and `onAnimationComplete`.

**Comment by dschlabach** [comment]
Note if you're using the `layout` prop, you'll want to use these instead:

```
onLayoutAnimationStart={() => setIsAnimating(true)}
onLayoutAnimationComplete={() => setIsAnimating(false)}
```

**Comment by mattgperry** [comment]
Can also use a motion value if you want to avoid a re-render

```javascript
const overflow = useMotionValue("scroll")

onAnimationStart={() => overflow.set("hidden")}
```
