### ISSUE TITLE
[BUG] motion.svg not animating with LayoutGroup ( but did with AnimateSharedLayout )

### ISSUE THREAD

**Issue by herrKlein** [framer/motion#1469]
**2. Describe the bug**

When using layout and layoutId with <motion.svg> it does not animate, while <motion.div> does.
With an older version,  framer motion 4 and <AnimateSharedLayout> it did animate.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-2-animating-shared-layouts-forked-0lpz7v

**4. Steps to reproduce**

In the codesandbox example 
1. Press the next button
2. the green sphere does animate, 
3. the red sphere does not 

**5. Expected behavior**

<motion.svg> also to animate when having the same props as a <motion.div>
It did work in framer motion 4 with <AnimateSharedLayout>

**Comment by herrKlein** [comment]
Apparently a know issue: https://www.framer.com/docs/animation/###svg-layout-animations-are-broken
Is there any estimate, since it used to work we have a product which relied on svg animations and with the new version of framer the svg's don't animate anymore :(

**Comment by mattgperry** [comment]
SVG layout animations may have worked incidentally but they wouldn't have worked robustly, I don't think we're in an immediate rush to add these either. However I think `svg` elements should be no problem, I will take a look.
