### ISSUE TITLE
[FEATURE] dragConstraints in a circular shape

### ISSUE THREAD

**Issue by partiellkorrekt** [framer/motion#1473]
**Is your feature request related to a problem? Please describe.**
I would like to create a virtual joystick with framer motion. I started the code like this:

```ts
const Knob = styled(motion.div)`
  /* Make this a nice round knob using styled-components */
`

const Joystick: React.FC = () => {
  const ref = useRef<HTMLDivElement>(null)
  return (
    <Wrap>
        <Background ref={ref} />
        <Knob
          drag
          dragSnapToOrigin
          dragConstraints={ref}
          dragElastic={0.1}
          dragTransition={{ bounceStiffness: 600, bounceDamping: 50 }}
        />
    </Wrap>
  )
}
```

The problem with this code is, that the dragging is restricted to the square bounding-box of the background, while the background itself is a circle using `border-radius: 100%`. That makes the joystick feel a little unnatural as the knob can "leave" the background diagonally while it can't leave it horizontally.

**Describe the solution you'd like**
I think the easiest solution would be a new property like `dragConstraintShape: 'rectangle' | 'circle'`.

**Describe alternatives you've considered**
Another way would be that instead of giving constraints, I can give it a function that gets the x/y-coordinates and returns the resistance against the movement away from the center. That function could then easily determine the distance to the center and at some threshold return `Infinity` or a very high number.

**Additional context**
Maybe this sketch helps understand the problem:
![Bildschirmfoto 2022-03-01 um 12 59 44](https://user-images.githubusercontent.com/4728256/156165472-c3038698-765c-4ad5-a5c2-315a9175bc81.png)

**Comment by kellymilligan** [comment]
I would love this feature too. Alternatively, I'd propose a `radius` confugration option inside `dragConstraints`:

```
<motion.div
  drag
  dragConstraints={{ radius: 100 }}
/>
```

- `radius` would need to be a positive number
- Allows translation in all directions up to the radius distance
- `left`, `right`, 'top`, `bottom` would be ignored if radius is defined? 

Cheers!

**Comment by mattgperry** [comment]
I like the feature idea but to set expectations I'm closing as a `wontfix` for now. Never say never as if we find a use for it within Framer it could still happen.

**Comment by 55Cancri** [comment]
Wanted to achieve something similar. Try it out with my gamepad joystick:

```typescript
import React from "react";
import { animate, PanInfo, useMotionValue } from "framer-motion";
import Grid from "atoms/grid";

export default function Dragpad() {
  const x = useMotionValue(0);
  const y = useMotionValue(0);
  const radius = 30;

  const handlePan = (
    event: MouseEvent | TouchEvent | PointerEvent,
    info: PanInfo
  ) => {
    // Calculate the new x and y position based on the drag delta
    const newX = x.get() + info.delta.x;
    const newY = y.get() + info.delta.y;

    // Calculate the distance from the center
    const distance = Math.sqrt(newX * newX + newY * newY);

    if (distance <= radius) {
      // If within the circle, update x and y to the new position
      x.set(newX);
      y.set(newY);
    } else {
      // If outside the circle, constrain the position to the circle's edge
      const angle = Math.atan2(newY, newX);
      const constrainedX = Math.cos(angle) * radius;
      const constrainedY = Math.sin(angle) * radius;
      x.set(constrainedX);
      y.set(constrainedY);
    }
  };

  const handlePanEnd = () => {
    // Animate x and y back to zero for the snap-back effect
    animate(x, 0, { type: "spring", stiffness: 500, damping: 30 });
    animate(y, 0, { type: "spring", stiffness: 500, damping: 30 });
  };

  return (
    <Grid
      position="relative"
      placeI
      w="100px"
      aspectRatio={1}
      br="50%"
      bg="blue.500"
    >
      <Grid
        style={{ x, y }}
        whileDrag={{ cursor: "grabbing" }}
        onPan={handlePan}
        onPanEnd={handlePanEnd}
        placeI
        w="35px"
        aspectRatio={1}
        br="50%"
        bg="neutral.900"
        cursor="grab"
      ></Grid>
    </Grid>
  );
}
```

Notice no drag props needed at all.
