### ISSUE TITLE
onViewportBoxUpdate how to get?

### ISSUE THREAD

**Issue by wallacerenan** [framer/motion#1474]
In newer versions the onViewportBoxUpdate property was removed, how do I get it in newer versions?

I need to update the lib in my project

I give an example of how it worked before

A old version:

[Old CodeSandbox](https://codesandbox.io/s/framer-motion-multiple-direction-drag-drop-0hztl?file=/src/App.js)

A new version:

[New CodeSandbox](https://codesandbox.io/s/framer-motion-multiple-direction-drag-drop-forked-vyu34l)

**Comment by sparkeplug** [comment]
Any update / workaround on this issue?

**Comment by TolgayEFE** [comment]
@wallacerenan did you find a way?

**Comment by mattgperry** [comment]
Dupe https://github.com/framer/motion/issues/1388

**Comment by Sallaa** [comment]
The **Reorder.Group** component is now available https://www.framer.com/motion/reorder/

**Comment by gyunayK** [comment]
Yes its available but there is no example of a grid! @Sallaa
