### ISSUE TITLE
[FEATURE] Animating text values

### ISSUE THREAD

**Issue by bhollis** [framer/motion#1476]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to animate a number counting up or down to a target, easily.

**Describe the solution you'd like**

In `react-spring`, I can use `interpolate` to do this, and it's quite straightforward:

```typescript
export default function AnimatedNumber({ value }: { value: number }) {
  const animatedValue = useSpring<{ val: number }>({ val: value, config: spring });
  return <animated.span>{animatedValue.val.to((val: number) => Math.floor(val))}</animated.span>;
}
```

**Describe alternatives you've considered**

The closest I've figured out in Framer Motion is much more awkward:

```typescript
const spring: Spring = {
  type: "spring",
  duration: 0.3,
  bounce: 0
};

function AnimatedNumberFramerMotion({ value }: { value: number }) {
  const ref = useRef<HTMLSpanElement>(null);
  const val = useMotionValue(value);

  useLayoutEffect(() => {
    const unsubscribe = val.onChange(
      (value) =>
        ref.current &&
        (ref.current.textContent = Math.floor(value).toLocaleString())
    );
    return unsubscribe;
  }, [val]);

  useEffect(() => {
    const controls = animate(val, value, spring);
    return controls.stop;
  }, [val, value]);

  return (
    <span className="number" ref={ref}>
      {Math.floor(value).toLocaleString()}
    </span>
  );
}
```

https://codesandbox.io/s/tender-water-zd3ei?file=/src/App.tsx

**Comment by marcelmusiol** [comment]
You can use `useSpring`, that makes it a bit shorter:

```tsx
import { useMotionValue, useSpring } from "framer-motion";

function AnimatedNumberFramerMotion({ value }: { value: number }) {
  const ref = useRef<HTMLSpanElement>(null);
  const motionValue = useMotionValue(0);
  const springValue = useSpring(motionValue);

  useEffect(() => {
    motionValue.set(value);
  }, [motionValue, value]);

  useEffect(
    () =>
      springValue.onChange((latest) => {
        if (ref.current) {
          ref.current.textContent = latest.toFixed(0);
        }
      }),
    [springValue]
  );

  return <span ref={ref} />;
}
```

**Comment by coreyward** [comment]
I have the same problem. I suppose something like this works if you have a small component that is okay to render a lot:

```jsx
const useInterpolatedMotionValue = (motionValue, optionalCallback) => {
  const [interpolatedValue, setInterpolatedValue] = useState(motionValue.get())

  useEffect(() =>
    motionValue.onChange(value => {
      setInterpolatedValue(optionalCallback ? optionalCallback(value) : value)
    }, [])
  )

  return interpolatedValue
}
```

**Comment by loupmasneri** [comment]
> You can use `useSpring`, that makes it a bit shorter:
> 
> ```tsx
> import { useMotionValue, useSpring } from "framer-motion";
> 
> function AnimatedNumberFramerMotion({ value }: { value: number }) {
>   const ref = useRef<HTMLSpanElement>(null);
>   const motionValue = useMotionValue(0);
>   const springValue = useSpring(motionValue);
> 
>   useEffect(() => {
>     motionValue.set(value);
>   }, [motionValue, value]);
> 
>   useEffect(
>     () =>
>       springValue.onChange((latest) => {
>         if (ref.current) {
>           ref.current.textContent = latest.toFixed(0);
>         }
>       }),
>     [springValue]
>   );
> 
>   return <span ref={ref} />;
> }
> ```

Why when adding `duration` to the useSpring config it does not work anymore ?

**Comment by loupmasneri** [comment]
> > You can use `useSpring`, that makes it a bit shorter:
> > ```tsx
> > import { useMotionValue, useSpring } from "framer-motion";
> > 
> > function AnimatedNumberFramerMotion({ value }: { value: number }) {
> >   const ref = useRef<HTMLSpanElement>(null);
> >   const motionValue = useMotionValue(0);
> >   const springValue = useSpring(motionValue);
> > 
> >   useEffect(() => {
> >     motionValue.set(value);
> >   }, [motionValue, value]);
> > 
> >   useEffect(
> >     () =>
> >       springValue.onChange((latest) => {
> >         if (ref.current) {
> >           ref.current.textContent = latest.toFixed(0);
> >         }
> >       }),
> >     [springValue]
> >   );
> > 
> >   return <span ref={ref} />;
> > }
> > ```
> 
> Why when adding `duration` to the useSpring config it does not work anymore ? Like so:
> 
> ```
> useSpring(motionValue, { duration: 1.5 })
> ```

nevermind duration here is in milliseconds so it must be multiplied by 1000
