### ISSUE TITLE
[BUG] Position Fixed Draggable Element Jumps When Using Drag Controls

### ISSUE THREAD

**Issue by yashspr** [framer/motion#1480]
**2. Describe the bug**

I have a fixed (`position: fixed`) draggable element which is controlled by one of its children with the help of `useDragControls`. It works fine on initial page load. But when we scroll the page and then try to drag the element, it just jumps. Not sure what is happening.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[https://codesandbox.io/s/fixed-element-drag-controls-jumping-issue-9f8t9z?file=/src/App.js](https://codesandbox.io/s/fixed-element-drag-controls-jumping-issue-9f8t9z?file=/src/App.js)

**4. Steps to reproduce**

1. Open the sandbox but don't drag anything yet.
2. Scroll to the very bottom of the page.
3. Drag the element by dragging the "Drag" child
4. The element just jumps off the screen

**5. Expected behavior**

The element shouldn't jump from its position when trying to drag it even after the page is scrolled.

**7. Environment details**

Using `frame-motion` 6.2.6 & tested it on latest versions of Chrome & Firefox.

-------------------------------------------------------------

Thanks

**Comment by anki247** [comment]
I see, It is a similar issue like I have (reported some min ago) 
If you could live without `snapToCursor: true` it seems to work... 🤔

**Comment by yashspr** [comment]
@anki247 Didn't realize its such a simple fix. Thanks!  Totally works for my use case

**Comment by mattgperry** [comment]
Closing for https://github.com/framer/motion/issues/2465
