### ISSUE TITLE
[BUG] Bugged movement in scaled parent element

### ISSUE THREAD

**Issue by spadgeaki** [framer/motion#1481]
This is reopening of #874, problem still occurs.

- I wanted to animate inside parent element that has `transform: scale(${scale})` applied
- Element animation is not animated the whole way - it jumps to center and animates from there
- I guess I should somehow make Framer Motion take that scale in consideration when animating position?
- I found old issue (#265) where `MotionConfig` with `transformPagePoint` prop should help but it doesn't seem to call the transform function (as it seems to be implemented only for drag gestures)

Codesandbox to showcase this issue:
https://codesandbox.io/s/bug-while-parent-scaled-bbwyq?file=/src/App.js

**Comment by mattgperry** [comment]
Essentially the same problem as https://github.com/framer/motion/issues/1414 - fix together
