### ISSUE TITLE
[BUG] Dragging ended by scrolling on iOS 15 Safari

### ISSUE THREAD

**Issue by mattp0123** [framer/motion#1482]
**1. Describe the bug**

As titled

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-drag-with-constraints-forked-92pijf?file=/src/Example.tsx

**3. Steps to reproduce**

Drag the cube horizontally and scroll a little bit using iOS 15 Safari

**4. Expected behavior**

Should lock the direction or at least not that sensitive.
`dragDirectionLock` prop should do the job.

**5. Environment details**

iOS 15 Safari

**Comment by mattgperry** [comment]
Thanks for the report - this is being tracked here https://bugs.webkit.org/show_bug.cgi?id=233417

**Comment by mattp0123** [comment]
@mattgperry Thanks for the reply.
Maybe check `@use-gesture/react` out. When the `preventScroll` option is set to `true`, dragging will not be stopped by scrolling.
https://codesandbox.io/s/framer-motion-drag-with-constraints-forked-92pijf?file=/src/index.tsx
