### ISSUE TITLE
[BUG] TypeError: a is not a function when applying ease to useTransform

### ISSUE THREAD

**Issue by TomSmedley** [framer/motion#1483]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

UseTransform is reporting an error when an ease is added to the options, documentation doesn't clearly demonstrate how the ease should be applied.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://stackblitz.com/edit/github-6rkaja?file=src%2Fcomponents%2FButton.jsx

**Comment by mattgperry** [comment]
Good catch, I've exported all the easing functions and updated the documentation.
