### ISSUE TITLE
[BUG] Spring set via `bounce` and `duration` can become "stuck"

### ISSUE THREAD

**Issue by thexpand** [framer/motion#1484]
**1. Describe the bug**
There is a component, that acts as a container, which makes use of `whileHover` and variants to animate a nested child component. The container/parent component has an initial state/animation of "idle" and then on hover it animates to a "hover" state. The child component has defined its variants through the `variants` prop. When I try to hover over the container, don't wait for the animation to complete, and then quickly move my mouse out of the container, the animation freezes for a second before animating back to the "idle" state. At first I thought that it happened because I was using `whileHover` and thought it was a bug with this prop in particular. But then I tried to replicate this whole thing by having a custom animation control via the `useAnimation` hook and with `onHoverStart` and `onHoverEnd` callback props on the animated container. Sadly, I noticed the same behavior. Finally, I decided to test with a completely different gestures library `@use-gesture/react` and did a `...bindHover()` on the container to only find out that the issue remains. So, I figured out the problem was because of the `AnimationControls.start()` method being called in a short amout of time subsequently. Finally, I tested a workaround with `setTimeout`, which you can see in the CodeSandbox and it seems to be working, but it's very ugly. Basically, I stop the animation and after 1ms start it again in the opposite direction (towards "idle").

I tried searching for similar issues, but couldn't find the same issue. It might be connected to this one in some way though https://github.com/framer/motion/issues/1179

**2. Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/framer-motion-start-overlapping-freeze-be4rty?file=/src/App.js

**3. Steps to reproduce**
1. Go to the CodeSandbox
2. Try to hover on one of the elements/links (except the ones in the workaround), and before the animation finishes, go out of the element.
3. Try this for a few seconds, or just go rushing your mouse up and down over the elements to see the bug.

**4. Expected behavior**
I expect the animation to start transitioning back to the "idle" state right after the mouse leaves the element, not after some "freeze" time.

**5. Video or screenshots**
https://user-images.githubusercontent.com/14979167/158030859-9d677db6-2284-440b-925a-8428c3efb04d.mp4

**6. Environment details**
- Windows 10 (10.0.19044 Build 19044)
- Chrome 99.0.4844.51 / Firefox 98.0 / Edge 99.0.1150.39
- framer-motion@6.2.8

**Comment by mattgperry** [comment]
Should be fixed in `10.17.2`
