### ISSUE TITLE
[BUG] AnimatePresence not working for imported react component

### ISSUE THREAD

**Issue by Ellarddekoeijer** [framer/motion#1487]
**1. Read the [FAQs](#faqs) 👇**
Read

**2. Describe the bug**
After following the docs (https://www.framer.com/docs/animate-presence/##animating-custom-components) I tried using custom react components inside the AnimatePresence. However it seems to me that importing a react component makes it so that the exit animation is not called. 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/serverless-haze-6h3x4i?file=/src/App.js:691-703
Note how the input_question's exit animation is not called. 

**4. Steps to reproduce**

1. Import AnimatePresence
2. Import React components with a motion.div element that has an exit animation.
3. Conditionally render one of the React components inside of the AnimatePresence (Inside the AnimatePresence, so that it remains mounted)

**5. Expected behavior**
The imported react components should animate out.

**7. Environment details**
Windows, Chrome version 98.0.4758.102 (Official Build) (64-bit)

**Comment by anki247** [comment]
It seems that the problem you are facing comes from the wrong import of framer-motion
You should import like this `import {...} from "framer-motion";`

**Comment by Ellarddekoeijer** [comment]
@anki247 you are totally right of course. It seems that Webstorm was recommending me the wrong path and I blindly followed it. This is resolved, thank you very much!
