### ISSUE TITLE
[BUG] Remove bounce on return

### ISSUE THREAD

**Issue by dottodot** [framer/motion#1488]
How do you stop the animation from bouncing on the return and using whileHover? Setting bounce to 0 has no effect. On release you'll see that the background bounces when it returns to the original position.

https://codesandbox.io/s/stoic-rgb-lz46jf?file=/src/App.js

**Comment by anki247** [comment]
You should put the transition outside
https://codesandbox.io/s/happy-pine-bc1mq2?file=/src/App.js

**Comment by dottodot** [comment]
@anki247 thanks, think I must have been looking at this example that has the transition inside https://www.framer.com/docs/gestures/#animation-helpers
