### ISSUE TITLE
[BUG] Elements being highlighted when interacted with in Reorder.Group

### ISSUE THREAD

**Issue by brad-bartlett** [framer/motion#1489]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

This is the sandbox from the docs. The only difference is the package is updated to its current version. When dragging an element it highlights the elements that it passes by, this only happens when going down. Up seems to be working fine. Any solution to this would be greatly appreciated.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Sandbox: (https://codesandbox.io/s/framer-motion-5-drag-to-reorder-lists-with-drag-handle-forked-9e45f1?file=/src/Item.tsx)

**4. Steps to reproduce**

1. update package to current (this sandbox already is)
2. drag an element down
3. it highlights the text of the elements is passes by

**5. Expected behavior**

Elements should not be highlighted

**Comment by anki247** [comment]
you just can apply to the labels
```css
user-select: none;
``` 
https://codesandbox.io/s/framer-motion-5-drag-to-reorder-lists-with-drag-handle-forked-g7e493?file=/src/Item.tsx

**Comment by brad-bartlett** [comment]
Thank you for the response. I should have put this in the original post, I tried that and it did fix the problem but then the list doesn't scroll when dragging an element. Doing user-select: none also makes weird things happen on the page like selecting other elements that are outside the list

**Comment by brad-bartlett** [comment]
It seems that it needs to be able to select the list items to be able to scroll

**Comment by erikiva** [comment]
I am having the same problem, if I add `user-select: none;` and the list of values is longer, the scroll doesn't work and  I can't drag an item below or above the visible area. Is there any other way to fix it?

**Comment by HamdyD** [comment]
Same problem here, thanks for reporting. Any updates @brad-bartlett ?

**Comment by Ambroos** [comment]
In case anyone else hits this: the only thing needed to fix this is to call event.preventDefault where you call dragControls.start(event).

```
      onPointerDown={(event) => {
        dragControls.start(event);
        event.preventDefault();
      }}
```

The exact same bugged sandbox from above with only this fix applied works great: https://codesandbox.io/s/framer-motion-5-drag-to-reorder-lists-with-drag-handle-forked-b63eiq?file=/src/Icon.tsx

**Comment by EtienneWei** [comment]
> In case anyone else hits this: the only thing needed to fix this is to call event.preventDefault where you call dragControls.start(event).
> 
> ```
>       onPointerDown={(event) => {
>         dragControls.start(event);
>         event.preventDefault();
>       }}
> ```
> 
> The exact same bugged sandbox from above with only this fix applied works great: https://codesandbox.io/s/framer-motion-5-drag-to-reorder-lists-with-drag-handle-forked-b63eiq?file=/src/Icon.tsx

Thanks, that worked for me!
