### ISSUE TITLE
[BUG] dragSnapToOrigin does not work, when by *only* click in combination with snapToCursor

### ISSUE THREAD

**Issue by anki247** [framer/motion#1490]
**1. Read the [FAQs](#faqs) 👇**
✅

**2. Describe the bug**

I have a drag element with `const onPointerDown = (e) => dragControls.start(e, { snapToCursor: true })` and I want to `dragSnapToOrigin` on drag end. Which works actually perfect when I do dragging, but if I **just click it** the drag element snaps to cursor and stays on the new position (ignores `dragSnapToOrigin`)

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/the-framer-book-example-animations-08-while-drag-forked-y5s4ty?file=/src/Example.jsx

**4. Steps to reproduce**

1. open CodeSandbox link -> you'll see a box
2. click somewhere on the corner (e.g right top) !important just click
3. The box snaps to the cursor and stays there

**5. Expected behavior**

There are 2 possible "expected behavior" and both would be fine for me
1. when only clicking without dragging -> prevent `snapToCursor`.
2. By mouse up -> The drag element should `dragSnapToOrigin`

**6. Video or screenshots**

https://user-images.githubusercontent.com/3366211/159142888-d04fd96e-6a2c-411f-9860-5f778e8808ff.mp4

**7. Environment details**

MacOS, Chrome

**Comment by Liel208** [comment]
+1

**Comment by mattgperry** [comment]
Should be fixed in `10.17.1`
