### ISSUE TITLE
[BUG] ES builds should not be using .mjs extension

### ISSUE THREAD

**Issue by milesj** [framer/motion#1492]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

Framer is a _web_ package and is shipping `.mjs` files for its web ES build, but `.mjs` is a _Node.js only_ feature.

Because of this, all downstream consumers that utilize Webpack (and probably other bundlers) are unable to use this package without patching their webpack config ([as seen here](https://github.com/framer/motion/issues/1307), and [all these other issues](https://github.com/framer/motion/search?q=es&type=issues)), and at a large company, this could be tens to hundreds of projects (what we're dealing with). 

If a consumer is required to patch things on their end, then the package is doing something it shouldn't be. All of these new file extensions (cjs, mjs, etc) have specific semantics and should be used correctly.

Solution:

`es` files should just use a `.js` file extension, since `.mjs` provides no benefit, but causes headaches for everyone else.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

A sandbox isn't necessary.

**4. Steps to reproduce**

1. Install the dep.
2. Try and bundle it with webpack.

**5. Expected behavior**

ES builds should not use `.mjs` file extension, just use `.js`.

**6. Video or screenshots**

N/A

**7. Environment details**

N/A

**Comment by isc30** [comment]
webpack5 enforces `.mjs` and `.cjs` file extensions.

The workaround for webpack4 is different: https://github.com/framer/motion/issues/1307#issuecomment-1059820972

**Comment by milesj** [comment]
@isc30 The `exports` field is meant to denote that information. If webpack is not respecting that, then it should be fixed upstream.

Furthermore, we are on the latest webpack 5 and we still can't load `.mjs` files without adding that patch.

**Comment by Noitidart** [comment]
Thanks for this topic @milesj - my built code also has a bunch of `let`s and `...` and other features not compatible in older browsers. Did you have a solution to transpile it down? I have a discussion opened here - https://github.com/framer/motion/discussions/1953

**Comment by mattgperry** [comment]
Framer Motion runs on Node.js, often. `.mjs` has worked for us for years and this is a bit of a rabbit hole that could cause us a lot of problems to change. Likewise, given the download numbers and the lack of people that contact me about this I have to conclude that it is working for most people. Sorry it doesn't work for you but this is a `wontfix`.
