### ISSUE TITLE
[BUG] clipPath with keyframes and inset function don't work

### ISSUE THREAD

**Issue by jullite** [framer/motion#1494]
**2. Describe the bug**

clipPath with keyframes and inset function don't work

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/framer-motion-clip-path-forked-jnr93g?file=/src/App.js

**4. Steps to reproduce**
1. open codesandbox
2. refresh page

**5. Expected behavior**

div with color swipe from let to right

**6. Video or screenshots**
https://gifyu.com/image/SpFP3

**7. Environment details**

- desktop: MacBook Pro (13-inch, M1, 2020)
- browser: chrome Version 99.0.4844.83 (Official Build) (arm64)

**Comment by prrrcl** [comment]
This is not a bug. You must write 0% (not zero)

**Comment by jullite** [comment]
> This is not a bug. You must write 0% (not zero)

oh, thanks for your help!
