### ISSUE TITLE
[BUG] Visual state is not synced correctly for nested motion component when using whileTap and whileHover

### ISSUE THREAD

**Issue by AlexSchwabauer** [framer/motion#1499]
**2. Describe the bug**
Hey all,

first of all thanks for the awesome and intuitive animation framework!
I am experiencing an issue when trying to use `whileTap` and `whileHover` simultaneously in combination with variants. The top-most motion component works as expected, i.e. switches to the correct variant (onHover, onTap, ect.). However, a child motion component that consumes the variants state ends up in a different state than the parent after onTap.

**3. Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/youthful-sky-5wejmo?file=/src/App.tsx

**4. Steps to reproduce**
1. Open sandbox
2. Hover over parent or child component; notice correct syncing of background
3. Click and hold parent or child component;  notice correct syncing of background
4. Release click;  notice **incorrect** syncing of background: parent is correctly in "hover" state, while the child component is in "animate" state.
5. Only after hovering out of parent and reenter, the state is fixed.

**5. Expected behavior**
Child component should go back to "hover" state after click release, just as the parent.

**Comment by randose** [comment]
Did this ever get resolved? I'm running into this issue as well!

**Comment by iDavid2619** [comment]
Same issue, I've tried using a callback function for dynamic varients, the function was correctly triggered after tapping, but the returned style was not applied to the component
