### ISSUE TITLE
[BUG] "reducedMotion" not implemented on <MotionConfig>

### ISSUE THREAD

**Issue by probablyup** [framer/motion#1502]
The documentation for framer-motion indicates that the `MotionConfig` provider component can take a property called `reducedMotion` that allows for global configuration of if motion animations should work or not depending on browser preference.

https://www.framer.com/docs/motion-config/#props

Looking at the code for the component, it appears this functionality was never actually implemented. The only way to customize motion behavior at the moment is the `useReducedMotion` hook, which works but is cumbersome to put in every single component.

**Comment by mattgperry** [comment]
```
export interface MotionConfigProps extends Partial<MotionConfigContext>
```

https://github.com/framer/motion/blob/main/packages/framer-motion/src/components/MotionConfig/index.tsx#L10

The `MotionConfigContext` defines the prop

**Comment by probablyup** [comment]
I'm aware, the functionality does nothing and the type for the component says its not a valid prop. What am I missing if you read the documentation and follow it?

**Comment by mattgperry** [comment]
That it does work and the type's aren't incorrect: https://codesandbox.io/s/framer-motion-keyframes-ekks8?file=/src/index.tsx
