### ISSUE TITLE
translate3d values remaining after animation

### ISSUE THREAD

**Issue by sswatson** [framer/motion#1505]
I have a dynamic list of `motion.div` components with `layout=true` which are rendered as children of a vertically oriented flexbox. 

After an item is removed, some of the children are sometimes out of place following the layout animation. Inspecting the DOM post-animation reveals that the `transform` css property is `none` on these elements when the animation works properly and something like `translate3d(0, -713px, 0)` when it doesn't. Manually changing the vertical displacement to zero puts the elements into the correct position.

I really wish I could create a CodeSandbox reproduction, but extracting the code from my app unfortunately solves the problem (which is especially hard to check since it's intermittent anyway). Therefore, I'm assuming there is some issue which is specific to my app's internal logic.

Still, I'm guessing that it's unusual for `motion.div` components to retain a `transform` post-animation, so I'm hoping that it will still be useful to report the issue at this level of detail.

**Comment by Benny233** [comment]
met the same issue, translate3d values remains after animation

**Comment by paragkatoch** [comment]
I have the same issue, translate3d value remains on some of the components after animation
