### ISSUE TITLE
[BUG] AnimatePresence doesn't work with React 18 type definitions

### ISSUE THREAD

**Issue by adhip94** [framer/motion#1509]
**1. Read the [FAQs](#faqs) 👇**
Yes

**2. Describe the bug**

AnimatePresence throws an error when used with React and React-DOM v18.
`Type '{ children: false | Element; key: string; }' is not assignable to type 'IntrinsicAttributes & AnimatePresenceProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & AnimatePresenceProps'`

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-image-gallery-forked-4l74mi?file=/package.json

In the codesandbox, if you hover on the AnimatePresence component, you will be able to see the error. Weirdly it doesn't throw an error when building in codesandbox.

**4. Steps to reproduce**

Upgrade FramerMotion to v6.2.9, React and react-dom to v18 including the type definitions of each. Then build the application and an error will be thrown.

**5. Expected behavior**

Error should not be thrown and build should happen properly when used with React 18.

**6. Video or screenshots**

![image](https://user-images.githubusercontent.com/20703483/162413911-5a52dfd3-c422-457b-9ebb-93897985f90f.png)

**7. Environment details**

**Comment by Iipal** [comment]
Adding more info, this was caused by this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210.

And there is description why they done this.

Waiting for soon hot-fix as `framer-motion 6.2.10` :)

**Comment by TimKolberger** [comment]
Until this is released this workaround fixes it for me:

Create a type augmentation in `<your-codebase>/framer-motion.d.ts`

```ts
import * as React from "react"

declare module "framer-motion" {
  export interface AnimatePresenceProps {
    children?: React.ReactNode
  }
}
```

**Comment by sajadevo** [comment]
Until they fix the issue you can simple use this trick in TypeScript to fix that issue I also had the same issue when using the `<AnimatePresence />` of framer-motion but I came up with something like the code below which fix my issue:

#### Before
```jsx
import React from "react";
import { AnimatePresence } from "framer-motion";

export function AnimatedComponent({ children }: { children: React.ReactNode }) {
   return <AnimatePresence>{children}</AnimatePresence>
}
``` 

#### After
```jsx
import React from "react";
import { AnimatePresence, AnimatePresenceProps } from "framer-motion";

interface NewAnimatePresenceProps extends Omit<AnimatePresenceProps, "children"> {
   children: React.ReactNode;
}

export function AnimatedComponent({ children }: { children: React.ReactNode }) {  
  const NewAnimatePresence: React.FC<NewAnimatePresenceProps> = AnimatePresence;

  return <NewAnimatePresence>{children}</NewAnimatePresence>
}
```

**Please lemme know if it doesn't work for you so that I can help you in a better possible way.**

**Comment by rayandus-ombori** [comment]
This worked for me
// @ts-ignore
import { motion } from 'framer-motion/dist/framer-motion';

I am using
"framer-motion": "^7.3.2"
"react": "^18.2.0"
"react-scripts": "4.0.3"

**Comment by rayandus** [comment]
This worked for me 
// @ts-ignore
 import { motion } from 'framer-motion/dist/framer-motion';

I am using
 "framer-motion": "^7.3.2" 
"react": "^18.2.0"
 "react-scripts": "4.0.3"
