### ISSUE TITLE
Exit Animation Not Work in react router v6

### ISSUE THREAD

**Issue by bobwatcherx** [framer/motion#1510]
**2. Describe the bug**

I'm having trouble returning to the previous page.
exit animation doesn't work there

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/restless-pine-y67rh9?file=/src/pages/About.js

```

**Comment by Zzongke** [comment]
demo:[stackblitz ](https://stackblitz.com/edit/react-ts-d7qn9z?file=pages/Home.tsx)

I'm at stackblitz Com website, there is a local copy of the project test. I didn't encounter this problem. It should be codesandbox There is this problem on the IO web page.

Hope to help you!

**Comment by mattgperry** [comment]
Here's a working setup https://codesandbox.io/s/framer-motion-react-router-6-page-transitions-2f2olf
