### ISSUE TITLE
[BUG] Animated Values in SVG RECT keep shifting back and forth

### ISSUE THREAD

**Issue by amcdnl** [framer/motion#1513]
## Issue
I'm using framer-motion to animate charts in reaviz.io. I noticed recently that some of the chart attributes ( such as `x` in this case ) when they have large numbers framer-motion seems to not handle them correctly.

If you goto this link https://reaviz.io/?path=/story/charts-bar-chart-vertical-multi-series--marimekko you can see they constantly are shifting back and forth. ( video: https://www.screencast.com/t/J8PMBF3TGe )

![image](https://user-images.githubusercontent.com/227909/163186467-308e89cd-fd2c-4d15-b7f4-3009bd357a1a.png)

I captured the attributes ( x then y ) in a console to show the numbers its being passed:

![image](https://user-images.githubusercontent.com/227909/163186712-c0fce729-637d-4f4d-a82a-d27c07fa0be0.png)

I attempted to do something like `.toFixed(2)` however the animations did not work as expected in that case.

The code for where the values are passed to the `motion.rect` is here: https://github.com/reaviz/reaviz/blob/master/src/BarChart/BarSeries/Bar.tsx#L544-L549

## Environment
    "framer-motion": "^6.2.10",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",

NOTE: Even though its React 18, I'm not using the new renderer hook so its working in v17 mode.

**Comment by mattgperry** [comment]
I think rather, these are extremely small numbers. (1e-27 being `0.00000000000000000000000007`) for instance

It looks as though the animation keeps getting closer to `0` without stopping - this is why `restDelta` is set to something like `0.01`. Without a simplified codesandbox reproduction I won't be able to look into this any further only to say that its odd and not something I've seen before.

**Comment by mattgperry** [comment]
Thanks for the sandbox! If you add 

```
            restDelta: 0.01,
            restSpeed: 0.01
```

This will fix it. As for why this isn't being applied by default I'm not sure, definitely a bug.
