### ISSUE TITLE
[BUG] TS2559 Error in AnimateSharedLayout

### ISSUE THREAD

**Issue by HyeokE** [framer/motion#1514]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

TS2559: Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes'.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/jovial-meitner-sghvsb?file=/src/App.tsx

**4. Steps to reproduce**

1. Go to 'https://codesandbox.io/s/jovial-meitner-sghvsb?file=/src/App.tsx'
2. Click on 'app.tsx'

<img width="490" alt="Screen Shot 2022-04-15 at 5 28 14 PM" src="https://user-images.githubusercontent.com/61281239/163546461-256841a4-dbc7-4039-a02c-bd2261c5097f.png">

**5. Expected behavior**

It works when I edit code AnimateSharedLayout.d.ts 

```
export declare const AnimateSharedLayout: React.FunctionComponent;
```

to

```
export declare const AnimateSharedLayout: React.FC<{ children: React.ReactNode }>;
```

**6. Video or screenshots**

<img width="801" alt="Screen Shot 2022-04-15 at 5 13 55 PM" src="https://user-images.githubusercontent.com/61281239/163544666-3e7bb34f-5fe1-4924-b518-2954c0a3fd28.png">

**7. Environment details**

browser: chrome Version 100.0.4896.88 (Official Build) (arm64)

```
{
  "scripts": {
    "start": "webpack-dev-server --mode development",
    "prebuild": "rimraf dist",
    "build": "webpack --mode=production --node-env=production",
    "build:dev": "webpack --mode=development",
    "build:prod": "webpack --mode=production --node-env=production",
    "watch": "webpack --watch",
    "serve": "webpack serve"
  },
  "dependencies": {
    "@types/lodash": "^4.14.181",
    "@types/styled-components": "^5.1.25",
    "clean-webpack-plugin": "^4.0.0",
    "framer-motion": "^6.3.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.3.0",
    "styled-components": "^5.3.5",
    "styled-normalize": "^8.0.7"
  },
  "devDependencies": {
    "@babel/core": "^7.17.9",
    "@babel/preset-env": "^7.16.11",
    "@babel/preset-react": "^7.16.7",
    "@babel/preset-typescript": "^7.16.7",
    "@types/react": "^18.0.5",
    "@types/react-dom": "^18.0.1",
    "@webpack-cli/generators": "^2.4.2",
    "autoprefixer": "^10.4.4",
    "babel-loader": "^8.2.4",
    "css-loader": "^6.7.1",
    "fork-ts-checker-webpack-plugin": "^7.2.6",
    "html-webpack-plugin": "^5.5.0",
    "postcss": "^8.4.12",
    "postcss-loader": "^6.2.1",
    "prettier": "^2.6.2",
    "rimraf": "^3.0.2",
    "style-loader": "^3.3.1",
    "ts-loader": "^9.2.8",
    "typescript": "^4.6.3",
    "webpack": "^5.72.0",
    "webpack-cli": "^4.9.2",
    "webpack-dev-server": "^4.8.1",
    "workbox-webpack-plugin": "^6.5.3"
  },
}

```

**Comment by mattgperry** [comment]
`AnimateSharedLayout` was deprecated in 5
