### ISSUE TITLE
[Question] How to specify duration for initial and exit animation seperately?

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [framer/motion#1516]
How can I specify the duration for initial and exit animations seperately, so:
	
		 initial={{y: 12, opacity: 0, scale: .5, }}     // Should have duration 3
  		exit={{y: -24, opacity: 0, scale: .3}}   // Should have duration 1

**Comment by ryanto** [comment]
You can pass a `transition` property to your `initial` and `exit`.

Example:

```jsx
<motion.div
  initial={
    {
      y: 12,
      opacity: 0,
      scale: .5,
      transition: { duration: 3 }
    }
  } 
  exit={
    {
      y: -24,
      opacity: 0,
      scale: .3,
      transition: { duration: 5 }
    }
  } 
>
```
