### ISSUE TITLE
[Question] How to specify "not to play exit animation before initial animation has finished"

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [framer/motion#1517]
How do you specify "not to play exit animation before initial animation has finished"?

exitBeforeEnter on animatepresence is not what I am after, since many elements is allowed to enter and exit at once ... their initial animation just have to finish entirely before their exit animation starts

**Comment by ryanto** [comment]
The animations in framer motion are designed to be interruptible and cancelable. 

Imagine a div that goes from opacity 0 to 1 based on an `isShowing` boolean:

```jsx
<motion.div animate={{ opacity: isShowing ? 1 : 0 }}>
```

If you get 50% through this animation and then isShowing flips back to `false`, framer motion will start animating opacity back to 0 from the 50% point.

If you want more fined grained control over when these animations start you should take a look at [animation controls](https://www.framer.com/docs/animation/#component-animation-controls). These APIs will let you imperatively control when an animation starts. This will let you detect if any animation is taking place, and not allow the item to exit until their animations have finished.
