### ISSUE TITLE
[BUG] ReorderGroup not work correctly on React 18

### ISSUE THREAD

**Issue by debugksir** [framer/motion#1518]
codesandbox link:

https://codesandbox.io/s/framermotionbugreport-12vxmn?file=/src/index.tsx

**Comment by mattgperry** [comment]
I had a brief look into this and so far I think this is happening specifically when using `useDragControls`.

**Comment by c-ehrlich** [comment]
> I had a brief look into this and so far I think this is happening specifically when using `useDragControls`.

I'm also experiencing this bug in a project since upgrading to React 18, and agree with your conclusion - the issue appears only when using `useDragControls`.

**Comment by 19ozman** [comment]
CKrook have you seen this?

**Comment by ckrook** [comment]
@19ozman  Just saw this during our daily standup. Are there any solutions in sight?

**Comment by 19ozman** [comment]
@ckrook did you also try the Magnum?

**Comment by Systemcluster** [comment]
Note that this only appears to be the case when StrictMode is used and in development mode. This does not seem to affect production builds.

**Comment by 19ozman** [comment]
Cool! It's working now!

**Comment by maltesa** [comment]
Also happens without dragControls (only in strict-mode during dev):
https://codesandbox.io/s/framermotionbugreport-forked-7fwnrj?file=/src/Item.tsx

**Comment by mtysor** [comment]
> Also happens without dragControls (only in strict-mode during dev):
> https://codesandbox.io/s/framermotionbugreport-forked-7fwnrj?file=/src/Item.tsx
This looks to be related to [strict effects](https://github.com/reactwg/react-18/discussions/19) which double-invokes  useEffect. Unfortunately I suspect this affects several packages. Good news is this will still work on prod, and will work locally by disabling StrictMode

**Comment by heymartinadams** [comment]
An easy way to not use `useDragControls` and therefore sidestep this bug for now is to do the following:

```js
const [items, setItems] = useState([])
const [draggable, setDraggable] = useState(false)

<Reorder.Group axis='y' onReorder={setItems} values={items}>
  <Reorder.Item
    dragListener={draggable}
    value={item}
  >
    <div
      onMouseEnter={() => setDraggable(true)}
      onMouseLeave={() => setDraggable(false)}
      onTouchStart={() => setDraggable(true)}
      onTouchEnd={() => setDraggable(false)}
    >
      <ReorderIcon />
    </div>

    {item}
  </Reorder.Item>
</Reorder.Group>
```

**Comment by minlare** [comment]
_For any Next.js users - I had this issue on a Next.js project as `reactStrictMode` is enabled by default in `next.config.js`._
