### ISSUE TITLE
[QUESTION] What's the best approach for animating height with a conditional and AnimatePresence 

### ISSUE THREAD

**Issue by ryanto** [framer/motion#1519]
I have a card component who's content changes and I'd like to animate the height as new content comes in an out of the card. I'm not sure how to go about thinking about this. 

In this example, I'd like to smoothly animate the height as `isActive` is toggled.

```jsx
<AnimatePresence initial={false} exitBeforeEnter>
  {isActive ? (
    <motion.div
      key="intro"
      initial="hiding"
      animate="showing"
      exit="hiding"
      variants={{
        hiding: {
          opacity: 0,
        },
        showing: {
          opacity: 1,
        },
      }}
    >
      <p>
        This card has a lot of text in it, but when you toggle it the new
        content will be much smaller.
      </p>
      <p>
        The height will jump when the new text is rendered.
      </p>
    </motion.div>
  ) : (
    <motion.div
      key="thankYou"
      initial="hiding"
      animate="showing"
      exit="hiding"
      variants={{
        hiding: {
          opacity: 0,
        },
        showing: {
          opacity: 1,
        },
      }}
    >
      Ok!
    </motion.div>
  )}
</AnimatePresence>
```

I made a code sandbox here that shows the card's height jumping: https://codesandbox.io/s/github/ryanto/animated-height

I also included a component in the sandbox that uses a ref to remember a height value. It will animate to and from that height value as `isActive` is toggled. 

My question is: Is using a ref to track the height for animation the best approach to solving this sort of problem?

**Comment by ryanto** [comment]
Ugh, I'm sorry I'm not sure why this got the bug label. This was meant to be question.

Sorry about that!

**Comment by mattgperry** [comment]
Yeah this is fine I think. I don't think we already support `"auto"` -> `"auto"` animations. You should set `height` in state though rather than a ref as you can't read mutable state within the body of a React render.

**Comment by ryanto** [comment]
Ya, `auto` -> `auto` didn't work. 

Good catch on state, I'll update that.

Thanks for the fast reply, appreciate it.
