### ISSUE TITLE
[Question] How to cancel an animation? (Not just stop it)

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [framer/motion#1523]
With controls you can stop an animation (`controls.stop()`), which actually just pauses it. 

How can you cancel an already running animation that has been started with AnimationControls? I.e. cancel the animation so that you can issue a new one right away using AnimationControls.

**Comment by mattgperry** [comment]
If by cancel you mean stop and unset the current value to its origin, currently the only way to do that is 

```
controls.stop()
controls.set({ x: 0 })
```
