### ISSUE TITLE
[BUG] Can't import the named export 'Children' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by Doughp** [framer/motion#1525]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
./node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available)

Give a clear and concise description of what the bug is.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

**4. Steps to reproduce**
Run npm install framer-motion
import { motion } from "framer-motion"
run npm start

**5. Expected behavior**

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

**7. Environment details**

If applicable, let us know which OS, browser, browser version etc you're using.

### Type error with `AnimateSharedLayout`

`AnimateSharedLayout` was deprecated in 5.0. Refer to the [upgrade guide](https://www.framer.com/docs/guide-upgrade/##shared-layout-animations) for instructions on how to remove.

### Preact isn't working

Framer Motion isn't compatible with Preact. 

### `AnimatePresence` isn't working

Have all of its immediate children got a unique `key` prop that **remains the same for that component every render**?

```jsx
// Bad: The index could be given to a different component if the order of items changes
<AnimatePresence>
  {items.map((item, index) => <Component key={index} />)}
</AnimatePresence>
```

```jsx 
// Good: The item ID is unique to each component
<AnimatePresence>
  {items.map((item, index) => <Component key={item.id} />)}
</AnimatePresence>
```

Is the `AnimatePresence` correctly outside of the controlling conditional? `AnimatePresence` must be rendered whenever you expect an `exit` animation to run - it can't do so if it's unmounted!

```jsx
// Bad: AnimatePresence is unmounted - exit animations won't run
{isVisible && (
  <AnimatePresence>
    <Component />
  </AnimatePresence>
)}
```

```jsx
// Good: Only the children are unmounted - exit animations will run
<AnimatePresence>
  {isVisible && <Component />}
</AnimatePresence>
```

**Comment by Doughp** [comment]
Fixed this by changing import to " import {AnimatePresence, motion} from "framer-motion/dist/framer-motion"; "

**Comment by destefanis** [comment]
Thanks for posting this fix! This was completely breaking my ability to upgrade to 6.3.0

**Comment by richard-lopes-ifood** [comment]
> Can't import the named export 'Children' from **non EcmaScript module** (only default export is available)

That `Children` refers to the module exported by `react`. Could it related to how `create-react-app` builds the app?

**Comment by mortoni** [comment]
When I use `framer-motion/dist/framer-motion` I get typescript errors ...

**Comment by Vasu-Garg-Noovosoft** [comment]
While using `framer-motion/dist/framer-motion` I am getting TS error: `Could not find a declaration file for module 'framer-motion/dist/framer-motion'.` and when I try to install types by `npm install @types/framer-motion` getting this -> `npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fframer-motion - Not found`

**Comment by bbovenzi** [comment]
I was having this issue (and the typescript issue with using the dist file) in webpack v4, but upgrading webpack to v5 fixed everything.

**Comment by yerraez** [comment]
When I used -> "import {AnimatePresence, motion} from "framer-motion/dist/framer-motion" .... I solved the problem of Animate, but I got other errors with Reat import, I fixed it putting -> "import React from 'react'" in all the components jsx files

**Comment by richard-lopes-ifood** [comment]
> I solved the problem of Animate, but I got other errors with Reat import, I fixed it putting -> "import React from 'react'" in all the components jsx files

How did you solve?

**Comment by yerraez** [comment]
> > I solved the problem of Animate, but I got other errors with Reat import, I fixed it putting -> "import React from 'react'" in all the components jsx files
> 
> @yerraez How did you solve the first problem?

I had this error "**./node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available)**"

to solve this error I replace this "**import {motion, AnimatePresence} from 'framer-motion'**" for this "**import {AnimatePresence, motion} from "framer-motion/dist/framer-motion"**"

**Comment by fabdul88** [comment]
I initially had this issue and it was fixed using the solution provided in this thread using:

 **import {AnimatePresence} from "framer-motion/dist/framer-motion";**

my app is a `create-react-app`

## Another solution that worked for me

I stumbled across another solution that worked for me, that doesn't require you to add **/dist/framer-motion** to the end of your import. This is when I updated `react-scripts` from `4.0.0` to `5.0.1`  for improved compatibility with React 18.

Refer to this changelog on how to update react-scripts https://github.com/facebook/create-react-app/blob/main/CHANGELOG.md

part of my package.json before:
```json
dependencies:{
    "framer-motion": "^6.4.1",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.0",
}
```

part of my package.json after updating react-scripts:
```json
dependencies:{
    "framer-motion": "^6.4.1",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "5.0.1",
}
```

After updating `react-scripts`, I deleted `node_modules` and `package-lock.json`. After that, `npm i` to install all dependencies again.

I then got this error:

**ERROR in ./src/Components/ComponentName/Component.jsx 11:0-89**

**Module not found: Error: Package path ./dist/framer-motion is not exported from package /Users/username/projectpath/projectname/node_modules/framer-motion (see exports field in /Users/username/projectpath/projectname/node_modules/framer-motion/package.json)**

This is where I removed **/dist/framer-motion** from the end of the import, and it worked for me.

**Comment by AugustoDiaz-Dev** [comment]
./node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available) 

I am getting that error and also some problems with the import of React. 

I finished a project, made a copy and ran npm install to get it working.

**Comment by JANDA-Developers** [comment]
Please fix this i need typescript support.

**Comment by adenisovgit** [comment]
+1

**Comment by ricardodalarme** [comment]
+1

**Comment by ricardodalarme** [comment]
+1

**Comment by Htet-Wai-Yan** [comment]
> I initially had this issue and it was fixed using the solution provided in this thread using:
> 
> **import {AnimatePresence} from "framer-motion/dist/framer-motion";**
> 
> my app is a `create-react-app`
> 
> ## Another solution that worked for me
> I stumbled across another solution that worked for me, that doesn't require you to add **/dist/framer-motion** to the end of your import. This is when I updated `react-scripts` from `4.0.0` to `5.0.1` for improved compatibility with React 18.
> 
> Refer to this changelog on how to update react-scripts https://github.com/facebook/create-react-app/blob/main/CHANGELOG.md
> 
> part of my package.json before:
> 
> ```json
> dependencies:{
>     "framer-motion": "^6.4.1",
>     "react": "^18.0.0",
>     "react-dom": "^18.0.0",
>     "react-router": "^5.2.0",
>     "react-router-dom": "^5.2.0",
>     "react-scripts": "4.0.0",
> }
> ```
> 
> part of my package.json after updating react-scripts:
> 
> ```json
> dependencies:{
>     "framer-motion": "^6.4.1",
>     "react": "^18.0.0",
>     "react-dom": "^18.0.0",
>     "react-router": "^5.2.0",
>     "react-router-dom": "^5.2.0",
>     "react-scripts": "5.0.1",
> }
> ```
> 
> After updating `react-scripts`, I deleted `node_modules` and `package-lock.json`. After that, `npm i` to install all dependencies again.
> 
> I then got this error:
> 
> **ERROR in ./src/Components/ComponentName/Component.jsx 11:0-89**
> 
> **Module not found: Error: Package path ./dist/framer-motion is not exported from package /Users/username/projectpath/projectname/node_modules/framer-motion (see exports field in /Users/username/projectpath/projectname/node_modules/framer-motion/package.json)**
> 
> This is where I removed **/dist/framer-motion** from the end of the import, and it worked for me.

The 2nd solution works for me. Thank you !

**Comment by Divuzki** [comment]
> framer-motion/dist/framer-motion

All you need to do is update your `packages.json` file and delete the `node_modules` folder and the `lock` file then run `npm install` or `yarn install` to install all the packages again **OR** you can just delete only the files related to `framer-motion` and remove it from your `packages.json` file then install `framer-motion` again.
```javascript
   //this is how you import from `framer-motion`
   import { AnimatePresence, motion } from "framer-motion" // not "framer-motion/dist/framer-motion"
```
~ I hope this helped (。_。)

**Comment by acnologia** [comment]
@Divuzki how do you update packages.json? i thought it would be automatic when I delete node_modules, but apparently not.

**Comment by luisFebro** [comment]
> I initially had this issue and it was fixed using the solution provided in this thread using:
> 
> **import {AnimatePresence} from "framer-motion/dist/framer-motion";**
> 
> my app is a `create-react-app`
> 
> ## Another solution that worked for me
> I stumbled across another solution that worked for me, that doesn't require you to add **/dist/framer-motion** to the end of your import. This is when I updated `react-scripts` from `4.0.0` to `5.0.1` for improved compatibility with React 18.
> 
> Refer to this changelog on how to update react-scripts https://github.com/facebook/create-react-app/blob/main/CHANGELOG.md
> 
> part of my package.json before:
> 
> ```json
> dependencies:{
>     "framer-motion": "^6.4.1",
>     "react": "^18.0.0",
>     "react-dom": "^18.0.0",
>     "react-router": "^5.2.0",
>     "react-router-dom": "^5.2.0",
>     "react-scripts": "4.0.0",
> }
> ```
> 
> part of my package.json after updating react-scripts:
> 
> ```json
> dependencies:{
>     "framer-motion": "^6.4.1",
>     "react": "^18.0.0",
>     "react-dom": "^18.0.0",
>     "react-router": "^5.2.0",
>     "react-router-dom": "^5.2.0",
>     "react-scripts": "5.0.1",
> }
> ```
> 
> After updating `react-scripts`, I deleted `node_modules` and `package-lock.json`. After that, `npm i` to install all dependencies again.
> 
> I then got this error:
> 
> **ERROR in ./src/Components/ComponentName/Component.jsx 11:0-89**
> 
> **Module not found: Error: Package path ./dist/framer-motion is not exported from package /Users/username/projectpath/projectname/node_modules/framer-motion (see exports field in /Users/username/projectpath/projectname/node_modules/framer-motion/package.json)**
> 
> This is where I removed **/dist/framer-motion** from the end of the import, and it worked for me.

Updating the react-scripts was the solution to this inner node_modules error. Thanks!

**Comment by richard-lopes-ifood** [comment]
@fabdul88  What does the new `react-scripts` version implement that works for this lib?

**Comment by michaelignat** [comment]
If you can't upgrade `react-scripts` to version 5, another workaround that worked for me is from [this answer here](https://stackoverflow.com/a/71458141):

1. Create a `framer-motion-types.d.ts` file in your src directory
2. Add the following code into the file created above:
```ts
declare module "framer-motion/dist/framer-motion" {
	export * from "framer-motion";
}
```
3. You can now use framer motion with the following import while keeping types working:
`import { AnimatePresence, motion } from "framer-motion/dist/framer-motion";`

**Comment by ronald-cognite** [comment]
Still experiencing this issue. Any updates?

**Comment by Naeem775** [comment]
I tried all above solutions, nothing is working for me, i am using it in next js project.
![image](https://user-images.githubusercontent.com/32215735/204143153-59791b0f-ad4f-49ce-be23-5770cb418181.png)

**Comment by priyanshutr** [comment]
Downgrading "framer-motion"  to ^4.1.13 work for me

**Comment by p0cket** [comment]
I've tried a lot of things, but the only thing that has worked so far is my project downgrading to framer-motion ^4.1.13. My project was a created with Codesandbox's React Template. I can't imagine downgrading is the optimal solution. Any thoughts on this?

**Comment by danielleo2** [comment]
Hello There, I'm gonna share my understanding of the issue: The problem it's that the newest Framer-Motion uses .mjs files, and their syntax its incompatible with the jsx files or js files we are using for our components. So, by downgrading we fix this issue because older versions of Framer-Motion had a native js file. But the "optimal" solution would be; changing the extension of our components so they all share the same syntax "mjs". In my case I just deleted Framer-motion and looked up for other native packages that would acomplish the same results

**Comment by BlackHatDevX** [comment]
This is a step-by-step guide to fix the error "Can't import the named export 'Children' from non EcmaScript module (only default export is available)" which should work for most users with latest framer-motion  version.

**Step 1: Update Dependencies**
The first step is to update the versions of the following dependencies in your package.json file:
`"dependencies": {
    "framer-motion": "^10.0.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-scripts": "5.0.1"
},`

Again make sure all the versions are the same.

**Step 2: Delete node_modules and Lock File**
After updating the dependencies, delete the node_modules folder and the lock file. You can do this by running the following command in your terminal:
`rm -rf node_modules
rm yarn.lock // for yarn users
rm package-lock.json // for npm users
`

**Step 3: Install Dependencies**
Now run the following command in your terminal to install all the dependencies again:
`npm install // for npm users
yarn install // for yarn users
`

**Step 4: Start Server**
To import framer-motion use:
`import {AnimatePresence, motion} from "framer-motion";`
After installing the dependencies, start your server and the error should be fixed.

This guide has been tested on a sandbox environment and should work for most users.

**Comment by claptimes5** [comment]
(Using Typescript) - In addition to upgrading `react-scripts` to v5, I also found I had `react-app-rewired` which I no longer used. I removed that package, deleted the node modules folder, installed the packages and then everything worked well.

**Comment by thesmashten** [comment]
Literally have no clue how to fix this and it's ridiculous lol. Can people stop gatekeeping and just tell me how tf to add framer motion... I get the error: 
/node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available)

**Comment by thesmashten** [comment]
It's unbelievable how restrictive and difficult it is to add framer motion/ spring react. We need better animation libraries out there!!

**Comment by mahmutisci** [comment]
I solved this problem with a webpack rule, I explained at here;
https://github.com/motiondivision/motion/issues/2627#issuecomment-2734904615
