### ISSUE TITLE
[Feature] type="switch/crossfade" configurable

### ISSUE THREAD

**Issue by singlexyz** [framer/motion#1528]
Automatic judgment using `switch` or `crossfade` in layout animation sometimes does not get the desired effect.
It's fine in most cases, but if the new component has a background color(with padding), the child elements will flicker because of the `crossfade` effect.

I made a demo.
https://codesandbox.io/s/eloquent-zhukovsky-b09jbf?file=/src/App.js

**Comment by mattgperry** [comment]
To set expectations this is probably a `wontfix` unless we find a need for it in Framer.
