### ISSUE TITLE
[BUG] Not able to debug in Chrome Animation Inspector

### ISSUE THREAD

**Issue by M1chaelChen** [framer/motion#1529]
**1. Describe the bug**
[Chrome Animation Inspector](https://developer.chrome.com/docs/devtools/css/animations/) is not able to catch any framer motion animation. Is there a way to debug animations?

**2. Expected behavior**
Animations should be caught by Animation Inspector.

**3. Video or screenshots**
<img width="642" alt="Screen Shot 2022-04-29 at 11 48 01 AM" src="https://user-images.githubusercontent.com/19735641/166007521-a31340e6-0a73-4518-a7d9-ff2a8f7814af.png">

**4. Environment details**
Chrome, Firefox

**Comment by mattgperry** [comment]
Ah no sorry this is a limitation of Chrome animation inspector. Without them opening an API to register JS animations there’s no way to
Support this.
