### ISSUE TITLE
[BUG] dragging side effect in React v18 with StrictMode

### ISSUE THREAD

**Issue by AndrejGajdos** [framer/motion#1533]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

Dragging doesn't work well in React v18 with StrictMode. It creates a strange jumping effect.

The issue is not visible in React v17 or React v18 without StrictMode.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[codesandbox](https://codesandbox.io/s/framer-motion-5-drag-to-reorder-lists-forked-3op3ve?file=/src/index.tsx)

**4. Steps to reproduce**

1. Try to drag items in codesandbox

**5. Expected behavior**

Dragging should work without a jumping effect.

**6. Video or screenshots**

https://user-images.githubusercontent.com/1593758/167120917-4cb3e8a6-eb42-45ba-b3f1-f9e351855e1e.mov

**Comment by mattgperry** [comment]
Seems to be fixed since
