### ISSUE TITLE
AnimatePresence doesn't catch up with multiple deletes in a row

### ISSUE THREAD

**Issue by XiupengMa** [framer/motion#1534]
I have a list of items that each of them has an exit animation. I have another button that can randomly delete an item from the list. if I quickly click the button for multiple times (i.e. faster than the animation duration), I saw the deleted items are no longer visible but their original space was still taken.

Demo: https://codesandbox.io/s/adoring-rubin-hsxcfh?file=/src/App.ts

see box `0` and `7` are removed but their space is still taken:

<img width="551" alt="Screen Shot 2022-05-13 at 10 03 23 PM" src="https://user-images.githubusercontent.com/4919529/168411495-e40a4ca3-9d1b-4545-a6fa-39ee9f83f69f.png">

**Comment by utileetdulce** [comment]
This seems to be related to 
[907](https://github.com/framer/motion/issues/907)
[1439](https://github.com/framer/motion/issues/1439)

**Comment by mattgperry** [comment]
This has been fixed since
