### ISSUE TITLE
[BUG] Scroll jacking in Safari browser

### ISSUE THREAD

**Issue by AndrejGajdos** [framer/motion#1537]
**2. Describe the bug**

I have a layout where inner element's position is synced with scrollbar position. I implemented it by using [useElementScroll](https://www.framer.com/docs/motionvalue/##useelementscroll) hook. The issue is that there is scroll jacking effect in Safari browser, but it's not visible in other browsers.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[codesandbox](https://codesandbox.io/s/silly-wing-sc43cu)

**4. Steps to reproduce**

1. Expand card
2. Scroll

**5. Expected behavior**

Scrolling with expanded card should be without scroll jacking in safari browser.

**6. Video or screenshots**

![scroll_jacking](https://user-images.githubusercontent.com/1593758/169663667-21a583a3-c89b-4fe7-9d15-ec1f363679ae.gif)

**7. Environment details**

OSX, Safari Version 15.5

**Comment by mattgperry** [comment]
This isn't "scrolljacking" per se but it's not a nice effect. This sort of thing should be achieved with `position: sticky` because Safari is painting the scroll effect with a higher priority than style updates.
