### ISSUE TITLE
[BUG] Scroll jacking issue with framer motion and FloatingPortal 

### ISSUE THREAD

**Issue by AndrejGajdos** [framer/motion#1538]
**2. Describe the bug**

I have a layout where inner element's position is synced with scrollbar position. I implemented it by using `useElementScroll` hook. I also use [FloatingPortal](https://floating-ui.com/docs/floatingportal) to render element's details in a portal. The issue is that scroll jacking occurs if `FloatingPortal` is used.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Here is [codesandbox](https://codesandbox.io/s/silly-wing-sc43cu) where scroll jacking occurs.

Here is [codesandbox](https://codesandbox.io/s/nifty-worker-s3nrwm) where scroll jacking doesn't occur because `FloatingPortal` is commented in `SecondLayerPopover`.

**4. Steps to reproduce**

1. Click on `show more` to expand the card and scroll.
2. Click on `show more` to collapse the expanded card.
3. Click on `t` button to open temporary card
4. Click on `t` button to hide temporary card
5. Click on `show more` to expand the card and scroll.

**5. Expected behavior**

Scroll jacking shouldn't occur.

**6. Video or screenshots**

https://user-images.githubusercontent.com/1593758/169664350-06866c6a-98de-4395-be9f-944860066d63.mov

**Comment by mattgperry** [comment]
I don't think this I'm not familiar with FloatingPanel but it's changing `top` rather than using `position: sticky` so it is bound to fall out of sync with scroll. I don't think this is a bug in Framer Motion.
