### ISSUE TITLE
[BUG] Weird scroll into view behavior with height: 'auto' motion

### ISSUE THREAD

**Issue by mattp0123** [framer/motion#1540]
### CodeSandbox
This is a forked accordion example from official one. The difference between the original one is that more accordions are added.

https://codesandbox.io/s/framer-motion-accordion-forked-uq6e9o

### Steps to reproduce
Expand the first accordion and scroll to the bottom of the page, then expand the last accordion.
After these steps, you will notice that the page scroll to the top (which the first accordion is at).

### Expected behavior
The page should not scroll to the top.

**Comment by youngkyo0504** [comment]
That problem is associated with only CSS. It looks like scrolling. but actually just container height changed.
You can solve the problem simply by setting the height on the elment. 

`styles.css`
.example-container {
  width: 320px;
  height: 200vh;
  padding: 20px;
}

```css

```

**Comment by mattp0123** [comment]
@youngkyo0504 What if I want the container's height to be auto (depends on children's height)

**Comment by mattgperry** [comment]
Playing around with it, the snapping only happens if the viewport is larger than the height of all the items when they're all closed and smaller when one is open. This is because to animate to auto we do some measurements that might have all elements in the collapsed state for long enough that the scroll resets. It might be possible to store and restore the scroll position during this operation, I'll take a look

**Comment by mattp0123** [comment]
This is my workaround to auto height (using the custom prop of motion element):
```typescript=
function AnimatedBox(props: { children: ReactNode }) {
  const ref = useRef<HTMLDivElement>(null);
  const [height, setHeight] = useState(0);
  useEffect(() => setHeight(ref.current!.scrollHeight), []);
  return (
    <Box
      ref={ref}
      initial={BoxVariant.Collapse}
      animate={BoxVariant.Open}
      exit={BoxVariant.Collapse}
      custom={height}
      variants={{
        [DetailBoxVariant.Open]: (height: number) => ({ height }),
        [DetailBoxVariant.Collapse]: { height: 0 },
      }}
    >
      {props.children}
    </Box>
  );
}

function App() {
  const [isBoxOpen, setIsBoxOpen] = useState(false);
  return (
    <AnimatePresence initial={false}>
      {isBoxOpen && (
        <AnimatedBox>
          <div>Text</div>
        </AnimatedBox>
      )}
    </AnimatePresence>
  );
}
```
