### ISSUE TITLE
drag gesture to drag along the Y axis

### ISSUE THREAD

**Issue by xnslx** [framer/motion#1545]
I am trying to use the drag gesture to drag up/down the product information card. As you can see in the demo when you drag up, there is quite a big margin on the bottom which makes sense since I have the `dragConstraints={{ top: -500, bottom: 0 }}` Is there any way to fix this issue? Many thanks. 

![ezgif com-gif-maker (27)](https://user-images.githubusercontent.com/51500554/170130311-89f0bd55-2735-4abf-855c-3c354350b8fd.gif)

**Comment by mattgperry** [comment]
Hi there - can you please reopen with a codesandbox example? Thanks!
