### ISSUE TITLE
whileInView not working while using X position

### ISSUE THREAD

**Issue by devshahrukhkhan** [framer/motion#1546]
I am trying to use whileInView in order to animate some elements on scroll in react.

here is the codesandbox link: [https://bz6msx.csb.app/](https://bz6msx.csb.app/)

if you go and check the code then you see that while using whileInView it does not trigger the animation.

is there anything am I missing?

Thanks

**Comment by youngkyo0504** [comment]
That is not bug. `whileInView` property is associated with Intersection Observer API. In your CodeSandBox , h1 tag has initial state with `x: 100vh`. h1 tag not visible in viewport. only visible element activate whileInView animation. 

There are some tricks. 

1. set 100vw to 95vw. Then element is visible.  
```js
     <div className="App">
      <motion.h1
        initial={{
          x: "95vw" // set 100vw to 95vw
        }}
        // This is not working
        whileInView={{
          x: 0,
          transition: {
            duration: 1,
            type: "spring",
            stiffness: 50
          }
        }}
      >
        Motion
      </motion.h1>
    </div>
```

2. Set WhileInView Property parent tag. 
```js
import "./styles.css";
import { motion } from "framer-motion";
import { useState } from "react";
export default function App() {
  const [isInView, setIsInView] = useState(false);
  return (
    <motion.div
      whileInView={() => {
        // when element in viewport , set IsInView true!
        setIsInView(true);
        return {};
      }}
      className="App"
    >
      <motion.h1
        initial={{
          x: "100vw"
        }}
        // This is working
        animate={
          isInView && {
          x: 0,
          transition: {
            duration: 1,
            type: "spring",
            stiffness: 50
          }
        }}
      >
        Motion
      </motion.h1>
    </motion.div>
  );
}

```

**Comment by devshahrukhkhan** [comment]
@youngkyo0504 That is amazing thanks for the reply :)

**Comment by jdnichollsc** [comment]
@youngkyo0504 hey mate, do you know if we can update the state when the component is not in view?

Thanks for your help!

**Comment by Armadillidiid** [comment]
> That is not bug. `whileInView` property is associated with Intersection Observer API. In your CodeSandBox , h1 tag has initial state with `x: 100vh`. h1 tag not visible in viewport. only visible element activate whileInView animation.
> 
> There are some tricks.
> 
>     1. set 100vw to 95vw. Then element is visible.
> 
> 
> ```js
>      <div className="App">
>       <motion.h1
>         initial={{
>           x: "95vw" // set 100vw to 95vw
>         }}
>         // This is not working
>         whileInView={{
>           x: 0,
>           transition: {
>             duration: 1,
>             type: "spring",
>             stiffness: 50
>           }
>         }}
>       >
>         Motion
>       </motion.h1>
>     </div>
> ```
> 
>     2. Set WhileInView Property parent tag.
> 
> 
> ```js
> import "./styles.css";
> import { motion } from "framer-motion";
> import { useState } from "react";
> export default function App() {
>   const [isInView, setIsInView] = useState(false);
>   return (
>     <motion.div
>       whileInView={() => {
>         // when element in viewport , set IsInView true!
>         setIsInView(true);
>         return {};
>       }}
>       className="App"
>     >
>       <motion.h1
>         initial={{
>           x: "100vw"
>         }}
>         // This is working
>         animate={
>           isInView && {
>           x: 0,
>           transition: {
>             duration: 1,
>             type: "spring",
>             stiffness: 50
>           }
>         }}
>       >
>         Motion
>       </motion.h1>
>     </motion.div>
>   );
> }
> ```

How can I incorporate the `amount` parameter into the mix? I would like my element to transition when 50% of its body is in view. However, this seems challenging due to the element's position on the x-axis.
