### ISSUE TITLE
[BUG] Examples link in documentation broken since new site

### ISSUE THREAD

**Issue by IngoValente** [framer/motion#1548]
I can't seem to get to the examples page anymore since frame introduced its new website.

**Steps to reproduce the behavior:**
1. Go to https://www.framer.com/docs/
2. Click on 'Examples' in the menu on the left
3. Page redirects to framer gallery instead of examples

**Expected behavior**

Show the examples page, the one that was live before the new website design.

**Comment by mattgperry** [comment]
Thanks for the report, this is fixed now!
