### ISSUE TITLE
[FEATURE] An update to the documentation on which implementation of onChange is valid/correct. 

### ISSUE THREAD

**Issue by kiddio** [framer/motion#1551]
**Is your feature request related to a problem? Please describe.**
The documentation on the framer website states that motionValue.onChange returns an unsubscribe function. Yet the JSDoc example code states that you should return a unsubscribe function explicitly so I think it needs to be updated to state clearly what implementation is correct or whether both is valid and why?

**Describe the solution you'd like**
An update to the documentation to state which implementation of onChange is correct. 

**Describe alternatives you've considered**
N/A. 

**Additional context**
JSDoc example code:
![image](https://user-images.githubusercontent.com/25619935/170674896-48694859-b4ed-4a19-b110-2c496f7a0b45.png)

Framer Motion documentation:
![image](https://user-images.githubusercontent.com/25619935/170674944-31887cc0-f10b-4676-a875-3841ac334e92.png)

### Does Framer Motion support Preact?
It might work with Preact, but we don't explicitly support it, so if it does currently work you'd be using it at your own risk.

**Comment by mattgperry** [comment]
The docs show two unsubscribers being returned from two calls to onChange and how that might be handled.
