### ISSUE TITLE
[BUG] Layout animation works incorrectly if item size was changed

### ISSUE THREAD

**Issue by gercog1** [framer/motion#1560]
1. Bug description

   Layout animation works incorrectly if the item size was changed. But it is working if none of the items is expanded. 
   Moreover, it works on the second re-render even though the first one was buggy.

2. CodeSandbox reproduction 

   [https://codesandbox.io/s/jolly-monad-ilen07?file=/src/App.js](https://codesandbox.io/s/jolly-monad-ilen07?file=/src/App.js)
   
3. Steps to reproduce
    
    Just press the toggle button to expand/collapse items :) 

4. Expected behaviour

    Layout animation works even if item size was increased/decreased.

5. Video

https://user-images.githubusercontent.com/22454747/171388061-4ec36c93-750c-48c1-9fed-f58622fb2749.mov

**Comment by mattgperry** [comment]
In this example state changes are localised to the items. Use `LayoutGroup` to synchronise throughout all items:

https://codesandbox.io/s/compassionate-wind-mipxxz?file=/src/App.js

To fix the distortion you can wrap the header with a `layout` prop and additionally wrap the blue box contents with `layout="position"`

**Comment by gercog1** [comment]
Wow, that's an easy fix. Thanks for the quick response and great library @mattgperry 🥇
