### ISSUE TITLE
[BUG] typo in framer docs

### ISSUE THREAD

**Issue by tahseenio** [framer/motion#1564]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
Typo in close-source docs website. 
So the issue is a small typo in https://www.framer.com/docs/examples/ , 'Shared layout animations'. and https://www.framer.com/docs/animation/ , in the  'Shared layout animations'. The sample code is not the same.

Give a clear and concise description of what the bug is.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
Unable to due to closed-source 

A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

**4. Steps to reproduce**

1. Go to the Shared layout animations at https://www.framer.com/docs/examples/ . You will see the sample code is `isSelected ? <motion.div layoutId="underline" /> : null`
1. Go to the Shared layout animations at https://www.framer.com/docs/animation/ . You will see the sample code is `isSelected && <motion.div layoutId="underline" /> : null`

**5. Expected behavior**
It is expected the ternary statement looks like the below.
1. `isSelected && <motion.div layoutId="underline" />`
 or
2.  `isSelected ? <motion.div layoutId="underline" /> : null`

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

**7. Environment details**

If applicable, let us know which OS, browser, browser version etc you're using.

**Comment by tahseenio** [comment]
I have sent this information to Palmaswell#6348 ( framer-staff ) in the Framer discord who will File a report internally and get this fixed.

**Comment by mattgperry** [comment]
A fix for this went out yesterday, thanks!
