### ISSUE TITLE
[BUG] Exit animation doesn't work properly

### ISSUE THREAD

**Issue by nic-brown** [framer/motion#1575]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
Trying to implement page transition effects, but encountered a small problem.
For some reason exit animation doesn't work  when I go from */work/the-athlete to the other pages

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[https://codesandbox.io/s/jovial-shaw-sh2e21]( https://codesandbox.io/s/jovial-shaw-sh2e21)

**4. Steps to reproduce**

Please see the screenshots below

**5. Expected behavior**

Exit animation on route change

**6. Video or screenshots**
[Screenshot 1]( https://i.stack.imgur.com/yGrlN.png)
[Screenshot 2](https://i.stack.imgur.com/RX0ob.jpg)
[Screenshot 3](https://imgur.com/a/25qRxXj)

**Comment by nic-brown** [comment]
I'm completely new to the whole  react thing, so I just refused  to give up and tried to  solve the issue by trying different things (most  of which didn't even make any sense)
My patience was running out and a thought came to mind: *What if I move my states up a bit (to the App.js) and pass it down in props....
And whoala! It worked like a charm😅

**Comment by mattgperry** [comment]
Glad you got it sorted! Closing as this looks like the correct setup in the codesandbox
