### ISSUE TITLE
[BUG] LayoutId animation positioned incorrectly after page scroll

### ISSUE THREAD

**Issue by linchengzzz** [framer/motion#1580]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

In nextjs the current page and the page after the switch use layoutid animations to position errors after the page has scrolled

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

https://codesandbox.io/s/framer-demo-lu1hg0

**4. Steps to reproduce**

1. Go to home page
2. Click on `click me` to demo page
3. Then click on the box to return to the previous page 
4. Scroll and click again `click me`, position will not follow scrolling

**5. Expected behavior**

layoutId animation to follow the page scroll position and then zoom in

**6. Video or screenshots**

https://user-images.githubusercontent.com/24381509/173506451-740fe83d-6ad0-45d3-8799-6e805faa3bec.mov

**7. Environment details**

- Next.js: 12.1.6
- React: 18.1
- Framer-motion: 6.3.11

**Comment by ivanburlakov** [comment]
I have the same setup with vertical list and opening cards. Plus another problem for me is that sometimes after you scroll and open the card - the div that is supposed to hold it's space while it was in `position:fixed` seems to lose it's height (or shift). So after you close the card it follows by a weird animation of all the cards moving, while they should stay in one place.

**Comment by gijsroge** [comment]
Using Remix, have the same issue. Not much more I can contribute :/

**Comment by SweetSquid** [comment]
Do you have any workaround for this issue?

**Comment by Blechkelle** [comment]
I ran into the same issue. I think it has something to do with the router scrolling back to top when changing the location. u can see this behavior in your example too.

**Comment by bacvietswiss** [comment]
I'm facing the same problem with NextJS 13 app directory, is there any update or work around for this?

**Comment by mattgperry** [comment]
The page itself is scrolling and the box is animating correctly from its previous position on the page (slow down the animation as evidence)

**Comment by jrolfs** [comment]
I ran into this sort of thing when attempting to animate a `layoutId` component that's scrolled way down in a list into a `position: fixed` fullscreen view and worked around it by preserving the `body` height and scroll offset on the fullscreen route.

**Comment by pawelos231** [comment]
Does anyone have a working solution for this?

**Comment by alexsafayan** [comment]
@linchengzzz @pawelos231 were you able to find a solution?
