### ISSUE TITLE
[BUG] Touch event on mobile phones trigger drag event

### ISSUE THREAD

**Issue by rohit1101** [framer/motion#1582]
Describe the bug:

We have implemented our own version of card carousel for our use case at our work but we pass `drag="x"` as prop but when we touch and move the card gently vertically on y-axis (not to be confused with scrolling the page when the touch the card) we noticed that the offset as `{x: -200, y: -2000 }` when we consoled the value on `onDragEnd` handler.

This issue also exists on latest version of framer-motion v6.3.11 and we are currently using v6.3.3

CodeSandbox reproduction of the bug:

Sandbox link: https://codesandbox.io/s/little-currying-vuy602?file=/src/components/Slider.jsx&resolutionWidth=320&resolutionHeight=675

Steps to reproduce the behavior: (Please check the following steps on any ios devices => iphones and android devices):

1. Try to swipe on the card in vertical direction and notice that the next card will be rendered.
2. We do not want the next card to be render unless and until we swipe it.
3. We already set the drag to be only on x-axis
![image](https://user-images.githubusercontent.com/37110560/174046046-f7e44f57-00c3-45d0-9510-37fae2920b19.png)

Video or screenshots:

This behavior is happening on both ios and android:

https://user-images.githubusercontent.com/37110560/174053332-9efce15a-743b-46fb-9196-cf4df0739a84.mov

Environment details:

This issue is happening on safari browser on iphones and and android chrome browser.

**Comment by omattman** [comment]
+1 would love a fix for this

**Comment by marcel-d8** [comment]
+1 would love a fix for this

**Comment by mattgperry** [comment]
Feel free to reopen with working sandbox
