### ISSUE TITLE
[BUG]: Drag event not working as expected on mobile phones

### ISSUE THREAD

**Issue by rohit1101** [framer/motion#1583]
Describe the bug:

We are using `drag` event for swiping between cards in our custom slider implementation but at times when we try to swipe from the third card to the second card the drag event is not complete and we would have to swipe more than once to render the second card.

Provide a CodeSandbox reproduction of the bug:

https://codesandbox.io/s/little-currying-vuy602?file=/src/components/Slider.jsx&resolutionWidth=320&resolutionHeight=675

We have also tried to use `onPanEnd` instead of `onDragEnd` and we are still facing the error (please change to `onDragEnd` on the above codesandox on `motion.div`

Steps to reproduce:

1. Swipe to the third card
2. Then try to swipe from third card to the second card 
3. If the issue is not reproduced try swiping between second and third card multiple times.
4. See error:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37110560/174253178-8d374743-e716-485d-a43f-2d0097bd2730.png">

Expected behavior:

The swipe behavior between second and third card should similar to the swipe behavior between first and second card.

Video or screenshots:

Please notice the swipe from thrid card to second card from 0:11

https://user-images.githubusercontent.com/37110560/174251914-a90b19cf-e256-4bed-9df2-c2483bf50efb.MOV

 Environment details:
 
 This issue is happening on safari browser on iphones and and android chrome browser.

**Comment by mattgperry** [comment]
Feel free to reopen with working sandbox link
