### ISSUE TITLE
[DOCS] Sizes for `domAnimation` and `domMax` don't seem correct

### ISSUE THREAD

**Issue by dstaley** [framer/motion#1585]
The [docs](https://www.framer.com/docs/guide-reduce-bundle-size/) contain the following:

> - domAnimation: This provides support for animations, variants, exit animations, and tap/hover/focus gestures. (~13kb)
> - domMax: This provides support for all of the above, plus pan/drag gestures and layout animations. (~18kb)

However, after testing I believe the relationship in size between these two exports is not correct. In actual bundles, we're seeing increases of about 30kb when switching from `domAnimation` to `domMax` in `v6.3.11`. This is confirmed by [reproducing minimal bundles](https://replit.com/@dstaley/framer-motion-animations) that export each of these.

```
$ npx rollup@latest -c && echo 'domMax' && gzip -c output/domMax.js | wc -c && echo 'domAnimation' && gzip -c output/domAnimation.js | wc -c
npx: installed 1 in 3.409s

src/domMax → output...
created output in 7.9s

src/domAnimation → output...
created output in 5.7s
domMax
69955
domAnimation
43213
```

I'm not exactly sure how the 13 and 18kb numbers were generated, so I can't suggest the exact values that the documentation should use, but it definitely seems like the size for `domMax` should be more than just 5kb larger than `domAnimation`.

**Comment by mattgperry** [comment]
Wh

**Comment by mattgperry** [comment]
Btw if you want to see how these are calculated the `rollup.config` file is responsible for bundling
