### ISSUE TITLE
[BUG] Layout id overlaping with other components

### ISSUE THREAD

**Issue by gdlazcano** [framer/motion#1588]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

When using layout id, the first page transition works as expected but when pressed the back button the animation overlaps with the other components and the z-index, i guess, is lower. 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/bold-snow-f39mq4?file=/pages/_app.js

**4. Steps to reproduce**

**5. Expected behavior**

Both animations don't overlap with the other components, either when going to another page or coming back from another page. I think this has more to do with framer-motion than with next js tbh

**6. Video or screenshots**

https://user-images.githubusercontent.com/49376133/174870735-3e0fba3d-bac5-40db-a1da-3af9274ad919.mp4

**Comment by drager** [comment]
@gdlazcano Did you solve this? I'm experience the same issue...

**Comment by gdlazcano** [comment]
> @gdlazcano Did you solve this? I'm experience the same issue...

Yes I believe it was a thing related to the overflow and the z-index. I believe you can't have both scroll and hidden, so you must find a way of changing the overflow when initiating the animation and adding a bigger z-index on the animated element

**Comment by drager** [comment]
> > @gdlazcano Did you solve this? I'm experience the same issue...
> 
> Yes I believe it was a thing related to the overflow and the z-index. I believe you can't have both scroll and hidden, so you must find a way of changing the overflow when initiating the animation and adding a bigger z-index on the animated element

Hmm ok, thanks! I have tried tinkering around with z-index but without luck though...

**Comment by devRabbani** [comment]
Same problem

**Comment by islamBelabbes** [comment]
for anyone still having the issue here is a hacky way

```ts
export default function HomePage() {
  // 1 - Define a ref that holds a multiple elements
  const elRefs = useRef<HTMLElement[]>([]);

  const router = useRouter();
  const onRoute = (id: number) => {
    router.push(`/${id}`);
  };

  // 2 - a function to Append zIndex to each element
  const appendZIndex = (id: number, zIndex: number) => {
    const currentRef = elRefs.current[id];
    if (!currentRef) return;
    currentRef.style.zIndex = zIndex.toString();
  };

  // 3 - a function to Append ref to each element
  const appendRef = (ref: HTMLElement | null, id: number) => {
    if (!ref) return;
    elRefs.current[id] = ref;
  };
  return (
    <main className="flex min-h-screen flex-col items-center justify-center text-white">
      <ul className="grid w-full max-w-screen-lg grid-cols-3 gap-2">
        {arr.map((image, i) => (
          <motion.li
            ref={(ref) => appendRef(ref, i)} // pass ref to appendRef function
            key={i + 1}
            className={`relative aspect-video w-full rounded bg-red-200 track_${i}`}
            layoutId={`track_${i}`}
            onLayoutAnimationStart={() => appendZIndex(i, 10)} // increase zIndex when animation start
            onLayoutAnimationComplete={() => appendZIndex(i, 1)} // reset zIndex when animation complete
            onClick={() => onRoute(i)}
          >
            <Image
              src={image}
              alt="image"
              fill
              className="rounded object-cover"
            />
          </motion.li>
        ))}
      </ul>
    </main>
  );
}

`

Result : 


https://github.com/user-attachments/assets/2a10aa74-7ad7-406e-bc5a-cf62db85fefa
