### ISSUE TITLE
[BUG] Reorder trigger does not work on mobile

### ISSUE THREAD

**Issue by ArchitecTJ37** [framer/motion#1597]
**1. Read the [FAQs](#faqs) 👇**
If you need the code workground, please refer to "3." which has the link to it.

Let me give you more background here:
- The code is basically identical to the example provided in Framer Motion official doc here: [https://www.framer.com/docs/reorder/##drag-triggers](https://www.framer.com/docs/reorder/##drag-triggers)
- The only different is the Framer Motion version. Official doc uses 5+, my codesandbox uses 6+ (Which my future development will be using).
- The bug will only occur with mobile.
- I mostly done the testing on Chrome Dev Tools with device toolbar activated(I toggled the iPhone XR for testing)
- I also used a real Android device for testing, same bug happened
- ** I tried turn off strict mode on my local source code. It does not help

**2. Describe the bug**
Cannot drag to reorder on mobile.

Visually, it can be drag a little, but cannot reorder it.
It just goes back to where it was.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
The codesandbox workground: [https://codesandbox.io/s/framer-motion-5-drag-to-reorder-lists-with-drag-handle-forked-k7fed0](https://codesandbox.io/s/framer-motion-5-drag-to-reorder-lists-with-drag-handle-forked-k7fed0)

**4. Steps to reproduce**
For Chrome: Open Dev Tools with device toolbar activated(I toggled the iPhone XR for testing). Try dragging.

For real, physical Android device: Simply open the codesandbox and try dragging.

**5. Expected behavior**
Using the trigger and drag should be reorder the items. Should be the exact same result from official doc [https://www.framer.com/docs/reorder/##drag-triggers](https://www.framer.com/docs/reorder/##drag-triggers)

**6. Video or screenshots**
[https://cdn.discordapp.com/attachments/989945638823268413/989949130904305714/VID_20220625_014325.mp4](https://cdn.discordapp.com/attachments/989945638823268413/989949130904305714/VID_20220625_014325.mp4)

**7. Environment details**
Chrome (Android) - Bugged
Chrome (Ubuntu) - Bugged
Brave (Ubuntu) - Bugged
Firefox (Ubuntu) - Normal

**Comment by dorshinar** [comment]
Happens in iOS as well. I'm testing the same thing with iPhone 13 Pro on iOS 15.5 and the same thing as the video happens.

**Comment by femaury** [comment]
Happens in my app as well, very frustrating for mobile users. 
Tried using `onTouchStart` instead of `onPointerDown`, same issue.
`framer-motion: v5.3.0` & `react: v17.0.2`

**Comment by ImBaedin** [comment]
I found a workaround that I'm not particularly proud of, but that works. 

https://codesandbox.io/s/framer-motion-5-drag-to-reorder-lists-with-drag-handle-forked-fix-7bypke

Essentially, the fix relies on capturing the `touchstart` event and using `.preventDefault()` to prevent the default behavior (which I believe is the scroll.) Sadly, we can't use react's native `onTouchStart` event because we need to pass `{passive: false}` to the `addEventListener` call.

Check out the modified code sandbox for the details. In your example, I needed to forward the ref but the rest of the fix is pretty easy to understand. Could probably even pull out the whole touch listener code to a custom hook, but for my case I'm only using it in one component so I didn't bother.

Hope it helps 😊

**Comment by Garett-MacGowan** [comment]
> Happens in my app as well, very frustrating for mobile users. Tried using `onTouchStart` instead of `onPointerDown`, same issue. `framer-motion: v5.3.0` & `react: v17.0.2`
> 
> [edit]: actually using `framer-motion: v5.6.0` [edit 2]: downgrading to `framer-motion: v5.2.1` fixes the problem.

Confirmed downgrading to v5.2.1 as a temporary workaround.

**Comment by Frost7994** [comment]
Is there any other solution than downgrading? Ran into this problem while trying to create a reorderable list that overflows and came across this issue

**Comment by Garett-MacGowan** [comment]
> Is there any other solution than downgrading? Ran into this problem while trying to create a reorderable list that overflows and came across this issue

Confirmed @ImBaedin's fix works with 7.3.6

Relavent code:

```
const iRef = React.useRef<HTMLElement | null>(null);

React.useEffect(() => {
    const touchHandler: React.TouchEventHandler<HTMLElement> = (e) => e.preventDefault();

    const iTag = iRef.current;

    if (iTag) {
        //@ts-ignore
        iTag.addEventListener("touchstart", touchHandler, { passive: false });

        return () => {
            //@ts-ignore
            iTag.removeEventListener("touchstart", touchHandler, {
                passive: false
            });
        };
    }
    return;
}, [iRef]);
  
return (  
    <Reorder.Item ref={iRef} value={props.id}>
        ....
    </Reorder.Item>
)
```

**Comment by ArchitecTJ37** [comment]
Can I close this now as @ImBaedin and @Garett-MacGowan already stated the fixes.

I experienced multiple issue on the latest version and some mean-talking-attitude responses from framer Discord members.
I have already left framer motion behind a month ago.

**Comment by Frost7994** [comment]
I appreciate that @ImBaeadin solution works but like they state themselves it's a work around, in my experiences workarounds tend to end up causing some buggy behavior further down the line. I'd much rather a clear solution than trying to patch up a working one. Sorry you had to deal with that though

**Comment by Garett-MacGowan** [comment]
> I appreciate that @ImBaeadin solution works but like they state themselves it's a work around, in my experiences workarounds tend to end up causing some buggy behavior further down the line. I'd much rather a clear solution than trying to patch up a working one. Sorry you had to deal with that though

Agreed. It's probably best that this stays open so that someone can go in and fix the underlying issue. It was working in the past, so I'm sure it's fixable, hopefully without too much effort.

Perhaps the fix above is pointing to the issue.

**Comment by kashif12702** [comment]
@ImBaedin  In my case it started working in mobile but now not working in big screen . I am using next-js

**Comment by ImBaedin** [comment]
> @ImBaedin In my case it started working in mobile but now not working in big screen . I am using next-js

I don't believe I'm of any help to you in that case. That fix worked for me on mobile and desktop, also using nextjs.

**Comment by kashif12702** [comment]
@ImBaedin  which version of Farmer are you using ?

**Comment by ImBaedin** [comment]
> @ImBaedin which version of Farmer are you using ?

7.2 at the moment,

**Comment by Novo1999** [comment]
import { Reorder, useDragControls } from 'framer-motion'
import { useEffect, useRef, useState } from 'react'
import { GrDrag } from 'react-icons/gr'
import InvoicesHeader from '../components/InvoicesHeader'
import Status from '../components/Status'
import { invoices } from '../utils/mockInvoices'

const Invoices = () => {
  const [items, setItems] = useState(invoices)
  const controls = useDragControls()

  const touchRef = useRef(null)

  useEffect(() => {
    const touchHandler = (e) => e.preventDefault()

    const tag = touchRef.current

    if (tag) {
      tag.addEventListener('touchstart', touchHandler, { passive: false })

      return () => {
        tag.removeEventListener('touchstart', touchHandler, { passive: false })
      }
    }
  }, [touchRef])

  const handleReorder = (reorderedIds) => {
    const reorderedInvoices = reorderedIds.map((id) =>
      items.find((invoice) => invoice.id === id)
    )
    setItems(reorderedInvoices)
  }

  return (
    // invoice parent
    <main className='min-[425px]:w-96 min-[425px]:ml-5 sm:w-[40rem] sm:ml-24 lg:w-fit lg:ml-40 xl:m-auto xl:px-20'>
      <InvoicesHeader />
      <Reorder.Group
        axis='y'
        values={items.map((item) => item.id)}
        onReorder={handleReorder}
      >
        {items.map((invoice) => {
          const { id, amount, due, name, status } = invoice
          return (
            // invoice items
            <Reorder.Item
              className='grid grid-cols-2 mx-4 xl:ml-12 mt-4 bg-[#3b82f6] md:ml-10 lg:ml-5 p-4 rounded-lg shadow-lg items-center'
              key={id}
              value={id}
              dragListener={false}
              dragControls={controls}
            >
              <div className='space-y-2 sm:grid sm:grid-cols-3 items-center'>
                <div>
                  <span className='text-gray-200'># </span>
                  <span className='font-bold'>{id}</span>
                </div>
                <p className='lg:col-span-1 text-xs'>Due {due}</p>
                <p className='block sm:hidden font-semibold'>$ {amount}</p>
                <p className='text-sm lg:text-base hidden sm:block text-end font-semibold'>
                  {name}
                </p>
              </div>
              <div className='flex flex-col gap-4 sm:gap-0 sm:grid grid-cols-2 sm:items-center'>
                <div className='flex sm:hidden justify-end gap-4 items-center'>
                  <p className='text-sm lg:text-base  text-end font-semibold'>
                    {name}{' '}
                  </p>
                  <span ref={touchRef} onPointerDown={(e) => controls.start(e)}>
                    <GrDrag />
                  </span>
                </div>

                <p className='hidden sm:block text-center font-semibold'>
                  $ {amount}
                </p>
                <Status place='component' status={status} />
              </div>
            </Reorder.Item>
          )
        })}
      </Reorder.Group>
    </main>
  )
}
export default Invoices
 Trying on this code, its not working

**Comment by Novo1999** [comment]
Trying on this code, not working

`import { Reorder, useDragControls } from 'framer-motion'
import { useEffect, useRef, useState } from 'react'
import { GrDrag } from 'react-icons/gr'
import InvoicesHeader from '../components/InvoicesHeader'
import Status from '../components/Status'
import { invoices } from '../utils/mockInvoices'

const Invoices = () => {
  const [items, setItems] = useState(invoices)
  const controls = useDragControls()

  const touchRef = useRef(null)

  useEffect(() => {
    const touchHandler = (e) => e.preventDefault()

    const tag = touchRef.current

    if (tag) {
      tag.addEventListener('touchstart', touchHandler, { passive: false })

      return () => {
        tag.removeEventListener('touchstart', touchHandler, { passive: false })
      }
    }
  }, [touchRef])

  const handleReorder = (reorderedIds) => {
    const reorderedInvoices = reorderedIds.map((id) =>
      items.find((invoice) => invoice.id === id)
    )
    setItems(reorderedInvoices)
  }

  return (
    // invoice parent
    <main className='min-[425px]:w-96 min-[425px]:ml-5 sm:w-[40rem] sm:ml-24 lg:w-fit lg:ml-40 xl:m-auto xl:px-20'>
      <InvoicesHeader />
      <Reorder.Group
        axis='y'
        values={items.map((item) => item.id)}
        onReorder={handleReorder}
      >
        {items.map((invoice) => {
          const { id, amount, due, name, status } = invoice
          return (
            // invoice items
            <Reorder.Item
              className='grid grid-cols-2 mx-4 xl:ml-12 mt-4 bg-[#3b82f6] md:ml-10 lg:ml-5 p-4 rounded-lg shadow-lg items-center'
              key={id}
              value={id}
              dragListener={false}
              dragControls={controls}
            >
              <div className='space-y-2 sm:grid sm:grid-cols-3 items-center'>
                <div>
                  <span className='text-gray-200'># </span>
                  <span className='font-bold'>{id}</span>
                </div>
                <p className='lg:col-span-1 text-xs'>Due {due}</p>
                <p className='block sm:hidden font-semibold'>$ {amount}</p>
                <p className='text-sm lg:text-base hidden sm:block text-end font-semibold'>
                  {name}
                </p>
              </div>
              <div className='flex flex-col gap-4 sm:gap-0 sm:grid grid-cols-2 sm:items-center'>
                <div className='flex sm:hidden justify-end gap-4 items-center'>
                  <p className='text-sm lg:text-base  text-end font-semibold'>
                    {name}{' '}
                  </p>
                  <span ref={touchRef} onPointerDown={(e) => controls.start(e)}>
                    <GrDrag />
                  </span>
                </div>

                <p className='hidden sm:block text-center font-semibold'>
                  $ {amount}
                </p>
                <Status place='component' status={status} />
              </div>
            </Reorder.Item>
          )
        })}
      </Reorder.Group>
    </main>
  )
}
export default Invoices
`

**Comment by mattgperry** [comment]
https://www.framer.com/motion/use-drag-controls/#touch-support

**Comment by heymartinadams** [comment]
@mattgperry would you please be so kind and update your [docs here](https://www.framer.com/motion/reorder/#drag-triggers) with this:

```ts
<div onPointerDown={startDrag} style={{ touchAction: "none" }} />
```

Would easily have saved me a few hours 😆

**Comment by WilcoBreedt** [comment]
Agree with @heymartinadams , this took me hours to figure out just now not working on iOS ... Docs need to be updated at https://motion.dev/docs/react-reorder#drag-triggers, I see it is very well documented at https://www.framer.com/motion/use-drag-controls/#touch-support, but let's be honest no one really clicks on more documentation than they have to 😉. It is very confusing once you got it working on desktop and suddenly you get kick in the ..... and it doesn't work on mobile. Thanks for the solutions in this thread though! Very helpful
