### ISSUE TITLE
[BUG] css properties not set in safari (offset-distance/offset-path)

### ISSUE THREAD

**Issue by 6abotage** [framer/motion#1603]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

framer-motion is not able to set offset-distance or offset-path path CSS property on motion.div in Safari. It works on Mozilla Fierfox 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/exciting-mirzakhani-wfqqq9?file=%2Fsrc%2FApp.js

**4. Steps to reproduce**

1. Open Code-Sandbox in Firefox and Safari
2. Both animations work in Firefox, offset-distance and offset-path animation with framer motion does not work in Safari, normal css animation of offset-distance and offset-path work in safari

**5. Expected behavior**

framer-motion is not setting offset-path and offset-distance, neither if you animate it or if you put it in a style tag on the motion.div

**6. Video or screenshots**

/

**7. Environment details**

Firefox 103 macOS
Safari 15.5 macOs

**Comment by mattgperry** [comment]
Safari won’t support offset-path until 16 sadly!

**Comment by mattgperry** [comment]
Not necessarily, no. For instance, it may be that Safari 15.5 has partial support where these properties can be set through selectors in the `<style />` tag but not via the `.style` attribute. Additionally a cursory hack shows `<div />` also doesn't set these styles via the `style` prop.
