### ISSUE TITLE
[BUG] Animating SVG Path/Polygon pathLength doesn't close the shape on animationComplete

### ISSUE THREAD

**Issue by thoseamongus** [framer/motion#1605]
**1. Describe the bug**

When animating the pathLength on <motion.path> or <motion.polygon> the shape is left open and a gap is visible

**2. Steps to reproduce**

1. Create an svg element
```jsx
<motion.svg width="100px" height="100px">
     <motion.polygon
                points="50 2.409, 91.194 26.192, 91.194 73.759, 50 97.542, 8.806 73.759 , 8.806 26.192 , 50 2.409"
		initial={{ pathLength: 0 }}
		animate={{
			pathLength: 1,
			transition: {
					duration: .5,
					type:"tween",
					ease:"easeInOut"
				}					
			}}
     style={{ fill: "none", stroke: "url(#_Linear1)", "strokeWidth": "4px" }}  />
<defs>
	<linearGradient id="_Linear1" x1="0" y1="0" x2="01" y2="0"  >
		<stop offset="0" style={{ stopColor: "rgb(255,233,0)", stopOpacity: 1 }} />
		<stop offset="1" style={{ stopColor: "rgb(234,39,194)", stopOpacity: 1 }} />
	</linearGradient>
</defs>
</motion.svg>
```
2. Watch the animation
3. The top of the hexagon should be closed but there is a gap
4. You might have to zoom in to see it
![image](https://user-images.githubusercontent.com/435601/176767445-7b4c5e6f-4584-41e3-a199-ae576c162ce1.png)

**3. Expected behavior**

When the animation completes it should close the shape since polygons are supposed to be closed shapes.

**4. Environment details**

Happens on all latest version browsers with framer-motion version 6.3.16

**5. Workaround

```jsx
const ref = useRef<SVGPolygonElement>();
<motion.svg width="100px" height="100px">
     <motion.polygon
               ref={ref}
                points="50 2.409, 91.194 26.192, 91.194 73.759, 50 97.542, 8.806 73.759 , 8.806 26.192 , 50 2.409"
		initial={{ pathLength: 0 }}
		animate={{
			pathLength: 1,
			transition: {
					duration: .5,
					type:"tween",
					ease:"easeInOut"
				}					
			}}
                onAnimationComplete={()=>
                {
                     // remove stroke-dasharray after the animation completes
                     // needs to be on the next paint since its still animating the stroke
                      requestAnimationFrame(()=>{ref.current?.removeAttribute("stroke-dasharray");});
                }}
     style={{ fill: "none", stroke: "url(#_Linear1)", "strokeWidth": "4px" }}  />
<defs>
	<linearGradient id="_Linear1" x1="0" y1="0" x2="01" y2="0"  >
		<stop offset="0" style={{ stopColor: "rgb(255,233,0)", stopOpacity: 1 }} />
		<stop offset="1" style={{ stopColor: "rgb(234,39,194)", stopOpacity: 1 }} />
	</linearGradient>
</defs>
</motion.svg>
```

I haven't looked at the code but I think a possible fix would be when animating pathLengths to remove the stroke-dasharray when its complete vs setting it to `stroke-dasharray="1px 1px"`

**Comment by stentibbing** [comment]
Is it in all browsers ? I faced this in Chrome (problably in Edge aswell) but not in Firefox. The problem was that the stroke is centered and it will be meeting the other end so animation will be completed. Adding stroke-linecap fixed it visually.

**Comment by Ayuilos** [comment]
I got the the problem, need more attention to this issue, devs.

Thanks❤️.

**Comment by mattgperry** [comment]
Please make a ticket with a sandbox as per the issue template.
