### ISSUE TITLE
[BUG]: drag axes do not rotate with element

### ISSUE THREAD

**Issue by AGBrown** [framer/motion#1608]
- [x] ~**1. Read the [FAQs](#faqs) 👇**~

**2. Describe the bug**

- Given two `motion.div` elements, one inside the other
- And the outer element is rotated using `animate: { rotate: degrees }`
- And the inner element is drag-able inside the rotated div, constrained to a drag axis `y`
- When I drag the mouse in-line with the outer div
- Then the inner div should move along the motion of the mouse, and along the track of the outer div

What I see:
- If the rotation is zero degrees, the element moves vertically, and the mouse movement to drag the element is also vertical.
- If the rotation is any non-zero degrees, the element moves along the rotated axis, but the mouse movement to drag the element is still vertical.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/embed/shy-glade-cr0c8b?fontsize=14&hidenavigation=1&theme=dark&view=preview

**4. Steps to reproduce**

1. Expected: Drag the green div, the mouse axis for dragging is vertical, the div moves vertically
1. Error: Drag the red div, moving the mouse horizontally: it does not drag

The mouse axis for the red div drag is vertical, while the div moves horizontally

**5. Expected behavior**

Users expect the drag axis to be along the line the div moves, even after rotation.

**6. Video or screenshots**

I can provide if the above is not clear enough.

**7. Environment details**

all

**Comment by mattgperry** [comment]
To set expectations I'm closing this as a `wontfix` - it might still happen but probably only if we find a use within Framer.
