### ISSUE TITLE
[BUG]Demo(Drag to reorder tabs): tab item `scale` stops changing when add tabs consecutively

### ISSUE THREAD

**Issue by xuerzong** [framer/motion#1609]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

When I add tabs consecutively, the text of first tab will be deformed.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-5-drag-to-reorder-tabs-zd2q7?from-embed

**4. Steps to reproduce**

1. Click the add button twice consecutively

**5. Expected behavior**

All tabs are not deformed

**6. Video or screenshots**

https://user-images.githubusercontent.com/49989857/177195475-ecf465a8-920c-4672-a9a9-4d928b5137e9.mov

**7. Environment details**

- MacOS: 12.3 (m1)
- Chrome: 103.0.5060.53 (arm64)

**Comment by mattgperry** [comment]
Fixed in latest
