### ISSUE TITLE
[FEATURE] Publish docs for past versions

### ISSUE THREAD

**Issue by colepeters** [framer/motion#1612]
**Is your feature request related to a problem? Please describe.**
I have components and apps using past versions of Framer Motion (in my case, version 3), but there's no way to read the docs for past versions — at least as far as I can tell from the Framer Motion docs website. This makes it really hard to debug issues with these components and apps relating to Framer Motion.

**Describe the solution you'd like**
I would like previous versions of the docs to be available online.

**Describe alternatives you've considered**
N/A

Thanks for the consideration!

**Comment by mattgperry** [comment]
Hi @colepeters, I definitely see some value in this but it basically isn't going to happen, there's no resource to implement this. Changes between majors is usually very minimal and much of what was written in the original v1 still works today. And there's a straightforward upgrade path in the upgrade guide.
