### ISSUE TITLE
[FEATURE] add onExitStart prop to AnimatePresence

### ISSUE THREAD

**Issue by ergofriend** [framer/motion#1618]
**Is your feature request related to a problem? Please describe.**

For example, let's say you want to animate a transition from a page with multiple links to a detail page, using location.pathname as the key.
If you click on another link at the same time the location changes, two histories will be accumulated before the animation.
Therefore, we would like to display an Overlay component that disables link clicking for the entire page from the time the key changes until the animation ends.

**Describe the solution you'd like**
Add onExitStart prop to AnimatePresence, it looks like below.

```tsx
// react-router v6

const App = () => {
  const outlet = useOutlet()
  const location = useLocation()
  const key = location.pathname
  const showOverlay = useRef(false)
  return (
      <AnimatePresence
          initial={false}
          onExitStart={() => {showOverlay.current = true}} 
          onExitComplete={() => {showOverlay.current = false}}
        >
        {showOverlay.current && <Overlay /* stop pointer-events */ />
        <Suspense key={animationKey} fallback={<Loading />}>
          {outlet}
        </Suspense>
      </AnimatePresence>
  )
}
```

**Describe alternatives you've considered**
If the routing definition and current location are different for all pages, it would be too redundant to go around covering them with an Overlay component.

For example, a transition animation that moves left or right should be implemented as follows to go around.
```tsx
const XXXPage = () => {
  const location = useLocation()
  const showOverlay =  location.pathname === '/XXXroute'
  return (
      <div>
        {showOverlay && <Overlay /* stop pointer-events */ />
        ... /* any page layout */
      </div>
  )
}
```

**Comment by mattgperry** [comment]
It should be that the overlay is added on the same render that removes the content, with the state being unset in `onExitComplete`

**Comment by TahaAhmedRasheed** [comment]
You've dodged the question I'm afraid. In the specific example shared by ergofriend above, the content removal isn't triggered within the component but externally by react-router. How is one supposed to 'add the overlay on the same render that removes the content' in that case?

**Comment by TahaAhmedRasheed** [comment]
@ergofriend Please let us know if you a found a solution to this separately.
