### ISSUE TITLE
[FEATURE] Add progress control for transition using motion values

### ISSUE THREAD

**Issue by zhangcx93** [framer/motion#1632]
I want to make an scroll linked layout animation, but currently, there is no way to use motion values to control layout animations.
I'm thinking if we can make transition function not a time controlled function, but a progress value(between 0 and 1) controlled function, with an extra parameter, it can solve this problem, and also make many other animation easily controlled by scroll-progress.

Though many animation can be done by motion value, but it requires user to manually do value transitions for each properties, with this feature, things would be much easier.

Also this enables easy translate between scroll triggered animation and scroll linked animation, which during my development experience, happens a lot. Many animations are designed as key-frame animation, but sometimes we want make them scroll-linked, not event triggered animations. With this new API we can easily use the key-frame animation with one extra parameter, then it is done.

**Describe the solution you'd like**

```
function GeneralTransition() {
  const { scrollYProgress } = useScroll();
  return (
    <>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ progress: scrollYProgress }}
      >
        Something
      </motion.div>
    </>
  );
}
function LayoutTransition() {
  const { scrollYProgress } = useScroll();
  const [visible, setVisible] = useState(false);
  return (
    <>
      <div className="flex">
        {!visible && <motion.div layoutId="movingPart" onClick={() => setVisible(true)}>Something</motion.div>}
      </div>

      <div className="relative">
        {visible && (
          <motion.div
            layoutId="movingPart"
            transition={{ progress: scrollYProgress }}
          >
            Something
          </motion.div>
        )}
      </div>
    </>
  );
}
```

**Describe alternatives you've considered**
For scroll linked layout animation, i can only think of re-implement the complicated layout animation logic and interpolate all changed style/position with motion value.

**Comment by Krono5GG** [comment]
This is very neat. Hope it can be added soon, would love to use it in my upcoming projects.

**Comment by mrbjjackson** [comment]
Just wanted to chime in and say I too would love this feature. Would be great to queue up a complex animation sequence and effectively control the "playhead" of the animation with something like a scrollYProgress.

**Comment by mattgperry** [comment]
To set expectations, I'm closing as a `wontfix`. I do like the idea but could be delicate and I don't see it happening until we need something like it in Framer.
