### ISSUE TITLE
Error when using AnimatePresence / motion.div TypeError: Cannot read properties of undefined (reading '_owner')

### ISSUE THREAD

**Issue by ikjudd** [framer/motion#1639]
hey all,

using framer-motion in a nextjs 12 / react 18 stack

had animations working just fine a few days ago, a clean 'fade in / fade out' then today, i noticed that the animations got very choppy and take nearly 10 seconds to reveal the component. I started receiving this error as well

TypeError: Cannot read properties of undefined (reading '_owner')
TypeError: Cannot read properties of undefined (reading '0')

here is how I'm using it..

 ```
 {viewAgileModal && (
        <AnimatePresence>
            <motion.div
              key={"about modal"}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
            >
              <AgileAboutModal />
            </motion.div>
        </AnimatePresence>
          )}
```

has the package deprecated or something? i haven't changed a thing since a few days ago and it was working just fine

**Comment by jakobsen** [comment]
I think you might fix this issue by moving the `AnimatePresence` wrapper outside of the conditionally rendered component:

```jsx
<AnimatePresence>
  {viewAgileModal && (       
    <motion.div
      key={"about modal"}
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
    >
      <AgileAboutModal />
    </motion.div>
  )}
</AnimatePresence>
```
