### ISSUE TITLE
[FEATURE] Search bar in docs

### ISSUE THREAD

**Issue by PritamSarbajna** [framer/motion#1642]
### Is your feature request related to a problem? Please describe. ###
When I'm reading the docs and searching for a particular word I should be able to do with search bar. not by `ctrl+F`

### Describe the solution you'd like ###

In the documentation there should be search bar which returns what I'm searching.

![Screenshot (183)](https://user-images.githubusercontent.com/90236635/182524870-0dc050b4-6d00-4e38-8e23-c1707db55739.png)

**Comment by Kinark** [comment]
Yeah, it's pretty funny how literally all docs framework provide search out-of-the-box and framer-motion simply doesn't have any search bar.

**Comment by jamborski-dev** [comment]
Yes please. It is pretty annoying when looking for a specific thing I have to opt to using browser search or just to Google exact thing to land on the docs page I need..

**Comment by mattgperry** [comment]
The search docs don't use an OOTB solution. Some time this year they're going to be ported to Framer, so the site team probably isn't going to implement a search box until then.

**Comment by bsampada7** [comment]
Has this been implemented? I still cannot find a search bar on the documentation page. I was going to open a feature request when I saw this ticket as closed.

**Comment by gauel** [comment]
Yeah exactly. This is so annoying and unexpected from a framework like Framer Motion.

**Comment by Cesar-Paredes** [comment]
still nothing, it's pretty annoying and hard to find solutions when you don't have a search bar!
