### ISSUE TITLE
[BUG]How to expand/Shrink items without covering the others

### ISSUE THREAD

**Issue by voyagebagage** [framer/motion#1644]
**1. Read the [FAQs](#faqs) 👇**
I read !
**2. Describe the bug**
Ok, I'm new here but I'm trying to do something like **[that with framer motion:(youtube)](https://www.youtube.com/watch?v=whk76VMOlp0&list=PLgcPxVODYXGIT9iX0uHBUYQSyqGvafwHT&index=3
)**

I'm using chakra ui and nextjs but I have tried few exemple with chakra and from you sandbox exemples but no luck, 
### 1 **first** thing is that if I try to expand the circle they will go on top of each other and maybe that is a container/wrapper issue 
![Capture d’écran 2022-08-05 à 17 27 18](https://user-images.githubusercontent.com/81431557/183058737-3adcb14b-dfe4-4b1b-8d4e-2c6ab90d5966.png)
and I would like they move away when on Click.

### 2 seconde I'm using variants here but I've tried ``` {isOpen && <Content/>} ```but that just create another circle in between....

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
So what is the correct way to achieve it? if possible and down the road I would like to build a timeline

[A CodeSandbox ](https://codesandbox.io/embed/sandpack-project-forked-1rne70?fontsize=14&hidenavigation=1&theme=dark)

**4. Steps to reproduce**

you can play around and try the <AnimatePresence> if you want 
I use [that exemple](https://codesandbox.io/s/framer-motion-2-animating-shared-layouts-forked-w8s8mw?file=/src/App.js:958-968)
and that one the variants one

**5. Expected behavior**

as the youtube video link intro, I would like the circles not clicked on to move away when the one i'm clicking on expends then back to normal when I click again

**7. Environment details**

Chakra ui, nextjs, chromuim(brave)

**Comment by voyagebagage** [comment]
so I manage to get there:

```jsx
<AnimatePresence initial={false}>
        <Box
          as={motion.div}
          animate={isSelected ? "expand" : "shrink"}
          layout
          bg={props.bg}
          variants={variants}
          m={4}
          // onClick={() => setIsSelected((isSelected) => !isSelected)}
          // not work: transition={{ ... }}
          padding="2"
          // @ts-ignore - "Does not exist" Type Error against Motion
          // bg="red"
          borderRadius="full"
          width="12"
          height="12"
          display="flex"
          flex="1"
          flexDirection="column"
          gap={10}
        />
        {/* {isSelected && <MyBox key={props.key} />} */}
      </AnimatePresence>
      
  ```
  
  mix of variant and Animated Presence, **if you any suggestion of any better way to achieve it** ?
  here I added a margin

**Comment by mattgperry** [comment]
Glad you managed it - this looks more like a CSS question than Framer Motion but yeah scale alone will overlap as it isn't account for in the layout
