### ISSUE TITLE
[BUG] Safari Scaling on an SVG is blurry

### ISSUE THREAD

**Issue by wahidshafique** [framer/motion#1650]
**2. Describe the bug**

Only on Safari, when I scale an svg asset to x times its original size, it appears noticeably more blurry when comparing it against firefox or chrome

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/scaling-for-svg-blurry-in-safari-0i3hy6?file=/src/App.tsx

**4. Steps to reproduce**

1. visit the sandbox link
2. open the link in chrome and safari
3. notice the difference when the item is scaled in Safari

**5. Expected behavior**

Both should be on par

**6. Video or screenshots**

Safari (blurry): https://gyazo.com/12cca283d109647909cc9dacce80b7b5
Chrome (normal): https://gyazo.com/617b65c2e92420adc2a61162d6116367

**Comment by mattgperry** [comment]
This seems like a Webkit rendering bug (it may even be intended behaviour) https://bugs.webkit.org/
