### ISSUE TITLE
[Help] How to change font color in a translating way ? whileHover={{}}

### ISSUE THREAD

**Issue by voyagebagage** [framer/motion#1653]
Give a clear and concise description of what the issue is.

I would like to change the color of the Text on hover, **in a translating way** , 
I have a default  font color, and while I'm hovering it's changing to the other (font) color coming in sliding from the bottom to the top.

## [SANDBOX](https://codesandbox.io/s/chakra-ui-framer-motion-example-forked-guch4b?file=/src/Example.js)
what do you thing I need to make it work?

or

should I look for a background half transparent half red in this exemple, and move its bg-position ?

ps: I'm aware that the hover is on the wrong element for now

**7. Environment details**
I'm using chakra and next

Thanks

**Comment by mattgperry** [comment]
Hi there

This isn't a Framer Motion issue as much as it is a CSS question. Your best bet IMO is to render two of each letter, one on top of the other, and use https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path to "reveal" the one underneath
