### ISSUE TITLE
[BUG] When using custom motion with layout it doesn't animate

### ISSUE THREAD

**Issue by saharnaha** [framer/motion#1661]
**When trying to use framer motion layout with custom component it doesn't animate while with motion.div it does**

### CodeSandbox

[CodeSandbox](https://codesandbox.io/s/heuristic-golick-omnuhv?file=/src/App.js)

### Screen recordong
https://user-images.githubusercontent.com/103422273/184493884-6591beee-81a9-4ba3-9050-b43dcf862665.mov

**Comment by mattgperry** [comment]
There's multiple things going on here

1. Creating components within the render function
2. No use of `React.forwardRef`
3. Attempting to receive `ref` as prop instead of second argument

https://codesandbox.io/s/boring-buck-vhkd73?file=/src/App.js
