### ISSUE TITLE
[BUG] Setting `zIndex` of dragging children

### ISSUE THREAD

**Issue by vasilemidrigan** [framer/motion#1665]
When drag down, the item slips over the items in the list (which seems to be normal), but when dragging up, the item slips under the items in the list (which I find pretty ugly). Is there any solution how to fix that?

Sandbox:
https://codesandbox.io/s/cranky-sinoussi-cm9fxz?file=/src/App.js

Click a task and drag it down, then drag it up (and notice how it slips under the other tasks)

Expected behavior:
The task we drag needs to slip over not under another tasks

**Comment by mattgperry** [comment]
Could you do something like `whileDrag={{ zIndex: 2 }}` ?

**Comment by vasilemidrigan** [comment]
It doesn't work for me.

**Comment by vasilemidrigan** [comment]
Does anybody know how to fix that?

**Comment by mattgperry** [comment]
Ah yeah it also needs to have `position: relative`

https://codesandbox.io/s/vibrant-mirzakhani-lg0ne9?file=/src/components/ToDoList.js:2153-2200
