### ISSUE TITLE
[BUG] Using framer-motion-3d 7.X.X throws 'Error: R3F: * is not part of the THREE namespace!' 

### ISSUE THREAD

**Issue by AugustGSP** [framer/motion#1667]
It seems as if the latest release of framer-motion is incompatible with one of its dependencies when using `MotionCanvas`, but I'm not 100% sure which one, _(guessing @react-three/fiber ?)_. 
Even the most barebones setup I can think of throws an error about Three components `not being part of the THREE namespace`:

https://codesandbox.io/s/fervent-mcnulty-07tvur?file=/src/App.js

`Error: R3F: PerspectiveCamera is not part of the THREE namespace! Did you forget to extend? See: https://docs.pmnd.rs/react-three-fiber/api/objects#using-3rd-party-objects-declaratively`

**Dependencies**  _(latest stable release of each one)_

- @react-three/fiber: 8.3.1
- framer-motion-3d: 7.2.0
- react: 18.2.0
- three: 0.143.0

The error persists on all browsers.

**Comment by hood** [comment]
Same issue here. 
Using
```
framer-motion: 7.3.2
framer-motion-3d: 7.3.2
```

**Comment by QuentinMerabet** [comment]
Does anybody found a solution to this? Same issue.

**Comment by mattgperry** [comment]
This can be fixed by following the instructions in the error message. But we should do this by default in the LayoutCamera component
