### ISSUE TITLE
[FEATURE] Add support for custom interpolators

### ISSUE THREAD

**Issue by andyrichardson** [framer/motion#1669]
**Is your feature request related to a problem? Please describe.**
I was trying to use an interpolator for a path animation, but couldn't find a way to do this and instead had to do the following.

```js
const oldLine = pathRef.current ? pathRef.current.getAttribute("d") : "M0,10 L10,10"
const newLine = // data conversion to new path
const interpolator = somePathInterpolator(oldLine, newLine);

<motion.path
  ref={pathRef}
  animate={{
    d: [0, 1].map(interpolator)
  }}
/>
```

This unfortunately doesn't allow for spring animations without manually creating an easing curve.

**Describe the solution you'd like**
Being able to provide an interpolator for transitioning between props would be nice

```jsx
// Path element animating path
<motion.path 
  d={someValue}
  interpolate={{ d: (oldVal, newVal) => interpolatePath(oldVal, newVal) }}
/>

// Circle element animating fill color across RGB spectrum
<motion.circle 
  cx={10}
  cy={10}
  r={10}
  fill={someColor}
  interpolate={{ fill: (oldVal, newVal) => interpolateRgb(oldVal, newVal) }}
/>
```

In the first example, the function in the `interpolate` prop would be called whenever the `d` prop changes. That function would be expected to return an interpolation function ([example](https://github.com/d3/d3-interpolate/blob/main/src/number.js#L1)) which is then called by framer when transitioning.

**Describe alternatives you've considered**
For paths, baked in interpolation would be nice but I think custom interpolation support would open up opportunities for a wider set of animated props.

**Additional context**
N/A

**Comment by mattgperry** [comment]
To set expectations I'm closing this as a `wontfix` as it's unlikely to be implemented in the near future but `useTransform` does have support for custom mixers https://www.framer.com/motion/use-transform/###mixer
