### ISSUE TITLE
[BUG] Install error for `"react": "^17.0.2"`

### ISSUE THREAD

**Issue by nichita-pasecinic** [framer/motion#1675]
Could not install `framer-motion` in a react project 

```json
"react": "^17.0.2",
"react-dom": "^17.0.2",
```

Install cmd `npm i framer-motion`

Error log

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: trading-ui@0.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.0.0" from framer-motion@7.2.0
npm ERR! node_modules/framer-motion
npm ERR!   framer-motion@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\NichitaPasecinic-JG\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\NichitaPasecinic-JG\AppData\Local\npm-cache\_logs\2022-08-22T08_44_28_713Z-debug-0.log
```

**Comment by jacob-ruiz** [comment]
I'm having the same issue. Any luck finding a fix @nichita-pasecinic ?

**Comment by juanserna8** [comment]
I've got the same issue. I thought I had solved it by running npm install --save framer-motion --legacy-peer-deps.
It was running ok in my local server, but it crashed when deploying.

**Comment by mattgperry** [comment]
As per the upgrade guide and the error message, Framer Motion 7 uses React 18 as a minimum. If you can’t upgrade then you can use the latest version of 6.

**Comment by nichita-pasecinic** [comment]
@mattgperry Thanks, would be nice to have a table of `motion` versions compatible with `react` versions

**Comment by jacob-ruiz** [comment]
Switching to version 6 worked for me, thanks for the quick reply @mattgperry

**Comment by juanserna8** [comment]
Hey @mattgperry thanks mate. Problem solved. Much appreciated!
