### ISSUE TITLE
[BUG] Layout animated components misposition after scroll and parent components state change

### ISSUE THREAD

**Issue by stentibbing** [framer/motion#1676]
**Description**

Layout animated components misposition themselves after scrolling the document and changing state of the parent.

**CodeSandbox link:**

https://codesandbox.io/s/framer-layout-bug-11q9uz?file=/src/App.js

**Steps to reproduce**

1. Hover over **LEFT** menu items (no need to click)
2. Scroll down to the bottom of the page
3. Click "Change state" button to change the parents state
4. Hover over **RIGHT** menu items (no need to click)
5. The layout animated hover indicator of the **LEFT** menu will misposition itself out of the viewport

**Expected behavior**

There should be no repositioning relative to the document / viewport

**Unexpected behaviour present on**

MacOS 12.4
Firefox 103.0.2 / Chrome 104.0.5112.101 / Safari 15.5

**Notes**

As a temporary fix it's possible to use memoized components. Note that the parent container of the elements is fixed positioned.

**Comment by mattgperry** [comment]
Fixed in latest
