### ISSUE TITLE
[BUG] AnimatePresence Exit for Children

### ISSUE THREAD

**Issue by MrDesjardins** [framer/motion#1682]
**1. Read the [FAQs](#faqs) 👇**

✅ I saw what is described for the AnimatePresence, but still couldn't find the information to fix my issue.

**2. Describe the bug**

When unmounting a parent with a list of children, the animation on the children does not trigger.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[CodeSandbox](https://codesandbox.io/s/framer-motion-unmounting-children-animation-part-1-yhs6km?file=/src/Parent.tsx)

**4. Steps to reproduce**

1. Go to the [Code Sandbox](https://codesandbox.io/s/framer-motion-unmounting-children-animation-part-1-yhs6km?file=/src/Parent.tsx) 
2. The UI has a button that forces a remount of the Parent.tsx. That one will force a remount of its child.
3. Click the button
4. The LI inside the `Child` are mounted and animated when the `Parent` component is mounted.

**5. Expected behavior**

The `Child` mount with the two LI elements animated (staggered). That work until unmount. The expectation is that the two LI would move back (reverse animation) before unmounting.

**6. Video or screenshots**

https://user-images.githubusercontent.com/1014796/187276365-b3c67cea-4d0e-4960-9b6a-da2ac8e4b1d8.MP4

**7. Environment details**

- Mac or Windows (reproduce in both)
- Chrome 104
- Framer version 6.5.1

**8. What have you tried?**

1. I tried to move the `<AnimatePresence>` at different places in the tree
2. I tried to change the `key`
3. I tried to pass change the variants/initial/animate/exit properties
4. I tried to move the two LI into a single component and move the `<AnimatePresence>` in the Child.tsx

**Comment by MrDesjardins** [comment]
I have a second example in which I allow two levels of rendering (one at the app, and one at the parent container of the two emojis).

https://codesandbox.io/s/framer-motion-unmounting-children-animation-part-2-mj7ygo?file=/src/Child.tsx:1028-1037

The button that re-renders the parent has the mount/unmount animation working in both ways. However, the button that forces the application to re-render is still working only on mounting. To fix the parent-to-children list, I removed the transition `spring` to a specific delay, and it seems to work out if adjusting the stagger delay at a lower value.

**Comment by MrDesjardins** [comment]
I think I found some explanation, but one question remains.

Third iteration here: https://codesandbox.io/s/framer-motion-unmounting-children-animation-part-3-e3x3pd?file=/src/Parent.tsx

I can make one of the two buttons work, not both at the same time.

For the "Toggle" button, at the app level. I need to have a `AnimatePresence ` in the App.tsx:

```
<AnimatePresence exitBeforeEnter={true}>
            <Parent key={mountCount} mountCount={mountCount} />
</AnimatePresence>
```

Pushing the toggle button will appear and disappear with the animation expected. However, the "Remount Parent" only performs the animation on the render, not the unmount (exit).

If I add a `<AnimatePresence exitBeforeEnter={true}>` in the parent.tsx (keeping the one also in app.tsx), I only have the "Remount Parent" button with the enter/exit animation, while the "Toggle" button only has the initial animation without the exit.

If I keep the  `<AnimatePresence exitBeforeEnter={true}>` in the parent.tsx and remove it from the app.tsx, the initial and exit animation work for the "Remount Parent" button, not the toggle. So, it is the opposite situation.

The remaining question is how can we handle different remounting at many levels and have all the animation executed?

**Comment by mattgperry** [comment]
Dupe https://github.com/framer/motion/issues/746
