### ISSUE TITLE
[BUG] Click on draggable component breaks AnimatePresence

### ISSUE THREAD

**Issue by Dima9473** [framer/motion#1686]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
It is possible to stop animation of closing child component of AnimatePresence by clicking inside draggable area.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
To reproduce use next link
https://codesandbox.io/s/summer-frog-dck42k?file=/src/AnimatedComponent.tsx

**4. Steps to reproduce**

1. Go to https://codesandbox.io/s/summer-frog-dck42k?file=/src/AnimatedComponent.tsx
2. Click on show button
3. Click on close button
4. Immediately click red area

**5. Expected behavior**
Child component is expected to be closed

**6. Video or screenshots**

https://user-images.githubusercontent.com/5555342/188368151-b9007ed5-78fc-4d3b-af95-a4af9ec72678.mov

**7. Environment details**
Google Chrome 104.0.5112.101

**Comment by Dima9473** [comment]
Hi, Is there any information?

**Comment by mattgperry** [comment]
Fixed in latest
