### ISSUE TITLE
[FEATURE] Mocks for testing

### ISSUE THREAD

**Issue by atk** [framer/motion#1690]
**Is your feature request related to a problem? Please describe.**
Testing code that uses framer-motion in a jsdom environment is considerably slowed down. So a mock that would bypass the animation steps would help a lot. Unfortunately, the API is rather involved and thus hard to keep in sync; it would be simpler for the package itself to provide mocks.

**Describe the solution you'd like**
A 'framer-motion/mocks' export that can be used in testing would be the best solution IMO.

**Describe alternatives you've considered**
One can still mock only a few APIs, but that is brittle and requires extra work.

**Additional context**
Testing was done with jest and vitest. Both allow for filename alliasing.

**Comment by mattgperry** [comment]
By slower what do you mean? Are you awaiting animations to finish? I've been thinking about a `MotionConfig` prop that would force instant transitions for this kind of thing, rather than maintaining a seperate mock. Would this suffice?

**Comment by atk** [comment]
Just by loading the whole infrastructure, the tests require more memory and CPU. Not sure what the animations do to jsdom, but I have tried to mock framer-motion in a rather complex test suite, which went from >60s to 16s immediately. But yes, such a prop would probably already go a long way to improve testing performance.

**Comment by thebuilder** [comment]
This would great. Being able to skip `LazyMotion` and animations in general would help a lot with making tests faster and more reliable.
I'm running in to a bunch of act() warnings when upgrading to the latest version of `@testing-library/dom`, and it seems to be related to `LazyMotion` components.

**Comment by JPaulDev** [comment]
Yes matt, the main issue is having to wait for animations to complete before running assertions.

Examples I ran into were removing elements with an animation then checking they have been removed, currently only way is to wait. I think react spring does what you are talking about.

They have some way to disable all animations.

https://react-spring.dev/guides/testing#testing

Bottom of the page.

**Comment by mryechkin** [comment]
> By slower what do you mean? Are you awaiting animations to finish? I've been thinking about a `MotionConfig` prop that would force instant transitions for this kind of thing, rather than maintaining a seperate mock. Would this suffice?

Hi @mattgperry - just wondering if this is something that's been given more consideration?

**Comment by mattgperry** [comment]
```
import { MotionGlobalConfig } from "framer-motion"

MotionGlobalConfig.skipAnimations = true
```
