### ISSUE TITLE
[BUG] Shared drag gesture drops drag and snaps element to origin of new parent

### ISSUE THREAD

**Issue by siddhatiwari** [framer/motion#1692]
**2. Describe the bug**

Shared drag gestures don't seem to work following the examples in the current version of the docs. Shared drag gestures, when the dragged element moves to a new parent, seem to drop the drag gesture and snap the element back to the origin, which shouldn't happen.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

I forked the Shared drag gesture example from the docs (https://codesandbox.io/s/framer-motion-2-shared-drag-gesture-5trtt?from-embed) with updated framer motion dependencies (`"framer-motion": "7.3.2"`) to showcase the bug.

Bug: https://codesandbox.io/s/framer-motion-2-shared-drag-gesture-forked-doukgr?file=/src/App.js

**4. Steps to reproduce**

1. In the forked example, drag the square to and from the different zones to notice how the square DOES snap to the origin and the drag DOES end
2. In the original example, drag the square to and from the different zones to notice how the square DOESN'T snap to the origin and the drag DOESN'T end

**5. Expected behavior**

The forked example with the new version of framer motion should function just like the original example.

**Comment by EricSSartorius** [comment]
@siddhatiwari I just saw the following comment in the example sandbox that might answer your question:
```
 NOTICE: This won't work in later versions of Framer Motion. The shared drag gesture was never widely used. But we may add it back sometime in the future.
 ```
 It looks like the version in the website example is `2.5.0` so this behavior will not work in version `7.3.2`

**Comment by markoradak** [comment]
Any idea whether it will in fact be added ever again? We are using it on multiple projects where we are still stuck with version 2 🥲

**Comment by mattgperry** [comment]
Setting as `wontfix` to set expectations. Not to say it will never happen but it'll probably be if we need it in Framer.
