### ISSUE TITLE
framer motion with React 17

### ISSUE THREAD

**Issue by aymanesarrar** [framer/motion#1694]
hello, so i wanted to use framer motion on an old version of react (react 17), and because it doesn't have the useId function i keep getting this error 
Uncaught TypeError: React.useId is not a function, is there any way how to fix that ?

**Comment by Carloitaben** [comment]
Yeah, this is because [Framer Motion 7 requires React 18](https://www.framer.com/docs/guide-upgrade/#70) to work. Switching to Framer Motion 6 should do the trick!

**Comment by aymanesarrar** [comment]
thank you
