### ISSUE TITLE
[BUG] Type '{ children: Element[]; initial: false; }' is not assignable to type 'IntrinsicAttributes & AnimatePresenceProps'.   Property 'children' does not exist on type 'IntrinsicAttributes & AnimatePresenceProps'.

### ISSUE THREAD

**Issue by asif-simform** [framer/motion#1697]
Type '{ children: Element[]; initial: false; }' is not assignable to type 'IntrinsicAttributes & AnimatePresenceProps'.   Property 'children' does not exist on type 'IntrinsicAttributes & AnimatePresenceProps'.

**Comment by mattgperry** [comment]
Please reopen with a sandbox link
