### ISSUE TITLE
[BUG] pathLength does not animate using whileInView

### ISSUE THREAD

**Issue by lochie** [framer/motion#1698]
**2. Describe the bug**

`pathLength` does not animate when used within `whileInView`.
works fine when using `animate`

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-pathlength-x-whileinview-bug-pirr56

**4. Steps to reproduce**

```jsx
<motion.path
  viewport={{ once: true }}
  initial={{ pathLength: 0 }}
  whileInView={{ pathLength: 1 }}
  ...
/>
```

**5. Expected behavior**

`pathLength` to animate when in viewport

**Comment by mattgperry** [comment]
Ah this looks like a bug in Chrome, but I'll make a note in the docs https://bugs.chromium.org/p/chromium/issues/detail?id=963246

**Comment by mattgperry** [comment]
You could use `onViewportEnter` on a parent HTML `motion` element to change `animate` to do this more manually
