### ISSUE TITLE
transition color doesn't work.

### ISSUE THREAD

**Issue by mohammadaahnaaf** [framer/motion#1699]
while I'm working with framer-motion wanna apply some styling on it. but didn't find anything useful to the doc. while applying bgcolor to the <motion.div> it directly visible on the main page's bg color. Not the animated layers.

please provide an code sandbox example how to do it in right way.

import '../styles/globals.css'
import '../styles/tag.css'
import { motion, AnimatePresence } from "framer-motion";
import { useRouter } from 'next/router';

function MyApp({ Component, pageProps }) {

  const router = useRouter();
  const variants = {
    initialState: {
      opacity: 0,
      clipPath: "polygon(0 0, 100% 0, 100% 100%, 0% 100%)",
    },
    animateState: {
      color: "#001451",
      opacity: 1,
      clipPath: "polygon(0 0, 100% 0, 100% 100%, 0% 100%)",
    },
    exitState: {
      clipPath: "polygon(50% 0, 50% 0, 50% 100%, 50% 100%)",
    },
  }

  return (
    <AnimatePresence exitBeforeEnter>
      <motion.div
        key={router.route}
        initial="initialState"
        animate="animateState"
        exit="exitState"
        transition={{
          background: "#001451",
          duration: 0.75,
        }}
        variants={variants}
        className="animation-style"
      >
        <Component {...pageProps} />
      </motion.div>
    </AnimatePresence>
  );

}

export default MyApp

**Comment by mattgperry** [comment]
Please provide a codesandbox and reopen, thanks!
