### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RyanLarge13** [framer/motion#1701]
Hey, I am having an issue with Reorder.Group/.Item with framer motion in my React project. It seems that when you declare a variable as an array it only takes in an array of strings, but not an array of objects. All functionality works besides the actual reordering of the list. I could not find anything in the documentation stating you can not use an array of Objects, if I have miss read the documentation than forgive this issue. Here is a copy of the code I use to create my Reorder list... 

import React from 'react';
import { Reorder } from 'framer-motion';
import { useState } from 'react';

const itemList = [
	  { name: 'Laundry', id: 1 }, 
	  { name: 'Dishes', id: 2 }, 
	  { name: 'Garbage', id: 3 }, 
	  { name: 'Groceries', id: 4 }
	]

const List = () => {
	const [items, setItem] = useState(itemList);
	
  return (
    <div className="to-do-list list-list">
        <div className="list-container">
          <Reorder.Group className='list' axis='y' values={items} onReorder={setItem} >
            {itemList.map((item) => (
            <Reorder.Item className='item' key={item.id} value={item} whileInView={{ scale: [0, 1.1, .9, 1] }} whileTap={{ scale: 1.1 }}>
              <p>{item.name}</p>
            </Reorder.Item>
            ))} 
          </Reorder.Group>
        </div>
    </div>
  )
}

export default List

**Comment by mattgperry** [comment]
Please reopen with a sandbox example.
