### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TkinterinShanghai** [framer/motion#1707]
## The 0 in the height keyframes does not get accepted
```javascript
const fadeAnimation = {
  show: {
    opacity: [0, 0, 1],
    scale: [0, 0, 1],
    transition: {
      delayChildren: 1,
      duration: 0.5,
      ease: "linear",
      when: "beforeChildren",
    },
    **height: [ --> 0 <--, "auto", "auto"],**
  },
  hide: {
    opacity: 0,
    scale: 0.8,
    height: 0,
    transition: {
      duration: 1,
      ease: "linear",
      when: "beforeChildren",
    },
  },
};
```

## The output is:

``

    Unhandled Runtime Error
    ----> Error: All keyframes must be of the same type <-------------------------------------------------------------------

    Call Stack
    invariant
    node_modules/hey-listen/dist/hey-listen.es.js (11:0)
    eval
    node_modules/framer-motion/dist/es/render/dom/utils/unit-conversion.mjs (146:30)
    Array.forEach
    <anonymous>
    checkAndConvertChangedValueTypes
    node_modules/framer-motion/dist/es/render/dom/utils/unit-conversion.mjs (122:0)
    unitConversion
    node_modules/framer-motion/dist/es/render/dom/utils/unit-conversion.mjs (229:0)
    parseDomVariant
    node_modules/framer-motion/dist/es/render/dom/utils/parse-dom-variant.mjs (12:25)
    makeTargetAnimatable
    node_modules/framer-motion/dist/es/render/html/visual-element.mjs (86:42)
    Object.makeTargetAnimatable
    node_modules/framer-motion/dist/es/render/index.mjs (318:0)
    animateTarget
    node_modules/framer-motion/dist/es/render/utils/animation.mjs (69:88)
    eval
    node_modules/framer-motion/dist/es/render/utils/animation.mjs (37:0)
    animateVariant
    node_modules/framer-motion/dist/es/render/utils/animation.mjs (58:0)
    animateVisualElement
    node_modules/framer-motion/dist/es/render/utils/animation.mjs (15:0)
    eval
    node_modules/framer-motion/dist/es/render/utils/animation-state.mjs (21:102)
    Array.map
    <anonymous>
    eval
    node_modules/framer-motion/dist/es/render/utils/animation-state.mjs (21:0)
    Object.animateChanges
    node_modules/framer-motion/dist/es/render/utils/animation-state.mjs (274:0)
    eval
    node_modules/framer-motion/dist/es/motion/utils/use-visual-element.mjs (36:0)
    commitHookEffectListMount
    node_modules/react-dom/cjs/react-dom.development.js (23150:0)
    commitPassiveMountOnFiber
    node_modules/react-dom/cjs/react-dom.development.js (24926:0)
    commitPassiveMountEffects_complete
    node_modules/react-dom/cjs/react-dom.development.js (24891:0)
    commitPassiveMountEffects_begin
    node_modules/react-dom/cjs/react-dom.development.js (24878:0)
    commitPassiveMountEffects
    node_modules/react-dom/cjs/react-dom.development.js (24866:0)
    flushPassiveEffectsImpl
    node_modules/react-dom/cjs/react-dom.development.js (27039:0)
    flushPassiveEffects
    node_modules/react-dom/cjs/react-dom.development.js (26984:0)
    commitRootImpl
    node_modules/react-dom/cjs/react-dom.development.js (26935:0)
    commitRoot
    node_modules/react-dom/cjs/react-dom.development.js (26682:0)
    performSyncWorkOnRoot
    node_modules/react-dom/cjs/react-dom.development.js (26117:0)
    flushSyncCallbacks
    node_modules/react-dom/cjs/react-dom.development.js (12042:0)
    eval
    node_modules/react-dom/cjs/react-dom.development.js (25651:0)
**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

**Comment by mattgperry** [comment]
Keyframes of different types aren't supported. This may change with a future incorporation of Motion One but even in that case, `auto` won't be supported inside keyframes.
