### ISSUE TITLE
[BUG] CSS transform is being removed after transition/animation

### ISSUE THREAD

**Issue by omerfaran** [framer/motion#1711]
Hello everyone,

I see that my issue is related to this thread: https://github.com/framer/motion/issues/914

In my case, I'm using framer motion to have an animated transition on `left` of `position: absolute`

```
const Handle = styled(motion.div)<{ isOn: boolean; variantColor: string }>(
  ({ isOn, theme, variantColor }) => ({
    top: '50%',
    position: 'absolute',
    left: isOn ? '65%' : '0%',
    transform: 'translateY(-50%)',
    backgroundColor: variantColor,
    borderRadius: 'inherit',
    cursor: 'pointer',
  }),
);
```

This is a toggle that changes the `x` but the `y` should always have ` transform: 'translateY(-50%)',`.
However framer motion will reset it when transition is being applied. My element:

```
        <Handle
          layout
          isOn={isOn}
          transition={spring}
          variantColor={variantColor}
          whileTap={{ scale: 0.95 }}
          onClick={() => setIsOn(!isOn)}
        />
```

I'm sharing a very basic code that demonstrates it:
https://codesandbox.io/s/xenodochial-taussig-14dnlz

Thank you very much in advance!

**4. Steps to reproduce**

1. Click on 'move right' in the sandbox code

**5. Expected behavior**

Y axis shouldn't be changed, only X

**Comment by mattgperry** [comment]
As its performing independent transforms and layout animations these will conflict with externally-created transforms.

You could set `y` to "50%" via the `motion` component's `style` prop.
