### ISSUE TITLE
[Performance issue] How to optimize large list of motion elements. (how to avoid unnecessary rerender?) 

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [framer/motion#1715]
Minimal working example to showcase the problem: https://github.com/Sebastian-Nielsen/card-route-animation

**Problem:** I have a list of motion.div elements, when I click on one of these elements, it is supposed to do an animation. The problem is that all other motion.div elements in the list _unnecessarily_ rerender too! -- which slows down the page _a lot_ when the list gets large.

Using the 'Profiler' dev tools, it is clear that the motion context is the cause of it (to elaborate: whenever I click on one of the elements in the list, all other elements will get rerendered to because of the context):
![image](https://user-images.githubusercontent.com/34586104/192151491-c89b3714-6c46-413f-bb1a-041e0c55e3f4.png)

Here you can see how big of an issue it is:
* 1020 elements loaded (very slow): https://i.gyazo.com/964de68cad2a17821c061c1201b90ad3.mp4

* 20 elements loaded (very fast): https://i.gyazo.com/73451ce8d4f0d88ddcc4b60d9dacada5.mp4

**My question is** how am I supposed to handle this situation?

**Comment by mattgperry** [comment]
Are the items re-rendering siblings? As it seems unlikely these renders will be because of `MotionContext` unless they all share a common `motion` ancestor also doing some changing of variants.

Perhaps you could render each item as a memoized React component that rerenders only when it becomes the active item?

**Comment by mattgperry** [comment]
Please feel free to reopen with further questions/comments if the above suggestion doesn't work for you!
