### ISSUE TITLE
Sequencing API

### ISSUE THREAD

**Issue by mattgperry** [framer/motion#1720]
The main outstanding feature in Framer Motion is a more robust way of orchestrating animations. It'd be great to provide a declarative alternative to Motion One's `timeline` function.

**Comment by nvh** [comment]
RFC: https://paper.dropbox.com/doc/RFC-Timeline-API--Bqeo2i5P_0_uk5Ytrk2KrbhNAg-buQ0wqfXJN1QnMVw0ogJJ

**Comment by sukjae** [comment]
Hello. The above RFC is not accessible. Is there any progress I can check?
