### ISSUE TITLE
[BUG] On Mobile, onClick And Link Navigation doesn't function while items are animating

### ISSUE THREAD

**Issue by ivan-angjelkoski** [framer/motion#1722]
On Mobile, onClick And Link Navigation doesn't function while items are animating,
for example, when children are animation (staggerChildren),the button or link inside the child doesnt work,
and i noticed this bug is only on mobile,on computer it works fine,but on mobile it doesnt,the animation has to finish so i can click it.
if i have 10 children with staggerChildren set to 0.5, i need to wait 10 seconds and then i can click the button or link.

Here is a sandbox with the example:
https://codesandbox.io/s/framer-motion-bug-q4gzsb

also here is the website i made that i noticed the bug on.
https://rickandmortyexplorer.netlify.app/

and you can't click on the characters while they are animating ( ON MOBILE! )

**Comment by stivenm16** [comment]
any update? same issue

**Comment by kms113** [comment]
same too

**Comment by Alexandredc** [comment]
Same  !

**Comment by mattgperry** [comment]
Closing as sandbox doesn't reproduce stated bug

**Comment by MAHKdev** [comment]
Kindly reopen. this is not the same as issue as other linked ones.
