### ISSUE TITLE
[BUG] Shared layout animations don't work fully with multiple React roots

### ISSUE THREAD

**Issue by rchrd2** [framer/motion#1726]
**2. Describe the bug**

Some applications aren't developed as one monolithic React tree, but rather multiple React roots on the page. 

My team found that `transition` is partially working with multiple React roots. But it only works depending on the order they are rendered on the page. Eg it only animates to a target if the previous location was rendered before the target. We verified that the order the roots are rendered is the cause, by reversing the order, and observing the behavior in reverse.

I understand this is an unusual case, but multiple React can be a common pattern for legacy applications that did not start as a monolithic React app. Showing that it can work in one direction gives me hope that the library could be modified to also work in the previous direction.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Code sandbox: https://codesandbox.io/s/hungry-panka-cfdeog?file=/src/index.js

**4. Steps to reproduce**

1. Go to https://codesandbox.io/s/hungry-panka-cfdeog?file=/src/index.js
2. Click on the `<button>` element with the words "Switch" (you can click any button).
3. If you click a button that is lower, it transitions to it with animation. 
4. If you click a button that is higher, it just jumps to it.

**5. Expected behavior**

It should transition between all roots, regardless of if it was initialized before or after another root.

**6. Video or screenshots**

Demo video
https://user-images.githubusercontent.com/182479/193953610-7046ed6a-fa71-4c26-9409-53e64591760e.mov

In the video you can see that it correctly animates to the a React root that was initialized after the previous one. However, if you try to transition to a React root that was initialized before the previous one, it does not animate, it simply changes instantly.

**Comment by mattgperry** [comment]
I'll take a deeper look into it at some point but I suspect this is a wontfix. It's a miracle that they work as much as they are, and not intended. Layout animations work closely with the React render cycle and when there's multiple roots this becomes very unpredictable, making it hard to read/write layout in the synchronous way needed to pull these animations off.
