### ISSUE TITLE
[FEATURE] drag the Reorder.Item after a long press

### ISSUE THREAD

**Issue by MarwenLabidi** [framer/motion#1731]
**Is your feature request related to a problem? Please describe.**
I would like to **drag** the Reorder.Item after **a long press.** It would be nice if If you can **specify the amount of time** before you start dragging

**Comment by ArjanJ** [comment]
This would be great. It would probably solve the mobile issues where drag and scroll happen at the same time.

**Comment by mattgperry** [comment]
I like the idea though closing as a `wontfix` as this will probably only be implemented if we find a use for it in Framer.
