### ISSUE TITLE
[BUG] SVG rect X/Y sets translateX/translateY, not x/y attributes

### ISSUE THREAD

**Issue by alexlouden** [framer/motion#1733]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

Give a clear and concise description of what the bug is.

Setting an SVG rect's x/y values to a motion value sets the translateX/translateY styles, not the positional attributes as per the documentation. See previous bug report (or related?): https://github.com/framer/motion/issues/384

Two line repro:
```js
const y = useMotionValue(10);
<motion.rect style={{ y }} />
```
Renders this:
```html
<rect style="transform: translateY(10px);"></rect>
```

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

https://codesandbox.io/s/priceless-snowflake-xf2i00?file=/src/App.js

Sandbox shows why the difference between using the attribute and the translateX/translateY behaviour is important - when the rect has a clip path (amongst other use cases!)

**4. Steps to reproduce**

1. Go to CodeSandbox above
2. Blue rect should be half hidden by the clip-path, like the red one below.
3. See in HTML that blue rect has `style="transform: translateX(25px);"` set, instead of `x="25px"`

**5. Expected behavior**

Setting the `x`/`y` attribute

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

**7. Environment details**

Tested with framer-motion@7.5.3

**Comment by mattgperry** [comment]
Ah this is a problem with the docs that I'll update but you can set these via `attrX` and `attrY`

**Comment by mattgperry** [comment]
Updated the docs so closing this out

**Comment by alexlouden** [comment]
Ahh, great - thank you!
