### ISSUE TITLE
R3F: (SomeElement) is not part of the THREE namespace! [BUG]

### ISSUE THREAD

**Issue by hedonicadapter** [framer/motion#1735]
Three.js elements throw an exception inside MotionCanvas--"R3F: (element) is not part of the THREE namespace! Did you forget to extend? See: https://docs.pmnd.rs/react-three-fiber/api/objects#using-3rd-party-objects-declaratively".

repro: https://codesandbox.io/s/stupefied-cannon-g3ri9y?file=/src/App.js

Add any(?) three JSX element to a MotionCanvas parent. The codesandbox is blank sometimes, so you might have to refresh.

![image](https://user-images.githubusercontent.com/63095356/195574714-61a3a9af-d18f-4680-9639-813a4f5ad78a.png)

**Comment by hedonicadapter** [comment]
> Did you forget to extend?

oh my bad, I missed the extend() function, thanks

**Comment by TheBigSasha** [comment]
What exactly needs to be extended for this to work? I continue to get this error when I use `<MotionCanvas>` but when I use `<Canvas>` everything works fine. I have tried extending like this: `import { motion as motion3d, MotionCanvas } from 'framer-motion-3d';

extend({ MotionCanvas, motion3d });
`

Using latest framer-motion and matching framer-motion-3d

**Comment by thejzain** [comment]
Yup same issue here too

`Unhandled Runtime Error
Error: R3F: Mesh is not part of the THREE namespace! Did you forget to extend? See: https://docs.pmnd.rs/react-three-fiber/api/objects#using-3rd-party-objects-declaratively`

**Comment by FranciscoRSilva** [comment]
> Yup same issue here too
> 
> `Unhandled Runtime Error Error: R3F: Mesh is not part of the THREE namespace! Did you forget to extend? See: https://docs.pmnd.rs/react-three-fiber/api/objects#using-3rd-party-objects-declaratively`

Did you manage to fix it ?

**Comment by TheBigSasha** [comment]
> > Yup same issue here too
> > `Unhandled Runtime Error Error: R3F: Mesh is not part of the THREE namespace! Did you forget to extend? See: https://docs.pmnd.rs/react-three-fiber/api/objects#using-3rd-party-objects-declaratively`
> 
> Did you manage to fix it ?

I managed to get past this in my project by wrapping Framer Motion's motion values with RXJS observables and using the observables to animate the scene, bypassing Framer Motion 3d.

**Comment by dev-aly3n** [comment]
same issue with  `import { motion as motion3d, MotionCanvas } from 'framer-motion-3d';`
