### ISSUE TITLE
[BUG] chakra v1.8.8 didn't work with framer-motion version 5 and above

### ISSUE THREAD

**Issue by zaherkassem** [framer/motion#1736]
I want to use framer-motion version 6  with chakra v1.8.8 for 2 reasone:

1. my project build in react v17 and i can't upgrade right now to v18 , so i can't also upgrade chakra-ui  to v2
2. i want to use ReOrder from motion that not found in v4 
3.  when i install motion v5 or v6 some of chakra-ui components are broken

**Comment by calvinf** [comment]
I'm using framer-motion 6.5.1 with Chakra 1.8.8 and it's been working well for our project.

@zaherkassem What components have been breaking for you?

**Comment by mattgperry** [comment]
Sorry this sounds like something outside our control - I would upgrade to React 18 in any case.
