### ISSUE TITLE
[BUG] Typescript module framer-motion declares CycleState locally, but it is not exported

### ISSUE THREAD

**Issue by selvinkuik** [framer/motion#1737]
**Describe the bug**

When using Typescript, and passing useCycle around in a React context, the type definition for CycleState is not accessible.

**Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/eloquent-bird-f7pli7?file=/src/App.tsx

**Expected behavior**

I should be able to create an interface with useCycle as follows:

```
interface GlobalContextProps {
  mainNavigationIsOpen: boolean;
  setMainNavigationIsOpen: CycleState<boolean>;
}
```

**Comment by mattgperry** [comment]
Published in `7.6.1`
