### ISSUE TITLE
[BUG] Text jumping when an animation is exiting

### ISSUE THREAD

**Issue by himanshunegi378** [framer/motion#1739]
**2. Describe the bug**

When I open and close the accordion, the closed text of other accordions make sudden jump.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/flamboyant-fast-w6qtdg?file=/src/App.js

**4. Steps to reproduce**
1. Click on section 1.
2. wait for the content
3. click on section 1
4. observe the closed text of other accordions jump

**5. Expected behavior**

smooth transition between closed text and content

**7. Environment details**

Windows 10

**Comment by mattgperry** [comment]
On line 618 you have padding set on the container, which you're also animating to `height: 0`. But it will still take up height because of the padding. Remove the padding to fix.

**Comment by himanshunegi378** [comment]
Sorry @mattgperry, I made some changes to the code so the actual behavior which I filed was not present in the sandbox. I have reverted the sandbox, so now it have the initially mentioned behavior.
video of the issue:
[2022-10-18 15-35-16.webm](https://user-images.githubusercontent.com/20705560/196402266-839bc1d4-ba32-4525-a15d-f2e8f1e29805.webm)
