### ISSUE TITLE
[BUG] Animating sibling widths with different values from 0 -> width causes narrow sibling to animate too far

### ISSUE THREAD

**Issue by dxu** [framer/motion#1740]
When you have two sibling elements, with different width values, animating one from `0 -> WIDTH_NARROWER`, and the other from `WIDTH_LARGER -> 0`, the narrow sibling animates from `0 -> WIDTH_LARGER` instead of from their own width. 

[Here is a sandbox link](https://codesandbox.io/s/busy-greider-7jgzft?file=/src/styles.css) with a minimal repro. 

Here is a video of what happens: 

https://user-images.githubusercontent.com/718423/197330229-bed80a95-f4ff-4cce-9c50-93fc4ed66dc3.mp4

**Comment by mattgperry** [comment]
It's possible that as these are animating with different unit types when the elements are measured something about the setup of this page means the dimensions aren't as you expect.
