### ISSUE TITLE
[BUG] Demo for #shared-layout-animations is buggy

### ISSUE THREAD

**Issue by hfossli-agens** [framer/motion#1746]
The item in the selected tab may sometimes wrongfully disappear.
https://www.framer.com/docs/layout-animations/#shared-layout-animations 

**CodeSandbox**
https://codesandbox.io/s/framer-motion-layout-animations-snxgv?from-embed

**Steps to reproduce**
Click back and forth between the tabs in various tempo

**Expected behavior**
The selected item should always be visible

**Video or screenshots**
https://user-images.githubusercontent.com/395012/199190697-1a76b38c-acb5-4115-a184-62c643afcbc9.mp4

**Environment details**
Brave Version 1.44.112 Chromium: 106.0.5249.119 (arm64)
macOS 12.6 (21G115)
M1

**Comment by mattgperry** [comment]
I've upgraded the demo so it shouldn't happen any more.
