### ISSUE TITLE
Gracefull fallback for scroll triggered animations if javascript is disabled

### ISSUE THREAD

**Issue by pc-erin** [framer/motion#1752]
**Is your feature request related to a problem? Please describe.**
We've been using the scroll-triggered animations to essentially do [AOS](https://michalsnik.github.io/aos/) effects on page items. The problem is that if JS is disabled in the browser, everything remains invisible.
For reference the props we're applying look like this:
```ts
{
  initial: { opacity: 0 },
  whileInView: { opacity: 1 },
  transition: { duration: 0.7, ease: [0.25, 0.1, 0.25, 1] },
  viewport: { once: true },
}
```

**Describe the solution you'd like**
Is there any way to do scroll-triggered animations that won't hide everything in case JS is disabled? We're using Next and were hoping to use server rendering to ensure a good experience even for users without JS.

**Describe alternatives you've considered**
Maybe we could implement these using classes and add a stylesheet inside a noscript tag that cancels out the classes. I noticed the `initial` and `whileInView` props allow `className` to be used as a property, but don't appear to apply it.

**Comment by mattgperry** [comment]
Hey @pc-erin 

I think if we tackle this it will probably be as a feature for Framer rather than something we put into Framer Motion. It's not ideal but you can still override each CSS style using `!important`.
