### ISSUE TITLE
[BUG] AnimatePresence change order of useEffect and cleanup function

### ISSUE THREAD

**Issue by SwimmingPolar** [framer/motion#1772]
This may not be bug just want to clarify. To my knowledge, useEffect or useLayoutEffect will be executed in order they are called or declared. When using <AnimatePresence> this orders change. Say, there are two components. Something like this

<AnimatePresence>
  show && <CustomMotionComponent key=1 ... >
  !show && <CustomMotionComponent key=2 ...>
</AnimatePresence>

In situation where I toggle 'show' button on and off. I expect first component with the key value 1 to execute
useEffect and clenaup then second component's useEffect (not cleanup yet). but I see different result and
just realized this is what was causing me unexpected bugs. Is this expected behaviour of AnimatePresence?
With mode prop set to "wait", it works as expected but that's not what I want so, looking for any workaround or should I change whole code structure?

expectation:
inside first component's useEffect
inside first component's cleanup function
inside second component's useEffect

results:
inside first component's useEffect
inside second component's useEffect
inside first component's cleanup function

Reproduction:
https://codesandbox.io/p/sandbox/hungry-goldberg-2e8z7s

**Comment by paales** [comment]
This is expected behavior, while transitioning between the two different states both of the components are rendered. After the animation is complete, the first component is cleaned up.
