### ISSUE TITLE
animate max width [FEATURE]

### ISSUE THREAD

**Issue by loh-aivy** [framer/motion#1785]
**Is your feature request related to a problem? Please describe.**
I want to animate max width.

**Describe the solution you'd like**
`style={{ maxWidth: 512 }} && controls.start({ maxWidth: 256 })`

**Describe alternatives you've considered**
using percentage (`style={{ width: '80%' }} && controls.start({ width: '40%' })`) is possible.

best regards

**Comment by mattgperry** [comment]
You can. If it isn't working please reopen with a sandbox link. But double check that changing `max-width` yourself works as you'd expect, because this is supported in Framer Motion.
