### ISSUE TITLE
[FEATURE] i thinking we need 'custom data mutiples' 

### ISSUE THREAD

**Issue by synasapmob** [framer/motion#1799]
the first i want sent thanks to every `contributors/developers at framer-motion`,
sorry but i don't see posts related custom data mutiples?,
detail am doing makes an variant can inheritance for every element in my component,

from document `framer motion` 'photo below' just once parameter for ` 'delay: custom * 2'`

but i want `get second/third? parameters` 

sorry for my bad english
thanks everybody! .

**my variant**

![Screen Shot 2022-11-30 at 16 29 24](https://user-images.githubusercontent.com/42969529/204758832-0e5ce9c8-2dbc-4f27-8b7f-280936d93d26.png)

**my props**

![Screen Shot 2022-11-30 at 16 29 44](https://user-images.githubusercontent.com/42969529/204758905-cf46b396-da03-4964-a008-e5e1198297f7.png)

[https://www.framer.com/docs/component/](url)

![Screen Shot 2022-11-30 at 16 15 15](https://user-images.githubusercontent.com/42969529/204755638-3a915eab-98b1-4c9f-a2f7-cddf127f375b.png)

**Comment by mattgperry** [comment]
You can pass extra info through via the first argument with an array or object

```
<motion.div custom={[a, b, c]} />
```
