### ISSUE TITLE
[FEATURE] React Native Support

### ISSUE THREAD

**Issue by chrisdrackett** [framer/motion#180]
**Is your feature request related to a problem? Please describe.**
Can't currently use with react native components

**Describe the solution you'd like**
support for react-native (`motion.View`?)

**Describe alternatives you've considered**
I haven't dug much into if this is even possible atm.

**Comment by amannn** [comment]
I guess one of the main challenges is that in `react-native` animations don't run on the JS thread, but are only _described_ there. The animation itself is handled in native code, as it would be too expensive to send animation instructions over the bridge with 60FPS.

An example that shows the difference well is interpolations.

`react-native` using the [`Animated` API](https://facebook.github.io/react-native/docs/animations#interpolation):

```
const y = x.interpolate({
  inputRange: [0, 1],
  outputRange: [0, 2],
});
```

In Framer Motion, animations run on the JS main thread and therefore you can interpolate freely with [`useTransform`](https://www.framer.com/api/motion/motionvalue/#usetransform):

```
const y = useTransform(x, value => value * 2)
```

For such calculations you'd have to use a [separate API](https://facebook.github.io/react-native/docs/animated#combining-animated-values) from `react-native`. There's the `react-native-reanimated` project, but as far as I know they use the [same architecture](https://github.com/kmagiera/react-native-reanimated#animatedcode).

There might be other areas where this difference in architecture makes a big difference. Maybe it could work to only support a subset of the Framer Motion API, but you'd have to implement the transitions in native code.

**Comment by nicksmithr** [comment]
Yes please. In the meantime, will pose for React Native be kept alive @InventingWithMonster ?

**Comment by skoshy** [comment]
[Pose by Popmotion](https://popmotion.io/pose/learn/native-get-started/) supported react-native, maybe it can be a source of inspiration?

**Comment by chrisdrackett** [comment]
I'd be ok with a subset myself, this is the current constraint I live with using pose on native and web (our app is universal and uses react-native-web).

**Comment by InventingWithMonster** [comment]
@nicksmithr Yeah I won't be deleting anything but I might offer it to the community to take over.

@amannn Motion was built largely with this kind of thing in mind. So useTransform's first syntax was the array-based interpolation, the function only came after I realised I was being too strict about this. 

I'm also interested in getting to a place where we can pre-calculate frames using Popmotion and then pass those to the WebAnimations API. This will further push the architecture to a place that will be good for Native support.

There's places where Motion interacts quite closely with the DOM, forcing renders and what-not. So we'd have to address those.

With a subset of functionality I think this is quite doable, but we need to gauge interest from the Framer X community. Stuff like this issue helps - if people are interested, give it a thumbs up.

**Comment by amannn** [comment]
> So useTransform's first syntax was the array-based interpolation, the function only came after I realised I was being too strict about this.

I'm really glad that you allow for a custom function in `useTransform`. The first attempt at [my last animation prototype](https://amannn.github.io/friends-ui/) has used Animated for web and it was pretty tricky to get the bubbles moving in a circular shape at the right spot with a [complicated interpolation](https://github.com/amannn/friends-ui/commit/3fab23813b8b211f61bf330d5b8eec06a818f449#diff-d47b22c9552f645e7eb72914f017deeeL129). When I moved to RxJS that was much easier, as I could do proper math there for the movement. I'm really glad that Framer Motion is "web first" in that regard and doesn't limit you there!

> I'm also interested in getting to a place where we can pre-calculate frames using Popmotion and then pass those to the WebAnimations API. This will further push the architecture to a place that will be good for Native support.

That sounds pretty interesting to me. I didn't know this is possible!

**Comment by viktorrenkema** [comment]
[@eberdotjs](https://twitter.com/eberdotjs/status/1166003047148982272) is also interested in React Native support :)

**Comment by viktorrenkema** [comment]
[+1 Lennart](https://twitter.com/brandtnewww/status/1183793938802630658)
[+1 Travis](https://twitter.com/souporserious/status/1183794922886856710)

**Comment by matthewbal** [comment]
+1 keen for react native support if possible

**Comment by Prattjames** [comment]
This could be really great!

**Comment by tomfloresa** [comment]
+1 

Would be grate and much appreciated.

**Comment by crsanthony** [comment]
+1000 please and thank you!

**Comment by KristofferEriksson** [comment]
This could be great!

**Comment by jsheffers** [comment]
Agreed!

**Comment by matthewdias** [comment]
Please don't send +1 comments. You can thumbs up the issue without spamming subscribers.

**Comment by OctavioTosta** [comment]
Please, @InventingWithMonster , do this! We need Framer on React Native.

**Comment by alan-oliv** [comment]
+1

**Comment by juriuschakow** [comment]
This would be briliant!!

**Comment by flacito** [comment]
+1   I _depend_ on React Native Pose for _easy_ to implement, _delightful_ menu effects.   Please provide Framer on React Native.

**Comment by imranhassan87** [comment]
+1

**Comment by paul-bg** [comment]
This will be amazing!!!!

**Comment by paul-bg** [comment]
+1

**Comment by simpleshadow** [comment]
+1!

**Comment by lucasnantonio** [comment]
+1

**Comment by sorakthunly** [comment]
This will be really awesome. Please! +1

**Comment by acerbastimur** [comment]
+1

**Comment by therealadum** [comment]
> I guess one of the main challenges is that in `react-native` animations don't run on the JS thread, but are only _described_ there. The animation itself is handled in native code, as it would be too expensive to send animation instructions over the bridge with 60FPS.
> 
> An example that shows the difference well is interpolations.
> 
> `react-native` using the [`Animated` API](https://facebook.github.io/react-native/docs/animations#interpolation):
> 
> ```
> const y = x.interpolate({
>   inputRange: [0, 1],
>   outputRange: [0, 2],
> });
> ```
> 
> In Framer Motion, animations run on the JS main thread and therefore you can interpolate freely with [`useTransform`](https://www.framer.com/api/motion/motionvalue/#usetransform):
> 
> ```
> const y = useTransform(x, value => value * 2)
> ```
> 
> For such calculations you'd have to use a [separate API](https://facebook.github.io/react-native/docs/animated#combining-animated-values) from `react-native`. There's the `react-native-reanimated` project, but as far as I know they use the [same architecture](https://github.com/kmagiera/react-native-reanimated#animatedcode).
> 
> There might be other areas where this difference in architecture makes a big difference. Maybe it could work to only support a subset of the Framer Motion API, but you'd have to implement the transitions in native code.

While this may not be a popular answer, it might be wise to monitor the RN 2020/2021 roadmap and wait until the bridge is removed. Once the framework is rearchitected 60fps is definitely possible (imo) for running complicated animations (like interpolation) on the JS thread and synchronously communicating that to the native ui/modules.

**Comment by flacito** [comment]
@therealadum, great analysis.  “Maybe it could work to only support a subset...”.  Small starts that have meaningful functionality are a great. I use pose to just move buttons in and out for a little sizzle to my UI.  Its so simple and so effective.  Would an initial subset include something like this?

**Comment by stevejboyer** [comment]
Another +1 here!

**Comment by 0xe9f** [comment]
+1 🚀

**Comment by data987** [comment]
+1 Here!!

**Comment by stewwan** [comment]
+1

**Comment by dentuzhik** [comment]
Guys, as mentioned in the comment above reactions like `+1` are perfectly achievable with reactions on PRs. I think everybody here understands that it's a desired feature. 
https://github.com/framer/motion/issues/180#issuecomment-577357562

So, unless you have some value to bring into discussion of the issue, please refrain from spamming other people, who follow this issue with GH notifications interface 🙇 

Disclaimer, I am NOT a maintainer of Framer, but this is generally adopted good practice in open source.
Let's respect other people in the community.

Thank you.

**Comment by ODINA101** [comment]
+1

**Comment by EhsanSarshar** [comment]
I think using `react-native-reanimated` and `react-native-gesture-handler` will tackle the issue of 60fps  animations in `react native` and it will be perfect to combine it with framer motion

**Comment by anzorb** [comment]
Folks, framer motion (and previously pose) is far superior to anything out there for react / react native animations. For those who want to build beautiful apps that aren't just stack, tabs, and other rigid transitions (with react-native-animation), we're stuck writing hundreds of lines of code instead of just defining some variants and using enter/exit transitions with Pose group/animatePresense. I'd love to see framer motion supported to the same degree as pose on RN but also with animatePresence so we can transitions between "pages" in a beautiful way. Massive +1. Thanks for all your work!

**Comment by ganySA** [comment]
Just wondering if there is now a solution for motion.View?
The last version of Posed does not work with the latest react.

**Comment by asim47** [comment]
+1

**Comment by marlonsecundo** [comment]
+1

**Comment by EhsanSarshar** [comment]
`react-native-reanimated@2-alpha` is using JSI. so it's performant to start a react-native-framer base on that and we can finally achive the first release

**Comment by Faisal-Manzer** [comment]
Any updates on the first release? I guess this would go great.

**Comment by ptrobert** [comment]
+1

**Comment by kevinrodriguez-io** [comment]
When is this going to happen?

**Comment by tsalemy** [comment]
Would be happy to help to make this happen.... I would prefer Swift but react-native probably more applicable for a broader community

**Comment by nandorojo** [comment]
Echoing what @EhsanSarshar said, Reanimated 2.0's JS-based animation API would be pretty ideal for this.

**Comment by tsalemy** [comment]
I'd have to disagree. You should go a more native route than relying on an existing platform that constantly changes and honestly in my opinion becomes obsolete once Framer finds a way to automatically export builds of the apps created in these high fidelity prototypes. I think that you integrate with react-native through another driver layer, but ultimately build the core functionality such that it transcends frameworks and applicable across native, web, and any other future platform. ie use javascript if you may, but think strongly about using the most native language you can implement in

**Comment by nandorojo** [comment]
@tsalemy That's a good point. Reanimated is just miles ahead of any universal animation solution for React Native at the moment. But if the bandwidth exists for a first-principles approach that's as close to native as possible, it could be better than relying on Reanimated.

**Comment by tsalemy** [comment]
agreed -- I honestly think if I'm framer looking through this comment thread, it's clear the #1 driver of the business and community will be automatically connecting designs + animation to any app across multiple platforms, automatically building experiences akin to Unreal Engine (which is far far more complex so confused why design platforms haven't accomplished this) and leverage the typescript interfaces they're already using to represent the information that gets piped into each view through a RESTful service or whatever you're using

**Comment by nandorojo** [comment]
Just note that Shopify (& many others) contribute to Reanimated. While it's perhaps not ideal to rely on a separate library with its own API, I think it's worth noting that Reanimated has a particularly strong presence in the React Native community.

**Comment by tsalemy** [comment]
Agreed I just personally think react native 5 years from now goes away if Framer develops this type of tech. just think about the power that opens up for designers and the engineering community in general if we take away all the cruft and go with an opinionated, first-principles language that automates the develop + build process after handoff. so many companies are failing to tackle this w/ the right approach. Framer is the #1 app to handle this properly

**Comment by tsalemy** [comment]
javascript no matter what way you put it is inferior in performance due to its design. it was built for simplicity. which has been fantastic for unlocking innovation to date. but do you really need simplicity if it's automatically generated + exported code + built by Framer? probably not, and if you do, probably can hire someone to dive through Rust/etc. whatever you end up using.

**Comment by hadnet** [comment]
I'm familiar with Framer since ver x21. Honestly I don't know which one is miles ahead of something... whether is Framer with the possibility of exporting a build or Reanimated with a universal animation solution..

**Comment by csemur** [comment]
+1

**Comment by InventingWithMonster** [comment]
As an update it's unlikely that this is going to happen any time soon. There seems to be a general lack of enthusiasm when I've brought it up. Reanimated 2 looks great though and would certainly bring the idea closer to the realm of achievability.

**Comment by nandorojo** [comment]
I think it would be a great move to use Reanimated 2 here for native.

**Comment by hairarrow** [comment]
I'm in a place where I'd love to use Framer to maintain production animations on web and native, but I'm currently transforming everything with Reanimated 2 on RN.

I would be open to helping out with a `native-motion` project, or at the very least try to get support for `<motion.View />`. I was hoping to write a transformer for my Framer animations to make them compatible with `react-native-pose`, but I have a couple scroll based animations that need to be offloaded to the UI thread and require Reanimated.

**Comment by VrTech** [comment]
Please make this happened

**Comment by matdocker** [comment]
+1

**Comment by geraldcells18** [comment]
Waiting...

**Comment by robrecord** [comment]
> As an update it's unlikely that this is going to happen any time soon. There seems to be a general lack of enthusiasm when I've brought it up. Reanimated 2 looks great though and would certainly bring the idea closer to the realm of achievability.

Currently the promise of Framer is broken when building React Native apps. If Framer Motion could support react Native it would open up a world of possibility for seamless mobile prototyping and development. I don't understand why there would possibly be a lack of enthusiasm (and by whom)?

**Comment by hadnet** [comment]
The huge advantage if FM supports RN would be a seamless animation prototyping/development on both realms: web and mobile. Learn once, run on both!

**Comment by EhsanSarshar** [comment]
I think reanimated 2 is enough it's easy and you can implement any sort of animations with it. sometimes abstraction avoid creativity. that's what I believe and I am agree if most of you unlike it.

**Comment by gruckionvit** [comment]
Im in the process of setting up the architecture for a long running project. Currently considering react native web and animation libraries. It would be amazing to have a motion library that works on both react and native.

**Comment by nandorojo** [comment]
I've been working on a framer-motion-like library for React Native. You can follow along on Twitter if you'd like to use it when it's out: https://twitter.com/FernandoTheRojo/status/1351234878902333445?s=20

@mattgperry gave me a hand getting `AnimatePresence` support to work. 

And yes, it's built with Reanimated 2 under the hood.

**Comment by mattgperry** [comment]
Moti looks like an excellent Native-compatible alternative. I don't think Reanimated 2 is "there" yet for us to jump on it, and Native support won't be on our roadmap for the foreseeable future so I'm closing this in the meantime.

**Comment by codinsonn** [comment]
> Im in the process of setting up the architecture for a long running project. Currently considering react native web and animation libraries. It would be amazing to have a motion library that works on both react and native.

Have a look at react-spring or @nandorojo's moti, they work cross platform

**Comment by ortonomy** [comment]
@mattgperry - sad that it's not on your roadmap. Appreciate `Moti` is essentially recreating Framer Motion for React Native, but would love to have used FM in React Native... oh well. Thanks for being honest.

**Comment by danflynndesign** [comment]
Would really love support for React Native! This would greatly help our design/dev handoff and collaboration for our app

**Comment by Mi3liX9** [comment]
I wish we could use FM with Chakra UI with RN :)

**Comment by NilsBaumgartner1994** [comment]
+1

**Comment by NilsBaumgartner1994** [comment]
> @Mi3liX9 tem o native base, é igual ao chakra UI - https://nativebase.io/

Englisch please ?

**Comment by kevinrodriguez-io** [comment]
Just use Nandorojo's Moti. Feature parity and very well maintained.

**Comment by Brunowilliang** [comment]
@NilsBaumgartner1994 and @Mi3liX9 has native base, it's the same as chakra ui... - https://nativebase.io/

**Comment by Alireza17224** [comment]
+1

**Comment by sayan-avantai** [comment]
Currently using react-native-animatable but waiting for framer
