### ISSUE TITLE
[FEATURE] GPU animations

### ISSUE THREAD

**Issue by mattgperry** [framer/motion#1806]
Start introducing WAAPI animations for select values, perhaps starting with opacity

**Comment by finkrer** [comment]
Hey @mattgperry, thanks for this change! Do I understand correctly that only opacity is animated using WAAPI in the latest version?

I've noticed that framer animations were noticeably slow in Safari, and found this update. In the new version, opacity animations work great! But transforms are still done using styles, right? Can't wait to use `layoutId` animations in my project, but last time I checked they were too slow for production unfortunately, at least in my case.

**Comment by mattgperry** [comment]
Hi there - yeah it’s just opacity for now. I’ll be looking at other values but transform is one of the least likely as layout animations require per-frame javascript. It’s be interesting to see what your perf issues are in a sandbox though
