### ISSUE TITLE
[FEATURE] Passthrough props when using AnimatePresence

### ISSUE THREAD

**Issue by AndriesVDW** [framer/motion#1813]
**Is your feature request related to a problem? Please describe.**
Sometime I pass down a prop from a parent to a child using `cloneElement`.
For example, when `Card` is a child of `GridItem`, the `Card` will have an extra class `in-grid` given to it by `GridItem`:

```
<GridItem>
    <Card />
</GridItem>
```

Which produces the following HTML:
```
<div class="grid-item">
    <div class="card in-grid"></div>
</div>
```

Now I'd like to animate the card:
```
<GridItem>
    <AnimatePresence>
         <Card />
    </AnimatePresence>
</GridItem>
```

This works, except my `in-grid` class is now passed down to `AnimatePresence` which ignores it.

**Describe the solution you'd like**
It'd be nice if props passed down to `AnimatePresence` could be passed down to their children.

**Comment by mattgperry** [comment]
I think as there's a way of fixing this in userland we probably won't add this in just for `cloneElement` usage.
