### ISSUE TITLE
An issue with useScroll({container}) option. Any advice?

### ISSUE THREAD

**Issue by olehkhalin** [framer/motion#1819]
Hello, I have a particular issue with useScroll({container}) option.
If you are on a child component and you want to track its scroll progress based on a container ref that it's from the parent component, it will not trigger any value change. 
I tried passing the parent ref as a prop or getting the div with getElementById but it didn't work.
I have a list of Card that should parallax but are contained into a scrolling div instead window.

_Originally posted by @liqueflies in https://github.com/framer/motion/issues/646#issuecomment-1304846737_

**Comment by mattgperry** [comment]
Please reopen with a sandbox example

**Comment by dominikseger** [comment]
Same problem here. 
@olehkhalin Did you solve this?
