### ISSUE TITLE
[FEATURE] adding `onStart` and `onComplete` callbacks to `useMotionValue`

### ISSUE THREAD

**Issue by kuus** [framer/motion#1824]
**Is your feature request related to a problem? Please describe.**
I would like to know if there is any intention or anything against adding an `onStart` and `onComplete` callbacks to `useMotionValue`, the use case is simply to be able to use a callback (maybe from a parent component) when the animation starts/ends. Another usecase is to set some styles depending on the current state of the animation. I know all of this is possible with the `animate` property of the `<m.{component} />` but it would be good I think being able to achieve the same as `onAnimationStart` and `onAnimationComplete` props with the "render-less" approach allowed by `useMotionValue`.

**Describe the solution you'd like**
From an API point of view I imagine this usage:
```
const marginValue = useMotionValue(0, {
  onStart: () => someRef.current && someRef.current.style.overflow = "hidden",
  onComplete: () => someRef.current && someRef.current.style.overflow = "auto",
);
```

**Comment by mattgperry** [comment]
This is implemented, great suggestion https://twitter.com/mattgperry/status/1603371303775379456
