### ISSUE TITLE
[BUG] Layout animation scroll jumping elements

### ISSUE THREAD

**Issue by VictorPulzz** [framer/motion#1828]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
I make a switcher and when I scroll the page, and then do the switch, the inner element jumps (apparently framer motion does not recalculate the position of the element when scrolling)

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
Simple example code:
```js
export const Switcher: FC<SwitcherProps> = ({ list, value, onToggle }) => {
  return (
    <div
      role="button"
      className={styles.container}
      data-toggle={value === list[0]}
      onClick={() => onToggle(value === list[0] ? list[1] : list[0])}
    >
      <motion.div
        layout
        transition={{
          type: 'spring',
          stiffness: 700,
          damping: 40,
        }}
        className={styles.toggle}
      />
    </div>
  );
};
```
https://codesandbox.io/s/framer-motion-bug-layout-animation-scroll-tlgx2e

**4. Steps to reproduce**
1 - Just check codesanbox,
2 - Scroll inside panel
3 - Click by switcher
**5. Expected behavior**
No bug

**6. Video or screenshots**

<img width="83" alt="image" src="https://user-images.githubusercontent.com/23406402/207551092-00ce18b0-ca1a-4cce-bb26-50641bd15de4.png">
Got same error in my website
<img width="70" alt="image" src="https://user-images.githubusercontent.com/23406402/207551169-b62f5fce-c3dc-41c4-bd56-9b2a709f6b9a.png">

**7. Environment details**
"react": "18.2.0",
"react-dom": "18.2.0",
"framer-motion": "^7.0.0",

**Comment by mattgperry** [comment]
Please reopen with a sandbox using the latest version of `framer-motion`
