### ISSUE TITLE
[DOCS] position transtions linking to wrong sandbox

### ISSUE THREAD

**Issue by madou** [framer/motion#183]
Hi! Cool library, great design 😎 

https://www.framer.com/api/motion/examples/
https://github.com/framer/api-docs/blob/master/pages/motion/examples.mdx

Position transitions codesandbox link is pointing to https://codesandbox.io/s/framer-motion-drag-with-constraints-pjn6t?fontsize=14&module=%2Fsrc%2FExample.tsx instead of the expected one.

edit: you're even using the brand colours for your labels! too good 😄

**Comment by InventingWithMonster** [comment]
Thanks for pointing this out - there's a fix going out
