### ISSUE TITLE
Add possibility to add new children after initial `staggerChildren` animation

### ISSUE THREAD

**Issue by TS-Tobias** [framer/motion#1836]
Right now, it is not possible to add new elements to a `staggerChildren` container.
New elements added to a `staggerChildren` container will not be animated in since the children cannot have an animate property (due to the way `staggerChildren` works).

So, if a new child element has an initial opacity of zero, it will never become visible, because there is no way of adding an `animate` property to children of a `staggerChildren` container without breaking the stagger animation.

This is not the first time I have struggled with this limitation, and I am unable to work my way around it. If there is a way to do this, it should be added to the documentation.

**Comment by mattgperry** [comment]
Dupe of https://github.com/framer/motion/issues/776
