### ISSUE TITLE
[BUG] Stop scrolling from interfering with dragging

### ISSUE THREAD

**Issue by danprince** [framer/motion#185]
**Is your feature request related to a problem? Please describe.**
If you render a list of `drag="x"` components and try to scroll down on a touch device, a small amount of horizontal drag happens on each element that your finger touches.

**Describe the solution you'd like**
A generic solution could be to allow the variant styles to override the styles from the drag.

```tsx
let variants = {
  // this would override whatever x value the drag gesture is providing
  static: { x: 0 },
  swiping: { },
};

let Swipeable = () => {
  let [isSwiping, setIsSwiping] = useState(0);

  let onDrag = (event, info) => setIsSwiping(info.offset.x > 10);

  return (
    <motion.div drag="x" animate={isSwiping ? "swiping" : "static"} onDrag={onDrag} />
  );
}
```

**Describe alternatives you've considered**
I also tried overriding by passing `transform` styles directly to the `motion.div` element.

A more specific version of this might be adding a `dragThreshold` prop that would specify the offsets that the gesture must pass before the `onDragStart` event is called.

Another option might be having some way to cancel the animation (but not the event) from the `onDrag` handler.

**Comment by InventingWithMonster** [comment]
Are you finding that scrolling is happening at all when you drag on a component? It should be blocked - ideally we'd only block if you touched in the same direction as defined in `drag` but there's been issues getting this to work reliably.

You can combine `dragDirectionLock` with a drag axis so at least, for now, it shouldn't move if the user is swiping in the opposite direciton 

```jsx
<motion.div dragDirectionLock drag="x" />
```

**Comment by danprince** [comment]
Thanks! That's at least a step in the right direction :+1:

I had been testing by scrolling in screen space below the list, but that's actually a much bigger issue if/when the list occupies the whole screen. Guessing there's not a way to unblock scrolling right now then?

**Comment by InventingWithMonster** [comment]
Not at the moment sadly. I believe there might be a possible fix. But the problem ultimately is that to detect whether a user is dragging and in which direction we need to block the touch event from scrolling, or at least start blocking it before scrolling. But there's a distance a user can swipe within a single event that initiates scrolling. Once it's started, it's unblockable. Mobile browsers 👍

**Comment by danprince** [comment]
What about allowing the user to control whether `blockViewportScroll()` is called, via a prop?

In my case, there's no horizontal scroll space available, so a drag on the x axis isn't going to affect it. Scrolling on the y axis shouldn't interfere because of the direction lock, right?

**Comment by dcecile** [comment]
I have a motion component that I want to drag on `"x"` for animations, but it takes enough of the screen on mobile that I want users to be able to drag it on `"y"` for scrolling. Do you have any advice or workaround ideas right now?

**Comment by thebuilder** [comment]
I just build a nice slider using the `drag="x"` functionality, when I ran into this issue. The component takes up most of the viewport, so you should be able to scroll down the page without trigging the drag effect.

Had to look into `blockViewportScroll()`, and it seems like a really aggressive method of preventing scrolling while dragging, since we have no way of controlling it.

I know this is one of those difficult issues, and we can agree that you don't want scrolling to occur while dragging.

I made "fix" given that determines if we are scrolling on dragging based on the initial velocity in `onDragStart` - but it's far from perfect. Might be better if it could sample a few events before locking it.
 
```jsx
function Example() {
  const [allowScroll, setAllowScroll] = useState(false)
  useEffect(() => {
    if (allowScroll) {
      const handleTouch = event => {
        event.stopPropagation()
      }
      document.addEventListener('touchmove', handleTouch)
      return () => {
        document.removeEventListener('touchmove', handleTouch)
      }
    }
  }, [allowScroll])

  return <motion.div drag="x" onDragStart={(event, info) => {
          setAllowScroll(Math.abs(info.delta.y) > Math.abs(info.delta.x))
        }}
  />
}

```

**Comment by brunocrosier** [comment]
Not sure if I fully understand why this can't currently work - but for anybody who happens upon this thread looking for a solution, I did notice that the react-swipeable-views package does seem to achieve this to some extent.

What I would find useful is the ability to scroll vertically but at the same time use framer-motion for dragging on the x-axis. Perhaps it could be opt-in to avoid the problem mentioned by @InventingWithMonster ?

I think this is quite a common use case for many UIs (eg Tinder-style "swipe" interfaces)

**Comment by brunocrosier** [comment]
Alternatively, for anyone looking for vertical scrolling while being able to drag an element horizontally, you can use react-spring. I have set up a quick codesandbox example:

https://codesandbox.io/s/react-use-gesture-simple-ou6dt

**Comment by alilishan-omniphics** [comment]
Has this been implemented yet? I am also facing the same issue ... I have a  list of items that is longer than the screen and need to scroll down but he drag="x" keeps preventing it

**Comment by Jeyloh** [comment]
> ```js-jsx
> function Example() {
>   const [allowScroll, setAllowScroll] = useState(false)
>   useEffect(() => {
>     if (allowScroll) {
>       const handleTouch = event => {
>         event.stopPropagation()
>       }
>       document.documentElement.addEventListener('touchmove', handleTouch)
>       return () => {
>         document.documentElement.removeEventListener('touchmove', handleTouch)
>       }
>     }
>   }, [allowScroll])
> 
>   return <motion.div drag="x" onDragStart={(event, info) => {
>           setAllowScroll(Math.abs(info.delta.y) > Math.abs(info.delta.x))
>         }}
>   />
> }
> ```

Thank you very much, this solved my Carousel issue ❤ Have you seen any issues with it? The X drag was hit a little bit in responsiveness, but it's worth being able to scroll.

**Comment by FlorinSenoner** [comment]
> Thank you very much, this solved my Carousel issue ❤ Have you seen any issues with it? The X drag was hit a little bit in responsiveness, but it's worth being able to scroll.

Do you have a working example of this? Can't get this to work in a reliable manner

**Comment by kimgronqvist** [comment]
I have this that used to work (in 1.6.7), but not in the latest version.

```tsx
const Example = () => {
    const clientYStart = useRef(null);
    const clientXStart = useRef(null);
    const horizontalScrollStart = useRef(0);
    const isDragging = useRef(false);
    const isScrolling = useRef(false);

    return (
        <div
            onTouchStart={e => {
                // Track current direction
                const touch = e.targetTouches[0];
                clientYStart.current = touch.clientY;
                clientXStart.current = touch.clientX;
                horizontalScrollStart.current = horizontalScroll.get();
            }}
            onTouchMove={e => {
                const touch = e.targetTouches[0];
                const deltaY = Math.abs(touch.clientY - clientYStart.current);
                const deltaX = Math.abs(touch.clientX - clientXStart.current);
                if (isDragging.current) {
                    return;
                }
                if (isScrolling.current) {
                    e.stopPropagation();
                    return;
                }
                if (deltaX > deltaY) {
                    isDragging.current = true;
                } else {
                    isScrolling.current = true;
                    e.stopPropagation();
                }
            }}
            onTouchEnd={e => {
                if (isScrolling.current) {
                    horizontalScroll.set(horizontalScrollStart.current);
                }
                isDragging.current = false;
                isScrolling.current = false;
            }}>
            {items.map(item => (
                <motion.div drag={'x'} style={{ x: horizontalScroll }}></motion.div>
            ))}
        </div>
    );
};
```

**Comment by sparlos** [comment]
I'm also dealing with this right now. I have drag='x' with dragDirectionLock enabled on an element that can have overflow-y which is set to scroll, but on mobile I'm not able to scroll it. Perhaps implementing a way to cancel a drag in progress would be helpful? For example, a way to cancel the drag in the onDirectionLock callback if the axis returned is 'y'. Not sure if that would be feasible though; just spitballing.

**Comment by wintercounter** [comment]
I just want to maintain body scroll, but doesn't matter if i set `dragDirectionLock` or not, it won't allow me scroll up/down on mobile. I simply use `drag="x"`.

**Comment by dimitriirybakov** [comment]
As temporary solution we use [react-use-gesture](https://github.com/react-spring/react-use-gesture) instead of drag properties and animate everything with `framer-motion`.

**Comment by InventingWithMonster** [comment]
@dimitriirybakov Can you show the basic pattern how you use that to fix this? I am not above copying as this one has stumped me.

**Comment by alpfilho** [comment]
As temporary solution we use pan props to implement drag and `touch-action: pan-y` css prop in the draggable element to allow browser react to vertical scroll

**Comment by dimitriirybakov** [comment]
@InventingWithMonster well, it's basically something like this

```
const x = useMotionValue(0);

const bind = useDrag((state) =>  x.set(state.movement[0]));

return <div style={{ x }} {...bind()}/>;
```

**Comment by OlegPanagushin** [comment]
Possible workaround, not ideal but can be useful 

`
const Component:FC = () => {
  const containerRef = useRef<HTMLDivElement | null>(null)

  useEffect(() => {
    let prevY = 0
    let prevX = 0
    const handleTouch = (event: TouchEvent): void => {
      const { clientY, clientX } = event.touches[0]

      const deltaY = Math.abs(clientY - prevY)
      const deltaX = Math.abs(clientX - prevX)
      if (deltaX < deltaY) { //vertical swipe
        event.stopPropagation()
      }
      prevY = clientY
      prevX = clientX
    }

    containerRef.current?.addEventListener('touchmove', handleTouch, true)
    return (): void => {
      containerRef.current?.removeEventListener('touchmove', handleTouch)
    }
  }, [containerRef])

  return (
    <div ref={containerRef}>
       <motion.div drag="x">
         -- CONTENT --
       </motion.div>
    </div>
  )
}
`

**Comment by Weffe** [comment]
Can confirm I also have this issue as well. Is this issue on the roadmap of getting fixed in the next major/minor version?

**Comment by oygen87** [comment]
i also have this issue with a list taking all my mobile screen and i cant scroll y-axis because of the listItems having drag=x..
any progress?

**Comment by zephy20** [comment]
Has anyone been able to solve this? Been stuck on this for hours.

**Comment by BenjaminCorey** [comment]
The blocked scrolling was giving me some problems implementing a list of swipeable cards, here's the workaround I used:

```jsx
const SwipeableCard = (props) => {
  const [dragEnabled, setDragEnabled] = useState(true);
  return (
    <motion.div
      drag={dragEnabled ? "x" : false}
      dragDirectionLock
      onDirectionLock={(axis) => {
        setDragEnabled(axis !== "y");
      }}
      onTouchEnd={() => setDragEnabled(true)}
    >
      {props.children}
    </motion.div>
  );
};
```

**Comment by danilockthar** [comment]
> style={{ x }} {...bind()}

Hi! is there a way to make this work with motion dragcontraints? im tried this and the scrolling seems to work along with the x drag, but i have to take out the framer motion "drag" property to acomplish. This breaks the dragContraints property.

**Comment by BenjaminCorey** [comment]
> > style={{ x }} {...bind()}
> 
> Hi! is there a way to make this work with motion dragcontraints? im tried this and the scrolling seems to work along with the x drag, but i have to take out the framer motion "drag" property to acomplish. This breaks the dragContraints property.

@danilockthar I just did this last night and it seemed to work...

``` jsx
const myComponent = ({children}) => {
  const animation = useAnimation({
    x: 0,
    transition: {
      type: "spring",
      stiffness: 1,
    },
  });
  const bind = useDrag(
    (state) => {
      if (state.dragging) {
        animation.start({ x: state.movement[0] });
      } else {
        animation.start({ x: 0 });
      }
    },
    {
      axis: "x",
    }
  );

  return (
    <motion.div
      {...bind()}
      animate={animation}
    >
      {children}
    </motion.div>
  )
}
```

**Comment by danilockthar** [comment]
> > > style={{ x }} {...bind()}
> > 
> > 
> > Hi! is there a way to make this work with motion dragcontraints? im tried this and the scrolling seems to work along with the x drag, but i have to take out the framer motion "drag" property to acomplish. This breaks the dragContraints property.
> 
> @danilockthar I just did this last night and it seemed to work...
> 
> ```js-jsx
> const myComponent = ({children}) => {
>   const animation = useAnimation({
>     x: 0,
>     transition: {
>       type: "spring",
>       stiffness: 1,
>     },
>   });
>   const bind = useDrag(
>     (state) => {
>       if (state.dragging) {
>         animation.start({ x: state.movement[0] });
>       } else {
>         animation.start({ x: 0 });
>       }
>     },
>     {
>       axis: "x",
>     }
>   );
> 
>   return (
>     <motion.div
>       {...bind()}
>       animate={animation}
>     >
>       {children}
>     </motion.div>
>   )
> }
> ```

This looks great Benjamin ! Thank you very much.  It works great :D

**Comment by omarryhan** [comment]
Thanks @BenjaminCorey 

Where did you import the `useAnimation` hook from? Framer Motion's `useAnimation` hook does not accept any arguments. Is it from a different lib?

**Comment by papeloto** [comment]
> I just build a nice slider using the `drag="x"` functionality, when I ran into this issue. The component takes up most of the viewport, so you should be able to scroll down the page without trigging the drag effect.
> 
> Had to look into `blockViewportScroll()`, and it seems like a really aggressive method of preventing scrolling while dragging, since we have no way of controlling it.
> 
> I know this is one of those difficult issues, and we can agree that you don't want scrolling to occur while dragging.
> 
> I made "fix" that determines if we are scrolling or dragging based on the initial velocity in `onDragStart` - but it's not perfect. Might be better if it could sample a few events before locking it.
> 
> ```js-jsx
> function Example() {
>   const [allowScroll, setAllowScroll] = useState(false)
>   useEffect(() => {
>     if (allowScroll) {
>       const handleTouch = event => {
>         event.stopPropagation()
>       }
>       document.documentElement.addEventListener('touchmove', handleTouch)
>       return () => {
>         document.documentElement.removeEventListener('touchmove', handleTouch)
>       }
>     }
>   }, [allowScroll])
> 
>   return <motion.div drag="x" onDragStart={(event, info) => {
>           setAllowScroll(Math.abs(info.delta.y) > Math.abs(info.delta.x))
>         }}
>   />
> }
> ```

Using this solution with vertical list I have the same problem, the event gets locked infinitely `onDrag` which I am only able to exit by clicking outside.

**Comment by em** [comment]
I think I'm having the opposite issue here in that I have my own scroll-blocking in place using https://www.npmjs.com/package/body-scroll-lock. And framer-motion's built-in blocking appears to break mine after the first drag by colliding with body-scroll-lock. Not sure why yet, perhaps both are modifying body style?

**Comment by mattgperry** [comment]
The way it works is by applying touch-action style to the element - maybe
you can override it with an !important rule and see if that fixes it?

**Comment by Dm1Korneev** [comment]
> Thanks @BenjaminCorey
> 
> Where did you import the `useAnimation` hook from? Framer Motion's `useAnimation` hook does not accept any arguments. Is it from a different lib?

Hey @omarryhan do you found the way how to handle it?
I have stucked with tha same problem. Ca't drag scrollable container on mobile...

**Comment by omarryhan** [comment]
Hey @Dm1Korneev 

Here's the code I used: https://github.com/omarryhan/trendzz/blob/master/components/WithSlide/Component.tsx

And for the live demo, go to: https://trendzz.netlify.app and try swiping a repo card to the left.

Hope that helps.

**Comment by omattman** [comment]
Any news on this?

**Comment by menachem1** [comment]
I know chrome for Android has a preview feature that does what this issue is trying to resolve does anyone maybe know the logic of how that works?
I'm struggling with the same issue.
