### ISSUE TITLE
Can't reopen non-contributor issue on Github

### ISSUE THREAD

**Issue by maurocolella** [framer/motion#1856]
Happy New Year.

Last week, I reported a possible [bug](https://github.com/framer/motion/issues/1850#issuecomment-1366611755), which was closed for lack of access to the source code (was private, my mistake).

I fixed the access and shared a code sandbox, but I can't reopen that bug due to not being a contributor on the repo.

I just wanted to flag this as an issue.

**Comment by mattgperry** [comment]
Thanks!
