### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by unxoun** [framer/motion#1869]
The `dragControls` functionality does not work on Chrome Mobile.
Select "Toggle Device Toolbar" in Chrome Devtools & check the following:
https://codesandbox.io/s/dreamy-firefly-epp49e

**Comment by mattgperry** [comment]
Have you verified this on an Android device? My expectation is this is more likely a bug with the mobile emulation

**Comment by unxoun** [comment]
> Have you verified this on an Android device? My expectation is this is more likely a bug with the mobile emulation

Yes I have checked with the real Android device too, the problem exists.

**Comment by mattgperry** [comment]
I've taken a look into it - you need to add 

```
touch-action: none;
```

To the triggering element. I've updated the docs to reflect this.

**Comment by unxoun** [comment]
> I've taken a look into it - you need to add the CSS rule
> 
> ```
> touch-action: none;
> ```
> 
> To the triggering element. I've updated the docs to reflect this.

Solved! thanks!
