### ISSUE TITLE
Animating a item on click in a list of items

### ISSUE THREAD

**Issue by mpn7** [framer/motion#1871]
Hi,

I'm having trouble finding a solution to my problem.

**What I want to do**
I have a dynamic  list of items that comes from a DB, on click of a item I want it to zoom in and the adjacent items to move out of the way. 

**What I've tried / thought of doing**
From what I understand I need to have a AnimationControl to say when to start the animation. What I can't figure out is how to have a control for each item. I read through your documentation and haven't found anything that does what I want. 
I thought of assigning a useAnimationControls() for each item but react doesn't let me do it because the hooks need to be in the body of a function component.

Does anyone have any insight / recommendations on how to do this.

Thank you in advance.

**Comment by mattgperry** [comment]
You might have more luck asking a question like this in our Discord https://discord.com/invite/framer

Personally I would give all these items a `layout` prop and simply change the layout via CSS.

Alternatively - from what you've said I'm not sure why you think you need `useAnimationControls`, usually the simplest thing is to use the `animate` prop. To zoom one item in you're presumably already using props or state. Change the values within `animate` based on those.  

If for some reason you do need to use `useAnimationControls` then you can give each item its own controls by making each item its own component. But from the sounds of it this seems more complicated than what it probably needs.
