### ISSUE TITLE
[FEATURE] Wait for measurement calculation before reading `initial` prop and starting presence animation

### ISSUE THREAD

**Issue by atomiks** [framer/motion#1878]
To preface: I apologize if this problem already has a solution, but I couldn't find a solution in the docs, nor searching on GitHub. 

## Problem

I have a dynamic `initial` prop whose values depend on a calculation made **after** an animated element mounts — `y` should be negative if the calculation is `'bottom'`, but positive if `'top'` (side-aware transitions). This is only known on the next render after the element mounts, because it needs to be on the DOM and measureable, right after Framer Motion begins the animation.

In essence:

```js
import { motion, AnimatePresence } from "framer-motion";
import { useCallback, useState } from "react";

export default function App() {
  const [side, setSide] = useState(null);

  const measureNode = useCallback(() => {
    // The side is only known based on the node's dimensions,
    // which means we don't know this until it has mounted.
    setSide("bottom");
  }, []);

  return (
    <AnimatePresence>
      <motion.div
        ref={measureNode}
        initial={side ? { y: side === "top" ? 5 : -5 } : {}}
        animate={{ y: 0 }}
      >
        My node
      </motion.div>
    </AnimatePresence>
  );
}
```

I can't find a way to let it wait (only 1 frame necessary) for this value to be calculated and then start the animation on the next render.

I tried:

1. `variants` to orchestrate a fake wait
2. `delay` to wait briefly, but it closes over the stale value, not the next rendered value?
3. `<motion.div key={side} />` works, but causes a bug with the `ref` prop (calls it with `null` unexpectedly at the end), and makes the animation sometimes glitchy, which breaks something else and makes it non-viable.
4. Two separate nodes to render, where the measurement is performed on a "fake" layout node, then once it's ready, animate in the "real" node.

[Point 4 works](https://codesandbox.io/s/floating-ui-react-dom-template-forked-ym2gjx?file=/src/App.js), but feels like a hack, requiring the node to be extracted to a variable, and has to re-mount:

```js
import { motion, AnimatePresence } from "framer-motion";
import { useCallback, useState } from "react";

export default function App() {
  const [side, setSide] = useState(null);

  const measureNode = useCallback(() => {
    setSide("bottom");
  }, []);

  const node = (
    <motion.div
      ref={measureNode}
      initial={side ? { y: side === "top" ? 5 : -5 } : {}}
      animate={{ y: 0 }}
    >
      My node
    </motion.div>
  );

  return (
    <>
      {!side && node}
      <AnimatePresence>
        {side && node}
      </AnimatePresence>
    </>
  );
}
```

Here's a [CodeSandbox demo](https://codesandbox.io/s/floating-ui-react-dom-template-forked-5okbpi?file=/src/App.js) demonstrating point 4 above using an actual library to show a concrete example.

## Solution

Some kind of prop on `AnimatePresence`?

**Comment by mattgperry** [comment]
You can perform the measurement in `useLayoutEffect`. In a future update you might be able to use this measurement to set state with this measurement before the animation runs but I'm going to set this as a `wontfix` as I can't make any promises with that. But the measurement could be saved somewhere like a ref and retrieved dynamically with a [dynamic variant](https://www.framer.com/motion/animation/##dynamic-variants).
