### ISSUE TITLE
Add a reference to `dragListener` property in `dragControls` documentation

### ISSUE THREAD

**Issue by maticzav** [framer/motion#1879]
**Is your feature request related to a problem? Please describe.**
It's hard to figure out that you need to set `dragListener` to `false` when using `dragControls` to prevent auto-dragging. It would be great if the docs referenced the `dragListener` property instead of relying on the developer seeing it below.

**Describe the solution you'd like**
Make a reference in the description of `dragControls` property "that you likely want to change `dragListener`".

**Describe alternatives you've considered**
Perhaps it would make sense to make it a default to set `dragListener` to `false` whenever there's `dragControls` property, and `dragListener` hasn't been explicitly set to `true`.

On the other hand, this would be a breaking change, and the upside of changing it isn't that significant.

**Additional context**
I discovered I need to use `dragListener` to prevent auto-dragging another issue regarding `dragControls` on GitHub. I don't think that's the intended way of learning about `dragListener`, and I suppose many people don't check beyond `dragControls`.

**Comment by mattgperry** [comment]
Good suggestion, publishing a copy change now
