### ISSUE TITLE
[BUG] Re-opening #1837: Hardware-accelerated opacity animations breaking stacking context

### ISSUE THREAD

**Issue by hiddenest** [framer/motion#1885]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
Re-opening #1837 issue.
the elements that applied opacity animations by framer-motion, are hide behind the `position: relative` areas.  
It works normally until v7.8.1.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
Copied some of my sample code running in production:

- [CodeSandbox Link](https://codesandbox.io/p/github/hiddenest/framer-motion-opacity-error/draft/clever-boyd?create=true&workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clcnd4wma000g3b6lco3yap36%2522%253A%257B%2522key%2522%253A%2522clcnd4wma000g3b6lco3yap36%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522clcnd4wma000h3b6la77igqx9%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522clcnd4wma000i3b6l47gnoa4o%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clcnd4wma000g3b6lco3yap36%2522%252C%2522spacesOrder%2522%253A%255B%2522clcnd4wma000g3b6lco3yap36%2522%255D%257D)
- [GitHub Repository](https://github.com/hiddenest/framer-motion-opacity-error)

**4. Steps to reproduce**

1. Check 'Hide Fake Element' checkbox as `checked`
2. Click 'Click me' button
3. Click 'Toggle' button

**5. Expected behavior**

**As-is**
<img width="414" alt="스크린샷 2023-01-08 오후 9 49 14" src="https://user-images.githubusercontent.com/8682478/211196912-087ab23c-df24-4f15-bff5-a79d4f805d09.png">

**To-be**
`Relative Area` should not hide the menu areas.

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

https://user-images.githubusercontent.com/8682478/211196867-d1631d4e-0f5a-4528-bcf9-7eeca5e0448f.mov

**7. Environment details**

Mac OS 13, Chrome 108. Setup project with React 18 + TypeScript based on Vite official template.

**Comment by mattgperry** [comment]
To some extent this is expected.

What's happening is the layer with the `opacity` animation is creating a new stacking context. So the child with the high `z-index` is having no effect vs the "Relative" layer.

Any element with a non `1` `opacity` is a new stacking context: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

So this would already have been a problem in older versions of Framer Motion during the animation itself. Probably masked a little bit by the visual nature of opacity animations.

The difference now is this stacking context is persisting beyond the end of animation but to be honest the visual output of a consistent stacking context is more desirable than it flicking in and out. So I'm not going to fix it within Framer Motion, and a fix you could try here is by moving `z-index` to the element that shares a stacking context with the "Relative" element: The element with the `opacity` animation.

**Comment by hiddenest** [comment]
@mattgperry thx for your help!
fixed by adding `z-index: 1` to the element with the opacity animation 💪
