### ISSUE TITLE
[BUG] [REGRESSION] SVG Path Animations NaN Error

### ISSUE THREAD

**Issue by amcdnl** [framer/motion#1903]
## Bug
SVG Path animations are failing after upgrading github.com/reaviz/reaviz to framer-motion v8 from v7.

I'm getting the following error in the console:

```
Error: <path> attribute d: Expected number, "M0,NaNL111,NaNL250,…".
```

which is in reference to this path transition:

```
M0,104L111,0L250,208L333,104 -> M0,234L111,234L250,234L333,234

M0,104L111,0L250,208L333,104L333,234L250,234L111,234L0,234Z -> M0,234L111,234L250,234L333,234L333,234L250,234L111,234L0,234Z
```

No other changes were made outside of upgrading to v8. If I had to guess it might be related to some code in this file https://github.com/reaviz/reaviz/blob/master/src/common/Motion/MotionPath.tsx but I'm not entirely sure.

After change:
<img width="609" alt="image" src="https://user-images.githubusercontent.com/227909/213199178-b41e8ea7-4d03-4fd7-8790-c9a248502269.png">

Before change:
<img width="504" alt="image" src="https://user-images.githubusercontent.com/227909/213199272-5bd61462-e198-45ed-9f9b-53381e749946.png">

**Comment by mattgperry** [comment]
Note: @amcdnl discovered this broke in 7.8.1

**Comment by amcdnl** [comment]
@mattgperry - Any updates - this is blocking me from upgrading at the moment.

**Comment by amcdnl** [comment]
@mattgperry - Retested on 10.12.18 and still an issue.

**Comment by mattgperry** [comment]
Closing without a sandbox reproduction, it would be great to have this isolated perhaps to a `useTransform` even.

**Comment by amcdnl** [comment]
I was able to solve this a different way so this can be closed if it's not an issue for others
