### ISSUE TITLE
[BUG] Conditionally animating background or backgroundColor does not work and happens instantly, but things like opacity do work

### ISSUE THREAD

**Issue by 55Cancri** [framer/motion#1909]
** Describe the bug**
Conditionally animating background or backgroundColor does not work and happens instantly, but things like opacity do work

** IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/wonderful-tereshkova-26uubi?file=/src/App.js

** Expected behavior**
Background color should smoothly animate from one color to the next

**Comment by mattgperry** [comment]
Motion doesn't support named colors. All supported value types are listed here: https://www.framer.com/motion/component/#supported-values
