### ISSUE TITLE
[BUG] useAnimation variants don't propagate unless the parent has variants defined

### ISSUE THREAD

**Issue by InventingWithMonster** [framer/motion#191]
Go to this example: https://codesandbox.io/s/framer-motion-directional-stagger-effect-grid-f127v

Remove the `variants={{}}` prop from the parent - the animation breaks.

Variants should always propagate until they meet a child with its own `animate` prop.

**Comment by equinusocio** [comment]
Should this example be updated with this fix?
https://codesandbox.io/s/framer-motion-directional-stagger-effect-grid-f127v?file=/src/index.js
