### ISSUE TITLE
[BUG] page transition is not continuous

### ISSUE THREAD

**Issue by yerori** [framer/motion#1910]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

Give a clear and concise description of what the bug is.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

![ezgif com-gif-maker](https://user-images.githubusercontent.com/66937293/214226585-f74273fd-4891-46cc-acab-4fb69d4d3a10.gif)

I am developing an animation that switches from page 1 to page 2.

However, when routing in page 1, it can be seen that it is mounted to <h3>page 1->empty page -> page 2.</h3>

I want to make an animation that goes directly from page 1 to page 2 without empty space or blank page.

_app.tsx
```
<AnimatePresence initial={false} exitBeforeEnter>
  <App {...props} key={router.asPath} />
</AnimatePresence>
```

AnimatedPage HOC Component
```
 <motion.section
                    initial={{ x: "100vw" }}
                    animate={{
                        x: 0,
                        opacity: 1,
                    }}
                    exit={{
                        x: "-100vw",
                    }}
                    transition={{
                        ease: "easeInOut",
                        duration: 1,
                        staggerChildren: 5,
                    }}
                >
                    {children}
                </motion.section>
```

How can I fix the code to correct it as I expected?

**Comment by yerori** [comment]
> **1. Read the [FAQs](#faqs) 👇**
> 
> **2. Describe the bug**
> 
> Give a clear and concise description of what the bug is.
> 
> **3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
> 
> A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**
> 
> ![ezgif com-gif-maker](https://user-images.githubusercontent.com/66937293/214226585-f74273fd-4891-46cc-acab-4fb69d4d3a10.gif) [ ![ezgif com-gif-maker](https://user-images.githubusercontent.com/66937293/214226585-f74273fd-4891-46cc-acab-4fb69d4d3a10.gif) ](https://user-images.githubusercontent.com/66937293/214226585-f74273fd-4891-46cc-acab-4fb69d4d3a10.gif) [ ](https://user-images.githubusercontent.com/66937293/214226585-f74273fd-4891-46cc-acab-4fb69d4d3a10.gif)
> 
> I am developing an animation that switches from page 1 to page 2.
> 
> However, when routing in page 1, it can be seen that it is mounted to
> 
> ### page 1->empty page -> page 2.
> I want to make an animation that goes directly from page 1 to page 2 without empty space or blank page.
> 
> _app.tsx
> 
> ```
> <AnimatePresence initial={false} exitBeforeEnter>
>   <App {...props} key={router.asPath} />
> </AnimatePresence>
> ```
> 
> AnimatedPage HOC Component
> 
> ```
>  <motion.section
>                     initial={{ x: "100vw" }}
>                     animate={{
>                         x: 0,
>                         opacity: 1,
>                     }}
>                     exit={{
>                         x: "-100vw",
>                     }}
>                     transition={{
>                         ease: "easeInOut",
>                         duration: 1,
>                         staggerChildren: 5,
>                     }}
>                 >
>                     {children}
>                 </motion.section>
> ```
> 
> How can I fix the code to correct it as I expected?

**Comment by orsifrancesco** [comment]
Removing "exitBeforeEnter" will fix the problem :)
