### ISSUE TITLE
[BUG] Cant install frame-motion

### ISSUE THREAD

**Issue by shaddamalbz** [framer/motion#1915]
**1. Read the [FAQs](#faqs) 👇**
done

**2. Describe the bug**
simply error when install framer-motion, it work when I try to install in another project with same environment below. 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

**4. Steps to reproduce**

1. yarn install framer-motion

**5. Expected behavior**
success to install framer-motion dependencies.

**6. Video or screenshots**

![image](https://user-images.githubusercontent.com/47707535/215381453-6d92cd22-e809-4e8d-8a06-81aa41ba21ba.png)
here the log
![image](https://user-images.githubusercontent.com/47707535/215382701-5318ed2e-9f1d-42ff-9e90-9da4bbb17356.png)

**7. Environment details**
Node: 18.13.0
Yarn: 1.22.19
npm : 8.19.3

**Comment by theresasogunle** [comment]
Hello @shaddamalbz, Not sure if this is a Framer-motion bug from your screenshots. More like you have a `@restart/hooks` package in your package.json that isn't getting resolved. Can you please share a screenshot of your package.json file?

**Comment by mattgperry** [comment]
Yeah this doesn't look like a problem with Framer Motion

**Comment by shaddamalbz** [comment]
Sorry my bad, yeah, it's doesn't problem from Framer Motion its problem with my yarn.lock file. I need to delete yarn.lock then install it again and it work.
