### ISSUE TITLE
[BUG] There are issues related to UseInView hook . 

### ISSUE THREAD

**Issue by Srijan-Baniyal** [framer/motion#1917]
*Bug Description

Basically, I was working on my project and there is no error from typescript, JavaScript and other esLinting tools and extensions.
It's more like maybe my "typed" types somewhere maybe wrong or somewhere executions are going wrong in the compilation.
It's not getting animated .It gets rendered in the last position.

This is my CodeSandBox Link: -
[`codesandbox`](https://codesandbox.io/s/suspicious-water-uzy4ks)

Expected behavior.

It should have animation coming from left to right when it's in the viewport or the intersection area .

**Comment by mattgperry** [comment]
Your `transition` is malformed.

<img width="295" alt="Screenshot 2023-02-01 at 10 27 58" src="https://user-images.githubusercontent.com/7850794/216003961-3ef6b4a2-58c0-42be-b5b0-29894b8acdb0.png">

Further, `transform` won't work with `display: inline` elements which is the default for `<span />` elements. So double check  you have this set to `inline-block`.

**Comment by Srijan-Baniyal** [comment]
Nope, by default I have settled it up on block and in the span, tag gave some variations no change.
