### ISSUE TITLE
[BUG] `Shared layout animations` section's `Learn More` link is broken

### ISSUE THREAD

**Issue by snelsi** [framer/motion#1919]
In [this section](https://www.framer.com/motion/examples/#shared-layout-animations) of the docs "Learn More" link seems to exclude the last letter:

![image](https://user-images.githubusercontent.com/15171036/215849265-88d58ea5-7e5b-48e9-8c38-3bdc02f47f86.png)

![image](https://user-images.githubusercontent.com/15171036/215849295-836eac90-7db4-44c8-a176-c7960ac9f696.png)

The last letter "e" should be clickable as well.

**Comment by mattgperry** [comment]
Thanks again - publishing a fix
