### ISSUE TITLE
[BUG] `Viewport options` link is broken

### ISSUE THREAD

**Issue by snelsi** [framer/motion#1920]
In [this section](https://www.framer.com/motion/scroll-animations/#scroll-triggered-animations) of the docs:

```
An object of [viewport options](https://www.framer.com/motion/scroll-animations/#viewport-options) that define how the viewport is detected.
```
![image](https://user-images.githubusercontent.com/15171036/215856503-154c3790-34ce-4b73-8231-c7c756242e0b.png)

`viewport option` link leads to https://www.framer.com/motion/scroll-animations/#viewport-options. 

This is incorect. It should actually lead to https://www.framer.com/motion/scroll-animations/##viewport-options (with double hash character)

**Comment by mattgperry** [comment]
Thanks - just publishing a fix now!
