### ISSUE TITLE
[BUG] Animation with CSS variable in rgb function fails

### ISSUE THREAD

**Issue by samselikoff** [framer/motion#1921]
**2. Describe the bug**

An animation using the css rgb function along with a css variable is causing an error.

Given

```css
:root {
  --red: 255 0 0;
}
```

and

```jsx
<>
  <motion.div
    style={{ backgroundColor: "rgb(255 0 0 / 1)" }}
    whileHover={{ backgroundColor: "rgb(255 0 0 / 0)" }}
  />

  <motion.div
    style={{ backgroundColor: "rgb(var(--red) / 1)" }}
    whileHover={{ backgroundColor: "rgb(var(--red) / 0)" }}
  />
</>
```

...hovering the top box will work but the bottom will throw the error

> Uncaught (in promise) Error: 'rgb(var(--red) / 0)' is not an animatable color. Use the equivalent color code instead.

Similar issue: https://github.com/framer/motion/issues/1652

**3. Reproduction**

https://codesandbox.io/p/sandbox/nifty-gates-82c7br?file=%2Fsrc%2FApp.tsx

**4. Steps to reproduce**

1. In the Code Sandbox click "Open in a new tab" (so you can see the error in the console)
2. Hover the top square, and notice it animates
3. With the devtools console open, hover the bottom square
4. You'll see the `rgb(var(--red) / 0) is not an animatable color` error

**5. Expected behavior**

The bottom box's hover animation works. I actually swear I've done this before! I'm not sure if anything changes in versions since then, but I couldn't put my finger on that demo.

**Comment by kpauletti** [comment]
I have this same issue using hls. `hls(var(--custom-variable))` also does not work. Seems like its not able to parse nested functions.

**Comment by sjoerdvanBommel** [comment]
I tried a workaround to wrap `hsl(var(--custom-variable))` inside of a separate variable and use that, but that also doesn't seem to work. Has there been made any progress regarding this? Thanks!

**Comment by mattgperry** [comment]
I've gone down this rabbit hole a few times to no avail. It's not easy to support nested CSS vars (which can be nested) with regex, I believe it requires a chunky bit of code. I'm closing as `wontfix` for now just to set expectations but it might be possible in the future to force animations like these to run over WAAPI.
