### ISSUE TITLE
[FEATURE] DevTools

### ISSUE THREAD

**Issue by mattgperry** [framer/motion#1922]
Not so much for editing animations tobegin with but for helping debug production sites it would be good to have introspection.

Some ideas

- Layout animations
    - Reason for triggering
    - LayoutGroup propagation info
    - Successful/unsuccessful tree optimisations
- Animations
    - WAAPI vs JS
    - Settings used to request animations

**Comment by ChazUK** [comment]
This would be insanely helpful for showing trigger positions, even things like the margin property on useInView is very hard to understand which could be helped by adding easy visuals.

**Comment by mattgperry** [comment]
Closing as more likely we'll build something into Framer itself.

**Comment by ChazUK** [comment]
@mattgperry out of interest, do you expect people to be using Framer to create animations and exporting them into code? I have never used Framer itself only the framer-motion API directly in code.

**Comment by mattgperry** [comment]
No the editor would be just for animations made within Framer. This feature itself is hypothetical - I'm just saying I definitely don't see us making something for code export.
