### ISSUE TITLE
Next JS code not compiling after adding latest framermotion "motion" tag to a div

### ISSUE THREAD

**Issue by CaesarBourne** [framer/motion#1924]
I just installed the latest Framer motion version in an existing Next JS application, and the code does not compile when the motion tag is added to a div please find more details below and screenshots,

Please note my node version is 18.10.0 and my 
Next JS version is 13.1.6 
Framer motion version is version 9.0.0
and this issue can be reproduced with these versions

<img width="454" alt="Screenshot 2023-02-01 at 20 41 37" src="https://user-images.githubusercontent.com/30521761/216146728-880f7a81-1aa2-4922-8483-f398d3bace9d.png">

<img width="695" alt="Screenshot 2023-02-01 at 20 35 33" src="https://user-images.githubusercontent.com/30521761/216145835-4b196540-c685-41c1-be86-bc5985a4c1f4.png">

**Comment by mattgperry** [comment]
Reopening due to complications with https://github.com/rollup/rollup/issues/4699

**Comment by kerwanp** [comment]
I still have the issue when using the `framer-motion@10.1.0-alpha.3` version.
When adding manually `'use client';` to the top of the dist/cjs/index.js file I get the following error:

```
Error: Cannot access motion.div on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.
```

Do you have any workaround ?

**Comment by mattgperry** [comment]
I believe you need to make a local file that re-exports

```
// motion.js
"use client"
export * from "motion"

// foo.js
import { motion } from "./motion"
```

I'm setting as a `wontfix` to set expectations as although we have a `"use client"` directive in Motion it gets transpiled and compressed out with the bundling. If someone wants to take a look at that feel free.
