### ISSUE TITLE
[FEATURE] add dependencies array to `useScroll`

### ISSUE THREAD

**Issue by robbeman** [framer/motion#1929]
**Is your feature request related to a problem? Please describe.**

When the `offset` changes the scroll progress will not update.

**Describe the solution you'd like**

Allow passing dependencies to the `useScroll` hook.

https://github.com/framer/motion/blob/a514f7bcfaccccfb99409a1326e2647c4f0a6503/packages/framer-motion/src/value/use-scroll.ts#L58

**Describe alternatives you've considered**

Possible alternative could be to nest the component in some `key`ed component, but that might trigger a lot of unwanted renders.

**Additional context**

Sometimes the offsets may change during the lifespan of the useProgress hook. Take ad-slots, on top of the page, with a dynamic height for example. When you want to exclude this from the "read progress" you can do so by adding offsets to the useScroll hook.

**Example implementation**

```tsx
import { DependencyList } from 'react';

export function useScroll(
    {
        container,
        target,
        layoutEffect = true,
        ...options
    }: UseScrollOptions = {},
    dependencies: DependencyList = [], // <= pass a DependencyList as an optional parameter (or add to `UseScrollOptions`)
) {
    const values = useConstant(createScrollMotionValues)

    const useLifecycleEffect = layoutEffect
        ? useIsomorphicLayoutEffect
        : useEffect

    useLifecycleEffect(() => {
        refWarning("target", target)
        refWarning("container", container)

        return scroll(
            ({ x, y }) => {
                values.scrollX.set(x.current)
                values.scrollXProgress.set(x.progress)
                values.scrollY.set(y.current)
                values.scrollYProgress.set(y.progress)
            },
            {
                ...options,
                container: container?.current || undefined,
                target: target?.current || undefined,
            }
        )
    }, dependencies) // <= pass dependencies to effect hook

    return values
}
```

**Comment by mattgperry** [comment]
I believe this has been fixed in the meantime
