### ISSUE TITLE
[BUG] Scale animation broken after upgrade

### ISSUE THREAD

**Issue by jabrks** [framer/motion#1938]
First of all, apologies if this is not a bug. I have just finished upgrading from Framer Motion 6.0 to 9.0 and one of my animations is no longer working. A simplified example can be seen below

```jsx
import { motion, useAnimationControls } from 'framer-motion';
import { useEffect } from 'react';

function Component() {
  const controls = useAnimationControls();

  useEffect(() => {
    controls.start({ scale: ['2', '1'] });
  }, [controls]);

  return <motion.div animate={controls} />;
}
```

| Before | After |
|:--|:--|
| <video src="https://user-images.githubusercontent.com/52410024/217661718-5691427b-1c2b-40fe-89fe-b43448cdecde.mov" /> | <video src="https://user-images.githubusercontent.com/52410024/217661713-40f76707-2dda-46c0-8e1e-1d794b87402c.mov" /> |

I have also created a CodeSandbox demonstrating the issue for convenience: https://codesandbox.io/s/framer-scale-9etc2w

I was able to get the expected behaviour back with the following change

```diff
  useEffect(() => {
-    controls.start({ scale: ['2', '1'] });
+    controls.start({ scale: [2, 1] });
  }, [controls]);
```

I narrowed the first affected version down to 7.8.1. It's unclear to me if this is a regression or the original code was never supposed to work in the first place, so I thought I'd raise it here just in case. Any insight would be appreciated

**Comment by mattgperry** [comment]
I'm surprised this actively stopped working but I'm also surprised its ever worked - we've never had active support for unitless strings. Sorry it just broke randomly but yeah I don't think this is something we'll support any time soon either.

**Comment by jabrks** [comment]
No worries! It was simple enough to fix. Thanks for clarifying
