### ISSUE TITLE
[BUG] useInView missing amount dependency

### ISSUE THREAD

**Issue by LeoVS09** [framer/motion#1940]
When `amount` param changes, `useInView` not reflect changes

If it not problem, I think it pretty straingforward bug and I can point to exact line in code. I will skip reproduction and CodeSandbox.

[Line with missing dependency](https://github.com/framer/motion/blob/bafa7a925d23b79141ad90a03bd0a544d4deba59/packages/framer-motion/src/utils/use-in-view.ts#L32)

**Comment by mattgperry** [comment]
Fixing in `10.17.5`
