### ISSUE TITLE
[BUG][React 18 + NextJS] `AnimatePresence popLayout`: can't pass ref to custom children components

### ISSUE THREAD

**Issue by mnpqraven** [framer/motion#1942]
**2. Describe the bug**

I was trying to follow the example on [popLayout](https://www.framer.com/motion/animate-presence/###mode) mode but with custom components instead of normal `<motion.>` components.
I've tried to pass the required Refs to the list of components, both by using a single ref and multiple refs, each for each child component but it's always the last element in the list getting animated and not the one that I'm interacting with

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[CodeSandbox](https://codesandbox.io/p/sandbox/naughty-dubinsky-enzwn1?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A8%7D%5D)

**4. Steps to reproduce**

1. Write a parent component containing a list of child components
2. Wrap child component inside `forwardRef`, in parent component give child components `key` and `ref`
3. Add a few items to the list
4. Click the middle of the list

**5. Expected behavior**

That exact child component in step 3 will be faded out like the [example in the doc](https://codesandbox.io/s/framer-motion-animatepresence-poplayout-mode-t7qxhv?from-embed)

**6. Actual behavior**
The exact child component disappears instantly, last child component animates once

**7. Environment details**

I'm using React 18 + NextJS 13 (still using `pages/`, not `app/`)

**Comment by mattgperry** [comment]
Are these refs present during the initial render? Seems more likely this has something to do with immer

**Comment by mnpqraven** [comment]
hmm I don't think so, the behavior seems to be identical even when I use vanilla `useState`

[CodeSandbox](https://codesandbox.io/p/sandbox/wonderful-villani-c6q6vd?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A21%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A21%2C%22startLineNumber%22%3A5%7D%5D)

**Comment by mattgperry** [comment]
Ah yeah sorry what I'm getting at is the refs should be created and provided on the initial render.

**Comment by mnpqraven** [comment]
It should, I made another [sandbox](https://codesandbox.io/p/sandbox/wonderful-villani-c6q6vd?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A23%2C%22endLineNumber%22%3A19%2C%22startColumn%22%3A23%2C%22startLineNumber%22%3A19%7D%5D) that creates the refs right after declaring the list but it's still showing up the described behavior

**Comment by mattgperry** [comment]
The keys are being swapped whenever an item is removed so its impossible to track the lifecycle of a given number. It should be persistent:

```

                key={id}
                value={id}
```
