### ISSUE TITLE
[BUG] Reorder.Item requires position:relative set to render correctly

### ISSUE THREAD

**Issue by ze-kel** [framer/motion#1943]
Open [reorder example from docs](https://codesandbox.io/s/framer-motion-5-drag-to-reorder-lists-uonye?from-embed=&file=/src/styles.css)

Delete line 41 from styles.css
`li {
position: relative;
}`

Drag second item to first position. The first item will move to second position flying over first one as if it has higher z-index than the item being dragged.

This expectation of particular styling applied is not obvious and people copying code from docs will experience this bug.

Should either be explicitly documented or set automatically by Reorder.Item component.

**Comment by heymartinadams** [comment]
Fully support this! The amount of time I spent trying to debug this issue has been mind-boggling. A simple `position:relative` position would have fixed it right away.

Needs to be in the documentation, or automatically set, like @ze-kel mentioned.

```js
<LayoutGroup>
  <Reorder.Group axis='y' layoutScroll onReorder={setItems} values={items ?? []}>
    {items?.map((item, i) => (
      <Reorder.Item key={item.name} style={{ position: 'relative' }}>Item</Reorder.Item>
    ))}
  </Reorder.Group>
</LayoutGroup>
```

**Comment by mattgperry** [comment]
I think it's a little too opinionated to automatically set something but I'll make sure this is added to the docs, thanks for flagging.
