### ISSUE TITLE
[BUG] Fade in animation play twice on safari/firefox after updating framer motion v8.5.5+

### ISSUE THREAD

**Issue by iUnstable0** [framer/motion#1944]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
 
Animation re-playing multiple times on some web browsers (Safari and Firefox)

Give a clear and concise description of what the bug is.

When I visit a page the form will fade in, but the form faded in twice for no reason on safari/firefox. Works fine on Chrome.

this issue happened after I updated frmaer motion but I didn't check which version it was, before it never happened and I didn't change a single code after updating.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

I can't create a CodeSandbox because my app is too complex, but I'm happy to provide my code and this is the prod website
https://dev-serverside.falcon-utility.com

I've published the code in here
https://github.com/iUnstable0/framer-motion-bug-report
if you need more, lmk and I'll add it. thanks!

![CleanShot 2023-02-13 at 00 16 06](https://user-images.githubusercontent.com/46888825/218326151-6f38ff88-1f31-4e08-a08e-ff51a7603348.png)

**4. Steps to reproduce**

On that website you'll see a form, click the "Register" text on the bottom then the register on the second page should flicker on Safari and Firefox but not on Google Chrome

**5. Expected behavior**

I expect it to only fade in once

**6. Video or screenshots**

https://user-images.githubusercontent.com/46888825/218325799-cef0f3ec-f4f3-4d64-bbe2-cd8e3010aec7.mp4

**7. Environment details**

MacOS Ventura latest version Apple Silicon and Safari latest version firefox developer edition latest version and google chrome latest version too.
ALso on Windows 11 ARM Chrome latest version and Firefox dev edition latest version
iOS 16 latest version (every browsers since ios only allows webkit engine) latest version

**Comment by mattgperry** [comment]
Please reopen with sandbox example

**Comment by mattgperry** [comment]
The point of a sandbox example is *because* in situ the rest of an app can be too complex and by providing a minimal reproduction it can better help isolate the circumstances of the bug.

**Comment by niemal** [comment]
I second this, I had the exact same problem on my nextjs project (I don't know if nextjs plays a part). It solved downgrading to v8.5.4. Will see if I can put up a sandbox that reproduces sometime.

**Comment by mikirejf** [comment]
I observed the same issue. The problem was due to CSS transition properties being present on the motion element.

**Comment by filippozanfini** [comment]
Same goes for v.11.11.11. I solved the problem by downgrading to v. 8.5.4
