### ISSUE TITLE
[BUG] Scroll animation does not work on touch device

### ISSUE THREAD

**Issue by kaushal722** [framer/motion#1945]
**Scroll animation does not work on touch device**

Give a clear and concise description of what the bug is.

**CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-scroll-velocity-r1dy4u

**Comment by mattgperry** [comment]
Please reopen with browser and OS information

**Comment by kaushal722** [comment]
there was the issue with one of the render component which was having css property oxerflow-x : hidden, that was restricting it to work on smaller screens.
