### ISSUE TITLE
[BUG] UseScroll is compatible with older browsers

### ISSUE THREAD

**Issue by zhoushihao-creat** [framer/motion#1948]
In the useScroll() method, you can always get the amount of change scrollY, but in useScroll, you use the document.documentElement to get the scrollTop, but in older WebKit-based browsers, this is not feasible. For example, in Safari (bug 5991), you should use document.body instead of document.documentElement. You need to be compatible with lower versions of browsers

**Comment by mattgperry** [comment]
Which version of safari is this broken in?

**Comment by zhoushihao-creat** [comment]
> 这是哪个版本的 safari？

The ScrollY exposed by the useScroll() method in ios12 and below is unable to obtain the scrolling distance of the page

**Comment by mattgperry** [comment]
Ah ok - Motion doesn't support versions of iOS < 13 (0.3% of worldwide browsers)

**Comment by iwillwen** [comment]
@mattgperry Hey Matt, this bug could be reproduce in the WebView in WeChat App(Android version, WeChat is the most popular application in China). WeChat use a webkit-based custom rendering kernal on Android.

`document.documentElement.scrollTop` will always be 0.
