### ISSUE TITLE
[BUG] Error Rules of Hooks from console

### ISSUE THREAD

**Issue by mtr1990** [framer/motion#1949]
**2. Describe the bug**

When using lazy motion
Console warning when using version 9.0.2 (There is no this warning in version 8.x)

![xx](https://user-images.githubusercontent.com/13531993/218701883-c474b319-ce32-474e-9f90-da2a9096678c.jpg)

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Change framer-motion version and check at console to see the difference (Refresh browser after version change)
https://codesandbox.io/s/lazy-motion-asynchronously-forked-xppv4x?file=/src/App.tsx

**5. Expected behavior**

No error occurs in browser console

**Comment by mattgperry** [comment]
Just tested with the latest alpha and looks like this will be fixed in an upcoming release
