### ISSUE TITLE
[BUG] Chrome 54 support issues

### ISSUE THREAD

**Issue by present-g** [framer/motion#1952]
The version above `"framer-motion": "7.5.3"` has problems with Chrome 54 support in the `animateStyle` function.

`element.animate` receives incorrect arguments

Could you please check it?

Attaching the errors...

<img width="875" alt="Знімок екрана 2023-02-15 о 19 01 17" src="https://user-images.githubusercontent.com/47174128/219101292-90ef84ab-6516-4f0e-8932-559a86413b7d.png">

<img width="897" alt="Знімок екрана 2023-02-15 о 19 00 12" src="https://user-images.githubusercontent.com/47174128/219101347-baddeb89-346c-4541-b309-6fdf6ffd7541.png">

**Comment by mattgperry** [comment]
I might take a look if one or both of these are easily fixed but Chrome 54 isn't a supported browser https://www.framer.com/learn/compatibility/
