### ISSUE TITLE
[FIX] Deprecated code in useTransform() documentation

### ISSUE THREAD

**Issue by Deveesh-Shetty** [framer/motion#1954]
# Deprecated Code in documentation of `useTransform()` in Framer React Website

In an example code, we are using `useViewportScrolll()` which is deprecated (according to VSCode and has been updated to `useScroll()`). I tried the same snippet with `useScroll()` and it is working the same.

The code snippet is this
```js
const { scrollY } = useViewportScroll()
const rotate = useTransform(
  scrollY,
  [0, 100],
  [0, 360],
  { clamp: false }
)
```

Link to the page: [useTransform() Docs](https://www.framer.com/motion/use-transform/)

**Comment by mattgperry** [comment]
Thanks for the heads up! Publishing a fix now
