### ISSUE TITLE
[UX ISSUE] Modal Covering Right Side bar

### ISSUE THREAD

**Issue by Deveesh-Shetty** [framer/motion#1955]
# Cannot remove the modal from the screen.
I have been reading the docs for the past few hours and this modal is covering the sidebar and there is no way to close it. Even the text in it is not clickable.

- There should be a close button to close the modal. 

![Modal Issue](https://user-images.githubusercontent.com/89470104/219280539-73691aca-3787-4f55-80a4-43482fe89207.png)

**Comment by mattgperry** [comment]
Are you using Brave?

**Comment by Deveesh-Shetty** [comment]
Yes, I am using Brave

**Comment by Deveesh-Shetty** [comment]
I don't see the issue on the website now... I guess, it has been patched... @mattgperry?
