### ISSUE TITLE
Unable to remove the animation for Reorder list when css display property is flipped between "block" and "none"

### ISSUE THREAD

**Issue by MinHtet-O** [framer/motion#1958]
**Description**

I have the tab component that use css display property ( block/ hidden ) to show the content. Inside the tab content, I have the framer motion reorder group. When the tab is flipped, there is list animation that comes from the top left of the corner to the final position. I don't want this animation. I have tried using `AnimatePresence` to wrap the items and overwrite this animation. But it doesn't work.

I can control the animation if I conditionally render the component with react like the given example.

```
<AnimatePresence>
  {isVisible && <Component />}
</AnimatePresence>

```
But in my component, it flips the css display property.

**Steps to reproduce**
- Open the following [codesandbox](https://codesandbox.io/s/charming-austin-km001s)
- Click Show/Hide button
- The animation that comes from top left to the list position will be displayed. ( I want to remove this animation )

**Expected behavior**
There is no initial animation when the reorder div element is flipped from `display: none` to `display: block`

**Environment details**

React: 18.2.0
framer-motion: 5

**Comment by qtow** [comment]
`AnimatePresence` is (as far as I know) only for animating things that are conditionally rendered, like you pointed out. The method I've seen for controlling `display` like you want is to set `display: block` on the `style`, and use `transitionEnd: { display: "none" }` in your exit animation. [Here's a CodeSandbox](https://codesandbox.io/s/suspicious-pond-8kr6w4) that I think does what you want. Note that there's currently a bug (#1957) that can cause an element animated like this to get stuck with `display: none` if its opacity is also animated. It's somewhat rare (requires the animation to be cancelled on a specific frame), and only affects versions >= 7.9.0.

**Comment by mattgperry** [comment]
I think you would need to mount/unmount the component as what's currently happening is between renders it's getting measured as 0x0 (`display: none`) and animating out from that.
