### ISSUE TITLE
A Parallax example would be very nice :-)

### ISSUE THREAD

**Issue by rchrdnsh** [framer/motion#197]
**Is your feature request related to a problem? Please describe.**
I can't figure out how to implement a basic parallax on viewport scroll, so a simple and clear example in the docs would be awesome.

**Describe the solution you'd like**
A simple example of a few different divs moving around in relationship to viewport scroll position.

**Describe alternatives you've considered**
I'm reading through the MotionValue API docs but it's not really clicking for me yet.

**Additional context**
I mean, any other use cases for MotionValue I can think of I will add, I guess.

XD

**Comment by natemoo-re** [comment]
You may have discovered this already, but there are some [more examples](https://www.framer.com/api/motion/examples/#more) in the docs now, including this [Parallax](https://codesandbox.io/s/framer-motion-parallax-osm5p) one!

**Comment by InventingWithMonster** [comment]
Thanks natemoo! Totally forgot to update here

**Comment by imdevan** [comment]
> You may have discovered this already, but there are some [more examples](https://www.framer.com/api/motion/examples/#more) in the docs now, including this [Parallax](https://codesandbox.io/s/framer-motion-parallax-osm5p) one!

I believe the parallax image example is broken; are the images supposed to be parallax or just the containers around them?

**Comment by breadadams** [comment]
I've just checked out the example and can't help feel somethings off with it, by the time you get to the 5th of the 8 images all the parallax blocks have scrolled by already. Leaving the last 3 images without any floating magic 😿 .

Or maybe that was intentional in the example?

**Comment by opr-inzn** [comment]
Can anybody help me out with the Parallax example? I'd like to build the re-following the following scroll-behaviour: [https://www.johannclausen.com/?filter=Featured](https://www.johannclausen.com/?filter=Featured).

- Fade-In title
- On scroll, move it down, but stop after moving it 300px

I'm very knew to Gatsby (React) and Framer Motion, so any help would be appreciated. I found the .tsx example but couldn't get it to work 
`import { Override, useMotionValue, animate } from "framer"

// Declare the controls variable outside the other functions so we can access it from all of them
let contentOffsetY

// Apply this override to your scroll component
export function Scroll(): Override {
    contentOffsetY = useMotionValue(0)

    return { contentOffsetY }
}

// Smooth scroll to a value
export function SmoothScroll(): Override {
    return {
        onTap: () => {
            animate(contentOffsetY, -570, { duration: 1.5, ease: "easeOut" })
        },
    }
}`

and the example mentioned above is very hard for me to understand. In Vanilla JS this is quite easy, but learning React/Gatsby, I'd rather work with those resources.
