### ISSUE TITLE
[BUG] Springs cut off a little too early if interpolating complex value type

### ISSUE THREAD

**Issue by mattgperry** [framer/motion#1979]
```
initial: { x: '100%' },
animate: { x: 0, transition: { type: 'spring', stiffness: 2000, damping: 240 },
```

This animation gets cut off a little sooner than prefered. Consider lowering restDelta by a factor - `0.5` is fine for pixels but becomes too large for percentages.

**Comment by atsixian** [comment]
Hi @mattgperry, not sure if it's related to this issue, but I'm seeing the spring animation end abruptly in the end(the final downward movement). I used very small `restDelta` and `restSpeed`, but it's still abrupt. 

Here's the repro [CodeSandbox](https://codesandbox.io/s/framer-motion-spring-cut-off-end-53s9gq?file=/src/Square.tsx). 

https://github.com/framer/motion/assets/43892874/d0fdc413-a848-47d8-ac09-3d364cb8f7f1

**Comment by mattgperry** [comment]
This was since implemented
