### ISSUE TITLE
Calling motionValue.set(val) doesn't animate 

### ISSUE THREAD

**Issue by sami616** [framer/motion#198]
Calling .set and passing a value seems to snap the element into place instead of animating, is this expected behaviour?

**Comment by InventingWithMonster** [comment]
Yeah. You can create a value via useSpring https://www.framer.com/api/motion/motionvalue/#usespring and it’ll spring towards the new value. Or you can use animation controls if you’re after imperative animation controls https://www.framer.com/api/motion/animation/#animation-controls

**Comment by jamesplease** [comment]
@InventingWithMonster , is there any reason why `useSpring` exists, but not an analogous hook for curve-based transitions? For example,

```js
useCurve(10, {
  duration: 0.25,
  ease: 'easeOut'
})
```

**Comment by jamesplease** [comment]
Answering my own question above by cross-referencing #218 🙂
