### ISSUE TITLE
[BUG] Reorder Grid Issue (both axis)

### ISSUE THREAD

**Issue by piotrosmola** [framer/motion#1986]
Hi, I'm trying to create reordable grid component with Framer Motion, but it seems to be bit buggy. I mean it's hard to put an item between other two items. 

Example: https://codesandbox.io/s/framer-motion-5-drag-to-reorder-lists-forked-s8pst4

Is there any chance to improve it? Thanks in advance!

**Comment by piotrosmola** [comment]
Oh, thanks! I would be great to have it!

**Comment by niefufeng** [comment]
I would be great to have it!!!

**Comment by artemshchirov** [comment]
I would be great to have it!!!

**Comment by joi-lightyears** [comment]
> Hi, I'm trying to create reordable grid component with Framer Motion, but it seems to be bit buggy. I mean it's hard to put an item between other two items.
> 
> Example: https://codesandbox.io/s/framer-motion-5-drag-to-reorder-lists-forked-s8pst4
> 
> Is there any chance to improve it? Thanks in advance!

Hi, have you found the solution for this, I need it for my project

**Comment by OlegWock** [comment]
`sortable` from dnd-kit works very well with grids https://dndkit.com/

**Comment by joi-lightyears** [comment]
<img width="1330" alt="Screenshot 2024-04-19 at 20 46 59" src="https://github.com/framer/motion/assets/73181841/3d5c5704-4ac0-40eb-acee-393f70798380">
where do I find the code for this part, I clicked show code and it just one line
