### ISSUE TITLE
[BUG] Width 'auto' animation doesn't work when element is rotated

### ISSUE THREAD

**Issue by Tam** [framer/motion#1987]
When animating width from 'auto' on an element that has been rotated (either directly or via a parent element), the animation jumps.

https://codesandbox.io/s/keen-dewdney-gs037y

**Comment by chris-y-dev** [comment]
A further exploration into this bug, it appears that animating the width using any non-pixel value causes a bug. See examples below:

1. Using a percentage value (e.g. width: '100%') REMOVES this jump, BUT introduces a new bug, where the animation moves horizontally as well as vertically. This issue also only appears when element is rotated.

[https://codesandbox.io/s/intelligent-glitter-4wkcck](https://codesandbox.io/s/intelligent-glitter-4wkcck)

2. Using REM (eg width: '8rem') also replicates the jump noticed by Tam above.

[https://codesandbox.io/s/crimson-sunset-hnjqkk](https://codesandbox.io/s/crimson-sunset-hnjqkk)
