### ISSUE TITLE
[BUG] motion.text on Safari not working

### ISSUE THREAD

**Issue by lloydrichards** [framer/motion#1990]
**Describe the bug**

When using motion.text to create an animation, the initial state is stuck until you trigger a re-render.

[CodingSandbox](https://codesandbox.io/s/motion-text-bug-on-safari-xp6hu7)

**To reproduce**

1. Go to the Sandbox in Chrome and Safari
2. See the Chrome text animate larger
3. See the Safari text do nothing

I expect both to animate

**Comment by mattgperry** [comment]
Transforms looks broken in Webkit with `text` elements generally: https://9084rl.csb.app

Might be worth opening a reproduction for https://bugs.webkit.org

**Comment by lloydrichards** [comment]
I've gotten some traction on this [bug with webkit](https://bugs.webkit.org/show_bug.cgi?id=253259) in case anyone is dealing with the same issue.
