### ISSUE TITLE
[FEATURE] Add an option to visualise a viewport margin

### ISSUE THREAD

**Issue by JayBox325** [framer/motion#1995]
**Is your feature request related to a problem? Please describe.**
I have spent some time trying to work out when exactly the margin I've set is going to trigger animations.

**Describe the solution you'd like**
It could be a great time saver to have a `showMargin: true` option that renders an element that shows the margin you're setting so you know 100% where the trigger point is. Another bonus would be small info text specifying which line is what margin position.

**Describe alternatives you've considered**
I have added a div on top with a slightly transparent border of my desired margin, but a single line would possibly work better. 

**Additional context**
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/13233809/223015109-de0a3253-fa1e-4315-9655-6d24842d43fd.png">

**Comment by mattgperry** [comment]
I think this is a great idea but to set expectations closing this as `wontfix` as although it's something we might introduce to Framer it's unlikely to end up in React
