### ISSUE TITLE
[BUG] layoutId and position: sticky container

### ISSUE THREAD

**Issue by peksipatongeis** [framer/motion#1996]
layoutId animation inside `position: sticky` container are in some cases wonky. I was refactoring away from Framer Motion v4 with AnimateSharedLayout to layoutId when the animations started bugging. Navigation items with an active underline are acting weird when the page is scrolled and then navigated away. On the actual site it's also happening when switching between the pages but on the reduced test case I was only able to get to reproduce when clicking the same link item again. 

When the sticky container has `layoutRoot` and `layout` props then the functionality is similar to the bug I'm actually experiencing.

1. Go to [CodeSandbox](https://codesandbox.io/p/sandbox/framer-motion-layoutid-ccj0vk?file=%2Fcomponents%2FNavigation.tsx)
2. Scroll down on the page
3. Click on the active navigation element
4. See the active underline flying in

**Expected behavior**

Active underline item is expected to animate naturally

**Environment details**

Windows 11, Firefox 110.0.1 and Chrome 110.0.5481.178

**Comment by jamesvclements** [comment]
@peksipatongeis any luck on this? I have the same issue with a `layout` animation inside a fixed navbar. If you scroll down then navigate to another page, the element flies in from the bottom to the top of the page. It makes sense (it's transforming from it's scrolled position to the top page position) but that transformation should be relative to the fixed parent

**Comment by mattgperry** [comment]
Closing this as a `wontfix` as although `layoutScroll` does work for when the sticky element is in "fixed" mode its very difficult to determine when its in "fixed" vs "static" mode.
