### ISSUE TITLE
[BUG] [CodeSandbox 👍🏻] Can't `useSpring` on a `useTransform` MotionValue color: `'NaN' is not an animatable color. 

### ISSUE THREAD

**Issue by dxu** [framer/motion#2000]
When I try to use `useSpring` on a MotionValue

Here is a minimal CodeSandbox reproduction: https://codesandbox.io/s/goofy-grass-wq60h5?file=/src/App.tsx:391-406

If you comment out the `useSpring`, it works. 

When i console.log the `useTransform` motionvalue, it correctly prints out the rgba string, but this seems to break when fed into `useSpring`

The code snippet looks like this: 
```
const { scrollY } = useScroll();
  const colorStopValues = [
     // ... see sandbox 
  ];
  const finalColorValues = [
    // ... see sandbox, in the form of "#fbfdfe",
  ];
  const color = useTransform(scrollY, colorStopValues, finalColorValues);
  const springConfig = { stiffness: 700, damping: 80 };

  const colorSpring = useSpring(color, springConfig);
```

**Comment by mattgperry** [comment]
I've updated the documentation to clarify but `useSpring` is only compatible with numerical inputs. You could move it to work on scrollY and then pass the spring to useTransform?
