### ISSUE TITLE
[BUG] useScroll has issues when parallax example on the framer-website is animated by a scrollable div

### ISSUE THREAD

**Issue by JashandeepSinghGill** [framer/motion#2001]
I am recreating the parallax example on the website making it work with a scrollable container rather than the whole body scroll. 
When  the Parallax component is the first component on the Page it renders fine but when it is not the first the animations does not work.

This is the [codeSandbox](https://codesandbox.io/p/sandbox/objective-silence-5vpg8o?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A42%2C%22endLineNumber%22%3A21%2C%22startColumn%22%3A42%2C%22startLineNumber%22%3A21%7D%5D)

Just GO to the index.tsx in pages to see when it works and when it does not

**Comment by mattgperry** [comment]
Should be fixed in latest
