### ISSUE TITLE
[BUG] Switching pages with nextjs causes AnimatePresence and motion to animate incorrectly

### ISSUE THREAD

**Issue by bdlowery** [framer/motion#2002]
**Describe the bug**
I'm using nextjs. I have an animation that animates between the links I hover in the header.
When I scroll down the page and click a link on my sticky header, my animation animates from the bottom upwards, when there is no property to do that.

**IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[codesandbox link
](https://codesandbox.io/p/github/bdlowery/framer-bug-hover/main?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522clff4h819000kg6d5dafqce7o%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clff4h9jr00153b6ikzr6elvb%2522%253A%257B%2522key%2522%253A%2522clff4h9jr00153b6ikzr6elvb%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522clff4h9jr00163b6iou4tquau%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clff4hm8c008l3b6izflz7lgh%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252Fgallery%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clff4hkvd004n3b6idgh63xpu%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clff4h9jr00153b6ikzr6elvb%2522%252C%2522spacesOrder%2522%253A%255B%2522clff4h9jr00153b6ikzr6elvb%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

repo with bug - https://github.com/bdlowery/framer-bug-hover

**Steps to reproduce**
1. Scroll down the page, and click on any link in navigation.
2. The box appears at at a distance you scrolled (so if you scroll less it'll be closer to the link), and animates upwards to it's correct position.

**5. Expected behavior**
The animation should only move left and right between the links. 
When a user clicks on a link, the animation **shouldn't** reset, and animate to the top of the page.
The animation should just stay inside where it's defined.

**Video or screenshots**
YouTube video showing the expected behavior (first 8 seconds), then the bug for the rest.
[https://youtu.be/0LRd8ceR_Vo](https://youtu.be/0LRd8ceR_Vo)

**Environment details**
Chrome

**Comment by simonlagneaux** [comment]
I'm having the exact same issue, so I assume it hasn't been fixed?

**Comment by simonlagneaux** [comment]
I've solved it for now by using a useEffect() to scrolltop the window on route change.
