### ISSUE TITLE
[BUG] - broken layoutId animation with Next.js page change and scroll

### ISSUE THREAD

**Issue by ValentinH** [framer/motion#2006]
## Describe the bug

We are using `layoutId` to animate a current link indicator in our navbar (using fixed positioning) in a Next.js app. The animation works as expected during page navigation except when the page is scrolled. In that case, the initial position of the animation seems to be affected by the scroll offset. See this video:

https://user-images.githubusercontent.com/2678610/224677550-be7bfb11-1eba-45df-a190-77c7c3a99444.mov

## Steps to reproduce

1. Go to https://codesandbox.io/p/sandbox/adoring-albattani-qtdt3b?file=%2Fsrc%2FLayout.tsx
2. Scroll the page
3. Click on the "Page 1" link
4. The animation is incorrect

## Expected behavior

The animation should work regardless of the scroll.

## Environment details
- MacOS 13.2.1
- Chromium 110, Firefox 110  and Safari 16.3
- framer-motion: 10.2.4 

## Similar issues
This issue seems similar to https://github.com/framer/motion/issues/1580 but I created a new one because I'm not fully sure that's the same issue. Feel free to tell me to close this one and comment there. 🙏

**Comment by CRIMSON-CORP** [comment]
I have another work around🙂, in case this issue still persists in your work.

The idea is to make the parents of the nav and the main page to have the exact height of the screen, and make the content page or its descendant to overflow, that way, the sticky nav is never scrolled, and hence retains its position on the page so it doesn't fly around when the page is changed, this might seem hacky and all but it is the cleanest solution I was able to think off

checkout this spinoff of your sandbox
https://codesandbox.io/p/sandbox/adoring-albattani-qtdt3b?file=%2Fsrc%2FLayout.tsx

**Comment by CRIMSON-CORP** [comment]
Thank you @ValentinH, I've updated my comment

**Comment by minardimedia** [comment]
Anybody from the maintainers putting attention to this ?. This looks similar to something that can be fixed with parent <montion.div layout layoutRoot > the case is that it does not solve the issue. The <motion.div layoutId={"underline"}> elements keeps using the whole window to make is calculations for the transform so when you scroll and change from page the calculation is wrong. The whole point of layoutRoot in my opinion was to avoid this in the the first place but it does not work.

**Comment by n1ckoates** [comment]
Hi! Does anyone here know if there's a workaround for this when using the app router?

**Comment by simonlagneaux** [comment]
Same, this such a frustrating issue! I've tried a lot of workarounds but nothing seem to work.
Running Next.JS 13.5.4 and Framer Motion 10.16.4.

**Comment by simonlagneaux** [comment]
Update, this workaround worked for me: https://github.com/framer/motion/issues/1972#issuecomment-1483452870

**Comment by mattgperry** [comment]
You can also change the `nav` to `<motion.nav layout layoutRoot`

**Comment by ValentinH** [comment]
@mattgperry I just tried your suggestion and it doesn't seem to work: https://codesandbox.io/p/devbox/adoring-albattani-qtdt3b?file=%2Fsrc%2FLayout.tsx. Did I misunderstood something?

@simonlagneaux workaround works though. 🙏

**Comment by devashish2024** [comment]
For me, adding `style={{originY: '0px'}}` fixed. Thank god, I searched nearly 5 hours just for this.

**Comment by rochajulian** [comment]
> For me, adding `style={{originY: '0px'}}` fixed. Thank god, I searched nearly 5 hours just for this.

this works, thanks!!!! why though??

**Comment by highlydeveloped** [comment]
> For me, adding `style={{originY: '0px'}}` fixed. Thank god, I searched nearly 5 hours just for this.

Absolute legend - worked a treat

**Comment by alexsafayan** [comment]
does anyone have a good solution for elements that move in both axes?
