### ISSUE TITLE
[BUG] [DOCS] Layout animations troubleshooting section has a grammatical error

### ISSUE THREAD

**Issue by blenderskool** [framer/motion#2011]
**1. Read the [FAQs](#faqs) 👇**
Done!

**2. Describe the bug**
The documentation for layout animations here https://www.framer.com/motion/layout-animations/###the-content-stretches-undesirably seems to be worded incorrectly.

> This is a natural side-effect of animating width and height with scale. Some elements, **like those containing changing between different aspect ratios (commonly text elements)**, might be better animated with layout="position", which only animates the position of the element.

My guess is that the bold section should be worded like this
> like those containing elements changing between different aspect ratios (commonly text elements)

I don't think the docs website is open source right now. I can contribute the fix if that isn't the case 🙂 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
NA

**4. Steps to reproduce**
1. Go to https://www.framer.com/motion/layout-animations/###the-content-stretches-undesirably

**5. Expected behavior**
Fixed grammatical error

**6. Video or screenshots**
NA

**7. Environment details**
NA

**Comment by mattgperry** [comment]
Thanks, publishing fix now
