### ISSUE TITLE
[BUG] >=10.2.4 breaks "useScroll with spring smoothing"

### ISSUE THREAD

**Issue by beanduong** [framer/motion#2017]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

Starting from 10.2.4, passing `scrollYProgress` as a motion value to `useSpring` only seems to start the animation once the user stops scrolling. I think the animation does get called, but is being blocked by something.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-usescroll-with-spring-smoothing-forked-c52ht0
or use the `useScroll with spring smoothing` example

**4. Steps to reproduce**

1. Open the CodeSandbox
2. Scroll up and down
3. Using CodeSandbox toggle between version `10.2.3` and `10.2.4`
4. Observe different behaviours

**5. Expected behavior**

The progress bar should animate while scrolling the page.

**Comment by mattgperry** [comment]
I think I have a fix for this in `10.3.3` which has published though for some reason not yet available on npm.

**Comment by mattgperry** [comment]
Ah no not fixed yet, looking into it though
