### ISSUE TITLE
[FEATURE] XY for drag

### ISSUE THREAD

**Issue by Kelin2025** [framer/motion#202]
**Is your feature request related to a problem? Please describe.**
I wanted to make a sortable grid (like [this](https://clauderic.github.io/react-sortable-hoc/#/basic-configuration/grid?_k=9n8g96)) but figured out that there is support for either `x` or `y` direction only  
It would be amazing to have `xy`

**Describe the solution you'd like**
Add support for `xy` drag

**Comment by InventingWithMonster** [comment]
```
<motion.div drag />
```

:)
