### ISSUE TITLE
[BUG] Latest update "Invalid keyframe value for property clipPath: " bug

### ISSUE THREAD

**Issue by Rover420** [framer/motion#2029]
In the latest framer-motion version there is a bug, when I'm animating the sidebar menu open/close I get a bunch of warnings and second time I want to call there is no animation and lag

Version with bug: latest (^10.3.4)

Version without a bug: ^10.2.3

Here is the code I'm using: https://codesandbox.io/s/framer-motion-side-menu-mx2rw?from-embed

and here is a console with the bug: 
![bug](https://user-images.githubusercontent.com/100524342/225942192-23bfb102-f6d4-490c-aeef-95bfd14edd1e.jpg)

**Comment by baumgm94** [comment]
We faced the same issue. However, 10.6.1 fixed it! Appreciate your swift response!

**Comment by yunsii** [comment]
With v10.15.0, I still got these warning 
![image](https://github.com/framer/motion/assets/18096089/a943d148-1c48-4f22-a6fe-973beb6f3832)
![image](https://github.com/framer/motion/assets/18096089/c7cb5e54-8915-4192-a44c-1a21b2676489)
