### ISSUE TITLE
[BUG] framer-motion removes the page-scoped css properties before the exit animation finishes

### ISSUE THREAD

**Issue by dev-aly3n** [framer/motion#2031]
**1. Read the [FAQs](#faqs) 👇**
done

**2. Describe the bug**

I use Swiper carousel in a nextjs project. The CSS styles of Swipper were added directly to a specific page due to the size reduction of other pages that don't use swiper.

```jsx
//our-client.tsx

import "swiper/css";
import "swiper/css/autoplay";
```
 
There is also a page transition when the user route to another page.
the bug show up here: when you are on that page with swiper carousel and then route to another page, those specific CSS files that belong to swiper will remove instantly before the transition complete.

**4. Steps to reproduce**

1. add 3 pages in a nextjs project
2. add page transition effect with AnimatePresence
3. add swiper and its style to only one of these pages
4. change the route

**5. Expected behavior**

When a page unmounts with transition, all specific css that only belong to that page must remain in the app untill the end of the Exit transition.

**6. Video or screenshots**

This is a test that show the bug. 

I added the css import in the next page so when we route to next page **_swiper is ok_**

https://user-images.githubusercontent.com/79654879/226133740-305e70a3-a6ba-40a1-8a00-852804bee981.mp4

here the upper page doesn't contain the swiper css import and here you can see the bug.
 **_swiper not ok_**

https://user-images.githubusercontent.com/79654879/226133857-2238cd0d-fd9e-49c6-b723-20ddf95cb77a.mp4

(I increased the duration of transition to see the bug easier)

**Comment by mattgperry** [comment]
Feel free to re-open with a CodeSandbox reproduction.
