### ISSUE TITLE
[BUG] Re-rendering a component with an in-progress layout animation breaks the animation

### ISSUE THREAD

**Issue by mikirejf** [framer/motion#2034]
**1. Read the [FAQs](#faqs) 👇** 
✅ 

**2. Describe the bug**

If a component is hosting layout motion elements and is currently performing a layout animation, re-rendering the component will break the animation. I don't know if this is something that can be fixed within the library itself or if it's expected to be handled by the developers themselves?

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[Codesandbox](https://codesandbox.io/s/framer-motion-re-render-glitching-vml598?file=%2Fsrc%2FApp.js)

**4. Steps to reproduce**

1. Open the codesandbox link provided above.
2. Click on the "toggle state" button.
3. Observe how the animation plays out.
4. Comment out line 19 and repeat from step 2 to observe expected behavior.

**5. Expected behavior**

**6. Video or screenshots**

Broken:

https://user-images.githubusercontent.com/8895894/226574145-d33b6d2c-96dc-4c40-ad23-ae50f7dd88e0.mp4

Working as expected:

https://user-images.githubusercontent.com/8895894/226574356-a0300501-d730-4f8a-a2d4-0c7a242a2ed2.mp4

**Comment by mattgperry** [comment]
Dupe https://github.com/framer/motion/issues/1085
