### ISSUE TITLE
[BUG] Shared Layout animations don't work if parent has animation Config or Variants

### ISSUE THREAD

**Issue by CRIMSON-CORP** [framer/motion#2036]
**1. Read the [FAQs](#faqs) 👇**
✅

**2. Describe the bug**
Shared Layout animations don't work if parent has animation Config or Variants

Give a clear and concise description of what the bug is.
Shared layout animations and transitions fail to work if a motion parent in the tree has some animation config like initial, animate, exit props or if the motion parent uses variants

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**
https://codesandbox.io/p/sandbox/competent-mccarthy-wg2bic?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A3%2C%22endLineNumber%22%3A116%2C%22startColumn%22%3A3%2C%22startLineNumber%22%3A116%7D%5D

**4. Steps to reproduce**

1. Go to the code sandbox project via the link above
2. Click on any of  Email or Push notification buttons and note the underline indicator fails to animate between the two
3. Comment out line 123 where the variant props is added to the motion parent Wrapper
4. save refresh and note that the indicator now moves between the two buttons

**5. Expected behavior**

I need motion children Shared layout animation to work regardless of whether it has a  motion parent or not

**6. Video or screenshots**

https://user-images.githubusercontent.com/71358573/226646813-e3e2051f-e9d0-4cc3-ac1b-c9eca04979e4.mp4

If applicable, add a video or screenshots to help explain the bug.

**7. Environment details**

If applicable, let us know which OS, browser, browser version etc you're using.

- OS - Windows 11 Professional
- Browser - Chrome
- Broser Version - Version 111.0.5563.65 (Official Build) (64-bit)

**Comment by mattgperry** [comment]
The problem specifically is layout animations aren't compatible with `%` transforms and this is probably a wontfix.

**Comment by CRIMSON-CORP** [comment]
> The problem specifically is layout animations aren't compatible with `%` transforms and this is probably a wontfix.

Sorry please I don't understand this, are you referring to the x transform on the parent? because I've removed it and changed it to pixel values and it still doesn't animate

**Comment by Julian24Design** [comment]
@mattgperry Any workaround for this issue? Thank you.
