### ISSUE TITLE
[BUG] Animation flickering on Firefox and "moving" right next to the end of the seconds in Chrome

### ISSUE THREAD

**Issue by hrqmonteiro** [framer/motion#2038]
Firefox:

https://user-images.githubusercontent.com/17055027/226767593-f5c8e2c9-0c80-4d9f-aada-9076540e1da0.mov

Chrome:

https://user-images.githubusercontent.com/17055027/226767605-02dda359-a9ae-4a65-b360-f13ccab10052.mov

Is the simplest animation that is:

```
          <motion.h1
            animate={{ y: 0, opacity: 1 }}
            initial={{ y: 20, opacity: 0 }}
            className='text-xl md:text-4xl lg:text-4xl font-medium'
            transition={{ duration: 2, delay: 0, type: 'spring' }}
          >
            Henrique Monteiro.
          </motion.h1>
```

```
<motion.h2
              animate={{ opacity: 1 }}
              className='w-full text-4xl md:text-7xl lg:text-8xl xl:text-9xl 2xl:text-10xl flex justify-start font-extrabold my-10'
              initial={{ opacity: 0 }}
              style={{ x }}
              transition={{
                duration: 3,
                delay: 1,
                type: 'spring'
              }}
            >
              full stack developer
            </motion.h2>
```

```
<motion.div
            animate={{ y: 0, opacity: 1 }}
            initial={{ y: 20, opacity: 0 }}
            transition={{
              duration: 2,
              delay: 0,
              type: 'spring'
            }}
          >
          {children}
          </motion.div>
```

I am using Next 13, for information purposes.

![Screenshot 2023-03-21 at 8 56 16 PM](https://user-images.githubusercontent.com/17055027/226767825-82590d0c-6701-4c06-a13f-bbe8a2e1c565.png)

**Comment by iUnstable0** [comment]
try version 8.5.4

**Comment by iUnstable0** [comment]
@hrqmonteiro ? was the issue resolved? if so please share how you did it as i’m experiencing this issue too

**Comment by hrqmonteiro** [comment]
> @hrqmonteiro ? was the issue resolved? if so please share how you did it as i’m experiencing this issue too

Not resolved, even with new version. I just gave up using it.

**Comment by iUnstable0** [comment]
@hrqmonteiro have you tried version 8.5.4?

**Comment by hrqmonteiro** [comment]
> @hrqmonteiro have you tried version 8.5.4?

Yes. Unfortunately nothing changed.

**Comment by jesspinklet** [comment]
I am having the same problem.
@hrqmonteiro  just because you gave up you shouldn't close the issue

Using motion 12.0.6

**Comment by mattgperry** [comment]
Can you open a new issue with a sandbox reproduction if you’re still experiencing this?

**Comment by jesspinklet** [comment]
> After further investigation, I found that opacity flickering is because of the initial value of `opacity-0` tailwind class. Somehow it works on edge and chrome, but in firefox, when animation is done that tailwind class (because of the cascading maybe) causes this problem.
> 
> Setting initial value by inline css or just pure css will fix it.
> 
> I couldn't use stackblitz for reproduction of tailwind v4 but with only pure css opacity initial value animation works.

My bad I found the problem https://stackblitz.com/edit/nuxt-starter-wjvgzojc?file=app.vue
Having transition on element on firefox will bug the animation
