### ISSUE TITLE
[BUG] `attrX` / `attrY` are not included in the typings for motion SVG elements

### ISSUE THREAD

**Issue by jordan-burnett** [framer/motion#2044]
According to the docs, I can use `attrX` and `attrY` to animate the value of the `x` and `y` attributes of an SVG element directly:

> SVG note: For SVG components, x and y attributes (as opposed to the transform style) can be set using attrX and attrY within animation props.

This appears to work as intended, and the code runs correctly however the typescript compiler throws an error. Example sandbox below:

![image](https://user-images.githubusercontent.com/2143374/227183374-92b8a8bf-42bd-40d4-81fb-1a265e2a7261.png)

Example sandbox:

https://codesandbox.io/s/ecstatic-bessie-38e7kj?file=/src/App.tsx

**Comment by liwn9527** [comment]
The sandbox is empty.

**Comment by TommySorensen** [comment]
Related: #2091
