### ISSUE TITLE
[BUG] AnimatePresence triggers animation twice when animating 'backdropFilter' with nested children 

### ISSUE THREAD

**Issue by utileetdulce** [framer/motion#2049]
**1. Read the [FAQs](#faqs) 👇**
check

**2. Describe the bug**

When using AnimatePresence with nested children where the outer children animates `backdropFilter: "blur()"` its animation is triggered again, when the inner child triggers its animations. It behaves as expected when the outer child has a css background set with a non transparent background color. (see line 26 in the codesandbox)

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[codesandbox](https://codesandbox.io/s/framer-motion-animate-presence-test-8bvkr9?file=/src/app.module.css)

**4. Steps to reproduce**
1. Click the "Toggle presence" button once to mount the AnimatePresence children.
2. Click again to unmount them.

**5. Expected behavior**

The codesandbox example contains two AnimatePresence children. The upper one with the green background shows the expected behavior: The outer children animates in with opacity ("beforeChildren") and the inner child animates in with opacity after the outer child has finished the enter animation. On unmount the the inner child fades out first and the outer child when the inner child has finished its exit animation.

**6. Video or screenshots**

<video src='https://user-images.githubusercontent.com/40870660/227466765-2243abd8-db29-44ea-8ba4-fae6e9d8aa1e.mp4' width=180/>

**7. Environment details**

macOS 12.6 
Chrome Version 111.0.5563.110 (Official Build) (x86_64)

**Comment by mattgperry** [comment]
This isn't related to Motion or `AnimatePresence`. You can see quick evidence of this two ways:

1. Change to `webkitBackgroundBlur` and animate in Safari
2. In the elements panel select the inner `div` (the one animating opacity) and in the console run `$0.animate({ opacity: 0.5 }, { duration: 5000 })`
