### ISSUE TITLE
Sticky box hiding content on website.

### ISSUE THREAD

**Issue by Mohammed-Yasin-Mulla** [framer/motion#2050]
This is regarding the  `https://www.framer.com/motion/`  documentation page
There is a box that I believe is positioned sticky to the screen

The box covers the content of the page, making it difficult to read the document's indexes, clicking on it does not have any effect on the box

 Steps to reproduce
 
1) visit the website: `https://www.framer.com/motion/`  
2) on scrolling the box appears hiding the content of the page

NOTE: This box randomly appears in view, does not happen every single time when opening new tabs

https://user-images.githubusercontent.com/55092280/227494848-e3ad35da-d6b5-49fb-90e4-7570b546b38d.mov

**Comment by Mohammed-Yasin-Mulla** [comment]
Hey,

**NOTE: This box randomly appears in view, does not happen every single time when opening new tabs** 

I will be more than happy to contribute to the website development by fixing the bug. 
Please mention which repository it is in, I was unable to find it.

**Comment by mattgperry** [comment]
Thanks for the notice - we're hopefully porting the page to Framer this year at which point this will be addressed.
