### ISSUE TITLE
[FEATURE] useSpring (optional length parameter)

### ISSUE THREAD

**Issue by sami616** [framer/motion#206]
Im struggling to figure out how i might rewrite the following example if there was an indefinite number of cards in the UI.

https://codesandbox.io/s/happy-bhabha-i3q10

As you can see Ive manually declared springs at the top for each of my cards, each using the last as a base:

```
  const frontX = useMotionValue(0)
  const middleX = useSpring(frontX, spring)
  const backX = useSpring(middleX, spring)
```

My initial thought was to map through an array of cards and create a spring for each one to later iterate through in my return, but quickly remembered that you cant use hooks inside closures.

Does something like `useSprings` exist in the API where you might be able to pass a base `motionValue` & `springConfig` and returns an array of springs, each based on the last? Another use case for something like this might be chatheads.

Thanks!

**Comment by InventingWithMonster** [comment]
I'm not a fan of the subtley-different plural hook but I can image returning a number of hooks based on an optional length parameter.

```jsx
const [a, b, c, d, e] = useSpring(x, config, 5)
```

One thing I'd say for now is that you **can** run hooks in a closure as long as that closure is guaranteed to run the **same way** every render (which you can enforce yourself).

So if you want 5 hooks from `useSpring`

```jsx
let prev = x
const springs = []
for (let i = 0; i < 5; i++) {
  const spring = useSpring(prev, config)
  springs.push(spring)
  prev = spring
}
```

**Comment by sami616** [comment]
> I'm not a fan of the subtley-different plural hook but I can image returning a number of hooks based on an optional length parameter.

☝ This sounds great. I agree, the subtle name difference might end up causing confusion. Would it be something you might consider for a future release? Thanks for the tip on hooks within closures, i'll go with that for now!

**Comment by InventingWithMonster** [comment]
Yeah it's for sure something I'll consider, I totally get the use-case

**Comment by mattgperry** [comment]
Closing this as we'll probably not add this to the core library, it's more a utility that can be achieved for now with the above snippet.
