### ISSUE TITLE
[BUG] Setting the speed value of the new animate feature to -1 does not reverse play.

### ISSUE THREAD

**Issue by sukjae** [framer/motion#2060]
**1. Describe the bug**

Setting the speed value of the new animate feature to -1 does not reverse play as mentioned in the document.
<img width="499" alt="image" src="https://user-images.githubusercontent.com/8156543/229003145-faf2ac0e-b628-41af-8816-20e74cfc1b3c.png">
https://www.framer.com/motion/animate-function/###speed

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/great-cherry-pxgogh?file=/src/App.js:1073-1219

**3. Steps to reproduce**

1. open codesandbox
2. click play button on reverse section (This is the bottom example.)

**5. Expected behavior**

```js
const animation = animate(".four", { x: [0, 100] });
animation.speed = -1;
```

I expected to start at 100 and end at 0 and then stay fixed at 0.

However, only a slight shaking occurs at the moment, but it does not work.

**Comment by mattgperry** [comment]
It will play from its current position. So you'd first need to set

```javascript
animation.time = animation.duration
```

**Comment by sukjae** [comment]
> It will play from its current position. So you'd first need to set
> 
> ```js
> animation.time = animation.duration
> ```

Unfortunately, it still doesn't work. Is there anything to do with this PR?

https://github.com/framer/motion/pull/2068

Sample Code: https://codesandbox.io/s/thirsty-firefly-d0zv50?file=/src/App.js
