### ISSUE TITLE
[BUG] - MotionCanvas not working with vite

### ISSUE THREAD

**Issue by moonraker22** [framer/motion#2062]
## Bug with MotionCanvas  and R3F with vite as environment

I've tried on both codesandbox which I think now uses vite under the hood, and in my own vite projects and always get the same error when I replace R3F canvas with MotionCanvas. The error is related to the materials in the scene and says {material} is not part of the THREE namespace! Did you forget to extend? I've seen the previous codesandboxes using create react app that work and have tried the exact same code to no avail.

[Codesandbox with bug](https://codesandbox.io/s/framer-motion-bug-pf7igu?file=/src/App.tsx)

[Codesandbox working with create-react-app instead of vite](https://codesandbox.io/s/framer-motion-3d-layoutcamera-i84e3?from-embed=&file=/src/Scene.js)

**Comment by hi6724** [comment]
I faced same bug. 
just add `Canvas` under `MotionCanvas` and give style `display:none` to `Canvas` 
like this

```tsx
export default function App() {
  return (
    <>
    <MotionCanvas>
      <directionalLight intensity={0.5} />
      <Scene />
    </MotionCanvas>
    <Canvas style={{display:"none"}}>
    </Canvas>
    </>
  );
}

```

**Comment by moonraker22** [comment]
Cool thanks for the reply I'll give that a shot

**Comment by syarif-studio** [comment]
Add something like this


```
import { Mesh, BoxGeometry, MeshStandardMaterial, Group } from 'three'

extend({ Mesh, BoxGeometry, MeshStandardMaterial, Group })
```

check this link : [canvas-tree-saking](https://docs.pmnd.rs/react-three-fiber/api/canvas#tree-shaking)
