### ISSUE TITLE
exit animation not working

### ISSUE THREAD

**Issue by SyedImam1998** [framer/motion#2063]
### Issue:
 The exit animation not working as expected. Here is the codeSandbox [Link](https://codesandbox.io/s/floral-resonance-cj751r?file=/src/App.js)
 
 I am using framer-motion-10.9.1 Can someone please help here Why?

**Comment by CRIMSON-CORP** [comment]
Hello, to allow elements perform exit animations, you meed to wrap the element in an AnimatePresence component like so https://codesandbox.io/s/floral-resonance-cj751r?from-embed=&file=/src/App.js

You can read more about ot from the Docs here https://www.framer.com/motion/animate-presence/

**Comment by SyedImam1998** [comment]
Thanks for the Quick help brother !!!!
