### ISSUE TITLE
Next.js 13 “use-client” standardization 

### ISSUE THREAD

**Issue by rafelis1997** [framer/motion#2066]
**Is your feature request related to a problem? Please describe.**
Right now motion is no able to be directly imported on server components on app directory on Next.js projects, basically it is considered a hook and hooks cannot be used in server components, so we have to create a “use-client” component exporting every motion.[tag] we need to use on the project 

**Describe the solution you'd like**
My solution to this is build a branch for framer to Next.js where motion will be already exported as “use-client” for every tag, so user can use it just like they used too

**Describe alternatives you've considered**
Another alternative is to export components for each tag with the “use-client” declaration on each component

**Comment by mattgperry** [comment]
Dupe https://github.com/framer/motion/issues/2054
