### ISSUE TITLE
[BUG] m component not working

### ISSUE THREAD

**Issue by federicocappellotto97** [framer/motion#2070]
With new Next.js version 13.3 **m** component is not working. Instead **motion** does work

**Comment by dromn1** [comment]
is this why when I add "motion" to the div doesn't work ?

**Comment by federicocappellotto97** [comment]
> is this why when I add "motion" to the div doesn't work ?

Actually for me <motion.div> is working. <m.div> instead, it’s not working

**Comment by mattgperry** [comment]
Please reopen with sandbox

**Comment by mikolyants1** [comment]
I have a similar bug , could you help me ? I use  "framer-motion": "^12.12.2",
"next": "^15.3.2",
