### ISSUE TITLE
Trying to copy the example but it does not work as shown in the example

### ISSUE THREAD

**Issue by kachkolasa** [framer/motion#2072]
![image](https://user-images.githubusercontent.com/72012513/230730612-1e9dc56b-f8a2-483e-86dd-b13c5029c113.png)

I see this example and when I tried with the code provided, it works but not as expected or shown in the example. 

I did some searching and found some other examples that work as the one in the home page in home page of framer motion but the problem is that those codes are from the v3. 

So can I still copy the example shown in the latest version?
Thanks!

**Comment by kachkolasa** [comment]
Ops! My bad, it works but there was some misconfiguration from my side.

**Comment by ACHIYANT** [comment]
> Ops! My bad, it works but there was some misconfiguration from my side.

can you please provide the working code for these cards ?

**Comment by kachkolasa** [comment]
![image](https://github.com/framer/motion/assets/72012513/bfa7e6f7-557e-4f2a-aa5d-3e8f6262037d)
![image](https://github.com/framer/motion/assets/72012513/67972465-fa8e-4f70-8630-1397c7184b29)

Hello, 
This might help!
The live version is here: kachkolasa.com/projects
