### ISSUE TITLE
[BUG] cannot use next/router & recoil

### ISSUE THREAD

**Issue by hi6724** [framer/motion#2073]
I cannot use next/router & recoil in MotionCanvas
when I use recoil inside of `MotionCanvas` I have to use `RecoilBridge`
and if I want to use `next/router` inside of `MotionCanvas ` I have to pass prop `router`

```tsx
  const RecoilBridge = useRecoilBridgeAcrossReactRoots_UNSTABLE();
  return   (
        <MotionCanvas>
          <RecoilBridge>
            <SomeMeshComponent1 router={router} />
            <SomeMeshComponent2 />
          </RecoilBridge>
        </MotionCanvas>
)
```

**Comment by mattgperry** [comment]
Hi, it's unlikely we'll be able to look at this particular setup so closing as `wontfix` for now.
