### ISSUE TITLE
[BUG] R3F: AmbientLight is not part of the THREE namespace! Did you forget to extend?

### ISSUE THREAD

**Issue by hi6724** [framer/motion#2074]
![image](https://user-images.githubusercontent.com/68803719/230756071-95778b3e-1254-40e1-8f15-4803e483d273.png)

When I use `MotionCanvas` I face this Error here is my code
```tsx
import { MotionCanvas } from 'framer-motion-3d';

function UserProfile() {
  return (
    <div>
      <MotionCanvas>
        <mesh>
          <boxGeometry />
        </mesh>
      </MotionCanvas>
    </div>
  );
}

export default UserProfile;
```
But, if I add `Canvas` with display none this error was deleted.
```tsx
import { Canvas } from '@react-three/fiber';
import { MotionCanvas } from 'framer-motion-3d';

function UserProfile() {
  return (
    <div>
      <MotionCanvas>
        <mesh>
          <boxGeometry />
        </mesh>
      </MotionCanvas>
      <Canvas style={{ display: 'none' }}>
        <mesh></mesh>
      </Canvas>
    </div>
  );
}

export default UserProfile;
```

**Comment by gonghaibo** [comment]
I also encountered this issue and spent a lot of time troubleshooting. Later, I found out that the version number in the demo was 5.5.5, but the latest version number is already 10.X.

**Comment by TheBigSasha** [comment]
I also get this issue. Everything works if I use an R3F::Canvas, but I get the `R3F: <elementname> is not part of the THREE namespace! Did you forget to extend?` for any R3F or framer-motion-3d component inside the Canvas. I tried solving using `	extend({ MotionCanvas, motion3d });` to no avail. Does anyone have a working sandbox of framer-motion-3d with a recent version or is MotionCanvas just borked?

**Comment by syarif-studio** [comment]
Add something like this


```
import { Mesh, BoxGeometry, MeshStandardMaterial, Group } from 'three'

extend({ Mesh, BoxGeometry, MeshStandardMaterial, Group })
```

check this link : [canvas-tree-saking](https://docs.pmnd.rs/react-three-fiber/api/canvas#tree-shaking)

**Comment by gregnr** [comment]
If you don't care about tree shaking and wish to have the same functionality as a regular `<Canvas>` the solution is:

```ts
import { extend } from '@react-three/fiber';
import { MotionCanvas } from 'framer-motion-3d';
import { useMemo } from 'react';
import * as THREE from 'three'

export default function MyComponent() {
  useMemo(() => extend(THREE), []);

  return (
    <MotionCanvas>
      ...
    </MotionCanvas>
  );
}
```

Which will extend the entire THREE catalog [as is done](https://github.com/pmndrs/react-three-fiber/blob/f3d92751d1c22533f10879eb7fd6bb075c674c46/packages/fiber/src/web/Canvas.tsx#L65-L68) in the real `<Canvas>` component.

As of R3F v8, the underlying reconciler no longer pulls in the THREE namespace automatically and instead moves this logic directly to the `<Canvas>` component (giving you the flexibility to tree shake if you implement your own `<Canvas>`).  It appears `<MotionCanvas>` [doesn't carry over](https://github.com/framer/motion/blob/fb227f8b700c6e2d9c3b33d0a2af1a2d2b7849e9/packages/framer-motion-3d/src/components/MotionCanvas.tsx) the THREE extend logic, so you have to do it yourself now.

**Comment by mattgperry** [comment]
This is in the docs so closing but good to know there is a fix of sorts that I might look at if we get back to Three.js
