### ISSUE TITLE
[BUG] useScroll with container doesn't take viewport position into consideration.

### ISSUE THREAD

**Issue by bitttttten** [framer/motion#2076]
When using `useScroll` and a `container`, if that `container` is positioned somewhere in the document then it's position relative to the viewport doesn't get taken into consideration. It acts like `container` is always at the top of the viewport.

Take this pen, where the header has a height of 0, and main (the `container`, in this case) has a height of "80vh". Everything works as expected: https://codesandbox.io/s/framer-motion-track-element-position-forked-n5kvte?file=/src/App.tsx

Now if make the header have a height of "10vh", you can see it doesn't report the scroll position accurately: https://codesandbox.io/s/framer-motion-track-element-position-forked-fc84g3?file=/src/App.tsx

Interesting to note, if you look at the second "broken" pen, you can see that when the element reaches the top of the _viewport_ is when the scroll progress reaches 100%.

** Expected behavior**

It takes the scrollYProgress into consideration when a container element is somewhere else in the document.

**Comment by bitttttten** [comment]
Perhaps this is the intended behaviour, as I am seeing inside `measure` that it only checks the position from the target to the container:

```tsx
if (target !== container) {
```

from

https://github.com/framer/motion/blob/5ac4934ce5fe909116a0b9816268442ae6fe9909/packages/framer-motion/src/render/dom/scroll/on-scroll-handler.ts#L15

I imagine for my use case I would want this to be `if (target !== document.documentElement)` ?

**Comment by coratype** [comment]
having the same problem. have a container centered thats about 200x200 and can be scrolled through, but the offset only tracks in relation to the top of the viewport not the container even though i have the container specified

**Comment by EntropyReversed** [comment]
@bitttttten  Did you manage to find some fix for this one?

**Comment by bitttttten** [comment]
@EntropyReversed I just wrote my own code in the end. I looked into framer motion's source code and copied the useScroll code into my own project, then just edited it :)

**Comment by coratype** [comment]
> @bitttttten Did you manage to find some fix for this one?

creating a new container absolutely positioned within the fixed container worked for me

**Comment by mattgperry** [comment]
This should be fixed in `10.17.5`
