### ISSUE TITLE
[FEATURE] Opt-in layout animations on window resize

### ISSUE THREAD

**Issue by pacocoursey** [framer/motion#2077]
**Is your feature request related to a problem? Please describe.**

I'd like to use layout animation on items of a navigation UI that hide or show depending on the size of the browser window. However, layout animations were disabled on window resize in #1256 without a reason — but I'm guessing for improved performance.

**Describe the solution you'd like**

Add a new prop, `layoutResize`, which re-enables layout animations on window resize. This is similar to the existing way we can opt-in to more expensive layout calculation using the `layoutScroll` prop.

**Describe alternatives you've considered**

There really isn't an alternative besides manually re-implementing layout animations myself, or delaying animations until after the 250ms resize delay. The first is unrealistic, and the second is too slow. I use framer motion to build smooth 120fps interfaces, not 4fps interfaces!

**Additional context**

Here's a simple CodeSandbox demonstrating how layout animations do not work on window resize, which could be used for a future test case:

https://codesandbox.io/s/cool-wozniak-imgggl?file=/src/App.js

**Comment by mattgperry** [comment]
I'm marking this as a `wontfix` to set expectations that we probably won't implement this. We disabled it for Framer as resizing is much smoother when we're not triggering or performing layout animations and most people were complaining when their layout animated on resize.

**Comment by kincaidoneil** [comment]
I'd also appreciate a flag to enable this. I have a UI effect that continuously rearranges and animates a grid. Scrolling in iOS Safari show/hides the toolbar, which causes the layout animation to stop momentarily.
