### ISSUE TITLE
[BUG] setting speed to -1 does not reverse play

### ISSUE THREAD

**Issue by sukjae** [framer/motion#2079]
**1. Read the [FAQs](#faqs) 👇**
🙆‍♂️

**2. Describe the bug**

related to https://github.com/framer/motion/issues/2060
and https://github.com/framer/motion/issues/2060#issuecomment-1501896461

```js
const animation = animate(".four", { x: 90 }, { duration: 2 });
animation.time = animation.duration;
animation.speed = -1;
```

**3. Provide a CodeSandbox reproduction of the bug**

Sample Code: https://codesandbox.io/s/thirsty-firefly-d0zv50?file=/src/App.js

**4. Steps to reproduce**

1. check version of framer motion is v10.11.4
2. press play button

**5. Expected behavior**

move from end position to start position

**Comment by mattgperry** [comment]
Ah yeah it could be because setting the animation to duration itself finishes the animation.

I can take a look.

**Comment by sukjae** [comment]
hi @mattgperry ! Is there any progress related to it? I'm looking forward to it a lot 🙏
