### ISSUE TITLE
[BUG] useSpring does not follow MotionValue animated with animate()

### ISSUE THREAD

**Issue by hatsumatsu** [framer/motion#2088]
Using `useSpring` with `useMotionValue`, I expect the spring to follow the MotionValue. However, when animating the MotionValue via `animate()` —f.e. for sequencing animations— the spring is acting weird.

https://codesandbox.io/s/pedantic-greider-2r39t3

In this example we create a MotionValue and a Spring that follows that value

````js
const x = useMotionValue(0);
const xSpring = useSpring(x, {...config});
````

To debug the animation we add two `<motion>` components, one using the MotionValue and the other the Spring in their style prop.

Setting the Motionvalue via `set()` works as expected: The motion component using the MotionValue updates immediately, while the component using the Spring is smoothly animated.

Animating the MotionValue via `animate()` as described in [the docs](https://www.framer.com/motion/animate-function/##animate-a-motionvalue ) animates the first component smoothly while the second one moves unreliably.
This means that currently you can't use `.set()` and `animate()`side-by-side.

Maybe I'm using the API all wrong, but I would expect the Spring to follow the MotionValue smoothly.

**Comment by mattgperry** [comment]
No that's definitely weird, I can take a look

**Comment by hatsumatsu** [comment]
@mattgperry do you have a hint for me how I could work around this bug? Would be so cool to be able to use both declarative `<motion>` elements with injected motion values and imperative `animate()` side by side.
