### ISSUE TITLE
[BUG] Animate height “0” to “auto” when switching to “display: block” from “none”

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [framer/motion#209]
Animating height from `0` to `auto` not is working properly when switching to `display: block` from `display: none`:

![accordion-bug](https://user-images.githubusercontent.com/13482427/61403744-43794700-a8d6-11e9-877e-81420b0212cb.gif)

According to the [Migrate from Pose](https://www.framer.com/api/motion/migrate-from-pose/#applyatstart%2Fapplyatend) documentation, _non-animatable properties are automatically applied at the start of an animation. Anything that you want to be applied at the end can be set to `transitionEnd`_.

The bug occurs with the following combination of properties:
```
{
  open: { display: "block", opacity: 1, height: "auto" },
  collapsed: { opacity: 0, height: 0, transitionEnd: { display: "none" } }
}
```

**To Reproduce**
1. Go to https://codesandbox.io/s/framer-motion-accordion-o0to4
2. Click on the accordion headers
4. Animation doesn’t work as expected on open (works fine on close)

**Expected behavior**
Smooth animation on opening and closing the accordion:

![accordion-expected](https://user-images.githubusercontent.com/13482427/61403761-48d69180-a8d6-11e9-89f3-728e72d28f80.gif)

This works fine **in Pose** using the following combination of properties:
```
{
  open: {  opacity: 1, height: "auto" , applyAtStart: { display: "block" } },
  collapsed: { opacity: 0, height: 0, applyAtEnd: { display: "none" }
}
```

**Comment by InventingWithMonster** [comment]
Yeah good catch. I'll dig into this.

**Comment by conor-cafferkey-sociomantic** [comment]
Thanks!
