### ISSUE TITLE
When changing layout (flex-direction) with animation on hover, sometimes the content jumps unexpectedly, is my code wrong?

### ISSUE THREAD

**Issue by muchisx** [framer/motion#2107]
Hi! ☀️

So as I described in the title, I'm using an animation on the change of layout, namely the flex direction and sometimes the animations behaves weirdly, more specifically when the cursors traverses the element too fast.

I have a fairly complex Button Component where I'm using it and I'm also using styled-components.

### Here's a demo of the issue:
https://user-images.githubusercontent.com/34131801/235388017-3d1eb22c-9a97-4351-921f-5468f31e33a2.mp4

You can see that when I hover slowly it works well, but when I hover too fast it goes crazy!

### Here's the code for the parent component:

```
import { useState } from 'react';
import { SpanStyled, ButtonStyled, Container, IconWrap, LinkStyled } from './Button.styles';
import type { Props } from './Button.types';

function Button(props: Props) {
  const { role, to, text, variant, Icon, action, className, newTab, rel } = props;
  const target = newTab ? '_blank' : '_self';
  const [isHovered, setIsHovered] = useState(false);

  const handleHover = () => {
    setIsHovered((current: boolean) => !current);
  };

  const buttonContent = (
    <>
      {text && <SpanStyled layout>{text}</SpanStyled>}
      {Icon && (
        <IconWrap layout>
          <Icon size={16} />
        </IconWrap>
      )}
    </>
  );

  const hoverAnimation = (buttonIcon?: Props['Icon'], buttonText?: Props['text']) => {
    const animation =
      buttonIcon && buttonText ? undefined : { scale: 1.1, transition: { ease: 'circIn', duration: 0.4 } };
    return animation;
  };

  return (
    <Container
      variant={variant}
      text={text}
      Icon={Icon}
      onMouseEnter={handleHover}
      onMouseLeave={handleHover}
      whileHover={hoverAnimation(Icon, text)}
      onClick={action}
      className={className}
      isHovered={isHovered}
    >
      {role === 'button' ? (
        <ButtonStyled>{buttonContent}</ButtonStyled>
      ) : (
        <LinkStyled to={to ?? ''} target={target} rel={rel}>
          {buttonContent}
        </LinkStyled>
      )}
    </Container>
  );
}

Button.defaultProps = {
  text: undefined,
  className: undefined,
  Icon: undefined,
};

export default Button;

```

### And here's the code for the styled component:

```
import styled, { css } from 'styled-components';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import type { Props } from './Button.types';

type ContainerProps = {
  Icon?: Props['Icon'];
  variant: Props['variant'];
  text?: Props['text'];
  isHovered: boolean;
};

export const ButtonStyled = styled(motion.button)``;
export const LinkStyled = styled(motion(Link))``;
export const SpanStyled = styled(motion.span)``;
export const IconWrap = styled(motion.div)``;
export const Container = styled(motion.div)<ContainerProps>`
  flex-shrink: 0;
  width: fit-content;
  height: fit-content;
  cursor: pointer;
  border-radius: ${(props) => (props.text ? '100px' : '50%')};
  color: var(--btn-color-text-${(props) => props.variant});
  background: var(--btn-color-bg-${(props) => props.variant});
  border: 1px solid var(--btn-color-border-${(props) => props.variant});
  padding: ${(props) => (props.text ? (props.Icon ? '.2rem .2rem .2rem 1.4rem' : '.7rem 1.4rem') : '.6rem')};
  transition: padding 200ms ease-in-out;

  &:hover {
    ${(props) => props.text && props.Icon && 'padding: .2rem 1.4rem .2rem .2rem '};
  }

  & ${IconWrap} {
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 50%;
    color: var(--btn-color-${(props) => (props.text ? `icon-${props.variant}` : `text-${props.variant}`)});
    ${(props) =>
      props.text &&
      css`
        padding: 4px;
        background-color: var(--btn-color-icon-bg-${props.variant});
      `}
  }

  & ${LinkStyled}, ${ButtonStyled} {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 1rem;
    background: none;
    font-size: 1.4rem;
    line-height: 1;
    cursor: pointer;
    ${(props) =>
      props.isHovered &&
      props.Icon &&
      props.text &&
      css`
        flex-direction: row-reverse;
      `}
  }

  & ${LinkStyled} {
    color: inherit;
    text-decoration: none;
  }

  & ${SpanStyled} {
    line-height: 1;
  }
`;

```

</div>

**Comment by muchisx** [comment]
I have this problem too with the other version of my component (just with the scale animation), here's the demo, any help?


https://user-images.githubusercontent.com/34131801/236090681-3a70943e-79d3-44a8-aceb-94aee0165f8f.mp4

As you can see above, the animation only worked like 2 times, most of the hovers just went immediatly to the final state (1.1 scale) how can I assure consistency in my hover animations?

**Comment by mikirejf** [comment]
@muchisx I suggest you provide a codesandbox.

**Comment by muchisx** [comment]
@mikirejf of course!

Here it is
https://codesandbox.io/s/framer-motion-button-bug-ye8hjz?file=/src/Button/Button.styles.tsx

Here's what i see in the codesandbox too:

https://user-images.githubusercontent.com/34131801/236556997-4a104da7-f3ec-452b-b68d-777725a7bf90.mp4

**Comment by mikirejf** [comment]
@muchisx 

If we hover the button and then unhover it before the layout animation completes, the animation will get interrupted and reversed. When we flicker the mouse quickly over the button, the animation interrupt-reverse events are apparently fired too often which then somehow breaks the animation.

One solution would be to add a short debounce timer to make sure the hover state doesn't change too quickly.

https://codesandbox.io/s/beautiful-worker-mqq9hq?file=%2Fsrc%2Findex.tsx

**Comment by muchisx** [comment]
@mikirejf 
That sounds like a step in the right direction! Thank you for your time in helping!

I like that the animation doesnt visually break animore with fast hovering, and I understood well what the issue was with your explanation, thank you !

Now, one thing I would like to fix is that when we hover fast, it doesnt visually break but it finishes in the other direction which is not the intention. Ideally, it will comeback at the original position, which is, text on the left and icon on the right.

Ideally, what I was thinking is that if we hover fast, the animation would somehow cancel midway and comeback to the original state, I will do some research on that but I think the direction you pointed me is good! 

If you think on something for this new issue let me know, thank you !


Demo:

https://user-images.githubusercontent.com/34131801/236574339-26523581-b709-4461-afcb-13774db74f51.mp4

**Comment by mikirejf** [comment]
@muchisx 

Ah sry, didn't even notice (very late hours). You could do something like this then: https://codesandbox.io/s/beautiful-leftpad-rbvvn5?file=%2Fsrc%2Findex.tsx

**Comment by muchisx** [comment]
@mikirejf 
Wow thank you this works great! I was trying to come up with something like this but you beat me to it ! Thank you, you rock !
