### ISSUE TITLE
10.12.8 is a breaking change for older browsers

### ISSUE THREAD

**Issue by cevr** [framer/motion#2110]
Not sure where to put this, up until this patch, framer-motion has worked for at least chrome 56 (stuck in this version to support Samsung's Tizen OS systems). 

Not any longer with queueMicrotask upgrade. Wasn't sure if this was a priority, but figured I would let you know

**Comment by mattdeco** [comment]
Additionally, I'm seeing regressions across multiple apps when upgrading to 10.12.8. It seems the change is breaking a variety of animations that use the `layout` prop and / or the `<AnimatePresence>` component. Downgrading and pinning to 10.12.7 resolves the issues.

It seems that animations instantly transition under certain conditions on 10.12.8.

**Comment by sandren** [comment]
All of the new issues being opened related to layout animations are caused by this change as well.

**Comment by mattgperry** [comment]
Thanks for the heads-up, these aren't supported browsers for us (<2%) but as I go through these tickets I'll take a look at things that might have been affected by `queueMicrotasks`. The nice thing about this is it batches animations but in a synchronous way, therefore if we get a double render via `useLayoutEffect` (which is quite common) we can cut a substantial amount of layout animations. So I would prefer to keep it, but will pay attention to it.
