### ISSUE TITLE
[BUG] NextJS + FramerMotion leads to jumps instead of animations; all client-side, no clear reason why.

### ISSUE THREAD

**Issue by StarrKiss** [framer/motion#2112]
I've created two code-sandboxes to demonstrate this: 
Here, in plain/vanilla React, https://codesandbox.io/s/exciting-tesla-cod12x?file=/src/App.js when you hit the test button, the transition is smooth and works as intended. However, in NextJS, https://codesandbox.io/p/sandbox/intelligent-sanne-76xt6d?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A59%2C%22endLineNumber%22%3A19%2C%22startColumn%22%3A59%2C%22startLineNumber%22%3A19%7D%5D when you hit the 'test' button, there is no animation; it simply jumps from end to beginning. This problem occured on my actual app website, which is very frustrating. I've absolutely no idea how to fix it or what the problem is - what I do know is that removing the 'layout' from the NextJS CodeSandbox causes it to work properly. Absolutely no idea why, but ah well.

**Comment by mikirejf** [comment]
The projects use different versions of `framer-motion` (`10.9.1` vs `10.12.8`).

[The solution](https://codesandbox.io/p/sandbox/intelligent-sanne-76xt6d?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A48%2C%22endLineNumber%22%3A7%2C%22startColumn%22%3A48%2C%22startLineNumber%22%3A7%7D%5D)

**Comment by StarrKiss** [comment]
thank you so much this helped me solve it :)
