### ISSUE TITLE
[BUG] Animations in Framer Motion and Next.js Stop Working on Page Reloads

### ISSUE THREAD

**Issue by hariscs** [framer/motion#2114]
**2. Describe the bug**

It seems that my Framer Motion and Next.js TypeScript setup was functioning well until recently when the animation stopped loading altogether. I tried deleting the ".next" folder and restarting the server, which initially resolved the issue, but the animation stopped working again upon page reload. Over time, the animation has ceased to load even after performing the folder deletion and server restart. I also attempted to update Next.js and Framer Motion to their latest versions, but the animation still failed to load.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

**4. Steps to reproduce**

1. run the project with `yarn dev`
2. open it with a browser

**5. Expected behavior**

The expected behavior of the animation is to move from right to left as the user scrolls.

**6. Video or screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/60646718/236931862-45ec127e-5c6e-4478-b30a-d5ec4ff5988b.png">
you can see that the animation is fixed to the right-hand side of the page and not moving, despite being a scroll-linked animation that should move from right to left as the user scrolls.

If applicable, add a video or screenshots to help explain the bug.

**7. Environment details**

If applicable, let us know which OS, browser, browser version etc you're using.
- Nextjs: v 13.4.1
- framer-motion: v 10.12.8
- browser: Chrome and Firefox

**8. Note**
The problem with Framer Motion is not limited to a single animation, as it is not working on other pages that use it as well.

**Comment by diakonovm** [comment]
Yeah, this happens after framer-motion v10.12.4. I just dropped back down to v10.12.4 until this is fixed.

**Comment by Got-crypto** [comment]
I'm facing this issue, whenever I'm trying to fetch data on the page framer motion stops working. Removing the data fetching framer-motion starts working again.

- framer-motion `10.16.1`
- next `13.4.19`
- Chrome browser

**Comment by Got-crypto** [comment]
> 

UPDATE: The animations are back to working after I done cleared all errors in my console. In my case, the errors were about CORS policy that I had to resolve.
