### ISSUE TITLE
[BUG] useSpring example from docs becomes glitchy with 9.0.3+

### ISSUE THREAD

**Issue by maxbarry** [framer/motion#2123]
The `useSpring` doco has a lovely demo embedded at the bottom of the page where you drag one colorful ball and the rest follow:

https://www.framer.com/motion/use-spring/

The actual demo is here:

https://codesandbox.io/s/framer-motion-usespring-example-0ctgom

I ran into problems trying to reproduce the effect, and noticed the demo uses framer-motion `6.4.2`. Beginning with version `9.0.3`, the same demo becomes glitchy: When you drag any ball except the top-left one, it jerks around the screen, as does the top-left ball:

https://codesandbox.io/s/trusting-feynman-f0co5s?file=/src/index.tsx

My best guess as to what's happening from experimentation is that the affected balls are somehow being doubly animated, by both `useSpring()` and `useMotionValue()`.

It works great up to & including version `9.0.2`, and is glitchy from `9.0.3-alpha.0` onwards, up to and including `10.9.1`.

**Comment by maxbarry** [comment]
[Screencast from 2023-05-16 10-19-45.webm](https://github.com/framer/motion/assets/892447/a0288f5f-7487-4fa2-af2c-6eea1715f8b4)

**Comment by mattgperry** [comment]
Dupe https://github.com/framer/motion/issues/2088

**Comment by maxbarry** [comment]
This issue was marked dupe of #2088, which was closed as fixed in January. 

However, the bug remains, both in my own project and in the official demo.

Here it is in 11.0.24:
[Screencast from 2024-04-05 13-23-50.webm](https://github.com/framer/motion/assets/892447/40342514-5052-4ea0-8eba-0ad294c710f0)

**Comment by maxbarry** [comment]
Happy to report this bug was fixed by [828b8d9](https://github.com/framer/motion/commit/828b8d9e52ee3db1693d5dad79a320f355e6e51f), so the glitchiness is gone starting with version [11.3.30](https://github.com/framer/motion/blob/main/CHANGELOG.md#11330-2024-08-23).
