### ISSUE TITLE
[BUG] CSS Does not animate with LayoutID

### ISSUE THREAD

**Issue by Lucien950** [framer/motion#2124]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

When styles are added to an object transitioning between LayoutIDs, the transition does not play.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
[Code Sandbox Replication](https://codesandbox.io/s/layout-animation-css-transitions-wmo4ro?file=/src/App.tsx)

**4. Steps to reproduce**
N/A, just look at the code sandbox.

**5. Expected behavior**
It should smoothly transition between colours.

**6. Video or screenshots**

**7. Environment details**
Win11/Chrome 113.0.5672.93

**Comment by mattgperry** [comment]
This is expected behaviour as each `underline` is new and `transition` only works when changing CSS values - here no CSS values are changed.

**Comment by mattgperry** [comment]
I believe there's a feature request for this somewhere although I can't dig it out right now

**Comment by Lucien950** [comment]
> I believe there's a feature request for this somewhere although I can't dig it out right now

I would be interested in following the progress on that.
