### ISSUE TITLE
[BUG] Changing the state does not trigger the `translateX` animation 

### ISSUE THREAD

**Issue by JSzczepanska-Chlipala** [framer/motion#2125]
Animation has stopped working. Changing the state does not trigger the animation of the element. The value of the `translateX` state is set after the appearance of another element on the screen - `onViewportEnter`. It changes its value correctly, but it does not trigger the animation. The image does not change.

Working version (framer-motion <= v10.12.6)
https://codesandbox.io/s/framer-motion-track-element-position-forked-3ze18x

Broken version (framer-motion v10.12.10)
https://codesandbox.io/s/framer-motion-track-element-position-forked-ouujjk

**Comment by mikirejf** [comment]
The workaround is to explicitly specify the translate as a transform: https://codesandbox.io/s/https-github-com-framer-motion-issues-2125-bq0lq4

**Comment by mattgperry** [comment]
The canonical way in Framer Motion to animate `translateX` is via `x`, but I can still take a look at what changed here.
