### ISSUE TITLE
Use inertia easings in animate()

### ISSUE THREAD

**Issue by jamesvclements** [framer/motion#2126]
Is it possible to use `type: inertia` in `animate()`?

Like so:
<img width="593" alt="image" src="https://github.com/framer/motion/assets/20052710/5716e5bc-b050-4295-91bf-960e99a72b7a">

That throws an error because I think `animate()` expects the second argument to be the `to` value, but in the case of `inertia` animations, I believe we should only need to pass the velocity and it calculates the target automatically.

**Comment by jamesvclements** [comment]
It does seem to work if you just pass an arbitrary value though, so not too big of a deal:
```tsx
        if (swipeX !== 0) {
          /* arbitrary "to" value, intertia uses velocity anyways but throws error without value */
          animate(distance, distance.get(), {
            type: "inertia",
            velocity: swipeX * velocityX * 500,
          });
        }
```

**Comment by mattgperry** [comment]
I probably won't fix this/provide an overload for it, but will add a comment in the docs.
