### ISSUE TITLE
[BUG] Adding a callback to animate() via .then() prevents using animation controls 

### ISSUE THREAD

**Issue by hatsumatsu** [framer/motion#2146]
Is it intended that adding a callback to `animate()` via `.then()` prevents us from using animation controls like `pause()`?

`animate()` seems to return different things depending on whether `.then()` is used. Controls are returned when no `then()` is present, otherwise a Promise is returned. Since we can't cancel a Promise effectively, how could both features used together?

Example:

````js
const animation = animate(0, 1, {...options}).then( () => { console.log( 'animation finished!' ); } );

function onClick() {
  animation.stop(); // breaks because animate() returns a promise...
}
````

A potential solution would be an `onComplete` option similar to `onUpdate`.

**Comment by mattgperry** [comment]
`animate()` doesn't ever return anything different. It always returns animation controls.

```
const animation = animate()
animation.then(() => {})
animation.stop()
```

**Comment by hatsumatsu** [comment]
@mattgperry My bad, thanks a lot for explaining this!
