### ISSUE TITLE
Site vs. page transition proposal

### ISSUE THREAD

**Issue by jamesvclements** [framer/motion#2151]
Using Next.js 13x, there's potential for a really intuitive API for site and page transitions:

`layout.tsx`
```tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head />
      <body>
        <SiteTransition>
          {/* shared layouts */}
          <Nav />
          {/* individual routes */}
          <PageTransition>{children}</PageTransition>
        </SiteTransition>
      </body>
    </html>
  );
}
```

`site-transition.tsx`
```tsx
export const SiteTransition = ({ children }: { children: React.ReactNode }) => {
  return (
    <motion.div
      // use unique names for these so that they don't conflict with the page's or component's own initial and exit animations
      initial="site-initial"
      animate="site-enter"
    >
      {children}
    </motion.div>
  );
};
```

`page-transition.tsx`
```tsx
export const PageTransition = ({ children }: { children: React.ReactNode }) => {
  const pathname = usePathname();

  return (
    <AnimatePresence
      mode="wait"
    >
      <motion.div
        key={pathname}
        // use unique names for these so that they don't conflict with the page's or component's own initial and exit animations
        initial="page-initial"
        animate="page-enter"
        exit="page-exit"
      >
        {children}
      </motion.div>
    </AnimatePresence>
  );
};
```

Where components anywhere inside the tree can then use these variant labels to hook into site enter / loading animations, and/or page transition animations:

```js
{
  'site-initial': { ... } /* preload */
  'site-enter': { ... } /* loaded  */
  'page-initial': { ... } /* pre-transition */
  'page-enter': { ... } /* on enter */
  'page-exit': { ... } /* on exit */
```

**However, this doesn't quite work** because defining `animate="page-enter"` inside of `page-transition.tsx` overwrites `site-enter`. No components inside of pages can differentiate between site enter vs page enter, though the animation treatment for those two situations is typically quite different (loader vs no animation or something more subtle).

1. Is there a way to handle this with the current API?
2. If not, is it worth considering a way to support this? Where children can pass-through their parent's animate rather than overwriting it?

**Comment by jamesvclements** [comment]
(meant to tag this as a feature)

**Comment by andrii-petlovanyi** [comment]
> (meant to tag this as a feature)

could you please tell me how to animate the output. Since I am using Next 13.4 app based routing and even after following your example, the dismounting of the component is not animated correctly. Instead of the animation of unmounting the current one, I get unmounting and immediately mounting a new one. thank you

**Comment by jamesvclements** [comment]
@andrii-petlovanyi this doesn't work as-is, just pseudocode for the idea. There's a [Next issue](https://github.com/vercel/next.js/issues/49279) for the exit animations

**Comment by mattgperry** [comment]
I like the idea but realistically this year I'll be concentrating on Framer Page Effects rather than adding new site transitions APIs so closing as `wontfix` to set expectations.
