### ISSUE TITLE
[BUG] Absolutely positioned element with adjacent element in position does not display whileHover styles

### ISSUE THREAD

**Issue by michaelaflores** [framer/motion#2164]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

An element who is absolutely positioned and hovered, which has an element within its position that also becomes hovered, does not apply its hover styles while the "child" is hovered.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/pedantic-brook-4f0huj

**4. Steps to reproduce**

1. Go to https://codesandbox.io/s/pedantic-brook-4f0huj
2. Hover your mouse over the element with text "I am an iPadOS style link"
3. Observe that only when hovering at the very boundary can you see the element with ` key="highlight"` showing its background, whereas once you hover over the text itself it disappears 

**5. Expected behavior**

When hovering an absolutely positioned element with an element inside of it, both elements maintain `whileHover` styles

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

**7. Environment details**

Tested on macOS 13.4 with Chrome 113.0.5672.126 and Safari 16.5

**Comment by mattgperry** [comment]
This isn't a bug, it's fundamentally how pointer events work on the web. The overlapping element, not being a child, is triggering a `pointerEnd` event on the element behind it. It's not "inside", it's adjacent.
