### ISSUE TITLE
[BUG] typescript rejects a resolver function as the`exit` prop

### ISSUE THREAD

**Issue by halouvi** [framer/motion#2165]
We've recently upgraded from v2 and are now getting a type error when using a function on a `<motion.div>`'s `exit` prop.
We wanted to utilise the `custom` prop passed the parent `<AnimatePresence>`.
As you can see in [this codesandbox](https://codesandbox.io/s/practical-frost-vgx5m6?file=/src/App.tsx), the code still works as expected, it's just a type error.

It looks like this diff removed the resolver type from the prop's definition:
https://github.com/framer/motion/pull/857/commits/5d9697e4212fe997c296cf1627c59fe7862cbf6b#diff-bd760c2ce07e02b73ae4a338d3f1eb813215733b0e99f1f57163b9452f31a244

**Comment by dreamboyx1** [comment]
@halouvi, I had a similar need and could not find good examples. I initially used something like your code but I ended up using something like this with no TypeScript issues:

```typescript
const variants: Variants = useMemo(
  () => ({
    initial: { opacity: 0, x: slideAmount * (isForward ? 1 : -1) },
    slideIn: { opacity: 1, x: 0 },
    slideOut: (isForward: boolean) => ({
      opacity: 0,
      x: slideAmount * (isForward ? -1 : 1)
    })
  }),
  [isForward]
);
```
And then...
```tsx
<AnimatePresence custom={isForward} mode="wait">
  <motion.div
    key={currStep}
    variants={variants}
    initial="initial"
    animate="slideIn"
    exit="slideOut"
  >
    <h1>currStep: {currStep}</h1>
  </motion.div>
</AnimatePresence>
```
Here is an updated version of your [codesandbox](https://codesandbox.io/s/weathered-butterfly-kg8l7f?file=/src/App.tsx)

**Comment by mattgperry** [comment]
I think it's basically a bit of luck that it works, it isn't a pattern we support or have any tests for which is why the types are saying it's not ok. The example by @dreamboyx1 is how dynamic variants work.
