### ISSUE TITLE
[BUG] onAnimationComplete not return expected results

### ISSUE THREAD

**Issue by frommainland** [framer/motion#2166]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

when rending elements from an array finish animation, use func "onAnimationComplete={() => removeElement(index)}" should unmount itself from the array, but it only remove the half the elements in the array.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/onanimatecomplete-9qoo9w?file=/src/App.js

**4. Steps to reproduce**

check out the console

**5. Expected behavior**

It should remove all elements in the array after finish its own animation

**Comment by frommainland** [comment]
The onAnimationComplete is working, change its key value should fix the problem

**Comment by mattgperry** [comment]
It should be the elements are removed by key not index (as this is mapping to different letters as items are moved)
