### ISSUE TITLE
[BUG] Usage of translateX and translateY in animate breaks with TypeError: positionalValues[key] is not a function

### ISSUE THREAD

**Issue by valkum** [framer/motion#2169]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

```
<motion.div
      animate={{ translateY: "0", opacity: 1 }}
      className="fixed bottom-0 z-50 w-full"
      exit={{ translateY: "100%", opacity: 1 }}
      initial={{ translateY: "100%", opacity: 1 }}
      transition={{ ease: [0.22, 0.77, 0.08, 0.99], duration: 0.75 }}
    >
``` 
results in 
```
TypeError: positionalValues[key] is not a function
```

The problem lies in [positionalValues](https://github.com/framer/motion/blob/main/packages/framer-motion/src/render/dom/utils/unit-conversion.ts#L86) which should also allow `translateX` and `translateY`.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/gracious-easley-cb0fpp?file=/src/App.js:138-417

**4. Steps to reproduce**

1. Render the CodeSandbox example

**5. Expected behavior**
It should be the same as with using `y` instead of `translateY`

```
<motion.div
      animate={{ y: "0", opacity: 1 }}
      className="fixed bottom-0 z-50 w-full"
      exit={{ y: "100%", opacity: 1 }}
      initial={{ y: "100%", opacity: 1 }}
      transition={{ ease: [0.22, 0.77, 0.08, 0.99], duration: 0.75 }}
    >
```

The docs say `x`, `y`, and `z` are shortcuts for `translateX`, `translateY`, and `translateZ`

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

**7. Environment details**

**Comment by BitYoungjae** [comment]
Same.. in Next.js 13.4.x

**Comment by josias-r** [comment]
Also experiencing this in next.

From the linked file by @valkum, I was able to update my variants from:
```
const variantsOLD: Variants = {
  visible: {
    translateY: 0,

    transition: {
      type: "spring",
      stiffness: 150,
    },
  },
  hidden: {
    translateY: "calc(100% + 25px)",
    transition: {
      ease: "easeInOut",
    },
  },
};
```
To:
```
const variantsNEW: Variants = {
  visible: {
    y: 0,

    transition: {
      type: "spring",
      stiffness: 150,
    },
  },
  hidden: {
    y: "calc(100% + 25px)",
    transition: {
      ease: "easeInOut",
    },
  },
};
```

... note the `translateY`. Seems like the translateXY keywords got lost in the object.
