### ISSUE TITLE
[BUG] - Scroll Linked animation with offset  , and pathLength animation - Not working with Tablet - iPad mini  

### ISSUE THREAD

**Issue by berenicestr** [framer/motion#2185]
I am implementing an animation with a text reveal with framer motion scroll-linked animation. I need to implement the animation inside a component with an offset.

The animation runs well/ok in different browsers. Doesn´t work with the tablet -the iPad mini - (not working with Safari and Chrome).

Codesandbox: https://codesandbox.io/s/framer-motion-scroll-linked-animation-forked-ckd5ty

Also, the pathLength animation doesn´t animate the path with the iPad mini.
This is a codesandbox created by your team: 
https://codesandbox.io/s/framer-motion-5-1-line-drawing-ph6ln?from-embed

Any help? Thanks in advance.
Best,

**Comment by pbshgthm** [comment]
I'm facing the same issue. Were you able to resolve it? `pathLength` is not working properly on any WebKit based browsers.

**Comment by mattgperry** [comment]
I think the original sandbox has had the path animation removed. But I've tested the second link in desktop and web Safari and seems to work.
