### ISSUE TITLE
How can I use transitionEnd with useAnimate() hook? 

### ISSUE THREAD

**Issue by paperpluto** [framer/motion#2188]
Can someone help me on how can I use 'transitionEnd' 
https://www.framer.com/motion/transition/###targetandtransition with useAnimate() hook. https://www.framer.com/motion/use-animate/

**Comment by jon-a-nygaard** [comment]
Hi @paperpluto, you can still pass `transitionEnd` as a part of an animation object provided to the `animate` function. 

There's also a few other alternatives like the `onComplete` callback, or using `await` with the `animate` function, that allows you to perform additional functionality after the animation has completed.

See the following [example in CodeSandbox](https://codesandbox.io/s/framer-motion-transitionend-forked-km93ph) for a demonstration of using `transitionEnd` and the alternative approaches.

Hope this can be of help to you.
