### ISSUE TITLE
How to animate children on parent hover

### ISSUE THREAD

**Issue by maotora** [framer/motion#219]
Hi everyone!

I want to animate children (rotate the icon to 90 degrees) when hovering at a parent element which is a button.

```jsx
<motion.button type="button" whileHover={{scale: 1.1}}>
    Visit our Industry 
    {/*Animate this Icon to rotate 90 degrees*/}
    <Icon type="arrow-up" /> 
</motion.button>

```

I also posted this question on [stackoverflow](https://stackoverflow.com/q/57125263/2405689) and surprisingly there wasn't a `framer-motion` tag yet.
Couldn't create it too, my rep < 1500. 🙄

**Comment by InventingWithMonster** [comment]
Variants!

```
const iconVariants = {{
  default: { rotate: 0 },
  hover: { rotate: 90 },
}}

return (<motion.button type="button" initial="default" whileHover="hover">
    Visit our Industry 
    {/*Animate this Icon to rotate 90 degrees*/}
    <motion.img variants={iconVariants} /> 
</motion.button>)
```

**Comment by maotora** [comment]
Sweet, Thanks! ✨✨

**Comment by maotora** [comment]
@InventingWithMonster hey, if you have enough reputation you can create the `framer-motion` tag on stackoverflow!
