### ISSUE TITLE
[BUG] CSS keyframe animations not working

### ISSUE THREAD

**Issue by shuklaayush** [framer/motion#2190]
**1. Describe the bug**

Keyframe animations with CSS `transform` values like `translate3d` and `rotatez` have stopped working after release [10.2.4](https://github.com/framer/motion/compare/v10.2.3...v10.2.4).

**2. Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/quizzical-noyce-523rjj

**3. Steps to reproduce**

1. Go to https://codesandbox.io/s/quizzical-noyce-523rjj?file=/package.json
2. Update `framer-motion` dependency to `^10.2.4`
3. See error `Both input and output ranges must be the same length`

Code to reproduce
```jsx
import { motion } from "framer-motion";

export default function App() {
  return (
    <motion.svg
      width="256"
      height="256"
      viewBox="0 0 64 64"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      stroke="currentColor"
      strokeWidth="2"
    >
      <motion.path
        d="M8,40 V16"
        initial={{
          transform: "translate3d(0px,0,0) rotatez(0deg)"
        }}
        animate={{
          transform: [
            "translate3d(0px,0,0) rotatez(0deg)",
            "translate3d(0px,0,0) rotatez(0deg)",
            "translate3d(25px,0,0) rotatez(-60deg)"
          ]
        }}
        transition={{
          duration: 1,
          type: "spring",
          stiffness: 100
        }}
      />
    </motion.svg>
  );
}
```

**4. Expected behavior**

The animation should work.

**Comment by taisei-13046** [comment]
I'm having it too.
Please solve, someone.

**Comment by mattgperry** [comment]
Spring/inertia has never worked with multiple keyframes (you can see in the working animation the animation settings aren't actually taking effect). Adding this support is unlikely but I can make a better error message.

**Comment by tcisse** [comment]
![CleanShot 2024-03-16 at 06 00 39@2x](https://github.com/framer/motion/assets/97899569/d5cf6948-4d5c-48bb-bfe4-2b35c3ada84f)


Hello I have same problem  framer version `"framer-motion": "^11.0.14",`

**Comment by tcisse** [comment]
in `framer-motion:^10.2.4` all is okay

**Comment by howdyfrom2019** [comment]
same here

**Comment by rhijjawi** [comment]
> in `framer-motion:^10.2.4` all is okay
Unfortunately, same issue.

**Comment by baijunjie** [comment]
same issue

**Comment by pablojsx** [comment]
![Captura de pantalla 2024-04-03 045802](https://github.com/framer/motion/assets/40902487/40a7183f-26e9-4f51-b118-b7c7385be9ba)

**Comment by kai-abat** [comment]
> ![Captura de pantalla 2024-04-03 045802](https://private-user-images.githubusercontent.com/40902487/319093915-40a7183f-26e9-4f51-b118-b7c7385be9ba.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTA4MjUsIm5iZiI6MTcxMjI1MDUyNSwicGF0aCI6Ii80MDkwMjQ4Ny8zMTkwOTM5MTUtNDBhNzE4M2YtMjZlOS00ZjUxLWIxMTgtYjdjNzM4NWJlOWJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE3MDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwYTc4Y2FhZjRiMjVhOTdjMDlhNTI1ZjljOGIzMGI3YTkyY2M4ODJmZDE4Zjc4NDU5MDU1OTE5NTUzMmJmMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LNPO57Kzu6FKmTM_aU-aM22zkSnqpGNQY0m_PVfoBYs)

Same issue, I encounter this as well if I repeatedly click the SELECT nextui component.

**Comment by Felipe-Emanuel** [comment]
> > ![Captura de pantalla 2024-04-03 045802](https://private-user-images.githubusercontent.com/40902487/319093915-40a7183f-26e9-4f51-b118-b7c7385be9ba.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTA4MjUsIm5iZiI6MTcxMjI1MDUyNSwicGF0aCI6Ii80MDkwMjQ4Ny8zMTkwOTM5MTUtNDBhNzE4M2YtMjZlOS00ZjUxLWIxMTgtYjdjNzM4NWJlOWJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE3MDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwYTc4Y2FhZjRiMjVhOTdjMDlhNTI1ZjljOGIzMGI3YTkyY2M4ODJmZDE4Zjc4NDU5MDU1OTE5NTUzMmJmMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LNPO57Kzu6FKmTM_aU-aM22zkSnqpGNQY0m_PVfoBYs)
> 
> Same issue, I encounter this as well if I repeatedly click the SELECT nextui component.

Me too, but, as [tcisse](https://github.com/tcisse) said, I just downgrade to 10.2.4 and it works perfectly

**Comment by Deeplobo** [comment]
```
transition={{
                  repeat: Infinity,
                  duration: 5,
                  type: "tween",
                }}
```
**This fixes my problem**

**Comment by chinchang** [comment]
> Spring/inertia has never worked with multiple keyframes (you can see in the working animation the animation settings aren't actually taking effect). Adding this support is unlikely but I can make a better error message.

I can confirm it used to work in some older version. I revisited my app today and found it doesn't work with the latest version.
