### ISSUE TITLE
[BUG] SSR for SVG components omits transforms

### ISSUE THREAD

**Issue by tkonopka** [framer/motion#2193]
**1. Read the [FAQs](#faqs) 👇**

The issue does not appear in faqs. It partially overlaps with a comment in the online docs (see below)

**2. Describe the bug**

When creating SVG graphics from a Next.js app, some attributes are omitted in the server-side rendering and hydrated later in the client. This makes SVG components jump/flicker when a page first loads. Affected attributes include `x`, `y`, `rotate` (attributes that contribute to 'transforms').

A related point is mentioned in the docs [here](https://www.framer.com/motion/component/##server-side-rendering). However, the flicker affects more attributes than is documented. Also, the docs suggest that specifying `originX` and `originY` should enable ssr rendering, but this does not appear to be the case. (?)

**3. Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/p/sandbox/nice-lumiere-kvckcm

**4. Steps to reproduce**

1. Open the codesandbox. Make sure the preview shows text and an svg graphic.
2. Press the "Refresh" button on the preview
3. The preview box will reload. A rectangle and a circle will momentarily appear in the top-left corner of the graphic - this corresponds to svg code generated by the server. A few moments later, the rectangle and circle will reposition to their final positions - this corresponds to svg code completed in the client.

**5. Expected behavior**

Shapes in svg graphics should not jump upon load. Server-generated svg code should include the correct coordinates/transforms.

**6. Video or screenshots**

Screengrab from the codesandbox:

https://github.com/framer/motion/assets/7260190/6873deec-f856-41fc-8ade-f328bc5cd3bc

**7. Environment details**

OS: linux
browser: chrome 114
framer-motion: 10.12.16 (but issue initially noticed in other versions)

**Questions**

I tinkered with the source code and I may have a fix (the fix seems to work in tests I did so far). I can submit a PR, including tests following your 'ssr.test.tsx' scheme. Would this be of interest? Would you be able to review a PR?

**Comment by v3locity47** [comment]
Did you find a solution? I have been struggling with this for past 2-3 days still no luck :(

**Comment by tkonopka** [comment]
Hi @v3locity47. As a workaround, you can include transforms manually in your own code. For example, instead of

```js
<motion.rect animate={{ x: 5, y: 5 }} />
```

use

```js
<motion.rect animate={{ x: 5, y: 5 }} style={{ transform: 'translateX(5px) translateY(5px)' }} />
```

The manual transform will be used for the intial render. Subsequent renders will replace it with information from `animate`. If the style and animate data match, the jump/repositioning should become invisible.

A more satisfying solution would be to have the correct transforms in ssr. Actually, framer-motion already computes the transform string on the server, but then it does not send the transforms to the client. I would like to submit a PR for this, unless this would introduce breaks elsewhere. What do you think, @mattgperry?
