### ISSUE TITLE
[FEATURE] Export MakeCustomValueType and TargetProperties or support TargetAndTransition type for initial animation attribute.

### ISSUE THREAD

**Issue by calvinagar** [framer/motion#2197]
**Is your feature request related to a problem? Please describe.**
I'm trying to create a wrapper for animations, and I created an interface which holds the values for a `motion` elements' `initial`, `animate`, `exit`, and `transition` attributes. I can safely get the typing for all of the attributes besides `initial`, since `MakeCustomValueType` and `TargetProperties` is not exported in `index.d.ts`.

As such, I cannot use values such as `{ opacity: 0.5 }` for the `initial` value in my interface.

**Describe the solution you'd like**
Export `MakeCustomValueType` and `TargetProperties` in `index.d.ts` so they are usable.
Alternatively you could support TargetAndTransition type for `initial` attribute on `motion` elements.
Create a new type that is added to types used by the `initial` attribute that supports those sorts of objects.

**Describe alternatives you've considered**
Currently unsure how to approach a solution besides removing `initial` from my interface and writing it directly in the DOM, defeating the purpose of the interface.

**Comment by mattgperry** [comment]
Those types are in flux so I would stick to trying `ResolvedValues` if this is exported or `{ [key: string]: number | string }` if not
