### ISSUE TITLE
[BUG] Animation takes longer than set in `transition.duration` on some devices

### ISSUE THREAD

**Issue by OlegWock** [framer/motion#2202]
**1. Describe the bug**

I tested my app on two macbooks, and on older one animation takes more time than set in `transition.duration`.

I have an AnimatePresence where I conditionally render current screen. 

```jsx
const mainScreenEnter = { x: '-30%', opacity: 0 };
const mainScreenExit = { x: '-30%', opacity: 0 };
const innerScreenEnter = { x: '30%', opacity: 0 };
const innerScreenExit = { x: '30%', opacity: 0 };
const transition = { duration: 0.18 };

<AnimatePresence initial={false} mode='wait'>
    {screen === 'main' && <MainScreen key='main' initial={mainScreenEnter} animate={{ x: 0, opacity: 1 }} exit={mainScreenExit} transition={transition} />}
    {screen === 'general' && <GeneralSettingsScreen key='general' initial={innerScreenEnter} animate={{ x: 0, opacity: 1 }} exit={innerScreenExit} transition={transition} />}
</AnimatePresence>
```

So basically one screen slides out and then new screen slides in. Transition is same for both of them. Screens pass animation props to underlying `m.div`.

On newer macbook (MacBook Pro 2021, M1 Max, 64 GB RAM) it works perfect and takes around 360 ms (two animations, 180ms each). However, on older one (MacBook Pro 2019, 6 core i7, 16GB RAM) it's noticeably slower (around 480ms). 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

I tried to make a minimal reproduction, but it didn't worked (animation had correct duration on older macbook). I assume this is because there is a lot more happening in actual app (and not happening in CodeSandbox). I know this isn't easy to find issue without reproduction, but I thought maybe you could give me some direction on what to check and what might be the problem.

**4. Expected behavior**

Animations taking same time on both machines.

**5. Video or screenshots**

This is how it works on newer mac (starts at ~0:03.200 and ends at ~0:03.560)

https://github.com/framer/motion/assets/7430438/877f0d88-ba64-4f9a-b4b2-6671c0368002

And this is from older mac (start at ~0:02.250 and ends at ~0:02.730)

https://github.com/framer/motion/assets/7430438/567ca607-735d-4623-9474-f28dbb8fb061

**6. Environment details**

Newer mac: Mac OS 13.4, Browser Brave v1.52.117 (Chromium: 114.0.5735.90)
Older mac: Mac OS 12.4, Browser Brave v1.50.121 (Chromium: 112.0.5615.138)

**Comment by mattgperry** [comment]
This is odd as animations resolve for time so unless its really chugging and filling up the main thread (its not much work by the looks of it) it shouldn't be any differnet. However I can't look into it without a reproduction so I'm gonna close for now but reopen if you can come up with something for me to profile even.
