### ISSUE TITLE
[BUG] Error when scroll exists in child element of drag component

### ISSUE THREAD

**Issue by gaonprime-shpark** [framer/motion#2207]
**1. Read the [FAQs](#faqs) 👇**

making the bottom sheet. 
When the child element of the sheet is at the top of the scroll, 
dragging the child element does not move the bottom sheet.
Non-scrolling header elements are draggable, but content elements are not.

What I want is, for example, when the scrollTop value of a child element is 0,
the bottom sheet moves when the user drags it.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/embed/billowing-fast-rmdppc?autoresize=1&fontsize=14&hidenavigation=1&theme=dark

4. Steps to reproduce

1. new window open CodeSandBox
2. mobile device view
3. bottomSheet header dragging check
4. bottomSheet content scrollTop = 0 dragging check -> not work bottomSheet

**Comment by eyyazubi** [comment]
Same error. Have you fixed it? or a solution?
