### ISSUE TITLE
[BUG] animate issues

### ISSUE THREAD

**Issue by tonyhallett** [framer/motion#2208]
There are multiple issues with animate.

Animating a sequence does not work with zIndex.
createAnimationsFromSequence creates all animations with the sequence duration, incorporating start times into the keyframes and not using delay.  ( It also "merges" segment animations on the same value into a single animation. )

https://github.com/framer/motion/blob/cd676af8844d1bcfecd47ad53c884567dcf61a54/packages/framer-motion/src/animation/sequence/create.ts#L297

When zIndex is animated and instant animation is created 
https://github.com/framer/motion/blob/cd676af8844d1bcfecd47ad53c884567dcf61a54/packages/framer-motion/src/animation/interfaces/motion-value.ts#L110
But given that there is no delay the zIndex animation will occur at the very beginning of the sequence animation and not where it was specified. ( and of course merging of zIndex animations makes no sense )
https://github.com/framer/motion/blob/cd676af8844d1bcfecd47ad53c884567dcf61a54/packages/framer-motion/src/animation/animators/instant.ts#L45

(The duration of the zIndex also affects the next segment and the total duration - even though it is starting immediately)

It is possible to hack around this bug by animating z-index instead of zIndex
from https://github.com/framer/motion/issues/1254

https://codesandbox.io/s/admiring-waterfall-pjynzl

There are two elements on top of one another.  Top is above bottom and is animated.  It should after a delay move to the right and then change its zIndex.

The demo is done twice - the one at the top uses zIndex and the one below using z-index.

Click animate to see the issue with zIndex and how hacking with z-index avoids the instant animation.

expected behaviour
As part of my animation a segment should be able to change the zIndex

---------------------------
Issue 2 - onRepeat is not used by motion 
`
export interface AnimationPlaybackLifecycles<V> {
    onUpdate?: (latest: V) => void
    onPlay?: () => void
    onComplete?: () => void
    onRepeat?: () => void
    onStop?: () => void
}
`
Here you can see that all the others are present ( and used )
https://github.com/framer/motion/blob/cd676af8844d1bcfecd47ad53c884567dcf61a54/packages/framer-motion/src/animation/animators/js/index.ts#L54

Issue 3 - The typescript for the animation segment overload
```
    /**
     * Animate sequences
     */
    function scopedAnimate(
        sequence: AnimationSequence,
        options?: SequenceOptions
    ): AnimationPlaybackControls

export type DOMSegmentWithTransition = [
    ElementOrSelector,
    DOMKeyframesDefinition,
    DynamicAnimationOptions & At
]

export type Segment =
    | MotionValueSegment
    | MotionValueSegmentWithTransition
    | DOMSegment
    | DOMSegmentWithTransition
    | SequenceLabel
    | SequenceLabelWithTime

export type AnimationSequence = Segment[]
```
The DOMSegmentWithTransition tuple, third item DynamicAnimationOptions is too wide.

```
export type AnimationOptionsWithValueOverrides<V = any> = StyleTransitions &
    SVGPathTransitions &
    SVGTransitions &
    VariableTransitions &
    ValueAnimationTransition<V>

export interface DynamicAnimationOptions
    extends Omit<AnimationOptionsWithValueOverrides, "delay"> {
    delay?: number | DynamicOption<number>
}
export type AnimationOptionsWithValueOverrides<V = any> = StyleTransitions &
    SVGPathTransitions &
    SVGTransitions &
    VariableTransitions &
    ValueAnimationTransition<V>

export interface ValueAnimationTransition<V = any>
    extends Transition,
        AnimationPlaybackLifecycles<V> {}

export interface AnimationPlaybackLifecycles<V> {
    onUpdate?: (latest: V) => void
    onPlay?: () => void
    onComplete?: () => void
    onRepeat?: () => void
    onStop?: () => void
}
```
It suggests that it is possible to supply onComplete etc which is not the case
https://github.com/framer/motion/blob/cd676af8844d1bcfecd47ad53c884567dcf61a54/packages/framer-motion/src/animation/sequence/create.ts#L297

Also the Transition from ValueAnimationTransition or StyleTransitions ( etc ) is too wide.
`
export type StyleTransitions = {
    [K in keyof CSSStyleDeclarationWithTransform]?: Transition
}
`
for instance Transition extends AnimationPlaybackOptions yet createAnimationsFromSequence does not look at these.

I would also argue that the "Transition" on StyleTransitions etc should also have the delay type changed from number to DynamicOption<number>.  This "value transition" replicating transition is also important to Issue 4.

Given that the delay will be taken from the value transition when provided surely it should be possible to provide it is a function there too.

https://github.com/framer/motion/blob/cd676af8844d1bcfecd47ad53c884567dcf61a54/packages/framer-motion/src/animation/sequence/create.ts#L226

```
export function getValueTransition(
    transition: DynamicAnimationOptions & At,
    key: string
): DynamicAnimationOptions {
    return transition[key]
        ? { ...transition, ...transition[key] }
        : { ...transition }
}
```

Issue 4 - Animate DOM overload - DynamicAnimationOptions does not permit AnimationPlaybackLifecycles on value transitions.  Does not support TransitionEnd.  Does not allow delay function on value transitions.
```
    /**
     * Animate DOM
     */
    function scopedAnimate(
        value: ElementOrSelector,
        keyframes: DOMKeyframesDefinition,
        options?: DynamicAnimationOptions
    ): AnimationPlaybackControls
```
This goes through animateElements
```
        } else if (isDOMKeyframes(keyframes)) {
            animation = animateElements(
                valueOrElementOrSequence as ElementOrSelector,
                keyframes,
                options as DynamicAnimationOptions | undefined,
                scope
            )
        }
```

I would expect to be able to supply different delays for x and y. 
```
        if (typeof transition.delay === "function") {
            transition.delay = transition.delay(i, numElements)
        }
```

Why is there no parameter for transitionEnd ? - [How can I use transitionEnd with useAnimate() hook?](https://github.com/framer/motion/issues/2188)
```
        animations.push(
            ...animateTarget(
                visualElement,
                { ...keyframes, transition } as TargetAndTransition,                               // add TransitionEnd
                {}
            )
        )
```

animateTarget for each value => animateMotionValue

Note the getValueTransition and valueTransition.onComplete / onUpdate

With DynamicAnimationOptions the value transition is limited to Transition and does not include any AnimationPlaybackLifecycles.
Surely I should be able to receive separate onComplete for x,y etc with its own value transition duration/delay ?
```
export const animateMotionValue = (
    valueName: string,
    value: MotionValue,
    target: ResolvedValueTarget,
    transition: Transition & { elapsed?: number } = {}
): StartAnimation => {
    return (onComplete: VoidFunction): AnimationPlaybackControls => {
        const valueTransition = getValueTransition(transition, valueName) || {}
.....
        let options: ValueAnimationOptions = {
            keyframes,
            velocity: value.getVelocity(),
            ease: "easeOut",
            ...valueTransition,
            delay: -elapsed,
            onUpdate: (v) => {
                value.set(v)
                valueTransition.onUpdate && valueTransition.onUpdate(v)
            },
            onComplete: () => {
                onComplete()
                valueTransition.onComplete && valueTransition.onComplete()
            },
        }
```

Issue 5
Why does animateMotionValue do an accelerated animation when I have supplied onUpdate ?  It considers onUpdate of owner.
Shouldn't it also `!valueTransition.onUpdate` ?
```
        /**
         * Animate via WAAPI if possible.
         */
        if (
            value.owner &&
            value.owner.current instanceof HTMLElement &&
            !value.owner.getProps().onUpdate
        ) {
            const acceleratedAnimation = createAcceleratedAnimation(
                value,
                valueName,
                options
            )

            if (acceleratedAnimation) return acceleratedAnimation
        }
```

**Comment by mattgperry** [comment]
Can you make one ticket per bug please and provide a sandbox for each.
