### ISSUE TITLE
[BUG] ``useInView`` Update hook called on initial render

### ISSUE THREAD

**Issue by ariesclark** [framer/motion#2209]
Error: Update hook called on initial render. ~~This is likely a bug in React. Please file an issue.~~

```ts
const reference = useRef<HTMLDivElement>(null);
const inView = useInView(reference);
```

**Comment by mattgperry** [comment]
This is expected behaviour. On initial render there's no way of knowing whether the component is in view.

**Comment by ariesclark** [comment]
> This is expected behaviour. On initial render there's no way of knowing whether the component is in view.

Throwing an error on render is **not expected behaviour**. It should either default to false, or be able to receive a fallback value on initial render, It is absurd to throw an error like this as _intended behaviour_, seriously..

**Comment by ariesclark** [comment]
For anyone facing this issue, I suggest using [react-intersection-observer](https://github.com/thebuilder/react-intersection-observer) instead, as it reasonably provides a ``initialInView`` property instead of throwing an error.
