### ISSUE TITLE
[BUG] Animation not triggering when the section is too long

### ISSUE THREAD

**Issue by chanpete** [framer/motion#2211]
**Describe the bug**

Setting viewport={{ once: true, amount: 0.25 }} for the section, the inner animation is not triggering the the section become too long.

**CodeSandbox**

[CodeSandbox](https://codesandbox.io/p/sandbox/mystifying-zhukovsky-vt66k5?file=%2Fsrc%2FApp.jsx%3A16%2C12)

**Steps to reproduce**

1. Open the CodeSandbox url above
2. Scroll down
3. Animation is not trigger if more than 8 cards

The problem seems also depends on the windows height, if open the page in new tab, animation will stop trigger for more than 12 cards. (My screen is 1920 x 1080, the windows inner height is 937 when openning the page in new tab.)

**Comment by mattgperry** [comment]
I can't get the sandbox to load but this sounds correct. If the section is too much longer than the viewport then the `amount` is never going to be more than `.25` and so it will never trigger.

**Comment by NotYoojun** [comment]
Hi there, I think we should consider the browser windows size of the user as well. Maybe if the element is, for example, taking 25% percent of the screen, it should trigger the animation as well. Both section size and window size is not predictable. So it's quite necessary to consider this!
