### ISSUE TITLE
[FEATURE] Update the date on the framer-motion documentation

### ISSUE THREAD

**Issue by code-env** [framer/motion#2222]
👋So I was on the framer-motion doc then realized that the date was not up to date🙃
![Screenshot from 2023-07-10 18-40-49](https://github.com/framer/motion/assets/135658967/980780ec-7949-4ef9-ae16-841c07d4290f)

**Comment by mattgperry** [comment]
Thanks for the heads up although I think this will be fixed permanently when we port the docs into Framer
