### ISSUE TITLE
[FEATURE] Search in the docs

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [framer/motion#2226]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when searching the docs manually. I’m used to devdocs having a search somewhere to just query the page.

**Describe the solution you'd like**
A search field to search the docs

**Describe alternatives you've considered**
running CMD+F, sure but that is not a deep-scan

I’d be willing to make a PR and add this if you point me to the correct repo folder 🤔 i.e. Algolia is free for open source projects like this one…

**Comment by mattgperry** [comment]
Dupe, will arrive alongside the migration from our CMS to Framer
