### ISSUE TITLE
Support rem units on `useInView(ref, {margin: "..."})`

### ISSUE THREAD

**Issue by hanoii** [framer/motion#2228]
**Is your feature request related to a problem? Please describe.**

I use tailwind and most unites are rem, I cannot take advantage of that if I want to use its margins and then use the margin option of `useInView()`

**Describe the solution you'd like**
I'd like to use `rem` units as part of the margin option of `useInvView()`.

**Describe alternatives you've considered**
Use fixed `px` instead, but for text It's not always layout proof if the font goes bigger, the offset changes.

**Comment by mattgperry** [comment]
I do like the idea but we're a bit bound here to `IntersectionObserver` and I think computing `rem` values would be prohibitive.
