### ISSUE TITLE
Other carousel libraries doesn't work properly if useInView is being used

### ISSUE THREAD

**Issue by hanoii** [framer/motion#2229]
**2. Describe the bug**

I have a NextJS project where I am using swiper and I was tracking an odd behavior that couldn't reproduce it on a vanilla swiper instance. Finally I tracked this down to the use of useInView (of an element outside of swiper).

I am not 100% sure where the issues lies, maybe on both!

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/p/sandbox/stoic-dust-xdvrhc

Thereyou can see that if you swipe the slides (with mouse/fingers, not arrows) the bullets don't update. If you just comment out line 20 on `page.tsx` (`const isAboutView = useInView(aboutRef);`) swiper starts to work properly.

I mentioned this on https://github.com/nolimits4web/swiper/issues/2915#issuecomment-1635921142 as I think is something worth investigating by both libraries.

**Comment by hanoii** [comment]
I wonder if this is also related to #2031

**Comment by hanoii** [comment]
I just faced a similar issue with https://github.com/naver/egjs-flicking, Pagination doesn't work. Removing the useInView or `ref`s from the Elements make it work.

**Comment by hanoii** [comment]
> I just faced a similar issue with https://github.com/naver/egjs-flicking, Pagination doesn't work. Removing the useInView or `ref`s from the Elements make it work.

Another sandbox showcasing this: https://codesandbox.io/p/sandbox/elated-carson-2krd8v

Now that a very similar thing happens with two completely different libraries I'd think that something this library is doing affects this, can you please advise 🙏 !

**Comment by mattgperry** [comment]
This is really weird. Also if I move the observed element to before the slider it works again.

I'm closing this as `wontfix` as all we do in `inView` is attach an `IntersectionObserver`. Nothing "clever". I've also given Swiper a brief look and can't see how this would cause a conflict, and realistically won't have time to look at this.
