### ISSUE TITLE
Exit Transition not working in Next 13 (App Router)

### ISSUE THREAD

**Issue by Arinji2** [framer/motion#2237]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

The Exit transition is not working, even with Animate Presence

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/p/sandbox/flamboyant-newton-q4hpzd?file=%2Fapp%2Ftest2%2Fpage.tsx%3A1%2C1

**4. Steps to reproduce**

1. Go to the sandbox
2. Click on the blue box to be redirected to the second page
3. Click on the green box to be redirected to the first page

**5. Expected behavior**

The boxes should translate further away before unmounting when redirected

**Comment by Arinji2** [comment]
Its moving out of the page before showing the transition, i would like to keep the page.
So when you click to redirect, the div moves while the page is still in view... instead of it going to some black page

**Comment by mattgperry** [comment]
The `children` don't have any exit animations and `AnimatePresence` is set to `mode="wait"` which allows a single child only.
