### ISSUE TITLE
[FEATURE] Update the AppStore sample to the latest version of frame-motion

### ISSUE THREAD

**Issue by ryanolivrdev** [framer/motion#2240]
## Overview
I'm using frame motion recently in my project, and reading the documentation I noticed the amazing example from the AppStore to study/make but unfortunately it's very outdated. I recommend that you update this to the latest version of frame motion so that we can have practical examples of what is possible to do with this library.

https://codesandbox.io/s/app-store-ui-using-react-and-framer-motion-ecgc2

**Comment by pixelass** [comment]
A believe that most examples are outdated: https://github.com/framer/motion/issues/1769#issuecomment-1807223395

The animate presence example is 5 Major Versions behind.
Let's hope that the core team at some point actually considers responding to the issues (which they generally don't seem to do for whatever reason) or that the amazing open-source community (thanks so much to all the amazing poeople helping to find solutions) 

> I'm really questioning if I should include framer motion with such little core-support :(

**Comment by mattgperry** [comment]
Closing as `wontfix` as realistically I won't have time to update this example.

**Comment by mattgperry** [comment]
Found the time: https://codesandbox.io/p/sandbox/framer-motion-app-store-demo-su6mx?file=%2Fsrc%2FItem.js
