### ISSUE TITLE
sequence of animation fires simultaneously 

### ISSUE THREAD

**Issue by hatsumatsu** [framer/motion#2244]
Animating a sequence of animations while referencing the same MotionValue, all parts of sequence fire simultaneously. 
This is in contrast to the [docs](https://www.framer.com/motion/animate-function/##animate-sequences) stating _"Each definition will, by default, play one after the other."_

Demo: 
https://codesandbox.io/s/framer-motion-animate-sequence-7z93yt?file=/src/App.js

Here the box should first animate to `scale: 2`, then back to `scale: 1`.
This only works as expected when manually adding the `at` parameter in the second animation definition:

````js
    const scale = useMotionValue(1);

    // both animations fire simultaneously
    animate([
      [scale, 2, { duration: 1 }],
      [scale, 1, { duration: 1 }] // needs at: 1
    ]);

    // the animations run one after another 
    animate([
      [scale, 2, { duration: 1 }],
      [scale, 1, { duration: 1, at: 1 }]
    ]);
````

Wondering is this is a bug or an inconsistency in the docs 😇

**Comment by OlegWock** [comment]
It seems that this was changed without updating docs and now animations fire simultaneously by default. As a workaround, you can use `await` or `.then` since `animate` now returns promise:

```js
animate(scale, 2, { duration: 1 }).then(() => animate(scale, 1, { duration: 1 }));
```

**Comment by hatsumatsu** [comment]
@OlegWock thanks for your insights. 
Just wondering if this doesn't defy the purpose of sequences alltogether?

**Comment by OlegWock** [comment]
maybe ¯\_(ツ)_/¯

**Comment by AlgusDark** [comment]
This is a bug 🤔 this only happens when animating motionValues. I'm facing with the same problem. But yeah, adding delay is a workaround.

**Comment by AlgusDark** [comment]
I think I found the problem.

It's on this line, where currentTime is always 0:
https://github.com/framer/motion/blob/fb227f8b700c6e2d9c3b33d0a2af1a2d2b7849e9/packages/framer-motion/src/animation/sequence/create.ts#L151

When this is is from a motionValue, it's not taking in count the `valueSequence` ending time 🤔 

I'm not able to run **framer/motion** locally, but I was debugging it through devtools.

I think that the solution is to do something similar to what is done here:
https://github.com/framer/motion/blob/fb227f8b700c6e2d9c3b33d0a2af1a2d2b7849e9/packages/framer-motion/src/animation/sequence/create.ts#L74

If my theory is correct, we should check `at` property from the previous sequence like:

```js
// Do we need to check also if `currentTime !== 0` ?
if (valueSequence && valueSequence.length) {
  currentTime = valueSequence[valueSequence.length - 1].at;
}

const startTime = currentTime + calculatedDelay
const targetTime = startTime + duration
```

I'll keep trying to run the repo locally, but if someone can test it, that would be nice.
