### ISSUE TITLE
[BUG] offset option in useScroll throws type error

### ISSUE THREAD

**Issue by jorgebef** [framer/motion#2245]
**1. Read the [FAQs](#faqs) 👇**
Done.

**2. Describe the bug**
Give a clear and concise description of what the bug is.
In React, using typescript, when using the `useScroll` hook and passing options to said hook, for example as follows:
``` tsx
  const container = useRef(null);
  const { scrollYProgress } = useScroll({
    target: container,
    offset: ['start start', 'end start'],
  });
```
It will throw an error:
`Argument of type '{ target: MutableRefObject<null>; offset: string[]; }' is not assignable to parameter of type 'UseScrollOptions'. Object literal may only specify known properties, and 'offset' does not exist in type 'UseScrollOptions'.`

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

https://codesandbox.io/p/sandbox/quirky-davinci-s9c9v7?file=%2Fcomponents%2Ftest-component.tsx%3A9%2C42

**4. Steps to reproduce**

1. use `useScroll` hook as specified in docs
2. pass `offset` option as specified in docs
3. See error

**5. Expected behavior**

No error should be shown since it is also documented appropriately and has worked until version 10.13 flawlessly

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

<img width="1206" alt="image" src="https://github.com/framer/motion/assets/3082620/d305623d-9805-4c39-888e-548fd3b99efb">

**Comment by wansaleh** [comment]
Yes. After 10.13. For some reason they deleted the offset property. Downgraded to 10.12.23 for now.

**Comment by kmkhant** [comment]
Can i fix it ? I think I found a way

**Comment by kmkhant** [comment]
Issue fix successfully, please test if it works correctly now

**Comment by jorgebef** [comment]
Confirming it has been fixed.
Thank you!!
