### ISSUE TITLE
[BUG] Error with useScroll() - Missing offset property

### ISSUE THREAD

**Issue by thetalesofj** [framer/motion#2258]
Hi,

I'm using the useScroll() hook from Framer Motion to achieve a specific scroll behaviour on my website. According to the documentation and examples, there should be an offset property available for the useScroll() hook to control the start and end of animations based on scroll position. 

Example:

```
const ref = useRef(null)
    const {scrollYProgress} = useScroll(
        {
            target: ref,
            offset: ["start end", "center start"],
        }
    )
```

However, when trying to use the offset property as suggested, TypeScript throws the following error:

```
Argument of type '{ target: React.MutableRefObject<null>; offset: string[]; }' is not assignable to parameter of type 'UseScrollOptions'.

Object literal may only specify known properties, and 'offset' does not exist in type 'UseScrollOptions'.ts(2345)

(property) offset: string[]
```

**Environment details**

React version: 18.2.0
Framer Motion version: 10.13.1
TypeScript version: 5.1.6

**Comment by kilimanjjjaro** [comment]
Same here!

**Comment by muneale** [comment]
Same
