### ISSUE TITLE
Nested dragging not working as expected

### ISSUE THREAD

**Issue by tjahn** [framer/motion#227]
**Describe the bug**

Hello, I tried copied example /dev/examples/dragPropagation.tsx which renders a red box nested within a blue box, both draggable.

What I experience is that after dragging the blue box once, I can not drag the inner red box without effecting the blue box.
When dragging the red box before touching the blue box everything works as I expected.
Somehow stopPropagation stops working after the first drag on the outer box.

**To Reproduce**
* Copy the example https://github.com/framer/motion/blob/master/dev/examples/dragPropagation.tsx
* bundle it into some react application
* drag red first -> it is working
* drag blue, then drag red -> blue moves together with red

**Expected behavior**
I expected the blue box to be uneffected by the drag of the inner, red box. Regardless of the order in which I touch them.

**Desktop**
 - MacOS
 - Google Chrome 75 and Safari 12.1.1.
- "framer-motion": "^1.2.6"
- "react": "^16.8.6" on

**Comment by InventingWithMonster** [comment]
Ah this sounds related to an emergent bug in Framer X that we're going to look at on Friday. Thanks for the report - the minimal reproduction I needed was sat right here all along!
