### ISSUE TITLE
[BUG] `useScroll` doesn't update when `offset` is updated

### ISSUE THREAD

**Issue by kalimantos** [framer/motion#2272]
`useScroll` doesn't update when `offset` param is updated

```javascript
const DELTA = 100;
const targetRef = useRef();
const headerRef = useRef();
const headerHeight = useComponentSize(headerRef).height;
const { scrollYProgress } = useScroll({
  target: ref,
  offset: [`start ${headerHeight + DELTA}px`, `start ${headerHeight}px`],
});
``` 

in this case when `headerHeight` changes `scrollYProgress` should change but `useScroll` doesn't notice that change due to empty dependency array in useScroll code. 
https://github.com/framer/motion/blob/main/packages/framer-motion/src/value/use-scroll.ts#L60
a quick fix could be stringify the offset param and pass it to the dependency array

```typescript
export function useScroll({
    container,
    target,
    layoutEffect = true,
    ...options
}: UseScrollOptions = {}) {
    const values = useConstant(createScrollMotionValues)

    const useLifecycleEffect = layoutEffect
        ? useIsomorphicLayoutEffect
        : useEffect

    useLifecycleEffect(() => {
        refWarning("target", target)
        refWarning("container", container)

        return scrollInfo(
            ({ x, y }) => {
                values.scrollX.set(x.current)
                values.scrollXProgress.set(x.progress)
                values.scrollY.set(y.current)
                values.scrollYProgress.set(y.progress)
            },
            {
                ...options,
                container: container?.current || undefined,
                target: target?.current || undefined,
            }
        )
    }, [JSON.stringify(options.offset)])

    return values
}
```

**Comment by ChazUK** [comment]
I know this issue has been marked as fixed and I can also see that the dependencies have also update in future PRs to include the container and target, but this is still causing an issue where I'm trying to incorporate a `useState` variable which is updated inside `useEffect` into the `offset` option. Are there any tips on how I can debug the lifecycle of this update as it doesn't seem like the offset update is being observed before repainting.
