### ISSUE TITLE
DEVS Complete the documentation

### ISSUE THREAD

**Issue by piscopancer** [framer/motion#2279]
![image](https://github.com/framer/motion/assets/109352196/188fab49-8977-49f6-b725-8098b508d3b1)
_where?_

Your documentation is not explaining advanced features and too brief about general features, too few examples and code blocks. You need to expand the existing articles and you also need to explain what is currently not on the docs but for some reason exists in the package, eg `mix()` or `toValue()` functions. I tried learning about them, but you can see on the screenshot that searching gives absolutely 0 matches. There is also no search engine (fe, Algolia or something more simple) right inside your docs page meaning you do not care if people learn framer motion or they get stuck at using only one half of its true power. 

Please take care of the docs guys goddamn

**Comment by mattgperry** [comment]
Search will be coming when we migrate the docs to Framer from their current CMS. Not all functions are public API. If it isn't documented, expect it to be removed, changed or broken.

**Comment by piscopancer** [comment]
> Search will be coming when we migrate the docs to Framer from their current CMS. Not all functions are public API. If it isn't documented, expect it to be removed, changed or broken.

understand. wish you luck to migrate easily 👌
