### ISSUE TITLE
Delayed visualElement subscription can miss animations in using LazyMotion

### ISSUE THREAD

**Issue by gurkerl83** [framer/motion#2292]
When utilizing the LazyMotion component, there's a scenario where the visualElement might not be immediately available for the animation controls. In the original animationControls code, animations get started without ensuring the presence of any subscribed visualElement, potentially causing missed animations.

**Steps to reproduce:**

- Integrate the LazyMotion component into a project.
- Use m-Components.
- Call controls.start() before the visualElement has subscribed - in the effect.
- Observe that animations may be skipped or missed.

```
Lazy-Load.ts
export { domAnimation as default } from 'framer-motion';
```

```
import { m, LazyMotion, useAnimation, useMotionValue } from 'framer-motion';
import { FC, useEffect } from 'react';

// only way to keep bundle size small
const loadFeaturesAsync = async () =>
  await import('./Lazy-Load').then(res => res.default);

// it works when features are loaded synchronously like, but bundle size increases
// import { domAnimation } from 'framer-motion';
// <LazyMotion features={domAnimation}>

export const AnimationTest: FC = () => {
  const controls = useAnimation();

  const variants = {
    foo: { x: 100 }
  };

  const childVariants = {
    foo: { backgroundColor: '#fff' }
  };

  const x = useMotionValue(0);
  const backgroundColor = useMotionValue('#000');

  useEffect(() => {
    controls.start('foo').then(() => {
      console.log('variants result: ', [x.get(), backgroundColor.get()]);
    });
  }, []);

  return (
    <LazyMotion features={loadFeaturesAsync}>
      <m.div
        animate={controls}
        variants={variants}
        style={{ x }}
        onAnimationStart={() => {
          console.log('onAnimationStart outer');
        }}
        onAnimationComplete={() => {
          console.log('onAnimationComplete outer');
        }}
      >
        <m.div
          variants={childVariants}
          style={{ backgroundColor }}
          onAnimationStart={() => {
            console.log('onAnimationStart inner');
          }}
          onAnimationComplete={() => {
            console.log('onAnimationComplete inner');
          }}
        >
          Hello
        </m.div>
      </m.div>
    </LazyMotion>
  );
};
```

Here is the sandbox https://codesandbox.io/p/sandbox/polished-sunset-pg25zr

**Expected Behavior:**
Animations should always be played regardless of **when** the visualElement subscribes.

**Actual Behavior:**
Animations might be skipped if started before the visualElement subscription.

**Suggested Fix:**
Improve animationControls to queue animation start calls and processes them once the visual element is available, see referenced PR

**Comment by mattgperry** [comment]
Because `useAnimation` is deprecated in favour of `useAnimate` I'm probably not going to have the time to fix this so closing as `wontfix` to set expectations
