### ISSUE TITLE
[BUG] `useInView` not working if used within `<Suspense>` and `<Await>` (Remix)

### ISSUE THREAD

**Issue by ParkerMJones** [framer/motion#2295]
**1. Read the [FAQs](#faqs) 👇**
✅
**2. Describe the bug**

`useInView` does not update if the associated element is within `<Suspense>` and `<Await>` in Remix (Remix 1.19.3, framer-motion 10.15.1).

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
[stackblitz](https://stackblitz.com/github/ParkerMJones/framer-motion-useInView-bug?file=app%2Froutes%2F_index.tsx)

**4. Steps to reproduce**

1. Go to [stackblitz example](https://stackblitz.com/github/ParkerMJones/framer-motion-useInView-bug?file=app%2Froutes%2F_index.tsx)
2. The middle element (framer motion within suspense) fails to update it's position appropriately, while the others behave as expected

**5. Expected behavior**

`useInView` should update when the element is in view, if the element is within `<Suspense>`
An example is included showing `react-intersection-observer`'s `useInView` updating correctly from within `<Suspense>`

**7. Environment details**

Apple M2
Chrome Version 115.0.5790.170 (Official Build) (arm64)

**Comment by mattgperry** [comment]
This actually highlights a danger of any API that accepts refs externally that I hadn't considered.

Your best bet is to colocate your ref alongside your `motion` component.

```jsx
      <Suspense fallback={<div>Loading...</div>}>
        <Await resolve={ditto}>
          {(ditto: any) => {
            const dittoRef = useRef(null)
            const isInView = useInView(dittoRef)
            return (
            <motion.div
              ref={dittoRef}
              animate={dittoIsInView ? { translateX: 0 } : { translateX: 300 }}
              transition={{ duration: 0.25 }}
            >
              <h2>{ditto.name}</h2>
              <img src={ditto.sprites.front_default} alt="ditto" />
            </motion.div>
          )
          }}
        </Await>
      </Suspense>
```

**Comment by mattgperry** [comment]
Honestly this is probably not going to be fixed without a more comprehensive API overview.
