### ISSUE TITLE
[BUG] Reorder not working expected

### ISSUE THREAD

**Issue by johypark** [framer/motion#2297]
Reorder mechanism is not working well. Order changes weird.

https://codesandbox.io/p/sandbox/ecstatic-tereshkova-kld3pk

This is the same example in document.

1. Reorder some items.
2. Items will not order well.

Items should order correctly.

https://youtu.be/-Ly1LU2MiPQ

framer-motion@10.15.2

**Comment by Kikuchan-Scc** [comment]
I also encountered the same problem
