### ISSUE TITLE
[BUG] "Invalid keyframe value for property clipPath"

### ISSUE THREAD

**Issue by Profesor08** [framer/motion#2298]
If I try to animate `clipPath`, it warns me in console. I have tried to animate `poligon` and `inset`. If you just trigger the animation, nothing happens, all works. But if you click fast, before the animation end, you will get warnings. As you can see on screenshot, there are values bigger then `0` but without unit `px`.

![image](https://github.com/framer/motion/assets/8218016/62367dac-d797-424f-a7ef-b442a588f961)

**Reproduction of the bug**

https://codesandbox.io/p/sandbox/framer-motion-clippath-bug-c9c85v

**Steps to reproduce**

1. Open console
2. Click multiple times on button
3. See error

**Expected behavior**

Calculation of inset to be correct: `inset(0 0 4.38145px 4.38145px)`. This will avoid warning and property will work correcly.

**Environment details**

Windows 11, Chrome latest

**Comment by yunsii** [comment]
I also got some warning like this:
![image](https://github.com/framer/motion/assets/18096089/0d6d7308-baec-42fb-a44d-3f5de9446cb2)

**Comment by mattgperry** [comment]
You want to ensure unit types are the same across definitions

```javascript
const animate = {
  clipPath: `inset(0 0 0px 0px)`,
};
```
