### ISSUE TITLE
[BUG] animate() in an effect is not properly reading CSS Variables

### ISSUE THREAD

**Issue by samselikoff** [framer/motion#2309]
**Describe the bug**

It seems Framer Motion is having trouble reading CSS Variables when using `animate()` in an effect:

```jsx
useEffect(() => {
  animate(ref.current, {
    // This doesn't work
    opacity: ["var(--opacity-from)", "var(--opacity-to)"]
  });
}, [animate, ref, count]);
```

**CodeSandbox**

https://codesandbox.io/s/framer-motion-css-variable-bug-5vkfws

1. Click button, see message fade
2. Comment out line 12, and uncomment line 15 (uses CSS variables)
3. Click button. Message doesn't fade.

**Expected behavior**

The animation should trigger using the values from the CSS Variables.

**Comment by rudzky** [comment]
any update on this? 😅
