### ISSUE TITLE
[FEATURE] Add drag element direction lock for single direction

### ISSUE THREAD

**Issue by gillescoolen** [framer/motion#2313]
**Is your feature request related to a problem? Please describe.**
AFAIK, it's only possible to set a direction lock for drag-able elements per axis. 

**Describe the solution you'd like**
I want to limit the direction per side. Instead of locking to top/bottom (y-axis) or left-right (x-axis), I just want to limit the direction to bottom only, and have zero movement when dragging to the top.

**Describe alternatives you've considered**
I've tried limiting the direction using the dragConstraints, but I can still slightly drag the element in the top direction.

**Comment by mattgperry** [comment]
Ah I like the idea although realistically this year I think this will only get implemented if we find a need within Framer so for now I'm going to close with `wontfix` to set expectations.
