### ISSUE TITLE
[BUG] conditional rendering and WhileInView

### ISSUE THREAD

**Issue by MrOxMasTer** [framer/motion#2314]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

problem with mounting/unmounting in ts-pattern. I use this library to conveniently display certain elements by the download status from the server, but the problem is that when the status changes, it does not work out the animation, because the viewport (whileInView) conditionally worked on the elements of the "skeleton" for these elements. Usually the elements just don't appear and that's it, as in the example from the sandBox. I simulated the operation of the server by changing the status approximately through useEffect and the elements are no longer being worked out for me. Sometimes the status can change so quickly that even conditional "skeletons" will not appear, and the viewport will work. AnimatePresence doesn't help much either. How could this be solved? For example, so that when changing the childrens, the viewport can be worked out anew.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/variants-forked-7kx82n?file=/src/Example.tsx

A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

**4. Steps to reproduce**

You don't need to click anything, the only thing you can do is change the viewport in the sandbox and see what it works out again and another one appears

**5. Expected behavior**

So that when the status changes, I have other elements with animation

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.
![image](https://github.com/framer/motion/assets/59291123/c646bd76-1db4-4ee9-9234-bca0c7bb37ee)

https://github.com/framer/motion/assets/59291123/51ff71b8-234f-40ea-8b6d-0fb94f974ad9

**Comment by MrOxMasTer** [comment]
![image](https://github.com/framer/motion/assets/59291123/303874c2-8ae8-42df-bef6-dc8d9248f37f)
and it's not even about the library. It doesn't even work that way

**Comment by mattgperry** [comment]
Hey @MrOxMasTer I appreciate the bug - can you update the sandbox though or perhaps save it as when I open it I'm getting the same code as the original example it was forked from.
