### ISSUE TITLE
[BUG] flickering / glitching on scroll-snap and framer on Chrome / Arc

### ISSUE THREAD

**Issue by Brentably** [framer/motion#2315]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

There is a flickering when I use framer with css snap-scroll-type functionality. The flickering takes place on Chrome and Arc, but not Safari or Safari for iOS. This seems to be the same flickering issue as the bug on [this ticket](https://github.com/framer/motion/issues/342#faqs), but it's definitely not the exact same bug--the bug in that ticket doesn't occur anymore. 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[CodeSandbox here](https://codesandbox.io/p/sandbox/github/Brentably/slide-snap/tree/main?file=%2Fpages%2Findex.tsx%3A68%2C28)

A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

**4. Steps to reproduce**

The section with the numbers is horizontally scrollable. Scroll on it and there's flickering and it doesn't work :(

**5. Expected behavior**

It should scroll nicely.

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

[Loom video here](https://www.loom.com/share/c28761b988e045d481bb5f55c687e20a?sid=578fb4ff-23c4-43b1-a349-6e40f14b11f0)
The first part shows it glitching on Chrome, and the second part shows it working nicely on Safari.

**7. Environment details**

The flickering takes place on Chrome and Arc, but not Safari or Safari for iOS.

**Comment by mattgperry** [comment]
I've had a look at the sandbox and stripping it back I can't really find what interaction could be the root of this. Could you reopen with an example built the other way, building the element *until the point it breaks*. For instance we don't need the `scrollTo` to see the break. So start with just the CSS with it scrolling, then add the scroll snapping in CSS, then add a single motion effect etc.
