### ISSUE TITLE
[BUG] Drag breaks when translate has been previously set to calc()

### ISSUE THREAD

**Issue by saltnpixels** [framer/motion#2324]
## Bug
When using drag, I noticed that if the translateX Or Y was already animated to something using css calc(), drag breaks. It can't figure out the starting position, so constraints and stuff seem broken. 

I am using an older version of framer motion v6.5.1, so I don't know if that is the issue or if it is just like this. I can't upgrade right now due to other packages.

### See here:
https://codesandbox.io/s/drag-drawer-5kvh5x

if you remove the code from line 102 which resets the Y value to 0, drag breaks cause its currently set to a string with calc()

**Comment by mattgperry** [comment]
Yeah the initial drag position needs to be set in pixels if set. Realistically this is a `wontfix` unless we bump up against it within Framer.
