### ISSUE TITLE
[BUG] Scale applied twice with `layout` prop

### ISSUE THREAD

**Issue by VimHax** [framer/motion#2328]
# Bug

I believe `layout` uses transforms to more efficiently move and resize elements when the layout changes. It is said in the documents that to prevent distortion of child elements that `layout` prop can be passed in so that an inverse scale would be applied. I believe below I have found a situation where the above expected behavior is not present.

```tsx
<motion.div
  layout
  initial={{ borderRadius: 50 }}
  className="child"
  style={{ width: isOpen ? 300 : "100%" }}
  transition={{ duration: 5 }}
>
  BBBBB
  <motion.div
    layout
    transition={{ duration: 5 }}
    style={{ width: "100%", height: "100%" }}
  >
    {" "}
    AAAAAA
  </motion.div>
</motion.div>
```

![image](https://github.com/framer/motion/assets/45242122/1fc338ab-345e-4dd6-b1e1-d2ff866f535d)

The scale seems to be getting applied twice to the child element, the first one removing the distortions but the second scale adding the distortions back in. (`0.850396 × 1.17592 = 0.99999766432`)

# Sandbox

https://codesandbox.io/s/framer-motion-2-scale-correction-forked-zqfq6h

**Comment by mattgperry** [comment]
This is actually working as expected, as evidenced by the lack of distortion on the pink box.

To remove distortion on the text, the `layout` element bounding box needs to match the text in both states. But by using Chrome inspection tools you can see the bounding box is quite different between states.

**Comment by mattgperry** [comment]
You can add a blue background to the AAAAA div to illustrate what's going on here.

**Comment by VimHax** [comment]
Oh okay, thanks for the quick response! I love the library you guys have developed here. :)
