### ISSUE TITLE
[BUG] When using transition type "spring", "whileInView" doesn't work properly

### ISSUE THREAD

**Issue by hangooksaram** [framer/motion#2335]
**1. Describe the bug**

When using `whileInview` and using a `spring` for the `type` of `transition`, when **scrolling up and down repeatedly**, the motion element does not move properly and is interrupted. I think it's because of `spring`. Because when I removed the `spring`, it worked normally.

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/transition-spring-example-mrysfp?file=/src/App.js

**3. Steps to reproduce**

1. Scroll up and down repeatedly

**Comment by mattgperry** [comment]
This has been fixed in the meantime
