### ISSUE TITLE
[BUG] onHover over grid of <rect/>'s do not return to their original spot

### ISSUE THREAD

**Issue by Stillerman** [framer/motion#2337]
**2. Describe the bug**

When I hover over the boxes, they do not return to their o.g. spot, they appear to double their x and y coords.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[SANDBOX](https://codesandbox.io/s/broken-grid-tw9spv?file=/src/App.js)

**4. Steps to reproduce**

1. Open Sandbox
2. Hover any box

**5. Expected behavior**
It grows and then shrinks

**6. Video or screenshots**
<img width="436" alt="Screenshot 2023-09-10 at 5 19 13 PM" src="https://github.com/framer/motion/assets/8527894/e4938dbd-e4e3-4335-82af-26ca47f5f3e7">

**Comment by mattgperry** [comment]
Ah yeah this is annoying but there's a difference between the CSS transforms and SVG attributes. To set the CSS transforms (which are later animated), use `initial`

```
            initial={{ x: i * WIDTH, y: j * WIDTH }}
            whileHover={{ width: WIDTH, height: WIDTH, x: 0, y: 0 }}
            key={`${i}-${j}`}
            width={WIDTH * 0.9}
            height={WIDTH * 0.9}
```

**Comment by Stillerman** [comment]
Thank you
