### ISSUE TITLE
[Question] AnimatePresence - only works for top children

### ISSUE THREAD

**Issue by lluzak** [framer/motion#234]
**Describe the bug**
I am trying to use AnimatePresence in Menu example.

**To Reproduce**
https://codesandbox.io/s/framer-motion-side-menu-erz68?from-embed

**Expected behavior**
Is there a way to animate whole tree on exit or only top children ?

**Comment by InventingWithMonster** [comment]
```
animate={"open"}
```

Would be correct - but otherwise this is the intended way to achieve this. Looks like a bug to me.

**Comment by InventingWithMonster** [comment]
What's weird is the sidebar actually is a child and thats animating fine

**Comment by lluzak** [comment]
i debug problem:

https://github.com/framer/motion/blob/32c9d53b336f1533fd9895fc59c06e5be4e4fe83/src/animation/use-value-animation-controls.ts#L32

That is a root cause. `<motion.ul>` element is being render on closing and which also clean all children, but because children are the same, they are not being render and never again added to parent controls.

**Comment by InventingWithMonster** [comment]
I think you're probably right!

I assumed 

```jsx
<motion.li key="a" variants={{...a}}>Test</motion.li>
```

Would force them to be rerendered tho and they aren't
