### ISSUE TITLE
[BUG] whileHover does not repaire the original style

### ISSUE THREAD

**Issue by ZenkieBear** [framer/motion#2341]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
The `whileHover` has some performance consistency problem.
①: If there're more than 1 motion element which defined `whileHover={{ scale: [1.5, 1.4] }}`, scale value not start with `null` and the element hasn't define **style** or **animate** attribute. 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/pedantic-hellman-rmf3f7?file=/src/App.tsx:132-260

**4. Steps to reproduce**
1. Now I have a element like below. Hover the element and leave it, the element will scale and back to its own style.
```jsx
<motion.div
  whileHover={{ scale: [1.5, 1.4] }}
/>
```
2. Copy this element ensure they meets requirement ①.

**5. Expected behavior**
The style after hover event should be its original style `scale: 1`, even I had not defined. Else it does not conform to _**consistency logic**.

**Comment by mattgperry** [comment]
Please reopen with a valid sandbox link
