### ISSUE TITLE
[BUG] `onDragStart` firing after `onDrag`

### ISSUE THREAD

**Issue by ruvkr** [framer/motion#2345]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

`onDragStart` firing after `onDrag`

```jsx
 <motion.div
   className="box"
   drag
   onDrag={() => console.log("DRAG")}
   onDragStart={() => console.log("DRAG START")}
   onDragEnd={() => console.log("DRAG END")}
 />
```
In console:
```
v10.1.0 and up
--------------
DRAG 
DRAG START 
DRAG x 37
DRAG END 

v10.0.2
--------------
DRAG START 
DRAG x 54
DRAG END
```

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-press-tap-animations-forked-y7lh9z?file=/src/App.tsx

**4. Steps to reproduce**

1. Go to CodeSandbox
2. Drag the button
3. See console

**5. Expected behavior**

Expected `DRAG START` to be printed before `DRAG`

**Comment by mattgperry** [comment]
Dupe https://github.com/framer/motion/issues/2056
