### ISSUE TITLE
border-radius value breaks useAnimation

### ISSUE THREAD

**Issue by zidkim** [framer/motion#2349]
Directly irrelevant to the question below but in case I forget, v10 useAnimate makes my animation extremely laggy, hence I'm using v9. Due to other bugs, I'll be excluding v7 and v10.

ISSUE: When using framer motion v9, v8, v7, or v6's useAnimation, my css "breaks" (explained below) when I set border-radius with a single value (I need at least 2). This is not an issue with framer-motion@^5.6.0.

```
// works in framer-motion@^5.6.0, regardless of the number of values I set for border-radius. Breaks from v6 to v9+.
border-radius: 2rem; 

// works in all versions
border-radius: 0px 0px 0px 2rem; 

// I suspect it's related to my use of useAnimation? Here I'm setting initial state. 
  useEffect(() => {
    controls.set({
      "--dx": `200%`,
      "--dy": `0%`,
      "--bg-x": `58%`,
      "--bg-y": `45%`,
      transition: {
        ease: "linear",
      },
    });
  }, []);
  
```

TECHNOLOGIES: 
- Framer motion v9
- NextJS v12
- React 18+

I understand that v10 is the new standard, however, useAnimate for some reason is extremely non-performant for the animations I'm making. It's pretty resource intensive, but it works fine in previous versions. Anyway, given that v10 is rather fresh, I thought I'd hope to get somewhere with this issue in a more stable version first.

Really hoping to get some answers/insights into this! Thank you in advance!!!!

**Comment by mattgperry** [comment]
Please reopen with sandbox. I'd be especially interested into your attempts with `useAnimate` and performance - I find it unlikely as they both use the same underlying code.
