### ISSUE TITLE
[BUG] AnimatePresence uses undesired values

### ISSUE THREAD

**Issue by agonsalves** [framer/motion#235]
I am using AnimatePresence to slide an element up from the bottom of the screen on mount, and then slide it out to the left on unmount. Here are my variants:
```
            defaultInitial: {
                position: 'fixed',
                top: '100vh',
                marginLeft: '0%',
            },
            defaultEnter: {
                position: 'relative',
                marginLeft: '0%',
                top: '0vh',
                transition: {
                    duration: .5
                },
            },
            defaultExit: {
                marginLeft: '-100%',
                top: '0vh',
                transition: {
                    duration: .5
                }
            },
```
Here is my component:
```
                <motion.div
                    key={currPost.id}
                    variants={variants}
                    initial="defaultInitial"
                    animate="defaultEnter"
                    exit="defaultExit"
                >
```

The problem I am having is that on mount, the component gets a left-margin value of NEGATIVE % and then animates to 0%.

Here is a snapshot of the div as it is animating in: `<div style="position: relative; margin-left: -10.2873%; top: 10.2645vh;">`

I have no idea where this negative value is coming from. I have tried changing units, position values, everything. I even change leftMargin to left or even x. It still gives it some negative initial value.

This only occurs on the initial load. Subsequent transitions use their proper values.

**Comment by InventingWithMonster** [comment]
I'll take a look at this - as a side note I'd recommend using `x` and `y` values to animate for improved performance.

**Comment by InventingWithMonster** [comment]
I've made a reproduction here https://codesandbox.io/s/framer-motion-bug-demo-rv5e2

It seems ok to me? Could you fork and amend to reproduce the bug?

**Comment by agonsalves** [comment]
Thank you for taking the time to help.

Right now, I am not sure how to replicate it because it depends on certain factors to emerge. If I knew more about the expected behavior, I might be able to look for various conditions that might affect it. I am using this method for basically all of my page transitions. Most pages animate in on load just fine. However, a subset of them exhibit this issue. I cannot figure out what makes them different, as I have most things standardized across pages.

I'll keep trying to figure it out.

**Comment by agonsalves** [comment]
Ok, I have managed to find the difference between pages that determines whether this happens or not, but I am not sure what to make of it.

Basically, nested a couple levels within the animated div, there is another div (flex) that can have 1 or 2 elements within it. When it only has 1 element, the page loads fine. When it has 2 elements within it, this problem occurs. I have not yet figured out anything else that affects it other than the presence of this element. I have played around with margins, padding, box sizing with all of the child elements and no adjustment seems to be able to affect it.

**Comment by InventingWithMonster** [comment]
Can you put together a codesandbox example for me to investigate further?

**Comment by agonsalves** [comment]
I can't do that. Too complex. I'll just link the WIP:

This is a page that works correctly: https://rm5.gjtest.com/ernest-j-aaronson-ii/news

This is a page that has the problem: https://rm5.gjtest.com/ernest-j-aaronson-ii/news/test-test

Again, the issue only occurs when you reload the page from scratch. Navigating between pages works fine.

**Comment by InventingWithMonster** [comment]
Closed for inactivity
