### ISSUE TITLE
[BUG] Shared layout animation is reversed

### ISSUE THREAD

**Issue by ZenkieBear** [framer/motion#2350]
**Describe the bug**
The [Shared layout animation] might got a logic problem.
Now I have:
```jsx
<motion.div
  className={styles["focus-line"]}
  layoutId="focus-line"
  initial={{ scale: 2 }}
  animate={{ scale: 1 }}
/>
```
When the initial scale more than 1x, the rendered size is smaller than 1x scale.
When inital scale less than 1x, the rendered result is bigger than 1x scale.
It's totally reversed😟

**IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/p/sandbox/billowing-pine-twxs3z?file=%2Fapp%2Fpage.tsx%3A14%2C36-24%2C15

**Comment by mattgperry** [comment]
Please reopen with valid sandbox link
