### ISSUE TITLE
[BUG] Reorder doesn't work at all with React 18 (framer-motion 8 works)

### ISSUE THREAD

**Issue by Megamannen** [framer/motion#2351]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
Reorder breaks down after some moves. 
It stops working completely or just stops putting things in the correct order

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/framer-motion-5-drag-to-reorder-lists-forked-zx5sc7

**4. Steps to reproduce**

1. Move the items around, it will break, for example
* Tomato to 3
* Tomato to 1
* Tomato to 2 (can't do it)

**5. Expected behavior**
That reorder works

**6. Video or screenshots**
-

**7. Environment details**
Firefox, Linux
(But also noticed in Windows + Edge or Chrome, unsure)

**Comment by NunesClement** [comment]
The problem appeared in framer-motion: 10.12.7, you can rollback to this version.

**Comment by mattgperry** [comment]
Collecting here https://github.com/framer/motion/issues/2476
