### ISSUE TITLE
Change CSS classes with Framer Motion

### ISSUE THREAD

**Issue by nikita-bashaiev** [framer/motion#2352]
This request is mainly related to using Tailwind with Framer Motion. It is very inconvenient to have to go back to setting primitive CSS values instead of using classes like I do for every non-motion piece of UI. Also, being able to have just one source of truth (e. g. Tailwind values in my case) just makes more sense to me.

The solution I was thinking of looks something like this:

```js
const bodyVariants = {
  hidden: {
    className: "h-0 opacity-0"
  },
  expanded: { 
    className: "h-auto opacity-100" 
  },
};
```

Or this:

```js
const bodyVariants = {
  hidden: {
    classes: ["h-0", "opacity-0"]
  },
  expanded: { 
    classes: ["h-auto", "opacity-100"] 
  },
};
```

I am not entirely sure if this would be possible to achieve as I am a beginner in the world of JS. Thus, I would appreciate if anyone let me know of the flaws and limitations of the approach presented above and/or propose some other way to achieve the goal described above.

One other solution I thought of is an option to make Framer Motion detect any changes in any of the properties of an element - e.g. colors, padding, margins, transforms etc. and animate them all at once. This would solve some of the problems with classes, such as differentiating between classes that will and won't change and making sure there are no conflicts and unexpected behaviors. It would make animating things a lot simpler - allowing users to declare all of the properties based on the needed conditions and basically telling Framer Motion to "figure it out and animate it". I imagine that it would, however, make it harder to provide users with granular control over each property. I am also not sure how hard this would be to implement, but it seems to me that this is what is already happening when one builds components with Framer (the web building tool)

**Comment by KGZM** [comment]
Have you looked at [twin.macro](https://github.com/ben-rogerson/twin.macro)?

It parses tailwind classes into a style object.

**Comment by LaxVox** [comment]
Just tried it and it seems to work perfectly for this use-case. Thanks a lot!

**Comment by LaxVox** [comment]
Or maybe it actually didn't. I had this piece of code: 
```js
const descVariants = {
  hidden: { height: 0, marginTop: 0, opacity: 0.8 },
  expanded: { height: "fit-content", marginTop: "1em", opacity: 1 },
};
```
and changed it to this:
```js
const descVariants = {
  hidden: tw`h-0 mt-0 opacity-80`,
  expanded: tw`h-auto mt-4 opacity-100`,
};
```
but my component just disappeared completely. Do you have any working example of how to use twin.macro with Framer Motion? Would be grateful to be able to see what I did wrong

**Comment by mattgperry** [comment]
I appreciate why you might want this but I think changing classes should be left for React, especially as our layout animations work on reading the layout it computes.

**Comment by johnsonthedev** [comment]
I also want to use classes instead of styles in the motion animation property. I understand that this will not be implemented by framer but does anyone know about a third party plugin to do this ? thx

**Comment by t-fritsch** [comment]
sorry for the late reply, in case it helps

@johnsonthedev https://github.com/reactjs/react-transition-group/ used to do that, but it's dead ([no support for react19](https://github.com/reactjs/react-transition-group/issues/918), last commit 3 years ago (dependabot...))

[someone mentioned](https://github.com/reactjs/react-transition-group/issues/918#issuecomment-2639071566)  https://github.com/szhsin/react-transition-state 
the readme provides a link to a [tailwind example](https://codesandbox.io/p/sandbox/react-transition-tailwindcss-21nys?file=%2Fsrc%2FApp.js)

I haven't had the chance to test it yet, sticking for now with motion and transitions defined in JS (I wish we could use classnames in motion or even pre-defined ones like rtg used to do... 🥺)

**Comment by tavishcode** [comment]
this kind of structure worked for me. toggled the classname based on a react state

` <motion.div
              layout
              className={
                hasSearched
                  ? "fixed bottom-8 left-0 right-0 flex justify-center z-50 pointer-events-none"
                  : "flex w-full items-center justify-center z-2 px-4 gap-2"
              }
            >`
