### ISSUE TITLE
[BUG] Exit animation not triggered with React Router v6

### ISSUE THREAD

**Issue by AtoLrn** [framer/motion#2367]
**2. Describe the bug**

The Exit animation is not triggering, the dom element is instantly removed

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/keen-dream-4vhcjc?file=/src/App.tsx

**4. Steps to reproduce**

1. Go to the codeSandbox Link
2. Click on **To Test1** or **To Test2**
3. The exit animation is not triggered

**5. Expected behavior**

The expected behavior would be to have exit animation

**7. Environment details**

On Firefox, With react router 6

## Important Code Part

Defining the AnimatePresence 
```jsx
<AnimatePresence mode='wait'>
          <RouteWrapper />
</AnimatePresence>
```

The RouteWrapper with the children routes with each a key set to a hardcoded one
```jsx
const RouteWrapper = () => {
  const location = useLocation();
  
  return <Routes location={location} key={location.key}>
  <Route path="/" element={<m.p key={'key-one'} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 2 }}>
    Test1
  </m.p>} />
  <Route path="/test2" element={<m.p
    key={'key-two'} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 2 }}>
      Test2
  </m.p>} />
</Routes>
}
```

**Comment by mattgperry** [comment]
Please re-visit the Bug report FAQs
