### ISSUE TITLE
[BUG] useScroll not change scrollYProgress value using a target ref.

### ISSUE THREAD

**Issue by syedslegend786** [framer/motion#2368]
The root is using 100vh and overflow-auto for snap scroll effect.
I want parallax effect in this component on the text, but its not working.

"use client";
import { cn } from "@/lib/utils";
import { useScroll, useTransform, motion, useMotionValue } from "framer-motion";
import React, { useEffect, useRef } from "react";
interface ParallaxProps {
  type: "Services" | "Portfolio";
}
export function Parallax({ type }: ParallaxProps) {
  const containerDiv = useRef<any>(null);
  const { scrollYProgress } = useScroll({
    target: containerDiv,
    offset: ["start start", "end start"],
  });
  const yText = useTransform(scrollYProgress, [0, 1], ["0%", "500%"]);
  console.log({scrollYProgress})
  return (
    <div
      ref={containerDiv}
      className={cn("h-full w-full relative ", {
        "bg-gradient-to-t from-[#111132]  to-[#0c0c1d]": type === "Services",
        "bg-gradient-to-t from-[#111132]  to-[#505064]": type !== "Services",
      })}
    >
      <motion.h1 style={{ y: yText }} className="font-bold text-5xl">
        {type === "Services" ? "What I Do?" : "What I Did?"}
      </motion.h1>
      {/* mountains */}
      <div className="bg-[url('/images/mountains.png')] absolute inset-0 bg-cover bg-no-repeat bg-bottom"></div>
      {/* planets */}
      <div className="bg-[url('/images/planets.png')] absolute inset-0 bg-cover bg-no-repeat bg-bottom"></div>
      {/* stars */}
      <div className="bg-[url('/images/stars.png')] absolute inset-0 bg-cover bg-no-repeat bg-bottom"></div>
    </div>
  );
}

**Comment by mattgperry** [comment]
Please reopen with a sandbox
