### ISSUE TITLE
Need help getting `useViewportScroll` to work properly

### ISSUE THREAD

**Issue by h-jennings** [framer/motion#237]
Hi there, 

Apologies in advance if this isn't to correct place to ask for help.

I'm working on adding `framer-motion` into a react project I'm working on and can't seem to get the `useViewportScroll` feature to work properly in my project.

I've created an isolated component within my app to test out this feature called `DivTest`
you can find the project here: https://codesandbox.io/s/github/h-jennings/portfolio-2019 and the test component is in the `src/js/components/` folder in the project. Here's a public github repo link if that's easier: https://github.com/h-jennings/portfolio-2019.

Anyway, by following the docs I'm expecting the `<motion.div className="divTest" style={{ scale }} />` components scale value to increase on scroll. This is the codeSandbox that I referenced: https://codesandbox.io/s/c4ww4?module=%2Fsrc%2FExample.tsx

I've been poking away at this component for an hour or 2, plus reading the docs and I'm just not sure at this point if I'm using the syntax correctly, or importing the library incorrect etc.

Any help or advice would be appreciated!

**Comment by h-jennings** [comment]
Woah! Interesting, I just located the issue.
On my `<body>` tag I had the following css added:

```css
body {
width: 100%;
height: 100%;
}

```

Upon removing `height: 100%;` the `useViewportScroll` feature worked as expected.

Might be something you want to add to the documentation as that's a pretty common css reset.

Thanks again!

**Comment by InventingWithMonster** [comment]
Yeah fair point, I'll leave this open to do so.

**Comment by Chizzah** [comment]
Anyone have an example of fading in when scrolled into viewport or is this not an use case for useViewportScroll? Very new to not only framer but animation in a whole
