### ISSUE TITLE
[BUG] Node v21+ implements global navigator without userAgent prop, which breaks SSR

### ISSUE THREAD

**Issue by apostolos** [framer/motion#2371]
Recently released Node v21 partially implements the Navigator interface, however it doesn't include the userAgent property.

This breaks code like:
https://github.com/framer/motion/blob/main/packages/framer-motion/src/projection/node/create-projection-node.ts#L2099-L2101

### Release notes:
https://nodejs.org/en/blog/announcements/v21-release-announce#navigator-object-integration

### Repro:
Render a component with framer-motion with a SSR framework like Next.js using Node v12

### Suggested fix:
Test for `window` before touching the `navigator` object or additional check if `userAgent !== undefined`?

**Comment by picasocro1** [comment]
I have the same issue.

@apostolos I'm only wondering whether in your fix it should be an additional casting to the boolean, to keep the consistency of the function result (always boolean, not boolean | undefined)

```
const userAgentContains = (string: string) =>
    typeof navigator !== "undefined" &&
    !!navigator.userAgent?.toLowerCase().includes(string)
```

**Comment by Uzlopak** [comment]
In node 21.1.0 navigator has now userAgent. Is your issue now solved?

**Comment by apostolos** [comment]
@Uzlopak It is!

Confirmed fixed in Node v21.1.0

**Comment by hirbod** [comment]
We bumped the framer-motion resolution to v10.16.5 (used by Moti, a React-Native library).
The undefined check is not sufficient for React Native, as navigator is defined but navigator.userAgent is not.

![simulator_screenshot_59501023-3208-4B41-9053-9DFAD95900F9](https://github.com/framer/motion/assets/504909/59eda410-7f69-45cf-ad7e-ca2e09bdbfbc)

**Comment by Uzlopak** [comment]
@hirbod 
Update to node 21.1.0

**Comment by hirbod** [comment]
@Uzlopak node is not related to React Native.

**Comment by Uzlopak** [comment]
Then this issue has nothing to do with the problem you reported. So please open a new issue.

**Comment by hirbod** [comment]
The issue is exactly related to it, since its the same code that breaks. RN resolves to the CJS part, but its unrelated to node.
Here is a patch file in case anybody else encounters this.

```patch
diff --git a/node_modules/framer-motion/dist/cjs/index.js b/node_modules/framer-motion/dist/cjs/index.js
index bd8dc68..8c1397d 100644
--- a/node_modules/framer-motion/dist/cjs/index.js
+++ b/node_modules/framer-motion/dist/cjs/index.js
@@ -4219,8 +4219,7 @@ const defaultLayoutTransition = {
     duration: 0.45,
     ease: [0.4, 0, 0.1, 1],
 };
-const userAgentContains = (string) => typeof navigator !== "undefined" &&
-    navigator.userAgent.toLowerCase().includes(string);
+const userAgentContains = (string) => typeof navigator !== "undefined" && typeof navigator.userAgent !== "undefined" && navigator.userAgent.toLowerCase().includes(string);
 /**
  * Measured bounding boxes must be rounded in Safari and
  * left untouched in Chrome, otherwise non-integer layouts within scaled-up elements
```

**Comment by Uzlopak** [comment]
I disagree, because the title states clearly "Node v21+". 
Anyhow, when you check for type, you could directly check if navigator.userAgent is a string...

**Comment by biels** [comment]
Maybe use something like this instead? I had to patch it to use with node v21.

```typescript
const userAgentContains = (string) => typeof navigator?.userAgent !== "undefined" &&
    navigator.userAgent.toLowerCase().includes(string);
```
