### ISSUE TITLE
[BUG]React.useState hook cooperate with motion animate property in Framer Motion version 10.16.4 very choppy

### ISSUE THREAD

**Issue by wave2006** [framer/motion#2372]
**Describe the bug**

The animation effects created with React.useState hook and the motion animate property in Framer Motion version 10.16.4 are very choppy. However, this issue doesn't occur with version 10.2.3 or any earlier historical versions.

**IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-animate-on-state-update-forked-xtl3px?file=/package.json

**Steps to reproduce**

1. Drag the x/y/rotate sliders.
2. You can see that the animation on the left side square is very choppy.

**Expected behavior**

A typical Framer animation should be extremely smooth.

**Environment details**

browser：chrome 117.0.5938.89 64bit

react：react 18

system：windows 11

**Comment by wave2006** [comment]
I suspect that perhaps some crucial changes were made starting from version 10.2.4 that caused this issue, but neither Framer Motion nor the FAQ mention any relevant updates or details. I haven't been able to find any code optimization solutions either.

**Comment by mattgperry** [comment]
Same underlying issue as https://github.com/framer/motion/issues/2088

**Comment by joeymich** [comment]
This issue still exists react 18.2.0 framer-motion 11.1.8
