### ISSUE TITLE
[BUG] The document‘s logic error

### ISSUE THREAD

**Issue by ZenkieBear** [framer/motion#2373]
**Describe the bug**
When I browser to **Scroll** page, there is an CodeSandbox example doesn‘t match the theme on this page.
<img width="1745" alt="image" src="https://github.com/framer/motion/assets/62818957/06e3ddd4-1968-4543-a569-29858f374a52">

**Comment by mattgperry** [comment]
Thanks will remove

**Comment by mattgperry** [comment]
Weird this is the sandbox I see https://codesandbox.io/p/sandbox/framer-motion-usescroll-xwdxbt
