### ISSUE TITLE
[BUG] Node 21 now has a "navigator" object defined on global scope.

### ISSUE THREAD

**Issue by nicksrandall** [framer/motion#2376]
This line no longer works in Node v21 because "navigator" is not on the global scope but it does not have an `userAgent` property.
There may be other issues but this is the first one I encountered when upgrading to node 21. 

https://github.com/framer/motion/blob/main/packages/framer-motion/src/projection/node/create-projection-node.ts#L2100

**Comment by AaronSTAY** [comment]
Causing me build errors even with all Framer Motion components removed from my client side code

**Comment by AaronSTAY** [comment]
Resolved manually setting Node version

**Comment by rmill2016** [comment]
> Resolved manually setting Node version

I tried setting .nvmrc to my node version as well as adding engines property to package.json, this wasn't able to resolve it for me. What did you do?

**Comment by AaronSTAY** [comment]
Locally, you can switch your Node version using NVM

For issues in CI/CD, I had to expressly set the node version in my runner and builder inside my Dockerfile

**Comment by rmill2016** [comment]
Alright, I just did this via nvm install 21.1.0 and nvm use 21.1.0. This doesn't seem to have fixed the issue, I'll probably just wait until the PR gets merged.

**Comment by AaronSTAY** [comment]
You will need to go down to a version below 21 to get it working.

**Comment by meabed** [comment]
this has been fixed in latest release https://github.com/nodejs/node/releases/tag/v21.1.0
