### ISSUE TITLE
item is disappearing when pressed quickly. (AnimatePresence wait mode) [BUG]

### ISSUE THREAD

**Issue by nodirbekrajaboff** [framer/motion#2380]
My codes (on Nextjs):

"use client"

import { useTheme } from "next-themes";
import CircleButton from "./circle-button";
import { Moon, Sun } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

export default function ThemeSwitcher() {
    const { theme, setTheme } = useTheme();

    const changeTheme = () => {
        setTheme(theme === "dark" ? "light" : "dark");
    };

    return (
        <CircleButton onClick={changeTheme} className="overflow-hidden">
            <AnimatePresence mode="wait" initial={false}>
                <motion.span
                    initial={{
                        opacity: 0,
                        y: -20
                    }}
                    animate={{
                        y: 0,
                        opacity: 1
                    }}
                    exit={{
                        opacity: 0,
                        y: 20
                    }}
                    transition={{
                        type: "keyframes"
                    }}
                    key={theme}
                >
                    {theme === "dark" ? <Moon size={20} /> : <Sun size={20} />}
                </motion.span>
            </AnimatePresence>
        </CircleButton>
    );
}

https://github.com/framer/motion/assets/119718499/92c8711f-bfa2-42b7-834b-08783dee319d

**Comment by OSAMA263** [comment]
any update?

**Comment by mattgperry** [comment]
Please reopen with a codesandbox
