### ISSUE TITLE
[BUG] onPan stops firing almost immediately on mobile (after ~ 2-5 times) - broken

### ISSUE THREAD

**Issue by elieven** [framer/motion#2386]
**Desrcription**

The `onPan` event is inconsistently firing and prematurely ending on mobile.

**Steps to reproduce**

1. Go to [https://codesandbox.io/s/framer-motion-mobile-pan-broken-forked-cvp4m7?file=%2Fsrc%2FApp.tsx](https://codesandbox.io/s/framer-motion-mobile-pan-broken-forked-cvp4m7?file=%2Fsrc%2FApp.tsx)
2. Open sandbox in another window or somehow enter mobile mode
3. Start and keep panning
4. Notice that after only a few calls the `onPan` stops firing

**5. Expected behavior**

The `onPan` should keep firing as it does on desktop

**Comment by mattgperry** [comment]
I suspect you want to add something like https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action
