### ISSUE TITLE
[BUG]Server Error Error: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function

### ISSUE THREAD

**Issue by AjitSingh-Brar** [framer/motion#2388]
Hi there,

After installing the framer-motion version 7.0. It gives an error when I am trying to apply on the NEXT Js application of version 14.0.1 and react version 18..2.0. Please let me know how can I resolve the issue

![img12](https://github.com/framer/motion/assets/68308589/21aa5c96-aa72-49a7-8285-928f279d3fa7)

**Comment by remrcll** [comment]
Same error for me with:
"next": "^13.5.6",
 "react": "18.2.0",
 "react-dom": "18.2.0",
 "framer-motion": "^10.16.4",

**Comment by remrcll** [comment]
I fixed the issue by adding 'use client' on my component. 
[[How does the "use client" directive work in Next.js 13 - stackoverflow](https://stackoverflow.com/questions/76369521/how-does-the-use-client-directive-work-in-next-js-13)]

**Comment by fitsaleem** [comment]
yes add use client it will work on your component

**Comment by melvinJD** [comment]
I now have this issue, however I am already using 'use client' ; any help would be greatly appreciated...

**Comment by madwhopaka** [comment]
When I am using "use client", I am getting another error : 

![image](https://github.com/framer/motion/assets/74057522/e629b979-fd03-46fa-8215-739c30dfa231)

**Comment by fitsaleem** [comment]
> When I am using "use client", I am getting another error :
> 
> ![image](https://private-user-images.githubusercontent.com/74057522/299884336-e629b979-fd03-46fa-8215-739c30dfa231.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDcwMDcsIm5iZiI6MTcwNjI0NjcwNywicGF0aCI6Ii83NDA1NzUyMi8yOTk4ODQzMzYtZTYyOWI5NzktZmQwMy00NmZhLTgyMTUtNzM5YzMwZGZhMjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA1MjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3YjY4ZDczNGNkOTU0MzlmZGMyOTg5MDVlOTczMjEzNThlNTQ1NDRmYjFjMDI2ZTFlMzJjOWE3ZjI5YjdjMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DTbqiRspaDhvGOZNTfiAl8wb5E4ROEjRA7gZeGfbfOA)

this error occurred because you did not import the useState hook as react. check on your file where you used this hook and do the correct import.
like:
import React, {  useState } from "react";

**Comment by madwhopaka** [comment]
Actually I have not used useState anywhere until now. It says the the error is in the framer motion files.

**Comment by fitsaleem** [comment]
Please share project terminal output also your browser console output so
maybe I will helpful to fix your issue

Saleem raza

**Comment by FarhanWijonarko** [comment]
> Saya memperbaiki masalah ini dengan menambahkan 'gunakan klien' pada komponen saya. [ [Bagaimana cara kerja arahan "gunakan klien" di Next.js 13 - stackoverflow](https://stackoverflow.com/questions/76369521/how-does-the-use-client-directive-work-in-next-js-13) ]

thanks bro

**Comment by moewbasit** [comment]
**Error: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function**

i have used 'use client' but still got this error

**Comment by moewbasit** [comment]
guys im facing this error from past two days but cant find any way to debug it
Error: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function

after deep research, i can say that it MAYBE due to some dependency issues. This is my package.json

  "dependencies": {
    "@toruslabs/eccrypto": "^5.0.1",
    "@walletconnect/ethereum-provider": "2.13.3",
    "@web3auth/web3auth": "2.1.3",
    "bn.js": "^5.2.1",
    "ethers": "5.7.0",
    "magic-sdk": "^28.0.7",
    "moralis": "^2.26.7",
    "moralis-v1": "^1.13.0",
    "next": "14.2.4",
    "pino-pretty": "^11.2.1",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-moralis": "^1.4.2"
  },
  "devDependencies": {
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "yarn-deduplicate": "^6.0.2"
 }
 and error remains even after using 'use client'
 please help me

**Comment by ZendeAditya** [comment]
ad₫ "use client" to solve this issue

**Comment by MinhMeoNguyen0** [comment]
Is there another way not using "use client"?

**Comment by vishal590** [comment]
> I now have this issue, however I am already using 'use client' ; any help would be greatly appreciated...

I also use "use client" already and yet showing that error
