### ISSUE TITLE
[BUG] AnimatePresence glitch on morphing the same element in a row

### ISSUE THREAD

**Issue by radubortan** [framer/motion#2391]
**2. Describe the bug**

Hello, I'm trying to animate a modal opening by clicking on a div from a group of divs. The clicked div is meant to morph into the modal. I'm trying to do this using AnimatePresence and layoutId. When opening the modal for the first time, everything works normally, but if I try to open the modal again using the same div, it glitches when closing. The problem occurs only if I open the modal using the same div in a row. If I alternate between divs, everything is normal. I think this has something to do with AnimatePresence because if I remove it, the bug doesn't occur anymore.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/pedantic-leaf-h9gps7?file=/src/App.js

**4. Steps to reproduce**

Click on the red div to open the modal, then click on the modal to close it. Click on the red modal again and the bug will occur when closing the modal.

**5. Expected behavior**

The modal shouldn't glitch when opened using the same div in a row.

**6. Video or screenshots**

https://github.com/framer/motion/assets/72158314/718f87bd-edd9-430a-888c-09cc8489307b

At the beginning, I'm showing what happens if you use the red div two times in a row, which is when the bug occurs.
I then show that if you alternate between the red and the blue one, the bug doesn't occur.

**7. Environment details**

M1 MacBook with MacOS Sonoma 14.1. Tested on Firefox (119.0), Safari (17.1), Chrome (119.0.6045.105)

**Comment by LiMao00** [comment]
I also discovered this bug in the past few days and couldn't find a solution. Considering the numerous issues accumulated in this library, it seems unlikely to be resolved in the short term. My suggestion is to avoid using <AnimatePresence>. Although it is useful for creating pop-ups, it has a critical bug that currently has no solution.

At the same time, you can see that the official example 'motion/dev/examples/Shared-layout-lightbox-crossfade.tsx' is in a similar situation. It's a bit frustrating.

![动画](https://github.com/framer/motion/assets/99939885/b70f8ece-f12b-4743-913d-3e7992b87f64)

**Comment by heavymachinery** [comment]
I am also running into this. I found that downgrading to 10.12.7 resolves it. Seems to have been introduced by the `queueMicrotasks()` [change in 10.12.8](https://github.com/framer/motion/blob/main/CHANGELOG.md#10128-2023-05-05).

Possibly related: https://github.com/framer/motion/issues/2110 https://github.com/framer/motion/issues/2172

**Comment by mattgperry** [comment]
Tracking here https://github.com/framer/motion/issues/2476
