### ISSUE TITLE
[FEATURE] Can we have pause on useAnimationControls?

### ISSUE THREAD

**Issue by god-of-javascript** [framer/motion#2392]
Can we have pause function on animation control to pause it and maybe resume it again?

**Comment by mattgperry** [comment]
`useAnimationControls` is deprecated in favour of `useAnimate`

**Comment by Jbmanllr** [comment]
> `useAnimationControls` is deprecated in favour of `useAnimate`

What's replacing it for variant controls?

**Comment by mattgperry** [comment]
Nothing currently. The timeline sequence syntax is a more powerful way to orchestrate when you’re using animate()
