### ISSUE TITLE
[FEATURE]how set animation speed dynamic

### ISSUE THREAD

**Issue by Aralhi** [framer/motion#2395]
**Is your feature request related to a problem? Please describe.**
when using useAnimate, how to set speed dynamic. such as slow down animation when hove on it.
i cannot search a api in `AnimationPlaybackControls` 
```
import { useAnimate } from 'framer-motion';

const [scope, animate] = useAnimate();
const controls = animate(
        scope.current,
        { x: tickerContentWidth ? tickerContentWidth * direction : 0 },
        { ease: 'linear', duration, repeat: Infinity },
      );
      controls.play();
```

Thanks a lot.

**Comment by juancarloscanoruiz** [comment]
Hey @Aralhi!

I found a way to set the animation speed. Basically what I did was using an state to save the object that we got from the `animate` function to control the animation. Then I used my state to control the animation speed using the `speed` property and set it to 0.5 (half speed) when hovering on the element. Here's the code 

```

  const [scope, animate] = useAnimate();
  const [animationControls, setAnimationControls] = React.useState<
    AnimationPlaybackControls | undefined
  >(undefined);

  React.useEffect(() => {
    if (isInView && !animationControls) {
      const controls = animate(
        scope.current,
        { x: tickerContentWidth ? tickerContentWidth * -1 : 0 },
        { ease: 'linear', duration: 10, repeat: Infinity }
      );
      controls.play();
      setAnimationControls(controls);
    }
  }, [isInView]);

  const handleMouseEnter = () => {
    if (animationControls) {
      animationControls.speed = 0.5;
    }
  };

  const handleMouseLeave = () => {
    if (animationControls) {
      animationControls.speed = 1;
    }
  };
```

Here's the full demo --> https://stackblitz.com/edit/stackblitz-starters-enojfq?file=src%2FApp.tsx

**Comment by Aralhi** [comment]
Thank you so much! it works for me.
