### ISSUE TITLE
[BUG] useTransform with {clamp: false} Not Extending Beyond Range

### ISSUE THREAD

**Issue by koljam** [framer/motion#2396]
**2. Description of the Bug**  
The `{clamp: false}` option in Framer Motion's `useTransform` is not functioning as expected. Despite setting `clamp` to `false`, the white bar does not continue to grow once the start of the element surpasses the start of the container. This behavior contradicts the [clamp option documentation](https://www.framer.com/motion/use-transform/###clamp).

**3. CodeSandbox Reproduction**  
[A minimal reproduction on CodeSandbox](https://codesandbox.io/s/scroll-forked-t9m793?file=/src/Example.tsx) demonstrates the issue.

**4. Steps to Reproduce**  
1. Visit the provided CodeSandbox link.
2. Scroll down in the preview.
3. Observe the white bar stopping its growth even though `clamp` is set to `false`.

**5. Expected Behavior**  
According to the documentation, setting `clamp` to `false` should allow the mapped output to continue even if the input falls outside the provided range. Therefore, the white bar is expected to keep growing regardless of the element's position relative to the container.

**6. Visual Evidence**  
The issue can be observed directly in the provided CodeSandbox.

**7. Environment Details**  
Further environment details can be found in the CodeSandbox setup.

**Comment by mattgperry** [comment]
It's the scroll progress that is already clamped. It doesn't extend beyond `0` or `1`. So it's the input that is clamped. I can see how this could be useful though - maybe worth putting in a feature request ticket to add this in `useScroll`.
