### ISSUE TITLE
framer-motion not working in next.js 14[BUG]

### ISSUE THREAD

**Issue by Meet2054** [framer/motion#2398]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
I am using next.js 14 and adding framer motion in it everything was working properly until the motion.div was add it started giving error  
Server Error
Error: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function

This error happened while generating the page. Any console logs will be displayed in the terminal window.
![Screenshot (52)](https://github.com/framer/motion/assets/93574181/e7cc3826-eea5-4703-b685-d98ed3e4a591)
![Screenshot (53)](https://github.com/framer/motion/assets/93574181/2c3d41c1-7603-44b7-aa64-e421a9ace328)

Give a clear and concise description of what the bug is.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

**4. Steps to reproduce**
first i next.js 14 project , add framer-motion then did npm install  imported packages but got the error then tried to reduce the version of framer-motion but no results then reduced the version of next.js to 13 but no results

**Comment by i-amWin** [comment]
If you are using server components the add "use client" at the top of component. And I hope It will fix the error.

**Comment by Captain-Leftovers** [comment]
I think you are trying to use it in a server component and thats the issue

**Comment by Mariga-M** [comment]
> If you are using server components the add "use client" at the top of component. And I hope It will fix the error.

I agree. Since the framer motion makes changes on the browser, it becomes a client component thus we add the "use client"

**Comment by yigithanyucedag** [comment]
> If you are using server components the add "use client" at the top of component. And I hope It will fix the error.

I don't think this is the right solution because there is an initial={false} prop to use in server components, but it currently causes this error. The error needs to be resolved.

**Comment by Meet2054** [comment]
Thanku everyone for giving solutions I am successful able to solve issue 
I have created this component and used in my code 
"use client";

import { motion } from "framer-motion";

export const MotionDiv = motion.div;
It is working

**Comment by mattgperry** [comment]
@yigithanyucedag `initial={false}` isn't there to make `motion` components compatible with server components as they are always going to be dynamic/client components.

**Comment by T-J-D-Cavey** [comment]
> Thanku everyone for giving solutions I am successful able to solve issue I have created this component and used in my code "use client";
> 
> import { motion } from "framer-motion";
> 
> export const MotionDiv = motion.div; It is working

@Meet2054 can you specify where you implemented 'use client' and how the exporting of MotionDiv works?

I am getting 'getStaticPaths is not a function' error when using Framer motion but don't need dynamic paths created or even getStaticProps function. So it looks like this server component and client scroll package aren't working well together...

**Comment by StasGavrilov** [comment]
Hey guys,
I facing same issue, but I trying to use the motion on next link:
`
import Link from "next/link"
import { motion } from "framer-motion"

const MotionDiv = motion(Link)

export default function Logo() {
    return (
        <div className="flex items-center justify-center mt-2">
            <MotionDiv
                href='/'
                className="w-16 h-16 bg-dark text-light flex items-center justify-center rounded-full text-2xl font-bold"
                whileHover={{ scale: 1.5 }}
            >
                SG
            </MotionDiv>
        </div>
    )
}
`
any idea why for me its failing?

**Comment by ivshiryaev** [comment]
> @yigithanyucedag `initial={false}` isn't there to make `motion` components compatible with server components as they are always going to be dynamic/client components.

Are there any solutions to use framer-motion in server components ?

**The problem:**
You cant import { motion } and use {motion} directly on <elements> inside the server component.......

**My solution**
However i made my own solution that relies on creating my own 'client' component and wrapping elements that i want to be animated in my <MotionComponent>

**example:**
'use server'
import <MyMotionComponent>
........
<MyMotionComponent>
  <div>Some text.....</div>
</MyMotionComponent

In that case everything works but .... Are there any simpler solutions?

**Comment by mattgperry** [comment]
`motion` is a client component. I haven't found a good way to publish the library with this directive but you can re-export manually:

```
"use client"
export * from "framer-motion"
```

**Comment by Neon-20** [comment]
I wonder..
I am trying to use framer-motion, what are the ways I can make this page interactive without making it "use client".

```
import UserInfo from "@/components/user-info";
import { CurrentUser } from "@/lib/auth";

const ServerPage = async() => {
    //fetch current user
    const user = await CurrentUser(); 
    return ( 
        <div className="mt-4 items-center text-center justify-center">
        <UserInfo 
        label="Server Component 🖥️"
        user = {user}
        />
        </div>
    );
}

export default ServerPage;
```

**Comment by ivshiryaev** [comment]
> I wonder..
> 
> I am trying to use framer-motion, what are the ways I can make this page interactive without making it "use client".
> 
> 
> 
> ```
> 
> import UserInfo from "@/components/user-info";
> 
> import { CurrentUser } from "@/lib/auth";
> 
> 
> 
> const ServerPage = async() => {
> 
>     //fetch current user
> 
>     const user = await CurrentUser(); 
> 
>     return ( 
> 
>         <div className="mt-4 items-center text-center justify-center">
> 
>         <UserInfo 
> 
>         label="Server Component 🖥️"
> 
>         user = {user}
> 
>         />
> 
>         </div>
> 
>     );
> 
> }
> 
> 
> 
> export default ServerPage;
> 
> ```
> 
> 

You can't obey using "use client" 

You can import and use Motion in the client client components

However, you can create custom "animation-wrapper" component, import motion to it, and add all the animations you want. This animation will receive children as a prop:


//ClientAnationWrapper
"use client"
import {motion} from "framer-motion"

function MyClientAnimationWrapper({children}.....){
return (
<motion.div>
{children}
</motion.div>
}


And later on u can use it in your server comoponent:


import MyAnimationWrapper from ...

const ServerPage() => 
<MyAnimationWrapper>
  <UserInfo>....
</MyAnimationWrapper>


The synatx is wrong because i am typing from the phone, but i think u got the idea 🙌

**Comment by Neon-20** [comment]
> > I wonder..
> > I am trying to use framer-motion, what are the ways I can make this page interactive without making it "use client".
> > ```
> > 
> > import UserInfo from "@/components/user-info";
> > 
> > import { CurrentUser } from "@/lib/auth";
> > 
> > 
> > 
> > const ServerPage = async() => {
> > 
> >     //fetch current user
> > 
> >     const user = await CurrentUser(); 
> > 
> >     return ( 
> > 
> >         <div className="mt-4 items-center text-center justify-center">
> > 
> >         <UserInfo 
> > 
> >         label="Server Component 🖥️"
> > 
> >         user = {user}
> > 
> >         />
> > 
> >         </div>
> > 
> >     );
> > 
> > }
> > 
> > 
> > 
> > export default ServerPage;
> > ```
> 
> You can't obey using "use client"
> 
> However, you can create custom "animation-wrapper" component, import motion to it, and add all the animations you want.
> 
> This animation will receive children as a prop:
> 
> //ClientAnationWrapper "use client" import {motion} from "framer-motion"
> 
> function MyClientAnimationWrapper({children}.....){ return ( <motion.div animate={{...> {children} </motion.div> }
> 
> And later on u can use it in your server comoponent:
> 
> import MyAnimationWrapper from ...
> 
> const ServerPage() => ....
> 
> The synatx is wrong because i am typing from the phone, but i think u got the idea 🙌


Ahh, I thought to use this type before, but I thought that If I render server component inside a client component as children props the server component will automatically become client component.
If that’s not the case, I will use your method.
Thanks mate 🤠

**Comment by ivshiryaev** [comment]
> > > I wonder..
> 
> > > I am trying to use framer-motion, what are the ways I can make this page interactive without making it "use client".
> 
> > > ```
> 
> > > 
> 
> > > import UserInfo from "@/components/user-info";
> 
> > > 
> 
> > > import { CurrentUser } from "@/lib/auth";
> 
> > > 
> 
> > > 
> 
> > > 
> 
> > > const ServerPage = async() => {
> 
> > > 
> 
> > >     //fetch current user
> 
> > > 
> 
> > >     const user = await CurrentUser(); 
> 
> > > 
> 
> > >     return ( 
> 
> > > 
> 
> > >         <div className="mt-4 items-center text-center justify-center">
> 
> > > 
> 
> > >         <UserInfo 
> 
> > > 
> 
> > >         label="Server Component 🖥️"
> 
> > > 
> 
> > >         user = {user}
> 
> > > 
> 
> > >         />
> 
> > > 
> 
> > >         </div>
> 
> > > 
> 
> > >     );
> 
> > > 
> 
> > > }
> 
> > > 
> 
> > > 
> 
> > > 
> 
> > > export default ServerPage;
> 
> > > ```
> 
> > 
> 
> > You can't obey using "use client"
> 
> > 
> 
> > However, you can create custom "animation-wrapper" component, import motion to it, and add all the animations you want.
> 
> > 
> 
> > This animation will receive children as a prop:
> 
> > 
> 
> > //ClientAnationWrapper "use client" import {motion} from "framer-motion"
> 
> > 
> 
> > function MyClientAnimationWrapper({children}.....){ return ( <motion.div animate={{...> {children} </motion.div> }
> 
> > 
> 
> > And later on u can use it in your server comoponent:
> 
> > 
> 
> > import MyAnimationWrapper from ...
> 
> > 
> 
> > const ServerPage() => ....
> 
> > 
> 
> > The synatx is wrong because i am typing from the phone, but i think u got the idea 🙌
> 
> 
> 
> 
> 
> Ahh, I thought to use this type before, but I thought that If I render server component inside a client component as children props the server component will automatically become client component.
> 
> If that’s not the case, I will use your method.
> 
> Thanks mate 🤠

Check this out,

https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#unsupported-pattern-importing-server-components-into-client-components

**Comment by suraj8423** [comment]
`"use-client";

import React from "react";
import { motion } from "framer-motion"

export const MotionDiv = motion.div;
const TestPage = () => {
  return (
    <div className='h-full flex items-center justify-center'>
     <motion.div className='w-96 h-96 bg-red-400 rounded'>Hello</motion.div>
    </div>
  )
}

export default TestPage`

I am facing the same issue with framer.

 "dependencies": {
    "framer-motion": "^11.0.14",
    "next": "14.1.0",
    "react": "18",
    "react-dom": "18"
  },
  "devDependencies": {
    "autoprefixer": "10.0.1",
    "eslint": "8",
    "eslint-config-next": "14.1.0",
    "postcss": "8",
    "tailwindcss": "^3.3.0"
  }
  these are the dependencies.

**Comment by Raghavj2000** [comment]
for example: 
```
 <motion.h3 initial={{ opacity: 0 }} whileInView={{ opacity: 1 }}>
            Enables Perpetual Sales Across All Channels Ensuring Seamless
            <br /> Access To Your Products Or Services At All Times
          </motion.h3>
```
this code is in my main page.js which i need it to server side rendered but also need the animation 
what happens in this case, will the h3 rendered on client or on server?

**Comment by Angular-gaseous42** [comment]
> `motion` is a client component. I haven't found a good way to publish the library with this directive but you can re-export manually:
> 
> ```
> "use client"
> export * from "framer-motion"
> ```





https://reacter.space/questions/issue-unrecognized-element-type-in-nextjs-while-starting-development-server

**Comment by levisstrauss** [comment]
Animation is a browser interaction that is why we need to add "use client" before <motion.div> can start working and don't forget to import it at the top: import {motion} from "framer-motion";

**Comment by sodhisaab** [comment]
by using "use client"; on the top of the file animation is working. But on the production when I disable the JS to check how bots/crawler will see the content it should nothing. Because the content supposed to be render on client.
