### ISSUE TITLE
[FEATURE]Small introduction to use it with page transitions, like pose had done

### ISSUE THREAD

**Issue by cctoni** [framer/motion#240]
It would be great to get some realworld examples. When it"s production ready, we would like to see some real scenarios, like page transitions in use with react router dom.

`
const AnimationSettings = {
  transition: { duration: 0.5 },
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
  exit: { opacity: 0, y: -20 },
};

const Routes = () => {
  const { location } = React.useContext(__RouterContext);

  return (
    <AnimatePresence {...AnimationSettings}>
      <Switch location={location}>
        <Route exact path="/" component={Dashboard} />

        <Route path="/board/:id" component={({ match }) => <BoardDetail boardId={match.params.id} />} />

        <Route path="/dashboard" exact component={Dashboard} />
        <Route path="/projects" exact component={Projects} />
        <Route path="/createboard" exact component={CreateBoard} />

        <Route path="/statistic/:id" component={({ match }) => <Statistic questionId={match.params.id} />} />
      </Switch>
    </AnimatePresence>
  );
};

export default Routes;
`

**Comment by InventingWithMonster** [comment]
I'll take a crack at a React Router example today

**Comment by sourcewars** [comment]
Here is a working example:

```jsx
import React from 'react';
import { Route, Switch, __RouterContext } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import CreateBoard from '../components/CreateBoard/CreateBoard';

import Dashboard from '../views/Dashboard';
import BoardDetail from '../components/BoardDetail/BoardDetail';
import Statistic from '../components/Statistic/Statistic';
import Projects from '../views/Projects';

const Routes = ({ transitionType, damping, stiffness, duration, easing }) => {
  const { location } = React.useContext(__RouterContext);

  const animation = {
    initial: { opacity: 0 },
    active: {
      opacity: 1,
      transition: {
        delay: 0.3,
        when: 'beforeChildren',
        staggerChildren: 0.1,
      },
    },
    exit: { opacity: 0, y: 200 },
  };

  const transition =
    transitionType === 'spring' ? { type: 'spring', damping, stiffness } : { type: 'tween', duration, ease: easing };

  return (
    <AnimatePresence>
      <motion.div
        key={location.key}
        initial={animation.initial}
        animate={animation.active}
        exit={animation.exit}
        transition={transition}
        //positionTransition
      >
        <Switch location={location}>
          <Route exact path="/" component={Dashboard} />

          <Route path="/board/:id" component={({ match }) => <BoardDetail boardId={match.params.id} />} />

          <Route path="/dashboard" exact component={Dashboard} />
          <Route path="/projects" exact component={Projects} />
          <Route path="/createboard" exact component={CreateBoard} />

          <Route path="/statistic/:id" component={({ match }) => <Statistic questionId={match.params.id} />} />
        </Switch>
      </motion.div>
    </AnimatePresence>
  );
};

export default Routes;

```

**Comment by BjoernRave** [comment]
An example to do the same with Next.js would be super awesome :D

**Comment by sourcewars** [comment]
I will have a look into it 🙏

**Comment by InventingWithMonster** [comment]
React Router example: https://codesandbox.io/s/framer-motion-x-react-router-n7qhp

**Comment by natemoo-re** [comment]
I'm working on a Next.js example: https://github.com/natemoo-re/next.js/tree/example-framer-motion/examples/with-framer-motion

If anyone could help with a small write-up in the README, I think it would be a great way to introduce Next.js users to Framer Motion.

cc @sourcewars @BjoernRave

**Comment by BjoernRave** [comment]
@natemoo-re so every component in the pages folder has to be wrapped with a `motion` component? Isn't there a way, where you define the animation once inside `_app.s` instead of every page?

**Comment by natemoo-re** [comment]
Nope, they don't have to be wrapped immediately with a `motion` component (and they [aren't](https://github.com/natemoo-re/next.js/blob/ebe8745508be615a46e18faabd27236faabced91/examples/with-framer-motion/components/Gallery.js#L68).) They just have to follow the [docs](https://www.framer.com/api/motion/animate-presence/#animating-custom-components) for using `AnimatePresence` with custom components. 

> The only requirement is that the first `motion` component within the custom component has an `exit` property defined.


To answer your question practically, you could just use a `motion` component directly in `_app` as long as you pass `router.route` as the `key` prop. Using Next's reccomended [`Layout`](https://github.com/zeit/next.js/tree/3f91f80ede3fc349f353e1ee6d2061e9dfd7807f/examples/with-app-layout) component pattern would be another way to set a universal transition animation.

**Comment by BjoernRave** [comment]
@natemoo-re ah okay, now I understand. Great, thanks alot for this :) Was easier than I though :D

**Comment by ryanwiemer** [comment]
Here is a very basic example with Gatsby if anyone is interested: 

https://github.com/ryanwiemer/gatsby-using-page-transitions

**Comment by mjackson** [comment]
Please use `useLocation()` instead of `useContext(__RouterContext)`. Thanks :)

**Comment by joaopaulobdac** [comment]
Note that if you choose to animate your page transitions with `AnimatePresence`, currently you won't be able to use `AnimatePresence` again inside of your pages: #746

**Comment by mattgperry** [comment]
Closing this for now as we don't really have the capacity to do guides on each router. I'm putting together a roadmap and will add the idea onto it.

**Comment by mikehuebner** [comment]
@cctoni Your solution helped me as well! Thanks! I kept trying to wrap the `motion.div` in a route and it just wasn't having it.
