### ISSUE TITLE
[BUG] inView is missing "once" option

### ISSUE THREAD

**Issue by maksymKhaiuk1989** [framer/motion#2404]
Framer motion latest version 10.16.4,  inView is missing once option. 
As per this doc https://www.framer.com/motion/in-view/ inView has once: boolean
By setting once: true, once an element is in view, inView will stop observing the element and always return true.

but here in code it is missing 

```
interface InViewOptions {
    root?: Element | Document;
    margin?: string;
    amount?: "some" | "all" | number;
}
```

and if i set once: false, it will fire only one time, so looks like this feature was removed? please pay attention i am talking about inView not useInView.

**Comment by mattgperry** [comment]
You're right, this was actually never in. I'll remove from the docs. You can call the `stop` function when `inView` first fires though and that will act the same way.
