### ISSUE TITLE
[BUG] `animate` function does not support repeat Infinity

### ISSUE THREAD

**Issue by piscopancer** [framer/motion#2408]
![image](https://github.com/framer/motion/assets/109352196/2ee0e9f7-4f3d-4363-a1ea-ebd06ac7a5ca)

```ts
const projectsAnchor = document.querySelector<HTMLAnchorElement>('a[href="#projects"]')!
const PAIconWrapper = projectsAnchor.querySelector<HTMLElement>('&>*:nth-child(1)')! // white circle
const PAIcon = PAIconWrapper.querySelector<SVGElement>('&>*:nth-child(1)')! // arrow
// init props
PAIconWrapper.style.opacity = '0%'
PAIconWrapper.style.translate = '0 5px'
animate([
  // appear from below
  [PAIconWrapper, { opacity: 1, y: 0 }],
  // arrow bouncing down (call to action)
  [PAIcon, { y: [-5, 0, 5], opacity: [0, 1, 0] }, { duration: 1, repeat: Infinity, repeatDelay: 0.5, ease: 'backInOut' }],
])
```
The problem is stat arrow only goes down once and fades away. There is not repetition of the animation :(

**Comment by mattgperry** [comment]
This isn't supported within a timeline definition. The next timeline segment occurs after the one before it by default. We couldn't calculate this if it was `repeat: Infinity`. Instead the whole animation itself needs `{ repeat: Infinity }` which probably isn't what you want here. But in lieu of that you would need to do:

```
await animate(PAIconWrapper, {})
animate(PAICON, {}, { repeat: Infinity })
```
