### ISSUE TITLE
[BUG] Reorder: scrollable list is not working

### ISSUE THREAD

**Issue by hrasoa** [framer/motion#2409]
Seems like the example for `<Reorder>` with scrollable list is not working on chrome:

https://www.framer.com/motion/reorder/##scrollable-lists

**Environment details**

macOs Sonoma
Chrome Version 119.0.6045.159 (Official Build) (x86_64)

**Comment by notmedia** [comment]
same

**Comment by hrasoa** [comment]
Closing
