### ISSUE TITLE
[BUG] `scrollY` of `useScroll` returns page offset, not element's

### ISSUE THREAD

**Issue by piscopancer** [framer/motion#2410]
The history section is situated about 10 scrolls to reach, however `useScroll` does not seem to care very much, it always outputs current page scroll progress in pixels

```ts
const historySection = useRef<HTMLElement>(null)
const { scrollY: historyScrollPx } = useScroll({ target: historySection, offset: ['0 1', '1 1'] })

useEffect(() => {
  historyScrollPx.on('change', (v) => console.log(v)) // for each scroll from the top of the page, the value grows by 100
}, [])
```

So my question is, how do I get the pixels offset of a particular element? I do not need to use progress (0-1) in my case because I do not know in advance the height of the element and I want to use pixels to make animation persistent and predictable uhuh 😉

**Comment by mattgperry** [comment]
This should be fixed in latest

**Comment by mattgperry** [comment]
The

**Comment by mattgperry** [comment]
Gonna file this one under https://github.com/framer/motion/issues/2189
