### ISSUE TITLE
Animating a color to alpha=0 leads to an error

### ISSUE THREAD

**Issue by tjahn** [framer/motion#244]
**Describe the bug**
When moving the mouse FAST over this animation, the animated alpha value becomes negative when the hovering ends.

`<motion.div style={{ border: "solid", borderColor:"rgba(0,0,0,0)" }} whileHover={{ borderColor:"rgba(0,0,0,1)" }} > Test </div>`

The result is the following error: Uncaught (in promise) Error: Complex values 'rgba(1, 0, 0, -0.00038)' and 'rgba(1, 0, 0, 0)' too different to mix. Ensure all colors are of the same type. 

**To Reproduce**
Past the animation above into an react app.

**Expected behavior**
The border should become visible while hovering and invisible again after endHover.
The error-message should not tell me about different color types.

**Desktop:**
 - MacOS
 - Google Chrome 75
 - 1.2.1

**Comment by InventingWithMonster** [comment]
A couple of oddities here:

1. The value should be recognised as a color type rather than a complex type (which is why alpha was allowed to end up in the negative). 
2. `rgba(1, 0, 0, -0.00038)` and `rgba(1, 0, 0, 0)` shouldn't be considered too different to mix.

**Comment by InventingWithMonster** [comment]
Ah it's because it's a negative that it's not being detected as a color which leads to both bugs. Will need to check out how it ever gets there.
