### ISSUE TITLE
[BUG] Reorder.Item animates back into place despite turning animation off completely

### ISSUE THREAD

**Issue by IroncladDev** [framer/motion#2451]
**1. Read the [FAQs](#faqs) 👇**

✅ I have read the FAQs

**2. Describe the bug**

When I disable animation on the `Reorder.Item` component by wrapping it with `<MotionConfig reducedMotion="always">` or setting the `transition` property to `{ duration: 0, ease: "linear" }`, the reorder item still animates when I release my pointer / finish dragging.

An item that is not being dragged does not animate as expected.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/p/sandbox/framer-motion-5-drag-to-reorder-lists-forked-cspd3j

**4. Steps to reproduce**

1. In the codesandbox repro, drag an item
2. Notice that the items that are **not** being dragged are not animated, as expected
3. Release the item you're dragging
4. Notice how it slowly animates into its new position regardless of the transition/reduced motion settings

**5. Expected behavior**

When you release the current item you're dragging, it should drop into place instantly instead of slowly animate to its new position when reduced Motion or transitions are set to turn animations off.

**6. Video or screenshots**

A video of my app

https://github.com/framer/motion/assets/50180265/f16a62e8-8612-4a30-a3be-3e41650f2901

And a video of the reproduction

https://github.com/framer/motion/assets/50180265/ea15a796-ae6d-4111-855b-fa787600bd25

**7. Environment details**
- OS: MacOS
- Browser: Google Chrome
- Browser Version: 119.0.6045.123 (Official Build) (arm64)

**Comment by mattgperry** [comment]
I think it's unlikely this will be fixed "officially" but this animation is controlled by `dragTransition` which is always a spring. So you can get close to instant by adding

```
dragTransition={{ bounceStiffness: 2000, bounceDamping: 10000 }}
```

**Comment by IroncladDev** [comment]
Thank you!
