### ISSUE TITLE
[FEATURE] Add the ability to sequence layout transition SIZE then POSITION (or vice versa) 

### ISSUE THREAD

**Issue by Galante97** [framer/motion#2455]
For Layout animations I would love the ability to sequence layout animation **size**, then **postion** (or vice versa), rather than doing them at the same time. As it currently stands when setting Layout to true, it will run both of those animations at the same time. Or we have the option to set layout="position | size" which then sets one of those to animate instantly, but this isn't always desired either. 

**Where this can come in handy:**
I have a vertical list that I want to animate when new data comes in and it gets resorted. The problem is, when the data is updated, sometimes the individual items content will change in height.  When the size and position of an item change, it can cause an undesirable stretching or compressing of the content.
```<>
{sortedList.map((item, index) => {
    return (
      <motion.div
        layout
        key={item.id}
        transition={{
          type: 'spring',
        }}
      >
        {/** CONTENT */}
      </motion.div>
    );
  })}
  </>
```
On the [layout animation documentation](https://www.framer.com/motion/layout-animations/###the-content-stretches-undesirably) it says you should set `layout="position | size"`, however I noticed this can cause glitchy animations where list items overlap each other. 

One potential solution I see is in the `transition` object allow us to individually animate layout position and size, for instance currently we can do this:
```
 <motion.div
        layout
        key={item.id}
        transition={{
          type: 'spring',
          layout: { delay: 1 } // this effects both position and size
        }}
      >
```
What I'm proposing is break up ` layout: { delay: 1 } ` into two pieces, `size` and `position`: 
```
 <motion.div
        layout
        key={item.id}
        transition={{
          type: 'spring',
          size: { delay: 0 },
          position: { delay: 1 }
        }}
      >
```
In the scenario above, size transition would happen first, and position would trigger 1 second later. This would allow us to sequence the two types of layout animations. 

If theres anyway to achieve this now without code changes, please let me know. Otherwise I'm open to discussing this more, or other implementations that might be more straightforward. Thanks.

**Comment by mattgperry** [comment]
Closing this as a `wontfix` - I appreciate why this would be cool but realistically I won't have time to look at this one. The way `layout="position"` etc is a little hacky and this is related to why it's a little involved to animate position and size separately.
