### ISSUE TITLE
[FEATURE] Wait to measure layout if component renders on a queue

### ISSUE THREAD

**Issue by davidisaaclee** [framer/motion#2456]
**Is your feature request related to a problem? Please describe.**
When using `AnimatePresence` with an Ionic component, entering layout animations do not get tweened – the elements just jump to their target layout.

I'm using Stencil components (by way of Ionic) with Motion. These components are set up by Ionic to render on a task queue (via `requestAnimationFrame`). When such an element starts an enter animation inside `AnimatePresence`, Motion tries to measure the layout of the element – [the initial render is queued](https://github.com/ionic-team/stencil/blob/a69b4d619ebf4f65f54e7ad35c24b28f2416d9c8/src/runtime/update-component.ts#L32), so it gets an empty layout box, and the tweening fails.

Repro: https://codesandbox.io/p/sandbox/thirsty-lederberg-vhz95n?file=%2Fpackage.json%3A16%2C1-20%2C1

**Describe the solution you'd like**
For me, it'd be sufficient to have a flag on `AnimatePresence` that, when enabled, checks layout after a `requestAnimationFrame` – if I know that the child is a queued render, then I'll enable the flag.

**Describe alternatives you've considered**
More flexible solution would be to have a way to tell Motion when the element is ready to be measured (in case it is not equal to one rAF). I thought that `layoutDependency` would work like that, but I wasn't successful: https://codesandbox.io/p/sandbox/adoring-kowalevski-dzzlvs?file=%2Fsrc%2FApp.tsx%3A37%2C10 – I haven't used `layoutDependency` before, so this might be coding error. (It seems like `layoutDependency` can incur additional layouts, but can't _defer_ a layout?)

**Additional context**
<video src="https://github.com/framer/motion/assets/1924620/5c808889-f229-461a-9def-82089af63259" />

Stencil can be configured to disable the task queue, but this supposedly causes other performance issues (and I think would require a fork of Ionic), so I'd like to avoid it.

Related to https://github.com/framer/motion/issues/1345, but that one is about an application-level logic of when to present, this one is just waiting for the child to actually render (idk, feels different to me!)

**Comment by davidisaaclee** [comment]
fwiw, adding the following patch makes my specific use case work (although it probably adds unnecessary latency to most use cases): 

```diff
diff --git a/packages/framer-motion/src/projection/node/create-projection-node.ts b/packages/framer-motion/src/projection/node/create-projection-node.ts
index 8d4eda74..28cddf8a 100644
--- a/packages/framer-motion/src/projection/node/create-projection-node.ts
+++ b/packages/framer-motion/src/projection/node/create-projection-node.ts
@@ -657,7 +657,7 @@ export function createProjectionNode<I>({
         didUpdate() {
             if (!this.updateScheduled) {
                 this.updateScheduled = true
-                queueMicrotask(() => this.update())
+                requestAnimationFrame(() => this.update())
             }
         }
```

**Comment by mattgperry** [comment]
Setting as `wontfix`. The problem with `requestAnimationFrame` is in the general case we'll see a flash of the target layout before we animate to it. Everything about layout animations is based on the fundamental assumption that this blocks rendering so it'd be unrealistic for me to say I'd look into this any time soon.
