### ISSUE TITLE
Animation not working on chrome browser

### ISSUE THREAD

**Issue by sercamembert** [framer/motion#2460]
Describe the bug
My animation is working good on chrome/safari but not working on chrome.

Provide a CodeSandbox reproduction of the bug
https://codesandbox.io/p/sandbox/framer-bug-pjpncf

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.
![image](https://github.com/framer/motion/assets/69466055/4db00a73-bdb8-43e5-ba6d-5facb71a252c)

**Comment by mattgperry** [comment]
`IntersectionObserver` doesn't work with SVG elements. Your best bet is to change `strokeDashoffset` to `pathOffset` and instead of using objects, adding variants to a wrapper.


```jsx
<motion.div initial="initial" whileInView="line">
  <motion.path variants={{ initial: {}, line: {} }} />
</motion.div>
```
