### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ChadrackTBD** [framer/motion#2484]
Is it possible to track the scrollYPosition of two elements on the same page ?

**Comment by mattgperry** [comment]
Yes - you make two `useScroll()` hooks and pass each a different `container` argument.

**Comment by ChadrackTBD** [comment]
> Yes - you make two `useScroll()` hooks and pass each a different `container` argument.

For instance i have this 

 const boxRef = useRef(null);
  const { scrollYProgress } = useScroll({
    target: boxRef,
    offset: ["0 1", "1.33 1"],
  });
  const scaleProgress = useTransform(scrollYProgress, [0, 1], [0.8, 1]);

and i want to do the same thing for a other div, how to do it ? 
Thanks
