### ISSUE TITLE
Handling two offset on one page

### ISSUE THREAD

**Issue by ChadrackTBD** [framer/motion#2486]
Hello
I would like to handle two different offset by using useScroll() hooks 
for exemple 

` const mainRef = useRef(null);
  const { scrollYProgress } = useScroll({
    target: mainRef,
    offset: ["0 1", "1 0"],
  });
  const scale = useTransform(scrollYProgress, [0, 1], [0.8, 1]);`

on the same page i need to track the position of an other div like 
` const ref = useRef(null);
  const { scrollYProgress } = useScroll({
    target: ref,
    offset: ["1 0", "0 1"],
  });
  const width = useTransform(scrollYProgress, [0, 1], [0.8, 1]);`

i  get errors every time 
how to use two useScroll on the same page ?

**Comment by mattgperry** [comment]
Can you reopen with a sandbox example and an explanation of errors that you see?
