### ISSUE TITLE
[BUG] Framer Motion maskSize animation doesn't work in mobile phone.

### ISSUE THREAD

**Issue by AlexAdvent** [framer/motion#2489]
I have created a simple SVG mask scroll in Framer Motion. Here is the link to the sandbox: https://codesandbox.io/p/sandbox/svg-nextjs-masking-vgnhnd. While this masking works fine on a PC, it's not functioning on a mobile phone. The size of the mask is not increasing on a mobile phone. Does anyone have an idea on how to solve this issue? I've seen sites where this SVG scroll masking works on mobile phones as well.

Here is the deployed version - https://svg-clip-mask-scroll.vercel.app/ you can see that the mobile scroll mask not working.

Here is the link to the sandbox: https://codesandbox.io/p/sandbox/svg-nextjs-masking-vgnhnd.

The output on a mobile phone shows that the mask size doesn't increase. I've tried different phones, but the same issue occurs. Do you have any possible solutions how to solve this bug?

**Comment by mattgperry** [comment]
It's working for me on iOS. I'm closing as a `wontfix` as it's currently not reproducable for me but could you reopen after first confirming that changing the CSS directly yourself and animating it via `transition` does work on mobile. As I think this is a problem specific to that browser.
