### ISSUE TITLE
[BUG] - Framer motion minor package bump broke animation rotate.

### ISSUE THREAD

**Issue by Saveljeffjonatan** [framer/motion#2512]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

I have a very simple motion.div that creates a loading spinner.
After updating to 10.18.0 the animation stopped. I lately tried to update to 11.0.3 and same result but if I revert to 10.16.4 it works again.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[CodeSandBox](https://codesandbox.io/p/sandbox/framer-dkzdlk?file=%2Fpackage.json%3A11%2C32&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsd9rw4900062e678vtmag6n%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsd9rw4800022e67vemtzb8b%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsd9rw4800032e67e0gjyxb2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsd9rw4900052e67mknoh370%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsd9rw4800022e67vemtzb8b%2522%253A%257B%2522id%2522%253A%2522clsd9rw4800022e67vemtzb8b%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsd9vm4g00022e67k3lrwjlb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A32%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A32%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsd9vm4g00022e67k3lrwjlb%2522%257D%252C%2522clsd9rw4900052e67mknoh370%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsd9rw4900042e67a9w38eql%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsd9rw4900052e67mknoh370%2522%252C%2522activeTabId%2522%253A%2522clsd9rw4900042e67a9w38eql%2522%257D%252C%2522clsd9rw4800032e67e0gjyxb2%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsd9rw4800032e67e0gjyxb2%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**4. Steps to reproduce**

# NOTE:
- 10.17.5 This seems to be the first version that the bug happens on!

1. Go to the link
2. Update package.lock - Framer to version 10.18.0 (or any later up to and including 11.0.3)
3. Reload the page
4. Now the spinner in the box should have stopped. *This is an error and is not expected.

**5. Expected behavior**

Bumping version of Framer should not interfere with the logic to have the spinner move. (There was no major release if you go from 10.14.6 -> 10.18.0).

**Comment by mattgperry** [comment]
`repeat: "loop"` should be `repeat: Infinity`
