### ISSUE TITLE
[DOCUMENTATION] Outdated Note in Scroll Triggered Animations section

### ISSUE THREAD

**Issue by JaeGif** [framer/motion#2513]
Docs section: [https://www.framer.com/motion/scroll-animations/#scroll-triggered-animations](https://www.framer.com/motion/scroll-animations/#scroll-triggered-animations)

The note at the bottom of the section is outdated. The issue it is referring to was resolved in chromium on Nov 29th 2023.
[chromium issue log](https://issues.chromium.org/issues/40627467).

Recommend removing the note from the docs. Referring to the note in the screenshot below.

<img width="794" alt="Screenshot 2024-02-10 at 10 40 58 AM" src="https://github.com/framer/motion/assets/105343665/68e977de-b55d-456e-b4e2-70f1476fed67">

**Comment by mattgperry** [comment]
Thanks! Will change
