### ISSUE TITLE
[BUG] AnimatePresence with React Router V6

### ISSUE THREAD

**Issue by SinGlEBW** [framer/motion#2540]
1. When creating a slide on the React router dom, I periodically receive premature deletion of the outgoing (exit) component.
2. If you wrap AnimatePresence in a component, you will get an incorrect behavior of the slide direction.
3. After the animation is completed, it can work again.

https://codesandbox.io/p/sandbox/slidereactroutev6-7dlfvw?file=%2Fsrc%2Fcomponents%2FPageSlideAnnimation.tsx%3A50%2C65

   "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "framer-motion": "^11.0.3",

**Comment by Sean-Wilson-Braille** [comment]
The codesandbox is not found

**Comment by mattgperry** [comment]
Closing as sandbox is not found. Can you give `11.3.18-alpha.0` a go and if your issue persists, open a new issue with a public sandbox?
