### ISSUE TITLE
[BUG] Height no longer animating with 'auto' specified within AnimatePresence after 11.0.10

### ISSUE THREAD

**Issue by SolidAnonDev** [framer/motion#2549]
**2. Describe the bug**

After 11.0.10, it appears I can no longer animate height to 'auto' using 'height: 'auto'' when coming from 0 when nesting a `motion.div` in `<AnimatePresence>`

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[CodeSandbox Reproduction](https://codesandbox.io/p/sandbox/purple-grass-zhr6lf?file=%2Fsrc%2FApp.tsx)

For a quick look, here's what the general code pattern looks like that I was using:

```
<AnimatePresence>
        {open && (
          <motion.div
            style={{ backgroundColor: "blue" }}
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            key="test"
          >
            <h1>Hello</h1>
          </motion.div>
        )}
</AnimatePresence>
```

**4. Steps to reproduce**

When the codesandbox open, `framer-motion` will be set to `latest` in package.json

1. In this config, you can click the 'open' button in the react app and note that the height is not animated.

2. **Change the framer motion version to 11.0.8 in the sandbox and reload**
3. Click the Open button again and you will see that the height is animated

**5. Expected behavior**

The height will be animated when using property `auto` for `height` in a `motion.div` that is nested in `AnimatePresence`

Note that something like this would work:

```<motion.div animate={{ height: open ? 'auto' : 0 }}>...</motion.div>```

Or explicitly setting the height to a value appears to work too, but my code had relied on `auto`, and not hardcoding the height. It was working well until `11.0.10` it appears

**Comment by mattgperry** [comment]
Thanks for the report, will take a look!
