### ISSUE TITLE
[BUG] Cannot destructure property 'animation' of 'this.resolved' as it is undefined

### ISSUE THREAD

**Issue by simPod** [framer/motion#2553]
Getting

> Cannot destructure property 'animation' of 'this.resolved' as it is undefined

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

**4. Steps to reproduce**

v11.0.12

![image](https://github.com/framer/motion/assets/327717/a331e29b-5ed3-484e-bb46-8cacf80364e3)

**5. Expected behavior**

No issue.

**7. Environment details**

v11.0.8 had no issue

**Comment by andylacko** [comment]
thx @simPod , for pointing out the working version, didn't have to try downgrading myself

**Comment by michaelcais** [comment]
I had the same error, but was able to resolve it by checking on the values I assigned to my animations. In my case, I had the following;
```
<motion.div
initial={{ y: '-10' }} 
animate={{ y: 0 }} 
transition={{ 
  duration: 0.15,
  type: 'spring',
  stiffness: 120,
  ease: 'easeInOut'
}}
>
```
            
  This used to work on earlier versions, but with the latest version, I had to remove the enclosed quotes for  `initial={{ y: -10 }}`

**Comment by Johnrobmiller** [comment]
> I had the same error, but was able to resolve it by checking on the values I assigned to my animations. In my case, I had the following;
> 
> ```
> <motion.div
> initial={{ y: '-10' }} 
> animate={{ y: 0 }} 
> transition={{ 
>   duration: 0.15,
>   type: 'spring',
>   stiffness: 120,
>   ease: 'easeInOut'
> }}
> >
> ```
> 
> This used to work on earlier versions, but with the latest version, I had to remove the enclosed quotes for `initial={{ y: -10 }}`

I also ran into this issue, although this fix did not work for me as none of the props were wrapped in enclosing quotes.

**Comment by michaelcais** [comment]
I apologize, the error is indeed still there when navigating to the page. Refreshing the browser on the same page however, did not trigger the error so I thought it got fixed when I was working on another error regarding `errors.mjs:8 You are trying to animate y from "-10" to "0". -10 is not an animatable value` previously.

**Comment by mattgperry** [comment]
Please open a ticket with a  sandbox demonstrating the bug

**Comment by simPod** [comment]
This may be fixed in .14 https://github.com/framer/motion/compare/v11.0.13...v11.0.14

I'll try to deploy it.
