### ISSUE TITLE
[BUG] AnimatePresence gets stuck when state changes quickly 

### ISSUE THREAD

**Issue by tommhuth** [framer/motion#2554]
**2. Describe the bug**
Framer Motion `v11.0.12`: When state changes very quickly `AnimatePresence` gets stuck and out of sync and no longer removes the element but instead always animates it in. Reverting  to version `v10.12.2` (based of other bug report concerning a similar/same issue) does not exhibit the same problem

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
[https://codesandbox.io/p/sandbox/serene-brattain-qwd278](https://codesandbox.io/p/sandbox/serene-brattain-qwd278)

**4. Steps to reproduce** 

1. Conditionally render an element inside AnimatePresence with an exit animation
2. Trigger condition change quickly
3. Animating component gets stuck as rendered, and any changes to the condition will just trigger an reset from initial => animate. The component is no stuck as visible and will never leave the DOM. 

**5. Expected behavior**

The component should not get stuck as mounted

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

**7. Environment details**

Chrome 122, Mac Sonoma

**Comment by justrealmilk** [comment]
Your code sandbox is broken

**Comment by Roon311** [comment]
I am encountering the same issue

**Comment by mattgperry** [comment]
Thanks for the sandbox - are you able to set it to public so I can take a look?

**Comment by Roon311** [comment]
https://codesandbox.io/p/github/Roon311/trying/master?workspaceId=e4d7df23-6eed-436c-861f-b723f62062f5

**Comment by Roon311** [comment]
@mattgperry When you use the right arrown to navigate through the animating images, the error shows up

**Comment by notmedia** [comment]
@Roon311 you link is also unavailable 
```
Unable to access this workspace
It is likely that you are not a member of the team that this project belongs to. To be able to access the web editor of this repository and edit the code, you need to be invited to the team.
```

**Comment by justrealmilk** [comment]
Okay now that I know why it breaks I can actually trigger the problem https://codesandbox.io/p/sandbox/modern-wood-h35hc6

**Comment by Roon311** [comment]
@notmedia is it still inaccessible ?

**Comment by OlegWock** [comment]
Here is another reproduction. Double click the button to see it

https://stackblitz.com/edit/hold-to-confirm-framer-motion-fj53pr?file=package.json

I can confirm that framer motion 11.0.8 works correctly with same code

**Comment by tommhuth** [comment]
sorry about that, https://codesandbox.io/p/sandbox/serene-brattain-qwd278 is now public

**Comment by eryilmazyasin** [comment]
I have the same problem and still could not find the solution. Here is my example. 

<AnimatePresence>
                    {open && (
                        <motion.div
                            key="contentMarkContainer"
                            initial={{ opacity: 0, position: 'absolute', bottom: 0, left: 0, right: 0 }}
                            animate={{ opacity: 1 }}
                            exit={{ opacity: 0, transition: { ease: 'easeOut', duration: 0.75 } }}
                        >
                            {My codes here...}
                         </motion.div>
                         )}
                        </AnimatePresence>

https://github.com/framer/motion/assets/40694757/2d020827-8537-466c-a1eb-6bd3414be27f

**Comment by iravid** [comment]
This appears to have been broken in `11.0.11`. Last version that doesn't suffer from this issue is `11.0.10`.

**Comment by ConsoleTVs** [comment]
> This appears to have been broken in `11.0.11`. Last version that doesn't suffer from this issue is `11.0.10`.

Correct. Just checked!

**Comment by federicocappellotto97** [comment]
Same here, using `"framer-motion": "^11.0.25"`

**Comment by HHogg** [comment]
Just linking for reference as I was linked to Issue #2023 first. We're also seeing this on `11.0.24`.

**Comment by Roon311** [comment]
Reverting to version v10.12.2 solved worked for me.

**Comment by 6thpath** [comment]
> @pklada Reverting to version v10.12.2 solved worked for me.

v10.12.2 does not work for me, 11.0.10 does

**Comment by pklada** [comment]
I'd prefer not to revert if possible as we're relying on some more recent fixes. Would be nice if there was some update on this specific issue as it seems like it is affecting a number of others

**Comment by pklada** [comment]
@mattgperry do you have any thoughts or should i just downgrade for now?

**Comment by luluxia** [comment]
I have the same issue.
https://codesandbox.io/p/devbox/great-brattain-hc9kgz
but i found using non-repeating `key` can solve it.

**Comment by kangju2000** [comment]
Same here. (v11.1.3)
https://stackblitz.com/edit/vitejs-vite-6vewix?file=src%2FApp.tsx

**Comment by VrTech** [comment]
> I have the same issue. https://codesandbox.io/p/devbox/great-brattain-hc9kgz but i found using non-repeating `key` can solve it.

Good find!
Using count can hot fix this for now
`  const [count, setCount] = useState(0);`

**Comment by Thanaen** [comment]
> I have the same issue. https://codesandbox.io/p/devbox/great-brattain-hc9kgz but i found using non-repeating `key` can solve it.

I can reproduce the bug in this codesandbox, just click quickly enough
![framer-bug](https://github.com/framer/motion/assets/16762369/c2a1801b-d1b8-4dca-9942-ecb8b5132271)

**Comment by luluxia** [comment]
> > I have the same issue. https://codesandbox.io/p/devbox/great-brattain-hc9kgz but i found using non-repeating `key` can solve it.
> 
> I can reproduce the bug in this codesandbox, just click quickly enough

change the `key` attribute in line 21 will fix it. I wrote a comment there.

**Comment by Thanaen** [comment]
@luluxia Ouuups, I thought the sandbox applied the fix, sorry! 😄

**Comment by VrTech** [comment]
@luluxia However, I found out the solution is not working with staggering children. :(

**Comment by Thanaen** [comment]
@RareSecond This seems to solve the problem of "deleting" the object, but there's still something wrong with it
With opacity:
![framer-presence-issue](https://github.com/framer/motion/assets/16762369/d4397402-bc5a-42a2-9b7b-9ed0e8a49abb)
Without opacity:
![framer-bug-bis](https://github.com/framer/motion/assets/16762369/827924a5-b82f-4f84-81bb-a1b1f9c21257)

**Comment by beefchimi** [comment]
Just chiming in to say - I am running into the same issue, and have found that avoiding `opacity` can get around the problem. A little more context here: https://github.com/framer/motion/issues/2618#issuecomment-2085488130

**Comment by quentinlagache** [comment]
> This appears to have been broken in `11.0.11`. Last version that doesn't suffer from this issue is `11.0.10`.

[Compare v11.0.10 ➡️ v11.0.11](https://github.com/framer/motion/compare/v11.0.10...v11.0.11)

**Comment by J4v4Scr1pt** [comment]
Same Issue:
https://github.com/framer/motion/issues/2693

**Comment by harrisonhoward** [comment]
I'm using `11.0.25` and experiencing similar issues with cancelling the exit animation part-way through. This is the recording of it using [Loom](https://www.loom.com/share/d3f86ec5efcc4bef90833adaab64ae62). Notifiable from the video, it flickers with no component rendered and if you spam it quick enough the project you were looking at disappears, when you go to any other project it will only show the hidden project.

`11.0.10` doesn't fix the flickering issue but resolves everything else. I will link the code below.

This is the Projects route component [Projects.tsx](https://github.com/harrisonhoward/harrison-portfolio/blob/feature/update-projects-page-on-click-feature-with-dedicate-project-view-instead/src/routes/Projects.tsx#L72)\
This is the card component that holds the ribbons animation (still working on it) [ProjectCards.tsx](https://github.com/harrisonhoward/harrison-portfolio/blob/feature/update-projects-page-on-click-feature-with-dedicate-project-view-instead/src/features/Projects/ProjectCard.tsx#L68)

To get the exit and entrance animations to work I have all projects rendered. For any project not selected it just returns null in the map, couldn't think of another way of doing it.

**Comment by harrisonhoward** [comment]
To follow-up, this code seemed to have to fix it sort of on the latest version. It only flickers if you return back to the same project while it's exiting to the new one.

[useDebouncedValue](https://usehooks-ts.com/react-hook/use-debounce-value)
```tsx
    const [selectedProject, setSelectedProject] = useDebounceValue(
        () => getProjectByYearAndIndex(activeYear, activeProjectIndex),
        250
    );
    useEffect(() => {
        const newProject = getProjectByYearAndIndex(
            activeYear,
            activeProjectIndex
        );
        if (selectedProject?.id !== newProject?.id) {
            setSelectedProject(newProject);
        }
    }, [activeYear, activeProjectIndex]);
```

**Comment by LeonLiu2020** [comment]
> > @pklada Reverting to version v10.12.2 solved worked for me.
> 
> `10.12.2` does not work for me, `11.0.10` does

thanks，11.0.10 works for me.
After two days of repeated debugging, none of the methods mentioned in the other issues worked, only downgrading the version was effective. This bug has been around for several years, it is unbelievable for such a large open-source project.

**Comment by GunnerCat** [comment]
> > > @pklada Reverting to version v10.12.2 solved worked for me.
> > 
> > 
> > `10.12.2` does not work for me, `11.0.10` does
> 
> thanks，11.0.10 works for me. After two days of repeated debugging, none of the methods mentioned in the other issues worked Only downgrading the version was effective. This bug has been around for several years since version 9.x?
> 
> Here are two links. The code is the same except for the version of framer-motion. 11.2.12： https://codesandbox.io/p/devbox/framer-motion-11-2-12-s2rwgt 11.0.10：https://codesandbox.io/p/devbox/framer-motion-11-0-10-6f43vg
> 
>  framer-motion11.2.12.mp4 
> 11.2.12
> 
>  framer-motion11.0.10.mp4 
> 11.0.10 works

did the same thing, can approove that it worked 👍

**Comment by GunnerCat** [comment]
> > > > @pklada Reverting to version v10.12.2 solved worked for me.
> > > 
> > > 
> > > `10.12.2` does not work for me, `11.0.10` does
> > 
> > 
> > thanks，11.0.10 works for me. After two days of repeated debugging, none of the methods mentioned in the other issues worked Only downgrading the version was effective. This bug has been around for several years since version 9.x?
> > Here are two links. The code is the same except for the version of framer-motion. 11.2.12： https://codesandbox.io/p/devbox/framer-motion-11-2-12-s2rwgt 11.0.10：https://codesandbox.io/p/devbox/framer-motion-11-0-10-6f43vg
> > framer-motion11.2.12.mp4
> > 11.2.12
> > framer-motion11.0.10.mp4
> > 11.0.10 works
> 
> did the same thing, can approove that it worked 👍

but when i do the same thing on my laptop, changes the version and all, it still breaks (only on my laptop). weird

**Comment by ConsoleTVs** [comment]
We found out that the opacity sometimes didn't work. We relied a lot in this library and are beginning to strip down bits of it due this bug.

**Comment by LeonLiu2020** [comment]
@ConsoleTVs   @GunnerCat 
After a few days of trying, I resolved all issues using version 11.2.12, including opacity and blur. Could you provide a CodeSandbox link so I can see if I can help?

**Comment by justrealmilk** [comment]
> > > @pklada Reverting to version v10.12.2 solved worked for me.
> > 
> > 
> > `10.12.2` does not work for me, `11.0.10` does
> 
> thanks，11.0.10 works for me. After two days of repeated debugging, none of the methods mentioned in the other issues worked Only downgrading the version was effective. This bug has been around for several years since version 9.x?
> 
> Here are two links. The code is the same except for the version of framer-motion. 11.2.12： https://codesandbox.io/p/devbox/framer-motion-11-2-12-s2rwgt 11.0.10：https://codesandbox.io/p/devbox/framer-motion-11-0-10-6f43vg
> 
>  framer-motion11.2.12.mp4 
> 11.2.12
> 
>  framer-motion11.0.10.mp4 
> 11.0.10 works

@LeonLiu2020

**Comment by pklada** [comment]
This is now the most commented on and "liked" issue (even more if you count the duplicates). Would be cool to at least get a comment on if its being looked into.

**Comment by GunnerCat** [comment]
> @ConsoleTVs @GunnerCat After a few days of trying, I resolved all issues using version 11.2.12, including opacity and blur. Could you provide a CodeSandbox link so I can see if I can help?

sorry for the late respond, [This is my code](https://codesandbox.io/p/sandbox/testing-animationpresence-ft94d3?file=%2Fsrc%2FApp.js%3A156%2C15), for some odd reason, this is the same exact code that im using the whole time, the CodeSandBox also uses 11.3.2 framer motion version, and for some UNGODLY REASON IT WORKS.

so at your code, does including opacity and blur fixes the problem?

**Comment by WinnieS0728** [comment]
```json
"framer-motion": "^11.2.11",
"macOS":"14.4.1"
```
I have same issue here, but I solve it in a silly way.

### add `Math.random()` in key

```jsx
<AnimatePresence initial={false} mode="popLayout" custom={direction}>
    <motion.section
        key={`${id}-${Math.random()}`}
        className="w-full h-100 relative cursor-pointer"
        style={{
            perspective: '1400px',
        }}
        onClick={() => {
            setIsFlipped((prev) => !prev);
        }}
        variants={sectionMotion}
        custom={direction}
        initial="init"
        animate={['enter', 'show']}
        exit={['exit', 'hide']}
        transition={{
            type: 'tween',
            duration: 0.2,
        }}
    >
        <MotionCard text={back} show={!isFlipped} />
        <MotionCard text={front} show={isFlipped} />
    </motion.section>
</AnimatePresence>;
```
I think is the exit props hold this component from unmount but in react this component mount again, so now framer-motion read two component having same key, somehow break the view.

if there is any better solution ?

**Comment by LeonLiu2020** [comment]
> sorry for the late respond, [This is my code](https://codesandbox.io/p/sandbox/testing-animationpresence-ft94d3?file=%2Fsrc%2FApp.js%3A156%2C15), for some odd reason, this is the same exact code that im using the whole time, the CodeSandBox also uses 11.3.2 framer motion version, and for some UNGODLY REASON IT WORKS.
> 
> so at your code, does including opacity and blur fixes the problem?

Sandbox not found.
And in the latest version of framer-motion, I can use opacity and blurs normally,  perform well regardless of how quickly the components refresh. I will upload a new example later.

**Comment by tnfAngel** [comment]
Any updates here? I have the same problem

**Comment by Flamenate** [comment]
> > sorry for the late respond, [This is my code](https://codesandbox.io/p/sandbox/testing-animationpresence-ft94d3?file=%2Fsrc%2FApp.js%3A156%2C15), for some odd reason, this is the same exact code that im using the whole time, the CodeSandBox also uses 11.3.2 framer motion version, and for some UNGODLY REASON IT WORKS.
> > so at your code, does including opacity and blur fixes the problem?
> 
> Sandbox not found. And in the latest version of framer-motion, I can use opacity and blurs normally, perform well regardless of how quickly the components refresh. I will upload a new example later.

I'm also using the latest version (11.3.4) but the opacity issue persists even when I specify a key. Can you upload the example you're using?

**Comment by Flamenate** [comment]
> @tnfAngel @Flamenate
> 
> [AnimatePresence works by detecting when Direct Child are removed from the React tree.](https://www.framer.com/motion/animate-presence/#usage)
> 
> base on framer-motion 11.3.4. when used in conjunction with radix-primitive, the same usage behaves inconsistently across different Radix-primitives components. For radix-primitive components that use the asChild prop, **sometimes they can be used directly as child nodes, and other times they cannot.**
> 
> Placing a motion.div as a direct child at the appropriate position can solve the problem for most cases.
> 
> Below are examples using radix-accordion, radix-context-menu, and radix-tooltip. link: https://codesandbox.io/p/devbox/framer-motion-11-3-4-34sjjk
> 
> video:
> 
>  11.3.4.mp4 
> These are some methods I have tried, which have solved all the issues I encountered:
> 
> 1. Elevate or lower the wrapping scope. Searching on Google for the usage of framer-motion with radix-primitives may reveal incorrect states during fast refresh.
> 2. Add a fixed key. Dynamic keys did not help me , even lost the exit animation  in a test
> 3. Add a motion.div at the outermost layer without adding a key. This is effective and has resolved most of my radix-primitive exit animation issues.
> 
> I am not sure about your use case, but if this does not help you, please create a sandbox link.

This was very helpful, thanks!

**Comment by Flamenate** [comment]
> I have the same issue. https://codesandbox.io/p/devbox/great-brattain-hc9kgz but i found using non-repeating `key` can solve it.

This doesn't work as expected when there are multiple children inside AnimatePresence. When you change only one child, all children are rerendered and reanimated despite having different keys.
Here's an example: https://codesandbox.io/p/devbox/great-brattain-forked-npsfc8

**Comment by mattgperry** [comment]
My suspicion given that this always(?) involves `opacity` and switching back to a previously existing component, that there's a bug in how WAAPI animations resolve after being interrupted.

So I'm going to write a browser test that encapsulates this behaviour and then figure out a fix.

**Comment by web3techlord** [comment]
"framer-motion": "^11.11.9"
`
<AnimatePresence>
              {animations.map((animation) => (
                <motion.div
                  key={animation.id}
                  initial={{ opacity: 1, y: 0 }}
                  animate={{ opacity: 0, y: -400 }}
                  exit={{ opacity: 0 }}
                  transition={{
                    x: { type: "spring", stiffness: 100 },
                    duration: 0.8,
                    delay: 0.01,
                  }}
                  className="select-none font-medium text-[40px] text-amber-500 touch-none"
                  style={{
                    position: "fixed",
                    left: `${animation.x}px`,
                    top: `${animation.y}px`,
                  }}
                >
                  + 1
                </motion.div>
              ))}
            </AnimatePresence>
`
This animation is used in a tap game. When I tap fast and a lot, game app freezes.
Any idea?

**Comment by loxator** [comment]
My use case was Page Transitions and adding the `key` to the <Routes /> was causing issues. I tried changing it to different things, but it persisted. Weirdly enough, removing it fixed my issue.

**Comment by nxtkofi** [comment]
> My use case was Page Transitions and adding the `key` to the was causing issues. I tried changing it to different things, but it persisted. Weirdly enough, removing it fixed my issue.

My god.
Can confirm that this solution resolves the issue for latest version - 11.14.4

**Comment by jthrilly** [comment]
I am encountering this issue again with NextJS. Removing layoutID from the nested children allows the animate presence to work. Would a reproduction be helpful?

In the meantime, is there any troubleshooting I can do?

**Comment by adham618** [comment]
Downgrading to 10.12.2 fixed the issue for me

**Comment by CarlosVergikosk** [comment]
This still happens to me on 12.6.2, should it be re-opened or there is already an open issue ? @mattgperry

**Comment by mattgperry** [comment]
@CarlosVergikosk Opening a new issue with a sandbox reproduction would be best!

**Comment by CarlosVergikosk** [comment]
> [@CarlosVergikosk](https://github.com/CarlosVergikosk) Opening a new issue with a sandbox reproduction would be best!

Just did!

**Comment by AdemHodzic** [comment]
Had the same issue trying to implement Tinder-like swipe animation.

I change `AnimatePresence` from `mode="wait"` to `mode="popLayout"` which solved it for me.

**Comment by xellanix** [comment]
I've faced the same issue for my slides' app. I fixed it by changing the `AnimatePresence` code from the **framer-motion** node_modules. 

File: `node_modules\framer-motion\dist\es\components\AnimatePresence\index.mjs`
``` diff
  if (presentChildren !== diffedChildren) {
      ...
      for (let i = 0; i < renderedChildren.length; i++) {
          const child = renderedChildren[i];
          const key = getChildKey(child);
+         const isPresent = propagate && !isParentPresent
+             ? false
+             : presentChildren === renderedChildren ||
+                 presentKeys.includes(key);
-         if (!presentKeys.includes(key)) {
+         if (!isPresent) {
+             /**
+              * Only allow exit animation if it was a single child.
+              * Otherwise, it disappears instantly.
+              * This is the "Stack Breaker" rule.
+              */
+             if (renderedChildren.length !== 1) break;
+             
              nextChildren.splice(i, 0, child);
              exitingChildren.push(child);
+             break;
          }
      }
  }
```
``` diff
  exitComplete.forEach((isExitComplete) => {
      if (!isExitComplete)
          isEveryExitComplete = false;
  });
+ // Remove this specific child immediately, without waiting for others.
+ setRenderedChildren(pendingPresentChildren.current);
  if (isEveryExitComplete) {
      forceRender?.();
-     setRenderedChildren(pendingPresentChildren.current);
      propagate && safeToRemove?.();
      onExitComplete && onExitComplete();
  }
```

I tested it in my app that using `AnimatePresence` with those configurations:
- **framer-motion** version: 12.23.26
- `mode`: `sync`
- `custom` data: yes
- `propagate`: default (`false`)
- `initial`: default (`true`)

After I tested it with "wait" mode, the bug is still be there.
