### ISSUE TITLE
[BUG] framer-motion 11.0.11 introduces a bug with AcceleratedAnimation

### ISSUE THREAD

**Issue by justrealmilk** [framer/motion#2556]
```
Uncaught TypeError: Cannot destructure property 'animation' of 'this.resolved' as it is undefined.
    at AcceleratedAnimation.stop (AcceleratedAnimation.mjs:210:1)
    at MotionValue.stop (index.mjs:279:1)
    at index.mjs:148:1
    at Object.process (render-step.mjs:92:1)
    at processStep (batcher.mjs:19:1)
    at Array.forEach (<anonymous>)
    at processBatch (batcher.mjs:27:1)
```

I came from 11.0.8 and gradually incremented the version to find which release triggered my error. It's bad though, my pages stop rendering haha

I use a collection of motion components (`<motion.div />`) with variants. Nothing fancy.

Here's the line https://github.com/framer/motion/blob/main/packages/framer-motion/src/animation/animators/AcceleratedAnimation.ts#L273

**Comment by mattgperry** [comment]
Can you reopen with a sandbox example please?

**Comment by justrealmilk** [comment]
I mean you created the bug

**Comment by mattgperry** [comment]
Yes, and I would like to fix it. Please create a proper report next time to help me do so.

**Comment by ahinkle** [comment]
@justrealmilk Don't be rude. OSS maintainers owe you nothing.

**Comment by nicohorn** [comment]
> I mean you created the bug

Dude that was low
