### ISSUE TITLE
[BUG] TypeError: Cannot read properties of null (reading 'animate')

### ISSUE THREAD

**Issue by M165437** [framer/motion#2557]
**1. Read the FAQs**
✅

**2. Describe the bug**

The recently worked on `AcceleratedAnimation.ts` is causing a type error on our end, specifically the type casting in [line 171](https://github.com/framer/motion/blob/a7449c605341dbe0e6cd2f6379753b73e880d1eb/packages/framer-motion/src/animation/animators/AcceleratedAnimation.ts#L171):

```
TypeError: Cannot read properties of null (reading 'animate')
    at animateStyle (framer-motion/src/animation/animators/waapi/index.ts)
    at AcceleratedAnimation.initPlayback (packages/framer-motion/src/animation/animators/AcceleratedAnimation.ts)
```

Unfortunately, I haven't been able to reliably reproduce the error. It has been showing up regularly on our production system since yesterday (03/13)

**Comment by crtnx** [comment]
Me too. The same annoying issue of `Cannot destructure property 'animation' of 'this.resolved' as it is undefined.`
Rolled back to v10 and the issue gone.

**Comment by rbourdon** [comment]
Same issue here `Cannot destructure property 'animation' of 'this.resolved' as it is undefined.` Rolling back to 11.0.10 resolved the issue.

**Comment by bigint** [comment]
Happening the same for me!
