### ISSUE TITLE
[BUG] Exit animation for both X and Y transform not working properly

### ISSUE THREAD

**Issue by lyonsun** [framer/motion#2560]
**Describe the bug**

Upgraded framer motion to latest `v11.0.13` yesterday, and seeing something odd happening when I have both `x` and `y` in `exit` animation. The same thing doesn't happen in previous version `v11.0.12`.

**IMPORTANT: Provide a CodeSandbox reproduction of the bug**

  - A [CodeSandbox](https://codesandbox.io/p/devbox/great-maxwell-forked-t7gjxm?embed=1&file=%2Fpackage.json) with framer motion `11.0.12`.
  - A [CodeSandbox](https://codesandbox.io/p/devbox/great-maxwell-2q45jf?file=%2Fsrc%2FApp.tsx) with framer motion `11.0.13`.

**Expected behavior**

The exit animation should work like in `v11.0.12` where both x and y transformation happen at the same time.

**Comment by mattgperry** [comment]
Thanks for the reproductions, I'll take a look. As an immediate fix you can explicitly define x/y as being percentages.

```
   initial={{x:"0%", y:"0%"}}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0, x: "-100%", y: "-100%", rotate: "-30deg" }}
```

**Comment by mattgperry** [comment]
Weird that removing `rotate` also fixes the x animation.
