### ISSUE TITLE
[BUG] AnimatePresence + positionTransition broken in 1.4

### ISSUE THREAD

**Issue by praxxis** [framer/motion#257]
**Describe the bug**
Somewhere between 1.3 and 1.4 the combination of `<AnimatePresence>` and `positionTransition` on its children has stopped working - the children no longer animate their position after the `exit` animation of the removed component. 

**To Reproduce**
See https://codesandbox.io/s/framer-motion-reorder-animation-z0esb - clicking a button animates the button away, but there is no animation when reordering the other components.

If you change the `framer-motion` dependency back to 1.3 the position animations work again.

**Additional context**
I thought I was going crazy because the example sandboxes showed this working (they're pinned to a much older version of framer), and at some point during my debugging I observed that [point where the position measurement was happening](https://github.com/framer/motion/blob/master/src/motion/functionality/position.ts#L74) was getting different results in 1.3 and 1.4. It seemed like the measuring in 1.4 was happening _before_ the exit animation had finished, so the components position didn't seem to have changed.

**Comment by InventingWithMonster** [comment]
Thanks for the reproduction - this is a weird one as it still works in demos like https://codesandbox.io/s/framer-motion-drag-to-reorder-pkm1k. I'll have to investigate tomorrow.

**Comment by InventingWithMonster** [comment]
Ah it's when things are being added/removed rather than reordered.

**Comment by praxxis** [comment]
Thanks for the quick followup!
