### ISSUE TITLE
[BUG] Systematic error keyframes when updating framer @11.0.17

### ISSUE THREAD

**Issue by kevinrss01** [framer/motion#2583]
When I update framer to 11.0.17, I systematically get an error when I use animations.

`The error: Only two keyframes currently supported with spring and inertia animations. [...]`

Everything is ok in version 11.0.8. I don't know from which version this happens.

To reproduce I only have to upgrade to version 11.0.7.

**Environment :**
- Node@v20.11.1
- Next.js@14.1.4
- MacOS sonoma 14.2.1 M3 PRO
- Arc browser

Here a video demo:

https://github.com/framer/motion/assets/94388367/94155491-0d54-456c-b633-a76f3ed20040

**Comment by mattgperry** [comment]
Please reopen with a public sandbox reproduction, thanks!
