### ISSUE TITLE
[FEATURE] Support for `className` and `id`

### ISSUE THREAD

**Issue by JajarGaming** [framer/motion#2585]
**Is your feature request related to a problem? Please describe.**
Our codebase got an update related to the framer-motion package and it added types to `motion.div` and probably all the other ones. We previously had classes normally, but now it *technically works*, but throws errors in the IDE

**Describe the solution you'd like**
Added support for `className` and `id`. Could also add `class` for Preact

**Describe alternatives you've considered**
Not using framer-motion or returning back to the previous version.

**Comment by mattgperry** [comment]
Can you reopen with a codesandbox that can isolate this change? All HTML attributes are supported and locally tests are passing with these types.

**Comment by JajarGaming** [comment]
I found the problem - in framer-motions index.d.ts it uses `ReactHTML` which doesn't exist on `preact/compat`
![image](https://github.com/framer/motion/assets/71441748/ea3ebd09-d867-46c9-913b-22335ed81633)
![image](https://github.com/framer/motion/assets/71441748/017d98ba-c028-4a40-b73a-515378353418)
