### ISSUE TITLE
[BUG] `Maximum call stack size exceeded` error when using `delay` and `ease` function

### ISSUE THREAD

**Issue by bradlc** [framer/motion#2589]
Since `v11.0.11` a `Maximum call stack size exceeded` error is thrown when:

- A `delay` is defined and the animation has not yet started because the delay has not been exceeded, and
- An `ease` function is used, and
- The animation is interrupted

Above is my understanding of the circumstances in which the error occurs, but you can check out the reproduction to verify:

[CodeSandbox Reproduction](https://codesandbox.io/p/sandbox/compassionate-sky-3crdds?file=%2Fsrc%2FApp.tsx%3A12%2C27&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu2m77cx00063b6flj9fqbt7%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu2m77cx00023b6feu0ok8lu%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu2m77cx00033b6f36k6apbi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu2m77cx00053b6fpkod8wfo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu2m77cx00023b6feu0ok8lu%2522%253A%257B%2522id%2522%253A%2522clu2m77cx00023b6feu0ok8lu%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu2m9ym900023b6fhh8sp0ib%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A27%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A27%257D%255D%257D%255D%252C%2522activeTabId%2522%253A%2522clu2m9ym900023b6fhh8sp0ib%2522%257D%252C%2522clu2m77cx00053b6fpkod8wfo%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu2m77cx00043b6fyf3b2xf1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu2m77cx00053b6fpkod8wfo%2522%252C%2522activeTabId%2522%253A%2522clu2m77cx00043b6fyf3b2xf1%2522%257D%252C%2522clu2m77cx00033b6f36k6apbi%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu2m77cx00033b6f36k6apbi%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Steps to reproduce:

1. Click the "Toggle Size" button
2. Click the "Toggle Size" button again before the animation starts (i.e. within 2 seconds)

Expected (`v11.0.10`)

https://github.com/framer/motion/assets/2615508/0794273e-9e61-4702-ba64-4ef7996b3637

Actual (>= `v11.0.11`)

https://github.com/framer/motion/assets/2615508/7cdcf811-60b1-46fc-88a6-eed229f31792

**Comment by pklada** [comment]
Ran into this today too
