### ISSUE TITLE
[FEATURE] multiple transitions within a single animation

### ISSUE THREAD

**Issue by agonsalves** [framer/motion#259]
Let's say you need to get x from 0 to 100 over the course of 7.5 seconds. For the first 2 seconds, you want to use a cubic bezier ease, then for the next 4 seconds you want to use a linear ease, and then for the remaining time, you want to use another cubic bezier ease. You could split this up into 3 separate animations, but you'd need to know what the value of x should be at 2s and 6s. That's not easy to calculate, so turning transition into an array would take care of it. It might look something like this:

```
x: 100,
transition: [
    {
        duration: 2,
        ease: [.3,0,.3,1]
    },
    {
        duration: 4,
        ease: 'linear'
    },
    {
        duration: 1.5,
        ease: [.6,0,1,.7]
    }
]
```

**Comment by mattgperry** [comment]
Closing this as we're probably not going to implement this. What you probably want is a custom easing function that accepts `t` as `0` - `1`:

```javascript
import { progress, mix, cubicBezier, linear } from "popmotion"

const curveA = cubicBezier(.3,0,.3,1)
const curveB = cubicBezier(.6,0,1,.7)

const thresholdA = 0.2
const thresholdB = 0.8

function myEase(t) {
  if (t < thresholdA) {
    const p = progress(0, thresholdA, t)
    const easedP =  curveA(p)
    return mix(0, thresholdA, easedP)
  } else if (t >= thresholdA && t <= thresholdB) {
    return mix(thresholdA, thresholdB, linear(progress(thresholdA, thresholdB, t))
  } else {
    return mix(thresholdB, 1, curveA(progress(thresholdB, 1, t))
  }
}
```

You can imagine making a function that decides what the threshold values are based on your desired durations.
