### ISSUE TITLE
[BUG] Error Only two keyframes currently supported with spring and inertia animations.

### ISSUE THREAD

**Issue by talebi1** [framer/motion#2590]
**Describe the bug**
framer motion variatns example crash in 11.0.11 (works OK in 11.0.10) with the below error:
https://www.framer.com/motion/examples/#variants

Error
Only two keyframes currently supported with spring and inertia animations...

**CodeSandbox reproduction of the bug**
[
CodeSandbox example (same as the official exept for the  framer motion version)
](https://codesandbox.io/p/sandbox/framer-motion-side-menu-forked-9crglg)

**Steps to reproduce**
While the menu is opening or closing with an animation, quickly click the menu icon or just double-click the menu icon.

**Comment by hubingkang** [comment]
+1
