### ISSUE TITLE
[FEATURE] zIndex delay transition

### ISSUE THREAD

**Issue by ng-hai** [framer/motion#260]
**Is your feature request related to a problem? Please describe.**
I'm trying to build a dropdown selection, which changes `z-index` property depending on its state. But I cannot figure out a way to delay transition for `z-index` in some case, like this

![Screen Recording 2019-08-02 at 3 05 44 PM](https://user-images.githubusercontent.com/19520278/62354533-51b29e80-b537-11e9-8c22-34d4c01259b2.gif)

This is my variant
```js
const popoverVariant = {
  expand: {
    height: 'auto',
    zIndex: 1,
    transition: {
      height: {
        ease: [0.4, 0.0, 0.2, 1],
        duration: 0.3,
      },
    },
  },
  collapse: {
    height: 40,
    zIndex: 'auto',
    transition: {
      height: {
        ease: [0.4, 0.0, 0.2, 1],
        duration: 0.25,
      },
      zIndex: {
        delay: 1,
      },
    },
  },
}
```

**Describe the solution you'd like**
Maybe `step-end` easing function can help

**Comment by InventingWithMonster** [comment]
Odd - the delay in your example should work. I feel like this is a bug.

**Comment by InventingWithMonster** [comment]
You can use `transitionEnd` to set a value at the end of an animation

https://codesandbox.io/s/framer-motion-sandbox-p9gxv

**Comment by InventingWithMonster** [comment]
@EricVanDerDijs It does seem that value-specific delays aren't working, I'll take a look

**Comment by ng-hai** [comment]
Thanks @InventingWithMonster

**Comment by InventingWithMonster** [comment]
Value-specific delay fixed in `1.6.5`

**Comment by nboliver** [comment]
@mattgperry How do you change the z-index with a layout animation? It should be higher during the animation and then return to normal / default on transitionEnd. I set it up like : 
```
style={{ zIndex: 10 }}
animate={{ transitionEnd: { zIndex: 0 } }}
layoutId={`project-image-${slug}`}
```
but it just jumps to `0` immediately.

**Comment by 4g3nt81lly** [comment]
@nboliver Don't know if you've found the solution, but I ended up using a motion value:
```tsx
const zIndex = useMotionValue(0);

// ...

<motion.div
    style={{ zIndex }}
    layoutId={layoutId} // your layoutId
    onLayoutAnimationStart={() => zIndex.set(10)}
    onLayoutAnimationComplete={() => zIndex.set(0)}
>
    {/* ... */}
</motion.div>
```

Putting this here in case anyone else is also looking for this.
