### ISSUE TITLE
[BUG] with new version 11.0.24

### ISSUE THREAD

**Issue by HenrikBechmann** [framer/motion#2602]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

on compile I get 

```
../../../node_modules/framer-motion/dist/index.d.ts(1902,11): error TS2430: Interface 'CSSStyleDeclarationWithTransform' incorrectly extends interface 'Omit<CSSStyleDeclaration, "direction" | "transition">'.
  Types of property 'x' are incompatible.
    Type 'string | number' is not assignable to type 'string'.
      Type 'number' is not assignable to type 'string'.
```

Give a clear and concise description of what the bug is.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

A CodeSandbox minimal reproduction will allow us to quickly follow the reproduction steps. **Without one, this bug report won't be accepted.**

**4. Steps to reproduce**

**5. Expected behavior**

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

**7. Environment details**

If applicable, let us know which OS, browser, browser version etc you're using.

### `"use client"` error

We would accept a PR implementing `"use client"` (see [previous discussion](https://github.com/framer/motion/issues/2054)). In the meantime a workaround is:

```javascript
// motion.js
"use client"
export * from "framer-motion"

// other.js
import { motion } from "./motion"
```

### Framer Motion won't install

Framer Motion 7+ uses React 18 as a minimum. If you can't upgrade React, install the latest version of Framer Motion 6.

### `height: "auto"` is jumping

Animating to/from `auto` requires measuring the DOM. There's no perfect way to do this and if you have also applied padding to the same element, these measurements might be wrong.

The recommended solution is to move padding to a child element. See [this issue](https://github.com/framer/motion/issues/368) for the full discussion.

### Preact isn't working

Framer Motion isn't compatible with Preact.

### `AnimatePresence` isn't working

Have all of its immediate children got a unique `key` prop that **remains the same for that component every render**?

```jsx
// Bad: The index could be given to a different component if the order of items changes
<AnimatePresence>
    {items.map((item, index) => (
        <Component key={index} />
    ))}
</AnimatePresence>
```

```jsx
// Good: The item ID is unique to each component
<AnimatePresence>
    {items.map((item, index) => (
        <Component key={item.id} />
    ))}
</AnimatePresence>
```

Is the `AnimatePresence` correctly outside of the controlling conditional? `AnimatePresence` must be rendered whenever you expect an `exit` animation to run - it can't do so if it's unmounted!

```jsx
// Bad: AnimatePresence is unmounted - exit animations won't run
{
    isVisible && (
        <AnimatePresence>
            <Component />
        </AnimatePresence>
    )
}
```

```jsx
// Good: Only the children are unmounted - exit animations will run
<AnimatePresence>{isVisible && <Component />}</AnimatePresence>
```

**Comment by HenrikBechmann** [comment]
I reverted to version 10.16.4, but still get the error.

Yet, webpack compiles my code with no errors.

**Comment by CiroLee** [comment]
> I reverted to version 10.16.4, but still get the error.
> 
> Yet, webpack compiles my code with no errors. (the error is shown with sublime text (build 4169) build)

I encountered this problem when building. This bug may be related to typescript. I reverted to version 5.3.3 and the error will not be reported when building

**Comment by nonara** [comment]
A little more detail — changes were made to TS v5.4 which it sounds like would be the culprit. Quickly skimming the release notes, I see that there were changes in strictness for narrowing and changes to libs. 

Release notes are here: 

- https://devblogs.microsoft.com/typescript/announcing-typescript-5-4/
- https://github.com/microsoft/TypeScript/pull/57027

What I can ascertain quickly is that `CSSStyleDeclaration` in `lib.dom.d.ts` has properties `x`, `y`, etc. defined as being `string`, so attempting to override and broaden those with a union including number are causing it to throw a diagnostic.

Please let us know when it's updated, and thanks for the great work!

**Comment by sevesalm** [comment]
The type error is still present. Should we create a new issue with maybe a more descriptive name and bug description to get this forward? It seems this issue is about `AnimatePresence` not working.

**Comment by sevesalm** [comment]
I think this issue was fixed int commit https://github.com/framer/motion/commit/ff8b1af3abe681dc8b49e85ddd20f9140211e655 and I no longer get the error in the latest version.

I guess this issue can be closed.
