### ISSUE TITLE
[BUG] AnimatePresence - enter and exit animations are mixed when they alternate rapidly

### ISSUE THREAD

**Issue by Thanaen** [framer/motion#2618]
**1. Read the [FAQs](#faqs) 👇**
Done ✅

**2. Describe the bug**
Enter and exit animations are mixed when they alternate rapidly.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://stackblitz.com/edit/vitejs-vite-5ocwzr?file=src%2FApp.tsx

**4. Steps to reproduce**
1. Slow click on "Next" and "Previous" to see the animation properly working
2. Now quickly click on "Next" and "Previous" to see the animation break

**5. Expected behavior**

The animation that works when slowly clicking on "Next" and "Previous" should also work when quickly clicking on "Next" and "Previous"

**6. Video or screenshots**
![framer-presence-issue](https://github.com/framer/motion/assets/16762369/13b6de70-a564-4013-9b17-929cf785e0ae)

If applicable, add a video or screenshots to help explain the bug.

**7. Environment details**
Tested on:
- Microsoft Edge 123.0.2420.81
- Google Chrome 123.0.6312.123
- Firefox 124.0.2

Tested on both `framer-motion@^10` (currently `10.18.0`) & `framer-motion@^11` (currently `11.0.28`)

UPDATE:
The problem doesn't actually exist on 10.18.0, even though this version has a small glitch visual (it blinks) when you make a quick change.

**Comment by Thanaen** [comment]
_PS: This is possibly a duplicate of bug #2554 , but the work-around proposed in this bug (use framer-motion@11.0.10) does not solve the problem in my repro repository._

**Comment by beefchimi** [comment]
I have also been battling with this issue for awhile, and have not found a fix.

While I am unable to reproduce the issue in the `StackBlitz` link provided by the author, I can consistently re-create it in several of my local projects.

Here is a video of a `TextArea` UI animating some "invalid character count" UI. We can see that the UI animates in/out perfectly when making edits at a moderate pace. But once I start making edits more quickly - such as removing and re-adding the `e` - the "invalid UI" gets stuck and remains visible even after the conditions that would render it are no longer true.

https://github.com/framer/motion/assets/643944/009dc9d6-74d3-4828-89c7-9c970870545f

The code for this would look something like:

```ts
const characterCountMarkup = !validateUsernameLength(value) ? (
    <CharacterCount key={`UserName-CharacterCount-${value.length}`} count={value.length} />
) : null;

<AnimatePresence>{characterCountMarkup}</AnimatePresence>
```

I am currently on version `11.1.7` but have tried this on `11.0` as well with the same result.

**Comment by beefchimi** [comment]
**I've created another minimal reproduction in case it is helpful:**
https://stackblitz.com/edit/framer-motion-fast-change-bug?terminal=dev

https://github.com/framer/motion/assets/643944/ca6ec126-db3b-43f7-bc4b-2550615b1248

**Comment by Thanaen** [comment]
@beefchimi 
Not using opacity reduces the problem, but doesn't solve it entirely (link to my own comment 😄: https://github.com/framer/motion/issues/2554#issuecomment-2066629659)

**Comment by Taib-Rabah** [comment]
I also faced that problem, I had to prevent the user from changing the state rapidly by disabling the buttons while the animation is running

here's what I created if any1 is interested:

* [Code + Preview on Stackblitz](https://stackblitz.com/~/github.com/Taib-Rabah/Framer-Motion-AnimatePresence-bug-and-workaround-solution)
* [Code on GitHub](https://github.com/Taib-Rabah/Framer-Motion-AnimatePresence-bug-and-workaround-solution)

**Comment by LeonLiu2020** [comment]
I ran into the same problem. And it's not only about opacity,  just using x, the same problem occurs. Someone mentioned in another issue that using different keys could help. I tried that and didn't work for me. In the DOM tree, there are many elements with different keys that should disappear due to conditional rendering, but none of them did.
