### ISSUE TITLE
[FEATURE] Improved support for managing both variant-style animations as well as arbitrary-value style animations at the same time

### ISSUE THREAD

**Issue by jamesplease** [framer/motion#262]
**Is your feature request related to a problem? Please describe.**

This isn't really a problem, per se, but it is a way to make the declarative component props API work in more situations.

Some background:

framer-motion's component props API supports two distinct kinds of animations. The first kind is "variant"-based animations, where the different variants capture discrete versions of a particular element. For instance, a component might have the following variants:

- open, closed, big, small

Consumers can animate between these variations using the `animate` prop:

```jsx
// Starting with these variants...
<motion.div variants={variants} animate={['open', 'big']} />

// ...you can then animate over to these
<motion.div variants={variants} animate={['closed', 'small']}/>
```

It also supports arbitrary animations using the object form of the `animate` prop. For instance, the position of an element could be animated based off of a number that's randomly generated every few seconds:

```jsx
const [x, setX] = useState(50);

useEffect(() => {
  setInterval(() => {
    setX(Math.random() * 100);
  }, 1000);
}, []);

// As `x` changes arbitrarily, this div will move around the page.
return (<motion.div animate={{ x }) />);
```

Tthe component API of framer-motion does not support doing both kinds of these animations at the same time, but a slight change to that API could make it so that it does.

**Describe the solution you'd like**

Updating the `custom` prop triggers animations when it changes would allow components to handle both kinds of animations. That way, even when the variants specified in `animate` remain constant, they can dynamically update from a value passed in through `custom`.

Right now, changes to `custom` do not trigger rerenders. [**View a CodeSandbox demonstrating this here.**](https://codesandbox.io/s/framer-motion-custom-doesnt-animate-8st85)

However, consider the following:

```jsx
// Given the following variant, which depends on `custom`:
const someVariants = {
  position(xValue) {
    return {
      x: xValue * 50
    };
  }  
};

// as `xValue ` changes, the `position` variant would animated, even if the
// `animate` prop doesn't change.
<motion.div variants={someVariants} animate="position" custom={xValue} />
```

[**View a CodeSandbox demonstrating this change using the code from #264**](https://codesandbox.io/s/framer-motion-custom-now-animates-4cqim)

This particular example is simple enough that you can solve it using existing framer-motion APIs, but the motivation for this change comes from more complex examples; namely, when you also want to use variants. See the CodeSandbox link below for an example of that kind of situation.

**Describe alternatives you've considered**

In the following CodeSandbox, each item in the list has different variants: visible/hidden and big/small. Additionally, the position of the item is determined by an arbitrary function. The CodeSandbox shows how you can write it declaratively using two motion components.

- Using two motion components. [**View a CodeSandbox here.**](https://codesandbox.io/s/old-pond-9exvt)

- An example showing the AnimationControls API [**View a CodeSandbox here.**](https://codesandbox.io/s/framer-motion-imperative-2-bdxo5)

**Comment by InventingWithMonster** [comment]
Excellent write-up, thanks!

I totally see this use-case. My fear is that there's going to be situation where we don't want this - you've already identified one with data structures. Generating a `delay` based on `custom={index}` is one of the predominant use-cases with `custom` and that definitely isn't something that warrants triggering a new animation.

With changing the value of `custom` there's only implicit intention and given these examples I'm hesitant to add that behaviour unless we're certain we want it in every situation.

In Pose there was an attribute called `poseKey`. When that changed it would force a new animation based on anything in `pose` prop. This wouldn't be quite as transparent but it would provide explicit consent to trigger a new animation.

I think there's value in doing something similar here with an `animateKey`. It would also work with `animate` when set as an object. This ability would have prevented me from needing imperative controls in this sandbox for instance: https://codesandbox.io/s/framer-motion-spring-powered-characters-remaining-count-i1wgk

**Comment by jamesplease** [comment]
Thanks for the quick reply, @InventingWithMonster ! I agree with you that introducing the `animateKey` prop makes more sense than changing the behavior of `custom`.

Based on this, I'll close out #264 .

If you'd like, I could try my hand at opening a PR to demonstrate this additional `animateKey` prop, although if you could implement it more quickly and would prefer to do that I can leave you to it; I know that sometimes the review process of PRs can be slower/more work than just implementing it yourself 🙂

**Comment by InventingWithMonster** [comment]
Ah no it'd be great to have a PR for this! I think your last PR was pretty close, it probably just needs adding to the `motion` component types.

**Comment by jamesplease** [comment]
tbqh...I forget. It looks like that PR is still open, so my guess is this that isn't possible still. v2 is right around the corner, so maybe it will be introduced then? I haven't had a chance to look unfortunately! I used to use this lib a lot at work but for the past few months I haven't had a chance to.

**Comment by mattgperry** [comment]
I've closed the attached PR and closing this issue. The officially-recommended way of triggering animations outside of Motion's internal logic is with the animation controls API:

```javascript
const controls = useAnimation()

useEffect(() => {
  controls.start({ x: 100 })
}, [invalidateAnimate])

return <motion.div animate={controls} />
```

**Comment by jamesplease** [comment]
Np – thanks for considering this change, @mattgperry !

I still think that this would improve the DX of the lib, but I understand you've likely got more impactful priorities ✌️

Thanks again for taking the time to think about this issue, as well as all of the amazing work you've done on framer-motion!

**Comment by obinasBaba** [comment]
Is it possible to change `variants` labels in `useEffect` like this: 

`const [ initialVariant, setInitialVariant ] = useState( 'initial'  );

useEffect( () => {
    if(  *\ some condition */  )
       setInitialVariant( 'initial__2' );
}

return <motion.div initial={ initialVariant }  varaints={ variant } />
`

I don't want to use a different variant depending on what page I came from. but it doesn't seem to work like the above.
