### ISSUE TITLE
[BUG] Property '$$typeof' is missing in `ForwardRefComponent`

### ISSUE THREAD

**Issue by jeremybanka** [framer/motion#2632]
**1. FAQs** 

👍 

**2. Describe the bug**

`framer-motion`'s new definition of `ForwardRefComponent` has broken compatibility with `React.ForwardRefExoticComponent`

**3. CodeSandbox**

[CodeSandbox](https://codesandbox.io/p/devbox/ykrjx9?migrateFrom=s38v6s&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clv5llwjg00063d5u6j4952rv%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clv5llwjg00023d5u4tbtruh6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clv5llwjg00043d5uqz57etkr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clv5llwjg00053d5umh0qu3sf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clv5llwjg00023d5u4tbtruh6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv5llwjf00013d5u14qleosu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%257D%255D%252C%2522id%2522%253A%2522clv5llwjg00023d5u4tbtruh6%2522%252C%2522activeTabId%2522%253A%2522clv5llwjf00013d5u14qleosu%2522%257D%252C%2522clv5llwjg00053d5umh0qu3sf%2522%253A%257B%2522id%2522%253A%2522clv5llwjg00053d5umh0qu3sf%2522%252C%2522activeTabId%2522%253A%2522clv5lm9so007b3d5utt26h9er%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clv5lm9so007b3d5utt26h9er%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%252C%2522clv5llwjg00043d5uqz57etkr%2522%253A%257B%2522id%2522%253A%2522clv5llwjg00043d5uqz57etkr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv5llwjg00033d5u4jd7t63p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clv5llx94000kdaf86qy23zli%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clv5lm5wi00693d5u6rdc66qc%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clv5llwjg00033d5u4jd7t63p%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
(seems like you'll need to create a fork to run the TS language server...?)

**4. Steps to reproduce**

1. Create a function that takes a param typed as `React.ForwardRefExoticComponent`.
2. Pass `motion.div` to that component.
3. You'll get a typescript error noting a missing property `$$typeof` in framer's `ForwardRefComponent`.

**5. Expected behavior**

No typescript error, as in `framer-motion@11.1.3`

**6. Video or screenshots**

<img width="727" alt="Screenshot 2024-04-18 at 12 20 02" src="https://github.com/framer/motion/assets/8570459/a735edfa-35a8-4e99-81b0-2a885a649757">

**7. Environment details**

TypeScript 5.4.5

**Comment by jeremybanka** [comment]
PR here: https://github.com/framer/motion/pull/2631

**Comment by mattgperry** [comment]
Thanks for the PR! Will publish now
