### ISSUE TITLE
[BUG] `TypeError: Unable to convert null to object` may occur in certain instances when using whileInView in conjunction with delay

### ISSUE THREAD

**Issue by lujjjh** [framer/motion#2645]
**2. Describe the bug**

```typescript
function Foo() {
  return (
    <motion.div whileInView={{ y: 10 }} transition={{ delay: 0.01 }}>
      Hello, <code>framer-motion</code>.
    </motion.div>
  );
}
```

When a `<Foo />` element is unmounted, a TypeError occurs because framer-motion attempts to animate the 'y' property from 10 to null.

As a workaround, the transition can be relocated to the `whileInView` property. Nevertheless, it would be more ideal to prevent the TypeError from being triggered.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/p/sandbox/framer-motion-issue-hxv3pt?file=%2Fsrc%2FApp.tsx%3A20%2C17-20%2C28

**4. Steps to reproduce**

1. Click "Toggle visibility".

**5. Expected behavior**

No errors occur.

**Comment by bredigian** [comment]
Hey, can you solved this bug? I have the same problem and I'm furious.

**Comment by lujjjh** [comment]
@bredigian In this example, only set `transition` for `whileInView`:
https://codesandbox.io/p/sandbox/framer-motion-issue-forked-6h53tq?file=%2Fsrc%2FApp.tsx%3A23%2C5

**Comment by bredigian** [comment]
> @bredigian In this example, only set `transition` for `whileInView`:
> https://codesandbox.io/p/sandbox/framer-motion-issue-forked-6h53tq?file=%2Fsrc%2FApp.tsx%3A23%2C5

okay, thanks you.

**Comment by kayeew** [comment]
Also experiencing the same issue, moving my entire transition to whileInView was not so simple so no choice but to revert back to an older version

**Comment by lujjjh** [comment]
It seems that this issue has been resolved in the latest version.
