### ISSUE TITLE
[BUG] layout - parent height does not animate when child is removed

### ISSUE THREAD

**Issue by airfortech** [framer/motion#2659]
**1. Describe the bug**

Parent height does not animate when child is removed. After change `AnimatePresence` `mode` to `popLayout`, parent height animates but child exit not. None of modes is working as expected.

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[https://codesandbox.io/p/sandbox/framer-motion-layout-k367fk?file=%2Fsrc%2FApp.js](https://codesandbox.io/p/sandbox/framer-motion-layout-k367fk?file=%2Fsrc%2FApp.js)

**3. Steps to reproduce**

1. Click `Add Items`. `ul` Height is animating properly.
2. Click some `Item`. Its exit animation works. After end `ul` height changes immediately. Should animates.

**4. Workaround fix**

After downgraded framer-motion to 4.0.0 and wrapped `<motion.ul>` with `<AnimateSharedLayout>` it works as expected.

**5. Video**

How it should work: (fm 4.0)
![opera_i9xgFi1MNC](https://github.com/framer/motion/assets/23710904/3bcd52de-0937-4034-80c7-1a73356601d5)

How it works now:
![opera_7bP04n3Ils](https://github.com/framer/motion/assets/23710904/7f6f3899-eaed-4181-a770-3d8c7a6c1b50)

**6. Environment details**

Windows 10, Opera, Edge. Same bug.

**Comment by mattgperry** [comment]
Ah yeah you need to wrap the list with `LayoutGroup` https://www.framer.com/motion/layout-group/

As layout animations are only triggered on render, and the `AnimatePresence` render to finally remove the element is private to itself.

**Comment by airfortech** [comment]
yea, with `LayoutGroup` wrapper it works.

**Comment by OahMada** [comment]
What if a grandchild is causing the height change? LayoutGroup doesn't seem to work in this case.
