### ISSUE TITLE
[BUG] Found a regression Introduced since version 11.0.11

### ISSUE THREAD

**Issue by WhiZTiM** [framer/motion#2663]
**1. Read the [FAQs](#faqs) 👇**
- [x] read

**2. Describe the bug**
In The documentation [regarding Spring physics](https://www.framer.com/motion/transition/#spring), there is a link to this [codesandbox](https://codesandbox.io/p/sandbox/framer-motion-spring-transition-e6c8dm?file=%2Fpackage.json%3A8%2C1-9%2C1&from-embed=) which shows the circle being animated.

##### _The Bug:_
- That example codesandbox uses version `10.17.4`.
- **_Running that example with newer releases of framer-motion (including version `11.2.0`) stutters baddly._**
- I did a bisect on the releases (tags) since `10.17.4`, and I discovered the regression was introduced in `11.0.11`.
- I would have love to dig in further, but the changeset is a bigger than my competency
https://github.com/framer/motion/compare/v11.0.10...v11.0.11 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

- Last version before regression [Link to `v11.0.10`](https://codesandbox.io/p/sandbox/hidden-tdd-vsykhw?file=%2Fpackage.json%3A8%2C30)
- Version That introduced the regression [Link to `v11.0.11`](https://codesandbox.io/p/sandbox/framer-motion-spring-transition-forked-kqflrx?file=%2Fpackage.json%3A5%2C18)

**4. Steps to reproduce**

1. See the initial example
2. Change framer-motion version
3. See the regression

**5. Expected behavior**

Animation should be smooth

**6. Video or screenshots**

-----------

_To the maintainers, Thank you for this awesome library, that makes front-end newbie a visual rockstar!!!_

**Comment by WhiZTiM** [comment]
I believe it's same bug here #2582

**Comment by mattgperry** [comment]
Yeah it is, closing as dupe
