### ISSUE TITLE
[BUG] Animating already exiting elements causes them not to unmount

### ISSUE THREAD

**Issue by WerdoxDev** [framer/motion#2673]
**1. Read the [FAQs](#faqs) 👇**
done
**2. Describe the bug**

Lets say we have a swap animation using AnimatePresence and it animates the swapping of 2 divs.
now when div a is entering and div b is exiting and I trigger the swapping again, it forgets to remove the now exiting div a.
or sometimes it works correctly but the next time triggering the animation both elements show up at the same time.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/p/sandbox/framer-motion-bug-rmgdpz

**4. Steps to reproduce**

Click "change"
Then click it again while both elements are animating.
It all breaks

**5. Expected behaviour**

Simply exit and unmount the exited element

**Comment by quentinlagache** [comment]
Bug related to `opacity` property present since `11.0.11`.
Duplicate issue of: #2618 #2554 #2416 

Would be great for @mattgperry to be able to look into it 🙏

**Comment by pklada** [comment]
Pls 🙏

**Comment by FlashLim** [comment]
I am too facing the problem, regardless of `opacity` property.

Version: 11.3.12
I have tried AnimatePresence with `popLayout`, `wait` and `sync` with nested component property `x` or `y` or `scale` or `width` or `height`. 
The nested component in AnimatePresence did not unmount.

I went for Version 11.0.10 fix the problem temporary.
