### ISSUE TITLE
[BUG] laggy animations after 11.0.10 version

### ISSUE THREAD

**Issue by Bazyli12** [framer/motion#2683]
**Describe the bug**

After version 11.0.10, animations in component (src/components/FramerAnim/Magnet.jsx) were lagged

https://codesandbox.io/p/github/Bazyli12/magnetic-button-bug/main

**Steps to reproduce**

move the mouse over bottom icons.

**Expected behavior**

icons should be smooth like in gsap version or as in this https://proj-magnetic-buttons.vercel.app/

**Video or screenshots**

good, smooth animation (up to 11.0.9 version)
https://github.com/framer/motion/assets/79319856/463e5521-fb87-4480-939f-3b1cb26bb2b6

wrong, laggy animation (after 11.0.10 version)
https://github.com/framer/motion/assets/79319856/37fc85f2-d1c2-4872-9a17-2177dcadc7ad

**Environment details**

Windows 11, Arc

**Comment by mattgperry** [comment]
I don't have permissions to copy your project - can you verify the `11.x` version was `11.2.4` or higher.

**Comment by mattgperry** [comment]
Because `11.0.11` introduced deferred keyframe resolution, which resolved keyframes on the following frame. This pattern of setting state every animation frame was never encouraged vs using Motion Values but did outright break with this change.
