### ISSUE TITLE
AnimatePresence firing preEnter motion before exit motion[BUG]

### ISSUE THREAD

**Issue by bpurtz** [framer/motion#269]
**Describe the bug**
I am attempting to utilize this library with reach router. I realize you guys have gone the way of the new React Router, but my company has not migrated and will try to avoid migrating, so I have to work with what I got. I will post a sandbox of my code, but here is the gist of it:

I want to be able to animate out pages when the user changes pages. This obviously looks like a job for AnimatePresence! But It is firing it's 'poses' in weird ways. When I switch pages, the page that just umounted does not stick around as desired. I was under the impression that it would stay until the exit animation finishes, but this does not seem to be the case. Instead, the pre-enter pose for the incoming child fires, then the exit pose for the incoming child, then the enter pose for the incoming child. I know, it's weird. You can see a simplified version of the fork I made of one of your codesandbox examples to utilize reach router:
https://codesandbox.io/s/framer-motion-x-react-router-blb78

**To Reproduce**
1. Go to 'https://codesandbox.io/s/framer-motion-x-react-router-blb78'
2. Click on an image
3. Bring of the console and look at the logs. 
4. go back and forth to see how the poses are firing. 
5. No animation takes place when the unmounting child unmounts. 

**Expected behavior**
I would like the exit pose for the unmounting child to fire, then the initial pose fire for the incoming child, then finally the enter pose to fire for the incoming child. The 'exitBeforeEnter' prop would be useful if it actually delayed the mounting child from animating until the unmounting child unmounts.

**Screenshots**
![Screen Shot 2019-08-06 at 8 19 13 PM](https://user-images.githubusercontent.com/40925796/62592289-813f0f00-b887-11e9-8b88-f68e9941a31d.png)

This is a screenshot that clearly shows the order of the mounting component. The exit pose gets called on the mounting component, not on the unmounting one. 

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Chrome
 - Version recent

I am just starting in on this library after using react-pose for a month or so. If I am making some stupid error, please let me know and I will close this issue with gratitude! My end goal is this:
 I am building sliding views with a sub-router from reach/router. I want the view to slide either right or left depending if they are going forwards or backwards in the process. The first step to getting this to happen is just to get them sliding in one direction nicely, then I will worry about dynamic poses to determine the direction of the sliding motion. Any help to further that goal would be greatly appreciated!

**Comment by worksbyscott** [comment]
Was there ever a solution to this problem, I'm having a similar issue?

**Comment by iDavid2619** [comment]
Same problem was experienced, the only solution found so far is to mimic the previous page in the initial state, but this is not doable for complex pages, any solutions? The previous page should be able to be kept alive, I've tried delaying the exit and setting mode to sync but no luck
