### ISSUE TITLE
AnimatePresence doesn't work on parent+child [BUG]

### ISSUE THREAD

**Issue by maxwoo-houzz** [framer/motion#270]
**Describe the bug**
If you try to animate both a parent and child element on dismount, it will only animate the parent and not the child.

**To Reproduce**
1. check out [this sandbox](https://codesandbox.io/s/framer-motion-animate-presence-unmount-rh3jj) and click "mount" and "dismount" to see what happens on dismount. Alternatively, here is the code for the react component:

```

function App() {
  const [isVisible, onCycle] = useCycle(true, false);

  return (
    <div>
      <button onClick={onCycle}>Toggle</button>
      <AnimatePresence>
        {isVisible && (
          <motion.div className="container"
              key="child"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}>
            <motion.div className="banner"
                key="child2"
                initial={{ y: 0 }}
                animate={{ y: 100 }}
                exit={{ y: 0 }}>
              Hello
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
```

**Expected behavior**
Both the parent and child should be animated on dismount.

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser Chrome
 - Version 75

**Comment by InventingWithMonster** [comment]
That’s as specced. You can use variants if you want the exit animation to propagate.

**Comment by maxwoo-houzz** [comment]
@InventingWithMonster awesome, that works. However, I couldn't find anywhere in the documentation that specifies that you have to use variants to propagate the exit animation. At least with `initial` and `animate`, it seems like you can define them explicitly on parent and child just fine (no need for variants), so it isn't clear how I would know that for `exit` you have to use variants.

**Comment by InventingWithMonster** [comment]
It’s a good point I’ll take a look at clarifying this in the docs!
