### ISSUE TITLE
Animate Presence won't evaluate inner react expressions while dismounting[BUG]

### ISSUE THREAD

**Issue by maxwoo-houzz** [framer/motion#271]
**Describe the bug**
If you want to have some content reactively update while dismounting, it won't work with AnimatePresence. For example, in [this sandbox](https://codesandbox.io/s/framer-motion-animate-presence-unmount-xofgq) I am trying to update the text while the element disappears. Notice how it works with regular animation, but not with AnimatePresence.

**To Reproduce**
1. Check out [this sandbox](https://codesandbox.io/s/framer-motion-animate-presence-unmount-xofgq)
2. click toggle to make the elements appear and disappear

Notice how the top element content gets updated while animated, but the bottom doesn't. The top element uses regular Framer animation, and the bottom uses Animate Presence. 

**Expected behavior**
The text content should update as the element is being animated and dismounted.

**Code to Reproduce Bug**
Here is the code I used in the sandbox, in case the sandbox ever goes down:

```babel
import React from "react";
import ReactDOM from "react-dom";
import { motion, AnimatePresence, useCycle } from "framer-motion";

import "./styles.css";

export const MyComponent = ({ isVisible }) => {
  let variant = isVisible ? { opacity: 1 } : { opacity: 0 };
  return (
    <motion.div
      className="container"
      key="container"
      animate={variant}
      transition={{ duration: 2 }}
    >
      <div>{`regular animate${isVisible ? "" : " hidden"}`}</div>
    </motion.div>
  );
};

export const MyComponent2 = ({ isVisible }) => {
  let variant = isVisible ? { opacity: 1 } : { opacity: 0 };
  return (
    <AnimatePresence>
      {isVisible && (
        <motion.div
          className="container"
          key="container2"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 2 }}
        >
          <div>{`animate presence${isVisible ? "" : " hidden"}`}</div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

function App() {
  const [isVisible, onCycle] = useCycle(true, false);
  return (
    <>
      <button onClick={onCycle}>Toggle</button>
      <div className="pagebody">
        <MyComponent isVisible={isVisible} />
        <MyComponent2 isVisible={isVisible} />
      </div>
      {/*isVisible && <MyComponent color="red" isVisible={isVisible} />*/}
    </>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome
 - Version 75

**Comment by InventingWithMonster** [comment]
Sorry, this is an intrinsic limitation of React. The component has been removed, so it can't receive further updates.

**Comment by InventingWithMonster** [comment]
That’s how AnimatePresence works. But the component isn’t updating because
you’ve unmounted it. AnimatePresence keeps the previous component reference
around until the animation completes. There is no new one because it’s been
unmounted.

**Comment by maxwoo-houzz** [comment]
is it possible to remount the component so that it still receives updates while animating, and then unmount it afterwards?

**Comment by InventingWithMonster** [comment]
No I'm afraid not

**Comment by amannn** [comment]
@maxwoo-houzz I had the same issue. You can work around it, by debouncing the value that hides the children inside of `<AnimatePresence />` by one frame, but reading the up-to-date value inside the children.

The gist is:

```js
// The children are generally visible when `isVisible` is `true`. However when the
// value switches to `false`, we need to render the children one additional frame, so 
// they can read the `isVisible: false` value. This avoids the stale props problem
// that is created when `AnimatePresence` renders the previous children.
const debouncedIsVisible = useDebounced(isVisible, isVisible ? 0 : 1) || false;

return (
  <AnimatePresence>
    {debouncedIsVisible && (
      <motion.div>
        {isVisible}
      </motion.div>
    )}
  </AnimatePresence>
);
```

See the updated CodeSandbox: https://codesandbox.io/s/framer-motion-animate-presence-unmount-7u6xu

**Comment by maxwoo-houzz** [comment]
@amannn neat! Though it's worth mentioning that it only fixes the initial state of the dismounted component, but if the state changes during dismount, that won't be reflected. I forked your sandbox to show this: https://codesandbox.io/s/framer-motion-animate-presence-unmount-8tuq1. Basically I just added a constantly refreshing timer, and you can see that on dismount, the `animate presence` timer freezes

**Comment by amannn** [comment]
@maxwoo-houzz good point!

In my scenario I had the issue that callbacks that were passed to the unmounting component became stale and didn't see the updated `isVisible` value. For that use case the solution is sufficient.

As @InventingWithMonster has mentioned before, the limitation is that you can't pass updated props to the component, since it isn't rendered anymore. However internally, Framer Motion still renders the previous children with the props they received when they were last mounted.

So if you can avoid props, you can still pass in values. One option is context, but you can also set up an event listener within the unmounting component.

I've forked your Sandbox to show a possible solution for the particular use case of displaying the current time: https://codesandbox.io/s/framer-motion-animate-presence-unmount-g9xhx. I guess this solution falls more in the "event listener" category.

**Comment by maxwoo-houzz** [comment]
@amannn oh I see, you moved the `useTimer` call into the inner component, so that the inner component was hooking to the `time` variable itself and not relying on the parent component to pass it down. Clever! This is actually a nice workaround to keep in mind the next time I need to do something like this.

However, this is still clearly just a workaround, and there are a few subtle but major issues with this approach. First, if there are multiple pieces of data that are changing during dismount, they all have to be refactored to use react hooks or event listeners. This adds a lot of boilerplate and complexity. In fact, if we wanted to be consistent, every single variable under every single `AnimatePresence` component would have to be converted to a react hook. If you were unmounting a sidebar...that's a lot of variables.

Second, imagine if a single prop was being passed down a component tree and was used in multiple places along the way. Something like:

```
<grandparent>
    <div>{currentTime}</div>
    <parent>
        <div>{currentTime}</div>
        <AnimatePresence>
            <div>{currentTime}</div>
```

There are two options. Either, refactor only the components under `<AnimatePresence>` to use react hooks or event listeners, and leave the outer ones to use props. Or, refactor all of them to use react hooks / event listeners. So for the sake of consistency, this workaround is now affecting components that aren't even being unmounted! I guess you could summarize that this workaround is not consistency to the React philosophy, where props are used to propagate data down the component tree. The behavior of `AnimatePresence` forces inner components to manually hook into the data that they need.

To me, it seems like this should be a solution implemented at the framework level. Eg, for framer motion to re-attach child components to parent components during unmount. In fact even in [the docs](https://www.framer.com/api/motion/animate-presence/#unmount-animations) it says that AnimatePresence:

>Allows them to defer that unmounting until after an operation is complete (for instance an animation).

So I feel like this is the behavior people would expect. I wonder if there are any clever fixes that we can find in the framework itself to allow this! :)

**Comment by amannn** [comment]
@maxwoo-houzz Yep, I understand your considerations – my suggestions are clearly workarounds. However I'm not aware of any approach that would work out of the box.

The main issue is that the components that should receive fresh props aren't even in the virtual DOM anymore, therefore they can't receive any props. Consider this:

```js
<AnimatePresence>
  {someCondition && <SomeComponent prop={foo} />
</AnimatePresence>
```

If you render with `someCondition: false`, the tree will effectively look like this:
```js
<AnimatePresence>
  {false}
</AnimatePresence>
```

How should the unmounted instance of `SomeComponent` be able to know the current value of `prop`? Neither it nor `AnimatePresence` knows it's value.

I think there's just no sensible way React or Framer Motion could know which props you want to pass to `<SomeComponent />`. I think the React team [is aware of this](https://twitter.com/dan_abramov/status/1184768140040982528), but there's no good solution at this point.

I think there might also be use cases where you don't want props to update within an unmounting component, as it can interfere with the unmount animation.

I guess for now if you want this behaviour, you have to utilize a workaround. The general purpose solution might be to use context for all props within the unmounting component that you want to be updated. See [this Code Sandbox](https://codesandbox.io/s/framer-motion-animate-presence-unmount-g9xhx) for an attempt at this.

The gist is:

```js
<AnimatePresenceProps.Provider props={{ time, isVisible }}>
  <AnimatePresence>
    {isVisible && (
      <AnimatePresenceProps.Child>
        {({ time, isVisible }) => (
          <motion.div>
            animate presence {!isVisible && 'hidden'} {time}
          </motion.div>
        )}
      </AnimatePresenceProps.Child>
    )}
  </AnimatePresence>
</AnimatePresenceProps.Provider>
```

By using a render prop, you can read the updated values without having to create another wrapper.

This is the utility code:

```js
import React, { createContext, useContext } from "react";

const AnimatePresenceContext = createContext();

function AnimatePresencePropsProvider({ children, props }) {
  return (
    <AnimatePresenceContext.Provider value={props}>
      {children}
    </AnimatePresenceContext.Provider>
  );
}

function AnimatePresencePropsChild({ children }) {
  const props = useContext(AnimatePresenceContext);
  return children(props);
}

export default {
  Provider: AnimatePresencePropsProvider,
  Child: AnimatePresencePropsChild
};
```

I think what's good about this solution, is that it allows you to intentionally decide which props you want to update during unmount and which can become stale, possible preventing a jittery animation.

Maybe that works for your use case?

**Comment by seba1342** [comment]
I know I'm late to the party here (hopefully this may help someone else). 

The `usePresence` hook can help you achieve this. By calling it like this:
```
const [isPresent] = usePresence();
```
You now know when your component has been removed from the DOM, and rather than using the `isVisible` prop which would otherwise be set to false at this point, the `isPresent` value from the hook will update at the point you want it to.

So your components would now look like this:
```
export const MyComponent = ({ isVisible }) => {
  const [isPresent] = usePresence();
  const variant = isPresent ? { opacity: 1 } : { opacity: 0 };
  return (
    <motion.div
      className="container"
      key="container"
      animate={variant}
      transition={{ duration: 2 }}
    >
      <div>{`regular animate${isPresent ? "" : " hidden"}`}</div>
    </motion.div>
  );
};
```

**Comment by InventingWithMonster** [comment]
It's important to note that if you use usePresence you have to call its second return value, `safeToRemove`, before the component will be removed. I am thinking about making this optional.

**Comment by seba1342** [comment]
@InventingWithMonster ah, thank you for the headsup!
Would be a nice feature to default it to run on `!isPresent`, but no sweat off my back to add that `useEffect()` you have in the docs.

---

That means the above code should look something like this:
```
export const MyComponent = ({ isVisible }) => {
  const [isPresent, safeToRemove] = usePresence();
  const variant = isPresent ? { opacity: 1 } : { opacity: 0 };

  useEffect(() => {
    if (!isPresent) safeToRemove();
  }, [isPresent]);

  return (
    <motion.div
      className="container"
      key="container"
      animate={variant}
      transition={{ duration: 2 }}
    >
      <div>{`regular animate${isPresent ? "" : " hidden"}`}</div>
    </motion.div>
  );
};
```
