### ISSUE TITLE
Prevent props from passing through to DOM elements

### ISSUE THREAD

**Issue by alxsavard** [framer/motion#272]
**Describe the bug**
When I use framer-motion with styled-components, I need to pass some extra props to my components to style them. Then, styled-component will pass those props along to the framer component that will pass them along to the DOM element. Then React complains because it does not recognize camelCase. 

It shows a warning in the console: 
```
Warning: React does not recognize the `someCamelCaseProp` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

Of course it's not a deal breaker, but the console gets awfully crowded with warnings after a while and it's a little bit annoying! 😬 

**To Reproduce**
See the sandbox: https://codesandbox.io/s/framer-motion-simple-animation-si0i9?fontsize=14

**Expected behavior**
I would expect framer to not pass along the camelCase props I guess? Like styled-components do. 

Thanks for the good work! Loving framer so far!

**Comment by InventingWithMonster** [comment]
I think the issue here is Styled Components doesn't understand that this isn't a valid prop because we're passing it a custom prop - it doesn't know there's just a `div` underneath. We do have a function that filters out invalid props so I'll take a look at what's going wrong.

**Comment by InventingWithMonster** [comment]
Edit: Ah the problem is we only strip out props we know to be erroneous. This was an attempt to improve performance and reduce filesize. I'd like to fix this without reintroducing Emotion's isvalidprop.

**Comment by InventingWithMonster** [comment]
Fixed in `1.6.6`

**Comment by mattbrannon** [comment]
@mattgperry Maybe I'm doing something wrong but I'm having this same issue with the current versions of framer-motion and styled-components. I was unable to reproduce in CodeSandBox but I made a public repository that shows the issue [here](https://github.com/mattbrannon/motion-console-warning). 

The exact message I get is - `Warning: React does not recognize the someProps prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase someprops instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

**Comment by tom2strobl** [comment]
> @mattgperry Maybe I'm doing something wrong but I'm having this same issue with the current versions of framer-motion and styled-components. I was unable to reproduce in CodeSandBox but I made a public repository that shows the issue [here](https://github.com/mattbrannon/motion-console-warning).
> 
> The exact message I get is - `Warning: React does not recognize the someProps prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase someprops instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

I have the same issue after updating `framer-motion` from `4.1.17` to `5.5.5` and I'm 99% sure I didn't touch the code that now throws a warning like the one above. I'm also using `styled-components` if that helps.

**Comment by Simba14** [comment]
I'm also running into the same issue using the latest framer-motion and styled components
