### ISSUE TITLE
initial animation only fires on first page

### ISSUE THREAD

**Issue by bpurtz** [framer/motion#273]
I am making a router with react router that animates between routes. I am having a hard time having the initial animation fire consistently. It always fires on the first page, and going back to the first page, but it will not animate anything else. Going to the second page, the exit animation fires, but the initial animation of the incoming page is not taking affect. The weird thing is that when I make the initial animation a function, and then do logs, it does fire. But they do not visually take affect. Any ideas on how this could happen?

**Comment by bpurtz** [comment]
I have gained more information on this. If I set initial="exit", then the initial animation fires, but when I do something like initial="preEnter", and define initial and exit and something different, the initial animation does not fire.

**Comment by InventingWithMonster** [comment]
Can I get a codesandbox link to take a look? Thanks

**Comment by bpurtz** [comment]
I believe I posted this prematurely and my issue is elsewhere. @InventingWithMonster thank you for responding, but I will close this for now and reopen it when I have defined my problem better.
