### ISSUE TITLE
[BUG] AnimatePresence does not guarantee that the item will exit/unmount

### ISSUE THREAD

**Issue by vanula** [framer/motion#2745]
**1. Read the [FAQs](#faqs) 👇**
✅

**2. Describe the bug**
When there is a quick exchange of blocks.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/p/sandbox/framer-motion-animatepresence-quick-exchange-of-blocks-bug-d3dfgc

**4. Steps to reproduce**

1. Open the reproduction
2. Click several times quickly on the toggle button(the time between clicks should be less than the time, for which the blocks change)
3. Sometimes you should see jumps

**5. Expected behavior**

After all the animations, only one block should remain visible.

**6. Video or screenshots**
https://github.com/user-attachments/assets/fc9a2d95-36d8-486c-b7ae-244cf3952653

**7. Environment details**
- "react": "18.0.0",
- "framer-motion": "11.3.17"
- "ubuntu": "20.04.6 LTS"
- "chrome": "126.0.6478.126 (Official Build) (64-bit)"

P.S. With framer-motion version 10 bug has not reproduce.

**Comment by ziloen** [comment]
Have you tried version 10.3.19? This issue should be fixed in version 10.3.18.

**Comment by vanula** [comment]
@ziloen Yes, with version 11.3.18 the problem is gone, thanks!

**Comment by vanula** [comment]
@ziloen Yes, with version 11.3.18 the problem is gone, thanks!
