### ISSUE TITLE
[BUG] AnimatePresence does not work under certain conditions

### ISSUE THREAD

**Issue by jamesplease** [framer/motion#276]
**Describe the bug**

I expect `AnimatePresence` to use the `exit` prop to animate a motion component when it unmounts. Most of the time it does this, but you can configure a series of props that breaks that functionality.

What happens instead is that you try to unmount the components but they do not animate to `exit` and instead stay mounted indefinitely.

**To Reproduce**

1. You must be using animation controls on the component
2. You must have `variants` defined on the component
3. You must have an `initial` prop set on the component and it must be a variant string

This combination of factors will break `AnimationControls`.

- If you remove `initial`, then the problem does not occur
- If you define `initial` using an animate object, then the problem also does not occur

[**View an isolated CodeSandbox here**](https://codesandbox.io/s/broken-animate-presence-z1j78)

To give myself some confidence that I actually understood AnimationControls, I made another CodeSandbox that has some functioning versions of this Box component, too. You can see that [here](https://codesandbox.io/s/gifted-gould-fic4o).

**Expected behavior**

I would expect `AnimatePresence` to work even when the above 3 conditions are met.

**Desktop (please complete the following information):**
 - OS: macOs 
 - Browser: Chrome
 - Version: 75

**Additional context**
I can try and dig into the code more to learn what's happening here, but it might take me some time to get an understanding of how AnimationControls works under-the-hood.

**Comment by InventingWithMonster** [comment]
We just ran into this too! Animate controls aren’t properly supported with
exit yet, I’ve been holding off on tackling it. There’s either the scenario
where it accepts props/variant labels and we just pass that to any existing
controls. Or it could be a function that’s provided the controls and
returns a promise that resolves once the animation is complete. This might
be better for
More intricate series of animations but it might also not work as expected
as exiting components don’t receive the latest props from React (as they’ve
been deleted from the tree already)

**Comment by jamesplease** [comment]
I might have some time to look more into this over the next few days. In the meantime, I plan to write a resolver that reduces a variants list to an animate object as a workaround. That way I can still organize my animations using variants without running into this issue.

i.e.;

```js
const variants = {
  open: { ... },
  closed: { ... },
  big: { ... },
  small: { ... }
};

const initial = resolveVariants(variants, ['open', 'big']);
// => {
//   x: 200,
//   y: 100,
//   opacity: 1
// }

return (
  <motion.div animate={controls} initial={initial} />
);
```

Obviously this comes with some limitations regarding what can be animated, but I think it'll work for my current use case.

**Comment by jamesplease** [comment]
> Or it could be a function that’s provided the controls and returns a promise that resolves once the animation is complete.

That's awesome that you all have been thinking about this as well! This is the specific feature I need for the use cases that I have, I think.

> More intricate series of animations but it might also not work as expected as exiting components don’t receive the latest props from React (as they’ve been deleted from the tree already)

I've thought about this as well. I had the idea to use refs to bypass this problem. Consider a hook that returns the ref. Although the hook won't be called after the component is unmounted from the perspective of React, if that hook returns a ref stored in context, and that ref is updated somewhere else, then presumably the unmounted component should be able to access the latest value of the ref within the exit callback.

It's a solution that's pretty specific to hooks, but it's the best solution I can think of for what I need to do. The tl;dr of my use case is route exit animations that are determined based on _where_ you're routing to.

Anyway, if there's anything I can do to help out with implementing this, let me know!

**Comment by InventingWithMonster** [comment]
I don't think there's any way to get around the ref thing considering that an unmounted component is never updated.

However I think you can already do route-specific exit animations by using dynamic variants and `AnimatePresence`'s `custom` prop. This will be passed to exiting components instead of their own `custom` prop (which can't be updated once they've been removed!)

```jsx
const variants = {
  exit: (nextRoute) => ({})
}

return (
  <AnimatePresence custom={nextRoute}>
  	<motion.div variants={variants} exit="exit" />
  </AnimatePresence>
)
```

**Comment by InventingWithMonster** [comment]
This will be fixed in `1.6.8` next week

**Comment by ymoon715** [comment]
is 1.6.8 released yet?

**Comment by jamesplease** [comment]
Yup! Also, you can view the latest versions of framer-motion on [the npm website](https://www.npmjs.com/package/framer-motion).

**Comment by aryankarim** [comment]
Idk if related, but my component did not start animating on mount. And it was been using in multiple places. So I added a unique ID now it works. Like so:

```tsx
const EntranceAnimation = ({ children, ...props }: PropsWithChildren) => {
  return (
    <motion.div
      key={Math.random()}
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
...etc

```
