### ISSUE TITLE
[BUG] will-change: opacity changes stacking context of elements

### ISSUE THREAD

**Issue by tim-richter** [framer/motion#2763]
**2. Describe the bug**

`will-change: opacity` is applied to elements, if `AnimatePresence initial={false}`, and it alters the appearance of svg's (and probably other elements as well)

According to MDN (https://developer.mozilla.org/en-US/docs/Web/CSS/will-change), the will-change property should not be used lightly and prematurely. I think it's probably fine to use in a lot of instances, but especially this paragraph is important for the behavior:

> Be aware, that will-change may actually influence the visual appearance of elements, when used with property values, that create a stacking context (e.g. will-change: opacity), as the stacking context is created up front.

So framer-motion actually introduced a breaking change in 11.3, because the appearance of all elements that use the property might change. I think it would be better to apply `will-change` only optionally, in cases where css animations are cleary slow to the user, and not generally for all elements that animate via css.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://stackblitz.com/edit/vitejs-vite-sgwdxh?file=src%2FButton.tsx

**4. Steps to reproduce**

1. Use `AnimatePresence` with `initial={false}`
2. Use any motion element as child (motion.span for example)
3. Animate the opacity
4. Check out the element in DevTools and see that `will-change: opacity` is set on the element
5. Notice weird things happening (element displays differently, svg elements are blurred etc.)

**5. Expected behavior**

Expected behavior would be to not see any visual regressions when using the combination above

**6. Video or screenshots**

It's probably hard to see via screenshare, but the blurry icon is very visible on the monitor and also screenshot tests:

[Kooha-2024-08-13-15-21-33.webm](https://github.com/user-attachments/assets/7ff7f0df-7330-4e68-a082-bbd253019cf3)

**7. Environment details**

NixOS, Chrome Browser Version 127.0.6533.88
Also happens in firefox

**Comment by mraballard** [comment]
@tim-richter i also noticed this issue affecting `motion.div` in my app (on chrome). i noticed dropdowns are stacking behind the motion.div due to the will-change opacity property. changing to a regular div fixes it.

**Comment by ValentinH** [comment]
We are also facing this issue after updating to the latest version. the `will-change` property used to be `auto` on all our `motion.div` and now it's is `opacity`. Therefore, it creates a new stacking context and all elements that were supposed to go outside of the div are now stuck inside it.

For now, we are adding `style={{ willChange: 'auto' }}` to all our `motion.div` but this doesn't feel right.

**Comment by zwily** [comment]
I have `will-change: transform` being set on elements when they have an exit animation that actually makes them positioned, causing havoc with descendants doing absolute positioning. This definitely needs to be rethought.

**Comment by ValentinH** [comment]
@mattgperry We just updated to `11.11.9` and removed all our `style={{ willChange: 'auto' }}` and the issue is still present 🤔 
It doesn't seem that all the breaking changes have been reverted.
I still see `will-change: opacity` or `will-change: transform, opacity` being applied on elements while it wasn't the case before.

**Comment by ynamite** [comment]
I agree, the issue persists even with 11.11.9

**Comment by AnYiEE** [comment]
Yes, the issue still exists in the latest version.

**Comment by AnYiEE** [comment]
v11.11.10 fixed this issue.

**Comment by tim-richter** [comment]
Can confirm the initial problem for this issue has been solved in 11.11.10.
