### ISSUE TITLE
[BUG] Drag contraints are not working properly when you try to use a useState hook in a drag function

### ISSUE THREAD

**Issue by mineshmshah** [framer/motion#277]
**Describe the bug**
When trying to set the state in the `onDragStart`, `onDrag` or `onDragEnd` then the drag constraints stop working.

**To Reproduce**
1. Create a component that uses a ref as a drag constraint
2. Add a setState function to the `onDragStart` or `onDrag` function
3. Try moving the component
4. The component will move outside of the drag constraints

Note: On the next move it will jump back inside the constraints error.

I experienced this on a refactored version of the example `dragConstraintsRef.tsx`.

My code was as follows:
```
import * as React from "react"
import { useRef, useState, useCallback } from "react"
import { motion } from "../../src"
import setPrototypeOf = Reflect.setPrototypeOf

const dragContainer = {
    width: "50%",
    height: "60vh",
    background: "#F30552",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "10px",
}


export const App = () => {
    const [value, setValue] = useState(false)
    const ref = useRef(null)

    const draggable = {
        width: 100,
        height: 100,
        background: "white",
        borderRadius: "10px",
    }

    return (
        <motion.div ref={ref} style={dragContainer}>
            <motion.div
                drag
                dragConstraints={ref}
                dragElastic={0.2}
                style={draggable}
                onDragStart={(event, info) => setValue(true)}
                onDragEnd={() => setValue(false)}
            />
        </motion.div>
    )
}
```

**Update** : 
Looking into the code I get the desired action if the following piece of code is commented out in the file `src/behaviours/use-drag.ts`.

```
    dragStatus.constraints = constraintsNeedResolution
        ? false
        : (dragConstraints as Constraints | false)
```

I think the `useState` hook causes the component to rerender and remove the constraints. As the `useEffect` hook is only called once on the first render it, won't rerun and pick up the drag constraints so that is why it is failing.

**Expected behavior**
The state should update through the motion and should not affect drag constraints.

**Screenshots**
AS you can see the shape is going outside of the bounds:

![Screen Shot 2019-08-10 at 12 47 09](https://user-images.githubusercontent.com/19519073/62821457-1afb0a80-bb6d-11e9-9b0e-1d56c2bfb87b.png)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Smartphone (please complete the following information):**
(Not tested)

**Comment by InventingWithMonster** [comment]
I believe this has been fixed since the PR was made. Please re-open if it's still broken for you in 1.6.5!

**Comment by craig-o-curtis** [comment]
I'm still having this same issue

**Comment by jayhxmo** [comment]
I'm still having this issue as well

**Comment by umereshaafi** [comment]
I am facing the same issue, when I resize the window to see the preview in mobile devices the dragConstraints become useless, can somebody help us out from this bug?

**Comment by fredriktre** [comment]
got the same problem as you umereshaafi... 
It just continues into oblivion

**Comment by CecoSvidovski** [comment]
Same problem here... I made a hook that tracks an element's width, offsetWidth etc. and set drag constraint using that hook (which updates the values on resize using event listener) and whenever I resize the windows the drag constraints are gone. The hook on the other hand works just fine and shows the current values every time.

**Comment by ajlamarc** [comment]
I can also replicate the issue - dragging blocked when not setting state, doesn't block when setting state.
