### ISSUE TITLE
[question] What are VariantLables used for?

### ISSUE THREAD

**Issue by tyler-mitchell** [framer/motion#280]
In the [documentation](https://www.framer.com/api/motion/types/#misc), there is a description for `VariantLabels`, but a use case would be helpful for better understanding.

**Comment by InventingWithMonster** [comment]
It might be clearer as `string | string[]`

```jsx
<motion.div variants={variants} animate={['active', 'hover']} />
```

**Comment by tyler-mitchell** [comment]
A little bit--is it just a way to combine different variants?

**Comment by InventingWithMonster** [comment]
Yeah exactly. Not all states are mutually exclusive so you want might something that is both active/inactive hovered/not hovered or similar
