### ISSUE TITLE
[BUG]Blurriness that occurs upon the completion of animation

### ISSUE THREAD

**Issue by axuj** [framer/motion#2816]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

#2811 Currently, there is blurriness that occurs upon animation completion in Chrome and Edge browsers..

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/p/devbox/dgs6kk?file=%2Fsrc%2FApp.tsx

**4. Steps to reproduce**

1. drag button
2. set willChange='auto'

**5. Expected behavior**

**6. Video or screenshots**

![image](https://github.com/user-attachments/assets/01bdbf16-01cf-4b41-8207-bc04d15fbebf)
**7. Environment details**

edge 129.0.2792.65   
chrome 129.0.6668.60

**Comment by AnYiEE** [comment]
It will also cause the background of the child element with `backdrop-filter: blur` added to not blur properly. You can check [this comment](https://github.com/nextui-org/nextui/issues/3817#issuecomment-2380897479). Similarly, the problem disappears after setting `will-change` to `auto` (that is, using version 11.5.6 and earlier).

**Comment by mraballard** [comment]
[fyi ](https://github.com/framer/motion/issues/2763#issuecomment-2386258633)
