### ISSUE TITLE
[BUG] Can't use className for example in motion.div component

### ISSUE THREAD

**Issue by FarzadMohtasham** [framer/motion#2843]
Describe the bug

Hi, I'm using framer-motion lib in my NextJS project, and recently I noticed that I can't use attribute className in motion.div components and of course in others like motion.span and so on...

![image](https://github.com/user-attachments/assets/21cb8025-bc99-4872-9dad-ca5d3bd16935)
![image](https://github.com/user-attachments/assets/73dc7498-9e70-48aa-b3bf-35963d02e234)
![image](https://github.com/user-attachments/assets/b8ecc871-ffeb-43ba-8920-266e894a5715)

Tools version:

react: v19.0.0-rc-69d4b800-20241021
next.js: v15.0.1
framer-motion: v11.11.9
clsx: v2.1.1
eslint: v9.13.0
eslint-config-next: v15.0.1

**Comment by Maginobion** [comment]
The version that supports React 19 is still on alpha
Try using framer-motion: 12.0.0-alpha.1

**Comment by FarzadMohtasham** [comment]
Thanks, Problem fixed.

**Comment by faradaytrs** [comment]
React 19 is now stable, i hope we can expect stable motion version for react 19 soon

**Comment by mattgperry** [comment]
With the majority of users still on 18, and 19's types being incompatible with 18, 19 support will be kept to its own release channel for a little way yet.

**Comment by faradaytrs** [comment]
> With the majority of users still on 18, and 19's types being incompatible with 18, 19 support will be kept to its own release channel for a little way yet.

it's fine if it will be like trpc, they have stable rc channel with new features support, they directly say it's stable and if you need just use it.

**Comment by mattgperry** [comment]
Ah I see - yeah it'll be like that. Honestly I'll need to look into it further - I wonder if there's a way of replacing the types of `motion.div` so it doesn't inherit from React at all. Ideally we could support both 18 and 19 on the same channel for a while.

**Comment by faradaytrs** [comment]
> Ah I see - yeah it'll be like that. Honestly I'll need to look into it further - I wonder if there's a way of replacing the types of `motion.div` so it doesn't inherit from React at all. Ideally we could support both 18 and 19 on the same channel for a while.

Well either way, we are currently blocked by https://github.com/motiondivision/motion/issues/2925 even on alpha, motion.create expects component to forwardRef

**Comment by eps1lon** [comment]
> With the majority of users still on 18, and 19's types being incompatible with 18, 19 support will be kept to its own release channel for a little way yet.

Most of the 19 changes should be backwards compatible with 18. What type changes are you referring to that aren't backwards compatible?

**Comment by mattgperry** [comment]
@eps1lon Mostly the HTML/SVG element types here https://github.com/motiondivision/motion/pull/2667/files#diff-2ca035457c4007d240d47c796d1300f1db6e79bf46d7a6a613b86ac5342cc3a5L54

**Comment by eps1lon** [comment]
> @eps1lon Mostly the HTML/SVG element types here [#2667 (files)](https://github.com/motiondivision/motion/pull/2667/files#diff-2ca035457c4007d240d47c796d1300f1db6e79bf46d7a6a613b86ac5342cc3a5L54)

Yeah that makes sense. Breakages to `createFactory` shouldn't be too surprising at this point.

**Comment by OkojieC** [comment]
Upgrading to 11.14.4 fixes this problem for me.

**Comment by Kashif-Ur-Rahman** [comment]
@Maginobion  Thank's problem has been solved.

**Comment by iamevansobeng** [comment]
`"framer-motion": "^11.18.2" ` worked for me

**Comment by hitesh-c** [comment]
Thanks, Facing same error
