### ISSUE TITLE
AnimatePresence - exit not happening

### ISSUE THREAD

**Issue by timscott** [framer/motion#289]
**Describe the bug**
`exit` animation not happening with `AnimatePresence`.

**To Reproduce**

The following is my code (redacted):
```react
{list.map(item => (
  <AnimatePresence>
    <motion.div
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      exit={{opacity: 0}}
    >
      <MyComponent
        key={item.id}
        item={item}
      />
    </motion.div>
  </AnimatePresence>
))}
```

This is pretty much exactly like the example found here: https://www.framer.com/api/motion/examples/#exit-animations 

**Expected behavior**

I expect `MyComponent` to fade out when it's `item` is removed from `list`.  It does not. It just disappears.

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6
 - Browser Chrome
 - Version 76.0.3809.100

**Comment by InventingWithMonster** [comment]
AnimatePresence should wrap the list otherwise it gets unmounted along with the item.

**Comment by timscott** [comment]
@InventingWithMonster - I revised to be:

```react
<AnimatePresence>
  {list.map(item => (
    <motion.div
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      exit={{opacity: 0}}
    >
      <MyComponent
        key={item.id}
        item={item}
      />
    </motion.div>
  ))}
</AnimatePresence>
```

And the behavior is the same. No `exit` animation.

**Comment by timscott** [comment]
Oops, I neglected to the move the key from `MyComponent` to `motion.div`. That fixed it.

**Comment by coolansplanet** [comment]
In my case it doesn't work on exit with React Router:

```
import React from "react";
import { BrowserRouter, Route, NavLink } from "react-router-dom";
import { AnimatePresence, motion } from "framer-motion";
import Hi from "./Hi";
import Something from "./Something";
import "./App.css";

const App = () => {
  return (
    <BrowserRouter>
      <AnimatePresence>
        <NavLink to="/">Hi</NavLink>
        <br />
        <NavLink to="/something">Something</NavLink>
        <hr />
        <Route path="/" exact={true} key="1">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 2 }}
            key="hi"
          >
            <Hi />
          </motion.div>
        </Route>
        <Route path="/something" exact={true} key="2">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            key="something"
            transition={{ duration: 2 }}
          >
            <Something />
          </motion.div>
        </Route>
      </AnimatePresence>
    </BrowserRouter>
  );
};

export default App;
```

**Comment by InventingWithMonster** [comment]
@coolansplanet In this example no components are being added or removed from the tree

**Comment by hoagy-davis-digges** [comment]
Would you be able to elaborate on that point? I'm not clear why the motion.div elements are not being removed from the tree when the route which is visible changes

**Comment by parthikrb** [comment]
exit animation will work only when the immediate child of <AnimatePresence> is getting unmounted

**Comment by Mahdi-Soultana** [comment]
Hello everyone please help or point me to any resources i searched around the web to solve how can make animation presence work between pages in next i tested all the solution but not working  please help >_<

**Comment by laneschmidt** [comment]
Hello friends, just started learning this today and love it so far. hoping there was some help available!

Sharing some redacted code below. My exit animations also aren't working as expected. 

Here is my custom Toast implementation `Toast.tsx`:

```
<ToastPrimitive.Provider
      swipeDirection="right"
      label={label ?? 'Toast notification'}
    >
      <ToastPrimitive.Root
        {...props}
        ...many props here...
      >
        <motion.div
          layout
          initial={{ x: 333, opacity: 1 }}
          animate={{ x: 0 }}
          exit={{
            opacity: 0,
            zIndex: -1,
            height: 0,
            width: 0,
            transition: {
              opacity: {
                duration: 0.3,
              },
            },
          }}
          transition={{
            type: 'spring',
            mass: 1,
            damping: 33,
            stiffness: 222,
          }}
          key={id}
        >
          ...many components here...
        </motion.div>
      </ToastPrimitive.Root>
      <ToastPrimitive.Viewport className={toastViewport()} />
    </ToastPrimitive.Provider>
```

Here's where the component(s) actually get rendered:

```
const ToastContainer = ({ toasts, onDismissToast }: ToastContainerProps) => {
  return createPortal(
    <AnimatePresence>
      {toasts.map(({ id, ariaLabel, ...args }) => (
        <ToastComponent
          key={id}
          id={id}
          aria-label={ariaLabel}
          onOpenChange={() => onDismissToast(id)}
          {...args}
        />
      ))}
    </AnimatePresence>,
    document.body,
  ) as ReactNode;
};
```

Initial animations work really nice but it just drops off the page after the duration, no exit animations.

Had a couple theories:

- maybe `createPortal` is causing something to happen?
- I found another similar implementation: https://buildui.com/recipes/animated-toast
  - key difference between this one and mine is that mine wraps `ToastPrimitive.Provider` with `AnimatePresence`, whereas theirs has the provider outside of `AnimatePresence`. I tried doing something similar but that meant having to use `AnimatePresence` within the Toast component itself (`Toast.tsx` above), which would also break it, so I don't think that's the cause of the issue.
