### ISSUE TITLE
[BUG] motion.custom should accept type parameters

### ISSUE THREAD

**Issue by iamkevinwolf** [framer/motion#290]
The `motion.custom` component should accept type parameters for passing the custom component props.

Having the following base component:

```tsx
import styled from '@emotion/styled'
import * as system from 'styled-system'

export type BoxProps = system.BackgroundColorProps &
  system.BorderProps &
  system.FlexboxProps &
  system.LayoutProps &
  system.OpacityProps &
  system.SpaceProps

export default styled.div<BoxProps>`
  ${system.compose(
    system.border,
    system.color,
    system.flexbox,
    system.layout,
    system.space
  )};

  box-sizing: border-box;
`
```

Wrapping the custom component with `motion.custom`:
```tsx
import Box from 'components/box'

const Container = motion.custom(Box)
```

And using the motion wrapped component passing my custom component original props:

```tsx
<Container
  minHeight={viewportHeight}
  display="flex"
  flexDirection="column"
  alignItems="center"
  justifyContent="center"
  opacity={viewportHeight === 0 ? 0 : 1}
  p={2}
>
  Test
</Container>
```

Gives the following TypeScript error:
```
Type '{ children: (string | number | boolean | {} | ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<...>)> | ... 4 more ... | undefined)[]; ... 6 more ...; p: number; }' is not assignable to type 'IntrinsicAttributes & MotionProps & RefAttributes<Element>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & MotionProps & RefAttributes<Element>'.ts(2322)
```

So my solution is to just accept a generic type parameter in `motion.custom` to avoid this errors:

```tsx
import Box, { BoxProps } from 'components/box'

const Container = motion.custom<BoxProps>(Box)
```

**Comment by petecorreia-appital** [comment]
Ran into this issue too and I believe a good fix could be:

```ts
// framer-motion.d.ts — line: 1953

custom: <Props = {}>(Component: ComponentType<Props>) => ForwardRefExoticComponent<MotionProps & RefAttributes<Element> & Omit<ComponentProps<typeof Component>, keyof MotionProps> & { children: ReactNode }>;
```

**Highlights**:
* Infers the props of the passed component
* Makes sure the motion prop definitions take precedence over the inferred props
* Adds children type

**This would need no further changes to the `motion.custom` API and would _just work_.**

---

In the meantime here's a utility function `animated` that implements it:

```ts
//
// Utility to create a type-safe motion.custom
//
// Example:
//
// const AnimatedBox = animated(Box)
//

export function animated<Props = {}>(Component: ComponentType<Props>) {
	return motion.custom(Component) as ForwardRefExoticComponent<
		MotionProps &
			RefAttributes<Element> &
			OmitMotionProps<ComponentProps<typeof Component>> & {
				children: ReactNode
			}
	>
}

type OmitMotionProps<Props> = Omit<Props, keyof MotionProps>
```

You can then wrap components easily and with type safety:
```ts
const AnimatedBox = animated(Box)

// the above will have both the MotionProps and the BoxProps
// the former takes precedence over the latter
```

/cc @henriquea

**Comment by petecorreia** [comment]
Ran into this issue too and I believe a good fix could be:

```ts
// framer-motion.d.ts — line: 1953

custom: <Props = {}>(Component: ComponentType<Props>) => ForwardRefExoticComponent<MotionProps & RefAttributes<Element> & Omit<ComponentProps<typeof Component>, keyof MotionProps> & { children: ReactNode }>;
```

**Highlights**:
* Infers the props of the passed component
* Makes sure the motion prop definitions take precedence over the inferred props
* Adds children type

**This would need no further changes to the `motion.custom` API and would _just work_.**

---

In the meantime here's a utility function `animated` that implements it:

```ts
//
// Utility to create a type-safe motion.custom
//
// Example:
//
// const AnimatedBox = animated(Box)
//

export function animated<Props = {}>(Component: ComponentType<Props>) {
	return motion.custom(Component) as ForwardRefExoticComponent<
		MotionProps &
			RefAttributes<Element> &
			OmitMotionProps<ComponentProps<typeof Component>> & {
				children: ReactNode
			}
	>
}

type OmitMotionProps<Props> = Omit<Props, keyof MotionProps>
```

You can then wrap components easily and with type safety:
```ts
const AnimatedBox = animated(Box)

// the above will have both the MotionProps and the BoxProps
// the former takes precedence over the latter
```

/cc @henriquea

**Comment by InventingWithMonster** [comment]
@petecorreia Thanks for taking a proper look at this and for the clear explanation. I'm going to take a stab at this along the lines you describe.

**Comment by oahmaro** [comment]
> ```ts
> //
> // Utility to create a type-safe motion.custom
> //
> // Example:
> //
> // const AnimatedBox = animated(Box)
> //
> 
> export function animated<Props = {}>(Component: ComponentType<Props>) {
> 	return motion.custom(Component) as ForwardRefExoticComponent<
> 		MotionProps &
> 			RefAttributes<Element> &
> 			OmitMotionProps<ComponentProps<typeof Component>> & {
> 				children: ReactNode
> 			}
> 	>
> }
> 
> type OmitMotionProps<Props> = Omit<Props, keyof MotionProps>
> ```

the utility function you shared isn't working for me, can you please share the full code
