### ISSUE TITLE
Slide animation with router

### ISSUE THREAD

**Issue by vBoykoGit** [framer/motion#291]
Hi, is it possible to implement slide animation, when existing page hides with new? The main idea is that the previous page is still visible with new over it.

Here is my code:
```
       <Route
        render={({ location }) => (
          <AnimatePresence>
            <Switch location={location} key={location.pathname}>
              <Route exact path="/account" component={Account} />
              <Route exact path="/details" component={Details} />
            </Switch>
          </AnimatePresence>
        )}
```

Example:
![image](https://user-images.githubusercontent.com/13284583/63591193-b604d300-c5b6-11e9-9b44-67b0bcc69eda.png)

**Comment by InventingWithMonster** [comment]
The above should work as long as both slides are positioned on top of one another?

**Comment by vBoykoGit** [comment]
> The above should work as long as both slides are positioned on top of one another?

I would say the image must be on top of those two slides.

**Comment by mattgperry** [comment]
I think your best bet would be to position the outgoing layer on the top and animate `clip-path` to animate it out.
