### ISSUE TITLE
Cannot vertically align adjacent paragraphs

### ISSUE THREAD

**Issue by maotora** [framer/motion#292]
Hello,

I don't know if I'm describing it correctly but I expect

```html
<p> Hello </p>
<p> world </p>
```

To display 

Hello
world

But with motion this;

```jsx

  const container = {
    default: { x: 200, opacity: 0},
    exit: { opacity: 0, y: 200 },
    animate: { x: 0, opacity: 1}
  }

  const p1 = {
    default: { opacity: 0, y: 50 },
    animate: { y: 0, opacity: 1, transition: {
      delay: .2
    }},
  }

  const p2 = {
    default: { opacity: 0, y: 50 },
    animate: { y: 100, opacity: 1, transition: {
      delay: .6
    }},
  }

//....
        <motion.div variants={container} initial="default" animate="animate">

          <motion.p variants={p1}> Hello </motion.p>

          <motion.p variants={p2}> world </motion.p>

        </motion.div>
```

Results to 

Hello world 

On one line, 🙄

I tried,

1. Setting display: block & inline-block;

2. Assigning each p element to 100% of the width.

both didn't work.

Help: How can I align them as normal paragraph elements?

**Comment by InventingWithMonster** [comment]
They are normal paragraph elements so this is odd. Can you open a Codesandbox example so I can take a look?

**Comment by maotora** [comment]
@InventingWithMonster Thanks man.

It actually works okay on [Codesandbox](https://codesandbox.io/s/practical-franklin-qq3o3?fontsize=14)

**Comment by InventingWithMonster** [comment]
You've probably tried but you can inspect the elements in Chrome to see if they're receiving some weird CSS from elsewhere in your stylesheet, might be the issue if it's working ok in Sandbox

**Comment by maotora** [comment]
Sure, it has to be something with my CSS.

I'll fix it no problem.
Thank you for your support man. :-)
