### ISSUE TITLE
`[DOC]` -  Incorrect package/import paths in `motion` guides

### ISSUE THREAD

**Issue by thommorais** [framer/motion#2920]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

On the page/anchor https://motion.dev/docs/react-lazy-motion#features 
`import * as m from "motion/m"` should be `import * as m from "motion/react"`

On the anchor https://motion.dev/docs/react-lazy-motion#async-loading
`import { domAnimations } from "framer-motion"` should be `import { domAnimation } from "motion/react"`

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
¯\_(ツ)_/¯

**Comment by evadecker** [comment]
Thank you for posting this issue! One addition:

`import * as m from "motion/m"` should be **`import { m } from "motion/react"`**

`m` is a named export and doesn't require importing the entire package using `* as m`. Took me awhile to figure this out. The docs are incorrect.

**Comment by mattgperry** [comment]
Thanks for the report- just publishing these changes now.

`import * as m from "motion/react-m"` and  `import { m } from "motion/react"` are technically the same, we only document the first though as its guaranteed to work with React Server Components.
