### ISSUE TITLE
[FEATURE] Bring SplitText from react-pose-text

### ISSUE THREAD

**Issue by EricVanDerDijs** [framer/motion#299]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem, but when I realized pose was deprecated, I have some animations made using SplitText from react-pose-text, and after going through your docs and repo I came to notice that nothing like SplitText had been ported to framer-motion

**Describe the solution you'd like**
Bring SplitText component or something similar to enable text animations using framer-motion API

**Describe alternatives you've considered**
I have already made SplitText component using the react-pose-text code. I'm currently using it in 
a project that uses framer-motion to do the animations, it exposes the SplitText component that uses the following props:

  - children: string -- the text to be animated
  - charVariants: Variants -- variants used to animate every char in the text
  - charMotionProps: MotionProps -- Any other motion-prop to be used by the chars animations
  - wordVariants: Variants -- variants used to animate every word in the text
  - wordMotionProps: MotionProps -- Any other motion-prop to be used by the words animations

chars are motion.divs which receive  the following custom object:
```
{
    wordIndex,
    numWords,
    charIndex,
    charInWordIndex,
    numChars,
    numCharsInWord,
}
```

words are motion.divs which receive  the following custom object:
```
{
    wordIndex,
    numWords,
}
```

I'm not very sure this is the best API, since a lot has changed since pose, but I do believe that this is a nice thing to have since SplitText does not exist on motion (or at least I was not able to find it).

**Comment by jakeranallo** [comment]
Is your SplitText component open source?

**Comment by EricVanDerDijs** [comment]
Well, it is licensed under GPLv3 ([here](https://github.com/Popmotion/popmotion/blob/master/packages/react-pose-text/LICENSE.md)), this is an adaptation of that packages to motion.

Also I found easier to just pass the config objects (**charMotionProps** and **wordMotionProps**), removing variants from the props.

**Comment by mattgperry** [comment]
Closing this out as I'm not going to get round to implementing this myself. It's totally possible for a third-party to do a version of SplitText with Motion though.
