### ISSUE TITLE
[FEATURE] Imperatively animate scroll position

### ISSUE THREAD

**Issue by amannn** [framer/motion#304]
**Is your feature request related to a problem? Please describe.**

I'm trying to use Framer Motion to scroll a DOM element with spring physics.

**Describe the solution you'd like**

I guess it should be possible somehow with `MotionValue`, but I wasn't sure how to trigger a spring animation.

This is the code I've tried:

```js
const scrollMotionValue = new MotionValue(scrollParent.scrollTop);
scrollMotionValue.onChange(value => {
  scrollParent.scrollTop = value;
});
scrollMotionValue.set(target);
```

This sets the value directly and it doesn't animate. I guess you'd have to use `attach` somehow? I couldn't quite figure it out.

**Describe alternatives you've considered**

I was able to get it to work with popmotion like this:

```js
spring({
  from: scrollParent.scrollTop,
  to: target,
  mass: 1,
  stiffness: 400,
  damping: 40
}).start({
  update(value) {
    scrollParent.scrollTop = value;
  }
});
```

I haven't used popmotion before and I'm not sure if that is entirely correct.

Thanks for your help!

**Comment by natew** [comment]
I believe you need to wrap it in a spring, in react-land like so:

```
const motion = useMotionValue(scrollParent.scrollTop);
const spring = useSpring(motion)

useEffect(() => {
  spring.onChange(value => scrollParent.scrollTop = value)
  scrollMotionValue.set(target)
}, [])
```

**Comment by amannn** [comment]
Hey @natew! Thanks, that seems to work. `motion.set` now animates using the spring.

However I also need a way to immediately set the motion value to a new value. The use case is that I always want to start from the current scroll position. I mean I could add a scroll event listener, which syncs the value back into the motion value, but then you'd end up in a strange chain between the scroll position and the motion value which syncs back and forth.

I couldn't find a function which does that. Calling `motion.stop()` before `motion.set()` doesn't seem to make a difference.

**Comment by eric-personal** [comment]
@natew how would you go about adding scrollParent.scrollTop when you don't have a reference to the scrollParent yet. For example.

const MyComponent = () => {
  const scrollParent = useRef(null);
   const motion = useMotionValue(scrollParent.current.scrollTop);
   const spring = useSpring(motion);
   const controls - useAnimation();

  return (
    <motion.div ref={scrollParent} animate={controls}>
      <div className='inner'></div>
    </motion.div>
  );
}

**Comment by scottmas** [comment]
I'm facing a similar problem. What would be ideal is an API similar to React Native's Animated API (if you're familiar) that lets devs set the motion value value either instantly or through an animation. Ideally, there would be an additional method expose on a MotionValue to trigger an animated transition to the new value like so: 

```
scrollMotionValue.setWithAnimation(100, {someConfig: true})
```

**Comment by bmcmahen** [comment]
You can try using `useAnimation` which accepts both a `start` and `set` method.

Having said that, it would be really nice if you could do the same for `motion` values which still support transforms / interpolation. Animations feel a bit like a black box.

**Comment by DoneDeal0** [comment]
Do you have a sandbox or any working exemple? I'm trying to migrate from react-spring to framer motion, and I need to imperatively scroll inside a virtualized list. 

I was doing:

```js
<Spring from={{ top: 0 }} to={{ top: lineHeight * (page.from - 1) }}>
          {(props) => (
            <List
              height={lineHeight * limit}
              rowCount={data.length}
              rowHeight={lineHeight}
              width={1}
              rowRenderer={row}
              style={{
                width: "100%",
                overflow: "hidden"
              }}
              scrollTop={props.top}
            />
          )}
        </Spring>
```

I don't see how to use useSpring or motionValue here.

**Comment by mattgperry** [comment]
There is now an `animate` function that you can use to imperatively animate anything.

```javascript
animate(scrollMotionValue, 100, {
  duration: 2
})

animate(0, 100, {
  duration: 2,
  onChange: v => window.scrollTop = v
})
```

@DoneDeal0 `motion` can animate `top`

```jsx
<motion.div animate={{ top: lineHeight * (page.from - 1) }} />
```

**Comment by justintemps** [comment]
@mattgperry the `onChange` method in your example should be `onUpdate`, right?

```
animate(0, 100, {
  duration: 2,
  onUpdate: v => window.scrollTop = v
})
```
