### ISSUE TITLE
Any way to slow down the steps of a transition?

### ISSUE THREAD

**Issue by rchrdnsh** [framer/motion#307]
Here's my code for a simple fade-out-and-in again transition using `framer-motion`:

```jsx
return (
    <AnimatePresence>
      <Container
        initial={{ opacity: 0 }}
        animate={{ opacity: 1, duration: 1 }}
        exit={{ opacity: 0, duration: 1,  }}
      >
        {children}
      </Container>
    </AnimatePresence>
  )
```
...with `<Container>` being a `styled(motion.main)` component. The transition works, but the duration parts don't seem to do anything, which is not what I want. Currently the transition is just too fast and looks like a FOUC, rather than a smooth fade between components. I would ideally like the fade out to last for `0.25 to 0.75` or something, then have the fade-in commence and last about the same amount of time. But no matter how long I set the durations on any of the pieces everything is always the same speed, which is just too dang fast, so it doesn't seem like it's working.

Any thoughts would be appreciated, thank you :-)

**Comment by msheakoski** [comment]
Duration should be inside of a transition object like this:
`animate={{ opacity: 1, transition: { duration: 1 }}}`

**Comment by rchrdnsh** [comment]
hmmm...that worked for everything except the exit animation...which occurs at the same speed, regardless of the value I set there.

```jsx
return (
    <AnimatePresence>
      <Container
        initial={{ opacity: 0, transition: { duration: 5, delay: 5 }}}
        animate={{ opacity: 1, transition: { duration: 5, delay: 5 }}}
        exit={{ opacity: 0, transition: { duration: 5 }}}
      >
        {children}
      </Container>
    </AnimatePresence>
  )
```

my exit animation transition duration is set a 5 seconds. but it still happens instantly, which is not what I want to happen. I want it to take 5 seconds, at least in this test. All of these values are not for the final app, but only for testing purposes.

**Comment by msheakoski** [comment]
Can you make a simple [CodeSandbox](https://codesandbox.io) example to demonstrate the issue? It might be a bug and will be helpful in fixing it.

**Comment by msheakoski** [comment]
@rchrdnsh I believe this is no longer an issue in the latest version, 1.6.9. Can you please confirm and close the issue if resolved?

**Comment by rchrdnsh** [comment]
Hi, I updated to the latest version, but the exit transition still does not seem to work...dunno at this point what to do to fix it...

**Comment by mattgperry** [comment]
I'm going to close this bu feel free to reopen with a sandbox.
