### ISSUE TITLE
[FEATURE] Offload spring calculation to wasm

### ISSUE THREAD

**Issue by natew** [framer/motion#308]
Keep in mind this is a wildly theoretical thing, I have no idea if it would even help performance. But in my tests when you get into some of the heavier animations that have sensitive requirements, I see some slowdowns that seem related to the spring update area. If I switch to duration-based, it seems to fix.

So one idea is offload some of that work to wasm. I recently ran across [this fork of react-spring](https://github.com/rexlabsio/react-spring-wasm/commit/f192a1c65065c6990aa9c9ab8b0823b04bc1eda5) which attempts to do as much so thought I'd just forward it here.

**Comment by natew** [comment]
This probably is much simpler and more effective, if I understand it. 

https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API

**Comment by mattgperry** [comment]
I would love to do this but it isn't going to happen in the near future for a few reasons. The WebAnimationsAPI is too limited and the Animation Worklet isn't fit for purpose https://mattperry.is/writing-code/animation-worklet-4-missing-features

In addition layout animations require a fair bit of control over the render loop and the ability to create tree structures which I don't believe will be possible with the Worklet.
