### ISSUE TITLE
[FEATURE] Allow drag to manipulate scroll

### ISSUE THREAD

**Issue by natew** [framer/motion#314]
So in my case it's actually a bit more complex than just attaching onDrag to a scrollable node and then having it change scroll, as I'd like to attach the onDrag to a *child element* of the scrollable node and have it scroll the parent. Both cases seem useful.

For the first case it could have some nice syntax:

```tsx
<motion.div drag="scroll" />
```

But for the second I think I'd prefer to just manually wire the scroll to the parent, and then have the ability to "prevent" the drag from applying to itself and instead send it up:

```tsx
const ref = useRef(null)

<motion.div ref={ref} style={{ flexFlow: 'row', overflowX: 'scroll' }}>
  <motion.div drag="x" onDrag={(event, pan) => {
      pan.preventDefault() // have this prevent the animation
      ref.current.scrollLeft += pan.offset // something like that
   }} />
</motion.div>
```

**Comment by hmbrg** [comment]
`pan.preventDefault()` doesn't seem to exist anymore. Is there anyway to achieve the same functionality?

**Comment by mattgperry** [comment]
Closing this as scroll has very different abilities compared to what we're allowed to do with transforms. We wouldn't be able to support all the features in the same way. The `Scroll` component in Framer is wired up like this - we apply drag to scroll and only apply out-of-bounds motion to transforms. But it's caused us problems and isn't something I'd like to ship in a public API.
