### ISSUE TITLE
[FEATURE] CSS will-change property

### ISSUE THREAD

**Issue by pushkine** [framer/motion#317]
I was just wondering what is Framer's team stance on the CSS 'will-change' property, I've only seen you use it on opacity with static sheets and I assume you'd already have added it to motion components dynamically if you didn't think it were useless ?

**Comment by samdenty** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/will-change
> will-change is intended to be used as a last resort, in order to try to deal with existing performance problems. It should not be used to anticipate performance problems.

**Comment by samdenty** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/will-change
> will-change is intended to be used as a last resort, in order to try to deal with existing performance problems. It should not be used to anticipate performance problems.

**Comment by mtrelis** [comment]
> > will-change is intended to be used as a last resort, in order to try to deal with existing performance problems. It should not be used to anticipate performance problems.

Google webdev docs recommend it on many articles, here is one : 

https://developers.google.com/web/fundamentals/performance/rendering/stick-to-compositor-only-properties-and-manage-layer-count

> As we mentioned in the “Simplify paint complexity and reduce paint areas” section, you should promote elements that you plan to animate (within reason, don’t overdo it!) to their own layer
