### ISSUE TITLE
[BUG] Scaling motion.text on iOS stops at initial state

### ISSUE THREAD

**Issue by programbo** [framer/motion#318]
On iOS browsers, scaling a `motion.text` element also scales its `x` an `y` coordinates (I am not sure if this is also a bug) and then does not progress past its initial state. Works almost as expected on macOS desktop browsers.

See https://codesandbox.io/s/ios-motiontext-bug-5qvc3

## Expected behaviour

Scale the text from `0` to `1` in the centre of the window:

![text-scaling](https://user-images.githubusercontent.com/1026196/64485644-865ff700-d255-11e9-9be3-9de24558ce44.gif)

Works on desktop, with the exception of this anomaly:

![pre-initial](https://user-images.githubusercontent.com/1026196/64485912-cd032080-d258-11e9-927e-cc945fbb36c0.png)

## Actual behaviour

![ios-simulator](https://user-images.githubusercontent.com/1026196/64485776-371ac600-d257-11e9-8d99-30a68882b86d.png)

The broken behaviour appears in Safari, Chrome, and Firefox on iOS 12. The animation completes on Safari, Chrome, and Firefox on macOS 10.14.

**Comment by InventingWithMonster** [comment]
This seems to be a bug in WebKit on iOS where CSS transforms don't apply to `text` elements. Closing this as there's nothing we can do about this :(

**Comment by lloydrichards** [comment]
This bug is still an issue or has resurfaced:

[Same Sandbox but updated to latest](https://codesandbox.io/s/motion-text-bug-on-safari-xp6hu7)

If you open the sandbox in Chrome and Safari you will see different loading animations :/
