### ISSUE TITLE
[FEATURE] Return variant name from `modifyTarget`

### ISSUE THREAD

**Issue by amannn** [framer/motion#320]
**Is your feature request related to a problem? Please describe.**

I'm building a bottom sheet as shown in this [CodeSandbox](https://codesandbox.io/s/framer-motion-bottom-sheet-problem-q416h). You can toggle it by pressing a button, but the user should also be able to close it by dragging it down.

When the user stops dragging I need to decide if the bottom sheet should close or if it should animate back to the open position. It's kind of a snapping situation.

Based on the docs I expected I can utilise `modifyTarget` to snap the bottom sheet back open when the user hasn't dragged it far enough.

However there are two problems here:
1. `modifyTarget` seems to only be called when the user releases the element with some velocity (bug?).
2. `modifyTarget` can only return numbers. Since I'm working with variants, it would be very helpful if I could directly return the closed variant name (feature).

**Describe the solution you'd like**

An API like this would be very helpful:

```
function modifyTarget(target, info) {
  return target > 0 ? 'hidden' : 'visible';
}
```

**Describe alternatives you've considered**

I got it working in [another CodeSandbox](https://codesandbox.io/s/framer-motion-bottom-sheet-fixed-m2vls) with external animation controls and `useEffect`.

I really like that it's very easy to iteratively add features to motion components, but the use case of snapping the bottom sheet back open made it necessary for me to switch from the declarative to the imperative API.

Not sure if there's a better way?

**Comment by mattgperry** [comment]
`modifyTarget` is really an exposed `popmotion` API, it wouldn't be possible to mix with variants. I think the `onDragEnd` callback is necessary for more complex stuff.

**Comment by amannn** [comment]
@mattgperry Thank you for the reply, using `onDragEnd` sounds good to me.

However I noticed [my CodeSandbox example](https://codesandbox.io/s/framer-motion-bottom-sheet-fixed-m2vls?file=/src/index.js) doesn't work anymore since Framer Motion v2.

Here's a work-in-progress version with the latest Framer Motion: https://codesandbox.io/s/framer-motion-bottom-sheet-fixed-latest-ym8bk?file=/src/index.js. It seems like as soon as you add the `drag="y"` prop in L34 neither the toggle button nor the dragging works anymore.

I couldn't find a workaround how to get this working again. Is this a bug or do you have any pointers? Thanks!
