### ISSUE TITLE
Support Custom Tags with Styled Components

### ISSUE THREAD

**Issue by pmualaba** [framer/motion#321]
**Is your feature request related to a problem? Please describe.**
When I use framer-motion together with styled-components, framer-motion does not recognize the custom tags which can be created with styled-components: i.e. `styled('element')`` will create a <element> tag in the DOM instead of a div `styled('div')``
 

**Describe the solution you'd like**
I would like to do the same with framer-motion: `styled('motion.element')``

**Describe alternatives you've considered**
There is currently no way tot

**Additional context**
`styled('motion.div')``  works :-)
`styled('motion.element')`` does not work :-(

**Comment by InventingWithMonster** [comment]
This coincides with a bundle-reduction measure I'd like to take, which is migrating from a list of elements to a `Proxy`.

**Comment by InventingWithMonster** [comment]
Actually if you're using plain JS you can do `motion.custom('element')`. I'm making a PR that updates the types to support this.

**Comment by pmualaba** [comment]
![image](https://user-images.githubusercontent.com/1754718/66560811-71c69580-eb58-11e9-841d-2e102aef8a8e.png)

This still renders as HTML <div> in the DOM, not as <global> Custom Tag ?
![image](https://user-images.githubusercontent.com/1754718/66560972-cf5ae200-eb58-11e9-8394-9d73911f76ea.png)

**Comment by InventingWithMonster** [comment]
Have you registered `'global'` as a custom element https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

**Comment by InventingWithMonster** [comment]
I tested 

```jsx
export const App = () => {
    const CustomComponent = motion.custom("global")

    return (
        <CustomComponent
            data-testid="custom-element"
            style={{ width: 100, height: 100, background: "red" }}
        />
    )
}

```

Even without registering that as an element and it worked. What browser are you in?

**Comment by pmualaba** [comment]
Hello, Thanks for taking al look at this. Indeed it works when using it without the styled() function.
so `motion.custom('global')` renders a `<global>` tag in the DOM, but `styled(motion.custom('global'))` does not.  

When I use `styled('global')` though it also renders a `<global>` tag in the DOM. 
So rendering a **styled** custom element works, rendering a **motion** custom element works, 
But rendering a **styled motion** custom element does not seem to work.

**Comment by InventingWithMonster** [comment]
Interesting thanks for the update. I'm gonna publish this types fix for custom tags and reopen this issue as Styled Components-specific

**Comment by InventingWithMonster** [comment]
@pmualaba I've just realised `global` actually isn't a valid custom element name (they have to include a hyphen). That doesn't seem to be a problem here though. I tried this:

```
const CustomComponent = styled(motion.custom("test-component"))``

export const App = () => {
    return (
        <CustomComponent
            style={{ width: 100, height: 100, background: "red" }}
        />
    )
}

```

And it correctly rendered a `test-component` element. Can you provide a CodeSandbox reproduction of the issue?

**Comment by pmualaba** [comment]
Ok I tested it on CodeSandbox and it seems indeed that the framer-motion part works correctly, but the styles are not applied when a `custom-element` is provided.
So it is probably a styled-components issue...

[https://codesandbox.io/s/custom-tags-framer-motion-with-styled-components-wgg17](url)

**Comment by pmualaba** [comment]
I raised an issue over at styled-components for this:

https://github.com/styled-components/styled-components/issues/2802
