### ISSUE TITLE
[BUG] Click handlers don't fire inside draggable elements

### ISSUE THREAD

**Issue by amannn** [framer/motion#322]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

When you have a draggable motion element and you have clickable elements inside, the click handlers aren't called on iOS.

Note that they are called on Chrome on Android though.

**3. Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-derived-state-bug-p6q20

**4. Steps to reproduce**

1. Go to https://codesandbox.io/s/framer-motion-derived-state-bug-p6q20 on your iOS device.
2. Try to click on the button.

**5. Expected behavior**

The click handler fires.

**6. Video or screenshots**

N/A

**7. Environment details**

iOS Simulator on OSX running iPhone X on iOS 12.4.

**Comment by amannn** [comment]
I found a workaround though: You can use `onTouchEnd` on the button for iOS devices. `onTouchStart` has a pretty big delay.

**Comment by alampros** [comment]
The workaround doesn't help if you have multiple click targets within the drag component.

It would be nice to have a prop to bypass calling `preventDefault()`on the original event.

**Comment by amannn** [comment]
Seems to be this here: 

https://github.com/framer/motion/blob/fc6b328fb87e03a55f0ef6b1fdb2b6bac0977498/src/behaviours/use-drag.ts#L385-L391

Maybe we could only prevent default for desktop devices? We could test for touch devices and don't prevent default there …

I could submit a PR if the overall direction is ok.
