### ISSUE TITLE
Unable to sync setInterval() and motion animation[BUG]

### ISSUE THREAD

**Issue by FatehAK** [framer/motion#324]
**1. Describe the bug**
I am trying to dynamically modify the text using setInterval() and I am using framer-motion for the fadein and fadeout effect. The problem is setInterval() and the fade transitions are not syncing up properly leading to weird animations. Can you look into it help me solve this sync issue? 

**2. Provide a CodeSandbox reproduction of the bug**
[CodeSandbox](https://codesandbox.io/s/pose-sandbox-dufho?fontsize=14)

**3. Steps to reproduce**
Open the codesandbox link and view the issue

**4. Expected behavior**
setInterval() and transitions should be in sync

**5. Environment details**
Chrome v74, React v16.9, framer-motion 1.6.7

**Comment by InventingWithMonster** [comment]
Hey there

It's probably more trouble than its worth to do it like this. Personally I'd use `AnimatePresence`: https://codesandbox.io/s/pose-sandbox-bt9jt

**Comment by FatehAK** [comment]
Thanks didn't know about AnimatePresence. It seems to be a new feature.

**Comment by FatehAK** [comment]
Hey I'm getting this error when I leave the tab and switch back to it at a later time.

`Uncaught TypeError: Cannot read property 'onAnimationStart' of undefined
    at ValueAnimationControls.onStart (framer-motion.es.js:1758)
    at ValueAnimationControls.start (framer-motion.es.js:1597)
    at framer-motion.es.js:4362
    at commitHookEffectList (react-dom.development.js:21864)
    at commitPassiveHookEffects (react-dom.development.js:21897)
    at HTMLUnknownElement.callCallback (react-dom.development.js:363)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:412)
    at invokeGuardedCallback (react-dom.development.js:465)
    at flushPassiveEffectsImpl (react-dom.development.js:25316)
    at unstable_runWithPriority (scheduler.development.js:818)
    at runWithPriority$2 (react-dom.development.js:12259)
    at flushPassiveEffects (react-dom.development.js:25283)
    at react-dom.development.js:25162
    at workLoop (scheduler.development.js:762)
    at flushWork (scheduler.development.js:717)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:212)`

I would like your thoughts on this.

**Comment by InventingWithMonster** [comment]
Looks like a bug imo, I'll reopen this

**Comment by InventingWithMonster** [comment]
@FatehAK Can you try this again with `1.6.13`?

**Comment by FatehAK** [comment]
I went with this package for the time being [https://www.npmjs.com/package/react-animation](url). I have now tested it with framer seems to work fine. No issues so far.

**Comment by FatehAK** [comment]
Hi, I came across another issue. I have the motion component on the `Home` page. Now, when I switch to another page immediately I get this error -
`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in AnimatePresence (at Downloads.js:48)
    in header (at Downloads.js:46)
    in div (at Downloads.js:45)
    in section (at Downloads.js:44)
    in Downloads (at Hero.js:15)
    in div (at Hero.js:14)
    in div (at Hero.js:9)
    in section (at Hero.js:8)
    in Hero (at Home.js:24)
    in div (at Home.js:17)
    in Home (created by Context.Consumer)
console.<computed> @ index.js:1375`

Can you look in it?

**Comment by ndimatteo** [comment]
Came here to also say that I'm getting the above warning about adding a `useEffect` cleanup function, due to `AnimatePresence`. I'm also animating children in/out with a setInterval, and it seems that if Framer is in the middle of an animation when the component is removed this warning is thrown.

I'm out of ideas on how to address this since I DO have a cleanup function for my setInterval, but this warning persists and is pointing blame at Framer's `AnimatePresence` every time.

Any ideas on how we can resolve this?

**Comment by Sean-Wilson-Braille** [comment]
I know this is closed but I also get the same error:
`AcceleratedAnimation.mjs:195 Uncaught TypeError: Cannot destructure property 'animation' of 'this.resolved' as it is undefined.
    at AcceleratedAnimation.stop (AcceleratedAnimation.mjs:195:17)
    at MotionValue.stop (index.mjs:289:28)
    at eval (index.mjs:155:30)
    at Object.process (render-step.mjs:95:21)
    at processStep (batcher.mjs:33:23)
    at Array.forEach (<anonymous>)
    at processBatch (batcher.mjs:45:20)`

The sandbox linked [here also throws a similar error](https://codesandbox.io/p/sandbox/pose-sandbox-bt9jt?file=%2Fsrc%2Findex.js%3A29%2C30-29%2C37) which is:
`TypeError
Cannot read properties of undefined (reading 'onAnimationStart')
ValueAnimationControls.onStart
https://bt9jt.csb.app/node_modules/framer-motion/dist/framer-motion.es.js:1162:39
ValueAnimationControls.start
https://bt9jt.csb.app/node_modules/framer-motion/dist/framer-motion.es.js:1040:10
eval
https://bt9jt.csb.app/node_modules/framer-motion/dist/framer-motion.es.js:2750:31
commitHookEffectList
https://bt9jt.csb.app/node_modules/react-dom/cjs/react-dom.development.js:19986:26
commitPassiveHookEffects
https://bt9jt.csb.app/node_modules/react-dom/cjs/react-dom.development.js:20016:11
HTMLUnknownElement.callCallback
https://bt9jt.csb.app/node_modules/react-dom/cjs/react-dom.development.js:347:14
Object.invokeGuardedCallbackDev
https://bt9jt.csb.app/node_modules/react-dom/cjs/react-dom.development.js:397:16
invokeGuardedCallback
https://bt9jt.csb.app/node_modules/react-dom/cjs/react-dom.development.js:454:31
flushPassiveEffectsImpl
https://bt9jt.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22868:7
unstable_runWithPriority
https://bt9jt.csb.app/node_modules/scheduler/cjs/scheduler.development.js:643:12
runWithPriority$2
https://bt9jt.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11305:10
flushPassiveEffects
https://bt9jt.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22841:10
eval
https://bt9jt.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22419:7
scheduler_flushTaskAtPriority_Normal
https://bt9jt.csb.app/node_modules/scheduler/cjs/scheduler.development.js:436:10
flushTask
https://bt9jt.csb.app/node_modules/scheduler/cjs/scheduler.development.js:482:32
flushWork
https://bt9jt.csb.app/node_modules/scheduler/cjs/scheduler.development.js:607:11
MessagePort.performWorkUntilDeadline
https://bt9jt.csb.app/node_modules/scheduler/cjs/scheduler.development.js:231:30
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.`
