### ISSUE TITLE
[BUG] Cannot stop propagation to parent elements when using onTap with e.stopPropagation

### ISSUE THREAD

**Issue by mineshmshah** [framer/motion#325]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
I have nested components (the child also being a `drag` component). I want to be able to use `onTap` on both elements, but I do not want to trigger the parent's `onTap` action from the child.

Currently, if I pass the function `e.stopPropagation()` on the child's `onTap` function then the onTap function of the parent is still triggered.

Note: if `e.stopImmediatePropogation` is used then the `onTap` works correctly and does not propagate.

**3. Sandbox**
A sandbox is provided below:
https://codesandbox.io/s/gallant-burnell-enpc9

**4. Steps to reproduce**
The red element represents the child element and the blue element represents the parent

1. Click on the parent element and the console should say that the parent has been clicked.
2. Click on the child element and the console says that the child **and** the parent have been clicked

**5. Expected behavior**
When clicking the child component, `e.stopPropagation` should prevent the parent from being clicked. The child should only show that the child has been clicked in the console.

**6. Environment details**
All environments

**Comment by maps82** [comment]
It this case it seems to work if you use `stopImmediatePropagation` instead of `stopPropagation`

**Comment by InventingWithMonster** [comment]
Closing in favour of https://github.com/framer/motion/issues/363 as there's an in-depth discussion on that ticket.
