### ISSUE TITLE
How to animate SVG circle position?

### ISSUE THREAD

**Issue by paolostyle** [framer/motion#333]
Hello, first of all thanks a lot for this library, it's pretty awesome.

I have encountered an issue related to animating `<circle>` element. If it was an HTML element I would use `positionTransition` prop, but TypeScript complains there's no such prop on `motion.circle`. I'm currently using 
```
<motion.circle
   cx={cx}
   cy={cy}
   animate={{ cx: cx as number, cy: cy as number }}
/>
```
and it seems like it works, but I'm seeing warnings in console like: `You are trying to animate cx from "-238.6925795053004" to -238.6925795053004. "-238.6925795053004" is not an animatable value - to enable this animation set -238.6925795053004 to a value animatable to -238.6925795053004 via the `style` property.` and I'm not sure how to handle that - using `style={{ cx, cy }}` does not work. I'd also rather not use type assertion in animate if that is the correct way to do that - the parent component of `<motion.circle>` extends `React.ComponentPropsWithoutRef<typeof motion.circle>` so I'm not sure why it doesn't work out of the box. Unfortunately I couldn't find anything in docs related to this issue.

Thanks in advance for your help.

edit: actually this warning only happens once, on initial render. On subsequent position changes it does not show up.

**Comment by InventingWithMonster** [comment]
Hi there

positionTransition only works with HTML elements, hence that error.

It looks like a bug where we're reading the initial value as a string, I'm not sure why this is. Rather than style can you try `initial`?

**Comment by paolostyle** [comment]
Sorry for late response - yes, setting them in `initial` helped. Thanks a lot!
