### ISSUE TITLE
[FEATURE] transitionStart

### ISSUE THREAD

**Issue by pushkine** [framer/motion#340]
**Is your feature request related to a problem? Please describe.**
Applying styling synchronously at start requires 'workarounds', transitionStart would facilitate the process.

**Describe the solution you'd like**
Like transitionEnd but at start

**Describe alternatives you've considered**
AFAIK the two main ways to do it are to either make a animation controller & call set() on it, or to specify a 'from' property to each styling prop in the transition property, the problem with the former is that I worry the library might not be able to optimize performance as much as it could if it knew what it had to do in advance, the problem with the latter is that some styling props have to be declared twice as one's transition is ignored if it's not animated to begin with

**Comment by InventingWithMonster** [comment]
What exactly are you trying to do? Could I take a look at a code example? You can `animate` non-animatable values, and it'll apply these on animation start. ie:

```
<motion.div animate={{ display: 'block' }} />
```

**Comment by mattjennings** [comment]
This would be helpful for updating the beginning state of an "exit" animation. 

For example, I want to set the position to `fixed` in an exit animation, but doing so resets the scroll position of that element. A workaround would be to set the `top` to the `-window.scrollY` in the exit animation, however that leads to a transition from `top: 0` to `top: -window.scrollY` over the exit animation.

[Here's a codesandbox demonstrating the example](https://codesandbox.io/s/ios-transitions-with-framer-motion-q1ick). If you click on dogs or cats, scroll down, then hit back, you'll see the scroll position snap to 0 as it transitions back. If you open `Page.js` and edit the exit animation to have `top: -window.scrollY`, you'll see the transition from 0 to window.scrollY.

**Comment by daviddelusenet** [comment]
This indeed would be nice to have.

**Comment by nathanredblur** [comment]
Nice, I have this problem that this feature could solve it:
I have a tooltip animated and the animation start when the mouse is over a button.
The animation  change the `Y` position so, for a millisecond the tooltip is over the button.
Then, because the button loose the `hover` the animation of the tooltip start backward and that is an infinity loop.

What I would like to have is just set `pointerEvents: 'none'` when the animation start and restore the `pointerEvents` when the animation ends.

**Comment by mattgperry** [comment]
Closing this as I think most things can be achieved already without this.

Animating non-animatable values will set them instantly, and they can be changed again at the end of the animation with `transitionEnd`.

For animatable values its possible to pass a value-specific transition as `type: false` to disable the animation.
