### ISSUE TITLE
[BUG] css scroll-snap on iOS causes flickering

### ISSUE THREAD

**Issue by Corjen** [framer/motion#342]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
On iOS, using scroll-snap-type combined with a motionValue results in flickering of the page.  

**3. Provide a CodeSandbox reproduction of the bug**
[https://65m3q.sse.codesandbox.io]. If you comment out the `opacity` key in Indicator.js(line 20), the flickering stops and the page scrolls normally without flickering

**4. Steps to reproduce**
1. Go to https://65m3q.sse.codesandbox.io on an iOS device
2. Scroll down to the point we're the safari UI collapses

**5. Expected behavior**
Scrolling should be smooth and red box in the left bottom corner should fade out.

**6. Video or screenshots**
[RPReplay_Final1569854363.MP4.zip](https://github.com/framer/motion/files/3671795/RPReplay_Final1569854363.MP4.zip)

**7. Environment details**
We're currently using iOS 13.1.1, but experience the same in issue in 12. 

Maybe it has something to do with `window.innerHeight` when the user scrolls past the 'UI snap point'? We've also tried a custom useViewportScroll hook with a fixed window height, but that didn't solve it.

Hope you can look into it! Happy to help out were I can! Thanks!

**Comment by InventingWithMonster** [comment]
Hey @Corjen thanks for the sandbox and the video, it help me debug this. 

Unfortunately this looks like a bug in Webkit. If you take a look at this fork https://codesandbox.io/s/hello-world-pr5fe I've re-implemented the effect without Framer Motion and the same bug emerges. I think this is specifically a bug in re-painting an element on top of an element that has the scroll snapping behaviour. You can provide them this sandbox if you want to open a bug there.

**Comment by CodeWithOz** [comment]
@Corjen @mattgperry sorry to bother you both but did either of you file a webkit bug report about this issue? I'm seeing something similar so I'd like to follow any conversations that resulted from this thread. Thanks.

**Comment by mattgperry** [comment]
I didn't personally

**Comment by ebukanas** [comment]
Has anyone managed to find a workaround for this issue

**Comment by AndrewNoviello** [comment]
Just following up on this issue...has anyone managed to find a solution? Experiencing the same bug with Framer Motion animations paired with Tailwind CSS scroll-snap in ReactJS web application (testing on Google Chrome).

**Comment by Brentably** [comment]
Getting the same issue

**Comment by Brentably** [comment]
When I go to the codepen on my iPhone, I don't get the flickering, but I definitely do with my framer project...
