### ISSUE TITLE
[FEATURE] Explicit variant inheritance

### ISSUE THREAD

**Issue by amannn** [framer/motion#343]
**Is your feature request related to a problem? Please describe.**

An active variant is automatically inherited to child motion components via React context (see [the docs](https://www.framer.com/api/motion/component/#animationprops.variants)). If you have nested components which use the same variant labels, this might lead to accidental overrides.

E.g. `hidden` and `visible` are IMO very common variant names. I have an app where you can open a sidebar (setting a `motion.div` variant to `visible`) and inside of it there are buttons where there's some touch feedback for the user (again, setting a `motion.div` variant to `visible`).

The outer animation variant automatically propagates to children and has caused an unexpected scenario where the animation value on the parent overrides the value on the child.

**Describe the solution you'd like**

Have you considered something like `<motion.div animate="inherit" />` or `<motion.div controlledFromParent />`? The idea is to make this relationship a bit more explicit and to avoid triggering it by accident.

I think `animate="inherit"` would be smart, as it avoids the scenario where you have an animation value from context and a local one set and it's unclear which of those wins. However the user can no longer use `inherit` as a variant name then, but I guess that's pretty uncommon anyway.

**Describe alternatives you've considered**

I'm currently scoping all variant names to a component:

```
const variantNames = {
  visible: 'IconButton_visible',
  hidden: 'IconButton_hidden'
};
```

You could still have the issue if you nest such components though.

**Comment by InventingWithMonster** [comment]
`animate="inherit"` wouldn't allow variant propagation via `useAnimation()`

However there's a prop called `inherit` that you can use to block variant inheritance from parents:

```jsx
<motion.div inherit={false} />
```

I've only just seen this isn't part of the docs so I'll add it now.

**Comment by amannn** [comment]
> However there's a prop called `inherit` that you can use to block variant inheritance from parents

Oh great, I just tested that in my app and it works perfectly 👌. Thanks!

> animate="inherit" wouldn't allow variant propagation via useAnimation()

Hmm, I think I'd need an example to understand that use case.

**Comment by InventingWithMonster** [comment]
```jsx
const controls = useAnimation()

return <motion.div animate={controls} />
```

**Comment by amannn** [comment]
I had an example like this in mind: https://codesandbox.io/s/framer-motion-variant-propagation-ze52v.

My expectation was that the variant of the inner component only switches to `visible` once the user clicks the button.

What I observed:
1. When you pass a variant name (or any string) to the inner component, this will always take precedence over the inherited value. I guess that's what you meant by:
> animate="inherit" wouldn't allow variant propagation via useAnimation()
2. When you pass `animate={controls}`, the component still inherits the variant from the parent.
3. As soon as you call `controls.start(…)`, the variant can be overridden internally. Not sure if a change in the parent will override it again?

The second observation is the one that confused me a bit in an app. Using `inherit: false` makes this clearer for me.

I guess the implemented strategy is that the latest change wins – no matter where it happend in the tree – (except for `animate={someString}`), whereas I thought the local `animate` prop always takes precedence.
