### ISSUE TITLE
[BUG] Exit variant not propagated in framer-motion@1.6.8

### ISSUE THREAD

**Issue by amannn** [framer/motion#345]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

Sorry for opening yet another issue 😬.

I noticed that there was a regression in framer-motion@1.6.8. When a motion component unmounts, its `exit` variant is no longer propagated to nested motion components.

**3. Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-exit-inheritance-qgrr9

This shows the expected behaviour with framer-motion@1.6.7. When you click the button, the panel first expands and then the content fades in. When you click again, the animation order is reversed.

**4. Steps to reproduce**

1. In the CodeSandbox, upgrade to framer-motion@1.6.8
2. Click the button to show the panel and then again to hide it.
3. You'll notice that the content no longer fades out.

**5. Expected behavior**

Nested motion components should inherit the `exit` variant when a parent unmounts.

**6. Video or screenshots**

**7. Environment details**

Chrome 77 on macOS.

**Comment by amannn** [comment]
@InventingWithMonster Thanks a lot for the quick fix!

**Comment by InventingWithMonster** [comment]
Fixed in `1.6.9`
