### ISSUE TITLE
[BUG] Race condition of AnimatePresence in 1.6.8

### ISSUE THREAD

**Issue by amannn** [framer/motion#347]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

Seems like the latest release introduced a race condition, where if you toggle the children of `AnimatePresence` fast enough, it's possible that you end up in a state where they aren't rendered while they actually should be.

**3. Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-animatepresence-race-condition-c0bzh

**4. Steps to reproduce**

1. Quickly click the toggle button and stop on the visible state.
2. Chances are the state is visible, but the children aren't rendered.

Note that with `1.6.7` I can't reproduce this.

**5. Expected behavior**

If `AnimatePresence` receives children, they should always be rendered.

**6. Video or screenshots**

![Kapture 2019-10-03 at 17 23 08](https://user-images.githubusercontent.com/4038316/66141331-cb343f00-e603-11e9-9759-881333a49f05.gif)

**7. Environment details**

Chrome 77 on macOS.

**Comment by amannn** [comment]
If there's anything I can help with, just let me know!

**Comment by izzuddinnatsir** [comment]
The same also happen in my website. Does the previous version release also has this bug?

**Comment by amannn** [comment]
No, framer-motion@1.6.7 doesn't have the bug. If you don't need something
from 1.6.8, you can downgrade.

**Comment by izzuddinnatsir** [comment]
Thanks @amannn !

**Comment by InventingWithMonster** [comment]
Thanks for the reproduction!

**Comment by InventingWithMonster** [comment]
Yeah I suspect the specific broken behaviour is that previously we were overwriting `animate` with `exit` when the component was exiting. In 1.6.8 we changed that behaviour so `exit` animations are handled separately.  So when a component stops exiting, its `animate` prop has never actually changed, so we don't know to re-run its contents. This should be a relatively trivial fix.

**Comment by InventingWithMonster** [comment]
Fixed in `1.6.9`

**Comment by amannn** [comment]
Thanks a lot, works really well in the CodeSandbox demo now!
