### ISSUE TITLE
[BUG] SVG "d" tag animation error

### ISSUE THREAD

**Issue by Lomkex1** [framer/motion#348]
**Bug Descriptiion**
motion.path "d" tag is treated as a number insted of string.
returns error, in my example:
"Error: <path> attribute d: Expected number, "M NaN NaN L NaN Na…" (stylefire.es.js :498)

**Steps to reproduce the behavior:**
1. Create motion.svg with motion.path as child
2. Create animaton variants, animating "d" value
3. Wait for initial render

**Expected behavior**
"d" tag is supposed to be treated as string and not tried to be parsed as a number

**Comment by InventingWithMonster** [comment]
Hi @Lomkex1, can you create a CodeSandbox reproduction that demonstrates this bug? As I haven't been able to replicate. Thanks.

**Comment by InventingWithMonster** [comment]
I'm going to close this for now, but please feel free to re-open with a CodeSandbox and I'll take a look!

**Comment by Lomkex1** [comment]
Sorry, turned out to be my fault...
Thanks for the reply, really appreciated.
