### ISSUE TITLE
[BUG] viewport listener doesn't seem to be firing on gatsby

### ISSUE THREAD

**Issue by jmcbee** [framer/motion#351]
I've created a sandbox to demonstrate the issue:

https://codesandbox.io/s/gatsby-starter-default-i0q4c

**Comment by InventingWithMonster** [comment]
Motion values specifically bypass the React render function for performance reasons. You can subscribe to scrollYProgress like this, and use it to update a component's state.

```jsx
 useEffect(() => {
    return scrollYProgress.onChange(v => console.log(v))
  }, [scrollYProgress])
```

**Comment by dnlmzw** [comment]
Sorry - maybe asking the stupid questions here, but can anyone explain to me what other way you're supposed to use this method, if not within the React render method? I mean, doesn't the example in the docs show this example as well?

```export const MyComponent = () => {
  const { scrollYProgress } = useViewportScroll()
  return <motion.div style={{ scaleX: scrollYProgress }} />
}```

Also, what are the pros in terms accessing the scrollY via motion, compared to creating an event listener on scroll?

**Comment by robksawyer** [comment]
I'm trying the following in the latest version of NextJS and it isn't working within my components. Any ideas?

> ```js-jsx
> useEffect(() => {
>     return scrollYProgress.onChange(v => console.log(v))
>   }, [scrollYProgress])
> ```

**Comment by focux** [comment]
I'm using also Next.js and it's not working. I'm on version `2.9.1`.

**Comment by ImSolitude** [comment]
I can also confirm `.onChange` listeners are so buggy in Next.js! and they're just not working!

**Comment by eteka03** [comment]
Nextjs version 10.0.4 and it istill not working . any ideas ?

**Comment by giacomocerquone** [comment]
that is not working in gatsby too... @mattgperry could you step in here? Any idea why that should not be working?

**Comment by mattgperry** [comment]
Are you talking about all onChange listeners or just those attached to the viewport motion values? If the latter have you tried attaching a traditional scroll event to the window and seeing how that works?

**Comment by giacomocerquone** [comment]
@mattgperry I'm debugging the problem right now.
Indeed I made the same thought and I attached an eventlistener manually during develop in gatsby and it works fine.
I'm currently trying to replicate the same return datastructure of your useViewportScroll but with my own eventlistener! I'll update here the results soon.

If I had to purely speculate on what the problem is, I'd say it is due to that useIsomorphiclayouteffect which might not be compatible (for some reason) with gatsby:

![Uploading image.png…]()

**Comment by giacomocerquone** [comment]
Solved it.
It wasn't the useIsomorphic stuff, though in gatsby the addDomEvent is not working (still don't know why), but this example works:

https://gist.github.com/giacomocerquone/19436f6f38f3c628a4066a6b25621ae1

If you see, replacing it with a normal window.addeventlisteners make it work. @mattgperry

**Comment by giacomocerquone** [comment]
Ok this lib is a bit hard.
Anyway this is what is going on:

you do this: 

```javascript
    const { xOffset, yOffset, xMaxOffset, yMaxOffset } = getOffsets();
    // Set absolute positions
    values.scrollX.set(xOffset);
    values.scrollY.set(yOffset);

    console.log(yOffset, yMaxOffset);

    // Set 0-1 progress
    setProgress(xOffset, xMaxOffset, values.scrollXProgress);
    setProgress(yOffset, yMaxOffset, values.scrollYProgress);
```

whereas getoffsets is defined like this:

```javascript
function getViewportScrollOffsets() {
  console.log(document.body.clientHeight, window.innerHeight);

  return {
    xOffset: window.pageXOffset,
    yOffset: window.pageYOffset,
    xMaxOffset: document.body.clientWidth - window.innerWidth,
    yMaxOffset: document.body.clientHeight - window.innerHeight,
  };
}
```

Those document.body.clientHeight and window.innerHeight are actually, for some reason, the same number and that subtraction is equal to zero.
Being equal to zero when you call the setProgress function, you set always 0:
The setProgress function is defined like this:

```javascript

function setProgress(offset, maxOffset, value) {
  value.set(!offset || !maxOffset ? 0 : offset / maxOffset);
}
```

So, what's going on here? What am I missing? Is it normal that those two values are actually the same?

**Comment by giacomocerquone** [comment]
I DONT BELIEVE THIIIIIIIS!
Reasoning about those two properties led me to think about the fact that I've set with css body height: 100%

That I'll be damned... so it has nothing to do with gatsby in my case (and probably in other's people case too).
What do you advice in these situations?

**Comment by giacomocerquone** [comment]
So angry right now lol

**Comment by mattgperry** [comment]
Yeah I think documentation is a good idea, I'm adding it to the 3.4 branch now. The only way to fix this is by removing that rule, because it breaks the browser's ability to accurately measure the page.

**Comment by giacomocerquone** [comment]
Ok then to the guys participating in here, if your issue is with height 100% you just need something like this in your component that is using useViewportScroll

```javascript
 useEffect(() => {
    document.body.style.height = "auto";

    return () => {
      document.body.style.height = "100%";
    };
  }, []);
```

@mattgperry if you're writing the doc, make sure to add also a snippet like the one I've posted
