### ISSUE TITLE
[FEATURE] Be able to send custom data to controls.set function

### ISSUE THREAD

**Issue by hassenc** [framer/motion#356]
**Is your feature request related to a problem? Please describe.**
When using animation controls (`useAnimation`) we can pass custom props to `.start() `function using the `custom` prop. We can't do that for the `.set()` function.

**Describe the solution you'd like**
On button click, would like to reset an animation to a state that depends on some props
````
const onClick() => {
  controls.set( i => {{x: i*10}})
  controls.animate( i => {{x: i*20}})
}
````
**Describe alternatives you've considered**
We can use variantLabels instead.

Let me know if this seems a legit feature request, I can open a PR for this.

**Comment by InventingWithMonster** [comment]
Yeah this sounds like a great feature request, totally understand the need for it. We'd take a PR for it.
