### ISSUE TITLE
Animate Presence Bug on Presence Child not removed

### ISSUE THREAD

**Issue by ralphchristianeclipse** [framer/motion#357]
Animate Presence 

BUG:

Presence Child still exists.

https://codesandbox.io/s/framer-motion-notifications-30ezo

Please check out the issue is it's not removing the notification. but the array is already 0

**Comment by ralphchristianeclipse** [comment]
Here is an image btw.

![image](https://user-images.githubusercontent.com/25447231/66724230-29f48680-ee56-11e9-9066-c6347118db46.png)

**Comment by anilanar** [comment]
Cannot reproduce after assigning `key={notification.id}`. Array indices are not unique/reliable keys.

/close.

**Comment by ralphchristianeclipse** [comment]
@anilanar it's not array indices you can check the key though it's a timestamp

**Comment by InventingWithMonster** [comment]
Can't reproduce in `1.16.15` - feel free to re-open with more detailed reproduction steps if you find the bug persists.
