### ISSUE TITLE
exitBeforeEnter AnimatePresence bug undefined onAnimationStart

### ISSUE THREAD

**Issue by ralphchristianeclipse** [framer/motion#358]
There is an error where it's trying to access onAnimationStart on an undefined object inside AnimatePresence when i put exitBeforeEnter

![image](https://user-images.githubusercontent.com/25447231/66725446-b443e700-ee64-11e9-926e-9c791e3ebc78.png)

**Comment by InventingWithMonster** [comment]
Thanks for the report, can you check this again in `1.6.13`?

**Comment by ralphchristianeclipse** [comment]
All good now thanks.
