### ISSUE TITLE
Unwanted horizontal shift when item using positionTransition grows

### ISSUE THREAD

**Issue by Rijk** [framer/motion#359]
See https://codesandbox.io/s/framer-motion-growing-item-positiontransition-issue-z2z4l

This is based on the [drag to reorder](https://codesandbox.io/s/framer-motion-drag-to-reorder-fixed-height-hwz8q) example. 

When an item changes width (for instance when content is added after loading), there’s an unwanted horizontal shift. I’ve added a timeout to demonstrate the issue:

![Screen Recording 2019-10-14 at 14 10 03](https://user-images.githubusercontent.com/159500/66750836-cdad5900-ee8d-11e9-85ff-9f81726808e2.gif)

Expected behaviour: item grows to the right, without shifting left. I’ve noted that this shifting only happens on framer-motion@1.6.x, not on 1.5.0.

Is this a bug? If not, is there a way to disable this, while keeping the `positionTransition` on the y-axis?

**Comment by InventingWithMonster** [comment]
That's weird. I assume you don't want the `width` to animate at all in this example?

**Comment by Rijk** [comment]
Nope; the `positionTransition` is just to animate the reordering.

**Comment by InventingWithMonster** [comment]
Cool ok as `layoutTransition` works correctly I think we're probably only shutting off some of the FLIP functionality when its a `positionTransition` animation.

**Comment by Rijk** [comment]
Right, `layoutTransition` is a nice option if I want the width to grow, but I would use that on a child div anyway since it would distort the border radius of this div. So for this use case the width animation that results from `positionTransition` is not desired.

Not sure what you mean with this though 😄

> we're probably only shutting off some of the FLIP functionality when its a positionTransition animation.

**Comment by InventingWithMonster** [comment]
Both `layoutTransition` and `positionTransition` use the same code to work, setting `positionTransition` just shuts off a small amount of it that deals with width and height.

Looking into it, the problem is when we detect the difference in layout, we measure from the center of the before and after bounding boxes. This is because when we move an element we actually only want to move it the distance of that center point (because if the element's changed size too, we don't want to factor that into the equation).

This might be as simple as using the top/left point for `positionTransition` and the center point for `layoutTransition`.

**Comment by Rijk** [comment]
Sounds good, I was thinking something along these lines (already messed around with `transform-origin` to attempt to fix this. So if I understand correctly this will require a framer-motion fix?

**Comment by InventingWithMonster** [comment]
Hmm actually on further consideration this works well if the anchor point as also top/left. But if the component has changed width/height and it has a `transform-origin` of `100% 100%` this would break.

I'll look into how I can smartly detect this.

**Comment by Rijk** [comment]
If it would require an additional parameter (e.g. `transformOrigin`), that’s perfectly fine for me as well.

**Comment by InventingWithMonster** [comment]
I'm starting to think we could calculate the transformOrigin based on how the bounding boxes have changed

**Comment by Rijk** [comment]
Makes sense I think. In this case, the bounding box won’t change position as a result of the width increase — so if somehow you can detect that, it should be easy to prevent the transition on the x axis from happening. I think that is the main problem here; the library (incorrectly) assumes a position transition has/will take place because the width of the element changes.

**Comment by InventingWithMonster** [comment]
Fixed in `1.6.14`

**Comment by Rijk** [comment]
Nice!
