### ISSUE TITLE
[BUG] useViewportScroll scrollY Motion values fluctuate (jitter) when document height changes.

### ISSUE THREAD

**Issue by agonsalves** [framer/motion#365]
I have 2 elements on the page that use the `scrollY` value from `useViewportScroll()`
The first element has its height adjust based on the scroll position, so that it appears to collapse as the user scrolls down the page. The second element has its Y position adjusted as the viewport is scrolled, to create the effect of it scrolling faster than the other objects on the page.
There are certain points along the page where the Y value of the second element fluctuates between two values (creating a visual jitter).

Codesandbox: https://codesandbox.io/embed/flamboyant-sara-yk1st

If you slowly slide the scrollbar down the page, you are sure to find at least one scroll position where the right column starts to jitter. (I would record a video but the FPS is too low to show the jitter) If you inspect the element, you'll see`y` fluctuate between two values.

I believe this may be happening because the changing height of the first element changes the height of the document.

**5. Expected behavior**

Obviously, there should not be a jitter. The value should stay constant if the user is not scrolling.

**7. Environment details**

Chrome (latest), Windows 10

Edit: I know that I can resolve this by establishing a minimum height for the first object so that it stops affecting the document height after it is off the page. The bug is still a bug, though.

**Comment by sammovale** [comment]
Have noticed this too when trying to implement a parallax scroll using `useViewportScroll()` and `useTransform()`.

My current code is as follows, though I dont believe the `ease: false` is actually doing anything but it was my attempt at trying to make it less jittery.

`  const { scrollYProgress } = useViewportScroll()
  const parrallaxImage = useTransform(scrollYProgress, [0,.3],['0vh','50vh'],{
    ease: false
  })
  const parrallaxImage2 = useTransform(scrollYProgress, [.65,1],['0vh','50vh'],{
    ease: false
  })`

This code enables two fullscreen images to have a parallax scroll and I use the range function for limiting the number of animations occuring concurrently. This jitter also seems a lot more apparent on safari ios when scrolling at a moderate pace, the momentum based scrolling causes a lot of jitter to occur. When I use vh units it seems to make it "slightly" more reliable. Would be good to see if theres some performance optimisations here.

I haven't tried the min-height fix so I will try that and see if it improves it.

**Comment by mattgperry** [comment]
In this case, it can be fixed by adding `overflow: hidden` to `.App`. I think what's happening is there's a loop getting fired where an element ends up outside of the viewport, the scroll is recalculated, changing the element's position, recalculating the scroll...

@sammovale can you check and see if a similar thing helps your case?
