### ISSUE TITLE
[BUG] Cannot use both `animate` and `borderRadius` in Firefox

### ISSUE THREAD

**Issue by bchociej** [framer/motion#367]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

In Firefox, `animate` and `borderRadius` don't work together. If both are specified, the border radius animation does not occur.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

I noticed this bug while looking at the Keyframes example in the API docs, so I'll just link that sandbox here: https://codesandbox.io/s/framer-motion-keyframes-ekks8?fontsize=14&module=%2Fsrc%2FExample.tsx

The use of keyframes and `scale` do not appear to make a difference when I edit the sandbox to remove them.

**4. Steps to reproduce**

1. Visit the above sandbox in Firefox 69

**5. Expected behavior**

I expected the border radius to animate smoothly. Instead, it snaps back and forth without animation.

**6. Video or screenshots**

Notice the border radius snap from 20% to 50% and back in this screen grab:

![keyframes-ff](https://user-images.githubusercontent.com/4683658/67062299-7f67b680-f128-11e9-85f6-20d3598c2d8b.gif)

**7. Environment details**

Firefox 69.0.3 (64-bit) on freshly updated Arch Linux

**Comment by poacher2k** [comment]
This bug is still present in the exact same form close to a year later in Firefox 81.0b7 (64-bit).

**Comment by InventingWithMonster** [comment]
This is actually a bug in Firefox. I've narrowed it down to changing `rotate` in the same frame as `borderRadius` doesn't update the border radius. The same bug can be replicated in (for instance) Anime.js

**Comment by bchociej** [comment]
Crossposted to https://bugzilla.mozilla.org/show_bug.cgi?id=1667788

**Comment by InventingWithMonster** [comment]
Nice one thanks!

**Comment by poacher2k** [comment]
FWIW, as one of the commentors on the bugzilla-page also said, I'm no longer experiencing this in FF Nightly (currently at 82.0b4 (64-bit) with an update waiting for me).
