### ISSUE TITLE
[Question] Trigger animation when visible in viewport

### ISSUE THREAD

**Issue by lucoel** [framer/motion#369]
I may have missed it in the documentation, but I wonder if there is the possibility to start an animation once an element is visible in the viewport (animate on scroll).

Thanks!

**Comment by thebuilder** [comment]
You'd use an intersection observer to trigger the animation, once the element enters view.
https://github.com/thebuilder/react-intersection-observer

**Comment by lucoel** [comment]
@thebuilder wow, that's exactly what I was looking for!

**Comment by EvanPurkhiser** [comment]
> using react-spring, but same principal

Looks like this was even converted over to framer-motion, nice surprise :)
