### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CurtisHumphrey** [framer/motion#370]
**1. Read the [FAQs](#faqs) 👇**
**2. Describe the bug**

AnimatePresence does not propagate exit to children

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-animatepresence-padding-issue-bvnii?fontsize=14

I have tried to have the children not have initial="close" animate="opened" exit="closed" but then the child does do the intro animation (just jumps to "opened").  It seems I can either have it do the entrance animation or the closing animation but not both.

**4. Steps to reproduce**

Opening animations work (both parent and child)
Exiting animations only the parent works not the child

**5. Expected behaviour**

AnimatePresence should propagate exit to parent AND its children

**Comment by InventingWithMonster** [comment]
If you upgrade to latest and change the errant `opacity` -> `backgroundColor` this works now
