### ISSUE TITLE
[QUESTION] Passing X and Y values into a variant object

### ISSUE THREAD

**Issue by Mellis84** [framer/motion#371]
Is there a way to bring in an elements X and Y values into a variants object?

Something like
```
 pressed: (isLightMode, x) => ({
    y: isLightMode ? 40 : 80,
    rotate: x === 0 ? 90 : 20,
    transition: {
      stiffness: 260,
      damping: 20
    }
  }),
```

Cheers!

**Comment by InventingWithMonster** [comment]
No you'd have to keep them externally, perhaps as motion values, and pass them in via the `custom` prop
