### ISSUE TITLE
[BUG] Chrome mobile/desktop responsive mode can cause `onPan` to infinitely loop

### ISSUE THREAD

**Issue by praxxis** [framer/motion#372]
**2. Describe the bug**

In Chrome on mobile or in responsive mode on desktop the `onPan` callback can be called an infinite loop, unless you provide the `drag="x"` prop. As far as I can tell this _only_ affects Chrome. Firefox desktop/mobile, and Safari desktop/mobile all function correctly, and never infinite loop. Based on that this is quite possibly a browser bug :(

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/embed/onpandrag-prop-bug-ccjl5?codemirror=1

**4. Steps to reproduce**

Load the sandbox in Chrome on mobile or in desktop *in responsive design mode*. Click-and-drag to "pan" the image, and note that it works. Click "toggle" to remove the `drag` prop. Click-and-drag again, and you should see the `panned` count keep going up (note: you might have to click-and-drag a couple of times to see it occur).

**5. Expected behavior**

If `drag` is required for `onPan` to work properly this should be documented, even if it's just a workaround for a Chrome bug.

**6. Video or screenshots**

Following the above steps you should see something like:

![panned](https://user-images.githubusercontent.com/15754/67119746-c51e9080-f1b5-11e9-9d72-25c6a9fa1d1a.gif)

**7. Environment details**

The gif was captured using `Version 79.0.3944.0 (Official Build) canary (64-bit)`. The code sandbox was forked from the official drag example. I updated it to use the latest framer-motion version, changed the callback to `onPan`, added the toggleable `drag` prop, and added the `panned` count display - the rest of it is untouched.

**Comment by praxxis** [comment]
Ha, as soon as I open my own bug I find out that it's something of a duplicate: https://github.com/framer/motion/issues/281, albeit with a different workaround

**Comment by mattgperry** [comment]
Closing this for the reasons given in that other thread. I'll add something to the docs.
