### ISSUE TITLE
[BUG] `positionTransition` not respected when elements enter deeper in the tree

### ISSUE THREAD

**Issue by smithki** [framer/motion#375]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

`positionTransition` is not respected at higher levels for components entering deeper in the tree. Using `<UnstableSyncLayout>` fixes the issue for _exiting components only!_

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/position-transition-not-executing-for-entering-components-3z2bf

**4. Steps to reproduce**

**5. Expected behavior**

I expected that `positionTransition` would be respected for elements _entering_ deeper in the tree. The code example I have provided was my natural instinct to achieve such behavior. I believe [this line of code](https://github.com/framer/motion/blob/d4885291958e184074f1dfcbc17c198602e31f78/src/components/AnimatePresence/index.tsx#L234) creates the desired behavior when components are exiting. Can it be used elsewhere to react to entering components as well?

**Comment by InventingWithMonster** [comment]
Closing as positionTransition has been removed
