### ISSUE TITLE
[QUESTION] How do I make sure stuff animates only when they're on screen?

### ISSUE THREAD

**Issue by atiyahio** [framer/motion#376]
I've been trying to use Motion in my projects but all animations end up happening once the page loads and the user doesn't even get to see them.

how do I fix that and wait till it's visible on screen?

**Comment by thebuilder** [comment]
See #369 

You'd use an intersection observer to trigger the animation, once the element enters view.
https://github.com/thebuilder/react-intersection-observer

**Comment by atiyahio** [comment]
> See #369
> 
> You'd use an intersection observer to trigger the animation, once the element enters view.
> https://github.com/thebuilder/react-intersection-observer


what if i have multiple different divs with multiple different animations, is there's a way to use intersection observer more than once?

**Comment by thebuilder** [comment]
You can create as many observers as you need.

**Comment by atiyahio** [comment]
great! thanks!
