### ISSUE TITLE
[BUG] Render into iframe

### ISSUE THREAD

**Issue by anilanar** [framer/motion#379]
When a `motion.div` (or any `motion` component) is rendered into an iframe, the following invariant fails:

```
invariant(ref.current instanceof Element, "No `ref` found. Ensure components created with `motion.custom` forward refs using `React.forwardRef`");
```

Although `ref.current` is also an `Element`, it's an `Element` from another `window`. Thus it doesn't belong to the same prototype chain as the one referenced in above code`instanceof Element`.

A possible solution is to use `ref.current.constructor.name`? Or remove the invariance?

https://codesandbox.io/s/framer-motion-iframe-bug-x7ud9

**Comment by anilanar** [comment]
I just noticed that getting rid of the invariant causes another problem at:

```
    var node = typeof nodeOrSelector === 'string' ? document.querySelector(nodeOrSelector) : nodeOrSelector;
```

because `document` !== `document of ref.current`.

The way `emotion` solves this is by having a React `Provider` for user-land to pass down such global dependencies.

**Comment by mrmckeb** [comment]
We've just hit a similar iframe related error. I think the fix that @anilanar suggested seems great, are the team OK if he (or I) look to implement this?

We're seeing this when using `motion.div` inside of an iframe:
```
No `ref` found. Ensure components created with `motion.custom` forward refs using `React.forwardRef`
```

**Comment by rsoury** [comment]
Ran into the same issue using the react-frame-component package.
The purpose was to encapsulate styling. My workaround was to make use of Shadow DOM using https://github.com/Wildhoney/ReactShadow

Unfortunately, Shadow DOM is not supported without polyfills on legacy browsers so would love an update on this issue.

**Comment by sivakumar-kailasam** [comment]
@InventingWithMonster Any suggestions/directions for anyone interested in raising a PR for this?

**Comment by vignestion** [comment]
Stuck with the same problem any update on this issue?

**Comment by pm990320** [comment]
+1 - also running into this issue with iframes. Likewise happy to look at contributing this

**Comment by dlosie** [comment]
Having the same issue trying to use this with [react-frame-component](https://github.com/ryanseddon/react-frame-component). Did anyone here find a solution? Or would it be better to switch to [react-spring](https://github.com/react-spring/react-spring) if you need to render into iframes?

**Comment by sivakumar-kailasam** [comment]
I [posted about this](https://discordapp.com/channels/341919693348536320/716908973713784904/726203695376629761) on the framer-motion channel on the framer discord server. I hope someone from the framer team eventually responds to this 🤞🏻

**Comment by InventingWithMonster** [comment]
This seems to be fixed at some unknown point in the past so closing this issue

**Comment by james2406** [comment]
It looks like this is still an issue. I modified the Drag demo to render into an iframe and I see the "No `ref` found" error:
https://codesandbox.io/s/framer-motion-drag-iframe-ghqe2. Has anyone managed to get it working?

**Comment by james2406** [comment]
Can this issue be reopened please?

**Comment by mattgperry** [comment]
Yep for sure. There’s MotionConfig but I’m not sure how useful that’d be?

**Comment by souporserious** [comment]
Hm yeah not sure if it makes sense there since it's changing window for things like `useViewportScroll`. I'll put together a PR and we can discuss further, thanks!

**Comment by mattgperry** [comment]
Doesn't seem to be broken by upgrading to `6.5`
