### ISSUE TITLE
[BUG] AnimatePresence : Insertion index for leaving children doesn't take entering children into consideration

### ISSUE THREAD

**Issue by JabX** [framer/motion#381]
Hello,

I am migrating from Pose and despite AnimatePresence being a complete (from my understanding) rewrite of PoseGroup, it seems that [an issue that I already found back then](https://github.com/Popmotion/popmotion/issues/685) is still present :(

Basically, if children are both entering and leaving at the same time (during the same render) and (at least) a leaving child is located after an entering one, then the insertion index for the leaving child is wrong because it doesn't take into account the newly entered one.

[See here](https://codesandbox.io/s/animatepresence-test-y840u) for the reproduction on CodeSandbox, which is exactly what I'm trying to do in my application. Pressing "+" or "++" animates correctly, while "-" or "--" skips a line.

Back then I also [proposed a fix](https://github.com/Popmotion/popmotion/pull/686) that I never took the time to properly test (well this is why it's still a pending PR), and I lived off of this fix as a patch in my project for the entire time since it was fixing my particular problem, at least.

I tried adapting my fix on the new codebase but I didn't quite manage to work my way around it, so I figured that I should at least reopen this issue so that more people could chime in on a solution (and merge it this time ;) )

**Comment by mattgperry** [comment]
I'm closing this as I'm not having luck replicating it in the linked sandbox. Are you still having a problem with this?

**Comment by JabX** [comment]
I just tried the latest version and the problem is still there. The sandbox does demonstrate the problem, but maybe it is more obvious with that gif showing the problem in the application I use for testing:

![animatepresence](https://user-images.githubusercontent.com/3266897/112732591-2d40dc80-8f3b-11eb-957f-c0a42b716434.gif)
