### ISSUE TITLE
[BUG] AnimatePresence intermediary element breaks exit

### ISSUE THREAD

**Issue by DavidBachmann** [framer/motion#382]
Hello, it's not clear by the docs whether or not this should work or not:

See Component2 with an intermediary div that breaks exit:
https://codesandbox.io/s/framer-motion-animate-presence-unmount-6yizw 

Working version with no div in between:
https://codesandbox.io/s/framer-motion-animate-presence-unmount-xofgq

Is AnimatePresence in sandbox link #1 behaving as intended?

**Comment by InventingWithMonster** [comment]
Yeah. It can only track the presence of immediate children.

**Comment by DavidBachmann** [comment]
Thanks for clarifying
