### ISSUE TITLE
[BUG] SVG Rect X/Y Not working anymore

### ISSUE THREAD

**Issue by amcdnl** [framer/motion#384]
## Issue
The change listed here: https://github.com/framer/motion/blob/master/CHANGELOG.md#fix-3 which makes `x`/`y` always translate vs x/y for SVGs causes SVG `rect` to break.

The docs note the expected behavior:

> SVG note: For SVG components, x and y are positional attributes distinct from translateX and translateY. Using the former will change the element's x/y attributes, while using the latter will set its style.transform property.

Looks like the change happened with the stylefire update - https://github.com/framer/motion/commit/4e35b577ff7dba1ea86b2ea4205f9dbdca880b74#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R96 with the change here: https://github.com/Popmotion/popmotion/pull/839

Example use case: https://github.com/jask-oss/reaviz/blob/master/src/BarChart/BarSeries/Bar.tsx#L482

**Comment by amcdnl** [comment]
^ Bump ---This is a major bug...

**Comment by TheFragen** [comment]
Bump. The `rect` behaviour is way off, bordering to unusable. I'm able to hack around it using the aforementioned `attrX` and `attrY` props, or using a `motion.path` instead.

**Comment by amcdnl** [comment]
Related: https://github.com/framer/motion/issues/644

**Comment by tomlagier** [comment]
Just wanted to note that this just bit me too - can't use `motion.rect` as the prop conflicts cause incorrect behavior.

**Comment by ritwikvd** [comment]
I'm not sure whether this is related, but the removal of some of the popmotion packages seem to have affected a pre-existing functionality where motion elements being added or removed could be auto-animated with just the animate prop. This was working in 2.0.0-beta.57, and no longer does with the current release.
