### ISSUE TITLE
[DOCS] Examples using resizing/dragging

### ISSUE THREAD

**Issue by Meemaw** [framer/motion#385]
Hi! I've been trying to re-create something similar to https://www.framer.com/learn/lesson/build-a-drag-handle/ in framer-motion, but I've struggled finding examples on the matter and had problems with keeping dragging/width in motion for a smooth animation.

As I like your [examples](https://www.framer.com/api/motion/examples/) a lot, I think they lack a few real world use cases that would drive adoption of the library. Resizable are in my opinion a very common use-case and it would be great if there were some nice examples about it.

**Comment by satvikpendem** [comment]
I'd like to see the same, I'm also trying to implement that drag handle example into framer-motion. Did you have any success? I am not sure where exactly those props in the Overrides are coming from, looks like they're passed in as the equivalent of the `style` prop in framer-motion elements.

**Comment by PTaylour** [comment]
I also saw that example and went looking for a framer-motion example.

Gave it a go myself if this is any use to everyone:

https://codesandbox.io/s/festive-rain-9cdqv?file=/src/index.tsx 

![image](https://user-images.githubusercontent.com/3678476/102773750-a996b300-4381-11eb-8ae0-868ddd32591d.png)


related https://github.com/framer/motion/issues/563

**Comment by PTaylour** [comment]
@aaronleopold yeah the CSS on my previous example was very geared towards it being a menu on the left.

Here's a shot at putting the resizable div on the right:

https://codesandbox.io/s/icy-architecture-1qtbz?file=/src/index.tsx


<img width="662" alt="image" src="https://user-images.githubusercontent.com/3678476/109960431-aa808500-7ce0-11eb-97d1-165748444bf7.png">



Arguably a cleaner implementation this way.

**Comment by aaronleopold** [comment]
@PTaylour Thank you so much!!
