### ISSUE TITLE
[BUG] AnimationPresence exit only works on direct descendants 

### ISSUE THREAD

**Issue by andrew-r-nf** [framer/motion#387]
**2. Describe the bug**

Exit animation doesn't work unless motion component is a direct descendant of `AnimationPresence`

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/peaceful-margulis-lnc6b

**4. Steps to reproduce**

- Click the +/- buttons and the animations should work as expected.
- Then uncomment the lines 9 and 20 
- Click the +/- buttons, the animation on mount works but the exit animation no longer works

**5. Expected behavior**

Exit animation to still work even if it's not a direct descendent 

**7. Environment details**

OS: macOs Catalina
Browser: Chrome 78.0.3904.70

**Comment by InventingWithMonster** [comment]
This is as per design. By uncommenting those lines you give `AnimatePresence` a single child which is never added or removed.

**Comment by deleteme** [comment]
The documentation has an example that matches this use case, but it does not mention anything about the exit animation not working. The presence of the `exit` prop implies that it is possible to animate the exit transition.

https://www.framer.com/api/motion/animate-presence/#animating-custom-components

```jsx
const Item = () => (
  <div>
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
    />
  </div>
)

export const MyComponent = ({ items }) => (
  <AnimatePresence>
    {items.map(({ id }) => (
      <Item key={id} />
    ))}
  </AnimatePresence>
)
```

**Comment by AHBruns** [comment]
@mattgperry this is a painful edge case if you don't know what's going on, any possibility of implementing this? If not, then this seems like a place where the docs could be improved. The example mentioned above should be removed, IMO.

**Comment by mattgperry** [comment]
Ah yeah I see the problem with example with the docs though I also think it’s important to show that the component with the exit animation can be nested, it’s just the component that’s unmounting that cant. 

It’s literally impossible to implement the latter in React though, which is why we have AnimatePresence.

**Comment by mattgperry** [comment]
I've updated the copy with a clarification.

**Comment by obinasBaba** [comment]
Any update on this issue? I think this is a serious BUG that no one gives notice of, or is it already resolved??

**Comment by mattgperry** [comment]
It isn’t a bug, it’s a fundamental limitation of React and the docs have been updated to clarify

**Comment by Jared-P-111** [comment]
This was so infuriating the docs have one word to describe the issue. Please spare the sanity of others and make a better explanation of the do's and don'ts with this. I lost 8 hours trying to figure out why I can't exit with nested components.

**Comment by Jared-P-111** [comment]
Now I know why your using GSAP in one of your examples. The lack of support, clarity and transparency just made me jump ship. Do yourself a favor and make this way way way more visible this edge case was an extremely painful experience. Reacts limitation or not it should be presented in a much more robust explanation. The fact that it is not raises eyebrows.
