### ISSUE TITLE
[BUG] PaddingTop animations with rem values are animating with px instead.

### ISSUE THREAD

**Issue by iamrane** [framer/motion#388]
When Im using variants and animating paddingTop with rem values, framer motion animate with px values.

https://codesandbox.io/s/framer-motion-sandbox-ylcop

Here is a nice placeholder to label animation I made.
When you type something in the input the input should add 1.3rem padding on it, but its add 1.3px instead.

**Steps to reproduce**

1. Go to https://codesandbox.io/s/framer-motion-sandbox-ylcop
2. Click on input field
3. Type something
4. Inspect element on the input element.

**Expected behavior**

The input should have 1.3rem paddingTop

**Comment by Darth-Knoppix** [comment]
Having the same problem.

I can reproduce the issue when using `useCycle` like:
```jsx
const [animate, cycle] = useCycle(
    {
      marginTop: '0rem'
    },
    {
      marginTop: '-10rem'
    }
  );
```
*Values are converted to pixel values incorrectly (-10px instead of -10rem) on animate.*

Issue also occurs with `padding` but **not** `top`, `left`, `bottom`, `right`.

**Comment by InventingWithMonster** [comment]
Can you try setting the prop via initial ad a rem value for now?

**Comment by Darth-Knoppix** [comment]
Setting the initial prop worked, thanks @InventingWithMonster.
