### ISSUE TITLE
[FEATURE] Documentation/example on how to work with virtualized UI items

### ISSUE THREAD

**Issue by carlosagsmendes** [framer/motion#389]
**Is your feature request related to a problem? Please describe.**
I'm trying to integrate layout transitions in a list virtualized with react-window to support a summary / details pattern (when I click on an item I want to show its details in fullscreen mode)

Since the items are virtualized, the animated transitions for items outside the initial viewport make it look as if the item is coming from (or returning to) a position outside the visible list (3rd and 4th items expanded on the animated example )

![a86d27b7-7817-4596-870a-a8fef18e0065-Virtualized720p](https://user-images.githubusercontent.com/1224078/68405226-9aea3e00-0177-11ea-8656-27178107bb2b.gif)

Here's a link to a [sample codesandbox](https://codesandbox.io/s/react-window-will-transform-h7020)

**Describe the solution you'd like**
It would be great to have an help section explaining how to deal with the enter/exit position of virtualized items. If you can provide some guidance I will be only glad to submit a documented working solution.

**Comment by mattgperry** [comment]
This looks improved with `layout` but still not ideal. What you want to do is instead of using variants, which are animated, change the position of each element with `style`. `layout` will figure out the animation itself.
