### ISSUE TITLE
[BUG] How to change the velocity of a MotionValue / useSpring

### ISSUE THREAD

**Issue by jimmy-e** [framer/motion#390]
I am trying to use the `useSpring` hook to change the velocity of my motion component, however, changing the velocity property won't make any difference.

[Code Sandbox](https://codesandbox.io/s/framer-motion-simple-animation-g4ndm)

e.g. changing `velocity: 1` to `velocity: 5` doesn't change the animation effects of my component.

```
import * as React from "react";
import { motion, useSpring } from "framer-motion";

const variants = {
  0: {
    top: "0rem"
  },
  1: {
    top: "4rem"
  },
  2: {
    top: "8rem"
  }
};

export const Example = () => {
  const springConfigs = {
    velocity: 1
  };

  const x = useSpring(0, springConfigs);

  return (
    <motion.div
      animate={position}
      className="childDiv"
      variants={variants}
      style={{ x }}
    />
  );
};

```

**Comment by InventingWithMonster** [comment]
In the attached example `x` never changes, you are animating `top`. The motion value should be set to `top`.
