### ISSUE TITLE
[BUG] Animation lags when hook and intercom widget are called at the same time

### ISSUE THREAD

**Issue by fhaussener** [framer/motion#391]
**Describe the bug**
I'm trying to create the animation, which can be seen in the CodeSandbox. It runs smoothly there, but in our app we call a hook and render the intercom widget at the same time, so it lags quite a bit. I found the `onAnimationComplete` prop in the docs, but not sure If that's the way to go. What's the best approach when having re-renders while the animation is running?

**To reproduce**
https://codesandbox.io/s/great-curie-mt834

**Expected behavior**
I expect to have a smooth animation without any lag.

**Environment details**
OS: MacOs Mojave
Browser: latest Chrome

**Comment by InventingWithMonster** [comment]
Yeah the work will need to be split up one way or the other. I would load Intercom `onAnimationComplete` too. At some point I want to introduce off-thread animations but WebAssembly isn't there yet.
