### ISSUE TITLE
[BUG] motion.custom passes props that is only used for internal use

### ISSUE THREAD

**Issue by Sandstedt** [framer/motion#394]
When using `motion.custom`, motion's props is passed down to it's children causing props being set to the DOM. For example the prop `animate` is also passed to the DOM's a-tag in this example:

https://codesandbox.io/s/agitated-franklin-605oh

(inspect the link to see the props being passed to the DOM element)

**Expected behavior:**
Only props that is not being used by `motion.custom` are passed down to it's custom element.

```js
const MotionLink = motion.custom(Link);

const App = () => {
  <MotionLink
    animate={{ opacity: 0.5 }}
    to="/"
    className="some-classname"
  >Settings</MotionLink>
}
ReactDOM.render(<App />, document.getElementById("root"));

// should render:
<a href="/" class="some-classname">Settings</a>

```
**Environment details**
Tested using the with react-router-dom `Link` element.
*framer-motion:* 1.6.15
*react-router-dom:* 5.1.2

**Comment by yudyananda** [comment]
any progress? I'm facing the same problem here when using `variants`

```js
const MotionLink = motion.custom(Link)

<MotionLink
     initial="hidden"
     variants={fadeInUp} 
     ...
 /`}>
     Foo
</MotionLink>

// output
<a variants="[object Object]" ...>Foo</a>
```

**Comment by AlexanderMelox** [comment]
Same here, still a problem for me. I opened up an issue yesterday on this. 
https://github.com/framer/motion/issues/853

**Comment by Sandstedt** [comment]
I could create s PR if that's helpful? @mattgperry  Seems like a simple fix (but probably isn't 😅)
