### ISSUE TITLE
[BUG][QUESTION] When animation is slow, can I reduce framerate?

### ISSUE THREAD

**Issue by tonicastillo** [framer/motion#396]
Hi 👋

I'm trying to animate a css property called "font-variation-settings". It works ok animating CSS variables, when using in a single motion component. But I need to animate in every single letter using motion.span (for a delay effect I need to do). This is very slow using Motion. Using animejs, for example, this works perfect.

You can see how it works here with Motion: https://codesandbox.io/s/framer-motion-css-variables-slow-example-iwkhe
You will see the animation starts on load.
The transition has 5 seconds, but real time is longer than that.

*CSS*
```css
span {
    ...
    font-variation-settings: "wght" var(--fontbold), "wdth" 250;
}
```

*JS*
```jsx
{"wght animated with long text".split("").map((letter, index) => (
  <motion.span
    ...
    style={{ "--fontbold": 100 }}
    animate={{ "--fontbold": 900, transition: { duration: 5 } }}
  >
    {letter}
  </motion.span>
))}
```

I'm testing with Chrome in Mac.

Can I reduce framerate for an optimal animation? I'm doing something wrong? Or another advice...
Thanks
🙏

**Comment by InventingWithMonster** [comment]
Hmm. I'm mostly interested in why this is performant with Anime.js. A quick look at the profiler shows that the JS is taking a minuscule amount of each frame's budget. The majority is layout, which would be the same with CSS/Motion/Anime.js. Have you got an example with Anime I can take a look at? This might help us make it more performant in Motion.

![image](https://user-images.githubusercontent.com/7850794/69238334-054ba700-0b98-11ea-8dff-dbbd06d579c2.png)

**Comment by tonicastillo** [comment]
Hi @InventingWithMonster . Thanks for your answer.

This is an animejs (not React) example: https://codesandbox.io/s/animejs-exampe-example-nqvp1
I don't know how to use CSS variables in AnimeJS, so I used an element attribute in every span and then a function every frame to pass this value to a style attribute. But you can see then animation, in every single span letter, works fine.

**Comment by InventingWithMonster** [comment]
Ah I understand what's going on. The performance is equal between the two but Framesync caps the max duration between any two frames at 40 milliseconds https://github.com/Popmotion/popmotion/blob/master/packages/framesync/src/index.ts#L59. This causes the animation duration to slow down, because every frame is taking a lot longer than 40ms.

I feel like this was written for a good reason but it was a couple of years ago now so the details are hazy. For now there's no way of changing this behaviour but I will consider removing the frame cap.

**Comment by tonicastillo** [comment]
Ok. I understand.
Do you think I can use a workaround?
Thanks

**Comment by InventingWithMonster** [comment]
No I don't think there is currently a workaround. Animating this property on so many elements is inherently slow and currently Motion is locked to 40ms max frame rate.

**Comment by tonicastillo** [comment]
Ok
Thank you anyway!
