### ISSUE TITLE
[BUG]: animations not re-rendering with react router 5.1+ and nested routes

### ISSUE THREAD

**Issue by laurencefass** [framer/motion#400]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

I've set up a very simple nested routing arrangement to test nested route animations.
https://codesandbox.io/s/react-router-animated-transitions-ku6r1

animations only work on the first route load. subsequent clicks on the top level framermotion menu item and its subroutes work without animations.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/react-router-animated-transitions-ku6r1

**4. Steps to reproduce**

Click the link above and navigate sub-routes of the FramerAnimation route to observe failing animations.

**5. Expected behavior**

Animations should repeat for each click of the FramerMotion component and its sub-routes. 

**6. Video or screenshots**

n/a

**7. Environment details**

codesandbox.

**Comment by hassenc** [comment]
You can try adding a key prop on the Switch : 
`<Switch location={location} key={location.pathname}>`
https://codesandbox.io/s/react-router-animated-transitions-qu8vd

**Comment by laurencefass** [comment]
many thanks
