### ISSUE TITLE
[FEATURE] Add support for `prefers-reduced-motion`

### ISSUE THREAD

**Issue by green-arrow** [framer/motion#401]
**Is your feature request related to a problem? Please describe.**

This is an issue from the `pose` library that I don't think ever made it in, but I would love to see it in framer motion: https://github.com/Popmotion/popmotion/pull/452

**Describe the solution you'd like**

Ideally, there would be an option to globally disable all animations, which would solve `prefers-reduce-motion` as well as disabling animations during tests, which is currently causing issues for me as well.

**Comment by green-arrow** [comment]
Additionally, I'd be happy to help implement / make a PR if someone can guide me in the right direction 😄

**Comment by soiluong** [comment]
The solution I had involved the “animate” attribute and to aggregate the animation objects to a global place or a single file. That way I could introduce a “simpler” or reduced animation option and allow the user to toggle between them.

**Comment by InventingWithMonster** [comment]
The logic does exist https://github.com/framer/motion/blob/master/src/dom/accessibility.ts

Before it's wired up there's some questions that need answering:

- What do we do in development mode for people who are using prefersReducedMotion?
- Is there an API to force motion on for all users?
- Do we only disable certain animations such as x/y/scale/rotate while converting into opacity animations like iOS?
