### ISSUE TITLE
layoutTransition vs positionTransition

### ISSUE THREAD

**Issue by ConneXNL** [framer/motion#402]
First of all, AWESOME to see you guys nailing the FLIP technique as from experience this seems to be really hard to get right without having tons of bugs!

Now to my issue with it...

The docs are not clear on when exactly **positionTransition** or **layoutTransition** triggers. The https://www.framer.com/api/motion/migrate-from-pose/#flip gives some more info on layoutTransition, however the api pages do not: https://www.framer.com/api/motion/component/#animationprops.layouttransition 

The problem I ran into is that **positionTransition** doesn't seem to be triggered in the same instances as **layoutTransition** is triggered. According to the _migrate from pose_  description of **layoutTransition**:
_This layout change can be instigated by any CSS application or DOM change, for instance:
Being adjacent to a resized component
Adding/removing a CSS class
Changing position in the DOM
Changing children_

So what triggers **positionTransition** ? What I seem to be missing is a way to have the above triggers work for positionTransition without having the scaling that layoutTransition brings. 

Additionally, I think it would be better to just go with a single option (for example _layoutTransition_) and give this some good defaults and and some props to configure WHEN you want it to trigger and WHAT you want to animate.

All in all, currently having them both next to each other is really confusing.

**Comment by InventingWithMonster** [comment]
Yeah I totally understand the confusion. `positionTransition` was made first when the feature only did changes in position, `layoutTransition` supports both size and position.

Internally, `positionTransition` uses `offsetTop`/`Left` to detect changes in position. Which is to say its position as measured relative to its nearest positioned parent.

`layouTransition` uses any visual bounding box change.

These are both useful independently so it might be that we expose the control of this in props at some point.

**Comment by ConneXNL** [comment]
@InventingWithMonster good to know! I wonder if making https://github.com/framer/motion/blob/master/src/motion/functionality/layout.ts#L314-L327 these lines optional for _layoutTransition_ would make it a "better" version of positioning without the hassle of having to deal with sizing distortions.

**Comment by o-alexandrov** [comment]
Probably, this issue should be closed, since both props:
- `positionTransition` and `layoutTransition`

were removed in:
- [Release [2.0.0] 2020-07-15
](https://github.com/framer/motion/blob/main/CHANGELOG.md#200-2020-07-15)
