### ISSUE TITLE
[BUG] Transform origin automatically set and changed on drag

### ISSUE THREAD

**Issue by rijk** [framer/motion#405]
Check out this sandbox: https://codesandbox.io/s/react-laag-tooltip-positioning-h7907

Note that the **first time** you’re dragging an item to a different position, there’s a subtle horizontal shift:

![Screen Recording 2019-12-09 at 21 33 12](https://user-images.githubusercontent.com/159500/70470784-1f5c1380-1acc-11ea-981f-ff5185ead574.gif)

This is caused by the changing of `transform-origin`. For some reason (I browsed through the source but couldn’t discover why) this is added automatically by framer-motion in this case. 

- The initial value is `transform-origin: 0% 50% 0px;`, 
- After dragging an item to another position it changes to `transform-origin: 50% 50% 0px;`. 
- After this, it stays the same.

Why does this happen, and how can I prevent it? Thanks!

**Comment by ConneXNL** [comment]
Ran into the same issue, but its not dragRelated, even if you transition without drag functionality it sets it to ` transform-origin: 50% 50% 0px;` after the first position/layout transition took place.

**Comment by pot-code** [comment]
No dragging related, but the transform origin value is override by default, it just ignored my settings in style prop

**Comment by pkrawc** [comment]
I'm finding this exact thing using the latest package.

The first time the `h4` animates it has the correct x and y positioning, but when you click on a tab, the origin is reset.

Sandbox: https://codesandbox.io/s/sharp-kowalevski-xelnd?file=/src/Header.js

**Comment by rijk** [comment]
This is no longer an issue when using the new [`layout`-based dragging implementation](https://codesandbox.io/s/framer-motion-2-drag-to-reorder-fc4rt), so I'm going to close this issue.
