### ISSUE TITLE
[BUG] onAnimationComplete not firing on staggered children

### ISSUE THREAD

**Issue by klase** [framer/motion#406]
When setting staggerChildren on a parent motion.div the children's onAnimationComplete is never triggered.

### CodeSandbox

https://codesandbox.io/s/dazzling-glitter-net34

### Steps to reproduce
Open codesandbox link, check console. When parent animation completes onAnimationComplete fires correctly but none of the events on children are logged.

###  Expected behavior

Children onAnimationComplete should trigger after their animations have run.

**Comment by amcdnl** [comment]
Also seeing this... ^ @mattgperry

**Comment by ortonomy** [comment]
seeing this still. just found it today
