### ISSUE TITLE
[BUG] Incorrect package.json version published for latest patch

### ISSUE THREAD

**Issue by rathpc** [framer/motion#408]
The latest patch release `1.6.18` was incorrectly published with `1.16.18` instead.

**Expected behavior**

package.json should have version `1.6.18`

![image](https://user-images.githubusercontent.com/5623579/70549451-3c332e00-1b42-11ea-877e-498f33b695c6.png)

**Comment by InventingWithMonster** [comment]
Thank you for pointing this out! Unpublished that and currently publishing
1.6.18

**Comment by prashnts** [comment]
Apologies for commenting on a closed issue, but just wanted to give a heads up that people who did upgrade to `1.16.18` (me!) will see yarn complain:

```
error Couldn't find any versions for "framer-motion" that matches "^1.16.18"
```

and would need to modify `package.json` manually. I'd suggest adding a note somewhere visible for people who run into this. Thanks for the great library though!
