### ISSUE TITLE
[BUG] `dragConstraints` doesn't work with a `ref` that is smaller than the element being constrained

### ISSUE THREAD

**Issue by timswalling** [framer/motion#411]
Dragging behaviour is buggy when the element provided as a ref to `dragConstraints` is smaller than the element being dragged.

**Steps to reproduce:**
1. Open this [minimal reproduction](https://codesandbox.io/s/drag-5tsri)
2. Click/tap on the translucent rectangular item (or its opaque square container) and begin dragging horizontally

**Expected behavior:**
The item will drag smoothly, but be constrained whenever the item ceases to completely cover the container, much like [this (faked) example](https://codesandbox.io/s/drag-wehuh).

**Actual behavior:**
The item jumps when being dragged, and is immediately constrained - see [screen capture](https://youtu.be/GG8_zae0igw).

**Environment details:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

**Comment by InventingWithMonster** [comment]
Agreed and thanks for the clear mock of expected behaviour.

**Comment by mattgperry** [comment]
Closing as this has been fixed for a while now and I missed this issue
