### ISSUE TITLE
Is there any way to transform strings with useTransform?

### ISSUE THREAD

**Issue by crn1** [framer/motion#412]
I didn't find it anywhere in the docs, so I'm asking it here. How do you combine some CSS filter, for example, invert, with `useViewportScroll` and `useTransform` hook? I noticed that you can put only numbers in `useTransform` and not filter strings like `invert(0)`. When I try to add filters I get:

`Error: 'invert(0)' is not an animatable color. Use the equivalent color code instead.`

This is code that replicates the error:
https://codesandbox.io/s/dry-butterfly-m888o

Is there some alternative to this?

**Comment by InventingWithMonster** [comment]
Yeah that is possible but for some reason it’s being detected as a colour.
This sounds stupid but could you try adding a space at the beginning of
both inverts?

**Comment by crn1** [comment]
I added the spaces. Still nothing.

**Comment by crn1** [comment]
One more thing: On my other project this approach does work but after a few file saves compiler it gives this error. Literally, sometimes the same code works but sometimes it doesn't.

**Comment by vassiliskrikonis** [comment]
> I didn't find it anywhere in the docs, so I'm asking it here. How do you combine some CSS filter, for example, invert, with `useViewportScroll` and `useTransform` hook? I noticed that you can put only numbers in `useTransform` and not filter strings like `invert(0)`. When I try to add filters I get:
> 
> `Error: 'invert(0)' is not an animatable color. Use the equivalent color code instead.`
> 
> This is code that replicates the error:
> https://codesandbox.io/s/dry-butterfly-m888o
> 
> Is there some alternative to this?

@crn1 I made your example work by using the first form of `useTransform` that takes just a `Transformer<T>` as a (second) argument

```
useTransform(scrollYProgress, v => `invert(${v})`);
```

**Comment by nathansearles** [comment]
@crn1 I was running into a similar issue. The suggestion that @vassiliskrikonis made seems to solve it.

Here's a working example:
https://codesandbox.io/s/css-filter-with-framer-motion-simplified-u0zkg

**Comment by crn1** [comment]
@vassiliskrikonis Yes, this solved it.

**Comment by Acccent** [comment]
Hi,

This was closed but the the solution is more of a workaround...
And the issue also exists with transform(), which doesn't have the overload which takes a function as a second argument.

The problem seems to be in [this file](https://github.com/Popmotion/popmotion/blob/master/packages/style-value-types/src/value-types/color.ts), `color.test` returns true even when the string doesn't actually describe a color. I'm not sure how to fix it. Any ideas?
