### ISSUE TITLE
[BUG] Code examples in docs need a different color theme

### ISSUE THREAD

**Issue by hmafzal** [framer/motion#415]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

The framer documentation text styling doesn't show up well in the docs. The font colors need to be updated to work better against a black background.

It would also be great if they were copy+pasteable!

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

N/A

**4. Steps to reproduce**

1. Go to https://www.framer.com/api/motion/
2. View the text color of the example code

**5. Expected behavior**

The code documentation is readable.

**6. Video or screenshots**

![image](https://user-images.githubusercontent.com/1441495/71023442-be869980-20d0-11ea-8ac8-3ef62cbe41bb.png)

**7. Environment details**

Using Chrome 78 on MacOSX

### `AnimatePresence` isn't working

Have all of its immediate children got a unique `key` prop that **remains the same for that component every render**?

```jsx
// Bad: The index could be given to a different component if the order of items changes
<AnimatePresence>
  {items.map((item, index) => <Component key={index} />)}
</AnimatePresence>
```

```jsx 
// Good: The item ID is unique to each component
<AnimatePresence>
  {items.map((item, index) => <Component key={item.id} />)}
</AnimatePresence>
```

Is the `AnimatePresence` correctly outside of the controlling conditional? `AnimatePresence` must be rendered whenever you expect an `exit` animation to run - it can't do so if it's unmounted!

```jsx
// Bad: AnimatePresence is unmounted - exit animations won't run
{isVisible && (
  <AnimatePresence>
    <Component />
  </AnimatePresence>
)}
```

```jsx
// Good: Only the children are unmounted - exit animations will run
<AnimatePresence>
  {isVisible && <Component />}
</AnimatePresence>
```

**Comment by InventingWithMonster** [comment]
@hmafzal Do you still see this?

**Comment by hmafzal** [comment]
@InventingWithMonster nope looks to be fixed

**Comment by InventingWithMonster** [comment]
Awesome thanks for letting me know
