### ISSUE TITLE
[BUG] Drag doesn't apply any unit conversion

### ISSUE THREAD

**Issue by angry-dan** [framer/motion#424]
**2. Describe the bug**

Motion doesn't convert non pixel units applied to elements before dragging begins.
This means that something like this won't work:

```
<motion.div
  initial={{ y: "100%" }}
  drag="y"
/>
```

Have a look at https://github.com/framer/motion/blob/master/src/behaviours/use-drag.ts#L373
In this case you'll get `origin[axis].get()` returning `"100%"`, and what should have been an arithmetic operation becomes a string concatenation (`"100%3"` for example).

I'm not entirely familiar with the source, but I have a feeling that somewhere around here: https://github.com/framer/motion/blob/master/src/behaviours/use-drag.ts#L436, where the origin motion values are initialised, there should also be a unit conversion.

I sort of hacked around this with an onDragStart handler and a gross oversimplification of unit-type-conversion.ts - https://codepen.io/angry-dan/pen/NWPwPQZ - which works for now, but I really think this should be dealt with by the library.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codepen.io/angry-dan/pen/povdwvr

**4. Steps to reproduce**

1. Go to https://codepen.io/angry-dan/pen/povdwvr
2. Try to drag the element, note that you can't
3. Stop dragging, note the drag end transition converts the initial percentage to a px value and then further drags are possible.

**5. Expected behavior**
Dragging even the first time should be possible.

**Comment by InventingWithMonster** [comment]
Yeah I agree this should be handled by the library, I'll see what we can do.

**Comment by DanielRoeven-Intunio** [comment]
Any update on this? 🙂 Would love to use  `rem`s to set initial and animation variants on a draggable component. I currently worked around this by querying the document's root font size, storing it in a state variable `remPixelValue`, and manually performing the unit conversion. But that breaks down when the documents root font size changes (it seems like the updating the variants prop doesn't trigger a rerender).

**Comment by angry-dan** [comment]
Hi, with the release of v2 (2.4.1), I can confrim that this is still happening for me. Here's an even simpler test case 

```
<motion.div drag="x" animate={{ x: "10%" }} />
```

https://codesandbox.io/s/framer-motion-simple-animation-forked-evzqz

Also, the source of that unexpected string concatenation has moved slightly: https://github.com/framer/motion/blob/main/src/gestures/drag/VisualElementDragControls.ts#L435

Hope this helps. Sorry, I don't have a reliable workaround at this time and still feel too out of my depth to safely introduce any unit conversion (presumably this should happen once, when the drag starts?)

**Comment by angry-dan** [comment]
Whilst I still don't have a workaround, this might be of interest - here I'm using the new `layout` prop to update an element's position within a grid once dragging is done. Which does at least start to allow for "snap to grid" style dragging 👍 

https://codesandbox.io/s/framer-motion-simple-animation-forked-7x8zy?file=/src/Example.tsx

**Comment by mmintel** [comment]
same issue with `4.0.3`
