### ISSUE TITLE
[BUG] event.stopPropagation() doesn't stop parent animations

### ISSUE THREAD

**Issue by IljaDaderko** [framer/motion#425]
**The bug**

I have 2 nested motion elements: Card with a button inside of it. Card has animated scale on `whileTap` and button has animated opacity with `whileTap` as well. I might be wrong but shouldn't handling of buttons `onClick` event with `event.stopPropagation()` allow to not trigger animation on its parent?

I added codesandbox below, if you click on button you will see it animate alongside card. What I was hoping to achieve there was to not animate parents scale when I tap on the button.

**CodeSandbox reproduction of the bug**

https://codesandbox.io/s/thirsty-field-edduh

**Steps to reproduce**

1. Go to provided sandbox
2. Click on on the button
3. You will see both elements animate

**Expected behavior**

adding `event.stopPropagation()` should not animate parent component?

**Comment by hegelstad** [comment]
Hi @IljaDaderko, you closed this. Did you find a solution? I am struggling with a similar issue and would love to hear what you did.

**Comment by IljaDaderko** [comment]
@hegelstad I just attached pointer down listener to the element I wanted to stop propagation on (https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener)

**Comment by hegelstad** [comment]
@IljaDaderko Thank you, looks like it did the trick!

**Comment by Peterabsolon** [comment]
@xzilja This is an thread, I know. Care to comment how you actually did it? If I do `onPointerDownCapture={(e) => e.stopPropagation()}` on either Card or Button the tap animation no longer works?
