### ISSUE TITLE
Drag Inertia applies min, max to both x and y

### ISSUE THREAD

**Issue by vassiliskrikonis** [framer/motion#427]
I'd like to ask what's the purpose of single number min, max of Inertia on drag transition which changes both x and y. The current behaviour seems to apply it to both values but I'm not sure it should be this way.

**Comment by InventingWithMonster** [comment]
You can specify a different min and max by setting a different transition for both x and y

```
dragTransition={{
  x: { min: 0 },
  y: { min: -100 }
}}
```
