### ISSUE TITLE
[FEATURE] GSAP Timeline like feature

### ISSUE THREAD

**Issue by atiyahio** [framer/motion#428]
I was wandering around if there's a way to set up a gsap timeline-like feature in framer motion and couldn't get to it.

is it already implemented or not? also if not, will you guys work on it anytime soon and if there's a workaround for now?

**Comment by hassenc** [comment]
Take a look at keyframes: https://www.framer.com/api/motion/animation/#keyframes
Is that what you're looking for ?

**Comment by atiyahio** [comment]
> Take a look at keyframes: https://www.framer.com/api/motion/animation/#keyframes
> Is that what you're looking for ?

is there's an example including keyframes? because it seems right

**Comment by hassenc** [comment]
Here is an example: 
https://codesandbox.io/embed/framer-motion-keyframes-ekks8?codemirror=1

In the times array 0 means animation start and 1 means the total duration (in this case 2s)

**Comment by atiyahio** [comment]
Perfect! thanks. :)
