### ISSUE TITLE
[BUG] Conditionally block scrolling for single-axis draggable elements 

### ISSUE THREAD

**Issue by InventingWithMonster** [framer/motion#429]
If a user tries to touch scroll on a horizontally-draggable element we currently have to block scrolling due to issues with event handlers. It might be possible to control this with the `touch-action` CSS prop https://mobile-first-animation.netlify.com/49

**Comment by FlorinSenoner** [comment]
Duplicate of #185

**Comment by dminkovsky** [comment]
This is generally true for any element where `touch-action: none` has been set to support correct behavior of `whileTap`:

* If `touch-action: none` **is not set**, you can begin a scroll from the item on a touch device, but then `whileTap` behavior is broken (does not end the tap when scrolled away).
* If `touch-action: non` **is set**, you can't scroll if your scroll starts on an element (scroll does not start), but then `whileTap` works.

**Comment by InventingWithMonster** [comment]
Fixed in `2.7.3`
