### ISSUE TITLE
[BUG] whileHover variant doesn't always propagate to children 

### ISSUE THREAD

**Issue by Dremora** [framer/motion#431]
**2. Describe the bug**

Image a hierarchy of two motion components, where the parent has both `whileHover` variant and `onHoverStart` callback defined. If `onHoverStart`, while being called, results in the change of its own value due to the containing component being re-rendered, `hover` variant will function correctly on the parent but won't be propagated to the child. The codesandbox provided below should make this more clear.

Same behaviour applies to `onHoverEnd`.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/interesting-wildflower-5qk26

Try replacing `onHoverStart` and `onHoverStop` callbacks with their commented out and memoized versions — this eliminates the bug. 

**4. Steps to reproduce**

1. Hover over the first line of text. Background color becomes gray (as defined on the parent), text color becomes red (as defined on the child).
2. Hover over the second line of text. Only the background color changes.
3. Hover again over the first line of text. Once again, only the background color changes.
4. Move the mouse pointer up and then hover again over the first line. Both colors will change.

**5. Expected behavior**

Both background and text color change on hover.

**Comment by mattgperry** [comment]
This seems to have been fixed in the meantime.
