### ISSUE TITLE
[FEATURE] useChain ability for framer motion

### ISSUE THREAD

**Issue by Mellis84** [framer/motion#432]
Is there a way to chain animations together? React Spring has something called useChain and other examples would be GSAP's timeline? would be great to know how to start an animation when another has finished without using delays or anything like that.

**Comment by InventingWithMonster** [comment]
Animations return a promise, so you can chain animations using `async`/`await`:

```javascript
const controls = useAnimation()

async function animation() {
  await controls.start({ x: 0 })
  await controls.start({ x: 100 })
  return await controls.start({ backgroundColor: '#000' })
}
```

And then those in turn become composable.
