### ISSUE TITLE
[BUG] variants api in Iphone 6,7,8 plus

### ISSUE THREAD

**Issue by ducanh2110** [framer/motion#433]
**1. Describe the bug
I have a problem with variants effect while using iPhone 6,7,8 plus. The others device work fine but in iphone 6,7,8 plus the effect need to touch again the screen or scroll then the sidebar or nav will show. Please help me tks so much

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/framer-motion-side-menu-mx2rw?fontsize=14&module=%2Fsrc%2FExample.tsx

With this example in iphone 6,7,8 it's not working with the background. Please help me to fix it please.

**Comment by InventingWithMonster** [comment]
Can't reproduce this on an iPhone 7. Clip path doesn't work in Safari currently though so the background won't animate, which might be confusing the example but the items show/leave as expected.

**Comment by ducanh2110** [comment]
I have test on chrome in iphone 6,7,8 it's still not working @InventingWithMonster. Always need to do something like scrolling or touching then the hidden div show.
