### ISSUE TITLE
[BUG] Memory leaks in SSR with next

### ISSUE THREAD

**Issue by nathanredblur** [framer/motion#434]
# The useTransform bug framer-motion@1.7.0

A lot of MotionValues is retained generating a memory leak in server side render (SSR) on request several time a single page.

this is the test case:

```tsx
import { useViewportScroll, useTransform } from 'framer-motion';

const IndexPage: NextPage = () => {
  const { scrollYProgress } = useViewportScroll()
  const heroBackgroundSize = useTransform(scrollYProgress, value => `auto ${value*100+100}%`)
  return (
    <div>hello</div>
  )
}
export default IndexPage
```

going deep in this problem I found that if you don't use `useTransform` the problem is gone.
and then I try to destroy the motion value and that works too.

`if (!process.browser) heroBackgroundSize.destroy()`

clearly useTransform is not destroying the listeners when the page is destroyed. 

Also I test the same but creating all inside a component consumed by the index page and the problem persist.

**Comment by nathanredblur** [comment]
this issue is present in browser too on navigate between several pages that use `useTransform`. 

I solve this in client on manually destroying this too throw a react.useEffect:
`React.useEffect(() => () => {if (heroBackgroundSize) heroBackgroundSize.destroy()}, [])`

this is how the memory leak looks in chrome. 

![image](https://user-images.githubusercontent.com/1273018/72382673-c6455800-36e7-11ea-87dc-e1111e2a72b4.png)

after apply my solution the Set and MotionValues disappear. 

reviewin the sourcecode for `useTransform` I can see that is using a `useMemo` but I can't see any `useEffect` so, I don't understand how framer-motion safely remove the attached children and handlers associated to the MotionValue once the component that call it is destroyed. 

https://www.framer.com/api/motion/motionvalue/#motionvalue.destroy 
But the documentation say something different, so maybe i'm not reading this right or this information is wrong because I'm not creating manually a new MotionValue.

**Comment by InventingWithMonster** [comment]
Thanks for diving into this. I'll have to take a look into this, I'm not sure how to correctly destroy the motion value given that useEffect won't run on the server.

**Comment by InventingWithMonster** [comment]
This is a tough one to determine. How are you measuring server side memory consumption?

In Chrome, running this code:

```jsx
class ObviousName {}

const LeakyComponent = () => {
    const a = useMemo(() => {
        return new ObviousName()
    }, [])

    console.log(a)

    return <div />
}

export const App = () => {
    const [key, setKey] = useState(0)
    return (
        <div>
            <LeakyComponent key={key} />
            <button onClick={() => setKey(key + 1)}>Flush</button>
        </div>
    )
}
```

And then searching for `ObviousName` in the Memory panel will also show that we have an increasing number of `ObviousName` class instances every time we flush the leaky component. This is even after forcing garbage collection using the trash can icon in the Memory panel.

**Comment by nathanredblur** [comment]
1. You are right I did a mistake on write my comment. This is what i'm doing to deal with this memory leak.
```
if (!process.browser) heroBackgroundSize.destroy()
React.useEffect(() => () => { if (heroBackgroundSize) heroBackgroundSize.destroy() }, [])
```
the first line is for fix the issue in the server, the second is for browser in case the React not destroy the MotionValue.

2. Because I'm using Next, for measuring the Memory in server I have this custom server script to run next.

```
const { createServer } = require("http");
const { parse } = require("url");
const next = require("next");

const port = parseInt(process.env.PORT, 10) || 3000;
const dev = process.env.NODE_ENV !== "production";
const app = next({ dev });
const handle = app.getRequestHandler();

const heapdump = require("heapdump");

app.prepare().then(() => {
  createServer((req, res) => {
    const parsedUrl = parse(req.url, true);
    const { pathname, query } = parsedUrl;

    if (pathname === "/___heapdump") {
      heapdump.writeSnapshot(function(err, filename) {
        console.log("dump written to", filename);
        res.writeHead(200, { "Content-Type": "text/plain" });
        res.write("OK");
        res.end();
      });
    } else {
      handle(req, res, parsedUrl);
    }
  }).listen(port, err => {
    if (err) throw err;
    console.log(`> Ready on http://localhost:${port}`);
  });
});
```
now you take a one heap dump  and then you can use your favorite script or manually trigger many request to the index and again generate another heap dump.

I will try your example too, something dark is happening around useMemo but, are we using it right? because react documentation says "If no array is provided, a new value will be computed on every render." or maybe react is deciding re-calculate the value often but because is a class attach to some other values is not removed, also react doc says:

" In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components."   
https://reactjs.org/docs/hooks-reference.html#usememo

not sure what is happening or how to solve it but I will here to help as much as I can.
thanks @InventingWithMonster

**Comment by InventingWithMonster** [comment]
Are you still seeing this? `useTransform` has been rewritten in the meantime so I'm wondering if that's changed anything.

**Comment by mattgperry** [comment]
Closing this but feel free to reopen if you're still encountering this.
