### ISSUE TITLE
Appling styling to an element only while it is animating: onAnimationStart triggered by non-Framer animations

### ISSUE THREAD

**Issue by tommhuth** [framer/motion#436]
I'm using Framer Motion with Reach Router to do page transitions. To do custom handling whenever an element is exiting or entering (to prep the element for animation, like `position: absolute`), I use the callbacks for `onAnimationStart` and `onAnimationComplete`. However, `onAnimationStart` seem to be triggered by other non-Framer Motion animations as well.  See  CodeSandbox https://codesandbox.io/s/elated-fog-23h6i where callback for `onAnimationStart` is confused by child CSS animation.

More specifically, this is my usecase: One of my screens has a fairy long animation that takes over 1s to finish (long after the actual animation done thru this lib), and when that CSS only driven animation ends, `onAnimationComplete` seem to be called twice. This is the order of calls:

1. Page enters, and  `onAnimationStart` is called
2. Page is done, and `onAnimationComplete` is called (600ms has now passed)
3. Other child component of Page now has a pure CSS animation that finishes, and `onAnimationStart` is now called twice. (around ~2s have now passed)

If I remove that animation, everything works like expected and only 1 and 2 happens. If I make the animation longer, the events still match up like above. 

The documentation makes it clear that these callbacks are only supposed to be called for properties in `animate,` and `onAnimationComplete` is also named differently, but that is not true for `onAnimationStart`.  Even so, capturing events in the custom component and doing `e.stopPropagation()` did not help. 

Is there something I'm missing here? Is this a  documentation problem? Essentially I  need to apply styling to an element _while_ it is animating, but not persist beyond that, how could I then do that without using these events?

**Comment by InventingWithMonster** [comment]
`onAnimationStart` isn't correctly filtered out of the props before being passed to the underlying DOM component, and because it has the same name as an actual DOM event this is causing the issue.
