### ISSUE TITLE
[BUG] Laggy in Firefox

### ISSUE THREAD

**Issue by visualcookie** [framer/motion#441]
**Description**

When using `framer-motion`, all used animations are lagging on Firefox, even the ones from the Example page. I've tried it on Chromium and saw no issue whatsoever in a laggy animation. FPS also seem fine (28-30fps).

**CodeSandbox**

Even tho you require a CodeSandbox for reproduction, it's not actually needed, as this also happens with the Examples on the Framer Motion page (or Docs). https://www.framer.com/api/motion/examples/

Code example I'm using as of now:
```js
const variants = {
  open: { opacity: 1, y: 0 },
  closed: { opacity: 0, y: '15px' },
}
```

```jsx
<motion.div initial={false} animate={shareBarVisible ? 'open' : 'closed'} variants={variants}>
  <ShareBar>
    <QuickShareBar>
      <FacebookShareButton url="https://google.com/">
        <FacebookIcon size={32} round />
      </FacebookShareButton>
      <TwitterShareButton url="https://google.com/">
        <TwitterIcon size={32} round />
      </TwitterShareButton>
      <EmailShareButton url="https://google.com/">
        <EmailIcon size={32} round />
      </EmailShareButton>
    </QuickShareBar>
  </ShareBar>
</motion.div>
```

**Steps to reproduce**

1. Go to https://www.framer.com/api/motion/examples/
2. Scroll down to any animation
4. See laggyness

**Expected behavior**

The animation should not be laggy. See following Video: https://streamable.com/g97k9

**Video**

Current behavior in Firefox:
https://streamable.com/m392r

**Environment details**

OS: macOS Catalina
Browser: Firefox Developer Edition (recent public build)

**Comment by InventingWithMonster** [comment]
Hmm yeah this is really noticeable. Thanks for letting me know, I'll look into it.

At first glance I reckon something is skipping every other frame. As the "laggyness" looks pretty consistent to me, possibly a solid 30fps.

**Comment by InventingWithMonster** [comment]
Closing as wontfix (cantfix). This is really crazy but Firefox is throttling all requestAnimationFrame animations until the page is interacted with (scroll and then replay the first animation to see)

**Comment by visualcookie** [comment]
@InventingWithMonster Did you change something on your animations?

**Comment by InventingWithMonster** [comment]
No it’s the same page. They started running smoothly when I clicked or
scrolled, I can’t remember.

**Comment by visualcookie** [comment]
Weird, tried that on the examples page, but still experience the laggyness.

**Comment by stolinski** [comment]
I'm also experiencing laggy animations in FF. Using Developer edition 73.0b12 (64-bit)

**Comment by iamawebgeek** [comment]
Noticing some micro freezes as well, using FF 72.0.2

**Comment by michelecocuccio** [comment]
Hello. I have created a light-box for React which is now available as npm package. In my next release I am going to move from React Transition Group to Framer Motion as I really want to add physic animations for the slides. I am noticing that on FireFox the animation is super laggy. On Edge, Chrome and Safari they run smoothly. There are two things that I have noticed:

I am using framer motion to animate two things: 
1) the main div containing the light-box which has a ```position: fixed```, it's just animating the opacity. The background-color of the div can be an rgba value passed by the user. 

2) the images that the user navigates through. In this case I am using ```<AnimatePresence />``` The image will slide left or right.

So I have noticed that if I change the position from "fixed" to "absolute" the animation runs smoothly. Please check this video:
https://drive.google.com/file/d/1HOOqYbGeA1GTnvO_D3r7xLAWBbjtHe8P/view

Also I have noticed that the animation seems very laggy if I have a background color with an rgba value on it with some transparency.  Please, check this short video:
https://drive.google.com/file/d/1vgP_brwRezuOLG3ngtDRIpFqR8ILnkmf/view

that's really odd! I need that position to be fixed as the main purpose of a light-box is to stay "fixed". I haven't released the new version to the public yet but I am planning to do so very soon and I will share the demo on code sandbox. 

Thanks

**Comment by GauravRajSharma** [comment]
this is still a major issue concerning framer-motion. animation works with all other major browsers but the laggyness of animation is still prominent in Firefox v78.0.2 (64-bit). any solutions concerning this? framer-motion is really nice and fun to work it, but Firefox support is a must.

**Comment by NasTomkinson** [comment]
@GauravRajSharma I managed to alleviate some of the laggyness by turning off smooth scroll in the Browser settings. While its not a direct fix, hopefully it helps in getting an resolution to this issue overall.

**Comment by visualcookie** [comment]
What did it for me was setting `privacy.resistFingerprinting` to `false` in the `about:config`. Apparently that also worked for `react-spring` animations, as things that were using `react-spring` in my code were not even showing up.

I know it's only a temporary fix, but maybe it helps the guys behind this library to figure out a way to actually remove the laggyness.

**Comment by InventingWithMonster** [comment]
Crazy find! Here's the bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1394735#c1

**Comment by InventingWithMonster** [comment]
This can be fixed on a per-site basis by serving content with the following headers:

```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```

From https://developer.mozilla.org/en-US/docs/Web/API/Performance/now#Reduced_time_precision

**Comment by visualcookie** [comment]
> This can be fixed on a per-site basis by serving content with the following headers:
> 
> ```
> Cross-Origin-Opener-Policy: same-origin
> Cross-Origin-Embedder-Policy: require-corp
> ```
> 
> From [developer.mozilla.org/en-US/docs/Web/API/Performance/now#Reduced_time_precision](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now#Reduced_time_precision)

Neat idea. How will this work with SPA applications deployed to Heroku, Vercel and Co?

**Comment by olegKusov** [comment]
When it will be fixed? Very laggy on firefox

**Comment by visualcookie** [comment]
> When it will be fixed? Very laggy on firefox

My guess is, that you should ask this to the Firefox devs, since this is a Firefox specific issue.

@mattgperry solution would only be a temporary fix. And I'm not sure, if setting fixed HEADERS should be done by a 3rd party JavaScript package.

**Comment by jacob-jacob-jacob** [comment]
I have set `privacy.resistFingerprinting` and `privacy.reduceTimerPrecision` to `false`, as suggested in https://developer.mozilla.org/en-US/docs/Web/API/Performance/now#reduced_time_precision
I checked if the performance timer stopped rounding and it does:
```
performance.now()
146902.152954
```
Unfortunately the animation is still laggy, see here:
![Peek 2021-03-09 19-42](https://user-images.githubusercontent.com/80355116/110521065-989f4780-810f-11eb-9236-f16c42008f05.gif)
hed gif)
the animation is very basic:
```
      <motion.div ....
        animate={{scale: [1.3, 1.6]}}
        transition={{
          duration: 1, repeatType: "reverse", repeat: Infinity
          }}
      >
```
and works in chromium.
I like the library, but I am not able to use it if it has no Firefox support.

**Comment by visualcookie** [comment]
> I have set `privacy.resistFingerprinting` and `privacy.reduceTimerPrecision` to `false`, as suggested in https://developer.mozilla.org/en-US/docs/Web/API/Performance/now#reduced_time_precision
> I checked if the performance timer stopped rounding and it does:
> 
> ```
> performance.now()
> 146902.152954
> ```
> 
> Unfortunately the animation is still laggy, see here:
> ![Peek 2021-03-09 19-42](https://user-images.githubusercontent.com/80355116/110521065-989f4780-810f-11eb-9236-f16c42008f05.gif)
> hed gif)
> the animation is very basic:
> 
> ```
>       <motion.div ....
>         animate={{scale: [1.3, 1.6]}}
>         transition={{
>           duration: 1, repeatType: "reverse", repeat: Infinity
>           }}
>       >
> ```
> 
> and works in chromium.
> I like the library, but I am not able to use it if it has no Firefox support.

If you just have a simple animation like that, why even referring to this lib? You could do this with CSS Transitions. The lib itself should only be considered, when you have a toggle and conditionally animate upon that.

**Comment by HappyGentle** [comment]
Hi I am a super beginner running into the same problem, I have adopted @visualcookie 's suggestion to add the COOP and COEP headers to enable the high precision timer, yet the problem persisted on **Firefox (Mobile mode / on Mobile device only)**. 

May I ask @visualcookie  whether you have resolved this problem completely? Thank you!

I am using Next js hosted on Vercel and I added the headers via next.config.js 

```javascript
//next.config.js

module.exports =  {  
 async headers() {
    return [
      {
        source: '/',
        headers: [
          {
            key: 'cross-origin-opener-policy',
            value: 'same-origin',
          },
          {
            key: 'cross-origin-embedder-policy',
            value: 'require-corp',
          },
        ],
      },

 //... other configs

 }
```

Evidence of high precision timer is successfully turned on via adding COOP and COEP:

<img width="159" alt="Screenshot 2021-04-22 at 9 23 10 AM" src="https://user-images.githubusercontent.com/67846537/115641898-90f8d280-a34c-11eb-8297-88af0d0081f3.png">

<img width="418" alt="Screenshot 2021-04-22 at 9 22 46 AM" src="https://user-images.githubusercontent.com/67846537/115641920-9a823a80-a34c-11eb-8f8d-03b6c1022559.png">

**Comment by opohorel** [comment]
Has anyone found any other possible solution to this problem?
Passing COOP and COEP headers achieved nothing in my project and some of my animations remain choppy.
Weirdly enough I experience this only on yoyo animation that changes scale, other animations are completely fine.

**Comment by erenkulaksiz** [comment]
Hello,
I've been using Framer Motion for my sideproject for a while. I've built a sidebar with width animation on collapse. Theres nothing wrong with it and it works amazing. But theres one catch: when content is filled with stuff, sidebar width animation starts to lag out. I could'nt figure out why, on other routes which has lower components than the laggy route's components and on those routes, sidebar width animation isn't laggy at all.
I know the best choice here is to build sidebar animation width with CSS, but i still want to use framer motion for this task, because when i switch to CSS, theres no point having a big chunky animation library on my project :D

**Comment by Jervx** [comment]
Today 2024 and it's not yet fixed. It was the reason I stopped using Firefox. 2 years ago when I was learning framer motion in react, I wasted a lot of time trying to find my mistake, but it turns out it's the browsers doing. The code was just simple motion.div with a variant that has initial and animate, just to make things short, I am animating a basic opacity : 0 to 1. It flickers at the end when the animation is almost done.

**Comment by Jervx** [comment]
It's 2024 today, and yet, there's still no fix. This was the reason I stopped using Firefox. Two years ago, when I was learning Framer Motion in React, I wasted a lot of time trying to find my mistake, but it turned out it was the browser's fault. The code was just a simple motion.div with a variant that had initial and animate properties. To keep it short, I was animating a basic opacity change from 0 to 1. It flickers at the end when the animation is almost done

**Comment by HarjjotSinghh** [comment]
Still no fix. Here is another comparison:

## Firefox

https://github.com/user-attachments/assets/5d6f3c67-98b9-484d-96e5-e94e2b36579b

## Chrome/Any Chromium-Based Browser

https://github.com/user-attachments/assets/8bb500b5-daa0-45b1-bdd5-261fe4a36560

**Comment by ectrc** [comment]
https://github.com/user-attachments/assets/08b8f4a7-a81f-4244-9445-f16ceb94ed6e

Same issue with a site I created.

**Comment by Lordfirespeed** [comment]
This is such a bizarre bug, especially as it seems to persist when all the firefox privacy options are disabled (and `performance.now()` is therefore yielding accurate, precise results).

**Comment by visualcookie** [comment]
> This is such a bizarre bug, especially as it seems to persist when all the firefox privacy options are disabled (and `performance.now()` is therefore yielding accurate, precise results).
> 
> https://transforms.framer.wiki/ very obviously reproduces this issue. But https://codesandbox.io/p/sandbox/framer-motion-usescroll-with-spring-smoothing-75rw1l is perfectly fine.
> 
> Should we open a bug on Mozilla's tracker? Would they even consider it, with it being so unspecific? We seemingly have no idea what causes this problem any more.

Per default, Firefox has hardware acceleration turned on. I've not been using framer-motion for quite some time, but it would be a try to turn that off and see, if that maybe fixes the issue.

**Comment by Lordfirespeed** [comment]
> Per default, Firefox has hardware acceleration turned on. I've not been using framer-motion for quite some time, but it would be a try to turn that off and see, if that maybe fixes the issue.

Sadly, no dice. I've had hardware acceleration disabled for some time.

**Comment by erenkulaksiz** [comment]
> Hello, I've been using Framer Motion for my sideproject for a while. I've built a sidebar with width animation on collapse. Theres nothing wrong with it and it works amazing. But theres one catch: when content is filled with stuff, sidebar width animation starts to lag out. I could'nt figure out why, on other routes which has lower components than the laggy route's components and on those routes, sidebar width animation isn't laggy at all. I know the best choice here is to build sidebar animation width with CSS, but i still want to use framer motion for this task, because when i switch to CSS, theres no point having a big chunky animation library on my project :D

Its been two years since my last comment, I want to add a comment on this because i saw this issue on my inbox. I can say that the code you write affects general performance of your application, especially if you have framer motion involved. Use memos and callbacks more. Dont be concerned if your animations aren't smooth in firefox, your 5K monthly user base will use 2.54% firefox potentially (~100 people) and its not a big of a deal. Also, try using gsap, give it a shot, its neat.

**Comment by ectrc** [comment]
@erenkulaksiz This issue is not just the result of "bad code" as the issue persists on the main framer preview site. I daily drive firefox and is very annoying when having to open a separate browser just I can develop in peace. To just ruin the experience for a minority of people due to either lazyness or not wanting to care is crazy to me.

**Comment by ivanjeremic** [comment]
I think this video explains everything. [Firefox is hard to love](https://www.youtube.com/watch?v=mmjUlFIaNLE&t=841s)

**Comment by Lordfirespeed** [comment]
Great quotes from Theo in this video/description:
- "Firefox just isn't a great browser." 
- "[...] my hatred, my deep disdain for the current state of Firefox [...]"
- "[...] I don't know if you Firefox users are delusional, stupid, or just, what, but [...]"
- "it doesn't [function]. It's horrifying."

Oh boy 😂😂

**Comment by mr-cheffy** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=2008324
