### ISSUE TITLE
[FEATURE] Performance Guide

### ISSUE THREAD

**Issue by mulholio** [framer/motion#442]
I've been creating some great animations with `framer-motion` but I've run into a couple of cases where the animations aren't as performant as I'd like.

I'd love to have some resources which advise on how to increase the performance and smoothness of animations: best practices, common pitfalls and so on. I'm not having great results with the React profiler.

I'm struggling to find advice on this lib through blog posts/Google so some advice from the author(s) would be greatly appreciated.

**Comment by InventingWithMonster** [comment]
Have you got some code examples of some poor performing animations? I think this is a great idea in general, but I would say the performance advice is the same here as it is for most web animations ie try to stick to transforms/opacity etc

**Comment by mulholio** [comment]
Hmm, building some now but not sure how speedy it would be to extract them into a CodePen.

I'm getting some lag with some animations that only use `x` transforms atm so not really sure where to look next to improve things.

Thanks for the quick response.

**Comment by samtgarson** [comment]
I've also struggled to find advice on this, beyond what has been mentioned on this thread already.

I'm no React/browser expert and I'm experiencing significant lag on a new animation heavy, personal site that I've just started on.

I haven't had time to pull out a codepen but you can see an example [here](https://next.samgarson.com/) and the code [here](https://github.com/samtgarson/portfolio-next) (there's not a lot of it).

Not asking for specific help on this thread but just `+1`ing the idea! I feel like there might be some obvious and easily-avoidable gotchas that would be worth documenting for less animation-experienced folks.

**Comment by mattgperry** [comment]
I'm closing this as it isn't Motion-specific but I am adding the idea to a roadmap plan that I'm putting together, I think it's a good one.

**Comment by GavanWilhite** [comment]
Was this ever completed? I'm having some crazy-slow (2 FPS?) layoutId-based scaling animations happening on a very simple next.js website, and I don't know where to start with diagnosing the problem.

**Comment by kb1995** [comment]
+1 this thread. I'm using framer motion for the first time and the hero section animation is very laggy on first load then afterwards it's fine. Would love to read a doc about how to potentially optimize it
