### ISSUE TITLE
[BUG] positionTransition doesn't get called when an adjacen element changes its height

### ISSUE THREAD

**Issue by tretyakvl** [framer/motion#444]
**2. Describe the bug**

In the example below the same motion component behave differently depending on how deep it is in the tree. The one higher doesn't transition when an adjacent element changes its height.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/condescending-swirles-xsn09

**4. Steps to reproduce**

1. Go to the sandbox above
2. Click toggle 1 button
3. Observe

**5. Expected behavior**

I expect the outside div in the example to transition its position.

**Comment by InventingWithMonster** [comment]
Closing as `positionTransition` has been removed. With the new `layout` prop you can group sections of the tree using `AnimateSharedLayout`.
