### ISSUE TITLE
[BUG] "Jerky" movement if updating `y` motionValues when scrolling

### ISSUE THREAD

**Issue by lintonye** [framer/motion#448]
**2. Describe the bug**
I'm trying to make an item "sticky" when scrolling. I have a motionValue `y` created with `useTransform`.

The scrolling only  works reasonably well in Chrome. In Safari or Firefox, the image becomes “jumpy” while scrolling.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/romantic-sammet-sxx7c

**4. Steps to reproduce**

1. Scroll the view

**5. Expected behavior**

Smooth "sticky" effect while the list is being scrolled

**6. Video or screenshots**

https://youtu.be/sLwiXbYAgQg

**Comment by InventingWithMonster** [comment]
I think this is a limitation of when the browser lets us know that there's been a page scroll. Hopefully the new `ScollTimeline` API will let us do this with a higher performance.
