### ISSUE TITLE
[BUG] AnimatePresence doesn't unmount component if no motion component detected

### ISSUE THREAD

**Issue by sathya9897** [framer/motion#449]
**Describe the bug**
If the top level component of a page is not a motion component and has all the required props of motion, then there is no warning or error in console. The URL updates but page doesn't load.
I am using `styled-components` with `framer-motion` in my Next.js project. In one of the pages I forgot to pass `motion.div` in `styled()` which happens to be my top level component of that page. There should be a warning or error which could help detect the problem easily, as it took me 2 days to figure out what was going wrong.

**A CodeSandbox reproduction of the bug**
https://codesandbox.io/s/nextjs-page-not-loading-8cf9x

**Expected behavior**
Expected to see a error or warning in the console and page should have been loaded with animations missing.

**Comment by InventingWithMonster** [comment]
Thanks for the report and reproduction. Renamed the ticket to reflect what's actually going on here. There is normally an error thrown here if no `motion` component is detected within `AnimatePresence`. I think this is probably preferable than silently unmounting the component.
