### ISSUE TITLE
[FEATURE] useAnimation() get current value of animated element

### ISSUE THREAD

**Issue by Mellis84** [framer/motion#450]
Basically (this might already be possible), it would be great to be able to get the current value of an animated element, for instance: 

```
  useEffect(() => {
    if (isHovered) {
      controls.start(i => ({
        opacity: [0, 1, 0, 0],
        scale: [0, 1, 0, 0],
        rotate: [0, 180],
        transition: {
          delay: i * 0.3,
          loop: Infinity,
          duration: 1.2,
          repeatDelay: 0.5,
        },
      }))
    } else {
      controls.start({
        opacity: 0,
        rotate: // When hovering out, get the current rotate value to set
      })
    }
  }, [isHovered])
```
When hovering out from the animated element, i'd like to grab the current rotate value to be set instead of say, setting it back to 0, so I can just fade the element out instead of it spinning it back to 0.

**Comment by mattgperry** [comment]
Sorry it's taken over a year to respond to this 😄 but the signature for the dynamic `start` is actually

```
(custom, current, velocity) => Target
```

So you can fish the current value from the second arg.
