### ISSUE TITLE
[BUG] onPanEnd is never fired on touch devices (or even screencast)

### ISSUE THREAD

**Issue by alielkhateeb** [framer/motion#452]
### Description

When I'm using `<motion.div onPan={onPan}/>` the function `onPan` is working perfectly fine on desktop, but when I use a phone (or any touch device), the function `onPan` is called infinitely, `onPanEnd` never fires basically.

### CodeSandbox 

https://codesandbox.io/s/polished-hill-qyixt
This codesandbox basically has a small grey div (which is my `motion.div` element), and a `text` state that shows the state of the interaction, so it'll be one of three 
- panning never started
- panning
- panning  ended

### Steps to reproduce

1. Go to https://qyixt.csb.app/
2. Start the devTools
3. Toggle Screencast
4. Start panning in the grey area
5. Stop panning
6. Watch the `text` value or your console

### Expected Behavior

I expect it to have the same behavior as the desktop version, `onPanEnd` should be fired and `onPan` should stop firing when I release the mouse click/touch

![expected](https://user-images.githubusercontent.com/20101678/73570881-428db880-44a8-11ea-9f90-eedfb7af8297.gif)

### GIF (Showing the bug)

![bug](https://user-images.githubusercontent.com/20101678/73570610-9e0b7680-44a7-11ea-881a-d7de17a9b6d4.gif)

### Environment Details

OS: Windows 10 (64-bit)
Browser: Chrome - Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by vdjurdjevic** [comment]
Any news on this? This is blocking issue

**Comment by markdesign** [comment]
still happening on latest 1.10.3

**Comment by mattgperry** [comment]
You need to add some kind of `touch-action: none` or similar rule. This isn't something we can take an opinion on as you might want it only on one axis. I've got a note coming through in the docs to update with this info.
