### ISSUE TITLE
[BUG] AnimatePresence unmounts all exiting components after first finished exit animation

### ISSUE THREAD

**Issue by Torsten85** [framer/motion#455]
AnimatePresence unmounts all motion components that should exit with a transition after the first component finished said transition. It does not correctly respects duration / delay.

https://codesandbox.io/s/framer-motion-simple-animation-dqh5n

**Steps to reproduce**

simply click on the refresh icon

**Expected behavior**

AnimatePresence should unmount each component individually as soon as their exit transition is completed.

**Comment by mattgperry** [comment]
Fixed in latest
