### ISSUE TITLE
[FEATURE] Objects with drag enable prevent page scroll

### ISSUE THREAD

**Issue by cesarvarela** [framer/motion#458]
I'm using this for a horizontally draggable object that covers the entire width of the device,  and this works beautifully, but seems to disable the natural touch scroll of the page, when touching said object

**Comment by FlorinSenoner** [comment]
Duplicate of #429

**Comment by mattgperry** [comment]
This has been fixed since

**Comment by denishotii** [comment]
@mattgperry can you please explain to me where exactly this has been fixed? Because I just ran into the same problem!

The element with drag, doesn't allow me to scroll the page! (On touch screen devices).
