### ISSUE TITLE
[FEATURE] Negative delay?

### ISSUE THREAD

**Issue by valerioleo** [framer/motion#460]
**Is your feature request related to a problem? Please describe.**
CSS transition allows using a negative delay prop that results in the animated component _causing the transition to begin immediately but to cause the transition to seem to begin partway through the animation effect_. (definition taken from https://stackoverflow.com/a/41493482)

From my experiments, it looks like Framer does not allow for negative delay. I have also created a sandbox [here](https://codesandbox.io/s/framer-motion-simple-animation-ziwmd): where the second box has a negative delay, but it starts at the same point of the box without a delay.

**Describe the solution you'd like**
The possibility to apply a negative delay to specify where to start the animation.

**Describe alternatives you've considered**
I couldn't find any alternative.

**Comment by mattgperry** [comment]
This could be achieved by leveraging Popmotion's `elapsed` prop rather than rolling our own `delay` logic

**Comment by voland62** [comment]
Definitely, "must have" feature! This is strange that it is not supported...

**Comment by mattgperry** [comment]
Negative delays are supported as `7.9.0`
