### ISSUE TITLE
[BUG] style-prop ignores conditions if motion value is passed

### ISSUE THREAD

**Issue by Marcel-Konjata** [framer/motion#461]
When we pass a dynamic value with motionValue/useTransform/scrollY into style-prop with conditions, after the condition is met for the 1st time, style prop ignores if the condition is changed.

example code:
```
const ScrollCalc = () => {
  const { scrollY } = useViewportScroll();

  const dynamicHeight = useTransform(scrollY, [0, 79], [0 + 350, 79 + 350]);
  const isMobile = useMedia(`(max-width: 470px)`);
  return (
    <>
      <h2>should be height dynamic? {isMobile ? "no" : "yes"}</h2>
      <Container
        style={{
          height: !isMobile ? dynamicHeight : 500,
          backgroundColor: !isMobile ? "purple" : "goldenrod"
        }}
      />
    </>
  );
};
```
after changing media query in this case from mobile to above, it works as expected. However if you resize back to mobile it will never go to 500px.
If you start with media query larger than mobile in this case, height will never be static.
I have tried it with other conditions, and every dynamic way as useSpring, useTransform etc.
Result remains same

codesandbox link: https://codesandbox.io/s/sharp-chaplygin-7m5og

**Comment by dminkovsky** [comment]
I played with this a bit it and it looks like if you wrap the `500` in `MotionValue` using `useMotionValue` it works as you expect: https://codesandbox.io/s/happy-goldwasser-ctrd1 (I changed 500 to 100 to make the difference more obvious). Haven't dug into the code, but it seems like it doesn't let you go back to non-MotionValue values after a MotionValue has been used.

**Comment by mattgperry** [comment]
This has been fixed some time since
