### ISSUE TITLE
[FEATURE] Animating pure data like Number, string, obj etc.

### ISSUE THREAD

**Issue by yokiijay** [framer/motion#464]
```
...
<motion.div>
{num}
</motion.div>
```
How may I animating { num } from 0 to 100  in 1s?  
Is there an existing api to manipulate? please help.

**Comment by mc-petry** [comment]
It's easy to write something like:

```tsx
function NumberAnimation() {
  const _content = useRef<HTMLDivElement>(null)
  const handleUpdate = useCallback((v: { to: number }) => {
    _content.current!.innerText = v.to.toFixed()
  }, [])

  return <motion.div
    ref={_content}
    animate={{ from: 0, to: 100 }}
    onUpdate={handleUpdate}
  />
}
```

**Comment by mackattack3k** [comment]
I think this question has also been answered in #505

**Comment by mackattack3k** [comment]
Just found this hook that you could use as well [useAnimatedState](src/animation/use-animated-state.ts)

**Comment by InventingWithMonster** [comment]
I wouldn’t recommend useAnimatedState, it’s an internal API that I’ll
delete at random. We do want to solve this properly at some point.

**Comment by mattgperry** [comment]
You can use `animate` to perform arbitrary animations.

**Comment by Noitidart** [comment]
> You can use `animate` to perform arbitrary animations.

Can you please show example.

**Comment by Noitidart** [comment]
> You can use `animate` to perform arbitrary animations.

Oh I came up with this example, does it look right? Does modifying the `span.textContent` cause issues in react? Or is it safe? Or is it safer to do `setState`?

```
function Num() {
  const spanRef = useRef();

  useEffect(() => {
    const intl = new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 })
    const controls = animate(0, 9000, {
      duration: 2,
      ease: 'easeOut',
      type: 'tween',
      onUpdate: value => {
        spanRef.current.textContent = intl.format(value.toFixed());
      }
    })
  
    return () => {
      controls.stop();
    }
  }, [spanRef])

  return <span ref={spanRef}>0</span>
}

**Comment by mattgperry** [comment]
Lgtm - as 0 never changes as far as react knows this should be safe and it’ll perform better not using setstate

**Comment by Noitidart** [comment]
Thanks very much for your constant support of this library and all our questions!

**Comment by Noitidart** [comment]
> It's easy to write something like:
> 
> ```tsx
> function NumberAnimation() {
>   const _content = useRef<HTMLDivElement>(null)
>   const handleUpdate = useCallback((v: { to: number }) => {
>     _content.current!.innerText = v.to.toFixed()
>   }, [])
> 
>   return <motion.div
>     ref={_content}
>     animate={{ from: 0, to: 100 }}
>     onUpdate={handleUpdate}
>   />
> }
> ```

I think using innerText is less performant than textContent as seen in this stackoverflow post - https://stackoverflow.com/a/35213639/1828637 - so maybe should prefer textContent.
