### ISSUE TITLE
[BUG] Restarting animation onDragEnd, value seems randomly different

### ISSUE THREAD

**Issue by mysterybear** [framer/motion#465]
Restarting an animation using animation controls with onDragEnd seems to affect the motion values in an undesirable way, as here:

![gif of the behaviour](https://raw.githubusercontent.com/mysterybear/framer-drag-reanimate/master/framer-drag-re-animate-2.gif)

[CodeSandbox here](https://codesandbox.io/s/github/mysterybear/framer-drag-reanimate)

[GitHub repo here](https://github.com/mysterybear/framer-drag-reanimate)

**Comment by mysterybear** [comment]
Tried adding `controls.stop()` inside `onDragStart`, does not resolve.

**Comment by mattgperry** [comment]
This sandbox doesn't seem to work for me but feel free to reopen if this isn still not working
