### ISSUE TITLE
[BUG] exitBeforeEnter breaking when children have no exit animation

### ISSUE THREAD

**Issue by KondakovArtem** [framer/motion#466]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
I have problem with using Redirect in React router. 
I use standart example with react-router and add Redirect component.

When i open url "/test", it correctly redirected to "/" but animation not started, and nothing happened

https://codesandbox.io/s/framer-motion-x-react-router-mu294

1. Go to '/test'
2. Page redirected to "/"
3. Nothing happens

**5. Expected behavior**
Start animation of main page

**Comment by m4tta** [comment]
I've run into this same issue today.

**Comment by evstinik** [comment]
+1 here

**Comment by lightyen** [comment]
I found a trick:
```tsx
const MotionRedirect: React.FC<RedirectProps> = ({ children, ...props }) => (
    <motion.div exit="undefined">
        <Redirect {...props} />
    </motion.div>
)
```
DEMO: [https://codesandbox.io/s/react-router-framer-motion-dr4u6](https://codesandbox.io/s/react-router-framer-motion-dr4u6)

**Comment by deebov** [comment]
same problem

**Comment by alecbignell** [comment]
I'm having this same issue in a case where a component will conditionally render a redirect. In a case where you directly navigate to the page by URL, the default usecase will cause the condition to return the redirect, and it has the same issue, once redirected the component doesn't show.

Using the workaround above solved this.

**Comment by EugeneBugor** [comment]
It is also an urgent problem for my case. Would be good if you guys can investigate the issue 🙏 @InventingWithMonster

**Comment by enzozerega** [comment]
Thanks @lightyen !! Your answer was really helpful. I also was having issues with the `<Redirect />` and `<AnimatePresence />` components. And wrapping the `<Redirect />` component into a `<motion />` component with `exit="undefined"` did the trick. In my code, where I had defined my app routes, what I did was:
```jsx
import { Fragment } from "react";

<AnimatePresence initial={false} exitBeforeEnter>
    <Switch location={location} key={location.key}>
        <Route exact path="/" component={Home} />
        <Route path="/about" component={About} />
        <Route path="/contact" component={Contact} />
        <Route path="/not-found" component={NotFound} />
        <motion.Fragment exit="undefined">
            <Redirect to="/not-found" />
        </motion.Fragment>
    </Switch>
</AnimatePresence>
```

**Comment by alimzhanovamir** [comment]
When will you solve the problem?
