### ISSUE TITLE
[BUG] unused variants prevent animation from running

### ISSUE THREAD

**Issue by noisyneuron** [framer/motion#467]
The presence of unused variants prevents the initial animation from running.. ie 
```
variants={{"farLeft": {opacity:0},"center": {opacity:1}}}
initial={{opacity:0}}
animate={{opacity:1}}
exit={{opacity:0}}
```
Removing the line `variants={{"farLeft": {opacity:0},"center": {opacity:1}}}` results in the expected behavior. [CodeSandbox](https://codesandbox.io/s/heuristic-minsky-i2kjo)

**Comment by mattgperry** [comment]
Fixed in the meantime
