### ISSUE TITLE
[BUG] Click on draggable component stops animation

### ISSUE THREAD

**Issue by dimitriirybakov** [framer/motion#471]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

When I click on draggable component animation stops, but onDragStart and onDragEnd doesn't get called.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

You can try it in one of your examples:
https://framerbook.com/x/animation/example-animations/35-swipe-to-delete/
https://codesandbox.io/s/framer-motion-example-35-z9hqi?module=%2Fsrc%2FExample.tsx

**4. Steps to reproduce**

1. Go to https://framerbook.com/x/animation/example-animations/35-swipe-to-delete/
2. Drag item and release it.
3. While animation is going try to click on it.
4. See that animation is stopped

**5. Expected behavior**

Animation should not stop or onDragStart and onDragEnd should be called (if it considered as another dragging)

**6. Video or screenshots**

https://monosnap.com/file/KQGFJT4A9EqmQoWXXMOKCWYLy29nhI

**7. Environment details**
Google Chrome 79.0.3945.130

**Comment by InventingWithMonster** [comment]
This is intended behaviour. Pressing on a moving component should be enough to stop it/catch it. But pressing without moving isn't enough to constitute a drag gesture.

**Comment by dimitriirybakov** [comment]
This is intended for who? I don't think it's intended for user. Why can't we handle this situation? If it "isn't enough to constitute a drag gesture" why can't we continue animation?

**Comment by YasharSL** [comment]
Hi, 
I am having the same issue. is there a way to disable this behavior?

**Comment by Dima9473** [comment]
Hi,
I faced the same issue. Is there any updates?
