### ISSUE TITLE
[BUG] layoutTransition is not detected

### ISSUE THREAD

**Issue by Fxlr8** [framer/motion#479]
**Describe the bug**
The height of the block changes because of increased amount of children, but `layoutTransition` is not transforming the scale.

**CodeSandbox reproduction of the bug**
https://codesandbox.io/s/solitary-voice-7uv1e

**Steps to reproduce**

1. Go to example above
2. Click on `make bigger` and `make smaller` buttons to change content size and see how the `layoutTransition` reacts to this change

**Expected behavior**
The scale should be animated in both cases.

**Comment by InventingWithMonster** [comment]
Hey there. Thanks for the clear example! The technical reason this is happening is because state changes are local to `Block`, so in the second example re-renders that trigger a new layout are happening without the knowledge of layoutTransition. This will be fixed with the magic motion feature.

**Comment by chapster11** [comment]
What is magic motion ? Having a similar issue with adding a child to parent and parent not getting layoutTransition when new element is added.
