### ISSUE TITLE
[BUG] AnimatePresense behaves differently from 1.9.1 to 1.10.0

### ISSUE THREAD

**Issue by zubinkhavarian** [framer/motion#487]
**Describe the bug**
I noticed after upgrading from **1.9.1** to **1.10.0** that the behavior of **AnimatePresence** has changed.

This is with respect to the _Notifications_ example on the website under _UI Patterns_ here: https://www.framer.com/api/motion/examples/#ui-patterns

The unmount animation on 1.9.1 has a smooth repositioning of the notifications that remain after one of the notifications is closed.

The same unmount animation on 1.10.0 is not smooth.

**CodeSandbox reproduction of the bug**
1.9.1: https://codesandbox.io/s/framer-motion-notifications-ijc7b
1.10.0: https://codesandbox.io/s/framer-motion-notifications-3ype9

**Steps to reproduce**
1. Go to each of the examples above
2. Click on the big round "+" button in the CodeSandbox browser to create a couple of notifications
3. Close a notification that is between others
4. You'll see in 1.9.1 that after the closed notification goes completely off-screen, the remaining notifications reposition smoothly. In 1.10.0 this repositioning isn't smooth and they rather snap.

**Note:** The only difference between the two code sandboxes is the package version in package.json. No other code was modified from the original CodeSandbox example here: https://codesandbox.io/s/framer-motion-notifications-5cvo9

**Expected behavior**
The position transition behavior shouldn't change between the two versions. I believe this is controlled by the `positionTransition` prop on the child <motion.*> element which for some reason is being ignored.

**Comment by dminkovsky** [comment]
Experiencing this as well. `(position|layout)Transition` do not work when wrapped in `<AnimatePresence/>`. I'm guessing we should downgrade to 1.9.1 and wait for 2.0.0.

**Comment by InventingWithMonster** [comment]
I'm gonna take a look at this now

**Comment by dminkovsky** [comment]
Oh cool. Thank you.

This lib is already great and 2.0.0 looks... magical. Border radius without heart ache.
