### ISSUE TITLE
[BUG] whileTap doesn't register click events on the edges

### ISSUE THREAD

**Issue by qazsero** [framer/motion#488]
**2. Describe the bug**
This bug has already been in the previous Popmotion library, I'm struggling for a year now searching for an override for this.

If you have an icon hooked with motion, and you include a whileTap and an onClick event, the whileTap gets always registered, but the onClick doesn't if you click on a location of the icon that's close to the limits but you can still see a pointer as a cursor.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/nostalgic-shaw-e0mq3

**4. Steps to reproduce**

Steps to reproduce the behaviour:
1. Go to the codesandbox and open the console
2. Click on the edges of the first play button or in the area where the icon is not drawn but your cursor changes to a pointer
3. You will see that a console log is not always registered, while the same click at the same location of the second icon will always register a click event.

**Video**
![](https://media.giphy.com/media/KeJTPCUUNK2PhucZfT/giphy.gif)

**5. Expected behaviour**

I expect that, if I click on an icon with whileTap, independently on the area of the icon where I click, if a whileTap event has been registered, an onClick event has to be registered as well.

**7. Environment details**

This has been tested in macOS, Windows, on Firefox, Chrome, in the versions that have been released since at least April 2019.

**Comment by mattgperry** [comment]
Closing this as it's more of a browser bug, similar to hover flickering you might get if you scale down as a result of hover and then hover over the edges. 

One thing you can do, is wrap the component in an element that never changes size during the tap and give it the `whileTap` definition and the `onClick`. Then animate the `scale` of the icon child via variants.
