### ISSUE TITLE
[BUG] Text deformations using Magic Motion (2) and CSS Grid

### ISSUE THREAD

**Issue by Sandstedt** [framer/motion#494]
**# Description of bug**

When translating between states using the beta version of magic motion, text inside CSS grid containers stretches out  while scaling (like a regular FLIP child scaling "bug"/effect)

**# CodeSandbox reproductions of the bug**

With CSS grid (not working):
https://codesandbox.io/s/framer-motion-magic-motion-expandable-article-test-with-css-grid-failing-le7je

With flexbox (working):
https://codesandbox.io/s/framer-motion-magic-motion-expandable-article-test-width-flex-6qf94

**I also notices issues when using the same React Node. But I guess this is a different bug?**

Modal version - CSS grid (not working):
https://codesandbox.io/s/framer-motion-magic-motion-expandable-article-test-failing-e9jwl

Modal version - flexbox (not working)
https://codesandbox.io/s/framer-motion-magic-motion-expandable-article-test-failing-7edc0

Modal version - flexbox - seperate React Node with matching magicId (working perfectly!):
https://codesandbox.io/s/framer-motion-magic-motion-expandable-article-test-working-7u712

** # Steps to reproduce**

1. Create a motion.div with a magicId, CSS grid and a box a text inside
2. Change the padding on the motion.div
3. The text scales incorrectly

**# Expected behavior**

Expect the text to use a scale effect that is inverted of the parents FLIP animation (when the parent has a CSS grid property).

**# Environment details**
Framer Motion 2.0.0-beta.31
React 16.3.1
Tested in Chrome 80, Edge 80 and Firefox 74 on Windows 10

**Comment by InventingWithMonster** [comment]
Thanks for the report! I’ll have to take a closer look but my first
intutition is that within CSS grid the text bounding box doesn’t closely
wrap the text which makes it impossible to correctly measure the text. This
will be more of a documentation thing as there’s no real fix for this but
like I say I’ll take a closer look.

**Comment by Sandstedt** [comment]
Yeah I thought so too, tried to break it by wrapping the text in a motion.span to try to work around that. But didn't work, and not sure how the measurements is made under the hood. 

And yes there are sollutions to work around it. But always good to document these kind of things for other people to find out, and perhaps it's a solvable bug. These things are so tricky.

(You can close this if you don't have time to look at it)

**Comment by InventingWithMonster** [comment]
Ah yeah, the `motion.span` thing might work if you style it `display:
inline-block` as `display: inline` elements don't accept a `transform`.

**Comment by Sandstedt** [comment]
Ah duh! Of course 🤦‍♂️. Here's a new version with two solutions:
https://codesandbox.io/s/framer-motion-magic-motion-expandable-article-test-with-css-grid-working-voi2k

**Solution 1:** Wrap the text in a `motion.span` with a `display: inline-block`
**Solution 2:** Set `justify-items: start` on the parent that has the CSS grid

Closing :) Thanks for the feedback and good luck with the launch!
