### ISSUE TITLE
[BUG] Drag events do not extend beyond the document bounds

### ISSUE THREAD

**Issue by aron** [framer/motion#496]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

Currently the drag events do not extend beyond the bounds of the current document when using framer motion within an iframe. This is because the mousemove & mouseup handlers registered for the drag need to be attached to the document (see [example](https://beta.framer.com/projects/Drag-Bug-ecHHO0hHGAFbIQK50MvO)) in order for the mousemove events to extend beyond the iframe. 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-drag-with-constraints-pjn6t?fontsize=14&module=%2Fsrc%2FExample.tsx

**4. Steps to reproduce**

1. Open the [drag demo](https://codesandbox.io/s/framer-motion-drag-with-constraints-pjn6t?fontsize=14&module=%2Fsrc%2FExample.tsx) for framer-motion in CodeSandbox 
2. Try dragging beyond the boundary of the preview iframe, the drag events stop once the cursor moves outside of the iframe.

**5. Expected behavior**

Expect the drag to continue beyond the bounds of the iframe.

**6. Video or screenshots**

N/A

**7. Environment details**

macOS/Chrome but same issue for all browsers.

### `AnimatePresence` isn't working

Have all of its immediate children got a unique `key` prop that **remains the same for that component every render**?

```jsx
// Bad: The index could be given to a different component if the order of items changes
<AnimatePresence>
  {items.map((item, index) => <Component key={index} />)}
</AnimatePresence>
```

```jsx 
// Good: The item ID is unique to each component
<AnimatePresence>
  {items.map((item, index) => <Component key={item.id} />)}
</AnimatePresence>
```

Is the `AnimatePresence` correctly outside of the controlling conditional? `AnimatePresence` must be rendered whenever you expect an `exit` animation to run - it can't do so if it's unmounted!

```jsx
// Bad: AnimatePresence is unmounted - exit animations won't run
{isVisible && (
  <AnimatePresence>
    <Component />
  </AnimatePresence>
)}
```

```jsx
// Good: Only the children are unmounted - exit animations will run
<AnimatePresence>
  {isVisible && <Component />}
</AnimatePresence>
```

**Comment by InventingWithMonster** [comment]
Fixed in `1.10.3`
