### ISSUE TITLE
[BUG] `motion.custom` is passing its props to the DOM element

### ISSUE THREAD

**Issue by zeckdude** [framer/motion#497]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

`motion.custom` is passing its props to the DOM element as attributes

```js
const CustomButton = forwardRef(({ children, ...props }, ref) => {
  return <button {...props} ref={ref}>{children}</button>
});

const MotionCustomButton = motion.custom(CustomButton);
```

```js
<MotionCustomButton 
  onClick={() => setHasBeenClicked(true)}
  initial={{ backgroundColor: '#ffffff' }}
  animate={{
    backgroundColor: hasBeenClicked ? '#52A078' : '#ffffff'
  }}
  transition={{
    duration: 3
  }}
>
  {children}
</MotionCustomButton>
```

The animation works great, but the `initial`, `animate`, and `transition` props are being added as attributes on the button DOM element.

```js
<button initial="[object Object]" animate="[object Object]" transition="[object Object]" style="background-color: rgb(255, 255, 255);">Yo there!</button>
```

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://stackblitz.com/edit/framer-motion-attrs-example

**4. Steps to reproduce**

1. Open the stackblitz link
2. Check out the `Button.js` file

I also couldn't find any docs about `motion.custom()` either, so those need to be added. 

**5. Expected behavior**

The rendered button shouldn't have the props added as attributes

**6. Video or screenshots**

None

**7. Environment details**

Max OSX

### `AnimatePresence` isn't working

N/A

**Comment by streamside** [comment]
I stumbled across this problem as well. When reading the source code it looks like it checks if the component to render matches `typeof Component === 'string'`. In the case when `motion.custom()`is used an objects is returned and hence the props are not removed properly.

As a work around I currently wrap the component to animate in a `<div>` / `<span>`.

Example:

````
// Non-working example
const MotionButton = motion.customer(MyButton);
return <MotionButton whileHover="hover" ... />

// Workaround
return (
  <motion.span whileHover="hover" ...>
    <MyButton ...>
  </motion.span>
);
````

Code reference:
https://github.com/framer/motion/blob/e34612ccafc79592d64f9f494b23e8d95eff568c/src/motion/functionality/dom.tsx#L108

**Comment by streamside** [comment]
Related to #394.

**Comment by InventingWithMonster** [comment]
Yeah I feel like the isDOM check could be run to see if we optionally use Emotion's prop filtering, but otherwise always filter out Motion's props

**Comment by mattgperry** [comment]
Dupe https://github.com/framer/motion/issues/394
