### ISSUE TITLE
[FEATURE] Disable Animations on mobile, or selected breakpoint

### ISSUE THREAD

**Issue by dongepulango** [framer/motion#499]
Would be nice if you can disable animations on mobile or selected media breakpoint. Or have separate animations on mobile and desktop.

**Comment by InventingWithMonster** [comment]
We probably won’t make specific API for this in the near term, but it’d be simple to incorporate with a useBreakpoints hook https://www.google.com/search?q=use+breakpoint+hook&rlz=1CDGOYI_enGB710GB710&oq=usebreakpoint&aqs=chrome.2.69i57j0l3.5305j0j4&hl=en-GB&sourceid=chrome-mobile&ie=UTF-8
