### ISSUE TITLE
[BUG] Animate based on state doesn't work until user hovers off button

### ISSUE THREAD

**Issue by zeckdude** [framer/motion#500]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

While hovering over a button, if you click on the button and change the state, the `animate` styles that are based on the changed state don't get animated until the user hovers off the button.

```js
const DeclarativeAnimationsButtonDemo = () => {
  const [hasBeenClicked, setHasBeenClicked] = useState(false);

  return (
    <motion.button
      onClick={() => setHasBeenClicked(true)}
      animate={{
        backgroundColor: hasBeenClicked ? '#3E9AA9' : '#ffffff'
      }}
      whileHover={{
        backgroundColor: hasBeenClicked ? '#3E9AA9' : '#ecb7dc'
      }}
      transition={{
        duration: 0.35
      }}
    >
      Using declarative animations
    </motion.button>
  );
}
```

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://stackblitz.com/edit/framer-motion-hover-animate-problem

**4. Steps to reproduce**

1. Open the stackblitz link

**5. Expected behavior**

The styles in the `animate` should override the `whileHover` when the state changes. 

I was able to make it work using the `useAnimation` hook, but I would prefer to use a declarative approach in this situation if possible. 

```js
const ImperativeAnimationsButtonDemo = () => {
  const [hasBeenClicked, setHasBeenClicked] = useState(false);
  const [isHovered, setIsHovered] = useState(false)
  const controls = useAnimation();

  useEffect(() => {
    if (isHovered && !hasBeenClicked) {
      controls.start({
        backgroundColor: '#ecb7dc',
      })
    } else {
      controls.start({
        backgroundColor: hasBeenClicked ? '#3E9AA9' : '#ffffff'
      })
    }
  }, [isHovered, hasBeenClicked])

  return (
    <motion.button
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      onClick={() => setHasBeenClicked(true)}
      animate={controls}
      transition={{
        duration: 0.35
      }}
    >
      Using imperative animations
    </motion.button>
  );
}
```

If this is not a bug, then I would like for it to be feature request please.

**6. Video or screenshots**

None

**7. Environment details**

Max OSX

### `AnimatePresence` isn't working

N/A

**Comment by mattgperry** [comment]
This should be fixed in the latest versions, please reopen if not
