### ISSUE TITLE
[BUG] Unable to swap motionValue with regular value 

### ISSUE THREAD

**Issue by bmcmahen** [framer/motion#504]
Once a motion value is set on a style, I'm unable to swap it out with a non motion-value. This is an issue in v1.10.3, and the latest v2 beta.

```jsx
export default function App() {
  const [dragging, setDragging] = useState(0);
  const x = useMotionValue(0);

  return (
      <motion.div
        onPanStart={() => setDragging(true)}
        onPan={(e, info) => {
          x.set(info.offset.x);
        }}
        onPanEnd={() => setDragging(false)}
        style={dragging ? { x } : { x: 0 }}
      />
  );
}
```

The expectation here is that when dragging ends, the `x` position is reset to `0`. Instead, it remains at whatever the motion value is set at.

Codesandbox:
https://codesandbox.io/s/mystifying-oskar-20gig

This example is a bit contrived, but it's relevant when wanting to trigger FLIP animations using either `layoutTransition` or the `magic` feature of v2.

**Comment by mattgperry** [comment]
Since been fixed
