### ISSUE TITLE
[FEATURE] Searchable docs

### ISSUE THREAD

**Issue by mittnavnermike** [framer/motion#508]
Thank you for a great tool! I love using it.

**Is your feature request related to a problem? Please describe.**
I'm spending a lot of time in the docs trying to find the thing that I'm looking for. For me it is hard to find it through the menu due to many of the same things are described in different places. E.g:
https://www.framer.com/api/motion/animation/#variants and https://www.framer.com/api/motion/examples/#variants

**Describe the solution you'd like**
A search bar for the docs.

**Comment by mattgperry** [comment]
Since been fixed
