### ISSUE TITLE
[BUG] AnimatePresence adds extra elements to the DOM 

### ISSUE THREAD

**Issue by AlexanderMelox** [framer/motion#510]
Using AnimatePresence around a list render in React adds extra and duplicated DOM nodes.

In the picture above you can see that the react dev tools states I have 2 items in the array but it seems that AnimatePresence is exponentially adding dom nodes into the list

Link: https://codesandbox.io/s/lucid-germain-f2du3?file=/src/App.js
steps to replicate.

1. Add an item
2. It should be adding extra dom elements (this is the bug)
3. If you remove AnimatePresence it doesn't add the extra dom elements but now I can't use AnimatePresence

**Expected behavior**

AnimatePresence should animate groups of elements on dom removal and additions.

**6. Video or screenshots**

<img width="1679" alt="Screen Shot 2020-04-16 at 11 02 06 AM" src="https://user-images.githubusercontent.com/12755042/79486381-3bbd0f00-7fdc-11ea-9230-c8b7338d8479.png">

<img width="1679" alt="Screen Shot 2020-04-16 at 11 02 19 AM" src="https://user-images.githubusercontent.com/12755042/79491063-7d04ed00-7fe3-11ea-885a-4fa10b99f61a.png">

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12755042/79491261-cce3b400-7fe3-11ea-8552-e190d4e37ec2.gif)
<i>In this gif you can see that I have one item in the "cart" I click add item and AnimatePresence adds 2 elements. I quickly check my dev tools and validate that my react component is only showing two items with two different keys for them</i>

**7. Environment details**

MacOS Catalina, Google Chrome latest

**Comment by MarkusWendorf** [comment]
Hey Alexander, you are generating a new key for each item on every render. So the dom elements do not have a stable identity across renders. You see the same behaviour if you do not provide a key at all (but you get a nice warning). 

Change `key={uniqid()}` to `key={item}`.

That solves the problem of the additional dom elements.

Adding an item works now but deleting does not. This could be a bug afterall.

**Comment by AlexanderMelox** [comment]
Even if I change the key to the item (just noticed the key can be the item) it doesn't update the dom. I added a console.log() that logs the items on deleteItem and the Items in the dom still don't get updated.

https://codesandbox.io/s/lucid-germain-f2du3?file=/src/App.js

**Comment by AlexanderMelox** [comment]
Is this being worked on? I currently need to use this for my work and really want to use framer-motion. Our current animations are being stalled because of this bug.

**Comment by dna1986** [comment]
try this 

https://codesandbox.io/s/new-browser-oiv4p?file=/src/App.js

 I just change the wrapper motion.div to a simple div and i moved 

` initial="enter" animate="open" exit="close" `

to the inner element

`<div  className="list">
        <AnimatePresence>
          {items.map(item => (
            <motion.div variants={variants} initial="enter" animate="open" exit="close" key={item} className="list-item">
              item: {item}
              <button onClick={() => deleteItem(item)}>&times;</button>
            </motion.div>
          ))}
        </AnimatePresence>
      </div>`

**Comment by AlexanderMelox** [comment]
@dna1986 This works! I am just confused because the creator of framer-motion did it the way that I did it so is this definitely a bug? or a workaround

**Comment by dna1986** [comment]
@AlexanderMelox As reported in this Page (For me the reference page) https://www.framer.com/api/motion/animate-presence/ 
AnimatePresence must wrap one or more motion components to works correctly

**Comment by InventingWithMonster** [comment]
> @dna1986 This works! I am just confused because the creator of framer-motion did it the way that I did it so is this definitely a bug? or a workaround

It's intended behaviour. The children of `AnimatePresence` must have `exit` props, not the parent.

**Comment by AlexanderMelox** [comment]
Wouldn't the variant pick up the exit prop from the Parent tree?

**Comment by InventingWithMonster** [comment]
No - the component that has animate/initial/exit defined will trigger these animations down throughout the tree. The parent component never exits, so it will never fire an exit animation down the tree.

**Comment by AlexanderMelox** [comment]
So to iterate. If AnimatePresence has a parent that controls an orchestration and it has the exit prop, it does not get inherited by the children of AnimatePresence because the parent does not exist? 

I'm trying to get this right haha, I'm pushing real hard at IBM for our devs to start using Framer motion as the package for animation. I'm also doing a lightning talk on it so I would want to be 100% correct on this.

**Comment by InventingWithMonster** [comment]
Correct. It's not the keys (initial/animate/exit) that get inherited. The components these are defined on are the components that trigger those animations down the tree. Which is how options like `staggerChildren` make sense.

**Comment by AlexanderMelox** [comment]
Okay, thanks I guess we can close this issue then?

**Comment by HeavenlyEntity** [comment]
Might want to consider reopening this issue @mattgperry my elements properly clean up. Yet it starts creating elements when I'm in another tab. As soon as I come back to the tab I was working in there are a bunch of elements on the screen that are not needed and/or cleaning up properly in the `AnimatePresence`.

Uploading a gif here soon.

**Comment by soomro-abd** [comment]
Same issue as @HeavenlyEntity
