### ISSUE TITLE
[BUG] - clipPath not working in ssr

### ISSUE THREAD

**Issue by tafelito** [framer/motion#512]
the clip-path style is is not prefixed while the client is  

when using clipPath as a variant with SSR it gives the error 
```Prop `style` did not match. Server: "clip-path:circle(1.1rem at 14.2rem 1.1rem)" Client: "-webkit-clip-path:circle(1.1rem at 14.2rem 1.1rem)```

![image](https://user-images.githubusercontent.com/5973652/79643952-b2404500-8173-11ea-9b49-4afa7e1155d6.png)

using the [variants](https://codesandbox.io/s/framer-motion-side-menu-mx2rw?fontsize=14&module=%2Fsrc%2FExample.tsx) example using SSR (I'm using NextJS)

**Comment by brennenfountain6** [comment]
The clipPath property remains in open state on some mobile devices (seen on iPhone 11 pro max and iPhone XS). Haven't been able to figure out a reason why. My issue is on a create-react-app build.

**Comment by mattgperry** [comment]
That's odd as we don't do any prefixing ourselves. Could this be a React bug? You can also animate `WebkitClipPath` if you need prefixing.
