### ISSUE TITLE
[FEATURE] transitionEnd can be an function ?

### ISSUE THREAD

**Issue by littlee** [framer/motion#514]
in the latest version, `transitionEnd` can only be an object value, and `onAnimationComplete` take no parameters, but what if I want to know which animation is complete this time ? 

like
```js
<AnimatePresence>
  <motion.div
    onAnimationComplete={(...args) => {
      console.log(...args); // log nothing...
    }}
    initial={{ opacity: 0, y: 200 }}
    animate={{ opacity: 1 }}
    exit={{ opacity: 0 }}
  />
</AnimatePresence>
```

**Comment by littlee** [comment]
COOL 😎 
https://www.framer.com/api/motion/component/#motioncallbacks.onanimationcomplete

**Comment by adamcoulombe** [comment]
Can anyone shed some light on why `onAnimationComplete` would not be working/firing? Running `framer-motion@^3.3.0` using it as follows: 
```
            <motion.div
               initial={false} 
               animate={this.props.current ? "open" : "closed"}
               transition={{ ease: [.05,.74,.45,.99], duration: 0.6 }}
               onAnimationComplete={()=>{
                  console.log('animation is complete');   //logs nothing
               }}
               variants={
                  {
                     open: { opacity: 1,height:"auto", overflow:"visible" },
                     closed: { opacity: 0,height:0, overflow:"hidden" },
                   }
               }
            >{this.content}</motion.div>
```

I would think having callbacks is a pretty critical issue, no?

**Comment by mattgperry** [comment]
`onAnimationComplete` now returns the definition of the triggering element.

@adamcoulombe If you have an outstanding bug please make a new ticket with a sandbox.
