### ISSUE TITLE
[BUG] Usign multiple variants does not seem to be working correctly

### ISSUE THREAD

**Issue by juanpasolano** [framer/motion#518]
**1. Praise**
This project is amazing! ✨ 

**2. Describe the bug**
If I try to use [multiple variants](https://www.framer.com/api/motion/component/#animationprops.animate) in the animate prop to orchestrate a component tree the state doesn't seem to work correctly.

Like: `<motion.div animate={["visible", "active"]} variants={variants} />`

It only works if I use multiple variants in the child elements but not when it comes from the parent.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/gifted-varahamihira-w1f0o

**4. Steps to reproduce**

1. Go to https://codesandbox.io/s/gifted-varahamihira-w1f0o
2. Interact with the demo
2.1 First red box is **what I'd like to achieve** (DOES NOT WORK)
2.3 Second box works but I added the multiple variants `animate={["a", "b"]}` inline which I want to avoid since I need to orchestrate the component tree
2.4 Third box works but is a single animate variant in the parent component.

**5. Expected behavior**
Adding multiple variants`animate={["a", "b"]}` should trigger the correct animations in the children coponents

**Comment by walmat** [comment]
Agh. I was trying to get this to work for days and just stumbled upon this. Seems like a pretty necessary feature imho. Any progress on this @juanpasolano?

**Comment by KirdesMF** [comment]
https://codesandbox.io/s/laughing-mendel-piscw?file=/src/App.js
https://www.framer.com/api/motion/animation/#propagation

and also it was Framer 1.10.3 in the sandbox

**Comment by mattgperry** [comment]
This has since been fixed
