### ISSUE TITLE
multiple end state

### ISSUE THREAD

**Issue by ourfamilygithub** [framer/motion#520]
hello
in my case that i use i wanna exit component depends on state, 
 `exit={{ x: props.formState === '1th' ? '-125%' : '125%' }}`
how can do that in framer?

**Comment by mattgperry** [comment]
You can pass custom data to removed components via `AnimatePresence`:

```
<AnimatePresence custom={props.formState}>
```

And use that to dynamically generate a variant:

```
variants={(formState) => { x: formState === "1th" ? '-125%' : '125%' }}
exit="exit"
```
