### ISSUE TITLE
[FEATURE] Individual transitions for each property

### ISSUE THREAD

**Issue by DexterShepherd** [framer/motion#522]
**Is your feature request related to a problem? Please describe.**
I need to animate multiple properties of a single element with different transitions. Something translating an element upwards over 1 second and fading opacity in over 0.5 seconds with different delays. 

I'm unsure if this is already supported somehow, can't find anything in the docs and I'd prefer not to use useAnimation as nothing imperative really needs to happen. May relate to https://github.com/framer/motion/issues/259.

**Describe the solution you'd like**
Maybe an api like 
```
variants = {
  stateA: {
    y: 100,
    opacity: 0,
  },
  stateB: {
    y: {
      value: 0,
      transition: { ... }
    },
    opacity: {
      value: 1,
      transition: {...}
    }
  }
}
```
I think this is pretty much how animejs handles it.

Or possibly the other way around might make more sense.
 ```
variants = {
  stateA: {
    y: 100,
    opacity: 0,
  },
  stateB: {
    y: 0,
    opacity: 1,
    transition: {
      y: { transition properties for y movement },
      opacity: { transition properties for opacity },
    }
  }
}

```

**Describe alternatives you've considered**
Alternatives seem to be either useAnimation which complicates my code in a way I'd like to avoid. Or adding a wrapper element for each property I want to animate which would work in this case but doesn't scale well if the list of properties gets larger than 2 or 3.

**Comment by InventingWithMonster** [comment]
Hey! You can actually do the latter already. You can also use “default” to
specify a transition for all values not explicitly named

**Comment by DexterShepherd** [comment]
Oh! Amazing! Is this documented. I'd be happy to submit a PR if not. 

Thanks again,

Dex
