### ISSUE TITLE
[BUG] Animate Presence children do not respect dynamic animate prop

### ISSUE THREAD

**Issue by alisd23** [framer/motion#523]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

When using `<AnimatePresence />` with children using a dynamic `animate` prop (with a `custom` prop on the children) - in my case based on the index of the child - the animated values do not get recomputed if the `custom` prop changes.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/animatepresence-dynamic-bug-dccwx?file=/src/Example.tsx

**4. Steps to reproduce**

1. See top 5 elements in the list displayed, where each element is smaller than the previous element in the list.
2. Click "delete" on the top item a few times
3. The items lower down the list never increase in size even though according to the `custom` prop, they should.

**5. Expected behavior**
When the 1st (top) item is deleted, the 2nd item should become the same size as the top item was, and the 3rd should become the same size as the 2nd etc...

**Comment by mattgperry** [comment]
This seems to be fixed in latest
