### ISSUE TITLE
[BUG] Setting state in onMouseEnter or onHoverStart stops whileHover from setting child variant labels in safari 

### ISSUE THREAD

**Issue by DexterShepherd** [framer/motion#524]
**Describe the bug**

Slightly convoluted one.

Setting component state in `onMouseEnter` or `onHoverStart` of a motion component stops `whileHover` from passing a variant label down to child motion components in safari. Removing the set state seems to resolve the issue, and it isn't reproducible in chrome/ff as far as I can tell. The component being hovered over _will_ update based on the `whileHover` label, but it's children do not update.

**IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/competent-haze-q7pco?file=/src/App.js

**Steps to reproduce**

1. Go to https://codesandbox.io/s/competent-haze-q7pco?file=/src/App.js in desktop safari
2. hover over the div with a red border
3. Notice how the h1 nested inside does not change scale.

**Expected behavior**

Safari should behave as other browsers do. Setting a variant label in whileHover should propagate to child motion components.

**Environment details**

Safari 13.1
MacOS Cataline 10.15.4

**Comment by alex83130** [comment]
I have the same issue on Chrome with  `whileHover` and `onHoverEnter` the version 2.1.0 of FramerMotion

**Comment by mattgperry** [comment]
This has since been fixed
