### ISSUE TITLE
Get transformed value in response to page scroll

### ISSUE THREAD

**Issue by scottmas** [framer/motion#526]
**Problem**
I would like to be able to animate a value inside a Frame in response to the user scrolling on the Page. For instance, it adds a feeling of warmth when the user scrolls into the new page and can control the size of say an image on the frame being scrolled into. 

**Ideal Solution**
An api like so would be perfect:

```javascript

export function App() {

  const PAGE_WIDTH = 300;
  const pageScroll = useMotionValue(0)
  const imageScale = useTransform(pageScroll, v => Math.min(v / PAGE_WIDTH, 1))

  return <Page pageScroll={pageScroll} size={PAGE_WIDTH}>
    <Frame center><motion.img src={'some-image.jpg'} width={100} height={100} /></Frame>
    <Frame center><motion.img src={'some-image.jpg'} width={100} height={100} style={{scale: imageScale}} /></Frame>
  </Page>;
}
```

**Alternatives**
I've looked and I've looked and for the life of me I cannot figure out any way to do this in userland. I even tried to re-implement `Page` with a custom pan handler, but there's too much secret sauce inside your guy's implementation and everything I did felt janky.

**Comment by scottmas** [comment]
There is a pretty hacky way to do it using css variables though. But I don't love it. And this just seems like such a common use case. For instance:

```javascript
<Page
        style={{ width, height }}
        effect={({ normalizedOffset, index }) => {
          return {
            "--scale": Math.max(0, 1 + Math.min(0, normalizedOffset * -1)),
          };
        }}
      >
        <Frame style={{ transform: "scale(var(--scale))"  }}>
           <motion.img src={'some-image.jpg'} width={100} height={100} />
        </Frame>
        <Frame style={{ transform: "scale(var(--scale))"  }}>
           <motion.img src={'some-image.jpg'} width={100} height={100} />
        </Frame>
        <Frame style={{ transform: "scale(var(--scale))"  }}>
           <motion.img src={'some-image.jpg'} width={100} height={100} />
        </Frame>
        <Frame style={{ transform: "scale(var(--scale))"  }}>
           <motion.img src={'some-image.jpg'} width={100} height={100} />
        </Frame>
      </Page>
```

**Comment by stokesman** [comment]
Maybe I'm not understanding something but is [useViewportScroll](https://www.framer.com/api/motion/motionvalue/#useviewportscroll) not what you're looking for? There's also an [example](https://www.framer.com/api/motion/examples/#viewport-scroll).

**Comment by scottmas** [comment]
Sorry to take a bit to get back. As I understand it, `useViewportScroll` only works on the viewport scrollbar. Not the page position of a `Page` component (like your official codepen: https://codesandbox.io/s/88j3049zr9)

In the snippet above with my "ideal" api, I'm trying to scale the image on the second page in perfect synchronization with the page swipe position. So when the user has only halfway swiped to the second page, the image will be at one half scale, and only reach a scale of 1 when fully swiped to the side.

**Comment by stokesman** [comment]
Yeah, I was definitely off in my initial reply. Upon looking at the docs for `Page` again I noticed [custom Page effects](https://www.framer.com/api/page/#custom) and decided to try it for making a [demo of your use case](https://codesandbox.io/s/page-effect-indirect-5nqp6?file=/src/index.tsx). It seems not too convoluted. That demo creates a `motionValue` for each page to track scale values since [`PageEffectInfo`](https://www.framer.com/api/page/#pageeffectinfo) conveniently provides a per-page offset (`normalizedOffset`). You could try a single `motionValue` tracking`offset` of `PageEffectInfo` but then I guess you'd need a per-page `useTransform` so it would maybe be a bit more verbose.

**Comment by scottmas** [comment]
Oh sweet! That's exactly what I was looking for. Thank you!
