### ISSUE TITLE
[FEATURE] Looping through different shapes or components like a slot machine.

### ISSUE THREAD

**Issue by hypo-thesis** [framer/motion#540]
**Is your feature request related to a problem? Please describe.**
This feature is suppose to make a fast flash card or slot machine type of changing objects or shapes on the screen.

**Describe the solution you'd like**
I am coding a simple Rock Paper Scissors game and I wanted to make the computer's choice animated in such a way that the choice starts looping through and showing the 3 options ( rock paper and scissor ) and then slowly stop on one.

**Describe alternatives you've considered**
I was thinking this could be achieved by `useEffect()` and some sort of timing which slows and and picks one of the choices.

**Additional context**
![Annotation 2020-05-11 124836](https://user-images.githubusercontent.com/28728305/81548335-d0215400-9385-11ea-9977-19a07e933df2.png)

**Comment by mattgperry** [comment]
This is definitely a user-land feature.
