### ISSUE TITLE
React router use: How do I prevent re-render of parent components with nested routes?

### ISSUE THREAD

**Issue by laurencefass** [framer/motion#541]
In the example sandbox below I have a parent React Router <switch> rendering two animated components.

https://codesandbox.io/s/frame-motion-x-react-router-x-simple-tb1wg?file=/src/Routes.tsx

One of them contains its own nested links - each with their own independent framer-motion animations. I need to stop the parent of the nested switch re-rendering when i click a route link. I can see the problem is related to use of the switch key on both levels but i dont know what to replace it with to stop re-rendering higher up the component hierarchy. If I remove the key, it breaks the animation. 

Steps: 

1. select About. note correct entry and exit animations.
2. select Contact. note the correct entry and exit animations.
3. select Child 1. note the unwanted re-render of the parent component
4. select Child 2. note the unwanted re-render of the parent component

Notes:

- i've added some Math.randoms inline which change on re-render.
- i've include a top level link with no animation to demonstrate the nested components animate on mounting as expected. however it is still re-rendering on selection of child links.

The location.pathname key is forcing re-renders when selecting deep nested links. what can i sensibly replace it with so that it doesn't re-render? Ive tried removing it, but that breaks the animation.

``` 
<Switch location={location} key={location.pathname}>
```

thanks

**Comment by laurencefass** [comment]
0


I have forked a solution adding a key to the component state independent of the routers location object and updating it on link clicks. Its not the prettiest solution (adding onclick to all the links) and there's a bit of repetition. If there is a way in React to say "add an onClick to all NavLinks" that would be better.

quick summary of changes...

  let [key, setKey] = useState();
  useEffect(() => {
    setKey(Math.random());
  }, []);
  ...
  <NavLink onClick={() => setKey(Math.random)} to={`${url}/child1`}>
     Child1
  </NavLink>
  ...
  <TransitionGroup>
    <CSSTransition>
      <Route path={`${url}/child1`} children={<Child1 />} />
  ...
It will work for any level in a component tree to allow independent CSSTransitions. The principal is sound and makes more sense than using the location.pathname for a key for multilevel components but it needs a bit of tidying up.

https://codesandbox.io/s/react-router-animated-transitions-using-state-and-effects-x3v3k?file=/example.js

**Comment by jpodpro** [comment]
struggling with this. i was thinking of trying to parse the location.pathname in each switch statement to determine if the url at that level had actually warranted a route update.

for example: if we were at /catalog and we changed to /catalog/77 then we wouldn't re-render the parent.

what i don't understand is how this isn't already being done. i thought react router v4 was smarter about re-rendering but i can't get it to stop doing this in a nested setup.

**Comment by divmgl** [comment]
Was this ever solved? It's four years later and I'm running into the entire app re-rendering on nested routes that should only affect the `Outlet`.

**Comment by laurencefass** [comment]
see https://github.com/framer/motion/issues/541#issuecomment-627236739
