### ISSUE TITLE
Correct configuration for nesting AnimatePresence/Switch components with React Router 5?

### ISSUE THREAD

**Issue by laurencefass** [framer/motion#542]
Im having difficulties getting a nested <AnimatePresence exitBeforeEnter> wrapper to work with React Router 5.

sandbox: https://codesandbox.io/s/frame-motion-x-react-router-x-simple-tb1wg?file=/src/Routes.tsx:401-435

background:

I have two nested routes inside a <switch> wrapped inside an <AnimatePresence> wrapped inside parent <switch> wrapped in a top level <AnimatePresence>

I have set up variants on the chld routes - ones a slide the other a rotate. im expecting that they animate on entry and exit but im only getting entry animations.

```
const slideVariants = {
  initial: {
    x: '-100%',
  },
  in: {
    x: 0,
  },
  out: {
    x: '-100%',
  },
}

const rotateVariants = {
  initial: {
    rotate: 180,
  },
  in: {
    rotate: 0,
  },
  out: {
    rotate: -180,
  },
}

```

steps

```

1. select nested link (no animation)
2. select child 1. observe entry slide animation
3. select child 2. observer entry animation
4. note absence of the exit animations.

```

i suspect this is due to use of the switch key changing on each render but i dont know what to replace it with. any help appreciated.

thanks

**Comment by laurencefass** [comment]
i've partially solved the problem using component keys to refresh <switch /> components on each click of a link. works ok but doesn't detect repeat link clicks so it repeats animations for the currently loaded route.

https://codesandbox.io/s/framer-motion-nested-routes-react-router-747yw?file=/src/Routes.tsx

I would be grateful to know of any recommendations for working with react router 5+.

**Comment by EugeneBugor** [comment]
I have the same issue.

**Comment by JonasBa** [comment]
This seems like a common use case - I'm having a similar issue and the config roughly looks like so:

```tsx
      <AnimatePresence initial={false}>
        <Switch location={location} key={location.pathname}>
          <Route path={routes.LOGIN} component={lazy(() => import('pages/Login/login'))} />
          <Route component={Dashboard} />
        </Switch>
      </AnimatePresence>
```
where Dashboard looks like so:
```tsx
  <Sidebar/>
  <Switch>
     <Route.../>
     <Route.../>
   <Switch/>
```

The outcome here is that I can either get entire Dashboard (including the sidebar) to rerender on each pathname change, or I end up with entire Dashboard being leaked into the DOM. Would love to have official guidelines on what's the best way to tackle this (if there is one, but it looks like a chicken/egg situation here). Anyways, would love some thoughts on how to tackle this

Thank you!

**Comment by mattgperry** [comment]
I'm going to close this out in favour of looking to add a React Router 6 example
