### ISSUE TITLE
Animate React Components (not just native DOM elements)

### ISSUE THREAD

**Issue by lukebennett88** [framer/motion#543]
I quite often use the [`@reach/dialog`](https://reacttraining.com/reach-ui/dialog) package for creating modals or other things things like off-screen mobile menus.

I'd like to animate the [`<DialogOverlay>`](https://reacttraining.com/reach-ui/dialog/#dialogoverlay) and [`<DialogContent>`](https://reacttraining.com/reach-ui/dialog/#dialogcontent) components using Framer Motion.

In [`react-spring`](https://www.react-spring.io), I could do something like this:
```jsx
const AnimatedDialogOverlay = animated(DialogOverlay);
const AnimatedDialogContent = animated(DialogContent);
```

Is there a way to do something similar in Framer Motion or can you only animate native DOM elements?

**Comment by InventingWithMonster** [comment]
Sure, it's `motion.custom(DialogOverlay)`

**Comment by lukebennett88** [comment]
Amazing, I was sure you would have thought of that already, but couldn't find it in the docs and my Google Fu failed me.
Thanks @InventingWithMonster!

**Comment by lednhatkhanh** [comment]
@lukebennett88 I couldn't make framer-motion to work with ReactUI's Dialog, could you please provide an example, thank you.

**Comment by lukebennett88** [comment]
Sure thing @lednhatkhanh, here is an example:

```
import React from 'react';
import { DialogOverlay, DialogContent } from '@reach/dialog';
import { AnimatePresence, motion } from 'framer-motion';

function Sidebar({ children, isSidebarOpen, setSidebarOpen }) {
  const handleDismiss = () => setSidebarOpen(false);

  const MotionDialogOverlay = motion.custom(DialogOverlay);
  const MotionDialogContent = motion.custom(DialogContent);

  return (
    <AnimatePresence>
      {isSidebarOpen && (
        <MotionDialogOverlay
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onDismiss={handleDismiss}
        >
            <MotionDialogContent
              initial={{ x: '100%' }}
              animate={{ x: '0%' }}
              exit={{ x: '100%' }}
              transition={{ min: 0, max: 100, bounceDamping: 9 }}
              aria-label="Sidebar menu"
            >
              {children}
            </MotionDialogContent>
        </MotionDialogOverlay>
      )}
    </AnimatePresence>
  );
}

export { Sidebar };
```

**Comment by lednhatkhanh** [comment]
@lukebennett88 Thank you so much!
