### ISSUE TITLE
Question: how to keep track of `UnstableSyncLayout` release?

### ISSUE THREAD

**Issue by iagodahlem** [framer/motion#545]
Is there any issue or PR available to keep track of when the `UnstableSyncLayout` component will be released?

I had to use it on a company project, and we wanted to keep a better track of it to use the "stable" version once it gets released.

Thanks in advance.

**Comment by InventingWithMonster** [comment]
Yep, check out the https://github.com/framer/motion/pull/502 PR. Once `AnimateSharedLayout` lands in stable you'll be able to use that instead.
