### ISSUE TITLE
[BUG] Animating colors as CSS Variables fails if not preceded by a space

### ISSUE THREAD

**Issue by izuchukwu** [framer/motion#546]
**2. Describe the bug**

If a CSS variable color is declared with a space between the colon and the color, like so:

`--color: #000`

Framer Motion will throw an error when it is used in an animation.

**3. Provide a CodeSandbox reproduction of the bug**

[Reproduction on CodeSandbox](https://codesandbox.io/s/framer-motion-css-variables-slow-example-l4v15?file=/src/styles.css)

**4. Steps to reproduce**

1. Open the [CodeSandbox](https://codesandbox.io/s/framer-motion-css-variables-slow-example-l4v15?file=/src/styles.css)
2. Click on any of the letters in the sentence "wght animated with long text"
3. See the error `' #ff0000' is not an animatable color. Use the equivalent color code instead.`

The letter's background should become red.
Instead, an error occurs.

The workaround is to change the CSS variable declaration in `styles.css` (line 4) from
`--color: #ff0000` to `--color:#ff0000`.

**5. Expected behavior**

CSS variable colors should be usable with a space between the colon and the start of the color.
I also saw this issue with `rgba()` values. Web colors (e.g. `red`) seemed to work.

**6. Video or screenshots**

![Screen Shot 2020-05-13 at 7 20 47 PM](https://user-images.githubusercontent.com/1860645/81875729-e2022300-954e-11ea-9ac1-25841c6987c4.png)

**7. Environment details**

OS: macOS 10.15.4
Browsers: Safari 13.1 & Chrome 81

**Comment by izuchukwu** [comment]
There also seems to be a perceptible delay when using a CSS variable as a value. Perhaps they're being fetched on the fly? A lot of weird delays disappeared when I changed my CSS variables in Framer Motion to string colors.

**Comment by izuchukwu** [comment]
The issue also appears if the color is succeeded by a space and an `!important` tag. This color would also cause an error:
`--color:#ff0000 !important;`

This would fix the error:
`--color:#ff0000!important`

Though both should work.

**Comment by mattgperry** [comment]
This seems to have been fixed in the meantime
