### ISSUE TITLE
QUESTION: How to layoutTransition by copying

### ISSUE THREAD

**Issue by JakubKoralewski** [framer/motion#550]
Not the biggest fan of React in general, but this library makes React **a lot** more fun! Thanks for open-sourcing it. 

Not a bug, or feature request, but I wanted to ask this here to be absolutely sure this isn't something framer-motion supports before trying to do this manually.

I have table A:
a| b| x
-| -| -|
0 | 0 | 0
0 | 1 | 0
1 | 0 | 0
1 | 1 | 1

And table B:
a\b|0|1|
-| -| -|
**0**| 0 | 0|
**1**| 0 | 1|

I want to make table B appear by duplicating table A and moving each `<td>` element in the **x** column into their appropriate new cell position in table B (similarly to the [Reorder animation example](https://codesandbox.io/s/framer-motion-reorder-animation-bviz6?fontsize=14&module=%2Fsrc%2FExample.tsx)). After the animation I want to have both table A and table B visible, but seems like with `layoutTransition` I will only end up with table B.

My idea for doing this by hand, is to insert an invisible table B into the DOM, then calculate the offset using `getBoundingClientRect`, apply that offset using `transform: translate(...` and then transition that offset into `transform: translate(0,0);`.

Is this possible with `framer-motion`? Thanks for helping :v: 

EDIT: Found [this example of integration with `react-table`](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/animated-framer-motion) but I still don't know how to integrate it with what I want to do :confused:

**Comment by InventingWithMonster** [comment]
You could possibly do something manually that uses Framer Motion but there's no "easy" or in-built way to do this currently

**Comment by JakubKoralewski** [comment]
@InventingWithMonster Thanks for letting me know!
