### ISSUE TITLE
Animated Number Counter

### ISSUE THREAD

**Issue by brunoalano** [framer/motion#551]
**Is your feature request related to a problem? Please describe.**
It's possible to do an animated number counter, like a loading number (0 -> 100)?

**Describe the solution you'd like**
I tried the following:

```javascript
useEffect(() => {
  setTimeout(() => {
    setNumber((old) => old + 10);
  }, 1000);
});

const [number, setNumber] = useState(0);
const animatedNumber = useSpring(0, { damping: 10, stiffness: 50 });
useEffect(() => animatedNumber.onChange(setNumber), []);
```

**Describe alternatives you've considered**
Looking something like this: https://codesandbox.io/s/5voqpr50mk?file=/src/index.js

**Comment by mattgperry** [comment]
Yeah now you could use `animate` to `setNumber`.

```
useEffect(() => {
  animate(0, 100, { onChange: setNumber })
}, [])
```

For better performance you could give the `div` or `span` a `ref` and update its `innerHtml` prop instead.

**Comment by surjithctly** [comment]
@mattgperry Can you elaborate on how can we make it work? Adding your code does nothing. 

Here's my code:

```jsx
import { motion, animate } from "framer-motion";

function Animate() {
 const [number, setNumber] = useState(0);
  useEffect(() => {
    animate(0, 100, { onChange: setNumber });
  }, []);

 return (
   <div> {number}</div>
 )
}

```

The above code does nothing but displays `0`, Not sure what I missed here.
