### ISSUE TITLE
[BUG] AnimateSharedLayout doesn't work if children to animate are not within the same component

### ISSUE THREAD

**Issue by ScottKaye** [framer/motion#553]
**2. Describe the bug**

The [docs](https://www.framer.com/api/motion/animate-shared-layout/) mention:

> These components do not need to be rendered in the same hierarchy, as long as they share the same layoutId, and are wrapped within the same AnimateSharedLayout component.

As seen in the demo, this doesn't seem to be the case.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[This simplified example](https://codesandbox.io/s/framer-motion-animatesharedlayout-gallery-demo-gzr6y?file=/src/App.js) should satisfy both conditions, but does not animate.  **By changing the `<div>` tag on line 10 to `<AnimateSharedLayout>` (as well as the closing tag), it works as expected.**

**4. Steps to reproduce**

1. In the demo, click the red/cyan/lime boxes.
2. Note how the selected item appears instantly below.
3. Change the regular div within Home to `<AnimateSharedLayout>`.
4. Click the boxes - should now animate.

**5. Expected behavior**

I expect the components to animate.  I have tried adding unique `key` props to everything in my Home component, unfortunately to no effect.  My use case is very similar to the original Gallery demo, except the actual components I want to animate between are fairly distant cousins (though they do exist under the same AnimateSharedLayout).

**7. Environment details**

Windows 10, Chrome 81.0.4044.138.

**Comment by InventingWithMonster** [comment]
Ah yeah there currently needs to be a re-render at the level of `AnimateSharedLayout`, I'm trying to figure out how to fix this so it won't be necessary but the problem is the scheduling currently relies on the lifecycle methods of `AnimateSharedLayout`.

**Comment by bjufre** [comment]
@InventingWithMonster Any news on this? I had it working and all of a sudden it started jumping instead of transitioning 🤔 

Thank you!

**Comment by InventingWithMonster** [comment]
I'll be surprised if the behaviour has *changed* but I'm currently concentrating on integrating this with drag and exit animations so haven't had the chance to look at this

**Comment by bjufre** [comment]
@InventingWithMonster that's why I don't fully get why all of a sudden it's not transitioning. This is the current part of the code that uses the `AnimateSharedLayout`:
<img width="576" alt="Screenshot 2020-06-09 at 14 15 56" src="https://user-images.githubusercontent.com/22913276/84146339-da557180-aa5b-11ea-8e63-6d8ad009f3a0.png">

**Comment by mattgperry** [comment]
`AnimateSharedLayout` no longer needs to be rendered alongside its children, please reopen with an example on the latest version if you're still hitting issues there.
