### ISSUE TITLE
QUESTION: How to detect if animation triggered by initial render or key re-render?

### ISSUE THREAD

**Issue by JakubKoralewski** [framer/motion#556]
I have an SVG in which I have some paths. On initial render I add some delay ```transition={{delay: d.depth*0.4}}``` based on the depth of the `d3` node in a tree. I also set a ```key={`${d.data.name}${i}`}```, so on re-renders if the node name changed I want to make the node re-appear; however, because of the set `transition.delay` property I have to wait a long time to see the node appear again. 

Is there a way to detect and pass a different `custom` argument whenever the re-render is triggered by the `key` instead of initial render to be able to set the delay to `0` in such a case?

**Comment by InventingWithMonster** [comment]
You can track this using `useRef` and `useEffect`.

```javascript
const isInitialRender = useRef(true)
useEffect(() => {
  isInitialRender.current = false
}, [])
```

**Comment by JakubKoralewski** [comment]
Well of course `useEffects` should have come to mind! Thanks for the help @InventingWithMonster! 

Although I'm having a problem still, passing the `isInitialRender` as the only argument for `custom` works, but I also need to pass the `link` object as one of the arguments. If I pass it as `custom={{initial: isInitialRender, link: l}}` or as an array, (by checking with console logging inside the custom variant function) the variant function is not being ran on re-renders :confused:

Here's my element:
```jsx
<motion.path
     animate="animate"
     initial="initial"
     variants={linkVariants}
     custom={{initial: isInitialRender, link: l}}
/>
```

And here's my variants:
```jsx
const linkVariants = {
    initial: ({initial, link}) => {
            console.log("animate link initial isInitial: ", initial)
              ...
    },
    animate: ({initial, link}) => {
        console.log("animate link animate isInitial: ", initial)
        ...
    }
}
```
The above only gets re-run if I pass only the `isInitialRender` as the one and only argument :/

**Comment by InventingWithMonster** [comment]
Are you still changing key? Because animate isn’t changing here it isn’t
expected to re-run on subsequent re-renders. When you were changing key you
were essentially re-mounting the component every render which forced an
animation from initial -> animate.

**Comment by JakubKoralewski** [comment]
I'm afraid I don't understand. How else can I achieve an initial longer animation + a shorter animation for each `motion.path` that has changed without using `key`?

**Comment by JakubKoralewski** [comment]
Ok I was able to do this. The problem may have been in me passing `ref.current` as the `custom` property to the `variants` instead of the ref object and/or setting `transition` property inside of both `initial` and `animate` instead of just in `animate`. 

Overall any confusion was probably my fault, thanks for the help @InventingWithMonster
