### ISSUE TITLE
[Question] How to animate a component with a hidden attribute?

### ISSUE THREAD

**Issue by daydream05** [framer/motion#557]
I'm using this [accordion](https://reacttraining.com/reach-ui/accordion) from UI Reach and I'm wondering if it's possible to animate it when "exiting"?

The component adds a `hidden` attribute when it "exits".

I'm able to do an auto height animation when the component is active but I'm unable to animate it as it "exits".

**Comment by mattgperry** [comment]
Feel free to reopen with a CodeSandbox example. I assume `hidden` makes it disappear immediately? I don't know if its possible without somehow overriding this.
