### ISSUE TITLE
[BUG] - Nested SVG 'x' shorthand issues

### ISSUE THREAD

**Issue by ShanonJackson** [framer/motion#558]
**1. Describe the bug**
https://codesandbox.io/s/stoic-bogdan-33tcr?file=/src/App.js

I want to animate the `x` on that nested SVG, however using `motion.svg initial={x} animate={x}` animates the transform: translateX property. This is inherently not the same as animating `x`.

Animating "x" on a nested SVG will physically shift the box model right I.E x="3%" on a nested SVG will physically  shift the box model and all its children right.

Animating "x" using transform: translateX(..) will NOT shift the underlying box model however will shift the element to the right 3%; The difference is that the children of a nested SVG are positioned relative to the box model therefore the line doesn't move.

Give a clear and concise description of what the bug is.

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/stoic-bogdan-33tcr?file=/src/App.js

**3. Expected behavior**
Its tough to say what the expected should be because "x" in framer-motion is short-hand for translateX, however i actually want to animate the actual attribute "x" in this nested SVG case.

**Comment by mattgperry** [comment]
You should be able to achieve this with `attrX` and `attrY`
