### ISSUE TITLE
[Question] How do I implement a chain animation?

### ISSUE THREAD

**Issue by daydream05** [framer/motion#559]
Similar to this react-spring feature:

https://www.react-spring.io/docs/hooks/use-chain

**Comment by pedropalhari** [comment]
Couldn't you use [`Animation Controls`](https://www.framer.com/api/motion/animation/#animation-controls) for it?

You can check it out an example on this [sandbox](https://codesandbox.io/s/flamboyant-feather-2n3zk?file=/src/App.tsx) I created.

**Comment by AlexanderMelox** [comment]
Wow this was helpful!

**Comment by blekmus** [comment]
How do you utilize `Animation Controls` to chain animations that playout when a component is mounted?

Like how animations in the animate prop work.

**Comment by asaduzzaman69** [comment]
@pedropalhari  hey what if i have to build a complex  Animation where lot of element will change in a sequence. for example something goes to right something goes to left and some fade out. in this kind of situation can u tell me how to chain those thing

**Comment by zebapy** [comment]
@pedropalhari  can you please post code example here? That sandbox is gone

**Comment by pedropalhari** [comment]
Hey guys, my answer is more than 2 years old at this point. I'll need to check again if the syntax is still supported to produce a new CodeSandbox.

I'll do one shortly.

**Comment by zebapy** [comment]
I realize you can almost achieve it with variants and delayed transitions 

crude example/idea: 
```tsx
<motion.div
  variants={{
    start: {
      x: 100,
      transition: {
        duration: 1
      }
    },
    mid: {
      y: 100,
      transition: {
        duration: 1,
        delay: 1
      }
    },
    end: {
      x: 100,
      transition: {
        duration: 1,
        delay: 2
      }
    }
  }}
  animate={["start", "mid", "end"]}
>
  test
</motion.div>
```

**Comment by zebapy** [comment]
@pedropalhari  is the above what you roughly had?
