### ISSUE TITLE
[BUG] When animating width, any padding doesn't collapse 

### ISSUE THREAD

**Issue by AlexanderMelox** [framer/motion#561]
# Description

When I animate an element from a certain width the 0 the padding in that div doesn't allow the div to completely go to the width of 0.

**CodeSandbox:** 
https://codesandbox.io/s/framer-motion-padding-adds-width-on-close-tg3qp?file=/src/index.js

**Steps to reproduce**

1. Click on Open button
2. You would notice the div on the left doesnt collapse all the way due to a padding of 16xp all around.
3. Click the close button
4. Toggle the padding off
5. Click the open button
6. Notice the div collapse all the way

** Expected behavior**

A motion.div should collapse completely to 0 , even if it has padding.

**Video or screenshots**

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/12755042/82375511-4fe29a80-99e6-11ea-9be0-7de855e88e25.gif)
Without padding

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/12755042/82375728-9cc67100-99e6-11ea-807d-5e5e66e68bd3.gif)
With padding

**Environment details**
macOS, Google chrome

**Comment by AlexanderMelox** [comment]
I found a workaround for this if you have a child in the motion.element and add that padding there it works. But sometimes this isn't the case. We want to give the styles to the outermost element and now I'm making extra markup.

**Comment by AlexanderMelox** [comment]
Update: I am currently using a wrapper div and give it overflow hidden, but shouldn't this be a design decision to assume whenever we say width: 0, the padding should also not be there?

Is this a CSS limitation as padding is outside of the content box?

**Comment by InventingWithMonster** [comment]
It's not something Motion is going to take an opinion on - `width: 0` should behave as you've defined it with `box-sizing`
