### ISSUE TITLE
[QUESTION] How to use motion to make divs resizable?

### ISSUE THREAD

**Issue by cakir-enes** [framer/motion#563]
I'm trying to make draggable and resizable div hoc. Currently I'm using `onPan` for dragging and `interactjs` package for resizing[0]. It would be nice to do remove a dependency and do resizing  with framer-motion too. Is there a way to implement it with current primitives? 
I think adding some small divs to borders and detecting their pans could work, but hacky. 

[0] https://gist.github.com/cakir-enes/44855ddf5049bb163413bd612c05ffe2 

By the way I tried to use `drag onDrag..` for dragging but div wouldn't move. Why would pan work but drag wouldn't ?

**Comment by mattgperry** [comment]
Apologises but I don't have an example for this
