### ISSUE TITLE
[FEATURE] motion component should be a constructor

### ISSUE THREAD

**Issue by AlexanderMelox** [framer/motion#565]
### Problem
When using libraries that have components, I want to make that component inherit the `motion.element` props. 

When it's my own component, the motion.element isn't a problem because I can add any classes but how can I make a component called `<Dropdown />` Inherit motion props? 
I can't simply wrap it around a motion component because it can throw the styling off.

### Solution
If we make the motion export also be a constructor that can allow me to create a new component that can be animated like so: 
```js
const MotionDropdown = motion(Dropdown);
```

#### Other libraries
Currently `react-spring` has this functionality with their animated component.
https://www.react-spring.io/docs/hooks/basics

```js
const AnimatedDonut = animated(donut);
```

**Comment by InventingWithMonster** [comment]
I think you’re looking for motion.custom but I do prefer this pattern

**Comment by AlexanderMelox** [comment]
Aren't custom props for dynamic values to your components? I don't see a way in the docs that you can pass an existing component and it turns it into a motion component. 

This can maybe be a custom hook called `const MotionComponent = useMotion(Component);`
I don't know how the pattern would be but we can also instantiate the motion component outside the scope of the component like how styled-components do it.

**Comment by InventingWithMonster** [comment]
Yeah but this is a method on `motion`, not a prop.

```jsx
const Component = React.forwardRef((props, ref) => {
  return <div ref={ref} />
})

const MotionComponent = motion.custom(Component)

export default App() {
  return <MotionComponent animate={} />
}
```

**Comment by AlexanderMelox** [comment]
Oh, I was confused with the custom prop sorry about that. 
This is exactly what I needed! Where in the docs can I find this? I spent hours trying to find it.

**Comment by InventingWithMonster** [comment]
I think it's been missed from the docs to be honest!

**Comment by AlexanderMelox** [comment]
I think this should live under the motion page since it's a method of that?
https://www.framer.com/api/motion/component/

Or maybe under Utilities. But thanks for the help!

**Comment by focux** [comment]
Yes, it's not on the docs, I searched it for a while with no luck but glad I could find this issue.

**Comment by AlexanderMelox** [comment]
@InventingWithMonster any future docs update to have this included?

**Comment by mattgperry** [comment]
Currently deploying change to the docs
