### ISSUE TITLE
[BUG] onDragEnd not firing on iOS when dragControls is used with dragListener false

### ISSUE THREAD

**Issue by isakkeyten** [framer/motion#567]
https://codesandbox.io/s/animation-g65kl

On Windows Chrome: 
click on activate
drag handler is the red bordered Comments
drag down 100px to close

On iOS Safari:
click on activate
drag handler is still the whole card (shouldnt be, it should only be red bordered component, meaning drag listener false is not working)
drag anywere from card or handler with red border
onDragEnd never fires so bottom sheet is not closed

**Comment by mattgperry** [comment]
Closing but feel free to reopen with a replication
