### ISSUE TITLE
[QUESTION] How do you mix transforms in animate and exit?

### ISSUE THREAD

**Issue by justinh00k** [framer/motion#575]
I am using different transform parameters on my `animate` (transition in) and `exit` (transition out). I am currently using `animate: { transitionEnd : { foo:bar  }`  to pass the initial values for the transition out, so that it may transition in with `transform: scale` and out with `transform: rotate`. (As an example - I am actually using many types.)

It all works fine unless the user toggles the transition out before the transition in is finished, and then I get an error like:

`Uncaught (in promise) Error: Complex values 'scaleX(1)' and 'rotate(-540deg) scale(0)' too different to mix.` 

Is there a way to make this work, or another way I should be approaching this?

Thanks!

**Comment by breadadams** [comment]
@justinh00k I'm not sure if this is the _exact_ same issue as I faced recently, but I ended up inserting the "defaults" when seeing such error. For instance with the example you've mentioned (mixing  `scaleX`, `rotate` & `scale`), it may be something like:

```js
const variants = {
  enter: { scaleX: 1, scaleY: 1, rotate: 0 },
  exit: { scaleX: 0, scaleY: 0, rotate: -540 }
}
```

**Comment by justinh00k** [comment]
Breaking out the transforms into their own properties definitely solves part of the problem - I set the defaults for the exit in the initial property and it prevents the error, but interrupting one transition with another (especially interrupting an exit with a start) produces some pretty wonky results. Seems like the initial values should be 0 OR the last state it was in when interrupted? (Which wouldn't help with exit anyway since there is no specific exit initial...)

**Comment by mattgperry** [comment]
Closing this but feel free to reopen with a sandbox example
