### ISSUE TITLE
[FEATURE] access mousecoordinates in whileHover via a callback

### ISSUE THREAD

**Issue by jescowuester** [framer/motion#576]
**Is your feature request related to a problem? Please describe.**

currently `whileHover` only accepts an object as an argument. Many animations ([like this type of hover effect](https://codesandbox.io/s/improved-omio-card-uqn9z?file=/src/Card.js:1974-1977)) require you to access the mouse coordinates to calculate the animated value

**Describe the solution you'd like**

Allow passing a callback to whileHover like this:

```
<div whileHover={({mouseX})=>({transform: `rotate(${mouseX}deg)}) />
```
-> rotation would increase the further right the mouse is

**Describe alternatives you've considered**
Can also be achieved by setting state in react 60 times x second. This works in some cases but quickly runs into performance limitations.

**Comment by mattgperry** [comment]
I don't see us implementing this kind of API. Rather than setting state at 60fps you can rather create a motion value and update that:

```
const rotate = useMotionValue(0)

return <div onMouseMove={() => /* set rotate */} style={{ rotate }} />
```
