### ISSUE TITLE
[BUG] useLayoutEffect warning when rendering serverside

### ISSUE THREAD

**Issue by thebuilder** [framer/motion#578]
The change in #195 introduces `useLayoutEffect` to the the `useViewportScroll` (and the new `useElementScroll`) hook, that causes a React warning when rendering serverside.

See [CodeSandbox](https://codesandbox.io/s/small-http-u4fnj?file=/pages/index.js)

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
```

A common fix is to create a `useIsomorphicLayoutEffect` that selects the right effect for the env.

```js
const useIsomorphicLayoutEffect = isBrowser ? useLayoutEffect : useEffect

function Comp() {
  useIsomorphicLayoutEffect(() => {
    // ...
  })
}
```

**Comment by alex83130** [comment]
I have the same issue with next.js, Is there a solution to solve that ?

**Comment by cghayden** [comment]
I'm using v2.9.4, but i'm still getting this warning.  I'm using nextJs v9 and Apollo.

**Comment by seawatts** [comment]
I'm using NextJs 12 and Framer 6.2.6 and am seeing this error.

**Comment by TheAggressive** [comment]
Seeing this too. Using NextJs 12 and Framer-Motion 6.2.6

**Comment by TheAggressive** [comment]
Any fixes for this?

**Comment by thebuilder** [comment]
Guessing it's caused by this file, that was just added:
https://github.com/framer/motion/blob/e0a6c1308c7b77d51e41439889d8dc63a08dfded/packages/framer-motion/src/utils/use-is-mounted.ts

It should use the `useIsomorphicEffect` instead.

A few files in the `framer-motion-3d` package is also using it directly:
https://github.com/framer/motion/blob/f39eb0730d75ada35437e20dd8cff8284030f7eb/packages/framer-motion-3d/src/components/use-layout-camera.ts
https://github.com/framer/motion/blob/c36db286ccd68010f7e030e39c06a701d4415778/packages/framer-motion-3d/src/components/MotionCanvas.tsx

**Comment by ryparker** [comment]
Still seeing this warning in v6.2.7

My workaround for now:

```ts
if (typeof window !== 'undefined'){
	return null;
}
```

**Comment by TIMMLOPK** [comment]
> 在 framer-motion 中仍然看到這個警告：v6.2.7，下一個：v12.1.0
> 
> 我現在的解決方法：
> 
> ```ts
> const  isBrowser  =  typeof  window  !==  'undefined' ; 
> if  ( ! isBrowser ) { 
> 	return  null ; 
> }
> ```

We are waiting,it still not release fix
