### ISSUE TITLE
[BUG] framer-motion with popmotion installed leads to type error

### ISSUE THREAD

**Issue by IgnusG** [framer/motion#580]
Installing `framer-motion` and then `popmotion` leads to type error with `framer-motion`:

```
ERROR in /project/node_modules/framer-motion/node_modules/popmotion/lib/reactions/value.d.ts(26,41):
TS2307: Cannot find module '../../../framesync/lib' or its corresponding type declarations.
Version: typescript 3.9.3
```

I think this error in the popmotion repository references this too https://github.com/Popmotion/popmotion/issues/865

**Steps to reproduce**

1. Install `popmotion` and `framer-motion`
2. npm either de-dupes framesync or run `npm dedupe` manually
3. Type Error

**Video or screenshots**

![image](https://user-images.githubusercontent.com/6438760/83336317-be5f0c80-a2b2-11ea-94e8-b7e808482495.png)

As on the image the library is actually 5 levels above instead of 3.

**Environment details**

Running typescript 3.9.3
npm 6.14.4
framer-motion 1.11.0 as well as 2.0.0-beta.72
popmotion 8.7.3

**Comment by mattgperry** [comment]
Closing as
