### ISSUE TITLE
[BUG][V2] Issues with AnimateSharedLayout

### ISSUE THREAD

**Issue by Ericnr** [framer/motion#586]
I'm just learning framer-motion, so it's possible there's a better way to implement this and avoid the bug.

Code reproduction: [codesandbox](https://codesandbox.io/s/framer-motion-animatesharedlayout-gallery-demo-wz73g?file=/src/App.js)

When you quickly deselect and then select another image or quickly select two images before the fade out finishes the animations become duplicate.

Bug reproduction: [streamable](https://streamable.com/uc9xm0)

**Comment by omarkhatibco** [comment]
I had the same problem after updating to `beta.73`.

**Comment by Ericnr** [comment]
@omarkhatibco what version were you at before? The sandbox is using `beta.42`

**Comment by omarkhatibco** [comment]
@Ericnr I revert to .72 and it works again.

**Comment by Ericnr** [comment]
Im not sure we're having the same problem. That said, versions .72 and .73 both break my animation in different ways, but I guess thats the point of the beta.

**Comment by sebtoombs** [comment]
For what it's worth; it seems that between beta 72 and beta 73 AnimateSharedLayout fails completely.

**Comment by Pytal** [comment]
Can confirm animations not working after changes in `2.0.0-beta.73`

**Comment by Victoire44** [comment]
Same on `2.0.0-beta.76`

**Comment by mattgperry** [comment]
I having trouble replicating with latest but I also couldn't replicate too well with this. I'm going to close for now but one thing I would recommend is to block pointer events using the overlay

**Comment by Ericnr** [comment]
Ive dropped this but fwiw I can still reproduce it on latest https://streamable.com/ryja7b
