### ISSUE TITLE
[FEATURE] Sound synchronization

### ISSUE THREAD

**Issue by cyruschoi76** [framer/motion#587]
**Is your feature request related to a problem? Please describe.**

How can I have the animation synchronise with sound playback ? Like I want to implement a wheel of fortune, with the sound effect playback when rotated like 45 degree. 

**Describe the solution you'd like**

I tried to use the subscribe the onChange event, but as the callback itself won't synchronize with anything. I can only manually keep trace whether the 45/90/135/etc trigger point is passed, and playback that sound effect, and it won't be that precise after all. 

Any better solution or possible better way to do this in the future ?

**Comment by mattgperry** [comment]
You can inspect the latest values with `onChange` but beyond that we don't offer explicit support for sounds
