### ISSUE TITLE
[FEATURE] Animation on CSS pseudo-elements (:after, :before)

### ISSUE THREAD

**Issue by alex83130** [framer/motion#595]
**Is your feature request related to a problem? Please describe.**
I use the [theme-ui](https://theme-ui.com/home) which use under the hood the both [emotion](emotion ) and a custom JSX pragma in order to use the `sx` prop.
This stuff allows me to use the pseudo-element CSS `:after` and `:before` as inline-style.
Is there a way to apply the animation on this pseudo-element ?

**Describe the solution you'd like**
That is a codexanbox with my environment and example : https://codesandbox.io/s/framer-motion-pseudo-element-mg553?file=/src/index.js

**Describe alternatives you've considered**
I think the other solution would be not to use this pseudo-element and found a different way to have the same UI. But ideally I would like keep the pseudo-elements CSS.

**Comment by stokesman** [comment]
Here's a [fork of your demo](https://codesandbox.io/s/framer-motion-pseudo-element-2xuep?file=/src/index.js) that keeps the pseudo-element and animates it using CSS custom properties.

The feature as you mocked up in your demo is probably possible but convoluted to implement because JS has no access to pseudo-elements as objects.

**Comment by InventingWithMonster** [comment]
Yeah I actually think this impossible I'm afraid, @stokesman's solution is as close as you'll get with JS.

**Comment by alex83130** [comment]
Since the `sx` props allow using pseudo-elements as inline-style, I could you use the traditional CSS `transition` and `transform` to solve my issue.
I put this specific solution in the codesandbox : https://codesandbox.io/s/framer-motion-pseudo-element-8hbnp?file=/src/index.js

**Comment by alex83130** [comment]
@stokesman, I just see your solution, I think this the more close, thanks !

**Comment by akashlama98** [comment]
This is the WAAPI way of animating pseudo elements.

```js
const logo = document.querySelector("#logo");

logo.animate({ opacity: [0, 1] }, {
  duration: 100,
  pseudoElement: "::after"
});
```

Isn't there a way we can figure out a way to achieve this in `animate()` function as well??
