### ISSUE TITLE
[BUG] Sidemenu example - sidemenu nav covers rest of page when hidden

### ISSUE THREAD

**Issue by ruaridhnewman** [framer/motion#599]
On the Side Menu example in the "closed" state, the navigation still covers the background of the site. If you inspect the html you can see it is covering the background, and also when you hover over where the navigation will appear when open, you can click on the nav items.

https://codesandbox.io/s/framer-motion-side-menu-mx2rw?fontsize=14&module=%2Fsrc%2FExample.tsx

**4. Steps to reproduce**

1. Go to the codebox example
2. Hover over where the nav will appear
3. You will see you are able to click on the nav items even though the nav is closed

**5. Expected behavior**

I would expect the navigation to be fully hidden, so you can only click the toggle button in the top left when its in a "closed" state, and not the nav items.

**6. Video or screenshots**

![sidemenu](https://user-images.githubusercontent.com/26965443/84516168-51da0980-acc5-11ea-90cd-77a2b3b76d90.gif)

**7. Environment details**

Have tried in firefox and chrome, macOS catalina

**Comment by anishkargaonkar** [comment]
I would like to take this up

**Comment by anishkargaonkar** [comment]
src/MenuItems.tsx
setting `dispaly: none` using `transitionEnd` in closed variant & resetting `dispaly: flex` in open variant should solve the issuse. 

```
const variants = {
    open: {
        y: 0,
        opacity: 1,
        transition: {
            y: { stiffness: 1000, velocity: -100 },
        },
        display: "flex",        // reset display property to flex when animation starts
    },
    closed: {
        y: 50,
        opacity: 0,
        transition: {
            y: { stiffness: 1000 },
        },
        transitionEnd: {           // after animation set display to none
            display: "none",  
        },
    },
}
```

**Comment by ruaridhnewman** [comment]
Perfect, thank you! Seems kind of strange that you have to do that, but as long as it works 🤷

**Comment by InventingWithMonster** [comment]
Great solution @anishkargaonkar !

@ruaridhnewman this is just the way CSS works I'm afraid. We can't take too many opinions on that because what would help in one situation (automatically display: none when opacity is 0) would break things for a lot of people!

**Comment by ruaridhnewman** [comment]
Ye, fair enough, any easy fix for me anyway. Thanks!

**Comment by sFritsch09** [comment]
I would like to have the white circle on the bottom right. it works with the button when you change the css, but not for white circle. I tried to change the x-y origins, however it is not responsive so it doesn't stay in place when I change screen size.

closed: {
		clipPath: 'circle(30px at 92.2vw 90vh)',
...
}

**Comment by MasterCollab** [comment]
Good notice, I fixed to set display: none while closed to <ul>, and it also worked

**Comment by sasarivera** [comment]
the display:none works fine to avoid the nav covering the content, but if you have content under the menu with mouse events, those events are not being fired when clicked. Any suggestions?
