### ISSUE TITLE
[FEATURE] After onDragEnd, provide onDragMomentumEnd.

### ISSUE THREAD

**Issue by the-observer-man** [framer/motion#600]
I am trying to drag my screen with some dragMomentum on it. I want to drag another screen based on previous drag. So I am listening to onDragEnd, but because there is momentum even after dragEnd screen is moving which I can't capture.

My proposed solution would be either fire onDrag till momentum decays to zero, or give a separate event like 'onDragMomentumEnd'

I thought of an alternative to listen to dom property changes but that really hurts the performance.

**Comment by stokesman** [comment]
`onDragTransitionEnd` is what you are looking for. I think it's missing from the docs.

**Comment by InventingWithMonster** [comment]
Thanks @stokesman. I've updated the docs with this.

**Comment by TomasSestak** [comment]
@mattgperry seems like it dissappeared

**Comment by federicocappellotto97** [comment]
@mattgperry  we also need a function that trigger on full drag (even on momentum), like onDragMomentum()

**Comment by antoniobrandao** [comment]
@stokesman seems the function doesn't return any `info` unfortunately, I needed a reliable way to get the X offset on drag transition end.
