### ISSUE TITLE
[BUG] useElementScroll function is not working.

### ISSUE THREAD

**Issue by jipi-despegar** [framer/motion#602]
**1. Read the [FAQs](#faqs) 👇**
✔︎

**2. Describe the bug**
`useElementScroll` function is not working as expected in version **v1.11.1**
If I try tu use useElementScroll method on a section of my web, the MotionValue result is not changing.

Is working fine with `useViewportScroll`, i think that `useElementScroll` is similar but with a ref element, i'm ok? or I misunderstand the function?

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

CodeSandbox (is the useViewporScroll example, converted to useElementScroll example)
https://codesandbox.io/s/scroll-r31k1?file=/src/Example.tsx

**4. Steps to reproduce**

1. Go to CodeSandbox
2. Open devtool to wath the change on the doms elements motion.div
3. Scroll down to end of example
4. See that the styles of motion.div's are not changing

**5. Expected behavior**
Update values when the provided element scrolls:

Maybe I am misinterpreting how it is used, if so please excuse the "bug" but I need to know how to implement it correctly.

**Comment by ianatlion** [comment]
Me too

**Comment by brettmeyer** [comment]
Having the same issue

**Comment by InventingWithMonster** [comment]
`useElementScroll` expects a scrollable element. I'll clarify in the docs.

**Comment by FobosGuy** [comment]
Does it work when only overflow-x set to scroll? Overflow-y is hidden
