### ISSUE TITLE
[FEATURE] Layout animations with SVGs

### ISSUE THREAD

**Issue by theoinglis** [framer/motion#605]
Hi, thanks for Framer Motion, it seems great so far. However, I am having an issue with using AnimateSharedLayout with svgs.

**Explanation**
When switching from one layout to another the shape I am trying to transition will disappear and then animate at the correct angle to the new position. I will want the animation to happen between routes and move the shape to a fixed position on the screen. As a result I can't just animate the shape to the new position within the svg container. Is this a bug (given it's in beta) or do I just need to set some more properties (initial values maybe?) for it to work correctly?

**Example**
https://codesandbox.io/s/interesting-margulis-7ovme

**Repro steps**
1. Click on the circle 

**Actual Behaviour**
It disappears and transitions to the new position from outside the svg, at the right angle.

**Expected behaviour**
It should smoothly transition from it's current position to the new position

**Comment by InventingWithMonster** [comment]
You're not doing anything wrong, they're not compatible yet. This probably won't be fixed for the final Motion 2 release but it is on the horizon. I'll keep this ticket open so we can track it.

**Comment by theoinglis** [comment]
Ok, thanks for the update.

**Comment by tnunes** [comment]
Bumped into this problem when trying to animate layout of an SVG.

Also found the notice on the docs saying that:

> **SVG layout animations are broken**
>  SVG components aren't currently supported with layout animations. This will be fixed in a future release.

Is there any work already started on the fix?
Or a write-up on the problem or planned approach to address it?

With a couple of pointers on where to look at inside framer-motions internals I could try to contribute to getting this solved and available in a future release, @mattgperry.

**Comment by mdugue** [comment]
hey @mattgperry any news here? Streamlined svg would be 💯 🎉. Also do you have any hints on workarounds?

**Comment by mattgperry** [comment]
Closing as `wontfix` to set expectations.

It's still possible this could be implemented, but it's unlikely to happen unless we need the functionality inside Framer.
