### ISSUE TITLE
[BUG] PresenceContext seems not to pass down custom prop to entire component tree

### ISSUE THREAD

**Issue by patricknick** [framer/motion#607]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

When using the [`custom`](https://www.framer.com/api/motion/animate-presence/#animatepresenceprops.custom) prop on `AnimatePresence`, these values are passed down to unmounting motion components and can be used in dynamic variants. But if you wrap the animating component with another motion component, plus you specify `initial`, `animate` and `exit`, the propagation stops. You can only avoid this if you specify these three properties on the inner motion comp.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Repro: https://codesandbox.io/s/framer-motion-image-gallery-boj95?file=/src/Example.tsx
Working example: https://codesandbox.io/s/framer-motion-image-gallery-oiyec?file=/src/Example.tsx

**4. Steps to reproduce**

1. In the slideshow, press the arrow keys. 
2. The animation is confusing, as images exit in the wrong directions.

**5. Expected behavior**

From the documentation I expect the custom values available on every level of the component tree, no matter where I specify the `initial`, `animate` and `exit` props. 

**6. Video or screenshots**

--

**7. Environment details**

framer-motion: 1.11.1

### `AnimatePresence` isn't working

Have all of its immediate children got a unique `key` prop that **remains the same for that component every render**?

```jsx
// Bad: The index could be given to a different component if the order of items changes
<AnimatePresence>
  {items.map((item, index) => <Component key={index} />)}
</AnimatePresence>
```

```jsx 
// Good: The item ID is unique to each component
<AnimatePresence>
  {items.map((item, index) => <Component key={item.id} />)}
</AnimatePresence>
```

Is the `AnimatePresence` correctly outside of the controlling conditional? `AnimatePresence` must be rendered whenever you expect an `exit` animation to run - it can't do so if it's unmounted!

```jsx
// Bad: AnimatePresence is unmounted - exit animations won't run
{isVisible && (
  <AnimatePresence>
    <Component />
  </AnimatePresence>
)}
```

```jsx
// Good: Only the children are unmounted - exit animations will run
<AnimatePresence>
  {isVisible && <Component />}
</AnimatePresence>
```

**Comment by nicolas-cusan** [comment]
Hi @patricknick I am having the same problem, did you find a workaround for this?

**Comment by mattgperry** [comment]
Seems to work as expected in later versions
