### ISSUE TITLE
'Complex values too different to mix' error for seemingly not complex values...

### ISSUE THREAD

**Issue by chocobuckle** [framer/motion#608]
I have the following variants...

```
const menuVariants = {
  menuIsClosed: {
    clipPath: 'polygon(calc(100% - 40px) 49px, calc(100% - 20px) 49px, calc(100% - 20px) 51px, calc(100% - 40px) 51px)',
  },
  menuIsOpen: {
    clipPath: 'polygon(0% 0%, 100% 0%, 100% 100%, 0% 100%)'
  }
}
```

...does Framer Motion not support calc() or what is so complex about this that is resulting in the error?

**Comment by stokesman** [comment]
The key part of that error is 'too different'. The strings do not have an equal quantity of numerical portions. The first has 12 the second has 8. It can work by either including the calcs in both or eliminating them in both.

**Comment by InventingWithMonster** [comment]
As answered by @stokesman.
