### ISSUE TITLE
[BUG] Transition backgroundColor inside varients doesn't work

### ISSUE THREAD

**Issue by alex83130** [framer/motion#609]
I would like have a transition on a `backgroundColor ` field caused by a changed state. In my specific case it was caused by a conditional scroll.
The animation work correctly if I use the `opacity` field (opacity 0 --> opacity 1, ), but seems not working when I put the field `backgroundColor`.
Maybe I use the wrong way to do this stuff.

I made a code sandbox in order to show that case : https://codesandbox.io/s/framer-motion-tfkel?file=/src/index.js

EDIT: I just notice that don't work only when I use label color (`red`, `green`, ...), with hexa value all work fine

**Comment by mattgperry** [comment]
Color labels aren't and won't be supported by Framer Motion so yeah try hex/rgb/hsl

**Comment by Johnrobmiller** [comment]
> Color labels aren't and won't be supported by Framer Motion so yeah try hex/rgb/hsl

Since it's so easy to convert, as an example, 'red' to 'hsl(0, 100, 50)', why not automatically code these conversions into Framer Motion?

**Comment by mattgperry** [comment]
It’s purely a bundle size thing.

**Comment by Johnrobmiller** [comment]
> It’s purely a bundle size thing.

Fair enough.

**Comment by habibollahi24** [comment]
Color labels aren't and won't be supported by Framer Motion so yeah try hex/rgb/hsl
