### ISSUE TITLE
[BUG] Animating between HSLA values throws an error

### ISSUE THREAD

**Issue by rickyhopkins** [framer/motion#613]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

Animating between two hsla values throws a warning.
`Both colors must be hex/RGBA, OR both must be HSLA.`

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/flamboyant-mirzakhani-f2kom?file=/src/App.js

**4. Steps to reproduce**

1. Go to the codesandbox example
2. Click on the animatable element
3. See error

**5. Expected behavior**

Either there should be no error or the error should explain that hsla values cannot be animated.

**6. Video or screenshots**

N/A

**7. Environment details**

`"framer-motion": "^1.11.0"`

**Comment by InventingWithMonster** [comment]
If you add `initial="start"` this will be fixed. The problem here is because `animate` isn't used for initial states (and we can leave this open until it is), the color is read from the DOM, which always returns rgba no matter how you actually defined it.

**Comment by InventingWithMonster** [comment]
Closing as the `initial` fixes it in 2.62 and beyond that the HSLA animation now works correctly.
