### ISSUE TITLE
[QUESTION] How to not trigger animation when transitioning to other pages?

### ISSUE THREAD

**Issue by ramojej** [framer/motion#614]
Hi I'm using Gatsby.js and have some animations in the header area. However, whenever I go to another page it animates again. 

codesandbox: https://codesandbox.io/s/condescending-dubinsky-vuydd

**Comment by InventingWithMonster** [comment]
Hi @ramojej 

I assume the animation in question is triggered by `initial` -> `animate`. If it's re-running, it means the entire component is being remounted. I don't know enough about Gatsby to fix this, but you can validate the component is remounting by adding

```
useEffect(() => {
  console.log('mount')
}, [])
```

If you can get that ^ not to fire when you go to another page by making the component persistent somehow, this will fix your issue.

**Comment by ramojej** [comment]
Hello @InventingWithMonster,

Thanks for the hint! I solved it using Gatsby's [wrapPageElement](https://www.gatsbyjs.org/docs/browser-apis/#wrapPageElement)
