### ISSUE TITLE
[FEATURE] Pinch/pull gesture

### ISSUE THREAD

**Issue by yoshikischmitz** [framer/motion#617]
**Is your feature request related to a problem? Please describe.**
Canvas-based and zooming interfaces like Figma are having a bit of a renaissance right now, and many laptop users lately expect two-finger pan and pinch-zoom to work on their trackpads when using such interfaces.

**Describe the solution you'd like**
I like the idea of using Framer motion to build such zooming user interfaces by composing gesture handlers and transformations.

**Describe alternatives you've considered**
There are many purpose-built libraries for this in React, but they're all hard to customize - and hard/impossible to compose with other behaviors of an app.

**Comment by wiesson** [comment]
Any updates to this topic?

**Comment by mattgperry** [comment]
Closing this out as I am fairly convinced we're never getting round to this. Your best bet is to do something like mixing https://use-gesture.netlify.app/docs/gestures/ with motion values.

**Comment by staaky** [comment]
> Not currently - it's relatively involved so I assume it won't happen unless there's a need for it inside Framer

Maybe this can be reconsidered with Motion no longer being tied to Framer?
