### ISSUE TITLE
[Question] Wait for animation to finish before adding second item using AnimatePresence

### ISSUE THREAD

**Issue by grigory-bogush** [framer/motion#619]
How do I make sure that previous `someNode` finished transitioning and is removed from the DOM before the  next node is inserted and animated in? Is that even possible?

The end goal is just to make fade in out transition on node change. Thanks

```
<AnimatePresence>
  <motion.div
     key={someNodeKey}
     enter={{ opacitiy: 0 }}
     animate={{ opacity: 1 }}
     exit={{ opacitity: 0 }}
  >
    {someNode}
  </motion.div>
</AnimatePresence>
```

**Comment by msheakoski** [comment]
Give the [exitBeforeEnter](https://www.framer.com/api/motion/animate-presence/#animatepresenceprops.exitbeforeenter) prop on AnimatePresence a try.

**Comment by InventingWithMonster** [comment]
Thanks @msheakoski !

**Comment by ShahriarKh** [comment]
For future googlers, `exitBeforeEnter` is now replaced with `mode="wait"`
