### ISSUE TITLE
[BUG] Animating SVG's path d attribute throws a color related error

### ISSUE THREAD

**Issue by wr9** [framer/motion#622]
**2. Describe the bug**

Animating SVG's path d attribute throws a color related error: 

Error: Complex values 'm 0 0 h 130 v 130 h -130 z' and 'm 32.5 58 a 20 20 0 1 0 65 0 a 20 20 0 1 0 -65 0' too different to mix. Ensure all colors are of the same type.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/keen-bhaskara-jmic2?file=/src/App.js (click refresh in the sandbox if you don't see the error)

**4. Steps to reproduce**

Just go to the sandbox and refresh in the sandbox if you see a black square and no error

**5. Expected behavior**

SVG morphs according to the new d attribute (m 32.5 58 a 20 20 0 1 0 65 0 a 20 20 0 1 0 -65 0).

**7. Environment details**

MacOS, Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by InventingWithMonster** [comment]
The error message should be clarified but that's a bug in Popmotion which I've opened an issue for.

Each `d` needs the same number and color pattern, whereas one of the values you've provided is much smaller than the other and we only support interpolation, not morphing.
