### ISSUE TITLE
[FEATURE] Ignore another drag event while dragging

### ISSUE THREAD

**Issue by mottox2** [framer/motion#624]
**Is your feature request related to a problem? Please describe.**
I try to implement pinch-in gesture with framer-motion's drag.
While I am dragging on the first touch, another touch event is triggered and dragging repeats between each touch.

**Describe the solution you'd like**
I want to ignore another drag event while I'm doing drag.

**Describe alternatives you've considered**
It may be possible to implement this using a native listener

**Additional context**
I checked with iOS 13.4 Safari.

**Comment by mattgperry** [comment]
Closing but anyone feel free to reopen with a codesandbox example
