### ISSUE TITLE
[BUG] Page links jumps to top of the page before exiting with Animate Pressence in Gatsby

### ISSUE THREAD

**Issue by JonasWN** [framer/motion#626]
** Describe the bug**

Might just be me overseeing something but When using Gatsby together with Animate Pressence the page will jump to the top before starting the exit animation

** IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/sharp-ardinghelli-jw5f9

From another gatsby issue that was fixed but im using the same browser config with animating pressence as this one.

** Steps to reproduce**

1. Scroll down abit so your not at the top
2.  click the link to page 2 under the paragraph and you will see it scrolls to the top then fades out.

**Expected behavior**

I think it´s a Gatsby issue somehow but it would be nice if there was a solution to it not jumping to the top of the page before beginning to animate out.

**Comment by Bleuzen** [comment]
Same problem with Next.JS

**Comment by JonasWN** [comment]
Sadly not a option with Gatsby Link as far as i know :/ but nice you found out for NextJS!

**Comment by michaeljblum** [comment]
Try adding the following code to your gatsby-browser.js file:

```
export const shouldUpdateScroll = ({
  routerProps: { location },
  getSavedScrollPosition,
}) => {
  if (location.action === 'PUSH') {
    window.setTimeout(() => window.scrollTo(0, 0), transitionDelay);
  } else {
    const savedPosition = getSavedScrollPosition(location);
    window.setTimeout(
      () => window.scrollTo(...(savedPosition || [0, 0])),
      transitionDelay
    );
  }
  return false;
};
```

**Comment by JonasWN** [comment]
@michaeljblum That works like a charm! thank you appreciate the reply

**Comment by eddsaura** [comment]
> Same problem with Next.JS
> 
> Edit: for Next as a workaround you can disable the scroll to top for links:
> https://nextjs.org/docs/api-reference/next/link#disable-scrolling-to-the-top-of-the-page
> and handle scrolling in the onExitComplete event on AnimatePresence

Hey how you doing? 😄 . I tried puting scroll={false} in my link but it isn't working in next 10.1.3, do I have to do something more in the onExitComplete ?

Ty

**Comment by Bleuzen** [comment]
> Hey how you doing? smile . I tried putting scroll={false} in my link but it isn't working in next 10.1.3

What exactly doesn't work with this?

>  do I have to do something more in the onExitComplete ?

Optionally, yes. If you want to scroll to the top of the page after the exit animation of the previous page is complete, you could do something like this:

```
  <AnimatePresence
    exitBeforeEnter
    initial={false}
    onExitComplete={() => {
      if (typeof window !== 'undefined') {
        window.scrollTo({ top: 0 })
      }
    }}
  >
```

**Comment by jalada** [comment]
This works for forward navigating with links, but doesn't work when pressing the back button. Has anyone got a solution for the back button scrolling before the animation starts?

**Comment by Sergioamjr** [comment]
I was facing the same problem on Next.JS `11.0.1` and framer-motion `4.1.17`. 

I solved by removing the `exit={{}}` property of my `<motion.div` inside the `<AnimatePresence`.

```js
return (
    <AnimatePresence exitBeforeEnter initial={false}>
      <motion.div
        key={router.asPath}
        transition={{ duration: 0.3 }}
        initial={{
          overflow: 'hidden',
          top: withDefaultTransition ? '100vh' : 0,
        }}
        // exit={{ top: 0, overflow: 'hidden' }}
        animate={{ top: 0, overflow: 'initial' }}
      >
        <motion.div
          key={`${router.asPath}-child`}
          initial={{
            overflow: 'hidden',
            top: withDefaultTransition ? '100vh' : 0,
          }}
          // exit={{ overflow: 'hidden' }}
          animate={{ top: 0, overflow: 'initial' }}
          transition={{ duration: 0.3, delay: 0.4 }}
        >
          {children}
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
```

In the `<Link` component I'm also passing the property `scroll={false}`
```js
<Link href="/blabla" scroll={false}
```

And scrolling to the top on the `router.events.on('routeChangeComplete', scrollToTop);` event.

```js
  const router = useRouter();

  useEffect(() => {
    const scrollToTop = (url) => {
      window.scrollTo({ top: 0 });
    };

    router.events.on('routeChangeComplete', scrollToTop);

    return () => {
      router.events.off('routeChangeComplete', scrollToTop);
    };
  }, [router]);
```

**Comment by loganpowell** [comment]
I'm having an issue also related to scroll position, but the opposite. When I navigate (using react router [in this case](https://codesandbox.io/s/framer-motion-animatesharedlayout-app-store-demo-forked-rtr4j?file=/src/App.js)) between pages that are wrapped with `<AnimatePresence>`, the scroll position from the _from_ page leaks into the _to_ page. 

I've made a minor adjustment to the [example in the docs](https://codesandbox.io/s/framer-motion-animatesharedlayout-app-store-demo-forked-rtr4j?file=/src/App.js) to illustrate. (click the "Bug" link at the bottom of the list page to see what I'm talking about)

**Comment by loganpowell** [comment]
I just want to follow up to mention that I've messed with scroll position for a library I maintain myself and it's an absolute nightmare of edge-cases, so I don't expect a fix for this. I'm just posting this here for posterity.

**Comment by eddsaura** [comment]
My problem in Next.js was that I was using `scroll-behaviour: smooth`. I got rid of that and used it only when I needed (in the back to top button). And it worked flawlessly

**Comment by loganpowell** [comment]
I actually just ended up managing scroll position manually using [`history.scrollRestoration === 'manual'`](https://developer.mozilla.org/en-US/docs/Web/API/History/scrollRestoration#prevent_automatic_page_location_restoration) along with a js `Map` that gets `set` to the current scroll position for any given url. I then attach a listener to the `popstate` event and pull the last `set` value for that url from the `Map` and restore scroll position with [`window.scrollTo`](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo)

**Comment by RectoVersoDev** [comment]
> 

https://janessagarrow.com/blog/gatsby-framer-motion-page-transitions/#bonus 🎁

**Comment by RectoVersoDev** [comment]
> I'm facing exact same issue now and I'm using React 17.0.2 and framer-motion 4.1.17, has anyone found a workaround for this issue for react? Any references would be appreciated.

https://janessagarrow.com/blog/gatsby-framer-motion-page-transitions/#bonus 🎁

**Comment by dazn-krishnak** [comment]
> > I'm facing exact same issue now and I'm using React 17.0.2 and framer-motion 4.1.17, has anyone found a workaround for this issue for react? Any references would be appreciated.
> 
> https://janessagarrow.com/blog/gatsby-framer-motion-page-transitions/#bonus gift

I tried to implement similar solution following the snippet mentioned in the reference url, but it didn't work. I hope there is a way for solving this in react.

**Comment by MrUltimate** [comment]
> > > I'm facing exact same issue now and I'm using React 17.0.2 and framer-motion 4.1.17, has anyone found a workaround for this issue for react? Any references would be appreciated.
> > 
> > 
> > https://janessagarrow.com/blog/gatsby-framer-motion-page-transitions/#bonus 🎁
> 
> thanks for the reference but I'm looking for a solution that is specific to react and not gatsby.

Lmao what? Gatsby is a React framework.

**Comment by YusukeSano** [comment]
> This works for forward navigating with links, but doesn't work when pressing the back button. Has anyone got a solution for the back button scrolling before the animation starts?
> 
> **EDIT** Oops actually I'm in Next.js land and the answer was for Gatsby so might be fine in Gatsby, sorry.

I am having the same problem with Next.js.
`<Link href="/" scroll={false}>` was a very good solution, but the browser back/forward button takes me back to the top before the exit animation finishes.

Does anyone have a good solution to this?

**Comment by johnstringerm** [comment]
> > This works for forward navigating with links, but doesn't work when pressing the back button. Has anyone got a solution for the back button scrolling before the animation starts?
> > **EDIT** Oops actually I'm in Next.js land and the answer was for Gatsby so might be fine in Gatsby, sorry.
> 
> I am having the same problem with Next.js. `<Link href="/" scroll={false}>` was a very good solution, but the browser back/forward button takes me back to the top before the exit animation finishes.
> 
> Does anyone have a good solution to this?

The solution above also worked for me, except for when using browser history buttons.

I found a solution to the back / forward buttons taking you to the top in this Next.js issue
[https://github.com/vercel/next.js/issues/20951](https://github.com/vercel/next.js/issues/20951)

There are a couple of different solutions in the issue but I ended up going with:
```
export const Transition: React.FC = ({ children }) => {
    const router = useRouter();

    useEffect(() => {
        router.beforePopState(state => {
            state.options.scroll = false;
            return true;
        });
    }, []);

    return (
         <Script>{`window.history.scrollRestoration = "manual"`}</Script>
        ...
    );
};
```
Which worked with the issue I was having.

**Comment by RNtaate** [comment]
> > Hey how you doing? smile . I tried putting scroll={false} in my link but it isn't working in next 10.1.3
> 
> What exactly doesn't work with this?
> 
> > do I have to do something more in the onExitComplete ?
> 
> Optionally, yes. If you want to scroll to the top of the page after the exit animation of the previous page is complete, you could do something like this:
> 
> ```
>   <AnimatePresence
>     exitBeforeEnter
>     initial={false}
>     onExitComplete={() => {
>       if (typeof window !== 'undefined') {
>         window.scrollTo({ top: 0 })
>       }
>     }}
>   >
> ```

This worked wonderfully, thank you very much.
