### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by omersname** [framer/motion#627]
Hello, I'm using drag gesture to a div, but I want to drag it only from one particularly place at that div.
For example:
![image](https://user-images.githubusercontent.com/37253325/87221323-e6429500-c373-11ea-9853-2d54e6451083.png)
Here I want the red square to be draggble but only by "holding" the blue one.

Now, I've tried it in so many ways, like using `useDragControls` hook, but as long as I set the red square (for example) to be draggble with `drag={true}`, it's going to be draggble no matter where I press it.

Please, any solutions ?

**Comment by micnil** [comment]
I think i solved this by setting `dragListener={false}` on the red div (and using drag controls like you suggested).

**Comment by InventingWithMonster** [comment]
Yep as @micnil says you can use a combination of useDragControls triggered by the blue component and dragListener={false} on the red outline box
