### ISSUE TITLE
[BUG] Animating theme-ui's Box

### ISSUE THREAD

**Issue by NickChristensen** [framer/motion#628]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

When using motion.custom() with `theme-ui`'s `<Box>`, each item is re-rendered (and re-animated) whenever any animation is fired.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/green-waterfall-cpp72

**4. Steps to reproduce**

1. Install theme-ui, framer-motion
2. Create a component that renders multiple instances of `motion.custom(Box)` inside `<AnimatePresence>`
3. Add or remove items to the list
4. Observe that on any change to the list, each item in the list re-renders and re-animates

**5. Expected behavior**

I expect the boxes to behave the same way as `motion.div`

**Comment by InventingWithMonster** [comment]
This line: `let AnimatedBox = motion.custom(Box);`

Should be outside the component, as this is creating a new component every render.

**Comment by NickChristensen** [comment]
Oof 🤦

Thanks, and congrats on the 2.0 launch. Y'all are killing it!
