### ISSUE TITLE
[QUESTION] AnimateSharedLayout performance issue

### ISSUE THREAD

**Issue by ivanburlakov** [framer/motion#631]
The `framer-motion@beta` documentation contains an example of which I am very interrested in: seamless and animated card routing:
https://su6mx.csb.app/
https://codesandbox.io/s/framer-motion-animatesharedlayout-app-store-demo-su6mx

It is working mostly fine on PC browsers with occasional frame dropping, but on mobile (Android) in Chrome it is quite laggy. If you try Firefox Mobile it is extremelly laggy. Is it something to do with animation or the content those card have? And is there a way to make it better?

**Comment by InventingWithMonster** [comment]
This one is quite intensive. I'm not sure there's anything you can do as a user, but we do continually look at performance as mobiles is a key output for Framer prototypes
