### ISSUE TITLE
[BUG] Nested layout distortion correction doesn't work 

### ISSUE THREAD

**Issue by dminkovsky** [framer/motion#635]
Please see:

https://codesandbox.io/s/framer-motion-2-scale-correction-19gtn?file=/src/App.js:1166-1234

- When you click on the white box, the the pink box is scaled correctly while the outer transformation occurs.
- When you click in pink box, the text inside of it is not correctly scaled as it is transformed, even though that text is itself inside a `<motion.div layout />`

I did see in the docs that distortion correction is applied to "immediate children", but here the immediate child is the text-containing motion div, no?

**Comment by InventingWithMonster** [comment]
So this one is actually working correctly but it is obviously a non-ideal result.

If you inspect the bounding box of the "Hello!!" it is full-width proportional to the ball in both states. Indeed it does scale correctly.

But the bounding box of the "Hello!!" **text** proportional to **its own bounding box** is different in both states. This is the source of the visual distortion.

The solution is to style the text box in a way that its bounding box wraps the text more closely, for instance using `float: "left"`  or potentially `'display: "inline-block"`

**Comment by dminkovsky** [comment]
Thank you for investigating.

Yes, I do see in now in the inspector that upon state transition, as the pink circle scales, the text-containing div scales against it.

But then unfortunately I seem to lack some knowledge to understand your explanation :(.

> But the bounding box of the "Hello!!" text proportional to its own bounding box is different in both states. This is the source of the visual distortion.

Can you please explain this some more? I would really appreciate it. Are you saying that because the text is inside a DOM text node, that that text node does not respond to the reverse-scaling of its parent element node? 

> The solution is to style the text box in a way that its bounding box wraps the text more closely, for instance using float: "left" or potentially 'display: "inline-block"

Yes, I tried adding `float: left` and `display: inline-block` to the style of the distortion-correcting motion.div, and both produced the desired effect. But I don't understand why this works, and would love to have been able to reach these conclusions on my own.

Thank you.

**Comment by dminkovsky** [comment]
Hey thanks a lot. Yes, that makes sense. I see now.

Also thanks for layout="position". Does seem to address both of the issues I posted.
