### ISSUE TITLE
[FEATURE] Motion path (with SVG definition)

### ISSUE THREAD

**Issue by michaeljblum** [framer/motion#640]
**Is your feature request related to a problem? Please describe.**
I'd really like to declaratively animate an element along an SVG path, using scrollY for control (or another non-duration based method), and taking advantage of useSpring for damping and stiffness etc. 

Code like `const xRange = useTransform(scrollYProgress, [0, 0.9], [0, path.current.getTotalLength()]);` _(where "path" is a ref for the SVG path)_ doesn't work because I'd only have access to the ref in a useEffect, where useTransform can't go.

**Describe the solution you'd like**
The imperative way would go something like `const pathLength = path.current.getTotalLength();
  const pts = path.current.getPointAtLength(
       scrollYProgress.current * pathLength
     );`

And then update `x` and `y` attributes on the SVG element (say, a circle) I'd like to animate by setting them to `pts.x` and `pts.y` respectively.

But this method misses out on taking advantage of some of the useMotionValue hooks like useTransform and useSpring.

So I was thinking of a solution that could look a little similar to useElementScroll that takes a ref (for the path element) and allows you to destructure off the scrollYProgress that effectively does something similar to `const pts = path.current.getPointAtLength(
       scrollYProgress.current * pathLength
     );`

Kind of specific but it'd be really nice to have a declarative way of doing this that doesn't involve tons of refs/getElementById calls or require GSAP.

**Comment by mattgperry** [comment]
Now that Webkit has announced `offset-path` is coming in Safari 16 we're probably not going to do anything too specific for this other than perhaps add some polyfiller for older browsers if we introduce the feature to Framer.
