### ISSUE TITLE
[BUG] Drag Controls not calculating correct position

### ISSUE THREAD

**Issue by amcdnl** [framer/motion#643]
## Bug Behavior
After upgrading to 2.1.0 from 1.x, the drag controls do not position the element correctly.

## Example Code
Below is example of the code:

```
const variants = {
  active: {
    opacity: 1,
    scale: 1
  },
  inactive: {
    opacity: 0,
    scale: 0.5
  }
};

const Drag = () => {
  const dragControls = useDragControls();
  const [activeDrag, setActiveDrag] = useState<any | null>(null);

  const onDragStart = useCallback(
    (event, data) => {
      setActiveDrag(data);
      dragControls.start(event, { snapToCursor: true });
    },
    [dragControls]
  );

  const onDragEnd = useCallback(() => {
    setActiveDrag(null);
  }, [activeDrag]);

  return (
    <div>
      <button onDragStart={onDragStart} onDragEnd={onDragEnd}>Drag me</button>
      <motion.div
        drag
        dragControls={dragControls}
        variants={variants}
        animate={activeDrag ? 'active' : 'inactive'}
        onDragEnd={onDragEnd}
      >
        {activeDrag && (
          <div>
            <img
              height="50"
              width="50"
              alt="logo"
              src={img}
            />
          </div>
        )}
      </motion.div>
    </div>
  );
};
```

## Video
https://www.screencast.com/t/P5vEKY9TK

## Environment details
Mac, Chrome

**Comment by o-alexandrov** [comment]
In our case, we upgraded from `2.0.0-beta.77` to `2.1.0` and started to notice:
- `dragConstraints` property **is not working properly** for us any longer

**Comment by vercetti11** [comment]
Same thing happened to me as @o-alexandrov says… @amcdnl

**Comment by InventingWithMonster** [comment]
@o-alexandrov Hopefully this PR fixes your issue https://github.com/framer/motion/pull/660 when it lands. Please open a ticket with a sandbox if it doesn't though.

**Comment by amcdnl** [comment]
@InventingWithMonster - Tested w/ latest release 2.1.4 and still not working - same behavior. I'll try to make a demo for you.

**Comment by InventingWithMonster** [comment]
Yeah this is two separate bugs but A demo would be appreciated in tackling
the one in the ticket.

**Comment by amcdnl** [comment]
@InventingWithMonster - Here ya go: https://codesandbox.io/s/framer-drag-bug-1l2c7

**Comment by amcdnl** [comment]
@InventingWithMonster - Bump ^

**Comment by amcdnl** [comment]
@InventingWithMonster - Bump ^

**Comment by amcdnl** [comment]
@InventingWithMonster - Looks like on 2.4.2 the demo I made above works. Thanks!
