### ISSUE TITLE
[BUG] CSS background properties not working

### ISSUE THREAD

**Issue by jacdx** [framer/motion#647]
Trying to get some parallax going with `useTransform` and `useViewportScroll`. I can get something to happen if I use a basic CSS property like `opacity` or `y`. But background properties like `backgroundPositionY` aren't functioning at all.

Also, it has been a confusing process figuring this stuff out, since the variable name you choose as a return value for `useTransform` must match a valid CSS property, which is a key detail I don't see in the docs. Is there a way to extract the value out a Motion Value so I can assign it to whatever CSS property I want, and have it automatically update? Additionally, is there a way to pass in a property name to useTransform, so that the return value variable name doesn't have to be the name of a valid CSS property?

**Comment by InventingWithMonster** [comment]
> variable name you choose as a return value for useTransform must match a valid CSS property

This isn't true:

> Is there a way to extract the value out a Motion Value so I can assign it to whatever CSS property I want, and have it automatically update?

```jsx
const literallyAnything = useTransform()
return <motion.div style={{ backgroundColor: literallyAnything }} />
```

> Trying to get some parallax going with useTransform and useViewportScroll. I can get something to happen if I use a basic CSS property like opacity or y. But background properties like backgroundPositionY aren't functioning at all.

For this one, I'm going to close the issue for now but please do reopen it with a CodeSandbox reproduction of the bug.

**Comment by marcelomandaji** [comment]
i am with the same problem.

the only properties that updates with useViewportScroll is x y scale and opacity.

i am trying a parallax effect using letterSpacing and it not works.  

the docs says letterSpacing uses a MotionValue<number> and i am passing it.

![2021-01-27 15_58_05-HomeAbout js - luci_portfolio - Visual Studio Code](https://user-images.githubusercontent.com/1044895/106065505-2b44d380-60da-11eb-9301-e4d9ea4b28a2.png)

**Comment by surbhirajpal** [comment]
I was having the same issue but this solution worked - 
Earlier I was using 
`backbgroundPositionY = useTransform(scrollY, ['0px', '900px'], ['-160px', '0px']);`
but the input range must always be a linear series of numbers, either counting up or counting down.
And this worked for me.
`backbgroundPositionY = useTransform(scrollY, [0, 900], ['-160px', '0px']);`
