### ISSUE TITLE
Error when animating between HSL/HSLA colors

### ISSUE THREAD

**Issue by acrobertson** [framer/motion#649]
**Description**

When animating between `hsl` or `hsla` color values on a motion component using `whileHover`, it throws an error if the component is hovered again during the animation: `Complex values 'hsla(177, 37.4978%, 76.66804%, 1)' and 'hsla(0, 0%, 100%, 1)' too different to mix. Ensure all colors are of the same type.`

This does not seem to happen using named colors or hex values.

**CodeSandbox**

https://codesandbox.io/s/clever-river-qnxfd?file=/src/App.js

**Steps to reproduce**

1. Hover the cursor over the link
2. Move the cursor and then quickly hover the link again
3. See error

**Expected behavior**

Colors of the same type should be animated between without error.

**Video**

![motion_error](https://user-images.githubusercontent.com/16787295/88095278-db9db200-cb62-11ea-980d-80e8df657148.gif)

**Environment details**

-macOS 10.15.6
-Chrome 85.0.4183.26
-Framer Motion 2.1.0

**Comment by InventingWithMonster** [comment]
For some reason one of those is being detected as a complex value rather than a color - I'll take a look
