### ISSUE TITLE
[BUG?] layout transition not working properly in super-seeding positionTransition...

### ISSUE THREAD

**Issue by rchrdnsh** [framer/motion#655]
Dunno if bug or not, but I had a div like this:

```jsx
<motion.div positionTransition />
```

...in framer motion 1.x and it worked great, animating its position on a grid like a champ.

Now I'm trying to migrate to 2.0 and have changed the code to this:

```jsx
<motion.div layout transition={{ duration: 2 }} />
```

...as per the migration docs and it is not working at all.

Dunno if I'm doing something wrong or if there is an issue with framer motion 2.

Anyway, will try to make a code sandbox in the meantime to repro...thank you!

**Comment by rchrdnsh** [comment]
hmmmm...made a sandbox...

https://codesandbox.io/s/stoic-tesla-8rp1v?file=/src/MajorScale.js

...and it seems to work here...will do more digging and see if i can figure out why it's not working in my app...

**Comment by rchrdnsh** [comment]
hmmmm...I may have found the issue...dunno why i had this thought but it seems that the `layout` prop in framer motion 2 does not seem to work with Preact. Some motion things DO work, like hover and tap, but not layout.

I am using Gatsby and I disabled `gatsby-plugin-preact` and it now works as advertised. This is kind of a bummer, however, as using preact saves a bunch of bytes over the wire over full React. Maybe someday the `layout` prop can work with Preact...

**Comment by Grsmto** [comment]
I noticed the same issue. It would be cool if we could identify where this come from and maybe we could look into a fix?
Any hint on what changed on the `layout` prop between v1 and 2 that could have break this?

**Comment by Grsmto** [comment]
Hey,
So I did some tests and actually I think it was not working already with v1 as you can see in this codesandbox: [https://codesandbox.io/s/cocky-shirley-snmwq](https://codesandbox.io/s/cocky-shirley-snmwq)

You can remove the alias in package.json to switch to React and it works fine.
