### ISSUE TITLE
[FEATURE] Custom Renderer

### ISSUE THREAD

**Issue by yorrd** [framer/motion#662]
**Is your feature request related to a problem? Please describe.**
We're using webcomponents with lit-element and would like to integrate this API into our framework. 

**Describe the solution you'd like**
I've started reading the `framer-motion` code and was going to try out using `HTMLVisualElement` as an entrypoint for an integration without react. However, it's not exported. Do you think it makes sense to export the class to allow for custom integrations? Is it even the correct class to start thinking about?

Thanks

**Comment by InventingWithMonster** [comment]
I honestly wouldn't know where to start with trying to adapt it for use outside of React. There's definitely bits and pieces you can use in the codebase that aren't React-specific. But I would caution that only the documented API is considered versioned and supported, and any other use should be expected to break unless you pin to a specific version.

**Comment by yorrd** [comment]
We went with anime.js in the meanwhile, can do a lot of the stuff as well and is agnostic. Thanks for the advice.
