### ISSUE TITLE
[BUG] Layout transform animations breaks dragging of children

### ISSUE THREAD

**Issue by dmtrKovalenko** [framer/motion#663]
**1. Description *

When the animation `drag` container is animated with `layout` animation of `x` or `y` – once drag container is dragged all the `motion.*` components with `animate` applied are not moving with the container. 

```jsx
<motion.div drag layout animate={{ x: 100 }}>
  // This h1 will not drag 
  <motion.h1 layout animate={{ fontSize: 44}}> 
       Something
  </motion.h1>
</motion.div>
```

**2. CodeSandbox**

Here: https://codesandbox.io/s/async-feather-27vqp?file=/src/App.tsx

**3. Steps to reproduce**

1. Go to https://codesandbox.io/s/async-feather-27vqp?file=/src/App.tsx
2. Drag pink div – everything is ok
3. Click on button `Click` 
4. Try to drag pink div again and observe that animated `h1` is not moving
5. Check styles and observe compensation of dragging `transform` on the element: 

**4. Expected behavior**

There is not additional `transform` applied when an element is dragging 

**5. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.
![image](https://user-images.githubusercontent.com/16926049/88458793-2851f780-ce99-11ea-994c-69378694d159.png)

**7. Environment details**

Any browser
MacOS: 11.0 beta 0 
Framer-motion: 2.1.4

**Comment by InventingWithMonster** [comment]
Duplicate https://github.com/framer/motion/issues/636
