### ISSUE TITLE
Not working on IE11 because in Framer Motion v2 "Proxy" is used, which is not supported [BUG]

### ISSUE THREAD

**Issue by asadhazara** [framer/motion#664]
I've been using till v1.11.1 without any problem in IE11, but since the upgrade to v2 my website shows an unexpected error, which is "Proxy in undefined".

**Comment by InventingWithMonster** [comment]
Hi @asadhazara 

Framer Motion hasn't ever supported IE11. Have you been using polyfills until now? Proxy isn't supported by polyfills.

**Comment by asadhazara** [comment]
@InventingWithMonster Yes, i've been using polyfills. Thank you for the clarification. I guess I have to drop supporting IE11 aswell :)
