### ISSUE TITLE
[QUESTION] Forwarding props from component to motion.input in typescript

### ISSUE THREAD

**Issue by mateusbds** [framer/motion#665]
**Describe the bug**

This is not really a bug, It's just a problem that I had and couldn't be able to solve. I was trying to make a generic input that has an scale when focused and gets normal scale when blur.

Tried doing something like that:

```
const Input: React.FC<ForwardRefComponent<
  HTMLInputElement,
  HTMLMotionProps<"input">
>> = ({ ...props }) => {
  const controls = useAnimation();

  return (
    <motion.input
      {...props}
      animate={controls}
      onFocus={() => controls.start({ scale: 1.1 })}
      onBlur={() => controls.start({ scale: 1 })}
    />
  );
};
```
but it doesnt work, I get the following error when i try to pass an prop :

`<Input placeholder="Name" />`

```
Type '{ placeholder: string; }' is not assignable to type 'IntrinsicAttributes & ForwardRefComponent<HTMLInputElement, HTMLMotionProps<"input">> & { ...; }'.
  Property 'placeholder' does not exist on type 'IntrinsicAttributes & ForwardRefComponent<HTMLInputElement, HTMLMotionProps<"input">> & { ...; }'.
```

**CodeSandbox reproduction**

https://codesandbox.io/s/github/mateusbds/framer-motion-repro

**Repository**

https://github.com/mateusbds/framer-motion-repro

**Expected behavior**

I want to get an input with its placeholder and its motion effects.

**Comment by albingroen** [comment]
Yeah @mateusbds I'm experiencing this too. Although I'm not sure the **Bug** label is accurate for this question. Basically we want to create general purpose and isolated components that use the framer-motion library - but also extends the types of the html input element we are building around. Basically a simple example of this is the following:

```jsx
interface IComponentProps extends React.HTMLProps<HTMLDivElement> {
  foo: string
}

const Component: React.FC<IComponentProps> = (props) => {
  return (
    <motion.div {...props}>
      ...
    </motion.div>
  )
}
```

We need something equivalent from framer-motion to replace this with I believe. Maybe this already exists but I do not see any documentation for it.

```jsx
extends React.HTMLProps<HTMLDivElement>
```

**Comment by mattgperry** [comment]
Does importing `HTMLMotionProps` and using `HTMLMotionProps<"input">` cover your use case? I'm going to preemptively close but feel free to re-open if it doesn't.

**Comment by ryparker** [comment]
Could we have this added to the docs?
