### ISSUE TITLE
[BUG] AnimatePresence not working with stagger children

### ISSUE THREAD

**Issue by hasibulHossain** [framer/motion#666]
**Describe the bug**

AnimatePresence does not remove the list items from the DOM when list item has variants property. But If I comment out the variants property of the list item then AnimatePresence works fine.

**CodeSandbox**
Here (https://codesandbox.io/s/shy-silence-opw9t?file=/src/components/Product/Product.js)

**Steps to reproduce**

1. Go to 'https://codesandbox.io/s/shy-silence-opw9t?file=/src/components/Product/Product.js'
2. Click on 'stagger' button twice to check stagger animation
3. Click on items 'close' button

**Expected behavior**

The list item will be unmounted after clicking the item close button

**Video or screenshots**

![video](https://user-images.githubusercontent.com/51342498/88479456-1774b500-cf71-11ea-8f60-edce6ece2706.gif)

**Environment details**
chrome: Version 84.0.4147.89 (Official Build) (64-bit)
os: windows 10
framer-motion: 2.1.4

**Comment by RRReact** [comment]
I have similar problem. When I pass variants to motion element exit prop  doesn't work and component isn't exiting , but when i pass object with desired animations it works just fine. I can work with it, but having variants is way more convinient. Did you find solution ?

**Comment by mattgperry** [comment]
This has been fixed in the meantime
