### ISSUE TITLE
"window" is not available during server side rendering.  (when building in Gatsby) [BUG]

### ISSUE THREAD

**Issue by anim8rDev** [framer/motion#672]
**2. Describe the bug**

Trying to import Frame from "framer" inside of Gatsby component will fail during build (works fine in dev mode).  The error is...
'"window" is not available during server side rendering.'

Get error with:
import { Frame } from "framer"  

No error with:
// import { Frame } from "framer"

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Not sure how to reproduce this Gatsby build error within Codesandbox.

**4. Steps to reproduce**

0) No need for anything other than trying to import Frame.
1) Place import { Frame } from "framer" at the top of a component.
2) type 'gatsby build' in shell.
3) See error in shell output log.

**5. Expected behavior**

No error on build

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

**7. Environment details**

Gatsby CLI version: 2.12.65
Gatsby version: 2.24.12
Windows 10

**Comment by InventingWithMonster** [comment]
Hey @anim8rDev 

The `framer` library isn't intended for use outside of Framer. It doesn't support SSR I'm afraid.
