### ISSUE TITLE
[QUESTION] Salvaging Drag and Reorder after upgrade to v2

### ISSUE THREAD

**Issue by captDaylight** [framer/motion#673]
@InventingWithMonster made an incredible drag and reorder example with [codeSandBox](https://codesandbox.io/s/framer-motion-drag-to-reorder-pkm1k?file=/src/Example.tsx:0-32) that appears to break when I upgrade it to `2.2.0`. 

I see from the upgrade that `dragOriginY` no longer exists, so I assume that has at least something to do with it. Is this sandbox salvageable or does this fall under the [breaking changes](https://www.framer.com/api/motion/guide-upgrade-to-framer-motion-2/#drag)?

**Comment by InventingWithMonster** [comment]
@captDaylight where did you find that sandbox?

Here's how to do it in Motion 2: https://codesandbox.io/s/framer-motion-2-drag-to-reorder-fc4rt

**Comment by captDaylight** [comment]
@InventingWithMonster it's the first result when I google "framer-motion drag and reorder". Thanks for the updated link!

**Comment by dminkovsky** [comment]
Thanks for posting @InventingWithMonster. I had seen this when I first explored Motion 2, but when I saw this issue I couldn't find it. Is it linked in the docs somewhere?
