### ISSUE TITLE
support ios 9 ?

### ISSUE THREAD

**Issue by littlee** [framer/motion#674]
after importing `proxy-polyfill`,  `motion.div` is undefined on ios 9 device

```js
import 'proxy-polyfill';
import { motion } from 'framer-motion';
console.log(motion.div); // undefined
```

(I used to use `react-pose`, and it works fine on ios 9 with core-js polyfill)

```
import 'core-js/stable';
import 'regenerator-runtime/runtime';
```

**Comment by InventingWithMonster** [comment]
Hey @littlee

Motion doesn't support runtimes without `Polyfill` support I'm afraid, and it isn't polyfillable. I am considering a seperate entry point for people who absolutely need it and don't mind the added bundle size though.

**Comment by littlee** [comment]
found `motion.custom` here
https://inventingwithmonster.io/20200302-can-i-use-framer-motion-with-styled-components/
(missing docs for `motion.custom` ? 🌚 )

on iOS 9
though `motion.div` is undefined, `motion.custom` can be used instead.

After re-write my component to
```
import { motion } from 'framer-motion';
const Wrap
```
