### ISSUE TITLE
[BUG] shadowBox transition doesn't work well with whileHover

### ISSUE THREAD

**Issue by alex83130** [framer/motion#676]
**1. Describe the bug**

Transition doesn't work correctly on `shadowBox` with the` hover in` but work well with the `hover out`.
With the `hover in` the `shadowBox` disappear appear without smooth transition after 1s (the duration define for transition) but appear with a smooth transition when I have a `hover out`

Give a clear and concise description of what the bug is.

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-tfkel?file=/src/index.js

**3. Steps to reproduce**

1. Hover the Button
3. You will see the `boxShadow` disappear suddenly after 1s
4.  Remove the hover
5. You will see the `boxShadow` appear with a smooth transition

**4. Expected behavior**

I would like to have the smooth transition for the both appear and disappear.

**Comment by InventingWithMonster** [comment]
Putting animating values in `initial` is more reliable as Motion doesn't have to read it off the DOM.

```
initial={{ boxShadow: "0 5px 0 0px rgb(110, 192, 66)" }}
```

**Comment by alex83130** [comment]
Thanks for the advice, work well ;)
