### ISSUE TITLE
[BUG] Unit conversion using maxWidth on window resize

### ISSUE THREAD

**Issue by manelet** [framer/motion#684]
First thing first, thanks a lot for providing such a rich and easy-to-use library. It's my animation solution since the react-pose times 🙏
Also sorry in advance in case I might be missing something, but I've been digging since yesterday without success.

**2. Describe the bug**

I want to use different values on maxWidth property depending on the window width.
Values are updated properly but units remain like the previous value.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/naughty-haze-79y5o

**4. Steps to reproduce**

Resize the window in order to switch breakpoint (768px) and see how <motion.nav /> is not updating it's maxWidth properly

**5. Expected behavior**

maxWidth should go from 100% on 'mobile' to 200px on 'desktop', instead current behaviour is:
- If page loads on >=768 maxWidth goes from 200px to 100px instead of 100%
- If page loads on <768 maxWidth goes from 100% to 200% instead of 200px

**Comment by manelet** [comment]
I've just seen that a workaround could be using `window.innerWidth` instead of '100%'.

That way no unit is converted and it works.

**Comment by InventingWithMonster** [comment]
Hi @manelet 

Sorry we're unlikely to explicitly support this. Currently unit conversion on width and height works by setting and measuring the before/after states and animating in pixels. With `max` units there's no real way for us to do this.

If you want to animate between the two states the official way to do this would be to move the `maxWidth` prop to `style`, and add the `layout` prop.

**Comment by foxieManel** [comment]
I'll try this, thanks!

**Comment by dminkovsky** [comment]
I have a similar situation: 

- In a variant TargetResolve I set the maxHeight to some discrete value, then in transitionEnd set it to 100%. 
- Later, want to set the value back to some discrete value, but it only animates to %s after being set to a percentage. 

I can calculate the discrete values I want to set by hand, before the animations start. Is there really no way to control the underlying motion values to be like "hey, you were 100%, now _set_ yourself to 700px (which is your current measured height), and then animate down to 100px"?
