### ISSUE TITLE
[QUESTION] How does one add transform: perspective(2000px) in an animation

### ISSUE THREAD

**Issue by AlexanderMelox** [framer/motion#687]
I'm working with `rotateY` and was trying to add a transform: perspective(2000px) to my styles but it keeps getting overwritten. How can I add this a motion component? Thanks! 

Example: 
https://codesandbox.io/s/credit-card-form-hqebf?file=/src/App.js

**Comment by khuezy** [comment]
https://github.com/framer/motion/blob/be6b253ae130bda9c6681c064e8c0d076718ce43/src/render/dom/utils/unit-type-conversion.ts#L73

https://github.com/framer/motion/blob/main/src/render/dom/utils/build-transform.ts

Doesn't look like `perspective` is being built into the `transform: ...` string. Adding this to `transform` would help sell certain animations (like page flips).

**Comment by AlexanderMelox** [comment]
I'll try this, thanks!

**Comment by konoplyyaa1** [comment]
Or you can use `transformPerspective` option 

Example:
```
style={{
  rotateX: rotateXOnScroll,
  scale: scaleOnScroll,
  transformPerspective: "1200px",
}}
```
