### ISSUE TITLE
Mobile Animation is absolute FUBAR

### ISSUE THREAD

**Issue by joebentaylor1995** [framer/motion#688]
**1. Describe the bug**

On desktop the animation is perfect, but on mobile, its pixelated, not the right size and sometimes doesnt even animate.

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/image-sequence-animation-ovkf9?file=/src/ImageSequence/index.jsx

**3. Steps to reproduce**

1. Scroll.

**4. Expected behavior**

Same animation as desktop, a smooth fade and zoom.

**Comment by InventingWithMonster** [comment]
Seems to work great on iOS. What phone/browser are you on?

**Comment by joebentaylor1995** [comment]
iOS iPhone XS Max.

I seem to have the same issue on mobile on my other site too, it’s like it’s cutting elements (the ones that are animated) off as I’m scrolling

**Comment by rolivegab** [comment]
About the pixelated problem, i think it's because image is still loading.

**Comment by joebentaylor1995** [comment]
Not a chance that it’s that

Kind regards,

Joe

**Comment by redbar0n** [comment]
In Safari on iPhone 6S and it runs just as well as on desktop.
