### ISSUE TITLE
does not unmounts immediately after exit animation

### ISSUE THREAD

**Issue by bhuvaneshdesai** [framer/motion#689]
I have created animated modal container 
its working fine for most part
only issue is **after doing the exit animation it takes a second or two to un mount** (in that period cannot click anywhere else)

code sandbox - https://codesandbox.io/s/restless-platform-oovo1?file=/src/App.js
To see the issue 👇🏻 
- click show modal button 
- click anywhere to close the modal
- notice that the scrollbar still exist denoting modal is not unmounted
- **also you cannot reopen modal immediately on clicking of open modal button after exit animation (for that 1 sec)**

i had seen `safeToremove `but didn't understand how to use it as there is no proper documentation

**Comment by InventingWithMonster** [comment]
If you take a look at this branch in framer-motion@2.6.2: https://codesandbox.io/s/billowing-sun-thf9f?file=/src/App.js

I've removed `delay: 0` from your transition so `when: "afterChildren"` works correctly. This latest version has some bug fixes around orchestration. The overlay fade out runs at the correct moment now and you can see the modal is removed when that animation completes.

You can add `pointerEvents: "none"` to the overlay exit variant (and the opposite to the visible one) if you want pointer events to pass through during an animation.

Or you could do something like this:

```
const opacity = useMotionValue(0)
const pointerEvents = useTransform(opacity, latest => latest < 0.5 ? "none" : "auto")

<motion.div
        className="animated-modal-backdrop"
       style={{ opacity, pointerEvents }}
```

To disable them when opacity is less than a certain value
