### ISSUE TITLE
[BUG] Initial/animate not working when mixed with whileHover as string

### ISSUE THREAD

**Issue by rijk** [framer/motion#690]
Sandbox: https://codesandbox.io/s/ecstatic-wind-q3q1n?file=/src/App.js

Maybe I am misusing this, and you either have to go full variants or no variants at all, but since I cannot find anything in the documentation about this I am posting because this might be bug.

Use case: I had a simple component that had inline `initial`/`animate` styles for a fade-in effect. I then had to add a hover effect, that only affects one of the element’s children (an animated underline). Because I couldn’t put the `whileHover` on the underline itself, I tried to use a variant for this on the parent.

**Steps to reproduce**

1. Go to https://codesandbox.io/s/ecstatic-wind-q3q1n?file=/src/App.js
2. Uncomment line # 37
3. Reload

**Expected behavior**

Fade in animation, same as when line # 37 is commented out.

**Actual behavior**

Element never animates in (is stuck in `initial` state).

**Comment by rijk** [comment]
This seems to be fixed in the latest version of framer-motion: https://codesandbox.io/s/magical-grothendieck-cj4zd?file=/src/App.js

**Comment by AsuraKev** [comment]
@rijk  is it fixed for you? I still see issues with it. I have this structure, hover effect is not triggered when animate is specified in string

![image](https://github.com/framer/motion/assets/52765572/3f4eeb78-0acd-4712-b43d-b4f890a738d9)

**Comment by rijk** [comment]
@AsuraKev  Not sure if this will work, but try removing the `animate` and `initial` props on the `<motion.img>`. I found it to work best if all those states are controlled from one parent (in this case, move them to the `<motion.div>` that has the `whileHover`). The childs will pick them up with their variants config anyway.

**Comment by AsuraKev** [comment]
@rijk surprisingly that worked! thanks for tha help :)
