### ISSUE TITLE
[BUG] `motion.*` follows pointer when scrolling

### ISSUE THREAD

**Issue by carljohnesan** [framer/motion#691]
`motion.youNameIt` follows pointer when scrolling while motion animating, after state update in `onHoverStart`/`onHoverEnd`(only), while pointer in its bounding area (aka hitbox)

Codesandbox reproduction - 
<https://codesandbox.io/s/framer-motion-scroll-bug-during-hover-reproduction-21b87?file=/src/index.js>

**Comment by InventingWithMonster** [comment]
This doesn't seem to be a problem in 2.6.2 - if you still have issues please reopen
