### ISSUE TITLE
[BUG] AnimatePresence's onExitComplete prop doesn't work

### ISSUE THREAD

**Issue by alex83130** [framer/motion#693]
**1. Read the [FAQs](#faqs) 👇**
👍 

**2. Describe the bug**

The callback prop onExitComplete of AnimatePresence send an error 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-tfkel?file=/src/index.js

**4. Steps to reproduce**

1. Click on the button "Animate"
2. See the error in the console

**5. Expected behavior**

I would like to have the callback correctly call when the AnimatePresence exit end

**6. Video or screenshots**

![issue](https://user-images.githubusercontent.com/15250423/89715622-e59e1e00-d974-11ea-93f8-414b58c23fda.PNG)

**7. Environment details**

![environement](https://user-images.githubusercontent.com/15250423/89715682-61986600-d975-11ea-9a85-65fee8d1c815.PNG)

**Comment by em** [comment]
Can we get an update on this? onExitComplete doesn't seems to fire at all in any case.

**Comment by mattgperry** [comment]
Closing this as the sandbox doesn't seem to reflect the bug any longer. From this log it looks like `onExitComplete` was passed to a `motion.` component rather than `AnimatePresence` because this couldn't be passed to the DOM otherwise.
