### ISSUE TITLE
[BUG] - using drag with animated motion doesn't hide the element

### ISSUE THREAD

**Issue by ahmedu007** [framer/motion#694]
**2. Describe the bug**

Adding a drag prop to `motion.div` interrupts the translation on exit

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/suspicious-bohr-s4w6z

(If you remove `dray='y'` prop, it works as expected)

**5. Expected behavior**

Expected the sheet component to `translateY` off the screen so the other elements are interact able again.

**Comment by InventingWithMonster** [comment]
Looks like an incompatibility between drag and % values

**Comment by mattgperry** [comment]
Closing as the sandbox doesn't seem to reflect the bug anymore, but also we recently released a version that helped drag work with %
