### ISSUE TITLE
[BUG] flickering when switching between position relative/absolute during drag

### ISSUE THREAD

**Issue by souporserious** [framer/motion#698]
**2. Describe the bug**

When changing properties like position `absolute` or `fixed` from `relative` while dragging the layout projection seems to flicker. When setting `fixed` specifically it looks like the coordinates don't get applied correctly.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[Codesandbox](https://codesandbox.io/s/usedraggabledroppable-collisions-c1pox?file=/src/App.js:2118-2126)

**4. Steps to reproduce**

1. Drag an item in/out of the container

**5. Expected behavior**

Expect the layout to not shift or flicker when changing `position` during a drag.

**6. Video or screenshots**

![drag](https://user-images.githubusercontent.com/2762082/89842543-c6e18800-db2a-11ea-8e12-7b1a16a56300.gif)

**Comment by souporserious** [comment]
Updated to the latest version (2.4) and now I'm seeing this error when setting any React state during a drag and using `AnimatedSharedLayout`. If I comment it out all seems to work fine, just no container animations.

![image](https://user-images.githubusercontent.com/2762082/90079731-92520580-dcbd-11ea-8faf-8e2c40713e32.png)

**Comment by InventingWithMonster** [comment]
The error should be fixed in 2.4.1

**Comment by souporserious** [comment]
That fixed it, thanks! Still has the distortion, but at least it's not erroring 😅 . I appreciate all of the work you've been doing on this 🙏  Drag and drop and layout projection are pretty remarkable when used together!

**Comment by InventingWithMonster** [comment]
I'll have to take a deeper look into your example, as a more minimal reproduction doesn't show this: https://github.com/framer/motion/compare/fix/drag-outside#diff-d9e71cedd924e3adc169f7620c6f0ba7R1

**Comment by souporserious** [comment]
Thanks for looking! That demo looks great! I'll keep chipping away at it in the latest version to see if I can find the culprit and reopen this if anything stands out.

**Comment by souporserious** [comment]
This [Codesandbox](https://codesandbox.io/s/vigorous-dust-b8god?file=/src/App.js) might help showcase it better. Just tried to do similar things I had in my complex demo by changing some values in the minimal demo you made while dragging and trying to use the `layout` prop.
