### ISSUE TITLE
[BUG] delayChildren only works one level in tree

### ISSUE THREAD

**Issue by rijk** [framer/motion#699]
**Describe the bug**

Not sure if this is a bug or works as intended, [the docs on this](https://www.framer.com/api/motion/types/#orchestration.delaychildren) are relatively sparse.

I am trying to orchestrate the timing of fading in from a parent component. There are multiple levels of animation in the child components; for example a fade in of the container + a staggered slide in for each line of text. 

While trying this using variants, I found that **only the direct children** of the parent follow the delay set via `delayChildren`. _Their_ children just animate instantly, without delay.

**Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/nameless-https-ywzfh

**Steps to reproduce**

1. Go to Sandbox
2. Click on "Go to other page"
3. Note that the text scales up with a 1.5s delay — but also note that the second paragraph is already visible from the start

**Expected behavior**

The second paragraph should only start to fade in after the same 1.5s delay defined in the parent’s `delayChildren`.

**Comment by InventingWithMonster** [comment]
This is a bug - delays are intended to be cumulative.
