### ISSUE TITLE
[BUG] Keyframes Duration not reacting

### ISSUE THREAD

**Issue by whirledsol** [framer/motion#707]
**1. Read the [FAQs](#faqs) 👇**

- [X] 

**2. Describe the bug**

Using animation keyframes, when changing the transition duration from a prop, re-render does not occur. Re-render does occur if the animate properties change.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
[https://codesandbox.io/s/mystifying-grothendieck-ok8qq?file=/App.js](https://codesandbox.io/s/mystifying-grothendieck-ok8qq?file=/App.js)

**4. Steps to reproduce**

1. Create a motion component with animate using keyframes and transition using a dynamic duration value
1. Have wrapper component control the dynamic duration value.
1. Observe that the duration does not change until the element re-renders.

**5. Expected behavior**
1. motion element should re-render if the transition.duration property is changed

**7. Environment details**
CRA app and framer-motion 2.4.2

**Comment by InventingWithMonster** [comment]
Animations are only re-triggered when the values in `animate` change. We probably aren't going to change this because the of the complexities involved in analysing `transition` (deep string/number equality) vs the availability of an imperative API (`useAnimation`)

**Comment by whirledsol** [comment]
Good to know and understood.
I solved the problem by making the motion element `key={duration}`. Hacky but it works.
