### ISSUE TITLE
[BUG]Error: [framer-motion@2.4.2 › style-value-types@^3.1.9] Can't find package style-value-types@^3.1.9

### ISSUE THREAD

**Issue by Holybasil** [framer/motion#708]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

When installed framer-motion, 
```
Install fail! Error: [framer-motion@2.4.2 › style-value-types@^3.1.9] Can't find package style-value-types@^3.1.9
Error: [framer-motion@2.4.2 › style-value-types@^3.1.9] Can't find package style-value-types@^3.1.9
```
So, I installed `style-value-types` manually,  and `"style-value-types": "^3.1.7"` came into my package.json.
Then I checked package.json of `framer-motion`,  `"style-value-types": "^3.1.9"` was in dependencies.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

**4. Steps to reproduce**

1. npm install framer-motion -S

**5. Expected behavior**

could install.

**6. Video or screenshots**

![image.png](https://i.loli.net/2020/08/17/Haf3IbTU7QMFgD2.png)

**Comment by InventingWithMonster** [comment]
You are likely using a private instance of npm: https://www.npmjs.com/package/style-value-types
