### ISSUE TITLE
[BUG] Animation Flickering/Jumping

### ISSUE THREAD

**Issue by Elia-d** [framer/motion#711]
**2. Describe the bug**

Animation Is Flickering when using the "backdrop-filter" CSS Property.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

**4. Steps to reproduce**

some times it takes up to 30 seconds for this behavior to start, so you might need to wait quite a bit 🙂

https://codesandbox.io/s/determined-chebyshev-wsvq2?file=/src/App.js

**7. Environment details**

MacOs, Chrome 84
Next.js framer-motion 2.4.3
CRA framer-motion 2.5.1

**Comment by InventingWithMonster** [comment]
This is weird. Seems to happen randomly when `scale` is set to `0`: 

<img width="235" alt="Screenshot 2020-08-26 at 11 21 22" src="https://user-images.githubusercontent.com/7850794/91286122-55dadb00-e78e-11ea-8d27-2c2f47960f95.png">

**Comment by InventingWithMonster** [comment]
```
scale: [0, 0.000905391446755624, 0]
```

Triggers this quite often. Looks like there's rendering issues with values between ? and 0 when placed over background-image

**Comment by Elia-d** [comment]
I found it also weird, can't think of any reason why this could be happening.

So far, it was only acting like this in Chrome and Microsoft Edge. It's acting as expected in Safari mobile browsers on iOS.
Firefox has also no problem but the backdrop-filter isn't yet supported there so...

It seems that it is acting like this in Chromium-based browsers if I'm not mistaking 🤔

**Comment by InventingWithMonster** [comment]
Changing the filters affects the artefacts 😂

**Comment by Elia-d** [comment]
I'm sorry, I did not know this was a new feature. I'll close the issue 🤣

**Comment by InventingWithMonster** [comment]
NW, I am filing this in the Chromium bug tracker

**Comment by InventingWithMonster** [comment]
Tracking at https://bugs.chromium.org/p/chromium/issues/detail?id=1121936
