### ISSUE TITLE
[BUG] dragControls dont respond on touch devices unless the user *taps* between each gesture.

### ISSUE THREAD

**Issue by sami616** [framer/motion#712]
**Describe the bug**

 dragControls dont respond on touch devices unless the user *taps* between each gesture. This is working fine on desktop devices as far as i can tell.

**Provide a CodeSandbox reproduction of the bug**

Code: https://codesandbox.io/s/dreamy-pine-nrm6w?file=/src/App.tsx
Preview: https://nrm6w.csb.app/

**Steps to reproduce**

1. Open the Preview link above
2. Set chrome dev tools to mobile mode
3. Try dragging on the blue area (nothing happens)
4. Tap once on the blue area, then try dragging (now works)
5. Repeat.

**Expected behavior**

I expect this to work as it does on desktop, the drag start should fire as soon as the gesture starts.

**Comment by InventingWithMonster** [comment]
Can you try again with the latest version of motion? I can't replicate this on iOS.

**Comment by InventingWithMonster** [comment]
This more of an event thing - drag controls isn't even firing. Replacing onMouseDown with onPointerDown will work as you expect. I'm going to make sure our docs are up to date.

**Comment by yashspr** [comment]
Even while using `dragControls` with `onPointerDown`, there seems to still be an issue on mobile devices. Using Framer Motion 6.2.6. As the OP mentioned, the drag doesn't work and the user has to repeatedly taps between each gesture.

The drag seems to be relatively better in Firefox mobile than on Chrome.

**Comment by trm217** [comment]
Still an issue with the latest framer-motion version when using onPointerDown in combination with dragControls.

**Comment by aroman** [comment]
still happening as of framer-motion `10.15.2`. might i suggest we re-open this issue? this is easily reproducible using Chrome DevTools
