### ISSUE TITLE
[BUG] Starting animate scale below 1 causes flash

### ISSUE THREAD

**Issue by colinricardo** [framer/motion#725]
**2. Describe the bug**
If any value less than `1` is provided for scale is given as the first argument for `animate` it reliably causes a flash about 80% of the time. 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
[CodeSandbox here](https://codesandbox.io/s/framer-motion-keyframes-forked-47u4y?file=/src/Example.tsx). It uses the [keyframes example from the docs](https://www.framer.com/api/motion/examples/#keyframes
), with the only change being the first scale argument:

`scale: [0.5, 2, 2, 1, 1]` versus `scale: [1, 2, 2, 1, 1]`

**4. Steps to reproduce**
1. Go to the above CodeSandbox. 
2. Click the refresh button: 

![image](https://user-images.githubusercontent.com/21294951/90983390-b63b0400-e565-11ea-8c8f-33465f6f62f6.png)

3. Watch to see the flash when the div mounts.  

**5. Expected behavior**
Should not flash.

**Comment by InventingWithMonster** [comment]
Setting `initial={{ scale: 0 }}` will fix the flash - the animation is starting after the component has been rendered, which it will otherwise do with the value set in `initial`. I can take a look into how easy it'd be to detect a mount `animate` with keyframes during the initial render and taking the initial value from that.

**Comment by InventingWithMonster** [comment]
I'm going to leave this as a wontfix for now for the following reasons:

1. There is a way to fix the flash using the existing API. This isn't a hack but the existing recommended way you would achieve this outside of keyframes.
2. The keyframes API allows `[null, ...]`, which respects the existing value for the animating value, so its quite prominently expected that the initial value may be set via `initial`
3. The complexity involved in changing this behaviour to allow for multiple initial values vectors is relatively high for relatively little payoff.
