### ISSUE TITLE
[BUG] event handler in doesn't work in child component with svg path

### ISSUE THREAD

**Issue by me-zhang** [framer/motion#728]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
when wrapping the motion.path in a parent component and passing in the event handler (onMouseEnter), the event handler doesn't work as intended. And also, the initial value of the component with the event handler is not properly rendered

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/framer-motion-animate-presence-unmount-forked-dpjb3?file=/src/SvgComponent.tsx

**4. Steps to reproduce**

1. The black capsule icon was rendered when initially loaded. 
2. When mouse hover on it, the capsule doesn't change

**5. Expected behavior**
1. when initially loaded, the capsule shape icon should not show, but the circle underneath should be rendered
2. when hover on the circle, the capsule shape icon should be triggered, and when the mouse leaves, the capsule should disappear and the circle shows again

**Comment by InventingWithMonster** [comment]
A `console.log` verifies the event handler is working correctly.

If you remove `motion.` from the elements, notice the circle does not render correctly.

Also no component has a `variants` prop so `animate={isChecked ? "checked" : "unchecked"}` is not expected to do anything.

**Comment by me-zhang** [comment]
Hi, i still think there is an issue with the event handler in the child component. 
I have revised my example for better clarification. 
Sandbox below:
https://codesandbox.io/s/framer-motion-svg-checkbox-forked-vgrre?file=/src/Example.tsx
 
The expected behavior is that when i hover on the black circle, a capsule shape icon will appear. When I move my cursor out of the circle, the capsule shape icon will disappear. 
In the example above, the onMouseEnter and onMouseOut doesn't work if i put them in the <CircleBackground> component. (as I have it now)
But if I move them to the <motion.svg>, then the capsule shape icon will appear when hover on svg container. 
But the intention is to have the capsule shape appear only when I hover on the circle, not on the svg container. Because i don't need the animation when hovering on white space. 

Hope i made my question clear. Thanks
