### ISSUE TITLE
[BUG] Transform origin is overridden in the style prop if layout={true}

### ISSUE THREAD

**Issue by pkrawc** [framer/motion#733]
## Description

When using motion values, any change in component state will set the `transform-origin` to `50% 50% 0px` even if it's explicitly defined in the style object.

**Demo**
https://codesandbox.io/s/sharp-kowalevski-xelnd?file=/src/Header.js

**Comment by InventingWithMonster** [comment]
Hey there. To fix this for now you can use the `originX` and `originY` styles.

```
originX: 0,
originY: 0
```

**Comment by InventingWithMonster** [comment]
Sorry that's incorrect ^ 

If you're using `layout`, `transform-origin` is dynamically calculated and applied. This is a `wontfix` for now as we do this to ensure the layout animations look correct.

Setting `originX` and `originY` will effect any additional transforms you add on top of `layout`, ie animating `scale`. But you won't see this reflected in `style`, they'll just be used in Motion's internal calculations.

**Comment by pkrawc** [comment]
Thanks for the feedback @InventingWithMonster, removing the `layout` prop did indeed fix my issue. Sorry for the confusion, I didn't realize I had left that on the h4 component.
