### ISSUE TITLE
[BUG]issue with the event handler in the child component.

### ISSUE THREAD

**Issue by me-zhang** [framer/motion#736]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

Hi, i think there is an issue with the event handler in the child component.
If I put the event handler in the parent component, which is motion.svg, then i can see the animation. But when I put the event handler into the chid component, which is the CircleBackground, then the event is not triggered, 

In the example above, the onMouseEnter and onMouseOut doesn't work if i put them in the CircleBackground component. (as I have it now)
But if I move them to the <motion.svg>, then the capsule shape icon will appear when hover on svg container.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/framer-motion-floating-icon-wxipv?file=/src/Example.tsx

**4. Steps to reproduce**

1. as the code show right now, onMouseEnter and onMouseOut are in the CircleBackgrouond component
2. the capsule shape icon animation was not triggered
3. if i move the event handler into the motion.svg component, the event will be triggered

**5. Expected behavior**

When I hover on the black circle, the capsule shape icon should appear, and when the cursor moves out, the capsule shape icon should disappear.
if I move the event handler to motion.svg component, the animation will be triggered. But i don't want the event to be triggered when i hover on the while space(svg container)

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

**7. Environment details**

If applicable, let us know which OS, browser, browser version etc you're using.

### `AnimatePresence` isn't working

Have all of its immediate children got a unique `key` prop that **remains the same for that component every render**?

```jsx
// Bad: The index could be given to a different component if the order of items changes
<AnimatePresence>
  {items.map((item, index) => <Component key={index} />)}
</AnimatePresence>
```

```jsx 
// Good: The item ID is unique to each component
<AnimatePresence>
  {items.map((item, index) => <Component key={item.id} />)}
</AnimatePresence>
```

Is the `AnimatePresence` correctly outside of the controlling conditional? `AnimatePresence` must be rendered whenever you expect an `exit` animation to run - it can't do so if it's unmounted!

```jsx
// Bad: AnimatePresence is unmounted - exit animations won't run
{isVisible && (
  <AnimatePresence>
    <Component />
  </AnimatePresence>
)}
```

```jsx
// Good: Only the children are unmounted - exit animations will run
<AnimatePresence>
  {isVisible && <Component />}
</AnimatePresence>
```

**Comment by noskovvkirill** [comment]
Experiencing the same issue after the last update 👀

**Comment by InventingWithMonster** [comment]
@me-zhang Where are you passing the event handlers through?

**Comment by InventingWithMonster** [comment]
This is your second issue that was opened erroneously in two days - can you please double-check your code before opening another? A good way to isolate a bug to Motion is to get your code working in React and then add `motion.` to the involve elements. If it then breaks, it's a Motion bug.
