### ISSUE TITLE
[BUG] toType.transform is not a function

### ISSUE THREAD

**Issue by raulfdm** [framer/motion#737]
## Description

Hello there.

So, on `framer-motion@2.6.2` this validation has been added:  https://github.com/framer/motion/compare/v2.6.1...v2.6.2#diff-43dd2c39c36b17f0016ccc25e03ea6e8R227

And it breaks `height` animation from `0` to `auto`.

<img src="https://user-images.githubusercontent.com/12464600/91416624-f2b17d00-e84f-11ea-80da-4d31c84c3ff1.png" width="400px" styles="margin: 0 auto;"></img>

## Code Sandbox

@InventingWithMonster example: https://codesandbox.io/s/framer-motion-accordion-qx958?fontsize=14&module=%2Fsrc%2FExample.tsx

## Steps to Reproduce

1. Open the codesandbox mentioned;
2. Switch the version from `1.2.0` to `2.6.2`
3. Try to click on the expanded animation

## Expected behavior

It keeps animating between height `0` and height `auto`.

Keep in mind that on `2.6.1` it's still working.

## Environment details

It happens in any browser

**Comment by InventingWithMonster** [comment]
Thanks for the report! This is fixed in `2.6.3`
