### ISSUE TITLE
[BUG] prop.match is not a function

### ISSUE THREAD

**Issue by clementizard** [framer/motion#741]
### Description

Hello there

As described in this style-value-types issue: https://github.com/Popmotion/popmotion/issues/421
Font size animations breaks without having "px" at the end. Properties like staggerChildren seens to be ignored and slows everything down.

CodeSandbox: https://codesandbox.io/s/headless-dust-w5yh0?fontsize=14&hidenavigation=1&theme=dark
(Sorry in advance if this is no the right way to share a CodeSanbox, i've never used it before)

**Expected behavior**

This issue is new, i've used framer-motion before without having to put these "px" at every end of font size fields.

**7. Environment details**

Browser: Google Chrome 84.0.4147.105
Framer-motion: 2.6.3

Edit: typo

**Comment by clementizard** [comment]
Update: Downgrading to framer-motion: 2.0.0 fixes the issue

**Comment by InventingWithMonster** [comment]
I think the behaviour changed when upgrading to Popmotion 9. 

`fontSize` here is read from the DOM to get an initial value as no `initial` is set. This will set the initial animation as (for instance) `"16px"` to `18`. Popmotion would infer that as a `px` animation whereas this is unaccommodated in Popmotion 9.

I'll take a look at reimplementing this behaviour.

**Comment by clementizard** [comment]
Thanks for your fast response! I'll keep checking newer versions and close the issue when needed.

**Comment by tmikeschu** [comment]
I had the same error due to `margin` values where changing to a string worked:

```diff
const variants = {
  expanded: {
    opacity: 1,
    x: 0,
    width: 'auto',
    marginLeft: '0.375rem',
    marginRight: '0.375rem',
  },
  collapsed: {
    opacity: 0,
    x: 0,
    width: 0,
-    marginLeft: 0,
-    marginRight: 0,
+    marginLeft: '0',
+    marginRight: '0',
  },
};
```

```
    "@popmotion/popcorn": "^0.4.4",
    "framer-motion": "^2.0.0",
```

**Comment by ffdead** [comment]
I have a similar problem that only occur when wrapping a `useTransform` with a `useSpring()` and the output range are strings with `vh` units.

This works: 
```
useTransform(scrollY, [0, 3000], ['-50vh', '50vh'])
```

This returns the error `Uncaught TypeError: prop.match is not a function at Object.createTransformer`
```
useSpring(useTransform(scrollY, [0, 3000], ['-50vh', '50vh']))
```

Version affected:
- Any version from 2.5+. (popmotion 9)

**Comment by Pajn** [comment]
I get this crash with `<motion.div animate={{borderRadius: 10}} ...` but only in Chrome, not in Firefox. `<motion.div animate={{borderRadius: '10px'}} ...` works in both browsers.

**Comment by JoshuaKGoldberg** [comment]
This diff actually worked for me:

```diff
    <motion.div
-      animate={{ opacity: 1, marginTop: 0 }}
+      animate={{ opacity: 1, marginTop: '0px' }}
      initial={{ opacity: 0, marginTop: '30px' }}
      transition={{ duration: 0.5 }}
    >
```

**Comment by Bobeta** [comment]
I have the same, amongst other situations when using **useSpring** with transform. Is there any fix in sight?

**Comment by cristiantx** [comment]
Is there any workaround for this without having to downgrade the library?

**Comment by EDMONDGIHOZO** [comment]
> This diff actually worked for me:
> 
> ```diff
>     <motion.div
> -      animate={{ opacity: 1, marginTop: 0 }}
> +      animate={{ opacity: 1, marginTop: '0px' }}
>       initial={{ opacity: 0, marginTop: '30px' }}
>       transition={{ duration: 0.5 }}
>     >
> ```

this works on all integer values, thanks.

**Comment by mattgperry** [comment]
Fixed in the meantime
