### ISSUE TITLE
[BUG] Input Fields are not behaving as expected when used with react-hook-form

### ISSUE THREAD

**Issue by Elia-d** [framer/motion#742]
**2. Describe the bug**

When using ```motion.input``` with react-hook-form, input fields are getting unregistered after resetting the form.

As you would see in the CodeSandbox provided below, using either normal input fields or using an input field with ```React.forwardRef``` both work as expected with no problems.

However, when using ```motion.input```, react-hook-form does not recognize the input fields after resetting the form (even when I tell it not to unregister inputs when removed from the DOM).

I also thought putting a key on the input field might probably fix the problem, but it didn't!

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/competent-wu-fk7dp?file=/src/App.js

**4. Steps to reproduce**

1. Go to the CodeSandbox provided above
2. Fill the form
3. Submit the form (form will reset after submitting)
4. Fill the form again
5. At this point when you try to submit the form, the framer-motion input fields will show a required error even though they are valid (because they are no longer recognized by react-hook-form).
6. If you look in the console before and after resetting the form, you will see that the Refs of the motion input fields do not exist on the ```fieldsRef``` object anymore!

**5. Expected behavior**

Motion input fields should behave like a regular forwardRef input field

**7. Environment details**

Os: macOs
Browser: Chrome 85

**Comment by mattgperry** [comment]
I think this functionality of `react-hook-form` is relying on a very specific peculiarity of how React handles callback refs: https://reactjs.org/docs/refs-and-the-dom.html#caveats-with-callback-refs

Motion isn't using `ref` incorrectly either and I think this is a bit of an edge case to actively support.
