### ISSUE TITLE
[QUESTION] Define a range for useTransform (Parallax case)

### ISSUE THREAD

**Issue by alex83130** [framer/motion#744]
Following the Parallax example : https://codesandbox.io/s/framer-motion-parallax-osm5p, I would like to add the possibility to define a range for the Y value. instead of see it translated indefinitely.
Basically in my specific case if I have an element of 200px I would like to see it only makes a translate-y between [elementTop, elementTop + elementHeight], so [0 , 200] for example.
I tried a lot but seems I have missing knowledge in order to tackle this one...
I have created a codesandbox : https://codesandbox.io/s/framer-motion-tfkel?file=/src/index.js

The help of some of you would be greatly appreciated :)

**Comment by mattgperry** [comment]
Apologises but we don't have a ready example for this kind of thing.

**Comment by mattgperry** [comment]
Apologises but we don't have a ready example for this kind of thing.
