### ISSUE TITLE
 ReferenceError: motion is not defined

### ISSUE THREAD

**Issue by moondustkj** [framer/motion#745]
I'm using motion.div in my project and while running test cases it throws a Ref error. Some css is added to motion.div using 'babel-plugin-styled-components'. If I remove those styles then the test cases pass but with it fails.
Mock function for framer-motion :
`import React from 'react'; 
jest.mock('framer-motion', () => {
  const AnimatePresence = jest.fn(({ children }) => children);
  const motion = {
    div: jest.fn(({ children, ...rest }) => <div {...rest}>{children}</div>)
  };
  return {
    AnimatePresence,
    motion
  };
});
`
Motion.div component:
`<motion.div
        className="container-fluid"
        css={' min-height: 100%; padding-right: 0; padding-left: 0;'}
      >
....
....
</motion.div>`
For testing react-testing-library is used. Is there any way to pass the test case while keeping the css?

**Comment by jeltehomminga** [comment]
I had the same issue, but yarn upgrade solved it for me

**Comment by mattgperry** [comment]
Sorry I don't personally know about this but we don't support individual Babel plugins. I think the bug will be the SC plugin.

**Comment by byrongomezjr** [comment]
you need to import motion from framer-motion at the top of your component as
import { motion } from "framer-motion";
