### ISSUE TITLE
Nested Animation works if outer AnimatePresences is initial false

### ISSUE THREAD

**Issue by captDaylight** [framer/motion#751]
I have an outer animation with `AnimatePresences` that toggles between settings and the main app. The initial animation is set to false.

Nested within that is another animation that doesn't trigger until clicked, which in the example below is called `ShowHide`.

The problem is the `ShowHide` animation doesn't work until the settings view is triggered. This is because the outer initial animation is set to false. I'm trying to find a way to not animate the settings on load but still be able to trigger the nested animation.

![Sep-05-2020 08-28-05](https://user-images.githubusercontent.com/700617/92305216-48261200-ef53-11ea-93f0-e83b1f19f69e.gif)

[Working example.](https://codesandbox.io/s/framer-motion-animatesharedlayout-menu-underline-demo-forked-ugldp?file=/src/ShowHide.js:435-466)

**Comment by InventingWithMonster** [comment]
You can make an `AnimatePresence` boundary here: https://codesandbox.io/s/framer-motion-animatesharedlayout-menu-underline-demo-forked-qbwd1?file=/src/ShowHide.js

**Comment by captDaylight** [comment]
Thanks @InventingWithMonster, good to know!
