### ISSUE TITLE
[BUG] useTransform changes behaviour from old to new version

### ISSUE THREAD

**Issue by mariasimo** [framer/motion#752]
**Describe the bug**

I'm trying to use useTransform to change the styles on scroll position. I'm reusing a snippet i had used successfully in a previous project (with version 1.1.1 of Framer Motion installed) but now the behavior is not the same. 

```jsx
  const [elementTop, setElementTop] = useState(null);

  useLayoutEffect(() => {
    if (!ref.current) return;
    setElementTop(ref.current.offsetTop);
  }, [ref]);
  
  const opacity = useTransform(scrollY, [elementTop, elementTop + 600], [1, 0]);
```
This works ok for previous versions, but in current version elementTop arrives to useTransform as a null value and final value of ouput range is applied inmediatly

**IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/solitary-meadow-6du76

**Steps to reproduce:** 
1. Scroll and observe behavior: opacity of bottom div becomes 0 before element is in viewport
2. Change version to 2.3.0. and older at package.json and notice behavior how now opacity starts changing when element is in top of viewport

**Expected behavior**
I would expect this to behave as in previous versions so I can pass elements' position and dimension info into useTransform
Maybe now I have to arrange my component differently in order to work? Please let me know

Thanks!

**Comment by afroald** [comment]
I have the same issue, `useTransform` is not usable anymore since 2.3.0. There is another issue already: https://github.com/framer/motion/issues/513
