### ISSUE TITLE
whileHover conflicted prop with exit does not get animated

### ISSUE THREAD

**Issue by p0ria** [framer/motion#755]
I have this variant on a button:
`hover: {
    rotate: -20
  },
  exit: {
    rotate: [0, 1000]
  }`
when I click the button, it gets removed from the DOM and exit animation fires.
But before click because I hovered over the button, the hover animation gets executed.
The problem is when I click the button it does not rotate from 0 to 1000, because It conflicts with hover animation. How can I have rotate animation both on hover and exit animation while clicking button causes its removal from DOM?

**Comment by mattgperry** [comment]
If this is still a problem please reopen with a codesandbox, thanks!
