### ISSUE TITLE
[QUESTION] Timing of onExitComplete for AnimatePresence

### ISSUE THREAD

**Issue by rplumlee** [framer/motion#764]
Hey team,

I've done pretty exhaustive digging through the source code and was wondering if you could explain how the timing of the unmounting of an Animated Presence works.

Specifically, onExitComplete seems to be tied to a period of 1s rather than tying to the duration of exit animations or anything that I've tried tweaking.  Check out the sandbox at https://codesandbox.io/s/exciting-benz-42e4s

I've logged 'hey' to the console, and despite .1s, non-staggered elements on the presence itself, the timing of the logging (or the disappearance of the scrollbar) seems to be static.  Is this built in statically or am I missing something?

Thanks!

**Comment by mattgperry** [comment]
`onExitComplete` seems to be working as you'd expect when using version 5+

The `AnimatePresence` prop is only called in one place and specifically when all exiting components have finished their layout animations and the component is ready to trigger a forced rerender, which then flushes out all the exiting nodes from the DOM
