### ISSUE TITLE
[BUG] AnimatePresence doesn't work with `animate={controls}` 

### ISSUE THREAD

**Issue by zeyi1** [framer/motion#766]
The exit prop of AnimatePresence is not getting trigger when using it with useAnimation and/or react-intersection-observer.
I wanted to start the animation when the element reaches the viewbox, so I used react-intersection-observer and useAnimation to trigger the animation, the exit prop breaks at this point.

I created a codesandbox at https://codesandbox.io/s/holy-dream-rb5gu?file=/src/index.js
It has a working example and an example with useAnimation and react-intersection-observer.

How should I go about fixing this?

**Comment by O4epegb** [comment]
Seems like it was fixed at some point, but broke again, possibly related issues:

https://github.com/framer/motion/pull/303
https://github.com/framer/motion/issues/276

**Comment by mattgperry** [comment]
Repro: https://codesandbox.io/s/competent-bush-w589f5?file=/src/App2.js
