### ISSUE TITLE
[BUG] Drag is broken on mobile @ 2.6.15

### ISSUE THREAD

**Issue by rizkyramadhan** [framer/motion#770]
Please visit https://d9dwx.csb.app/ on mobile.

This is the codesandbox https://codesandbox.io/s/framer-motion-drag-with-constraints-forked-d9dwx?file=/package.json

**Comment by InventingWithMonster** [comment]
Make/OS? Works on iOS.

**Comment by rizkyramadhan** [comment]
Sorry, it broke at my two device:
- chrome on android, 
- chrome on windows (switch to mobile mode)

**Comment by o-alexandrov** [comment]
I also confirm the regression when bumping from 2.6.13 to 2.6.15. The code sandbox with slideshow breaks for:
- iOS 13/iPhone X

Typing from a mobile device, will share more details once from a laptop

**Comment by o-alexandrov** [comment]
@rizkyramadhan btw, if you refer to `dragConstraints` not working on your codesandbox, add:
- [updated codesandbox](https://codesandbox.io/s/framer-motion-drag-with-constraints-forked-hejc6)

<img width="714" alt="Screen Shot 2020-09-23 at 1 23 00 AM" src="https://user-images.githubusercontent.com/9992724/93974525-8ab16200-fd3b-11ea-8498-5244fc5fd984.png">

**Comment by InventingWithMonster** [comment]
Ah yeah, Chrome in mobile mode did it, thanks for the heads up

**Comment by InventingWithMonster** [comment]
This is bizarre, I can't replicate using the local examples (only on CodeSandbox) and there's been nothing released between 13-14 that should touch drag.

**Comment by rizkyramadhan** [comment]
> This is bizarre, I can't replicate using the local examples (only on CodeSandbox) and there's been nothing released between 13-14 that should touch drag.

Try windows machine. It bugged on windows...

**Comment by InventingWithMonster** [comment]
It's the same in Windows/Mac Chrome mobile emulation. Happens on CodeSandbox but not locally.

**Comment by rizkyramadhan** [comment]
> It's the same in Windows/Mac Chrome mobile emulation. Happens on CodeSandbox but not locally.

Are you sure installed 2.6.15 because i can reproduce it on fresh install cra app.

**Comment by InventingWithMonster** [comment]
It's `main` yeah. I'll try and give it another go. From debugging its almost as if `pointermove` events stop being emitted.

**Comment by InventingWithMonster** [comment]
I think I know what this is - I enabled `sideEffects: false` but the viewport scroll blocking is a side effect so this is breaking in Webpack environments.

**Comment by o-alexandrov** [comment]
@InventingWithMonster it might be that as I saw a degradation for the slideshow when bumping from 2.6.13 to 2.6.15.
And I see you mentioned in the changelog, sideEffects change is introduced in 2.6.14

**Comment by InventingWithMonster** [comment]
Okay try `2.7.1` and let me know how that works for you.
