### ISSUE TITLE
[BUG] - AnimateSharedLayout - animation works with framer-motion@2.0.0-beta.77 but not in framer-motion@2.6.5 because there is no longer the transition props in the newer version

### ISSUE THREAD

**Issue by tiavina-mika** [framer/motion#773]
In the beta of 2.0.0 I had a transition for AnimateSharedLayout that was different from the transition on my motion elements. This let me have one animation for the shared layout and another for mount. Just curious if this is still possible as it seems that AnimateSharedLayout no longer has a transition prop?

**Comment by InventingWithMonster** [comment]
I'm not sure if or when `AnimateSharedLayout` will get a `transition` prop. But you can make different transitions like this:

```jsx
<motion.div
    layoutId="foo"
    transition={layoutTransition}
    animate={{
      opacity: 1,
      transition: mountTransition
    }}
/>
```

**Comment by tiavina-mika** [comment]
It works. thanks
