### ISSUE TITLE
[BUG] Transform not working on rect

### ISSUE THREAD

**Issue by PascalPixel** [framer/motion#777]
On >=2.0.0, transform doesn't work on rect

https://codesandbox.io/s/framer-motion-2-animatesharedlayout-animate-between-different-components-forked-1o6o5?file=/src/App.js

**Comment by InventingWithMonster** [comment]
Can you attach a screenshot of what you're seeing? What browser are you using?

**Comment by PascalPixel** [comment]
Had framer-motion saved to <2 in sandbox, fixed now

Safari, FireFox, Chrome:
![Screen Shot 2020-09-24 at 12 36 00](https://user-images.githubusercontent.com/3094044/94134607-8764c600-fe62-11ea-847b-260f532406f2.png)

**Comment by PascalPixel** [comment]
This was fixed in 3.4.0
