### ISSUE TITLE
Object does not animate upon changing the state

### ISSUE THREAD

**Issue by hypo-thesis** [framer/motion#782]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

Animate does not move on state change

```
function Content() {
  const [x, setX] = React.useState(200);
  const [y, setY] = React.useState(20);
  const handleX = (e) => {
    setX(e.currentTarget.value);
  };
  const handleY = (e) => {
    setY(e.currentTarget.value);
  };
  console.log(x, y);
  return (
    <div>
      <label>x</label> <input onChange={handleX} />
      <label>y</label> <input onChange={handleY} />
      <motion.div initial={{ x, y }} animate={{ x, y }}>
        H
      </motion.div>
    </div>
  );
}
```

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-2-animate-giudr

**5. Expected behavior**

I change the state for x and y and wish the object to move around but it does not.

**Comment by InventingWithMonster** [comment]
If you make the number values numbers this will work:

```javascript
setX(parseFloat(e.currentTarget.value));
```

**Comment by hypo-thesis** [comment]
> If you make the number values numbers this will work:
> 
> ```js
> setX(parseFloat(e.currentTarget.value));
> ```

Thanks mate
