### ISSUE TITLE
[BUG] Framer motion 2 animate attribute does not work

### ISSUE THREAD

**Issue by nimabrownlee** [framer/motion#785]
**1. Describe the bug**

Frame motion 2.7.5 animate is not working properly. 

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Here is a working example using beta version: https://codesandbox.io/s/framer-motion-automatic-animation-switch-demo-forked-sv552?file=/src/App.js

And the non working version: https://codesandbox.io/s/framer-toggle-button-vnb39

**3. Steps to reproduce**

Click on the switch.

**4. Expected behavior**

The switch handle should animate.

**5. Video or screenshots**

Use the codesandbox.

**6. Environment details**

Does not work on macOS latest version; Safari, Chrome and Firefox.

**Comment by 99diagha** [comment]
I believe the Motion API is different since leaving the beta.
Try this instead: https://codesandbox.io/s/framer-toggle-button-forked-smdv7?file=/pages/index.js

**Comment by InventingWithMonster** [comment]
Yep, layout is used for layout animations and all others must be explicitly defined. I’ll look into removing the beta sandboxes
