### ISSUE TITLE
[BUG] exit animation of conditionally rendered grandchildren of AnimatePresence not working

### ISSUE THREAD

**Issue by 55Cancri** [framer/motion#790]
**Describe bug**
The exit animation of an AnimatePresence's grandchildren are not happening if those grandchildren are conditionally rendered. Adding a nested AnimatePresence to surround those conditionally rendered components does not solve the issue. I would guess it has something to do with the keys of the grandchildren.

**Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/animatepresence-conditionally-rendered-grandchildren-7d3vd?file=/src/index.tsx

**Expected behavior**
Grandchildren are not removed from DOM until their exit animation has completed.

**Comment by InventingWithMonster** [comment]
Wrapping the grand children seems to work ok? https://codesandbox.io/s/animatepresence-conditionally-rendered-grandchildren-forked-hkg3p ?
