### ISSUE TITLE
[BUG] pathOffset in SVG path not working in React Typescript

### ISSUE THREAD

**Issue by jakapatb** [framer/motion#792]
I tried to use `pathLength` and `pathOffset` in my motion.path like this.

```
  <motion.path
        initial={{ pathLength: 0, pathOffset: 0.5 }}
        animate={{ pathLength: 1, pathOffset: 0.2 }}
        transition={{ duration: 5, loop: Infinity }}
        d="M47.5 116C120.3 94.4 197.167 222.333 226.5 289"
        stroke="black"
        stroke-width="5"
      />
```
 `pathOffset` have type-checking warning
 it's working in develop but not working when build

### Codesanbox

https://codesandbox.io/s/lingering-architecture-ry7xp?file=/src/App.tsx

### Quick fix

use styled-components to ignore type-checking but not good in long term
```
const Path = styled(motion.path)<any>``
```

**Comment by mattgperry** [comment]
Closing this for now as I believe this is fixed in latest versions, let me know if not.
