### ISSUE TITLE
[BUG] AnimatePresence stutters on exit

### ISSUE THREAD

**Issue by dadamssg** [framer/motion#798]
I have a sidebar i'm trying to animate opening and closing via the `width`. It opens smoothly but on close/exit it hangs for a good bit before snapping closed.

https://codesandbox.io/s/kind-galileo-ejknx?file=/src/App.js

**Steps to reproduce**

Click the "Open" button then click the "Close" button.

**Expected behavior**

I expect it to close as smoothly as it opens

![framer-exit](https://user-images.githubusercontent.com/881986/95283158-b1ce6000-0820-11eb-97cb-4c4b5b456e19.gif)

**Environment details**

Mac
Chrome

**Comment by dadamssg** [comment]
it seems that the padding on the animated div is what's causing the stutter. Yet, if i remove that the exit  animation is still significantly slower than open 

https://codesandbox.io/s/muddy-butterfly-9dqmj?file=/src/App.js

**Comment by dadamssg** [comment]
seems to either be a regression or change of behavior

https://twitter.com/samselikoff/status/1313909792574967828

**Comment by rakestto** [comment]
I have the same problem. This is my code example:
https://codesandbox.io/s/bug-when-the-item-is-closed-nncmx?file=/src/App.js

**Comment by dadamssg** [comment]
@rakestto it's the padding that causes the stutter 

https://codesandbox.io/s/bug-when-the-item-is-closed-forked-u6cp7

**Comment by rakestto** [comment]
Thank you. I was became crazy with it!

**Comment by NacereddineRebouh** [comment]
what was causing the stuttering for me was **"transition-all"** **(tailwindcss)** so i changed it to transition-shadow and it works fine
