### ISSUE TITLE
[BUG] Exit animations seem to use different default transition

### ISSUE THREAD

**Issue by mattgperry** [framer/motion#801]
https://codesandbox.io/s/muddy-butterfly-9dqmj?file=/src/App.js

**Comment by ChildishForces** [comment]
This doesn't actually appear to be based on exit but rather a transition back to 0. Try it with any other value and it works as expected.

**Comment by mattgperry** [comment]
Huh, that's right. Weird! Seems to have been fixed in the meantime.
