### ISSUE TITLE
[QUESTION/BUG] content stretched on resize animation with AnimateSharedLayout

### ISSUE THREAD

**Issue by dadamssg** [framer/motion#808]
**Describe the bug**

I'm trying to animate a sidebar opening/closing. The animation looks good when opening but as soon as it closes the main section snaps to a stretched look and then animates closing. I'm not sure why it's appearing stretched before it animates back to the initial height. It does not appear stretched when it's expanding.

I'm not sure if i'm doing something wrong or if this is a bug.

It would be nice if i could find a way to animate the both the the height/width on close like it does when opening. On closing, only the width changes and then the main section animates only the height. I'm surprised it's not animating both in the first place. I would think it would/should behave the inverse.

**CodeSandbox reproduction of the bug**

https://codesandbox.io/s/happy-silence-8ku7o?file=/src/App.js

**Steps to reproduce**

1. Click the Open button
2. Click the Close button
3. Notice how the text "Open" is stretched then shrinks back to the correct size.

**Expected behavior**

I never expect the "Open" text to look stretched.

**Video**

![Kapture 2020-10-12 at 21 22 21](https://user-images.githubusercontent.com/881986/95807968-11b98080-0cd1-11eb-947d-2cdc7d238771.gif)

**Environment details**

Mac, chrome

**Comment by mattgperry** [comment]
This is closed, but did you find a fix? What did the issue turn out to be?

**Comment by dadamssg** [comment]
hi @mattgperry, kind of but not really? As soon as i wrote that last paragraph i realized i hadn't tried that so i came up with this:

https://codesandbox.io/s/exciting-wildflower-jpnfe?file=/src/App.js

Which behaves a bit differently and doesn't look super great but i figure if i can speed it up, it'll look okay. It doesn't use `AnimateSharedLayout` though.

I closed the issue just so i wouldn't add to the issue noise. I can reopen if you like since i wasn't able to figure it out with `AnimateSharedLayout`.
