### ISSUE TITLE
[BUG] Tap event is triggered on pointer move

### ISSUE THREAD

**Issue by izorg** [framer/motion#809]
**2. Describe the bug**

Tap event is triggered when on drag action

**3. CodeSandbox**

https://codesandbox.io/s/framer-motion-gesture-animations-forked-jtwge?file=/src/Example.tsx

**4. Steps to reproduce**

1. Go to https://jtwge.csb.app/
2. Switch to mobile in Chrome responsive dev tools
3. Press on white square and move the pointer
4. See `tap` in console

**5. Expected behavior**

Tap event should not fire according to description in docs `It fires a tap event when tapping successfully completes on an component`

**7. Environment details**

Chrome 86
framer-motion 2.9.1

**Comment by colepeters** [comment]
I'm also seeing this on v3.2.1, for what it's worth. Unfortunately this is blocking me from implementing a fairly important feature 😅

**Comment by izorg** [comment]
Works for me on 4.1.3
