### ISSUE TITLE
[BUG] Unrelated state updates cause layout animations to trigger

### ISSUE THREAD

**Issue by alexthebake** [framer/motion#812]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

I'm encountering an issue where unrelated state updates seem to be causing layout animations to trigger. I.e. my parent component has some state that's being used by motion, and some state that is not being used my motion. When I update the state that should have no effect on motion elements, it appears to trigger the initial layout animation. In my case this causes a weird "jumpy" behavior when the unrelated state is updated.

This may also be related to https://github.com/framer/motion/issues/807

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/jolly-brahmagupta-11lz2?file=/src/App.js

**4. Steps to reproduce**

1. Go to code sandbox linked above
2. Click the button labeled "unrelated"
3. Observe 'jumpy' behavior / layout animation being incorrectly triggered

**5. Expected behavior**

I would expect that unrelated updates would have no effect on framer motion elements that do not depend on that state.

**6. Video or screenshots**

<a href="https://www.loom.com/share/037b77b897bb48db93ddf4ae7c1edebd"> <p>Screen capture of problem</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/037b77b897bb48db93ddf4ae7c1edebd-with-play.gif"> </a>

**7. Environment details**

 Chrome 85, macOS

**Comment by ttillberg** [comment]
confirming it's the same as  #807

**Comment by alexthebake** [comment]
I'm not sure if this helps, but I tried removing all `rotate` animations (i.e. just comment out any lines that have `rotate` in the codesandbox linked above), and that made it stop "jumping" whenever I click on the "Unrelated" button. Obviously this is not ideal (I'd like to be able to fan out the cards in my example), but perhaps it's a clue.

**Comment by mattgperry** [comment]
Rotate isn't compatible with layout animations (I believe this is in the docs) so this could be part of it. Got a PR for the other issue now

**Comment by alexthebake** [comment]
@mattgperry awesome, thanks for the update! Can confirm it's in the docs: "API > Animation"

> rotate and skew transforms are not currently compatible with layout animations.

Hopefully that means they may eventually be supported? For now I'm going to try putting a `motion` component _without_ the `layout` prop inside of a `motion` component _with_ the `layout` prop, and see if that allows me to achieve what I'm looking for.

As for the other issue (#807), I'm hoping your PR does the trick! I'll post an updated sandbox in here if I manage to succeed in getting things to render how I like.

**Comment by alexthebake** [comment]
Here's a code sandbox where I:
> try putting a motion component without the layout prop inside of a motion component with the layout prop, and see if that allows me to achieve what I'm looking for.

https://codesandbox.io/s/wispy-bush-fudtp?file=/src/App.js

It works pretty well! Some improvements could be made for sure, but at least "unrelated state updates" don't cause the "jumpiness" I was experiencing.

**Comment by mattgperry** [comment]
There is some support inside Framer so it is possible. It takes an extra DOM read/write cycle so its less great for performance although in your instance you wouldn't notice.

**Comment by mattgperry** [comment]
Closing this as now you can pass an element `layoutDependency`, so layout animations will only trigger when this value changes.
