### ISSUE TITLE
[FEATURE] Exposing animation controls globablly to offset the animation duty from component-level to a higher order entity.

### ISSUE THREAD

**Issue by ghost** [framer/motion#813]
**Is your feature request related to a problem? Please describe.**
Framer is cool. But it currently, afaik, doesn't have a system in place to expose controls of a component so that they can be used from the outside. This is frustrating because instead of having a central system that deals with animating components on its own, leaving components alone, you have to bake everything inside a component **and you can't clearly tell who animated what and why.** A system like Redux' where you could clearly see what actions were dispatched, when and why is much more beneficial.

**Describe the solution you'd like**

1. A component could be decorated with a `withVariants` hook. When this is set in motion, the component will create controls and pass them along to the central store. A `withVariants` hook contains an unique ID and any number of variables passed from the component.
2. The central store ingests this object and stores it under its key so that it can later identify it.
3. **However** each `withVariants` hook works with a callback:
```js
export const variantsCallback = (
	‘variants/that/compB/caresAbout’,
	controls,	
	...args
) => {
	if(args.isMinimized) {
		//Animate using Component B’s
		//controls
	}
}
```
The `args` are items passed from the component level, the `controls` are passed from the component level and the name is just what this "variant callback" is called.
4. Presumably, most of your `args` will be `selectors`. When there is a change in them, the `if` statement from inside our `variantsCallback` gets analyzed and if all conditions are met, an animation is started.

**Describe alternatives you've considered**
None. I haven't seen anything like this.

**Additional context**
Here is the full code of what it could potentially look like:
```js
//ComponentA.js
//Dispatches a simple action.
dispatch(
	setMinimized(true)
);

//ComponentB.js
//Cares about the `setMinimized` action, for which we have a selector.
const isMinimized = useSelector(getMinimized);


//Says that it cares about 'variants/that/compB/caresAbout', automatically creates some controls and then also
// passes the variables it cares about to the callback.
const animate = withVariants(
	’variants/that/compB/caresAbout’,
	//Everything from now on is passed to the store, which does its own thing.
	isMinimized
);

return(
	<motion.div
		animate={animate}
	>
	</motion.div>
);

//variants.js
//We're declaring our variants callback. Every time something happens in ComponentB.js, or really anywhere outside that
//make the if statement pass, then ComponentB will animate.
export const variantsCallback = (
	‘variants/that/compB/caresAbout’,
	controls,	
	...args
) => {
	if(args.isMinimized) {
		//Animate using Component B’s
		//controls
	}
}

```
And now we're able to control animations from the outside of the component itself! This way is a bit more opinionated, but anything along the lines of exposing (and being able to identify) a set of controls that, based on that unique ID you know correlates to a certain component will do.

The only missing link here is the store itself. **With who do we register `variantsCallback`?**, right now it's just a default export. This needs to be put inside the store so that the store itself could constantly re-evaluate if animations should happen or not.

An added benefit is that **you can chain components' animations** as you normally would with a timeline.

Please consider. A component shouldn't always care about the animations it has to do. It just has to be animated in some way.

**Comment by mattgperry** [comment]
Thanks for the detailed writeup. I can imagine some more global controls at some point and will keep these ideas in mind!
