### ISSUE TITLE
[BUG] Svg rectangle transform not working.

### ISSUE THREAD

**Issue by mikkmartin** [framer/motion#816]
Rect transform not working on framer-motion v2.0+

https://codesandbox.io/s/eloquent-moon-vrewh?file=/src/App.tsx

Video demonstration:
https://www.youtube.com/watch?v=QfH_0LN6oEM

Hovering the rectangle element should scale up but doesn't.

**Comment by jedierikb** [comment]
FWIW, scaling works with a plain div.
https://codesandbox.io/s/quizzical-gauss-h6the
