### ISSUE TITLE
[BUG] App Drawer doc example is using V1

### ISSUE THREAD

**Issue by glekner** [framer/motion#817]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**
While reading https://www.framer.com/api/motion/examples/
I noticed The App Drawer example is using V 1.6.0
Is the team going to update those docs?

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/app-store-ui-using-react-and-framer-motion-ecgc2

**4. Steps to reproduce**
https://www.framer.com/api/motion/examples/

**5. Expected behavior**
The example should use V2

**Comment by PTaylour** [comment]
I'm not sure how the the deployment is set up for codesandbox but this one is uses the latest release:

https://codesandbox.io/s/app-store-ui-using-react-and-framer-motion-jnqfv

**Comment by glekner** [comment]
nice, well its really not consistent through out the docs, maybe its better to clean up some reference links
