### ISSUE TITLE
[BUG] 2.9.0 Exit/Enter animation dramatically slowed down.

### ISSUE THREAD

**Issue by ymoon715** [framer/motion#819]
**1. Describe the bug**
https://codesandbox.io/s/framer-motion-image-gallery-pqvx3?fontsize=14&module=%2Fsrc%2FExample.tsx
I was using a component such as the provided example above, but when I upgraded to version 2.9, the animation greatly slowed down.

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/framer-motion-image-gallery-forked-wjxcn?file=/src/Example.tsx

**3. Steps to reproduce**

1. Go to https://codesandbox.io/s/framer-motion-image-gallery-pqvx3?fontsize=14&module=%2Fsrc%2FExample.tsx
2. Change the version of framer-motion to the latest (or click the link in reproduced bug step above)
3. test out the animations.

**4. Expected behavior**

Animation should be similar to version 1, or anything before 2.3. I was using 2.3 prior to the upgrade to 2.9

**Comment by mattgperry** [comment]
I'll update the original example but this isn't a bug, we've since fixed the animation of overdamped springs (which this is with a stiffness: 300 and damping: 200)
