### ISSUE TITLE
[BUG] AnimatePresence does not unmount children

### ISSUE THREAD

**Issue by zawupf** [framer/motion#820]
The children if an `AnimatePresence` component are not unmounted on exit, when there is a deeply nested `motion.div` that uses `variants`. If the nested `motion.div` uses objects for `initial/animate/exit` props, it works.

This bug affects version 2.9.0, older versions work.

See: https://codesandbox.io/s/framer-motion-nested-animate-presence-bug-k5gpq

**Comment by kirkobyte** [comment]
`AnimatePresence` also doesn't seem to trigger the `onExitComplete` callback if passed one since 2.9.0

**Comment by mattgperry** [comment]
This is fixed in `2.9.2`, thanks for the report and clear example!

**Comment by jscheel** [comment]
I'm experiencing this on 3.1.1 as well.

**Comment by The-dev-Sirmed** [comment]
I am expiriencing it on 4.1.17 as well
