### ISSUE TITLE
Remove inline translateZ etc on transition end

### ISSUE THREAD

**Issue by tommhuth** [framer/motion#823]
When the transition ends, how can I remove the inline style completely (_not_ set it to `0`)?  Even `translateZ(0)` causes side effect I really don't want (like position fixed not working on children)

**Comment by rayventerprise** [comment]
Having the same issue, 

[https://imgur.com/FFJNNJb](url)

**Comment by rayventerprise** [comment]
Just learned the workaround.

- In your variants, don't use any vw/vh props as that will cause the trailing transform.

`
 pageInitial: {
            opacity: 0,
            x: '100vw', // bad, vw will cause trailing inline style
          }
`

- You can fix the trailing opacity at the moment by explicitly setting opacity to 1 at the end of transition. 
`
  pageIn: {
            opacity: 1,
            x: 0,
            transitionEnd: { // temp workaround to fix trailing opacity
              opacity: 1,
            },
          },
`

**Comment by Tam** [comment]
I've temporarily worked around this by removing the style attribute [on animation complete](https://www.framer.com/api/motion/component/#visualelementlifecycles.onanimationcomplete):

```js
const onAnimationComplete = () => {
    requestAnimationFrame(() => {
        const drawer = document.querySelector(`.${css.drawer}`);
        if (drawer) drawer.removeAttribute('style');
    });
};
```

(You should probably use a ref to the element instead of a querySelector, which was needed in my case)

**Comment by mattgperry** [comment]
I don't think this is something we're going to add explicit support for in the near future so setting it manually on the element on animation complete is the only way to do this

**Comment by isc30** [comment]
I think documentation around this is necessary, I was having issue with `position: fixed` not working properly because a parent had a dangling `transform: translateX(0px)` when it should've been `transform: none`

**Comment by isc30** [comment]
```tsx
transitionEnd: {
  // temp workaround to fix trailing styles
  // https://github.com/framer/motion/issues/823
  transform: 'none',
  // color: 'unset'
  // opacity: 0
},
```

**Comment by LennardWesterveld** [comment]
> ```tsx
> transitionEnd: {
>   // temp workaround to fix trailing styles
>   // https://github.com/framer/motion/issues/823
>   transform: 'none',
>   // color: 'unset'
>   // opacity: 0
> },
> ```

Tried this as well, works for the in-animation but the exit-animation doesn't work anymore.
@isc30 how did you solve this? with variants?

**Comment by Noitidart** [comment]
Did you have to put x and y into transitionEnd @LennardWesterveld? I don't know why, but in one case, I can just use `x: 0` without `transitionEnd` and it works fine (children can use position fixed).
