### ISSUE TITLE
[BUG] (fix included) Child of AnimationPresence isn't always a PresenceChild, causing element to be rerendered

### ISSUE THREAD

**Issue by paales** [framer/motion#825]
**1. Read the [FAQs](#faqs) 👇**

✅

**2. Describe the bug**

Child of `<AnimationPresence>` isn't always a `PresenceChild`, causing element to be rerendered/

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

So I've tried to recreate the issue in the sandbox, but can't seem to reproduce it in the sandbox. But I've found a solution that works for us.

**4. Steps to reproduce**

See video

**5. Expected behavior**

I'd expect it to always have the PresenceChild. If it has a PresenceChild it wont suddenly rerender when it isn't necessary..

**6. Video or screenshots**

Video explaining the issue: https://d.pr/v/s4QwMs

**7. Environment details**

Latest framer motion version + nextjs

**8. Solution**

Change
https://github.com/framer/motion/blob/b414798092c857f3184ee0ccd239e7adf1340172/src/components/AnimatePresence/index.tsx#L248-L263

To
```tsx
    // Add `MotionContext` even to children that don't need it to ensure we're rendering
    // the same tree between renders
    childrenToRender = childrenToRender.map((child) => {
        const key = child.key as string | number
        return child.type === PresenceChild ? (
            child
        ) : (
            <PresenceChild
                key={getChildKey(child)}
                isPresent
                presenceAffectsLayout={presenceAffectsLayout}
            >
                {child}
            </PresenceChild>
        )
    })
```

So I'm 'just' checking if the child is an PresenceChild and if it isn't, wrap it.

I'm not sure what effect this might have on other parts of the library, but it seems to be working (as far as I can actually properly test this)

**Comment by paales** [comment]
Encountered an issue where onExit is triggered multiple times. This might be the cause of the issue: https://github.com/framer/motion/blob/b414798092c857f3184ee0ccd239e7adf1340172/src/components/AnimatePresence/index.tsx#L223

If I add a check`if(removeIndex > -1)` it seems to be working

**Comment by mattgperry** [comment]
Feel free to reopen with a sandbox
