### ISSUE TITLE
[BUG] AnimatePresence exit animation conflicts with whileHover

### ISSUE THREAD

**Issue by lintonye** [framer/motion#827]
Exit animation doesn't work if the same property exists in `whileHover`

CodeSandbox: https://codesandbox.io/s/tender-mendel-bqb72?file=/src/App.js

** Steps to reproduce**

1. Click any card, the expected animation is that the card will "fly out" from the deck
2. Now uncomment the line with "BUG"
3. Refresh the preview and click a card again

** Expected behavior**

The card should still fly out, i.e. its `y` should be animated

** Actual behavior **

The card no longer moves in the `y` direction.

** Environment details**

framer-motion 2.9.4

**Comment by mattgperry** [comment]
This has been fixed in the meantime
