### ISSUE TITLE
[BUG] Cumulative drag & useSpring is broken since v2

### ISSUE THREAD

**Issue by mrgnou** [framer/motion#829]
**2. Describe the bug**

Since version 2, it seems impossible to cumulate useSpring & drag. This feature is commonly used to benefit from drag, and programmatically set the spring value by clicking a button, for instance.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[Working example with v1.9.0](https://codesandbox.io/s/updating-usespringvalue-on-drag-forked-i744v?file=/src/index.js)
[Broken example with v2.9.4](https://codesandbox.io/s/updating-usespringvalue-on-drag-forked-hvzx0?file=/src/index.js)

**4. Steps to reproduce**

1. open the sandbox example
2. drag & drop the pink square

**5. Expected behavior**

The pink square should follow the mouse while dragging with a spring animation, and should come back to its initial position on drag end.

**7. Environment details**

Chrome desktop

**Comment by glottonous** [comment]
https://github.com/framer/motion/pull/799#issuecomment-716939854

I solved the issue with this, but you're right, this is a bug.

**Comment by mattgperry** [comment]
Thanks for the report, sorry for the delay in fixing. This is now fixed in `3.9.1`.
