### ISSUE TITLE
`whileFocus` gesture

### ISSUE THREAD

**Issue by stuartflanagan** [framer/motion#836]
**Is your feature request related to a problem? Please describe.**
Kind of. A lot of designs I see have focus states similar to hover states. There is no focus gesture so we need to fallback to a non animated variant for focus. Or add more react state to handle focus if we want to reuse say a `whileHover` state animation

**Describe the solution you'd like**
A gesture `whileFocus` to be added to the possible gestures

**Describe alternatives you've considered**
CSS fallbacks. A lot of the time results in us not using motion for hover states so we can replicate them for focus states.

**Comment by stuartflanagan** [comment]
👋

**Comment by dahannes** [comment]
I would also love to see this feature along with `whileDisabled`

**Comment by oielbanna** [comment]
Is anyone working on this? I've been needing this feature for a while now so Im down to work on it

**Comment by dahannes** [comment]
@oielbanna I had some time to look into this today. Please see the above MR. 
1. `whileFocus` is pretty straight forward and works just fine
2. `whileDisable` has been implemented via MutationObserver to listen for changes of the disabled attribute.
It also works fine, but I did not manage to test this correctly, because `VisualElement.element` is undefined when run in tests.

FYI: @mattgperry

**Comment by oielbanna** [comment]
@dahannes
I contacted Matt and he said I should go for it so I worked on whileFocus as well. I'm almost done, only missing the docs and examples. 
Did you branch off master? I think your PR might not be up to date with the latest changes. Would you like to work on this together?

**Comment by oielbanna** [comment]
One thing I was thinking about while working on this is we could add a console.warn when users try to use this with elements that cant get focus or other related rules. For example <a> cant receive focus if it doesnt have href.

**Comment by oielbanna** [comment]
@stuartflanagan https://github.com/framer/motion/pull/894 closes this feature request!

**Comment by stuartflanagan** [comment]
Thanks a heap for this it will reduce a lot of duplication!

**Comment by stuartflanagan** [comment]
Thank you for implementing this @oielbanna

**Comment by oielbanna** [comment]
@stuartflanagan my pleasure :)
