### ISSUE TITLE
[BUG] Initial position when using drag fails

### ISSUE THREAD

**Issue by arelaxend** [framer/motion#837]
Dear Framer team,

**2. Describe the bug**
When you use drag, and motionValue, the initial position fails (transform:none instead of something)

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Just look at your example with the latest version released.

https://codesandbox.io/s/framer-motion-path-drawing-drag-and-usetransform-forked-9dl5g?fontsize=14&hidenavigation=1&theme=dark

**5. Expected behavior**

In the codesandbox example, tranform: none make the initial position of the check icon wrong. We would like this icon to have correct position.

In image currently we have this:

![Capture d’écran 2020-11-04 à 11 52 34](https://user-images.githubusercontent.com/8854658/98102765-4bc31000-1e94-11eb-8947-a2fe0f4892e3.png)

And we would like

![Capture d’écran 2020-11-04 à 11 52 40](https://user-images.githubusercontent.com/8854658/98102786-51b8f100-1e94-11eb-8157-25713da6892b.png)

**7. Environment details**

Mac os latest version of Chrome.

Best

**Comment by mattgperry** [comment]
Seems to be fixed in latest
