### ISSUE TITLE
[BUG] Element not appearing after animation in Safari browser.

### ISSUE THREAD

**Issue by acolytec3** [framer/motion#838]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

I have a `<motion.div>` that is supposed to render a child component with `translate` and it works great Chrome but not at all in Safari.  In Safari, I can see that the child is getting inserted into the DOM in the dev tools but 9 out of 10 times it does not appear in the browser.  
**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/cocky-silence-puhp8?file=/src/Speeddial.tsx - 

**4. Steps to reproduce**
1) Open code sandbox in Safari
2) Click on plus
3) 9 times out of 10, no "Open Wallet" Icon button is rendered above the + icon

**5. Expected behavior**

Open the same codesandbox in Chrome or Brave and follow the steps to see expected behavior.

**6. Video or screenshots**

See codesandbox

**7. Environment details**

Issue occurs on Safari on both MacOS and iOS.  Reproduced in iOS 14, MacOS Catalina, and Big Spur in default Safari installation

**Comment by Gerigot** [comment]
Can I ask you why are you using a ref in the example? unfortunately I don't have a Mac so I can't test the strange behaviour, but maybe it's not the component itself but something other.

**Comment by acolytec3** [comment]
The ref is being used by a listener function to trigger a component state
update when a "mousedown" event is detected outside of the boundaries of
the component.  I'll try stripping that from the component and see if it
has any impact on the Safari issue.

**Comment by Gerigot** [comment]
Thank you for the answer I've deleted the comment because I've understood what it was used for.
Did you try to upgrade to the version v1 of the chakra ui?
https://chakra-ui.com/docs/migration

**Comment by mattgperry** [comment]
I'm closing this now but could you reopen with the latest versions of Chakra and Framer Motion? Thanks
