### ISSUE TITLE
[FEATURE] Web Animations API support

### ISSUE THREAD

**Issue by pie6k** [framer/motion#841]
I was wondering if are there any plans to add support for [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API) to Framer Motion.

Seems support is already quite good (https://caniuse.com/web-animation) and maybe potential performance gains could be significant, especially for lower-end devices?

**Comment by mattgperry** [comment]
No there's currently no plans for this. WAAPI has a number of limitations, including but not limited to:

- Blackboxed values (no way of extracting velocity or using useTransform)
- No spring/decay animations without precalculating frames (would require Popmotion import anyway)
- Limited to animating styles
- Non-trivial to support animation of individual transforms
