### ISSUE TITLE
[BUG] Can't install with latest version of React 17.0.1

### ISSUE THREAD

**Issue by joshbedo** [framer/motion#846]
Trying to install framer motion with React 17.0.1 and can't. Tried using force command but still won't install because of dependency issues. Does this not work with the latest version of React? Doesn't seem like they changed anything just performance updates.

<img width="574" alt="Screen Shot 2020-11-15 at 6 32 08 PM" src="https://user-images.githubusercontent.com/607239/99200016-f084fd80-2770-11eb-9d45-bba65d2e5fbf.png">

**Comment by Gerigot** [comment]
I think the propblem here is that in the peerDependencies the react version is written lik this ^16.8, that will not take the 17th or bigger in consideration.
I'll make a PR to correct this

**Comment by Amasa-Delano** [comment]
It would be cool to get a new release of the package with this fix in it.

**Comment by hafffe** [comment]
@mattgperry any reason why 2.9.5 isn't released to npm yet?

**Comment by mattgperry** [comment]
Apologises for the delay, just publishing this now
