### ISSUE TITLE
Is there a Codesandbox for this example?

### ISSUE THREAD

**Issue by danboyle8637** [framer/motion#852]
https://www.framer.com/motion/

Under the Headline... Animations that Work Like Magic...

There is an Animate Shared Layout example. Does this example have a full Codesandbox? I would really like to learn more about how this component works with some full code.

Thanks!

**Comment by jshikanova** [comment]
[1](https://codesandbox.io/s/framer-motion-2-animating-shared-layouts-1cpd0)
[2](https://codesandbox.io/s/framer-motion-2-animatesharedlayout-animate-between-different-components-dy0bv)

[other framer-motion sandboxes](https://codesandbox.io/search?refinementList%5Btemplate%5D%5B0%5D=create-react-app&refinementList%5Bnpm_dependencies.dependency%5D%5B0%5D=framer-motion&page=1&configure%5BhitsPerPage%5D=12)
