### ISSUE TITLE
[FEATURE] Initiating animations only when the element is visible in the DOM.

### ISSUE THREAD

**Issue by lavandalabs** [framer/motion#854]
First off, your animation library is beyond the beyond. You don't add the overhead that other libraries do, and you make it surprisingly easy to make React sites interactive. You guys are amazing.

The only thing I'd like to mention: I find it difficult to activate animations when the element is visible. For elements above the fold, animations work flawlessly. However, I find that animations below the fold are animated immediately--not allowing the user to see them.

I've tried a few "visibility" libraries like "react-visibility-sensor," but I've found a large reduction in performance.

I think it'd be quite a huge thing to automatically initiate the animation only when the element (or a small part of it) has been scrolled into view. It seems the large overhead required to enable viewed-animation somewhat offsets the simplistic nature of your API.

It seems your scroll-based API is relative to the element, as I have an element 10,000px down the screen which works just as good as if it were at the top.

I asked on your Discord for solutions for this problem, and I was provided a hardly helpful "maybe add a reasonable delay?" Which is a very short-term and non-working solution.

If I'm mistaken and your API offers this out of the box, I apologize for clouding your issues.

All the same, I think this would be an excellent feature to consider. Thanks so much for your time and for your API!

**Comment by paales** [comment]
https://www.smashingmagazine.com/2020/10/introduction-to-framer-motion/ -> CMD+F 'useInView' should give you a solution
