### ISSUE TITLE
[BUG] using "useDragControls" to "snapToCursor" does not respect the element's drag axis

### ISSUE THREAD

**Issue by lesleykhuu-mp** [framer/motion#855]
**2. Describe the bug**
The useDragControls' snapToCursor flag should allow the targeted element to immediately move to the cursor.  Prior to framer-motion@2.4.0, the element would be positioned correctly on the specified drag axis. Post framer-motion@2.4.0, the element snaps to the cursor correctly, but the element's locked axis is not respected. 

For example, if the element has a drag="x", the element should only be able to move on the "x" axis. The issue here is that the element's "y" axis is also updated when snapToCursor is enabled.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
https://codesandbox.io/s/framer-motion-usedragcontrols-forked-mv8qs?file=/src/App.js

**4. Steps to reproduce**
1. Go to https://codesandbox.io/s/framer-motion-usedragcontrols-forked-mv8qs?file=/src/App.js
2. Click just above the progress bar 
3. Button snaps to the cursor, but the button's "y" axis is also updated.

**5. Expected behavior**
The button should snap to the cursor based on the "x" axis. The "y" axis should remain unchanged.

**6. Video or screenshots**
Initial state:
![image](https://user-images.githubusercontent.com/50591758/99328671-6fda0600-2831-11eb-9a17-793dd76060a3.png)

After clicking just above the progress bar:
![image](https://user-images.githubusercontent.com/50591758/99328687-7a949b00-2831-11eb-82f4-cf55035e79a7.png)

**7. Environment details**
Issue was introduced framer-motion@^2.4.0
Issue occurs on Chrome and Safari.

Providing the code JS code block from the codesandbox
```
export default function App() {
  const handleX = useMotionValue(0);
  const progressScaleX = useTransform(handleX, [0, 300], [0, 1]);
  const dragControls = useDragControls();

  return (
    <div
      className="slider-container"
      onMouseDown={(e) => dragControls.start(e, { snapToCursor: true })}
    >
      <div className="bar">
        <motion.div className="progress" style={{ scaleX: progressScaleX }} />
      </div>
      <motion.div
        className="handle"
        drag="x"
        dragMomentum={false}
        dragElastic={0}
        dragConstraints={{ left: 0, right: 300 }}
        dragControls={dragControls}
        style={{ x: handleX }}
      />
    </div>
  );
}

```

**Comment by Weffe** [comment]
I just noticed this bug too in my own component that was using `dragControls` with `snapToCursor: true`.

**Comment by AmazingTurtle** [comment]
I found another weired issue that might relates to this.

snapToCursor does snap correctly in my case, but when I drag it from there, it resets to 0, like if I was dragging from all the way from the left. See https://codesandbox.io/s/framer-motion-usedragcontrols-forked-d6t9r

**Comment by RickyTickyTavy69** [comment]
@AmazingTurtle 

may I ask you if you found a solution for this issue? I am currently facing the same issue with my swiper using framer motion.
Every time I swipe it moves the swiper to the first element, like in your codesandbox too.
