### ISSUE TITLE
Animate not working now what?

### ISSUE THREAD

**Issue by developdeez** [framer/motion#856]
Hi I saw the tutorial on youtube shared below. It seems he was using some sort of beta since "animate" by itself doesnt work.

If it is, it's broken in latest build

https://codesandbox.io/s/framer-motion-animatesharedlayout-menu-underline-demo-jwkvp

**Comment by mattgperry** [comment]
`layout` ended up being used for automatic layout animations. For all other animations they should still be explicitly defined in `animate`
