### ISSUE TITLE
[BUG] AnimateShared Layout Won't Transform Height of Shared Component

### ISSUE THREAD

**Issue by vinicius507** [framer/motion#858]
I'm building a website using Next.js and Framer-motion, and I'm trying to animate layout between two different pages.

My page template has a container shared between two pages(homepage and default). It looks like this:

```
import { AnimateSharedLayout, motion } from 'framer-motion'
import styles from './layoutHome.module.css'

export default function LayoutHome({ children }) {
    return (
        <AnimateSharedLayout>
              <motion.div layout className={styles.container layoutID="container">
                     <main>{children}</main>
        </AnimateSharedLayout>
    )
}
```
The problem is, if I click a link in the Homepage(which updates `{children}`), the container won't animate to the new height(which is the expected behavior) in another page, it runs exit animation and enter animation.

**Comment by paales** [comment]
`AnimateSharedLayout` should always remain present, so it should be in your `_app.tsx`.

**Comment by vinicius507** [comment]
> `AnimateSharedLayout` should always remain present, so it should be in your `_app.tsx`.

You, sir, saved me. Gonna leave a more detailed answer should someone run into the same issue:
Not only do you need `AnimateSharedLayout` in `_app.tsx` or `_app.js`, you also need `{children}` motion components to be declared as child of the parent element. 
Kind of a noob mistake here. Thanks you for your help :)
