### ISSUE TITLE
[BUG?] Exit animation not working in a nested `ul`s layout

### ISSUE THREAD

**Issue by armandocin** [framer/motion#859]
**2. Describe the bug**

In nested `ul` that uses `layout` and `AnimatePresence` the variant animation that should trigger when element is removed from list, is not triggered and the animation is not executed. More specifically it is triggered only when the parent `ul` is also removed.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-2-animating-shared-layouts-forked-oplj5

**4. Steps to reproduce**

1. Click on a couple element in the side menu in order to add it to a new FAVORITES category (add more than 1)
2. click on one element in the FAVORITE category and the `li` will be removed from the list. The animation is not executed

Also:
3. Leave just 1 element in the FAVORITES list
4. Click on the only element to remove the entire category
5. In this case the animation on the `li` is executed (moves to the left)

**5. Expected behavior**

When removing an element from the FAVORITES category it should animate and slide to the left before exit.

**6. Video or screenshots**

https://share.getcloudapp.com/NQuKL4Rd

**Comment by paales** [comment]
AnimatePresence only works on _direct_ children, not on nested children.

So you have a few options:
- Wrap each .map AnimatePresence and make it work like that.
- Flatten the HTML so it doesn't need any nested html

**Comment by armandocin** [comment]
@paales Thanks for the reply

I thought about that but nesting the inner .map with AnimatePresence fix the out animation of the `li` elements when there are more than 1, but breaks the animation of the last `li` (doesn't animate when also the category is removed).

Basically this change makes swap the list I made in the description:

Steps to reproduce the behavior (after wrapped second .map with AnimatePresence):

3. Leave just 1 element in the FAVORITES list
4. Click on the only element to remove the entire category
5. In this case the animation on the li is **NOT** executed

Also (see animation that should work):

1. Click on a couple element in the side menu in order to add it to a new FAVORITES category (add more than 1)
2. click on one element in the FAVORITE category and the li will be removed from the list. The animation **IS** executed

About flatten the HTML, it could be worth trying. But having a data structure that is an array of object, each which has an array of items to show, suggests the use of 2 maps in React and this should be the way to render this structure.

Thanks again for the help and let me know if you have another idea.

**Comment by mattgperry** [comment]
@paales is correct in that this isn't technically a bug with `AnimatePresence`, the last exit works because the root component is being removed and isn't expected to work otherwise. 

[This ticket](https://github.com/framer/motion/issues/746) would help fix this as you could also wrap the items list with their own `AnimatePresence`
