### ISSUE TITLE
[BUG] Types for options and controls for the animate function should be exported

### ISSUE THREAD

**Issue by IgnusG** [framer/motion#860]
**1. Read the [FAQs](#faqs) 👇**
✔️ 

**2. Describe the bug**
The new `animate` function is really helpful! (Finally we don't have to result to falling back to popmotion's utility)

The only problem I found so far is that the options (`AnimateOptions`) and return value (`PlaybackControls`) are not exported along with it. Would be nice if they were to create and manage our own hooks/helpers using `animate`.

**5. Expected behavior**
[`PlaybackControls`](https://github.com/framer/motion/blob/main/src/animation/animate.ts#L6) and [`AnimateOptions`](https://github.com/framer/motion/blob/main/src/animation/animate.ts#L18) are exported from `framer-motion`

**Comment by mattgperry** [comment]
Fixed in `3.9.3`. FYI `PlaybackControls` is now `AnimationPlaybackControls`. Will be published within 10 min
