### ISSUE TITLE
[BUG] SVG briefly appearing on render when it shouldn't based on motion value and variant

### ISSUE THREAD

**Issue by MaximeHeckel** [framer/motion#862]
**1. Read the [FAQs](#faqs) 👇**
✅ 
**2. Describe the bug**

Hi 👋 I just upgraded from Motion 1.x to 2.x on one of my repo and noticed that one of my SVGs which can be in 2 different state `checked` (shows the sun icon) or `uncheck` (shows the moon icon) sometimes renders both state overlapping for 1 or 2 frames before going to the expected state. It does not happen consistently, only some times, and I really need to repeat several refreshes in order to reproduce the issue

It only happens upon re-rendering the website. I first thought it was due to some race condition on my end, but no, I can reproduce the issue very easily. See CodeSandbox below for a minimal reproduction.

Maybe I'm doing something wrong as well, and I'm misusing `useMotionValue` and `useTransform` but from what I;m seeing, these are still set properly.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

See the following code sandbox for a minimal reproduction: https://codesandbox.io/s/frosty-dream-jkkmd?file=/src/App.js

**4. Steps to reproduce**

1. Go to the codesandbox above
2. Refresh the codesandbox browser several times
3. See the moon SVG briefly appearing (it shouldn't as the condition isChecked is set to `false` in the code)

**5. Expected behavior**

I'd expect to consistently get 1 of the 2 SVGs to render based on the value of `isChecked`

**6. Video or screenshots**

![Kapture 2020-11-21 at 13 17 38](https://user-images.githubusercontent.com/2974412/99884444-4be53e80-2bfc-11eb-8956-d1ec8525126e.gif)

You can see in the recording that the moon icon is briefly appearing for like 1 or 2 frames before disappearing expected state

**7. Environment details**

macOS Big Sur
Chrome/Firefox
framer-motion: 2.6.13
react 16.13.0

**Comment by tomdohnal** [comment]
Hi, it seems like you've attached a wrong CodeSandbox link. The one attached is an empty create react app :)

**Comment by MaximeHeckel** [comment]
@tomdohnal oh woops will address that ASAP 😅

**Comment by MaximeHeckel** [comment]
@tomdohnal fixed the link https://codesandbox.io/s/frosty-dream-jkkmd?file=/src/App.js let me know if that works!

**Comment by tomdohnal** [comment]
Yes, it does work. Actually, I was experiencing a similar issue and managed to "fix" it by using the latest 3 rc version of the library. 
Maybe the fix can be backported to v2? @mattgperry

**Comment by MaximeHeckel** [comment]
ha! That's awesome news 🎉 
Having it backported would be great, but since it's not the biggest issue in the world I'm ok waiting a little bit for a stable release of Framer Motion v3

**Comment by jedierikb** [comment]
Upgrading to 3-rc fixed a flashing issue for me too... (happy to provide details if requested)

Thank you!  

Is there a changelog/roadmap/ for v3 so I know what else to look out for going up a version?

**Comment by tomdohnal** [comment]
I only found this pull request https://github.com/framer/motion/pull/857

**Comment by jedierikb** [comment]
Alas, my momentary flash issue persists on v3.  Moved issue over to https://github.com/framer/motion/issues/882

**Comment by mattgperry** [comment]
Can't reproduce in 6
