### ISSUE TITLE
Alternative to react-spring's 'useSpring' hook in Framer Motion

### ISSUE THREAD

**Issue by RectoVersoDev** [framer/motion#867]
Hello,

I'm trying to follow the last Joshua Comeau's tutorial 'Boop!' : https://www.joshwcomeau.com/react/boop/

He used react-spring library.

For the **#springs-to-the-rescue** part I found a workaround :

I remove this : 

```
const style = useSpring({
  display: 'inline-block',
  transform: isBooped ? `rotate(${rotation}deg)` : `rotate(0deg)`,
});
```

```
<animated.span onMouseEnter={trigger} style={style}>
  {children}
</animated.span>
```

And do this : 

```
<motion.span
  onMouseEnter={trigger}
  style={{ display: "inline-block" }}
  animate={{
    x: isBooped ? x : 0,
    y: isBooped ? y : 0,
    rotate: isBooped ? rotation : 0,
    scale: isBooped ? scale : 1,
    transition: {
       type: "spring",
       stiffness: 300,
    }
   }}
>
    {children}
</motion.span>
```

But now I'm stuck in the hook part (**#disconnected-boops**)

I couldn't find an alternative to the react-spring's 'useSpring' hook in Framer Motion.

Is there a way to achieve this with Framer Motion?

**Comment by mattgperry** [comment]
I don't have much time to look at this in detail at the moment but from what I read it looks like this can be achieved with variants?

```jsx
<motion.button initial={false} animate="rest" whileHover="boop">
  <motion.div variants={{ boop: { y: 100 }, rest: { y: 0 } }} />
</motion.button>
```

**Comment by RectoVersoDev** [comment]
Thank you for your answer !

It could work but the effect will not be the same, the div will move on hover but stay at its position until the user stops the hover.

Also, I don't know if it will work with the 'useBoop' (hook) approach of the tutorial.

**Comment by RectoVersoDev** [comment]
You were right, we can do this with variants 🔥

I replace the react-spring's 'useSpring' hook by this : 

```
const variants = {
   boop: {
      rotate: rotation,
      scale: scale,
      transition: transitionConfig,
   },
   rest: {
      rotate: 0,
      scale: 1,
   },
}
```

And then the component using the hook looks like this : 

```
const Boop = () => {
  const [isBooped, variants, trigger] = useBoop({ rotation: 25 })

  return (
    <motion.button onMouseEnter={trigger} animate={isBooped ? 'boop' : 'rest'}>
      Button text
      <motion.div variants={variants} />
    </motion.button>
  )
}
```

**Comment by deadcoder0904** [comment]
@RectoVersoDev I'm trying to achieve the same effect using Framer Motion. Can you post your entire code? I am getting an error on `onMouseEnter`:

> Type 'boolean | { boop: { translate: { x: number; y: number; }; rotate: number; scale: number; transition: { tension: number; friction: number; }; }; rest: { rotate: number; scale: number; }; } | (() => void)' is not assignable to type 'MouseEventHandler<HTMLButtonElement> | undefined'.
  Type 'false' is not assignable to type 'MouseEventHandler<HTMLButtonElement> | undefined'.ts(2322)

My code looks like:

# useBoop.ts

```tsx
import React from 'react'

export const useBoop = ({
	x = 0,
	y = 0,
	rotation = 0,
	scale = 1,
	timing = 150,
	transitionConfig = {
		tension: 300,
		friction: 10,
	},
}) => {
	const [isBooped, setIsBooped] = React.useState(false)
	const variants = {
		boop: {
			translate: { x, y },
			rotate: rotation,
			scale: scale,
			transition: transitionConfig,
		},
		rest: {
			rotate: 0,
			scale: 1,
		},
	}
	
	React.useEffect(() => {
		if (!isBooped) return

		const timeoutId = window.setTimeout(() => {
			setIsBooped(false)
		}, timing)

		return () => {
			window.clearTimeout(timeoutId)
		}
	}, [isBooped, timing])

	const trigger = React.useCallback(() => {
		setIsBooped(true)
	}, [])

	return [isBooped, variants, trigger]
}
```

# App.tsx

```tsx
<motion.button
	onMouseEnter={trigger}
	animate={isBooped ? 'boop' : 'rest'}
>
	<Cog />
</motion.button>
```

However, I am unable to make it work :(

**Comment by deadcoder0904** [comment]
The Codesandbox linked above is a close answer. Just need to fix the TypeScript error on variants:

> You are trying to animate translate from "0" to "[object Object]". 0 is not an animatable value - to enable this animation set 0 to a value animatable to [object Object] via the `style` property. 
    in MotionComponent (at framer-motion/​index.tsx:16)
    in Motion (at App.tsx:10)
    in App (at src/​index.tsx:7) 
You are trying to animate translate from "[object Object]" to "0". [object Object] is not an animatable value - to enable this animation set [object Object] to a value animatable to 0 via the `style` property. 
    in MotionComponent (at framer-motion/​index.tsx:16)
    in Motion (at App.tsx:10)
    in App (at src/​index.tsx:7) 

If anyone knows an answer to it, it would be an amazing help :)

**Comment by mattgperry** [comment]
You could import `Variants` and type `const variants: Variants`.

As for the error, `translate` is being set as an object. It needs to be just x and y: `{ x, y, scale }`, no translate

**Comment by mattgperry** [comment]
Motion also uses `stiffness` and `damping` instead: https://codesandbox.io/s/react-spring-vs-framer-motion-boop-animation-forked-lk236?file=/src/framer-motion/useBoop.tsx:0-933

**Comment by RectoVersoDev** [comment]
@deadcoder0904 I guess you don't need my code anymore, thanks to @mattgperry for the CodeSandbox !

**Comment by deadcoder0904** [comment]
Ah, I wish I checked Github. I solved it with someone's help & was just about to post the answer.

Thank you @mattgperry for the `stiffness` & `damping` tip. I never would've noticed otherwise.

Codesandbox is here → https://codesandbox.io/s/react-spring-vs-framer-motion-boop-animation-did6x

And posting it here in case Codesandbox gets deleted.

# useBoop.ts

```ts
import { Variants } from "framer-motion"
import React from "react"

export const useBoop = ({
	x = 0,
	y = 0,
	rotation = 0,
	scale = 1,
	timing = 150,
	transitionConfig = {
		type: "spring",
		stiffness: 300,
		damping: 10,
	},
}): [boolean, Variants, () => void] => {
	const [isBooped, setIsBooped] = React.useState(false)
	const variants = {
		boop: {
			translateX: x,
			translateY: y,
			rotate: rotation,
			scale: scale,
			transition: transitionConfig,
		},
		rest: {
			rotate: 0,
			scale: 1,
		},
	}
	React.useEffect(() => {
		if (!isBooped) return

		const timeoutId = window.setTimeout(() => {
			setIsBooped(false)
		}, timing)

		return () => {
			window.clearTimeout(timeoutId)
		}
	}, [isBooped, timing])

	const trigger = React.useCallback(() => {
		setIsBooped(true)
	}, [])

	return [isBooped, variants, trigger]
}
```

# App.tsx

```tsx
import React from "react"
import { motion } from "framer-motion"

import { useBoop } from "./useBoop"
import { Cog } from "../Cog"

export const Motion = () => {
	const [isBooped, variants, trigger] = useBoop({
		rotation: 20,
		timing: 150,
	})

	return (
		<>
			<h1 className="text-6xl text-pink-500">Framer Motion</h1>
			<motion.span
				onMouseEnter={trigger}
				animate={isBooped ? "boop" : "rest"}
				variants={variants}
			>
				<Cog className="w-16 h-16" />
			</motion.span>
		</>
	)
}
```
