### ISSUE TITLE
[BUG] animating border-color in firefox throws error

### ISSUE THREAD

**Issue by jakobgoerke** [framer/motion#868]
**1. Read the [FAQs](#faqs) 👇**

yep

**2. Describe the bug**

In Firefox: trying to animate "borderColor" on an element (i tried div & button) throws "Warning: `NaN` is an invalid value for the `border` css style property" 

Chrome works fine.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/hungry-tu-fdpvf

**4. Steps to reproduce**

1. Use Firefox
2. Open Sandbox & hover over the div
3. Border does not change and throws error in console

**5. Expected behavior**

border-color should be properly animateable in firefox

**7. Environment details**

osx mojave 10.14.5
firefox 83.0
firefox developer 84.0b4

**Comment by KirdesMF** [comment]
pretty sure because you need to set the inital `borderColor` in style or via the inital prop

https://codesandbox.io/s/sparkling-wood-1cuhy?file=/src/App.js

Tested in FF and Chrome

**Comment by jakobgoerke** [comment]
thank you very much that worked, i thought its enough to set the border style.
