### ISSUE TITLE
[BUG] Slow/glitchy animation with AnimatePresence

### ISSUE THREAD

**Issue by linuz90** [framer/motion#876]
I've tried multiple times to simulate pagination with `AnimatePresence`, but **only the first animation is right. Subsequent animations are slow and glitchy**.

Here's the CodeSandbox: https://codesandbox.io/s/animatepresence-issue-7qm2v?file=/src/App.js

I've tried to simplify it, but by using `AnimatePresence` I always end up having slower/glitchier animation compared to using the `motion` component outside of `AnimatePresence`.

**Comment by linuz90** [comment]
Just tried `framer-motion` 3 with CodeSandbox and the issue is done, so I guess it was indeed a bug and it's solved? Waiting for confirmation.

**Comment by mattgperry** [comment]
I haven’t looked at it specifically but the way 3 touches exit animations
is by treating them exactly like whileHover etc. That is to say in a
prioritisation system that it wasn’t previously a part of. So it could be
that other props were interfering with the exit animations whereas now
they’re getting handled differently? I’m not sure but glad to hear this is
resolved for you.

**Comment by linuz90** [comment]
I confirm it seems 100% fixed on framer-motion 3 🎉
