### ISSUE TITLE
[BUG] whileTap and whileHover props do not work as expected on elements inside an iFrame. 

### ISSUE THREAD

**Issue by ssijak** [framer/motion#880]
**2. Describe the bug**

whileTap and whileHover props do not work as expected on elements inside an iFrame. 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[https://codesandbox.io/s/d3rku](https://codesandbox.io/s/d3rku)

**4. Steps to reproduce**

In Chrome and Safari whileHover does not work at all, and whileTap does half of the animation. In Firefox, whileHover works but whileTap does not.

**5. Expected behavior**

whileHover and whileTap work in an iframe

**Comment by mattgperry** [comment]
`whileTap` makes some sense as the `pointerend` is attached to the window, however all the other listeners are attached to the element itself which you'd imagine would work

**Comment by mattgperry** [comment]
I'm closing this out for now as I haven't been able to reproduce on the latest version but also this library that people use for rendering into iframes doesn't seem to work with the latest React. Anyone please feel free to reopen with a modern reproduction.

**Comment by sarat1669** [comment]
@mattgperry , can we reopen this?
https://codesandbox.io/p/sandbox/rnxk2q

Here is the reproduction.

**Comment by isLzg** [comment]
> [@mattgperry](https://github.com/mattgperry) , can we reopen this? https://codesandbox.io/p/sandbox/rnxk2q
> 
> Here is the reproduction.

I’ve encountered the same issue as well.
