### ISSUE TITLE
[FEATURE] Method to immediately set the spring value from `useSpring`, skipping the spring animation

### ISSUE THREAD

**Issue by DanielHZhang** [framer/motion#884]
**Is your feature request related to a problem? Please describe.**

Currently, there is no documented way to immediately set the current value of a `MotionValue` returned by `useSpring`. Calling `.set(value, false)` continues to play the spring animation even if render subscribers are not notified. This results in strange animation when the spring value is updated frequently. 

See: https://codesandbox.io/s/framer-motion-hover-issue-59cd0?file=/src/App.tsx
In this example, setting the spring value in the `onMouseEnter` handler and then setting it again in response to subsequent `onMouseMove` events causes the animation to look janky, as these events fire in quick succession.

**Describe the solution you'd like**

There should be some public API on the `MotionValue` class that allows you to immediately set the current value of the spring while skipping the spring animation. Exposing `.current` and `.prev` as mutable public properties, skipping the animation on `.set(value, false)`, or introducing a new method such as `.immediate(value)` are possible solutions.

**Describe alternatives you've considered**
As far as I know, the only way to do this is to mutate the private property `.current` of the `MotionValue`. This works, but Typescript does not like it.

**Comment by Sirk** [comment]
I agree with @DanielHZhang. This is a missing feature. For example with `react-spring` you can do : 
```javascript
set({ x: 20, immediate: true })
```
which skips the animation, mentionned [in the docs](https://www.react-spring.io/docs/hooks/api).

The only current solution in `framer-motion` I found is similar to what @DanielHZhang mentionned, mutating `current` & `prev` to prevent spring oscillation : 

```javascript
x.current = x.prev = offsetX;
x.set(offsetX);
```

**Comment by mattgperry** [comment]
I assume you'd expect this to stop any current animations if they were running?

**Comment by Sirk** [comment]
> I assume you'd expect this to stop any current animations if they were running?

Yes, it would be like forcing a new value. Can be useful for example to set a position on a mouseenter event and animating it on mousemove.

**Comment by HammadB** [comment]
This would be useful. Is there a preferred API - I'd be happy to take a look at implementation.

**Comment by robksawyer** [comment]
Any movement on this? Or is there a better approach now?

**Comment by arlyon** [comment]
As a concrete usecase, I have an item that I want to be able to move around in response to outside state, while also being able to drag it to a new value. Currently, it all works, except if I drag somwhere else, as soon as I let go, due to how it is implemented, the object snaps back to its spring location before 'springing' over.
