### ISSUE TITLE
[BUG] AnimatePresence doesn't unmount when animation is finished when using a custom bounce transition value

### ISSUE THREAD

**Issue by linusklingzell** [framer/motion#886]
**1. Read the [FAQs](#faqs) 👇**
yes

**2. Describe the bug**

AnimatePresence dosen't unmount its children after exit animation is finished when using a custom bounce value

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/sharp-water-8rh86?file=/src/App.js

**4. Steps to reproduce**

Add a custom bounce value in transition prop in a motion.div component when using AnimatePresence
Click "Toggle me" in sandbox twice to show and then hide the component

**5. Expected behavior**

The children in AnmiatePresence should be unmounted when animation is finished

**Comment by Lukavyi** [comment]
I have a similar issue, had to disable animations because of it.

**Comment by KirdesMF** [comment]
it works if you set the duration of the transition

**Comment by williambout** [comment]
I can repro as well

**Comment by DovahBrownies** [comment]
Can confirm that it will keep bouncing infinitely.
Adding a `duration` does unmount the animation.

**Comment by fatso83** [comment]
Possibly related to #1048.

**Comment by mattgperry** [comment]
Since fixed
