### ISSUE TITLE
[FEATURE] Only allow dragging from a specific child of the draggable parent

### ISSUE THREAD

**Issue by FRMR1** [framer/motion#887]
**Is your feature request related to a problem? Please describe.**
I'm trying to create a draggable div, but instead of being able to drag from the entire div, I only want to be able to drag from a specific child from that div. Imagine an Windows or OSX window which is only draggable from the top section above the menu bar and not from the whole div. I see no way of setting the draggable target of a motion.div to be to a specific child, only the entire div. 

**Describe the solution you'd like**
To be able to explicitly set a drag target, or to have a way where through setting propagation you can the set/stop propagation for children to target a specific element. Also to allow the parent div to be dragged but to set it so it is not the "drag target". 

**Describe alternatives you've considered**
I've tried using DragControls, but this only extends the drag capability outside of the element, and does not provide a way to exclude the element from being draggable.

**Comment by mattgperry** [comment]
You can set `dragListener={false}` if you want to disable that functionality when using dragControls.

**Comment by FRMR1** [comment]
Perhaps that could be included in the docs? I didn't see that option mentioned anywhere and that would have saved me a lot of time. In fact I moved forward with a different library since this seemed to be a missing feature.

**Comment by Davydx7** [comment]
Yes, this 
definitely needs to be added to the docs, implementing a draggable color picker, couldn't easily figure to separate drag even on color pick from dragStart of motion.div parent
