### ISSUE TITLE
[BUG] Dynamic controls does not fired

### ISSUE THREAD

**Issue by KirdesMF** [framer/motion#888]
Dynamic Controls doesn't work, I tried with Framer and Framer motion
But with dynamics variants, it works
Maybe I'm missing something?

Codesandbox : https://codesandbox.io/s/gracious-shirley-6t03m?file=/src/App.tsx

1. Go to the codesanbox
2. Animation should works as expected
3. reverse the two useEffect.
4. Animation wont fired

**Comment by jshikanova** [comment]
Something like this? https://codesandbox.io/s/pedantic-cache-kx0yb?file=/src/App.tsx
I'm not sure how to make it work with Framer tho

I think you can get similar kind of animation with stagger:
https://www.framer.com/api/motion/animation/#orchestration
https://codesandbox.io/s/framer-motion-stagger-fade-in-up-9gky2

**Comment by KirdesMF** [comment]
the issue is not to have the same animation. The issue is that useAnimation with Framer does not work if you dont use a variants

https://codesandbox.io/s/gracious-shirley-6t03m?file=/src/App.tsx

When I tried with motion, I think I used the `useAnimation` from Framer and not framer-motion.

Anyway thanks for your help
