### ISSUE TITLE
[BUG] Code samples are hard to read on the documentation site

### ISSUE THREAD

**Issue by p45mark** [framer/motion#895]
The code samples are using black text on a very, very dark grey background. There's an older, closed bug report for this same issue (so maybe we should just re-open the older one?)
https://github.com/framer/motion/issues/415

No codesandbox required, this behavior is visible on the documentation site
https://www.framer.com/api/motion/

![image](https://user-images.githubusercontent.com/48729903/102136590-6e8b0180-3e0e-11eb-9cda-9f7dcf8f5ba9.png)

**Comment by KirdesMF** [comment]
only on chrome I guess

**Comment by mattgperry** [comment]
This is being caused by something like "Ace/Axe accessibility" plugin in Chrome. It is changing the HTML of the page, breaking our styles. We can't really support the actions of every potential plugin.
