### ISSUE TITLE
Question about starting animation

### ISSUE THREAD

**Issue by dvdbrk** [framer/motion#901]
How can I kickstart this animation when a user clicks on a button somewhere else on the page? 😕 

```
<motion.div
  initial={ false }
  animate={{ x: [ 0, +100 ] }}
  transition={{ duration: 0.3 }} >
    TEST
</motion.div>
```

**Comment by KirdesMF** [comment]
you can use the `useAnimation` hooks

https://www.framer.com/api/motion/animation/#component-animation-controls
