### ISSUE TITLE
Open a card example from homepage

### ISSUE THREAD

**Issue by tsahiBarshevsky** [framer/motion#905]
Hey, I'd really want to use the example with "tap to open a card" which appears on the [home page,](https://www.framer.com/motion/) but it looks like the code is partial. Can anyone help me with this? Thanks!

I'm talking about this:
![image](https://user-images.githubusercontent.com/38860203/102907624-0330d780-447f-11eb-92ab-c616c449a1b6.png)

**Comment by anatolzak** [comment]
I have the same question @tsahiBarshevsky  🙂

Here is a similar example with the same concept https://codesandbox.io/s/app-store-ui-using-react-and-framer-motion-ecgc2

Unfortunately, it uses `useInvertedScale()` which is not exported anymore in the latest release. 

I would love to check out how it is implemented with the latest release as well!

**Comment by tsahiBarshevsky** [comment]
Yes, it seems like you're right.
I've been using this example:
https://codesandbox.io/s/framer-motion-animatesharedlayout-app-store-demo-forked-h556x
which
works fine with the latest version of Framer-Motion, but it doesn't look
good on small screens.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
בלי
וירוסים. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

‫בתאריך יום ד׳, 23 בדצמ׳ 2020 ב-14:21 מאת ‪anatolzak‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by mattgperry** [comment]
We don't have a sandbox link of this I'm afraid. The code is purposefully minimal to illustrate the minimum working parts you need to make a similar effect; the source dump is more complicated and less helpful:

```jsx
We don't have a sandbox link of this I'm afraid. The code is purposefully minimal to illustrate the minimum working parts you need to make a similar effect; the source dump is more complicated and less helpful:

```

export default function App() {
  const [index, setIndex] = useState(false);

  const handleClose = useCallback(() => {
    setIndex(false);
  }, []);

  return (
    <LayoutGroup>
      <ul className={styles.gallery}>
        {[0, 1, 2, 3].map((item) => (
          <motion.li
            className={styles.item}
            key={item}
            layoutId={`${item}`}
            onClick={() => index === false && setIndex(item)}
            initial={{ borderRadius: "0.6rem" }}
          >
            <motion.div
              className={styles.placeholder}
              layoutId={`placeholder-${item}`}
            >
              <div />
              <div />
              <div />
            </motion.div>
            <motion.div
              className={styles.additional}
              layoutId={`additional-${item}`}
            >
              <div />
              <div />
              <div />
            </motion.div>
            <motion.div
              className={styles.itemClose}
              layoutId={`close-${item}`}
            />
          </motion.li>
        ))}
      </ul>
      <AnimatePresence>
        {index !== false && (
          <>
            <motion.div className={styles.modalContainer} key="modal">
              <motion.div
                className={styles.modal}
                layoutId={`${index}`}
                initial={{ borderRadius: "1.2rem" }}
              >
                <motion.div
                  className={styles.placeholder}
                  layoutId={`placeholder-${index}`}
                >
                  <div />
                  <div />
                  <div />
                </motion.div>
                <motion.div
                  className={styles.additional}
                  layoutId={`additional-${index}`}
                >
                  <div />
                  <div />
                  <div />
                </motion.div>
                <motion.div
                  className={styles.modalClose}
                  layoutId={`close-${index}`}
                  onClick={handleClose}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                >
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                    <path
                      d="M15 5L5 15M5 5l5.03 5.03L15 15"
                      fill="transparent"
                      strokeWidth="2"
                      stroke="currentColor"
                      strokeLinecap="round"
                    />
                  </svg>
                </motion.div>
              </motion.div>
            </motion.div>
            <motion.div
              className={styles.modalBackdrop}
              key="backdrop"
              onClick={handleClose}
              variants={{
                hidden: {
                  opacity: 0,
                  transition: {
                    duration: 0.16
                  }
                },
                visible: {
                  opacity: 0.8,
                  transition: {
                    delay: 0.04,
                    duration: 0.2
                  }
                }
              }}
              initial="hidden"
              exit="hidden"
              animate="visible"
            />
          </>
        )}
      </AnimatePresence>
    </LayoutGroup>
  );
}
```
```

**Comment by siddhesh-Mhatre** [comment]
```
import React,{useState} from 'react'
import {motion} from "framer-motion"

const data=[
{
    id:1,
    name:'react',
    dec: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit, molestiae."
},
{
    id:2,
    name:'garphql',
    dec: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit, molestiae."
}
  

]

const Card=({name,dec,id})=>{
    const [isopen, setisOpen] = useState(false);
   const variants={
        visible: {
            scale :1.2,
            boxShadow:"#d5a3d6 0px 0px 10px 1px",
            y: [0,50,-50],
            cursor:"pointer"
          },
          hidden: { scale: 1 },
    }
    return(
        <>
        <motion.div className='card' onClick={()=>setisOpen(!isopen)} variants={variants}  animate= {isopen?"visible":"hidden"}>
         <h1>{name}</h1>
         {isopen && (
        <>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 1 }}
          >
            <p>
            {dec}
            </p>
          
          </motion.div>
        </>
      )}
         </motion.div>
        </>
    )
}


const TaptoOpen = () => {
  return (
    <>
<div className='A_1'>
{
    data.map((cval)=>{
        return <>
        <Card {...cval} />
        </>
    })
}
</div>
    </>
  )
}

export default TaptoOpen;



````````````````````````````````````````` app.css``````````````````````````````````````````````````````````````
.App {
 
}
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  
}
body{
 height: 100vh;
 background: linear-gradient(to bottom, #33ccff 0%, #ff99cc 100%);
}

.A_1{
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  row-gap: 1rem;
  column-gap: 1rem;
}

 .card{
  width: 30rem;
  background-color: aliceblue;
  padding: 1.5rem;
 }

**Comment by siddhesh-Mhatre** [comment]
> ```
> import React,{useState} from 'react'
> import {motion} from "framer-motion"
> 
> const data=[
> {
>     id:1,
>     name:'react',
>     dec: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit, molestiae."
> },
> {
>     id:2,
>     name:'garphql',
>     dec: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit, molestiae."
> }
>   
> 
> ]
> 
> const Card=({name,dec,id})=>{
>     const [isopen, setisOpen] = useState(false);
>    const variants={
>         visible: {
>             scale :1.2,
>             boxShadow:"#d5a3d6 0px 0px 10px 1px",
>             y: [0,50,-50],
>             cursor:"pointer"
>           },
>           hidden: { scale: 1 },
>     }
>     return(
>         <>
>         <motion.div className='card' onClick={()=>setisOpen(!isopen)} variants={variants}  animate= {isopen?"visible":"hidden"}>
>          <h1>{name}</h1>
>          {isopen && (
>         <>
>           <motion.div
>             initial={{ opacity: 0 }}
>             animate={{ opacity: 1 }}
>             transition={{ duration: 1 }}
>           >
>             <p>
>             {dec}
>             </p>
>           
>           </motion.div>
>         </>
>       )}
>          </motion.div>
>         </>
>     )
> }
> 
> 
> const TaptoOpen = () => {
>   return (
>     <>
> <div className='A_1'>
> {
>     data.map((cval)=>{
>         return <>
>         <Card {...cval} />
>         </>
>     })
> }
> </div>
>     </>
>   )
> }
> 
> export default TaptoOpen;
> 
> 
> 
> ````````````````````````````````````````` app.css``````````````````````````````````````````````````````````````
> .App {
>  
> }
> *{
>   margin: 0;
>   padding: 0;
>   box-sizing: border-box;
>   
> }
> body{
>  height: 100vh;
>  background: linear-gradient(to bottom, #33ccff 0%, #ff99cc 100%);
> }
> 
> .A_1{
>   display: flex;
>   justify-content: center;
>   align-items: center;
>   height: 100vh;
>   row-gap: 1rem;
>   column-gap: 1rem;
> }
> 
>  .card{
>   width: 30rem;
>   background-color: aliceblue;
>   padding: 1.5rem;
>  }
> ```

i made this simple is it good ?

**Comment by siddhesh-Mhatre** [comment]
```
import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
const data = [
  {
    id: 1,
    name: "react",
    dec: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit, molestiae.",
    img: "https://images.unsplash.com/5/unsplash-kitsune-4.jpg?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjEyMDd9&s=50827fd8476bfdffe6e04bc9ae0b8c02",
  },
  {
    id: 2,
    name: "garphql",
    dec: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit, molestiae.",
    img: "https://images.unsplash.com/5/unsplash-kitsune-4.jpg?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjEyMDd9&s=50827fd8476bfdffe6e04bc9ae0b8c02",
  },
  {
    id: 3,
    name: "js",
    dec: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit, molestiae.",
    img: "https://images.unsplash.com/5/unsplash-kitsune-4.jpg?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjEyMDd9&s=50827fd8476bfdffe6e04bc9ae0b8c02",
  },
  {
    id: 4,
    name: "nodejs",
    dec: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit, molestiae.",
    img: "https://images.unsplash.com/5/unsplash-kitsune-4.jpg?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjEyMDd9&s=50827fd8476bfdffe6e04bc9ae0b8c02",
  },
  {
    id: 5,
    name: "css",
    dec: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit, molestiae.",
    img: "https://images.unsplash.com/5/unsplash-kitsune-4.jpg?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjEyMDd9&s=50827fd8476bfdffe6e04bc9ae0b8c02",
  },
];

const Blog = () => {
  const [show, setShow] = useState(false);
  const [info, setinfo] = useState();
  // animation for list
  const container = {
    hidden: { opacity: 1, scale: 0 },
    visible: {
      opacity: 1,
      scale: 1,
      transition: {
        delayChildren: 0.3,
        staggerChildren: 0.2,
      },
    },
  };
  const item = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
    },
  };

  //  animation for  popup

  const variants = {
    visible: {
      scale: 1.1,
      boxShadow: "10px 10px 0 rgba(0, 0, 0, 0.2)",
      y: -50,
      x: -100,
      cursor: "pointer",
      transition: { duration: 1, type: "spring" },
    },
    hidden: { scale: 1, opacity: 0 },
  };
  return (
    <section className="container mx-auto mt-5">
      <motion.ul
        style={{
          filter: show ? "blur(1px)" : "none",
        }}
        className="row d-flex   justify-content-center align-items-center"
        variants={container}
        initial="hidden"
        animate="visible"
      >
        {data.map((cval) => {
          return (
            <>
              <motion.li
                layout
                className="col-lg-5"
                onClick={() => {
                  setShow(!show);
                  setinfo(cval);
                }}
                variants={item}
              >
                <div
                  className="card position-relative w-100   p-0 "
                  style={{ borderRadius: "2rem" }}
                >
                  <img
                    src={cval.img}
                    className="img-fluid "
                    style={{
                      borderRadius: "inherit",
                    }}
                    alt=""
                  />
                  <h3
                    className="position-absolute text-capitalize text-black-50"
                    style={{
                      top: "17%",
                      left: "40%",
                    }}
                  >
                    {cval.name}
                  </h3>
                </div>
              </motion.li>
            </>
          );
        })}
      </motion.ul>

      <AnimatePresence>
        {show && (
          <>
            <motion.div
              className="card "
              style={{
                position: "fixed",
                top: "30%",
                left: "40%",
              }}
              onClick={() => {
                setShow(!show);
              }}
              variants={variants}
              animate={show ? "visible" : "hidden"}
              exit={{ scale: 1, opacity: 0 }}
            >
              <img src={info.img} className="img-fluid" alt="" srcset="" />
              <h1 className="card-title"> {info.name}</h1>
              <p className="card-text">{info.dec}</p>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </section>
  );
};

export default Blog;

```

**Comment by ACHIYANT** [comment]
> We don't have a sandbox link of this I'm afraid. The code is purposefully minimal to illustrate the minimum working parts you need to make a similar effect; the source dump is more complicated and less helpful:
> 
> ```js
> export default function App() {
>   const [index, setIndex] = useState(false);
> 
>   const handleClose = useCallback(() => {
>     setIndex(false);
>   }, []);
> 
>   return (
>     <LayoutGroup>
>       <ul className={styles.gallery}>
>         {[0, 1, 2, 3].map((item) => (
>           <motion.li
>             className={styles.item}
>             key={item}
>             layoutId={`${item}`}
>             onClick={() => index === false && setIndex(item)}
>             initial={{ borderRadius: "0.6rem" }}
>           >
>             <motion.div
>               className={styles.placeholder}
>               layoutId={`placeholder-${item}`}
>             >
>               <div />
>               <div />
>               <div />
>             </motion.div>
>             <motion.div
>               className={styles.additional}
>               layoutId={`additional-${item}`}
>             >
>               <div />
>               <div />
>               <div />
>             </motion.div>
>             <motion.div
>               className={styles.itemClose}
>               layoutId={`close-${item}`}
>             />
>           </motion.li>
>         ))}
>       </ul>
>       <AnimatePresence>
>         {index !== false && (
>           <>
>             <motion.div className={styles.modalContainer} key="modal">
>               <motion.div
>                 className={styles.modal}
>                 layoutId={`${index}`}
>                 initial={{ borderRadius: "1.2rem" }}
>               >
>                 <motion.div
>                   className={styles.placeholder}
>                   layoutId={`placeholder-${index}`}
>                 >
>                   <div />
>                   <div />
>                   <div />
>                 </motion.div>
>                 <motion.div
>                   className={styles.additional}
>                   layoutId={`additional-${index}`}
>                 >
>                   <div />
>                   <div />
>                   <div />
>                 </motion.div>
>                 <motion.div
>                   className={styles.modalClose}
>                   layoutId={`close-${index}`}
>                   onClick={handleClose}
>                   initial={{ opacity: 0 }}
>                   animate={{ opacity: 1 }}
>                   exit={{ opacity: 0 }}
>                 >
>                   <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
>                     <path
>                       d="M15 5L5 15M5 5l5.03 5.03L15 15"
>                       fill="transparent"
>                       strokeWidth="2"
>                       stroke="currentColor"
>                       strokeLinecap="round"
>                     />
>                   </svg>
>                 </motion.div>
>               </motion.div>
>             </motion.div>
>             <motion.div
>               className={styles.modalBackdrop}
>               key="backdrop"
>               onClick={handleClose}
>               variants={{
>                 hidden: {
>                   opacity: 0,
>                   transition: {
>                     duration: 0.16
>                   }
>                 },
>                 visible: {
>                   opacity: 0.8,
>                   transition: {
>                     delay: 0.04,
>                     duration: 0.2
>                   }
>                 }
>               }}
>               initial="hidden"
>               exit="hidden"
>               animate="visible"
>             />
>           </>
>         )}
>       </AnimatePresence>
>     </LayoutGroup>
>   );
> }
> ```

can i get the stylesheet also for this?

**Comment by ashleyww93** [comment]
How on earth does this example still exist in 2024 without example code?

**Comment by coderdiaz** [comment]
I build a similar example based on @mattgperry's code:
https://github.com/coderdiaz/framer-motion-homepage-cards
