### ISSUE TITLE
[BUG] AnimatePresence won't unmount fastly changing content

### ISSUE THREAD

**Issue by alisasila** [framer/motion#907]
**Bug description:**
Hi, 
I'm using AnimatePresence to animate text that shows up while hovering over some tiles.
I noticed that if I hover quickly over the tiles, AnimatePresence will play the text animations correctly, but will not unmount the component after the exit animation plays.

I want said animation to happen every time a user hovers over a different tile, so in my case the animation happens when:
1. The key of the HoverText component changes (according to the index of the tile, and the text being shown - makes sure it has a unique key).
2. The HoverText component mounts and unmounts (mouse enters tile, mouse leaves tile).

**CodeSandbox:**
https://codesandbox.io/s/animatepresence-quick-key-change-bug-zggbr?file=/src/HoverText.js

**Steps to reproduce:**
1. Go to the sandbox linked above.
2. Choose a single tile and hover over it - notice the text above pops up
3. Now stop hovering over the tile - AnimatePresence correctly animates and then unmounts the component.
4. Now, quickly hover over all the tiles from side to side, and then stop hovering over the tiles - notice how AnimatePresence animates them all correctly (both in and out), but for some reason does not unmount the component after finishing the exit animation.

**Video of bug:**

Correctly animates, and then unmounts:

https://user-images.githubusercontent.com/76623474/132943831-40e305fb-27c1-46be-904b-10fa8e78dec8.mp4{width="90%"}

Correctly animates, and then **doesn't** unmount:

https://user-images.githubusercontent.com/76623474/132943832-0355e449-e252-42d3-a222-732e930486d3.mp4

Also, sometimes if you hover over a couple of tiles slowly, the component does unmount, but this behavior is not consistent.

I am using the exitBeforeEnter prop on my AnimatePresence, but the problem persists even without it.

**Expected behavior:**
After a user hovers over the tiles quickly, AnimatePresence should unmount the HoverText component after its exit animation.

**Environment details:**
Using Chrome (Version 87.0.4280.88) on Windows

**Comment by Lukavyi** [comment]
I have the same issue

**Comment by utileetdulce** [comment]
This seems to be related to 
[1534](https://github.com/framer/motion/issues/1534)
[1439](https://github.com/framer/motion/issues/1439)

**Comment by silverprize** [comment]
Let's look at this issue please.

**Comment by Van4e3WT** [comment]
This problem is still observed

**Comment by mikkmartin** [comment]
Has anyone tested an earlier version of `framer-motion` where this is more reliable?

**Comment by mattgperry** [comment]
Since fixed
