### ISSUE TITLE
[BUG] snapToCursor not working

### ISSUE THREAD

**Issue by moterink** [framer/motion#912]
**2. Describe the bug**

I was trying to find a way to center a dragged motion component and encountered `snapToCursor`. However, when setting it to `true`, the dragged object is offset way off the screen so it seems like it disappeared, which I think is not expected behavior. If this actually is expected behavior, is there anywhere this is explained? Because it seems like the API documentation lacks explanation of this feature. 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/icy-silence-wu3xb?file=/src/App.js

**4. Steps to reproduce**

1. Drag the "Drag me!" container anywhere
2. The "Dragged" element is being offset to the left 

**5. Expected behavior**

The "Dragged" element should snap to the cursor

**Comment by KirdesMF** [comment]
works for me 

https://codesandbox.io/s/pensive-shtern-yncln?file=/src/App.js

**Comment by moterink** [comment]
@KirdesMF You are right, it was a silly mistake by me 😅 thanks for pointing it out! With a set width `spanToCursor` works perfectly. However I guess this feature should be documented (more) clearly in the API documentation.
