### ISSUE TITLE
[BUG] Issue with CSS transform

### ISSUE THREAD

**Issue by imangm** [framer/motion#914]
Hi,

If I apply the framer motion animation on an element which is centered using the following CSS code:

```
.center {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translateX(-50%) translateY(-50%);
}
```
Framer motion, will reset the transform property to 0. So it won't be center anymore.

Here is a sample on CodeSandbox:
https://codesandbox.io/s/fancy-hooks-4gj59?file=/src/App.js

Is there anyway to fix this behavior?

Thank you.

**Comment by oielbanna** [comment]
`x` and `y` in variants are gonna affect the transform css so you would have to remove that from your CSS class and add it to each of tbe variant classes. Since you're only actually changing the `y`, add `x: "-50%"` in all the variants you have - both show and hide. Does that work as expected?

**Comment by imangm** [comment]
@oielbanna Yeah, it worked using your solution. I removed all the transform CSS codes and put them in variants. Thank you!

BTW, It should be nice if it gives us the option to grab the initial status of the element and calculate the results based on that.

**Comment by mattgperry** [comment]
There is also a `transformTemplate` prop you can use to output custom `transform` strings.

**Comment by bosbode** [comment]
> 

I'm also not getting the desired result, when using transformTemplate and layout.

**Comment by ShubhaPradhan** [comment]
![image](https://user-images.githubusercontent.com/63387565/209853859-2d10930e-4beb-4c96-b048-8d52dce40232.png)

**Comment by BOSSladis** [comment]
> @oielbanna Yeah, it worked using your solution. I removed all the transform CSS codes and put them in variants. Thank you!
> 
> BTW, It should be nice if it gives us the option to grab the initial status of the element and calculate the results based on that.

Hey, how did you manage the `translateY(-50%)` and your `y: -100`, in your code to achieve both?
I'm facing a similar issue, where I have something centered in the same way and need to animate it on scroll with the style prop.

I'm trying to achieve something like this:

```
const { scrollY } = useScroll();
const transformedScrollY= useTransform(scrollY, [0, 200], [0, -100]);
// ...
<motion.img
style={{
y: `calc(-50%-${transformedScrollY}px)`,
x: "-80%",
}}
src={img}
alt="An image"
id="image"
/>
```

**Comment by prescottprue** [comment]
In my case when using Reorder.Group + Reorder.Item the `transformTemplate` (as called out by @mattgperry) along with `variants.initial.transform` did what I needed - without `transformTemplate` I was seeing misalignment between list items after reordering

```jsx
<motion.div
  // Match initial transform for ::marker to prevent misalignment after reordering
  transformTemplate={({ y }) => `translateY(${y}px)`}
  variants={{
    initial: {
      // the list item number appears slightly below the center,
      // and ::marker has limited styling options to move it up to center
      transform: 'translateY(6px)',
    },
  }}
/>
```

**Comment by salehi777** [comment]
You can use already generated transform too. [docs](https://motion.dev/docs/react-motion-component#transformtemplate)

```
transformTemplate={(latest, generated) => `translate(-50%, -50%) ${generated}`}
```
