### ISSUE TITLE
Drag and Drop list

### ISSUE THREAD

**Issue by arvigeus** [framer/motion#916]
I am trying to implement a list like this: https://codesandbox.io/s/framer-motion-2-drag-to-reorder-fc4rt

The thing is that this example is broken (changing heights to 60 for all breaks it), and there is no docs on how to do this anyway.

Had anyone implemented something similar?

**Comment by mattgperry** [comment]
This isn't an officially-supported feature so I'm closing this issue as I'm trying to clean up the issues board.

The demo is a little hacky in that it uses `height` for the item `key` so setting it in the `items` array isn't going to work as all items will have the same key. Ensure all items have a unique key.

**Comment by arvigeus** [comment]
I'll try to make it work in this fork: https://codesandbox.io/s/framer-motion-2-drag-to-reorder-forked-illop

If anyone in the future is looking for the same...
