### ISSUE TITLE
[FEATURE] Restore CSS Vendor Prefix

### ISSUE THREAD

**Issue by LBRDan** [framer/motion#920]
**Is your feature request related to a problem? Please describe.**
Some time ago (not sure on which version came off), Motion used stylefire for css related stuff and element style assignment. One of the many perks of using stylefire was having a larger support on older platforms that are in need of vendorized/prefixed css properties (eg. transform->WebkitTransform stuff)

**Additional context**
Seems like some legacy platforms (using some patched webkit version) expose an unsupported unprefixed css property as supported.
Eg:
Some of the Samsung Smart Tv's (Orsay) Webkit build, acts like it supports (using a test dom element as a testing probe [stylefire way]) the plain `transform` property, but actually does ignore everything throwed in it and works fine using `-webkit-transform`. Even the good old stylefire fails at detecting this.

**Describe the solution you'd like**
Restore this lost autoprefix behaviour inside motion

**Describe alternatives you've considered**
If you want, I already have a draft that I can submit via PR including this modification, but for the same reason described in the Additional Context paragraph, it fails to run some tests because the CSS property name picking function gives priority to prefixed one (surely supported) while the test make assertion about the exact style match
This can ben tedious to convert, also because the test environment uses a syntetic dom implementation via `jsdom` (using the .style implementation (inside `ElementCSSInlineStyle-impl.js`) based off `cssom` and `cssstyle`) therefore it is always pointing to the latest available living standard

**Comment by LBRDan** [comment]
I attached a PR about this
I think some maintainer should comment about the non-passing test (it is not a code related problem, but a trivial reason about the test env itself as explained here)

**Comment by mattgperry** [comment]
Hey thanks for the PR and issue, and sorry for the long response time. Looking at this now, we aren't going to restore prefixing. The number of browsers that will benefit is too low to validate the added bundlesize.
