### ISSUE TITLE
Release tags are confused and missing from GitHub

### ISSUE THREAD

**Issue by ewanmellor** [framer/motion#926]
https://github.com/framer/motion/releases shows a bunch of the v2.x series of releases (e.g. it has v2.7.6 and v2.7.5 but not v2.7.1-.4).  It doesn't have any of the v3.x releases.

https://www.npmjs.com/package/framer-motion?activeTab=versions has releases for v3.x through to v3.1.4, plus a 2.7.9, 2.8.x, 2.9.x.  It calls 3.1.4 "latest", 3.0.1 "rc", 2.7.2.alpha.1 "alpha", and 2.6.5-beta.8 "beta".

This is all really confusing.  Is the 3.x series supposed to be stable and 2.x series obsolete?  Or is 3.x series the bleeding edge and 2.x is the stable version?  Is the best 2.x release 2.7.6 per GitHub? Or is it 2.9.5 per the end of the NPM list?  So what's the alpha/beta/rc series?

If the NPM tags are obsolete and we're just supposed to use latest then please delete them.  Otherwise, they need updating I think.

It looks like you've given up on tagging git and are just relying on the package.json commit.  I think that's a shame because the GitHub releases page is very convenient, so if you can include tagging git in your release script (as before) then that would be good too.

**Comment by mattgperry** [comment]
Yeah good point about the tags, they were manually pushed so often out of date. I've now changed this to a `postpublish` script. 

I'm surprised to hear the tags are confusing. The stable tag, as with most npm packages, is `latest`. It's the one that gets installed when you run `npm install framer-motion` as per the instructions. You can ignore the rest.
