### ISSUE TITLE
[BUG] "Dynamic start" doesn't seem to be supported in 3.x

### ISSUE THREAD

**Issue by ewanmellor** [framer/motion#927]
The documentation at https://www.framer.com/api/motion/animation/ says:

> start can also accept a function that can dynamically start each component and the controls are bound to with a different animation definition.
> Custom data can be sent to this function via the component's custom prop.

This doesn't seem to be supported right now.  I found a line in `src/render/VisualElement/utils/animation.ts` that says `// TODO: Remove any and handle TargetResolver`, which I think is referring to this feature.

It seems to work in 2.9.5, and obviously it's documented.  Is this meant to be supported in 3.x?

**Comment by KirdesMF** [comment]
Seems related to #888 

https://codesandbox.io/s/crimson-cache-y9j59?file=/src/App.tsx

**Comment by jonathan-oberlander** [comment]
I also had an animation sequence break after updating to version 3.x. Here is simplified version. n is undefined, animation jumps straight to second step. This code is directly inspired from API documentation. Any thoughts?

```javascript
//
const animation = useAnimation()

useEffect(() => {
    const control = async () => {
      await animation.start((n) => ({
        y: -24,
        transition: {
          delay: n * 0.15,
        },
      }))
      await animation.start({
        opacity: 0,
        width: '45%',
        transition: {
          duration: 0.3,
        },
      })
    }
    control()
}, [anim])

return (
<>
  {['A', 'B', 'C', 'D'].map((letter, i) => (
   <motion.div
     custom={i}
     animate={animation}
     key={i}
   >
     {letter}
   </motion.div>
  )}
</>
)
```
