### ISSUE TITLE
[Documentation] layout='position' is not documented

### ISSUE THREAD

**Issue by ewanmellor** [framer/motion#928]
https://www.framer.com/api/motion/animation/#layout-animations has no mention of layout='position'.

This was added in PR #638 .

**Comment by dminkovsky** [comment]
I think it's documented here: 

https://github.com/framer/motion/blob/26c2bb73da62312522669a2895fcc643ca93a1da/src/motion/features/layout/types.ts#L26-L27

**Comment by mattgperry** [comment]
I've added a note about this in the layout animation troubleshooting section
