### ISSUE TITLE
[FEATURE] font-variation-settings animation

### ISSUE THREAD

**Issue by KirdesMF** [framer/motion#930]
**Is your feature request related to a problem? Please describe.**

It would be more a question of keeping my animations with framer. I'm using more and more variables font so it would be cool to be able to animate them with framer.

**Describe the solution you'd like**

Be able to animate any property of a variable font( random property according to the font )

**Describe alternatives you've considered**

I use CSS as fallback ( animation / transition )

**Additional context**

https://codesandbox.io/s/quiet-cloud-or4uq?file=/styles.css

**Comment by mattgperry** [comment]
Have you tried

```
initial={{ fontVariationSettings: `"TRMA" 0, "WMX2" 0, "SKLA" 0` }}
whileHover={{ fontVariationSettings: `"TRMA" 1000, "WMX2" 500, "SKLA" 500` }}
```

?

**Comment by KirdesMF** [comment]
it works . https://codesandbox.io/s/strange-wozniak-whcot?file=/src/App.tsx

Thx.

**Comment by prrrcl** [comment]
Ey! it could works with scrollY motionValue?

**Comment by krem06** [comment]
Hello @KirdesMF,

Would you mind publish again your codesandbox link? I am looking into framer motion to create some animations using variable font but not sure how to proceed as I am pretty new to framer...

Thanks

**Comment by krem06** [comment]
Awesome, thank you!
