### ISSUE TITLE
[BUG] layout prop for scale correction not working

### ISSUE THREAD

**Issue by Fxlr8** [framer/motion#931]
Hi, I used `layout` prop on my `motion.div` and noticed a weird behavior
When I use an inner `motion.div` for scale correction it makes things even worse

no correction on top, bottom one with correction.
before click:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/10725007/104132728-40a6c780-5390-11eb-99c1-b6f9162ff7ea.png">
immediately after click:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/10725007/104132740-55835b00-5390-11eb-85d8-727456a93428.png">
immediately after the second click:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/10725007/104132759-7055cf80-5390-11eb-9d01-f5dbf287b4b2.png">

As you can see, the text is distorted in both cases. But it is distorted even more with scale correction.

https://codesandbox.io/s/framer-motion-2-layout-animations-forked-415b5?file=/src/App.js

1. open sandbox
2. click on any switch to toggle a couple of times

**Comment by mattgperry** [comment]
Try `layout="position"` when animating text between two very different sized boxes (on and offfffff are naturally going to distort when animating from one size to the other): https://codesandbox.io/s/framer-motion-2-layout-animations-forked-4g5jj?file=/src/App.js

I also added `borderRadius: 50` to the style tag to enable scale correction on that too.

**Comment by Fxlr8** [comment]
Thanks, `layout="position"` is exactly what I was looking for. Looks like it is not documented yet.

**Comment by Fxlr8** [comment]
But anyways, I think that inner layout should cancel out the outer one so that the inner content is not distorted.
