### ISSUE TITLE
Best way to change animation settings depending on the screen size

### ISSUE THREAD

**Issue by RectoVersoDev** [framer/motion#932]
Hello, 

I'm looking for the best way to define different values of initial, animate and exit props for different viewport widths.

Same question for the useTransform hook, I use it for parallax like this :

```
function ParallaxSection() {
   const { scrollY } = useViewportScroll()
   const y = useTransform(scrollY, [0, 800], [0, -112])

   return (
      <Content style={{ y: y }}>
         ...  
      </Content>
   )
}
```
Is there a way to change these values depending on the screen size ?

Any examples would be very helpful.
Thanks!

**Comment by Fxlr8** [comment]
You can use `vh` and `vw` values instead of pixels. The movement will be proportional to the viewport size.
For some  something like https://material-ui.com/components/use-media-query/ hook. It is efficient and reliable.

**Comment by RectoVersoDev** [comment]
@Fxlr8 Thank you very much! I hadn't thought about viewport units! Also thanks for these hooks I'll test all this out.
