### ISSUE TITLE
[BUG] Nested MotionConfigs with duplicate features throws error 

### ISSUE THREAD

**Issue by harisraharjo** [framer/motion#933]
Hi,
I'm using AnimatePresence to enable page transition with react-router-dom.
However I encountered this error:
"Encountered two children with the same key, `animation`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version"

CodeSandbox:
https://codesandbox.io/s/loving-glitter-iy64g?file=/src/App.js

Steps to reproduce:

Go to the sandbox linked above.
Go to / 

It seems like this error is firing because of nested MotionConfig inside PageA. If I remove the outer MotionConfig and change the import from m to motion, the error goes away.

Environment details:
Using Chrome Version 87.0.4280.141 (Official Build) (64-bit) on Windows

**Comment by mattgperry** [comment]
For me, later: The solution here is to dedupe `features` with the same key.
