### ISSUE TITLE
[FEATURE] Automatically apply `will-change` style

### ISSUE THREAD

**Issue by amrnn90** [framer/motion#934]
### Description
I'm facing various glitches that appear on the background when trying to interact with the demos on Chrome (works fine on other browsers, tried with Edge and Firefox), it's mainly visible on the following demos (pease see attached gifs):
https://codesandbox.io/s/framer-motion-2-scale-correction-z4tgr
https://codesandbox.io/s/framer-motion-2-animating-shared-layouts-1cpd0

### Environment
OS: Windows 10 Pro Education (version 10.0.19042 Build 19042)
Browser: Chrome Version 87.0.4280.141 (Official Build) (64-bit)
GPU: NVIDIA Geforce GTX 1660 Ti

### Gifs showing the problem
![framer-motion-issue](https://user-images.githubusercontent.com/38134195/104468507-96fe4b00-55c8-11eb-83f4-a54d994af275.gif)
![framer-motion-issue-2](https://user-images.githubusercontent.com/38134195/104468522-9b2a6880-55c8-11eb-8bf7-65d44344362d.gif)

**Comment by amrnn90** [comment]
I believe the issues are mainly caused by `border-radius`, removing it makes things work fine.

**Comment by KirdesMF** [comment]
you can add `will-change: transform` to the element with a border-radius. It will fix this issue.

**Comment by KirdesMF** [comment]
and this issue is in all chromium broser so it happens also in Edge

**Comment by KirdesMF** [comment]
ok so its a chrome bug; I found this SO thread with an other solution to this issue : 

https://stackoverflow.com/questions/9983520/webkit-animation-is-leaving-junk-pixels-behind-on-the-screen

I rarely encounter this problem because I often use box-shadow and it forces chrome to repaint correclty (if I understand correctly).


the pen is updated : https://codepen.io/CedGrvl/pen/mdrQBWb?editors=1100

**Comment by amrnn90** [comment]
Hi @KirdesMF, thanks for your help.
Adding `will-change: transform` does indeed fix the issue, I tried doing `will-change: width, height` before since these are the things changed in the demo but I guess framer motion does change the transform internally for performance reasons.

I also thought all Chromium browsers would be affected but when I tried Edge it worked fine.

I know that the codesandbox is using an older version (I tried upgrading to framer motion 3 before posting the issue), but these demos are the ones used in the documentation and they're using an older version.

Maybe the demos sandboxes should add `will-change: transform` or mention something about this problem?

Anyway Feel free to close this, thanks again.

**Comment by KirdesMF** [comment]
not sure if the example should mention this issue. its known chrome issue. the SO thred exaplain well what's happen.
I agree that some framer example should be review.
I guess its a community job

**Comment by amrnn90** [comment]
@KirdesMF 
I can try and make PR to the docs repo, but I'm not sure what the best way is for updating the codesandbox examples since I don't have access to the originals...should I fork them and link to my forks instead?

**Comment by KirdesMF** [comment]
I'm really not an expert in PR and I really need to dig in. maybe check this repo and see where this examples are. and see if you can make a PR for that. idk sorry

**Comment by mattgperry** [comment]
I don't understand how `will-change: transform` works but we use `translate3d` for all these demos which I assumed did the same thing?

**Comment by KirdesMF** [comment]
it is really a weird issue.
you can check this sandbox : https://codesandbox.io/s/framer-motion-scale-correction-forked-1i8zx

it sometimes happens when there is a border radius, content inside the box

for `will-change`: https://dev.opera.com/articles/css-will-change-property/

hope it helps

**Comment by mattgperry** [comment]
Hi all

Due to the very strongly opinionated nature of this feature I decided to make it opt-in via a motion value, `useWillChange` https://www.framer.com/docs/use-will-change/

Please use it, and let me know how it works for you. It might be in the future this becomes a built-in default.
