### ISSUE TITLE
How does glitch effect on text work ?

### ISSUE THREAD

**Issue by Kronicom** [framer/motion#935]
Hello, apologies of opening an issue regarding this but,
I'm pretty new with Framer Motion, and I can't seem to find any documentation regarding the values of each attribute.

Example:

`animate={{ rotate: 360 }}`

That one is very straight forward but when it comes to, glitch, fly, etc, there's not many information out there regarding those.

Any examples with the glitch effect and/or a general overview of the other animations would be a fantastic help.

Thank you.

**Comment by KirdesMF** [comment]
because there is no built-in animation. you'll need to build your own. all attributes are css properties.

**Comment by Kronicom** [comment]
> because there is no built-in animation. you'll need to build your own. all attributes are css properties.

Is that so ?

**Comment by KirdesMF** [comment]
?
