### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mutaimwiti** [framer/motion#936]
**1. Describe the bug**

When a video element is added to the `AnimatePresence` component, there is a noticeable flicker. The same is not true for image sources.

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/video-flicker-is89k

**3. Steps to reproduce**

1. Open the sandbox link. You will see a video element.
2. Click `Toggle source 2` button. This will add another video element below the first one. Notice there is a flicker as the video mounts. Click it a few more times with a keen eye on the second video to get more clarity.
3. Click `Toggle media`. You will see one or 2 image elements. Click `Toggle source 2`. This will toggle the second image. Do this a few more times like in step 2. There should be no noticeable flicker like in the video scenario.
4. With the app in a state where the two elements are shown, keep clicking `Toggle media`. Notice that every time media changes to video, there is a flicker as the videos are mounted. This is not the case for images.

**4. Expected behavior**

When adding and removing video elements from `AnimatePresense` there should be no flicker.

**5. Video or screenshots**

https://user-images.githubusercontent.com/8180548/104597921-fae74900-5686-11eb-9106-550e4e71519f.mov

**6. Environment details**

React v16, MacOS Mojave

**Comment by mattgperry** [comment]
Closing as this effect is present even without `AnimatePresence`.
