### ISSUE TITLE
[FEATURE] Allow HTML color names as valid animation values

### ISSUE THREAD

**Issue by Lillebo** [framer/motion#937]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
Ref. https://www.framer.com/api/motion/component#supported-values

I'd like to be able to use [HTML color names](https://en.wikipedia.org/wiki/Web_colors#HTML_color_names) (incl. extended colors) as valid values. Example:

```
<motion.div
  animate={{
    backgroundColor: "red" <--
  }}
/>
```

**Comment by mattgperry** [comment]
I’ll leave this open for now as it might be that we make this user-pluggable but to be upfront this is never going to be added to the library. It adds a lot of bundle size relative to its value.

**Comment by mattgperry** [comment]
Closing as this is unlikely to be added in the near future
