### ISSUE TITLE
[BUG] Font loading error with latest version (1.2.12)

### ISSUE THREAD

**Issue by arvigeus** [framer/motion#938]
**1. Describe the bug**

Latest version of `framer` tries to load some fonts apparently, which causes a crash after 5 seconds

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Official framer code sandbox: https://codesandbox.io/s/rrlpv8lo3m

**3. Steps to reproduce**

1. Update `framer` package from any to 1.2.12 (1.2.11 seems to work)
2. Wait 5 seconds

**Comment by jurij** [comment]
any progress here? latest version `1.2.15` is also not working

**Comment by mattgperry** [comment]
Sorry this repo is just for `framer-motion`. You can find help for Framer on our community https://www.framer.com/community/
