### ISSUE TITLE
[BUG] Use with Components of Material-UI

### ISSUE THREAD

**Issue by DemetriusHR** [framer/motion#939]
**2. Describe the bug**
I use the motion.custom in Box of Material-UI, but is returned the error in console:

![image](https://user-images.githubusercontent.com/39563555/104918988-53af2e00-5974-11eb-90f4-f447c594709d.png)

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Link to CodeSandBox:
https://codesandbox.io/s/brave-archimedes-6570f?file=/src/App.tsx

**4. Steps to reproduce**

Please see CodeSandbox above.

**5. Expected behavior**

Don't have error in console.

**Comment by mattgperry** [comment]
Dupe https://github.com/framer/motion/issues/497
