### ISSUE TITLE
[SOLVED] Can’t reset motion element’s drag position manually

### ISSUE THREAD

**Issue by colepeters** [framer/motion#945]
**1. Read the [FAQs](#faqs) 👇**
✅ 

**2. Describe the bug**
I’m not sure if this is _technically_ a bug or not, however…

I’m attempting to manually reset a motion element’s drag position through it’s inline styles, but I can’t get this to work. The `translate3d` transform that is applied when dragging the element seems impossible to remove, even when props relevant to the component are updated.

(Background: I'm implementing a feature that allows a user to toggle a zoom factor on an image, and only drag the image when that zoom is enabled. When I disable the zoom, I want the dragged image's position to reset, but I can't get this to work.)

I've gone through the docs attempting to find a way to manually reset the element's position, but haven't come up with anything.

Any way to do this?

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

CSB repro: https://codesandbox.io/s/framer-motion-drag-reset-attempt-vbnoj?file=/src/App.js

**4. Steps to reproduce**

1. Open the sandbox linked above
2. Drag the image around
3. Toggle the drag
4. The image's inline styles contain a conditional style, `transform: none`, which get spread when `canDrag` is `false`. I would expect this to reset the element's translated position, but it has no effect.

**5. Expected behavior**

Applying an inline `transform` style (after a drag is completed) should overwrite the transform set by framer-motion. OR, there should be some other way to reset an image's dragged position.

**6. Video or screenshots**

I’m attaching a gif of the in-progress feature; this should help explain why the reset is important. When the image is zoomed out again, it's positioned very strangely. (Don’t laugh at the sample image I'm using. It’s for an English lesson on pronunciation. Okay fine you can laugh.)

![Jan-25-2021 14-26-16](https://user-images.githubusercontent.com/1713932/105762232-c17dcb80-5f19-11eb-8475-9afd9abb5be3.gif)

**7. Environment details**

framer-motion v 3.2.1

Tested on macOS and Chrome but I don't think this is client-specific.

**Comment by mattgperry** [comment]
Replacing `transform: "none"` with `x:0,y:0` seems to work for me

**Comment by colepeters** [comment]
@mattgperry Ah, nice! For some reason I hadn't thought of tapping into `animate` for this, but that makes a lot of sense, and it works. Thanks a lot!

**Comment by mattgperry** [comment]
I was testing these by passing into `style` as Motion supports single transform values in style, just in case that triggers unwanted animations

**Comment by colepeters** [comment]
@mattgperry D'oh; I conveniently also forgot about the enhanced `style` prop on motion elements. This actually works even better for my use case. Thanks again!

**Comment by ArianHamdi** [comment]
> Replacing `transform: "none"` with `x:0,y:0` seems to work for me

It's works but when combining with layout animation , the animation is a bit wierd.
Is there any way to reset drag position imperatively ?

I've tried using drag controls in this way but it doesn't work : 

```javascript
const dragControls = useDragControls();

const onReset = () => {
   dragControls.start({ 
        x:0,
        y:0
    })    
}

```

**Comment by wfortin** [comment]
@ArianHamdi I ran into the same issue today and found a solution combining `useDragControls` and `useAnimationControls`

```ts
const dragControls = useDragControls();
const animationControls = useAnimationControls();

const onReset = () => {
  animationControls.set({
    x:0,
    y:0
  })    
}

// In your JSX component
<motion.div 
   animate={animationControls}
   dragControls={dragControls}
/>
```

**Comment by jjkavalam** [comment]
Sharing a working codesandbox.io link with @wfortin 's solution: https://codesandbox.io/p/sandbox/framer-motion-drag-reset-attempt-forked-4gstj4

**Comment by lazerwalker** [comment]
Curious if anyone's found a solution that doesn't rely on animationControls — my component also has some other animations that mean I'm already using the `animate` property to set to a named variant, so I can't use the legacy AnimationControls system.

**Comment by lazerwalker** [comment]
To answer my own question for any future person who comes here via search result: I was able to just import the `animate` function and manually animate the component in my handler. The HTML element being animated was not the element that was receiving the touch events, but I was able to add a class name to the animated div (call it `.animation-view`) and more or less do:

```js
const animationTarget = e.target.closest('.animation-view') // plus some TS typecasting, a null check or two, etc
animate(animationTarget, { x: 0 }, { type: 'spring', ... }) // Or whatever animation you want to reset to
```

Not the most elegant, it feels a bit 'wrong', but it's a small amount of code and it works.
