### ISSUE TITLE
[DOCS] Documentation is difficult to read and highlight

### ISSUE THREAD

**Issue by tenthyoung** [framer/motion#946]
The documentation shows the code in this fashion:
![image](https://user-images.githubusercontent.com/18620046/105789280-fa786900-5f36-11eb-822e-53cbfa9fca60.png)

It's difficult to read and highlight for copy and pasting.

Is there a way to fix this on my end? 

Thanks!

**Comment by mattgperry** [comment]
@tenthyoung Thanks for the report - does your console show any errors when you visit this page?

**Comment by jberglund** [comment]
I had the same problem. Turned off `axe - web accessibility testing` and it went back to normal. Check your extensions if any of them inject something that might cause this @tenthyoung :)

**Comment by mattgperry** [comment]
@jberglund Thanks for the report. Installing this extension replicates the problem. I'm going to close this issue. The extension modifies the page markup, breaking the `pre code` CSS selection that applies many of the code styles. This isn't a bug on our end IMO.
