### ISSUE TITLE
[BUG] AnimatePresence route transition breaks when using css modules

### ISSUE THREAD

**Issue by edoguido** [framer/motion#948]
**1. Read the [FAQs](#faqs) 👇**
✅

**2. Describe the bug**

Page styles are removed during route transition with AnimatePresence on NextJS. This breaks the exiting route style.
This happens ONLY IN PRODUCTION, hence is not visible when developing locally, but only when building the web app or deploying it on Vercel. This means the code works.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Codesandbox with minified example https://codesandbox.io/s/jolly-chatterjee-jl1sp
https://zone-covid-712wtaw16.vercel.app/ is up and running with the problem.

**4. Steps to reproduce**

1. Go to https://codesandbox.io/s/jolly-chatterjee-jl1sp or https://zone-covid-712wtaw16.vercel.app/
2. Click on the white button on the homepage
3. See error
4. [optional] hit the back button in your browser
5. See error again

**5. Expected behavior**

Expected behaviour happens in development environment.
Exiting route should perform exit animation before new route enters, without css breaking.

**6. Video or screenshots**

https://user-images.githubusercontent.com/22613065/105861473-0c1d4780-5fef-11eb-806b-a7b6bf17eefc.mov

**7. Environment details**

Not relevant but tried with:
- macOS Chrome Version 87.0.4280.88
- macOS Safari Version 14.0.3 (16610.4.3.1.4)
- iOS 14 Mobile Safari

**Comment by edoguido** [comment]
For everyone else having the same issue and wondering, it's due to Next:
https://github.com/vercel/next.js/issues/17464#issuecomment-724345414

**Comment by edmundojr** [comment]
Having the same issue — also on Next.js. Thanks for sharing the issue @edoguido!

**Comment by AimanAlmureish** [comment]
Is there a way to fix this? I am having the same issue!

**Comment by jrrio** [comment]
AnimatePresence makes Next.js app messy in production (npm run build && npm run start) if the pages / components utilise CSS Modules. The solution is using global styles or Tailwind CSS.
