### ISSUE TITLE
[BUG] useViewportScroll() only working with x y scale and opacity properties

### ISSUE THREAD

**Issue by marcelomandaji** [framer/motion#950]
I am using framer motion to do a parallax effect in a website. One of the styles i need to change is the letter-spacing but the only styles i can change with useViewPortScroll is x y scale and opacity.

Sometimes while scrolling the letter-space changes, but is seems to be random, i cannot replicate that change.  

If you scroll up and down a few times you can see this happening.

https://codesandbox.io/s/framer-motion-parallax-effect-forked-udwsx

part of the code in question:

```
const { scrollYProgress } = useViewportScroll();
const letterSpace = useTransform(scrollYProgress, [0, 1], [0, 100]);
...
<motion.h1 style={{ letterSpacing: letterSpace }}>text</motion.h1>
```

**Comment by mattgperry** [comment]
`letterSpace` doesn't have default value type defined in motion (as a lesser-used prop) but you can always explicitly define one:

```javascript
const letterSpace = useTransform(scrollYProgress, [0, 1], ['0px', '100px']);
```
