### ISSUE TITLE
[BUG] Unmet dependency isn't compatible with React 17+

### ISSUE THREAD

**Issue by CitizenBeta** [framer/motion#952]
On yarn install, I get this:

warning " > framer-motion@2.9.5" has unmet peer dependency "react@>=16.8".
warning " > framer-motion@2.9.5" has unmet peer dependency "react-dom@>=16.8"

I'm on the latest version of react, as of this post is 17.0.1

**Comment by ndom91** [comment]
Also am having trouble installing with react@17.0.1 still. 

>=16.8 _not_ include major versions?

**Comment by mattgperry** [comment]
Does `3.7.0` work better for you?

**Comment by David-glitc** [comment]
I'm having these issues 
 framer-motion 10.12.16
│ └── ✕ unmet peer react-dom@^18.0.0: found 17.0.2
