### ISSUE TITLE
[FEATURE] Add back sideEffects to allow for tree shaking in webpack

### ISSUE THREAD

**Issue by jrparish** [framer/motion#953]
**Is your feature request related to a problem? Please describe.**

Webpack requires the `sideEffects` flag to be set in package.json in order for tree shaking to work appropriately. 

**Describe the solution you'd like**

I understand the reason behind orginally reverting `sideEffects: false` https://github.com/framer/motion/pull/774
But I believe this isn't the appropriate long-term fix. The sideEffects flag also allows for a list of files with side effects which tells webpack to leave these files alone https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

Ideally there wouldn't be side effects, but if there are, this file array is a good way to get the best of both worlds.

**Comment by mattgperry** [comment]
That rationale is no longer applicable either, let me take a look
