### ISSUE TITLE
[QUESTION] How to use <AnimatePresence />

### ISSUE THREAD

**Issue by kud** [framer/motion#958]
Hello,

I understand the point of `<AnimatePresence />` but I'm not 100% sure how to use it.

Should I use it as wrapper every time I've got a component I want to check or can I use it as "provider" in my whole app?

Thank you

**Comment by mattgperry** [comment]
Because of the limitations of React, exiting/entering components sadly must be direct children of AnimatePresence

**Comment by kud** [comment]
Got it! Thank you very much @mattgperry :)

**Comment by mattgperry** [comment]
No worries!
