### ISSUE TITLE
[BUG] Framer-Motion doesnt work when bundled with electron-webpack

### ISSUE THREAD

**Issue by SentoxAIO** [framer/motion#960]
It seems like that something in electron-webpack breaks framer-motion (I couldn't figure out what yet).

![image](https://user-images.githubusercontent.com/57367608/106794886-b33a5880-6659-11eb-82f5-f3b452bde829.png)
 No, It's not because of any hooks in my code (you can create a basic component with just a motion.div in it and get the same error)

I could trace back the origin of the error to this line in the package  (framer-motion.cjs.js):
![image](https://user-images.githubusercontent.com/57367608/106794816-9ef65b80-6659-11eb-8845-669b62f811a3.png)

I made a simple repo which shows what error I am talking about.
(A Sandbox doesn't do the job in this case)
https://github.com/SentoxAIO/framer-motion-bug

**Comment by Dlexius** [comment]
I'm having the exact same error.

**Comment by mattgperry** [comment]
@SentoxAIO Why did you close this issue?

**Comment by ts-23** [comment]
Does framer motion support electron js?
