### ISSUE TITLE
[BUG] Mount animation not working when I have when: afterChildren set in the transition prop 

### ISSUE THREAD

**Issue by 55Cancri** [framer/motion#963]
Here is the codesandbox of the issue:
https://codesandbox.io/s/cocky-pascal-bfgof?file=/src/App.js

Notice child 1 does not animate in on load, but child 2 does.

If you go to the variants file and comment out when: `afterChildren` and `when: beforeChildren` for the li variants, then refresh the page, it works as expected, both child 1 and child 2 load on mount.

However, if you then try to open child 1, then close it, it will close before the color swatches fade out. So by adding `when: afterChildren` to the closed variant, then when you close the panel, it will first wait for the swatches to fade out, then close. But then the mount issue occurs.

I don't know why the when prop would affect the mount animation. I tried adding unique keys to every motion component. Didn't help. I tried explicitly defining the initial and animate states of most of the motion components. Didn't work. Not sure what to do.

If there is a way to get the close animation of child 1 to wait for the swatches to disappear before closing the panel without using the when prop, that would be fine too.

Also notice that I'm using recoil as a state management library! Apparently, if you remove recoil from the component, it works fine.

**Comment by mattgperry** [comment]
Can you try with `3.5.3`? The mount animation should be fixed but I need to look into the unmount cancelation.

**Comment by 55Cancri** [comment]
> Can you try with `3.5.3`? The mount animation should be fixed but I need to look into the unmount cancelation.

Nice, that fixed it! Thank you Mr. Perry!
