### ISSUE TITLE
[BUG] motion.div style={{X} does not project after changes or call x.Set(value)

### ISSUE THREAD

**Issue by damikun** [framer/motion#965]
**2. Describe the bug**
motion.div `style={{x}}` does not gets updated in new version after `x` change... Works only in version <=2.3 (2.3.1rc2)

I have toggle example motion div and after state change or calling `x.Set("value")` the position is not updated over  `style={{x}}`. The  `x`  value itself is changed but `motion.div` keeps the last state and do not update this change...
```
     <motion.div
            style={{
              x: x,
            }}
            drag="x"
            dragConstraints={{ left: 0, right: 0 }}
            onDragEnd={(e, position) => {
              if (Math.abs(position.offset.x) / 2 > 20 / 2) {
                if (position.offset.x > 0) {
                  setstate(true);
                  x.set(20);
                } else {
                  setstate(false);
                  x.set(0);
                }
              }
            }}
            dragElastic={0.5}
     />
 ```

**Give a clear and concise description of what the bug is.**

LastVersion (**Not** working - BUG)
https://codesandbox.io/s/framer-toggle-test-forked-7pp44?file=/src/Example.tsx:355-479

Working ( v <= v2.3)
https://codesandbox.io/s/framer-toggle-test-forked-0ll9i?file=/src/Example.tsx

**Comment by georgekrax** [comment]
I am facing similar issues with versions **>= 3.0.0**. In my case the `useAnimation()` hook does not work at all for `x` and `y` values. 

It maybe is my mistake and the code is not working, but this library is considered *production-ready*, and in my opinion, that kind of issues should be fixed, and answers should be given in the comments section.

**Comment by mattgperry** [comment]
@ georgekrax This issue was opened three days ago, two of which have been the weekend. About a version that’s been out for over a month now. I’ll be looking at this ticket at some point in the coming weeks but it will be prioritised alongside other bugs and product features.

In the meantime we also accept PRs.

**Comment by georgekrax** [comment]
@mattgperry Thank you for your response. Yeah, I know that the **>= 3.0.0** versions were published over a month ago, but unfortunately when I upgraded the package in my project it did not work as it was with the previous versions, even though I followed the latest docs.

**Comment by mattgperry** [comment]
@damikun It's not immediately clear to me why this behaves differently between the versions but IMO this is actually working correctly in 3.x.

`x.set()` is being called during the `dragTransition` animation so the update is overridden by the animation. If you call `x.stop()` before `x.set()`, then the update fires.

**Comment by damikun** [comment]
@mattgperry  this is not related to `x.set()` but to `style={x}` of motion.div... You can change example just to react to state change... And when state change the style prop  `x` of motion.div  will never gets updated...

```
  <motion.div
            style={{
              x: someState,
            }}
            
            //etc
```

**Comment by georgekrax** [comment]
Btw, I found out that **Variants** that utilize the `custom` Prop - attribute, do no work as expected if used somewhere else than the `animate` Prop (eg. with the `useAnimation()` hook).

**Comment by mattgperry** [comment]
@damikun That is the safest way of doing it if you are running animations. Previous versions didn't monitor style change during animations.

@georgekrax Yes. Please open a bug report with an example sandbox.
