### ISSUE TITLE
[BUG] Main website (framer.com/motion) isn't working

### ISSUE THREAD

**Issue by mpereira** [framer/motion#967]
**1. Describe the bug**

[framer.com/motion](https://www.framer.com/motion) doesn't allow user interaction with the page.

**2. Steps to reproduce**

1. Go to https://www.framer.com/motion
2. The page seems to load correctly, but after a fraction of a second an overlay is added to it, making the whole page a bit darker 
3. Try to click on links, scroll the page. Doesn't work
4. Open DevTools to inspect the HTML elements
5. See overlay elements blocking user interaction

**3. Expected behavior**

I can click on links and scroll the main website.

**4. Video or screenshots**

![Screen Shot 2021-02-06 at 12 38 44](https://user-images.githubusercontent.com/112426/107117123-55378c00-6878-11eb-9175-96874673b5c3.png)
![Screen Shot 2021-02-06 at 12 38 57](https://user-images.githubusercontent.com/112426/107117126-58327c80-6878-11eb-9499-75b9f8672b79.png)

**5. Environment details**

macOS 10.15.5
Chrome  88.0.4324.96
Europe

**Comment by bouchenoiremarc** [comment]
Closing as this is now fixed site-wide. 🎉

**Comment by mpereira** [comment]
I can confirm that I don't get the overlay anymore and the site works. Thanks @bouchenoiremarc!
