### ISSUE TITLE
staggerChildren affects first render only

### ISSUE THREAD

**Issue by justrealmilk** [framer/motion#968]
`staggerChildren` affects first render only. Is this intentional behaviour or should subsequent renders also be staggered by this property?

For example, if I render 4 items from an array, they will stagger on initial render. If I adjust the offset for this imaginary array, the next 4 items will animate in-sync.

https://user-images.githubusercontent.com/156681/107303675-6200df00-6a34-11eb-943b-7f69ccfed7fe.mp4

**Comment by mattgperry** [comment]
What version are you using?

**Comment by justrealmilk** [comment]
> What version are you using?

3.3.0

**Comment by justrealmilk** [comment]
Okay, I've worked it out.

The container with the transition prop of staggerChildren won't stagger children a second time unless it's key changes, causing a re-render.

You learn a lot in 7 hours. I guess this is now a documentation request 😛

**Comment by mattgperry** [comment]
Ah no it is a bug - I believe it'll be fixed in 3.4.0

**Comment by justrealmilk** [comment]
Persists with 3.5.1 😔

**Comment by justrealmilk** [comment]
The component is being used like this:

```js
const VARIANT_CONTAINER: Variants = {
  initial: {},
  animate: (staggerChildren: number = 0.1) => ({
    transition: {
      staggerChildren,
    }
  }),
};

const VARIANT_MODULE: Variants = {
  initial: {
    opacity: 0,
    y: 16,
  },
  animate: (staggerChildren: number | undefined) => ({
    opacity: 1,
    y: 0,
    transition: {
      staggerChildren,
      duration: 0.1,
      ease: [0.33, 1, 0.68, 1],
    },
  }),
};


export function Container({ className, children, ...props }: Props) {
  return (
    <motion.div className={cx('container', className)} custom={props.staggerChildren} variants={VARIANT_CONTAINER} initial='initial' animate='animate' {...props}>
      {children}
    </motion.div>
  );
}

export function Module({ className, children, ...props }: Props) {
  return (
    <motion.div className={cx('module', className)} custom={props.staggerChildren} variants={VARIANT_MODULE} initial={useReducedMotion ? false : undefined} {...props}>
      {children}
    </motion.div>
  );
}

function Render() {
  return (
    <Container>
      {someVar ? <ComponentA /> : <ComponentB />}
    </Container>
  );
}

function ComponentA() {
  return (
    <>
      <Module>...</Module>
      <Module>...</Module>
      <Module>...</Module >
    </>
  );
}

function ComponentB() {
  return (
    <>
      <Module>...</Module>
      <Module>...</Module>
    </>
  );
}
```

**Comment by mattgperry** [comment]
The children will only stagger if the parent that defines staggerChildren is itself animating. It might be worth using a custom delay approach here.

**Comment by idrisadetunmbi** [comment]
This is unrelated: but how do I prevent the animations (variants) from running again when there is a rerender? Thanks.

**Comment by justrealmilk** [comment]
This is still an issue. I'll render a new parent on props change e.g. route params and its children won't stagger unless I assign it a unique key (or in this case, explicitly assign a key e.g. 'myContainer1').

**Comment by VincentThomas06** [comment]
For me staggerChildren has never worked. I tog an example from the docs but no luck
