### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by javusScriptus** [framer/motion#969]
**rotate3D**
I need to animate element with `rotate3d` function (from transform). Now I can only use : rotate/rotateX/rotateY/rotateZ/offsetRotate.
Is it possible to manipulate an element using rotate3D?

**Comment by mattgperry** [comment]
You can use `transform` instead of `x`/`rotateZ` etc as long as you keep the formatting/transform order the same.

**Comment by javusScriptus** [comment]
Great news, thank You for the information ;D Its working
