### ISSUE TITLE
How to programatically animate a list scroll?

### ISSUE THREAD

**Issue by DoneDeal0** [framer/motion#971]
**1. Describe the issue**

I am trying to migrate from react-spring to framer motion. I need to programatically scroll a virtualized list.

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Here is a working sandbox with react-spring. The list is uodated through the `scrollTop` property. I've tried to update its value through useSpring or useMotionValue states, but these were not progressively updated, they directly rendered the right number, so there was no spring scroll. 

https://codesandbox.io/s/spring-vs-motion-7ojlx?file=/src/VirtualizedList.tsx:791-1375

How to do it with Framer motion?

**3. Steps to reproduce**

Basically, the animation looks like this with spring:
```js
<Spring from={{ top: 0 }} to={{ top: lineHeight * (page.from - 1) }}>
          {(props) => (
            <List
              height={lineHeight * limit}
              rowCount={data.length}
              rowHeight={lineHeight}
              width={1}
              rowRenderer={row}
              containerStyle={{
                width: "100%",
                maxWidth: "100%"
              }}
              style={{
                width: "100%",
                overflow: "hidden"
              }}
              scrollTop={props.top}
            />
          )}
        </Spring>
```

**4. Expected behavior**

Scroll smoothly when clicking a new page.

**Comment by mattgperry** [comment]
For `scrollTop` you need to do this imperatively:

```javascript
useEffect(() => {
  const element = ref.current
  const controls = animate(element.scrollTop, scrollTarget, { onChange: v => element.scrollTop = v })
  
  return () => controls.stop()
}, [scrollTarget])
```
