### ISSUE TITLE
Scrolling is super jittery and stiff on WebKit Based Browsers [BUG]

### ISSUE THREAD

**Issue by antonioberetini** [framer/motion#973]
When using scroll component for scrolling, scroll is super smooth on Android and Windows based browsers, it is super jittery and stiff on WebKit based browsers making it useless. I see other people reporting this issue across multiple bug reports. Is this something that you plan to address?

**Comment by antonioberetini** [comment]
https://github.com/framer/motion/issues/472#issue-573146326

**Comment by mattgperry** [comment]
@antonioberetini Closing this for now as I feel like you're talking about `Framer`'s `Scroll` component? Rather than something in `framer-motion`. This is something that we plan on looking at but isn't an issue for this board.
