### ISSUE TITLE
[BUG] Gatsby build fails after update to framer-motion 3.X

### ISSUE THREAD

**Issue by silviojaeger** [framer/motion#977]
**Describe the bug**
We use framer-motion with gatsby-js. After update to framer-motion v.3, the gatsby build process fails with the following error message:

`ReferenceError: performance is not defined
    at Timeout._onTimeout (/......./public/render-page.js:8952:25)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)
     /......./public/render-page.js:8952
     return callback(performance.now());`

After downgrading to framer-motion 2.9.5, everything works fine again.
It may well be that the error also occurs with other frameworks using SSR like next.js?

**Steps to reproduce**
1. Install latest gatsby version.
2. Install framer-motion 3.x
3. run gatsby build

**Comment by mattgperry** [comment]
If you run `node -v` what do you get?

**Comment by mattgperry** [comment]
Also what's going on in `listOnTimeout` etc? I've tried to reproduce on a fresh Gatsby install but no dice.

**Comment by silviojaeger** [comment]
Thanks for your respond!

I'm running node version `15.9.0`

Looks like `listOnTimeout ` comes from the node module `framesync` which is is a dependecy of `framer-motion`.

**Comment by mattgperry** [comment]
I feel like this might mean you're running an animation on the server, maybe with `animate`, from a render function. I'm not sure, maybe something to keep an eye out for. In the meantime I've attempted to polyfill this in `3.6.4`, can you try that version and let me know if it works?

**Comment by silviojaeger** [comment]
Just tried with `3.6.4` and the build works fine again!
Thanks a lot for the support!

**Comment by jeanfortheweb** [comment]
Unfortunately, I'm having the same issue framer-motion version is ^4.1.17
