### ISSUE TITLE
[BUG] Drag contianer flashes on route change

### ISSUE THREAD

**Issue by guymunday** [framer/motion#978]
When navigating to a new page the drag element flashes back to "transform: none" and then quickly back to "transform: translate3d(x, y ,z)" when the new page is coming in, causing a flash. The draggable component shouldn't be unmounting as it's in the gatsby-browser. Am I missing something? Is there a way to prevent this flashing? 

here is a repo:
https://codesandbox.io/s/determined-glitter-f4g07?file=/src/components/DragNavigation.js

Steps to reproduce

Steps to reproduce the behaviour:

1. Drag the box to the centre of the the space.
2. Click on the link to the second page.
3. You can see the DragContainer flash before going back to where it's meant to be.

Expected behaviour:

The DragContainer shouldn't flash on the new page mounting.

**Comment by nattog** [comment]
@guymunday I have this too, on a Next.js build. Did you find a fix for this?

**Comment by guymunday** [comment]
@nattog I found a hacky work around where I set the animation delay on the flashing element to one hour. It wasn’t perfect but it fixed the flashing.

**Comment by mattgperry** [comment]
Feel free to reopen when this is verified
