### ISSUE TITLE
[BUG] Animation with css grid layout is squashing content and not synced properly

### ISSUE THREAD

**Issue by mshaaban0** [framer/motion#980]
## Description

I'm trying to build an animatable layout with css grid and framer motion, basically show and hide sidebar with subtle animation.

The issue is with orchestrating animation using `layout` prop and `AnimatedSharedLayout` when the animation happens the content container animates later, and squeezes its children elements

I'm not sure if I'm doing something wrong here, but please go ahead and have a look yourself...

https://codesandbox.io/s/framer-motion-css-grid-layout-4x0ug?file=/src/App.tsx

## How to reproduce
1. Go to [CodeSandBox](https://codesandbox.io/s/framer-motion-css-grid-layout-4x0ug?file=/src/App.tsx)
2. Click on 'Show Sidebar'
3. Notice the sidebar and content animation
4. Notice the 'Show Sidebar' button when animating

## Expected behaviour
Smooth, clear, synced animation :)

https://user-images.githubusercontent.com/6163988/108196218-22638280-7119-11eb-8de2-a4c989f35234.mov

**Comment by mattgperry** [comment]
That button should be a `motion.button layout` to counter-act the transform-induced scale deformation.

**Comment by mshaaban0** [comment]
oh, thanks, but that means I have to make all children `motion` components, unfortunately this is a UI component, children are defined by the consumer apps. Is there another way?

**Comment by mattgperry** [comment]
You could try adding a wrapper between the motion with layout and the children with a motion.div with layout=“position”?

**Comment by mshaaban0** [comment]
Awesome, that works, thanks. 

To sync transition timing between components, what's the best way to define it globally? passing the same transition values for both components doesn't seem to work

**Comment by mattgperry** [comment]
I'm gonna close this issue for now

**Comment by mshaaban0** [comment]
Thanks for helping 👍
