### ISSUE TITLE
[BUG] Filter blur glitch at the end of animation on Chromium

### ISSUE THREAD

**Issue by ArmedVeteran** [framer/motion#985]
**Describe the bug**

I'm animating a div, where it starts with filter: blur(10px) and animates to filter: blur(0px); (I also have opacity change, but that does not affect the problem). At the end of the animation div, together with it's content somewhat "jumps" or "twitches". 
That is the case on Chromium browsers (tested on Chrome and Edge). I've also checked it on Opera GX and the problem does not appear there, everything is smooth.
I've tried adding will-change: filter; and will-change: filter, opacity; to optimize it (together with -webkit equivalent), but nothing changed.

**CodeSandbox reproduction of the bug**

[CodeSandbox](https://codesandbox.io/s/framer-blur-bug-on-chromium-rrrzl)

**Steps to reproduce**

1. Go to the Sandbox from the link above
2. Wait for the animation to finish
3. Observe the text at the very end
If it's difficult to spot, then try setting duration to a longer time - the glitch will be visible even more.

**Expected behavior**

A smooth transition to fully clear, visible div with it's contents.

**Video or screenshots**

[Video](https://streamable.com/bhptcs)

**Environment details**

Google Chrome v.88.0.4324.182 (64-bit)

**Comment by mattgperry** [comment]
Have you tried the same animation with a CSS transition?

**Comment by ArmedVeteran** [comment]
> Have you tried the same animation with a CSS transition? I'm having trouble replicating on Chrome Mac

I haven't. I'll try to replicate it as soon as I can.

**Comment by mattgperry** [comment]
Managed to replicate with CSS: https://codesandbox.io/s/blur-bug-in-chromium-cr8c3?file=/src/App.js

Probably worth filing this with the Chromium team. Seems to be a problem for very low blur radius.
