### ISSUE TITLE
Using x transition causes mobile screen size issue

### ISSUE THREAD

**Issue by stevencmh** [framer/motion#987]
When using x: -200 to x: 0 for example, and the element moves onto screen and causes the page to shink and then expand again on mobile for a split second.

**Comment by jpamarohorta** [comment]
I'm having the same issue

**Comment by mattgperry** [comment]
When elements are positioned offscreen they need to be culled somehow, for instance a wrapper with overflow:hidden. This is true for all CSS transforms rather than a Motion bug
