### ISSUE TITLE
Transitions only fire on page load and first click

### ISSUE THREAD

**Issue by stevencmh** [framer/motion#988]
I have pretty basic set up: pageInitial, pageAnimate, and pageExit on _app.js, and hidden and visible transitions on a couple of components to transition a title and intro.

All works fine on page load and on the first click to navigate away. However any other page clicks and it doesn't fire.

Do I need to add any further configuration?

Thanks!

**Comment by mattgperry** [comment]
Closing now but feel free to reopen with a sandbox reproduction.

**Comment by stevencmh** [comment]
All sorted now! My use of the key was the issue. I was using:
    <AnimatePresence key={router.route} >
…working now instead with:
<AnimatePresence key={router.asPath} >
