### ISSUE TITLE
[BUG] onTapCancel does not fire on iOS

### ISSUE THREAD

**Issue by dminkovsky** [framer/motion#993]
Like #917: when you pointerdown, move, and and then pointerup outside the element, `onTap` fires instead of `onTapCancel`. Please see https://codesandbox.io/s/inspiring-lake-4tvqz?file=/src/App.tsx.

**Comment by mattgperry** [comment]
I've been looking into this and was surprised to learn that the target of a `touchend`/ touch `pointerend` is always the same as the initiating event: https://www.w3.org/TR/touch-events/#the-touchend-event

This makes it quite difficult to detect a cancel in the event of a `touchout`-style event. I'm marking this as a wontfix for now but would accept a simple PR to fix this if anyone has any ideas.

**Comment by dminkovsky** [comment]
Thank you @mattgperry. Have you considered dropping Touch Events, given that Pointer Events seem quite [well supported](https://caniuse.com/pointer) now.

**Comment by mattgperry** [comment]
They’re not well supported enough for a library like this to remove touch
events but we do have detection that uses pointer events where available.
I’ll double check these are being chosen correctly but I know sometimes
pointer events behave like touches when they’re touches
