### ISSUE TITLE
[BUG] Layout only animates from 0 => value not value => 0

### ISSUE THREAD

**Issue by ortonomy** [framer/motion#994]
**1. Read the [FAQs](#faqs) 👇**

OK

**2. Describe the bug**

When using with styled components to dynamically set the width and using the `layout` prop, the layout is only animated for one direction of the change.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-layout-width-bug-2mrc4

**4. Steps to reproduce**

1. go to sandbox
2. click bar
3. click bar again
4. repeat ad nauseum

**5. Expected behavior**

The layout animation occurs, for value => 0 AND 0 => value

**6. Video or screenshots**

![framer-motion-bug](https://user-images.githubusercontent.com/6688676/108581072-75337900-7369-11eb-8fba-dbd6aa8fbebf.gif)

**7. Environment details**

MacOS Big Sur latest, Chrome latest

**Comment by mattgperry** [comment]
There's a fundamental problem here in that layout animations are performed using transforms. The new layout is 0, so this can't be transformed to scale up to look like the previous button. You're probably better using `scale` to perform this animation.
